### ISSUE TITLE
Add a site version API

### ISSUE THREAD

**Issue by PorkrollPosadist** [LemmyNet/lemmy#1001]
### Is your proposal related to a problem?

In a perfect world, API changes would never require special handling, but in practice there will likely be many different versions of Lemmy installed and operating on the Fediverse.  Additionally, there will likely be a variety of third party clients used to connect to these instances.  In order for clients to support as many instances as possible, it would be helpful if Lemmy provided a standardized API for clients and peer instances to request the site version, client-server API version, server-server API version, and perhaps other information about installed extensions.

### Describe the solution you'd like

The Matrix protocol includes [a fairly extensible version API](https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-versions) which remains pretty simple to implement - especially if you are only trying to support one version in your implementation (as the Lemmy server likely will for some time). None the less, it allows for clients and servers which support multiple API implementations to choose an appropriate version, or enable/disable features as appropriate.

Additionally, it might be nice to have an optional `extensions` key included in this response. An array of strings to indicate extra features supported by the instance. These may include captcha protected logins, custom emoji sets, additional contact/info fields for the user page, or anything the Lemmy community can think up, really.

### Describe alternatives you've considered

* Never change the API /s

* Include version info in the SiteView structure which is already transmitted (though this requires SiteView to maintain backwards compatibility)

**Comment by dessalines** [comment]
This adds version to GetSite:

#### Get Site
##### Request
```rust
{
  op: "GetSite"
}
```
##### Response
```rust
{
  op: "GetSite",
  data: {
    site: Option<SiteView>,
    admins: Vec<UserView>,
    banned: Vec<UserView>,
    online: usize,
    version: String,
  }
}
```
##### HTTP

`GET /site`
