### ISSUE TITLE
Allow changing of names

### ISSUE THREAD

**Issue by Scaledi** [LemmyNet/lemmy#1006]
### Is your proposal related to a problem?

No
### Describe the solution you'd like

Allow changing of names, perhaps once every 3 months

**Comment by dessalines** [comment]
What does this mean? Changing of user names? That would break your federation urls. Why not just make a new acct if this is for security reasons, it takes a few seconds.

**Comment by Scaledi** [comment]
Yes, changing of usernames. My reasoning for this is then your posts can carry over. People grow out of names, but identity’s rarely change. Maybe add a warning: this will break your url?

Yall are using uuids right?

**Comment by Nutomic** [comment]
Not going to happen, it would be way too complicated to make this work with federation. Mastodon and other ActivityPub software also doesnt allow it for the same reason.
