### ISSUE TITLE
Impossible to build Lemmy from scratch as git.asonix.dog is down

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1012]
Lemmy loads the activitystreams-new and activitystreams-ext dependencies directly from git.asonix.dog. As that server is currently down, its now impossible to build from scratch.

@asonix This seems to be the only way to reach you, as your Matrix, Mastodon and Email are all down. Could you mirror your libraries somewhere else for the time being, or send the source to us so we can take care of it?

**Comment by Scaledi** [comment]
oh no. this is worrying, as his last contribution was a month ago.

**Comment by asonix** [comment]
I still exist, my stuff is just down because moving hassle. It'll likely be down through the end of the week, so I'll email some code to you @Nutomic

**Comment by Scaledi** [comment]
> 
> 
> I still exist, my stuff is just down because moving hassle. It'll likely be down through the end of the week, so I'll email some code to you @Nutomic

Oh awesome! we are saved!

**Comment by asonix** [comment]
Better idea:
- https://yerbamate.dev/asonix/activitystreams-new
- https://yerbamate.dev/asonix/activitystreams-ext

**Comment by igalic** [comment]
how about releasing the stuff to creates.io?

**Comment by dessalines** [comment]
@asonix it looks like `activitystreams-ext` has this in its dependencies:

```
[dependencies]
activitystreams-new = { git = "https://git.asonix.dog/asonix/activitystreams-sketch", branch = "main" }
```

Could you update this to the yerba one and push to yerbamate?

`activitystreams-new = { git = "https://yerbamate.dev/asonix/activitystreams-sketch", branch = "main" }`

**Comment by asonix** [comment]
it is done

**Comment by Nutomic** [comment]
Okay downloading the deps works now, but it looks like you uploaded an older version. The method `NoteType::Note.to_string()` is not found (and same for other types).

**Comment by asonix** [comment]
gah, i fixed those on my laptop after I had packed my desktop up. I'll go ahead and get those changes pushed too once I dig my laptop up

**Comment by Nutomic** [comment]
That to_string() is the only thing missing, so you could also code it again from scratch if its easier (and you dont fear conflicts with the original repo).

Anyway, thanks for the fast help, and I hope the move is going well :)

**Comment by asonix** [comment]
it's pushed now

**Comment by Nutomic** [comment]
@asonix Any idea when your Gitea will be up again? I need to look up how you handled the activity types in the inbox of ap-relay.

https://yerbamate.dev/LemmyNet/lemmy/pulls/72

**Comment by asonix** [comment]
@Nutomic it's up now, although pretty slow
- https://git.asonix.dog/asonix/ap-relay/src/branch/main/src/apub.rs
- https://git.asonix.dog/asonix/ap-relay/src/branch/main/src/routes/inbox.rs

**Comment by dessalines** [comment]
You could also push to both with a single `git push` too: https://stackoverflow.com/a/14290145/1655478 , I push all my changes to at least a few locations.

**Comment by Nutomic** [comment]
@asonix Thanks! It looks like you are basically converting back and forth between Activity and AnyBase a few times to handle the different types. Isnt that pretty bad for performance? Well I dont mind as long as it works.

**Comment by asonix** [comment]
@Nutomic converting to or from `AnyBase` should be slightly cheaper than converting to or from `serde_json::Value`, which is what BaseBox was in the previous version.
