### ISSUE TITLE
Proposals from downstream devs for balancing the influence of downvotes

### ISSUE THREAD

**Issue by kolgza** [LemmyNet/lemmy#1014]
# Introduction
This issue consists of a write up of a Discord conversation from downstream Lemmy contributors. The goal of the conversation was to devise a scoring/sorting system which:
- Encourages active conversation
- Discourages group-think
- Avoids excessive self-validation
- Is not susceptible to spam

# The Debate About Downvotes

[Tildes uses the following as justification for the complete removal of downvotes:](https://docs.tildes.net/philosophy/site-design#lack-of-downvoting)

> The ideal usage of a downvote is a generic way to express "this doesn't contribute", but in practice they tend to be used more as "I disagree" or "I don't like this". High-quality posts will often get downvoted because other users disagree with the opinion, and in taste-based communities (such as ones related to music), entire categories of valid posts might not be viable because they'll just be downvoted by users with different tastes.

Meanwhile, the following proposed hypothetical shows how the inclusion or exclusion of downvotes has a meaningful effect on scores with neither solution being obviously better:

> Say you have three comments:
>
> Description of comment | Upvotes | Downvotes | Score With Downvotes | Score Without Downvotes
> ----- | ----- | ----- | ----- | -----
> Constructive, people generally appreciate it | 20 | 2 | 18 | 20
> Divisive, pits two groups against each other | 21 | 20 | 1 | 21
> Unengaging, low-effort, but innocuous | 2 | 0 | 2 | 2
>
> With downvotes, the unengaging comment scores higher than the divisive comment. Without downvotes, the divisive comment scores higher than the generally well-liked comment.

Many (including myself) will argue that downvotes serve an important role: community self-moderation. Arguably, by completely removing downvotes, you are limiting the community's ability to deal with spam, trolling, low-effort posts, and the like.

# Potential Changes

## Weighing downvotes differently from upvotes

This is a solution I've previously came up with in the past: having different weights for upvotes and downvotes. I see this as a good compromise between having upvotes, and not having upvotes. This would involve changing using the following equation to calculate score:

```
Score = ceil(Upvotes - (0.5 * Downvotes))
```

This is how the results of the aforementioned hypothetical would change:

Description of comment | Upvotes | Downvotes | Score 
----- | ----- | ----- | ----- 
Cool comment, people generally like it | 20 | 2 | 19
Divisive, pits two groups against each other | 21 | 20 | 11
Unengaging, low-effort, but innocuous | 2 | 0 | 2

## Setting a minimum score

Many forums and link aggregators, such as Slashdot and HackerNews, set a minimum possible score for posts and comments. In other words, posts can't be downvoted past a certain point. The rationale for this might be to prevent posts and comments from being downvoted to a point that users willing to upvote them would not be able to discover them. 

Some have also suggested that this could potentially be used to trigger automated actions, such as hiding a post or alerting a moderator.

## Requiring karma for downvoting

I highly disagree with this approach, but it was brought up in the conversation. Basically, some forums, such as HackerNews and Voat, require users to have a certain amount of karma before they are allowed  to downvote posts.

## Obfuscation of the exact number of downvotes

Some have discussed whether displaying the exact number of downvotes on a post would give those who later read the post a preconceived bias, leading to a sort of hive mind. Such would be a user not upvoting a post or comment that they like, because it was already downvoted. In practice, this would involve replacing the counter for upvotes and downvotes with a percentage, or another vague metric such as a "health bar" or "heat scale." 

There is also a question on whether the exact number of downvotes should be shown *after a specific condition is meant* (such as after a period of time). Reddit, for instance, completely hides all indication of score for new posts and comments. As one person puts it: "The most important experience that I think needs to translate is what happens when a rating is surprising. If I think something was a good take but it was downvoted to hell or vice-versa, it makes me curious."

Vote fuzzing was also briefly mentioned.

## Emoji Reacts and "Tags"

Some users have expressed the desire to be able to specify a reason for upvoting or downvoting posts. They referred to this as "tags," where in that users can tag posts as funny, insightful. overrated, underrated, inflammatory, etc.
![image](https://user-images.githubusercontent.com/46303203/88219058-035a4c00-cc2f-11ea-9487-b17cecc3f280.png)

Other users have discussed the idea of Discord-style emoji reactions, that have no bearing on score.
![image](https://user-images.githubusercontent.com/46303203/88219032-f3db0300-cc2e-11ea-9a2a-859db8aa5595.png)

**Comment by dessalines** [comment]
Why should downvotes not have the same weight as upvotes, exactly?

> The ideal usage of a downvote is a generic way to express "this doesn't contribute", but in practice they tend to be used more as "I disagree" or "I don't like this". High-quality posts will often get downvoted because other users disagree with the opinion, and in taste-based communities (such as ones related to music), entire categories of valid posts might not be viable because they'll just be downvoted by users with different tastes.

I deeply disagree with this. Why should "I disagree", be worth less than "I Agree"? 

> Requiring karma for downvoting

Absolutely not. Lemmy will never have any reputation-based system, where abilities are granted based on reputation. That would lead to stackoverflow pretty quickly. 

> Score = ceil(Upvotes - (0.5 * Downvotes))

Where did you come up with `0.5` ? Why not `0.1`?

BTW [here's the current ranking algorithm](https://dev.lemmy.ml/docs/about_ranking.html). Reddit's tooks years of analysis to figure out what's wrong with it... that hasn't been done here.

**Comment by kolgza** [comment]
*I'll reiterate again that most of these ideas aren't mine. This is a write up of a conversation among downstream developers. Personally, I disagree with most of them.*

> Why should downvotes not have the same weight as upvotes, exactly?

This question I can answer. Basically, the existence of downvotes has issues, but the lack of downvotes has different issues. This is an attempt at mitigating both.

> Where did you come up with `0.5` ? Why not `0.1`?

I suppose it would make more sense to have this instead be a configurable value (call it `Weight`) to replace the binary choice of either having, or not having, downvotes.

Believe it or not, `0.5` isn't an arbitrary number. It's average between downvotes being enabled, (`Weight = 1`), and downvotes being disabled (`Weight = 0`).

**Comment by kolgza** [comment]
It also occurred to me that I should not have marked this as a feature request, because it did not actually request any specific features. I know this was already closed, but it still bothers me (admittedly, much more than it should). :grimacing: 

If wouldn't be a bother, would you or nutomic mind removing the "enhancement" label and adding a "discussion" label? I'm sorry if I'm being a burden, by the way.

**Comment by dessalines** [comment]
You're good, yes this is kind of a question thing, I apologize for being too harsh here, there are just two ppl working on this project and we're swamped with requests. I'll re-open and tag as discussion.

**Comment by kolgza** [comment]
Thanks.

I'd like to ask, though, of what you think of the idea of weighing downvotes differently. I see it as a good compromise between fully enabling and fully disabling downvotes. However I could conceive of someone writing a long explanation of why it would actually be the worst of both worlds.

**Comment by dessalines** [comment]
I disagree with all the initial premises that a like is somehow fundamentally different (and should be worth less for some reason?) from a dislike. Downvotes don't "encourage groupthink" any more than a like does; they discourage conversation people don't want to see (just as a downvote on a post in practice means you don't like seeing it), just as an upvote encourages conversations you think people should see. Both are great to have, and none should be worth more than the other. Any "weighting of upvotes more than downvotes", or vice versa, is completely arbitrary.

Most of these proposals pretty quickly get to the point of, well why not just get rid of voting altogether to stop all groupthink? Usually from people who forget the nightmare wild west of unmoderated, unranked forums that quickly get filled with unsorted trash.

People expressing preference is good, if anything they should more preference options. I don't want lemmy to become like a lot of the bigger social media giants who already have eliminated dislike / downvote, because they want to shield all users from criticism. 

Mostly, what's lacking is empirical data showing why lemmy's ranking algorithm is flawed. Reddits took years of big data analysis to figure out why it was terrible, that work hasn't been done here, at all.
