### ISSUE TITLE
Remove  `/u/` and `/c/` schemes from UI

### ISSUE THREAD

**Issue by kolgza** [LemmyNet/lemmy#1016]
> I don't want to use `/u/` or `/c/` in the UI really at all, only for urls.

Currently, Lemmy still uses this scheme both in the page titles for communities, and in the user pages:

![Screenshot from 2020-07-23 14-52-36](https://user-images.githubusercontent.com/46303203/88326570-31559400-ccf4-11ea-97f4-11c8b01a802a.png)
![image](https://user-images.githubusercontent.com/46303203/88326682-4b8f7200-ccf4-11ea-91e8-e565127385d2.png)

_Originally posted by @kolgza in https://github.com/LemmyNet/lemmy/issues/991#issuecomment-663175023_

**Comment by Axighi** [comment]
I'll fix this.

**Comment by kolgza** [comment]
Make sure to change them `!community` and `@user` instead of just removing them.

**Comment by Axighi** [comment]
#1034 Fixed in this pr.
