### ISSUE TITLE
Federate sticky posts

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1018]
We add a new boolean field `stickied` to `GroupExtension` (working in the same way as the `sensitive` field). 

Then we create an outbox collection for the community, and fetch that when initially following a remote community. The outbox only contains the first page of "popular" posts (including sticky posts). This ensures that newly following instances see some content, and especially the sticky posts (which might not be federated otherwise). We dont bother with pagination or any kind of consistency for the outbox though, that would be too complicated.

**Comment by vpzomtrrfrt** [comment]
I would suggest using `featured` instead to match Mastodon

**Comment by Nutomic** [comment]
Compatibility with Mastodon is not a goal for us now, and anyway there are lots of other things we will have to change to federate with Mastodon. That might be something for later, but for now we are just focusing on federation between Lemmy instances, and nothing else.

**Comment by Nutomic** [comment]
Implemented in https://yerbamate.dev/LemmyNet/lemmy/pulls/74
