### ISSUE TITLE
issue when threading by new

### ISSUE THREAD

**Issue by ProtoChoco** [LemmyNet/lemmy#1024]
### Issue Summary

When sorting comments by new under a lemmy post, replies to a comment get pushed to the top, losing the original context they were created in and making the thread difficult to follow.

### Steps to Reproduce

1. Go to a popular lemmy post with a lot of comments and replies
2. change sort by from 'hot' to 'new'

**Comment by dessalines** [comment]
What's the issue here? Its correctly re-sorting by new, so the newest replies should be at the top.

**Comment by ProtoChoco** [comment]
Idk this might be a personal preference thing but when I see a reply above a thread and have no way of linking that post to a specific thread it loses all the context.

I think it would be better if it displayed a chronological order of threads and a chronological order of replies to that thread

**Comment by dessalines** [comment]
Ohhh okay you're not hittng the new button, you're hitting the `chat` button. Yes you will lose context if you do that, it does all the comments flat by most recent.
