### ISSUE TITLE
APUB permissions / security checks.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1040]
- [ ] Write unit tests to fail first.
- [x] Check the actor and community id on incoming recieves against the allowlist / blocklist.
- [ ] Make sure all the API permissions checks are abstracted, then also used by the APUB receives.
- [x] Make sure `remote_fetch_or_insert` ones do allowlist and blocklist checks.

**Comment by Axighi** [comment]
Do you need extra hands here? @dessalines

**Comment by dessalines** [comment]
Thanks @Axighi! Probably not on this one, mainly because me and @Nutomic still have to create a list of security checks which we need to write tests for (that should fail before and pass after the checks are done). Plus I just did a huge test refactor so its fresh in my mind.

Are you wanting to do back-end, or front end, or both? We can figure out some good first issues to tackle.

btw if you aren't already, join our [lemmy-dev chat on matrix](https://matrix.to/#/!tUnhsBRCsiePXfsIGe:matrix.org?via=matrix.org&via=privacytools.io&via=asonix.dog)

**Comment by Axighi** [comment]
I do back end.

**Comment by Nutomic** [comment]
Okay here we go. I believe few or even none of these activities can be sent by Lemmy itself, so you will have to send it as raw text directly to the Lemmy inbox. 

- [ ] activity without any http signature
- [ ] activity with http signature signed by a different private key
- [ ] activity where ID and actor ID are from different domains
- [ ] activity that uses an `http://` ID in production mode
- [ ] activity from a domain that is not in the allowlist
- [ ] remove activity sent by someone who is not an admin/mod on the community's instance
- [ ] sticky/lock activity by someone who is not an admin/mod on the community's instance
- [ ] delete activity sent by someone who is not the creator of that community/post/comment
- [ ] update activity by someone other than the creator of that post/comment
- [ ] undo activity where the actor is different from the actor of the activity that should be undone
- [ ] activity destined for a community which lives on a different instance
- [ ] activity which attempts to comment on a locked post
- [ ] post/comment activity which contains slurs in the title/text
- [ ] post in a community that doesnt exist
- [ ] comment on a post that doesnt exist
- [ ] activity from a user that doesnt exist under the given ID
- [ ] multiple like/dislike sent by the same actor
- [ ] announce received from a community that we dont follow
- [ ] activity type received that we dont support
- [ ] activity sent by a user which is banned on the local instance (not sure if we are actually doing federated bans now)

**Comment by dessalines** [comment]
I'll start adding these in the `apub_security_checks` branch.

**Comment by Nutomic** [comment]
@dessalines I think we can close this issue, unless you have plans to add more test cases mentioned here.

**Comment by dessalines** [comment]
Nah this is good.
