### ISSUE TITLE
Browser default language after login doesn't work

### ISSUE THREAD

**Issue by ernestwisniewski** [LemmyNet/lemmy#1041]
### Issue Summary

Browser default language after login doesn't work

### Steps to Reproduce

1. Language is correct when you view the site as a guest
2. Log in (browser must be set to a language other than en)
3. If browser language is set in the profile, it is always English
4. If you change the language and save the profile, it displays correctly

### Technical details

ui/src/i18next.ts - after logged in (when the "browser" lang is set in the database), fallbackLng is always triggered. I think the bug occurred after the last merge.

**Comment by dessalines** [comment]
Version at the bottom? I'm pretty sure I fixed this in `v0.7.33`. 

Navbar Line 438 should change your i18n language to that saved in your user settings.

**Comment by dessalines** [comment]
Ohhh I think I understand the problem, its when you're using the browser default language. Let me test.

**Comment by dessalines** [comment]
Okay ya I confirmed the bug, fix should be out soon.
