### ISSUE TITLE
Hide deleted comments from the user profile

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#1053]
### Is your proposal related to a problem?

Having a bunch of "comment deleted" placeholders in a user profile can be distracting, and it also kind of goes against the user's wishes by deleting the content. Also, Lemmy already hides deleted posts so why not deleted comments?

### Describe the solution you'd like

I suggest not showing any deleted comments (or rather, deleted comment placeholders) on a user's profile.

**Comment by kartikynwa** [comment]
@Nutomic Is there still interest in this?

**Comment by Nutomic** [comment]
@kartikynwa Yes of course. If you need any help to implement it, feel free to ask here.

**Comment by kartikynwa** [comment]
@Nutomic 

I am thinking:

In `crates/api_common/src/person.rs` , modify `GetPersonDetails` and add ` pub show_deleted_and_removed: Option<bool>`.

In `crates/db_views/src/comment_view.rs`, modify `CommentQuery`  and add `show_deleted_and_removed: Option<bool>`. In the `list` function, filter `query` by `deleted=FALSE AND removed=FALSE` if `show_deleted_and_removed` is `Some(false)`.

In `crates/api_crud/src/user/read.rs`, add `..show_deleted_and_removed(data.show_deleted_and_removed)` to the `CommentQuery::builder()` call.

Anything else that I am missing?

**Comment by dessalines** [comment]
@kartikynwa That seems correct to me. Let me know in the  [lemmydev matrix chat](https://matrix.to/#/!tUnhsBRCsiePXfsIGe:matrix.org) if you need any help.
