### ISSUE TITLE
Duplicate dependencies

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1054]
I noticed that we have lots of cases where the same crate is required multiple times, just in different versions. You can check with `cargo tree -d`. For example, almost everything uses serde v1.0.114, but `config` pulls in serde v0.8.23. Making sure that we only use a single version for each dependency should give a moderate improvement to compilation time. But this will require some manual work, namely going to upstream crates and updating their dependencies.

**Comment by dessalines** [comment]
Daaang its a lot. If it were just a few I'd say it'd probably be worth it, but its so many, and obvi it would constantly change too as dependent libraries keep getting updated.

Libraries really need to start running `cargo outdated` more often.

**Comment by Nutomic** [comment]
This looks much better now that we dont depend on different serde versions anymore, thanks to removing config-rs. Most remaining duplicates look like rather small libraries. And there is not much we can do here, other than updating our dependencies, and hoping that transitive dependencies get upgraded.
