### ISSUE TITLE
Community count posts bug

### ISSUE THREAD

**Issue by ernestwisniewski** [LemmyNet/lemmy#1060]
The post count in the community info section is lower than it actually is.

https://dev.lemmy.ml/c/c_programming/data_type/post/sort/topall/page/1 > Post
https://dev.lemmy.ml/c/firefox/data_type/post/sort/topall/page/1 > 16 Posts
https://dev.lemmy.ml/c/diy > 2 Posts

**Comment by dessalines** [comment]
Fixed by that commit.
