### ISSUE TITLE
Federated moderation.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1061]
- [x] represent mods as `OrderedCollection`, instead of using `attributedTo` field
- [x] implement activities Add/Remove for mods
    - sent by existing mod to community
    - `object` is another user, `target` is the community's mod collection
    - announced to community followers if valid
- [x] accept mod activites from any user in the mods collection
    - announce them, as `Announce/Remove/Post`, `Announce/Undo/Remove/Post` etc
    - apply them to the local database
- [ ] ~~wrap community activities (`Update/Community`, `Remove/Community` etc) in announce, so they can be done by remote mods~~
- [x] implement federated user bans (#1298)
    - can also be done by remote mods
- [ ] write test case(s) for federated moderation?

**Comment by Nutomic** [comment]
> the most tricky part would be letting the remote user know that they were added/removed as mod
> so either via a new activity, or by ensuring that mods are correctly federated as part of the community json
> and then the community inbox just needs to allow Remove and Undo/Remove activities from these remote mods
> the activitystreams vocab we could potentially use are: Add, Remove, Invite, Join, and Leave . Prolly just Add IMO, and maybe it re-fetches the community json which has the modlist.

**Comment by Nutomic** [comment]
Rewrote the issue text.

**Comment by Nutomic** [comment]
WIP at [yerbamate.ml/LemmyNet/lemmy/pulls/185](https://yerbamate.ml/LemmyNet/lemmy/pulls/185).

**Comment by dessalines** [comment]
@Nutomic this is merged now, you want to keep this open to track issues w/ it, or open up new ones?

**Comment by Nutomic** [comment]
Lets keep it open cause its not finished yet.

**Comment by Nutomic** [comment]
This is finished now
