### ISSUE TITLE
If you want to help with translating, take a look at Weblate.

### ISSUE THREAD

**Issue by 7942app** [LemmyNet/lemmy#1068]
What's the question you have about lemmy?

Email confirmation is not sent when registering as a member.
The Report Registration Problem button is also broken.

I want to translate Korean.

**Comment by dessalines** [comment]
> Email confirmation is not sent when registering as a member.

We don't send email confirmations.

>  The Report Registration Problem button is also broken.

This is a feature on chapo.chat that's not in lemmy yet.

> I want to translate Korean.

https://weblate.yerbamate.dev/
