### ISSUE TITLE
Add a user setting to hide read posts.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1072]
Have an option to hide read posts. We currently have a `post_read` table that's not being used.

**Comment by aproposnix** [comment]
I assume this will be an opt-in feature. Is that correct? Otherwise, it might be a pain in the butt to find threads you are trying to follow, so there would have to be a "do not hide" option on every post (Nextcloud news app does this).

**Comment by dessalines** [comment]
Yep, off by default.
