### ISSUE TITLE
Cross-posting changes the URL of the original post in the form

### ISSUE THREAD

**Issue by kartikynwa** [LemmyNet/lemmy#1083]
### Issue Summary

When attempting to cross-post, the URL of the post is changed in the form.

This does not happen with all kinds of URLs.

Maybe it has something to do with the `#` in the URL.

### Steps to Reproduce

1. Go to https://dev.lemmy.ml/post/38946
2. Try to cross-post.
3. The link in the post will be changed to https://simplevote.tk

**Comment by dessalines** [comment]
I see why, its because my create post isn't doing a proper url encode / decode (necessary here because of the `#` param:

 `create_post?title=[Poll] Which shell do you use?url=https://simplevote.tk/#/poll/68nQ&body=You can add options if what you use isn't there. :)`
