### ISSUE TITLE
problem with the translation site sign-up process

### ISSUE THREAD

**Issue by 7942app** [LemmyNet/lemmy#1085]
problem with checking send email.

**Comment by dessalines** [comment]
What?

**Comment by 7942app** [comment]
The site sends a confirmation email to your personal email during the membership registration process.
However, the confirmation email does not arrive.
https://weblate.yerbamate.dev/accounts/register/

**Comment by Nutomic** [comment]
I dont think I have email sending configured for weblate. You should be able to login right away.

**Comment by 7942app** [comment]
> I dont think I have email sending configured for weblate. You should be able to login right away.

Tried for a few days but can't sign up.
When I click the error report button (complete report form), an error screen appears.

![2020-08-15 091224](https://user-images.githubusercontent.com/47238549/90300856-7a55ce00-ded7-11ea-8e04-8e29d3320b7d.png)

**Comment by Nutomic** [comment]
What is your username there?

**Comment by olleapp** [comment]
> What is your username there?

My ID is olleapp

**Comment by Nutomic** [comment]
There is no account with that name. I guess your registration just didnt finish successfully. Could you try again to sign up?

**Comment by 7942app** [comment]
> There is no account with that name. I guess your registration just didnt finish successfully. Could you try again to sign up?

The reason my ID was not retrieved is because the email did not arrive and the sign-up was not completed.

**Comment by dessalines** [comment]
I don't know if weblate updated or something, but it needs email configured because you don't provide a password when you register now.

**Comment by 7942app** [comment]
I've just checked. And the membership registration process has also been completed. And we are preparing a Korean translation. Thank you.
I saw the following message.
A new translation request has been sent to the project manager.

**Comment by dessalines** [comment]
@7942app okay this is added now : https://weblate.yerbamate.dev/languages/ko/lemmy/

**Comment by 7942app** [comment]
It is being translated now. Thanks for any help.
