### ISSUE TITLE
Password Bug

### ISSUE THREAD

**Issue by Azkulbel** [LemmyNet/lemmy#1087]
### Issue Summary

I use password manager and I am able to register just fine with using 100+ characters including even special one , but once I log out and try to log back in , I got a message saying wrong password. I created 3 accounts and everytime i made my password shorter and stopped to use special  characters. Last password that did not work was 74 character long password with small and capital letters + numbers .  After reseting and using 40 characters long password I do not have that issue anymore.

**Comment by dessalines** [comment]
I see this in the bcrypt code: 

```
    // We only consider the first 72 chars; truncate if necessary.
    // `bcrypt` below will panic if len > 72
```
