### ISSUE TITLE
Create private message not closing on send

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1095]
@Nutomic so we introduced a glitch in production that's causing the websocket sends on create private message to fail. (The message actually goes through, but the recipient and sender don't receive it live, and we get an infinite spinner). 

The issue is here : https://github.com/LemmyNet/lemmy/blob/main/server/src/apub/mod.rs#L107

It currently gets a panic or error with the message : 

```
lemmy_1     | [2020-08-18T01:41:14Z ERROR lemmy_server::websocket::server] Error during message handling Invalid config, both allowed_instances and blocked_instances are specified, or both are empty
```

If I change that panic to `Ok(())` , I get a different error:

```
lemmy_1     | [2020-08-18T01:55:32Z DEBUG rustls::client::hs] No cached session for DNSNameRef("localhost")
lemmy_1     | [2020-08-18T01:55:32Z DEBUG rustls::client::hs] Not resuming any session
lemmy_1     | [2020-08-18T01:55:32Z ERROR lemmy_server::websocket::server] Error during message handling Error sending request, Failed to connect to host: received corrupt message
```

So there are two issues here:-
1. It shouldn't be trying to send something to a local instance. 
1. If the apub sends fail, it probably shouldn't fail the entire API call.
1. We have `Settings.federation.enabled = false`, yet its still trying to send apub messages. (Which it shouldn't at all)

I'm not sure how do solve 1) (you might know better), but as far as 2 and 3, I could either wrap every one of these sends:

```rust
    if Settings::get().federation.enabled {
    updated_private_message
      .send_create(&user, &client, pool)
      .await?;
   }
```

Or do a soft fail:

```
    updated_private_message
      .send_create(&user, &client, pool)
      .await.ok();
   }
```

Wrapping all of the sends by checking for federation enabled is something we probably already should've done. I can do this, I just want to check with you to make sure you agree.

The 2nd solution (soft failing) is something we can deal with once the apub_actor_send stuff is done.

**Comment by Nutomic** [comment]
You are right, it definitely shouldnt attempt to do any apub sends in that case. I think the easiest solution would be to add a conditional here, and simply do nothing if federation is disabled. In that case Lemmy would still do some work to generate activities and insert them into the database, but I think thats acceptable.

https://github.com/LemmyNet/lemmy/blob/main/server/src/apub/activities.rs#L47

As for `check_is_apub_id_valid()`, we need to add a check along these lines:
```
if !Settings::get().federation.enabled && domain == local_instance {
  return Ok(())
}
```

I will test and make a PR if that helps.
