### ISSUE TITLE
A Tag For Violent And Gore Post

### ISSUE THREAD

**Issue by MaddRaccoon** [LemmyNet/lemmy#1099]
A tag similar to the NSFW one but for Gore and Violent stuff to improve the ''quality of life'' on Lemmy, this feature is one that is also asked for on Reddit

**Comment by eiknat** [comment]
might be good to consider the content warning system mastodon has?

**Comment by dessalines** [comment]
IMO we shouldn't break out multiple NSFW / content warning settings (especially since we only have one federation field for that). We could just rename the NSFW one to Content Warning or something on the front end.
