### ISSUE TITLE
Usernames check should be case insensative when logging in

### ISSUE THREAD

**Issue by Lambdanaut** [LemmyNet/lemmy#1102]
When logging in, "Lambdanaut" != "lambdanaut". I believe that either one of these should log-in as the same user, and it shouldn't throw an "Account not found" error when you don't login with the "correct" case.

**Comment by Lambdanaut** [comment]
@dessalines I'd like to give fixing this a try. Will report back within the week on progress.

**Comment by Nutomic** [comment]
Great, let us know if you need any help.

**Comment by Lambdanaut** [comment]
Closed out in https://github.com/LemmyNet/lemmy/pull/1107
