### ISSUE TITLE
Broken URL search.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1104]
I'm noticing this one isn't finding the previous post, which has the same url: 

- https://lemmygrad.ml/post/7615
- https://lemmygrad.ml/post/7571

**Comment by Nutomic** [comment]
Seems to work fine now.

![Screenshot_20210122_142622](https://user-images.githubusercontent.com/1044450/105496483-6fd50700-5cb5-11eb-8e41-1263ee8133e5.jpg)
