### ISSUE TITLE
Filter for unanswered questions/posts

### ISSUE THREAD

**Issue by Cam-B** [LemmyNet/lemmy#1106]
For those who use a community as a questions/answers type forum it would be great to have the option to filter/search communities for posts that don't have any comments yet. or posts that haven't been closed with an "accepted answer" yet.

**Comment by dessalines** [comment]
I don't think I'd want to add an "accepted answer" feature (half of the time they're useless on stackoverflow anyway, the accepted answer will have 10 votes, and the best one will have hundreds).

But yes adding a filter for posts with no comments would be helpful.

**Comment by Cam-B** [comment]
> I don't think I'd want to add an "accepted answer" feature (half of the time they're useless on stackoverflow anyway, the accepted answer will have 10 votes, and the best one will have hundreds).

I agree with that completely :)

**Comment by dullbananas** [comment]
When #317 is implemented, this could be done by adding an "answered" tag for posts
