### ISSUE TITLE
Duplicate .save string

### ISSUE THREAD

**Issue by 7942app** [LemmyNet/lemmy#1117]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Duplicate .save string
![2020-09-05 003734](https://user-images.githubusercontent.com/47238549/92258040-2efc7180-ef11-11ea-9559-ba32a056ab3f.png)

### Steps to Reproduce
1. The post save button and user settings save button have the same string.

### Technical details
In my opinion, need to separate the storage string.( ex settings_save)

**Comment by dessalines** [comment]
We have repeated strings all over the site, this is a good thing. No one should have to translate the same string twice. The context for both Saves is pretty clear.
