### ISSUE TITLE
Failed to load some stylesheets

### ISSUE THREAD

**Issue by smnthermes** [LemmyNet/lemmy#1127]
### Issue Summary

Some stylesheets fail to load on Pale Moon and Waterfox Classic, due to using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), but not providing a fallback theme.

### Steps to Reproduce

1. Visit dev.lemmy.ml, without logging in.

**Comment by dessalines** [comment]
The front end of lemmy will be moving to https://github.com/lemmynet/lemmy-isomorphic-ui soon. That shouldn't be a problem there, but also, I suggest using a browser that supports css unloading, which lemmy needs for themes.

![image](https://user-images.githubusercontent.com/930215/93004358-23faa000-f514-11ea-9832-ec31c7934773.png)
