### ISSUE TITLE
No GetComments operation in API description

### ISSUE THREAD

**Issue by uuttff8** [LemmyNet/lemmy#1128]
https://dev.lemmy.ml/docs/contributing_websocket_http_api.html?search=GetComments does not have description about GetComments operation, such as 

Request:

```json
{
  "op":"GetComments",
  "data": {
    "page":1,
     "limit":20,
     "sort":"Active",
     "type_":"Subscribed",
     "auth":"xxxx"
  }
}
```

Response:

```json
{
  "op": "GetComments",
  "data": {
    "comments": Vec<CommentView>
  }
}
```

**Comment by dessalines** [comment]
I added this in a pull request. https://github.com/LemmyNet/lemmy/pull/1121/files#diff-397b29a8c8b20ae3c848162b523d37b2R1798
