### ISSUE TITLE
should the user object in GetSiteResponse use ListingType/SortType enums?

### ISSUE THREAD

**Issue by eiknat** [LemmyNet/lemmy#1136]
default_sort_type and default_listing_type both currently return numbers, should or will these be returning the same enum values used in other endpoints?

**Comment by dessalines** [comment]
For now at least, consider these as numbered enums (This comes from them being the only sorting type stored in the DB, and I think I arbitrarily chose `smallint` as a way to store them). Unfortunately all the other types are string enums, and serialized that way. 

Eventually it'd probably be a good idea to have these ones be strings as well, so it would require changing both the API and that column to a varchar type.

**Comment by eiknat** [comment]
okay, thanks! i'll see if i can write a serializer for it that can accept both

**Comment by dessalines** [comment]
I would just let the serializer treat it like a number enum, and then the clients can use the index / ordinal of the value:

```
  handleUserSettingsListingTypeChange(val: ListingType) {
    this.state.userSettingsForm.default_listing_type = Object.keys(
      ListingType
    ).indexOf(val);
    this.setState(this.state);
  }
```

In the future we can convert it to a string-valued enum anyway.

**Comment by dessalines** [comment]
This could be done using: https://github.com/adwhit/diesel-derive-enum . The only other enum that's in use, is `RegistrationMode`
