### ISSUE TITLE
Adding translation support for new language via weblate

### ISSUE THREAD

**Issue by balsamfelder** [LemmyNet/lemmy#1137]
I would like to know if it is possible to add translation support for different regional varieties of Chinese (namely, `zh_TW` for Taiwan and `zh_HK` for Hong Kong). I can't seem to add a new language via weblate. 

The Traditional Chinese script is used as the standard in both TW and HK. It is different from the Simplified Chinese script, which is mainland China's standard and what Lemmy's `zh` is using. (Often, this variant is denoted as `zh_CN` to distinguish it from other regions)

In addition to the script, there are also some vocabulary differences between the TW and HK standards, especially when it comes to computer related terms. Ideally, having separate `zh_TW` and `zh_HK` translations would be nice. Nonetheless, it should be pretty easy to do this translation, given that there is already a simplified Chinese translation.

**Comment by dessalines** [comment]
I'll add these soon.

**Comment by dessalines** [comment]
For now I'll just copy the current `zh.json` to all three.

**Comment by dessalines** [comment]
Closed by https://github.com/LemmyNet/lemmy-ui/commit/33d54d31a0dcc32ccb880cec72f8d173bc101e8c
