### ISSUE TITLE
Clustering and scaling

### ISSUE THREAD

**Issue by 123mitnik** [LemmyNet/lemmy#1142]
It may be obvious, but I can't find how lemmy scales across multiple servers/clusters. What is the scaling strategy?

**Comment by Nutomic** [comment]
You can run different containers (postgres, pictshare, iframely) on separate hosts, but you cant scale Lemmy itself horizontally. And I'm not convinced that is needed, because the hardware requirements are extremely low thanks to Rust.

**Comment by dessalines** [comment]
We haven't found a case where an instance has hit its limits yet, but this is kinda what federation is for anyway.

**Comment by 123mitnik** [comment]
Thank you both @Nutomic !, @dessalines !

is there access to some shared state between multiple threads when actix is spawned.

I was thinking between the lines that for example, Redis will help to distribute lemmy between multiple hosts and put it behind load balancer. The second thought was about the session management and other cached data (how lemmy handles the sessions ?) i.e. in case of re-deployment - you will not lose the active sessions

**Comment by Nutomic** [comment]
Why are you asking about this? Are you actually running into performance problems with Lemmy? On our prod server, Lemmy is consistently under 1% CPU usage, with some rare spikes. The only thing that takes noticable resources is postgres.

**Comment by dessalines** [comment]
The websocket session thing shouldn't be a worry, because of `reconnecting-websocket`. I'd have to check the front end code, but the main pages have a `if (msg.reconnect)` thing, in which case it just needs to rejoin that context (IE the community room, user room, or post room).

**Comment by 123mitnik** [comment]
No performance issues (zero at this point !!!). Jut trying to figure out some unpleasant (hardware failures, traffic load etc), and some pleasant unpredictable events (traffic balancing by regions etc).. The most simple scenario is a hardware failure. It's not a mission-critical at this point -- but it may become such if the userbase skyrockets. Thank you for your immediate responses (and code)!

**Comment by academician** [comment]
@Nutomic @dessalines With the recent interest, is it worth reopening this issue (or something like it)? For large instances, it would probably be very helpful to be able to scale an instance horizontally.

**Comment by snowe2010** [comment]
@academician from what I've seen, the issue hasn't been lemmy so much as postgres and nginx. There are some weird configuration options in nginx causing issues, and the pool to postgres needs to be massively bumped up. Along with that, using a cdn like cloudflare massively reduced the load on our server.

**Comment by Xanvial** [comment]
With bigger userbase, there's not only performance that can benefit from horizontal scaling but also the High Availability of lemmy itself. With multiple instances, the server uptime can be improved (ie. can do rolling update, can still handle traffic if unexpected issue on one server occurs, etc)

**Comment by sunaurus** [comment]
I wrote down some notes on horizontally scaling Lemmy, feedback is welcome: https://github.com/LemmyNet/lemmy-docs/pull/249
