### ISSUE TITLE
Why isn't actixweb::get used directly in the API routes?

### ISSUE THREAD

**Issue by ibraheemdev** [LemmyNet/lemmy#1148]
Hey, quick question. What is the point of the whole `route_get()` and `Perform` trait used in the API routes? Why not just use `actix_web::web::get` directly? Is it down sort of dependency decoupling for unit tests?

**Comment by dessalines** [comment]
web::get is being used:

`.route("/get_captcha", web::get().to(route_get::<GetCaptcha>))`
