### ISSUE TITLE
How do I activate Access-Control-Allow-Origin for lemmy?

### ISSUE THREAD

**Issue by AlperAydin** [LemmyNet/lemmy#1156]
Hello,

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://10.0.2.15:8081/sockjs-node/info?t=1601155221468. (Reason: CORS request did not succeed).

We want to prepare ui in vue js but we couldn't handle that problem. How we can enable CORS for the lemmy?

Thanks!

**Comment by dessalines** [comment]
This isn't enough information for me to help. You need to be running lemmy locally if you want to develop another UI for it.

**Comment by AlperAydin** [comment]
We are running on localhost and just trying to get objects from api but CORS doesn't allow our request. (using axios)

**Comment by dessalines** [comment]
I don't know what axios is, but again this isn't enough info for me to help. You can't make cross-domain browser requests, you need to be running lemmy on the same domain as your ui.

**Comment by AlperAydin** [comment]
Okay, we tried it first on Vue.js but i will explain you with basic html file.
What our index.html file contains;
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-latest.js"></script>
</head>
<body>
 <script>

var ws = new WebSocket("ws://localhost:8536/api/v1/ws");
ws.onopen = function () {
  console.log("Connection succeed!");
  ws.send(JSON.stringify({
    op: "ListCategories"
  }));
};


$.get( "http://localhost:8536/api/v1/categories", function( data ) {
  console.log(data);
});

</script>
</body>
</html>
```

What we get on console log;

```
Connection succeed!
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8536/api/v1/categories. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

UI and backend working at the same server. If CORS was not available for this situation how the isomorphic ui works without CORS? Am i missing something?
Thanks!

**Comment by dessalines** [comment]
Run this command: `curl http://localhost:8536/api/v1/categories`

**Comment by AlperAydin** [comment]
Thank you so much!
It works but, how can we get via ajax? 
How isomorphic ui works without cors. As I know, curl does not provide a functionality to get data on client side. How can we handle this situation? We also tried to add a cors middleware into the main.rs file. But it wasn't work as expected.

**Comment by dessalines** [comment]
I don't see why you'd design a client from scratch considering we've already written one here : https://github.com/LemmyNet/lemmy-js-client . 

Again, you are getting CORs violations because you are running your http calls from a different domain than where you run the server. The isomorphic UI (and any UI) works fine because its running on the same host as the lemmy server.

**Comment by AlperAydin** [comment]
We're not working on a dockerized app. We are just running up the lemmy backend server and trying to get main post page via LemmyHttpClient for this time (Because you said axios is needless in this case). We took a look at your lemmy js client documents. All service methods are requiring the auth token (JWT).

We want to fetch the main page. According to our researches, this method doesn't require auth token. But we couldn't get data from the `lemmyHttp.listCategories()`  endpoint because of cors policy.

Lemmy Backend - 127.0.0.1:8536 - Vue Frontend 127.0.0.1:8080 but cannot handle this situation.

We are working on the same host.

**Comment by dessalines** [comment]
You've given me no way to reproduce your problem.

**Comment by AlperAydin** [comment]
Which way do you prefer:
Full dockerized app (backend + frontend) or just vue app for reproducing

**Comment by dessalines** [comment]
Either, as long as you list the steps to reproduce.
