### ISSUE TITLE
Invalid JSON Response Body

### ISSUE THREAD

**Issue by Casuallynoted** [LemmyNet/lemmy#1158]
Using my own postgres container and pointing the containers to it, since I already have the DB set up and I have auto backups set up for that container. 

I'm noticing several errors when trying to connect to lemmy this way. I've noticed that the UI loads when I do the url/index, but not just the url. It also doesn't load images and seems to have trouble connecting to the main instance based on the logs. 

[docker-compose.txt](https://github.com/LemmyNet/lemmy/files/5288977/docker-compose.txt)
[lemmy.txt](https://github.com/LemmyNet/lemmy/files/5288978/lemmy.txt)

**Comment by dessalines** [comment]
Looking at your docker-compose.yml, you're using a really old version of lemmy and lemmy-ui, and you also need to change some environment variables for lemmy-ui to point to your instance domain.

Instructions here:

https://dev.lemmy.ml/docs/administration_install_docker.html

Also, tell me if the docs are wrong and you get any issues, we haven't even done an official deploy of these changes yet.

**Comment by Casuallynoted** [comment]
Thank you so much for that info! So at the moment, I've gotten it all running with a postgres container from the compose. Updated env variables as well. Here are the updated ones. Currently the website loads at the url vote.casually.cat/index, but oddly not at vote.casually.cat. I'm getting this error from the UI container:

ext:qtip="(node:1) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://lemmy:8536/api/v1/post/list?page=1&amp;limit=20&amp;sort=Active&amp;type_=All&amp;auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJDYXN1YWxseW5vdGVkIiwiaXNzIjoidm90ZS5jYXN1YWxseS5jYXQiLCJzaG93X25zZnciOnRydWUsInRoZW1lIjoiZGFya2x5IiwiZGVmYXVsdF9zb3J0X3R5cGUiOjAsImRlZmF1bHRfbGlzdGluZ190eXBlIjoxLCJsYW5nIjoiYnJvd3NlciIsImF2YXRhciI6bnVsbCwic2hvd19hdmF0YXJzIjp0cnVlfQ.djLr5V8CbfxkILc7qBta7rGL8QngLQ43GyQ_qfbPOog reason: Unexpected token M in JSON at position 0 "

Attached is the updated docker compose
[docker-compose.txt](https://github.com/LemmyNet/lemmy/files/5289077/docker-compose.txt)

**Comment by dessalines** [comment]
What are those `&amp;`, it shouldn't be making requests like that, it should be using `&` Could you post your nginx? There should not be a route at `/index`.

https://vote.casually.cat/api/v1/categories fails for me also, telling me your nginx isn't set up correctly.

**Comment by Casuallynoted** [comment]
This is my current lemmy config:

[lemmy-nginx.txt](https://github.com/LemmyNet/lemmy/files/5289126/lemmy-nginx.txt)

**Comment by dessalines** [comment]
Hrm, nginx looks good.

Try using `dessalines/lemmy-ui:v0.7.61` or `dessalines/lemmy-ui:dev` in your docker-compose.

https://hub.docker.com/r/dessalines/lemmy-ui/tags

**Comment by Casuallynoted** [comment]
Tried using both but the issue seems to still persist, it wants to give me a gateway timeout on the main page but loads under/index (albeit with content missing and logging me out anytime I press on any of the "create" options)

**Comment by dessalines** [comment]
The only other thing I could do to debug, is to get everything loaded, then do `docker-compose logs -f --tail=100`, load the page, and tell me if there are any errors, especially in `lemmy-ui`.

Also something seems wrong here:

https://vote.casually.cat/api/v1/post/list?page=1&limit=20&sort=Active&type_=All Doesn't work

https://dev.lemmy.ml/api/v1/post/list?page=1&limit=20&sort=Active&type_=All Works

Which tells me something is wrong with your install.

**Comment by dessalines** [comment]
You're probably still on v0.7.9, and didn't upgrade to v0.7.61

**Comment by Casuallynoted** [comment]
Oh my god I'm an idiot and you're right! I updated the UI container but not the regular lemmy one! Done and now it works. Thank you so so much!

**Comment by dessalines** [comment]
No probs :) its my bad for not deploying this soon enough and making sure the docs are all set.
