### ISSUE TITLE
Add donation box for instance maintainers 

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy#1159]
### Is your proposal related to a problem?
Currently there's a way in Lemmy to donate to the main project, Lemmy. But maintaining an instance also have a cost (not only) in money.

### Describe the solution you'd like
For being able to maintain an instance only with the support of its users, it would be great if an optional box could be created in Lemmy, if instance maintainers want to add it to the UI.

### Describe alternatives you've considered
The current alternative would be to add that info in a description or rules of the instance, but that's not as elegant as a specific box,.

### Additional context
If done, it should be a standar stencill that can be changed to replace with the appropriate link for donation.

**Comment by dessalines** [comment]
You can put a donation link in the sidebar. I'll soon be moving the lemmy donation links and sponsors off the main site anyway.
