### ISSUE TITLE
links about how to set up your own instance

### ISSUE THREAD

**Issue by danielbartsch** [LemmyNet/lemmy#1167]
As a person with not much knowledge about hosting your own website, let alone connect lemmy with it, I would find it good to have a more detailed explanation of this in the [docs](https://dev.lemmy.ml/docs/administration_install_docker.html). Or perhaps links to resources to set up something like this.

I have basic knowledge about nginx, and how to host a basic website, but not how to connect lemmy to a subdomain (eg.) of it.
Using the provided nginx config doesn't seem to work for me (I'm not sure if I get the lemmy(ui)ports right).

For some reason there's an nginx error, too: 
```
nginx.service: Failed to parse PID from file /run/nginx.pid: Invalid argument
```

I've tried searching for this, but can't seem to find what's the cause of this.

Some more information about my "skills" with nginx: I was able to set up a subdomain with just a simple html file, but can't connect this with lemmy.

**Comment by dessalines** [comment]
I will add the default lemmy ports to that nginx template for this. Its

thing | port
--- | ---
lemmy_port | 8536
lemmy_ui_port | 1235

We can't really help with basic nginx knowledge, I'd suggest starting with digitaloceans nginx guides, and searching for how to use nginx with subdomains.

Your first thing, the search result: https://www.digitalocean.com/community/questions/unable-to-start-nginx-failed-to-read-pid-from-file-run-nginx-pid
