### ISSUE TITLE
Make documentation path configurable

### ISSUE THREAD

**Issue by andreymal** [LemmyNet/lemmy#1168]
I'm trying to run Lemmy without Docker, but Lemmy has a hardcoded path that's only accessible inside the container:

https://github.com/LemmyNet/lemmy/blob/442369a041e79af374dbc08fc0d8a5669806a210/src/main.rs#L103

Of course this directory does not exists on my arch linux, and `lemmy_server` produces an error:

```
$ ./lemmy_server 
Starting http server at 0.0.0.0:8536
[2020-10-02T20:34:23Z ERROR actix_files] Specified path is not a directory: "/app/documentation"
```

I suggest, for example, moving the static files routes into config, or at least replacing them with a relative path.

Probably related to #641

**Comment by dessalines** [comment]
This is doable, but that error won't break anything. The docs currently only work with the docker / ansible install, just like pictrs and iframely also require docker. I'd say that this would come after someone gets those working as a custom install first.

**Comment by Nutomic** [comment]
Fixed in https://github.com/LemmyNet/lemmy/pull/1245
