### ISSUE TITLE
Edit photo before uploading as avatar to avoid stretching

### ISSUE THREAD

**Issue by felipeforte** [LemmyNet/lemmy#1184]
Self-explanatory, it's not that urgent, though.

**Comment by felipeforte** [comment]
As far as I remember, I linked a photo for context in this bug report, but this issue is already fixed by now, so I'm closing it.

**Comment by Porrumentzio** [comment]
This means that the images uploaded won't be streched and deformed? They get oval form, and not only for avatars but also for communities' images

**Comment by dessalines** [comment]
This is a lemmy-ui issue, not lemmy.
