### ISSUE TITLE
Local users can immediately see posts to remote community

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1205]
Consider the following example: we have two instances alpha and beta, with users U1 and U2 on alpha, and community C on beta. Both users follow the community. Beta is down, and U1 makes a post to C. U2 will immediately see the post in C, because it is stored in the same database table.

This is mainly a theoretical problem for now, but it will become an issue once we implement things like community bans, or communities where only mods can post.

**Comment by Nutomic** [comment]
Relevant: https://yerbamate.ml/LemmyNet/lemmy/pulls/128

**Comment by dessalines** [comment]
Seems a dupe of #3399 , and possibly not important, since instance admins set the default view they want their users to see.
