### ISSUE TITLE
Change preferred_username column / API to display_name

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1211]
Since activitypub uses `preferredUsername` = the database user name, and `name` = `display_name`, which @Nutomic fixed in this PR : https://github.com/LemmyNet/lemmy/pull/1209

So now this should also be corrected in the DB and the API,  either by matching the apub terms exactly, or changing `preferred_username` to `display_name` to avoid confusion.

**Comment by eiknat** [comment]
i can do this. do you want to maintain compatibility with the old field for now in endpoints or do a full switch?

**Comment by dessalines** [comment]
That's okay, once I finish up a few other things, I'm starting #1275 , and we need to stop any DB changes until that gets going. I'll roll this into that one as a part of it.
