### ISSUE TITLE
Rate limited on first registration attempt

### ISSUE THREAD

**Issue by mkhan45** [LemmyNet/lemmy#1214]
### Issue Summary

I am rate limited on my first attempt to sign up with the message: `Register, IP. 172.20.0.1, 3 per 3600 seconds`

First I tried through my VPN, then I disconnected from my VPN after getting the message, and then I waited an hour and tried again.

### Steps to Reproduce

1. Go to sign in page
2. Enter details, finish captcha
3. Click sign up button

### Technical details

Here's the console log:
![](https://i.imgur.com/i1Ia7rm.png)

**Comment by dessalines** [comment]
Thanks, this seems to be an issue with nginx not correctly forwarding some IP headers.
