### ISSUE TITLE
Community Outbox should contain Activities

### ISSUE THREAD

**Issue by lanodan** [LemmyNet/lemmy#1216]
Hi, Pleroma dev here, I did some quick checks on what Lemmy federates and found some issues (btw Pleroma lacks `Group` at the moment so most of Lemmy couldn't work).

Instance used: <https://enterprise.lemmy.ml/> which seems to run v0.7.64

- Retrieving Objects (spec: <https://www.w3.org/TR/activitypub/#retrieving-objects>) `Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams` must work (Pleroma uses `Accept: application/activity+json` IIRC, which works for Lemmy). I got HTML instead.

- Outbox (spec: <https://www.w3.org/TR/activitypub/#outbox>) should contain activities (which I find quite useful to get test fixtures), I got objects.

**Comment by Nutomic** [comment]
I fixed your first issue here: https://yerbamate.dev/LemmyNet/lemmy/pulls/114

**Comment by Nutomic** [comment]
One way to fix this would be by adding an `actor` column to the `activities` table. Then we could easily return the last X activities of that actor for the community outbox HTTP endpoint. And we will have to parse it on the fetching side.

**Comment by dessalines** [comment]
We shouldn't have removed `user_id` in that case then, bc we could join to get the actor from there. We have that `down.sql`, so it'd be easy to add back in.

**Comment by Nutomic** [comment]
It can be either a user or a community, so calling it `user_id` doesnt make sense. Maybe we could have both `user_id` and `community_id` columns, with a constraint that exactly one of them is non-null.

**Comment by dessalines** [comment]
Ohhh I see.

**Comment by Nutomic** [comment]
Actually there's another problem: if we just serve all activities that the community sent in the outbox, then there might be hundreds of votes and comments. What we want are just the latest 20 posts, so in a very active community we might have to go through dozens of outbox pages to get those. Might be better if we only serve `Create/Post` in the community outbox, but then we also need to filter for those in the database.

**Comment by lanodan** [comment]
[2020-11-18 07:54:03-0800] Nutomic:
> Actually there's another problem: if we just serve all activities that the community sent in the outbox, then there might be hundreds of votes and comments. What we want are just the latest 20 posts, so in a very active community we might have to go through dozens of outbox pages to get those. Might be better if we only serve `Create/Post` in the community outbox, but then we also need to filter for those in the database.

Not sure if there is something in the spec about it but the outbox should contain all `as:Public` activities, which means a lot of noises (pump-io, which AP is heavily inspired from had a separate feed).

During APConf2020 and for AP C2S (which is barely used btw) I posed the question of how to filter/search such endpoints to get meaningful output and so not end up with clients having to skim throught a gigantic amount of pages by themselves, the issue is that the language used for querying needs to be flexible so we don't end up with a pile of similar endpoints.

**Comment by Nutomic** [comment]
I found a crate diesel_json which could help with querying and filtering based on json fields. Hopefully they can add support for the `->` operator, then this should be no problem. [Upstream issue is here](https://github.com/PPakalns/diesel_json/issues/1)

[And here's the unfinished code for this](https://yerbamate.ml/LemmyNet/lemmy/commit/ac128c93a99a883645df613029a0e29c12f5b7b3)
