### ISSUE TITLE
Install Lemmy without Docker ?

### ISSUE THREAD

**Issue by anmol26s** [LemmyNet/lemmy#1230]
Is there an official installation steps for hosting Lemmy on Debian, preferably with Nginx? If not, is it planned to provide it for the users who don't want to host Lemmy on Docker?

**Comment by dessalines** [comment]
We will not support manual / non-docker installs due to the complexity of all the potential OS's, and that lemmy requires other running services.

https://dev.lemmy.ml/docs/administration.html

**Comment by Nutomic** [comment]
I would be fine with adding docs to explain how to install Lemmy without Docker (if someone writes it). But we will definitely not provide support for that.
