### ISSUE TITLE
failed to install lemmy with docker

### ISSUE THREAD

**Issue by pullopen** [LemmyNet/lemmy#1231]
### Issue Summary

Failed to install Lemmy with Docker.

### Steps to Reproduce

Using installing steps in official document

### Technical details
Can not start "lemmy_lemmy_1", log shows:
```
lemmy_1     | thread 'main' panicked at 'missing field `use_tls`', lemmy_utils/src/settings.rs:79:15
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | Panic in Arbiter thread.
```

**Comment by dessalines** [comment]
What version of lemmy? Post your docker-compose.yml and config.hjson file.

It seems like you have the email block of the config uncommented, but didn't include the required `use_tls` field:

https://github.com/LemmyNet/lemmy/blob/main/config/defaults.hjson

**Comment by pullopen** [comment]
> 
> 
> What version of lemmy? Post your docker-compose.yml and config.hjson file.
> 
> It seems like you have the email block of the config uncommented, but didn't include the required `use_tls` field:
> 
> https://github.com/LemmyNet/lemmy/blob/main/config/defaults.hjson

I finally found what's going on. Using the official step, it ask me to
```
wget https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/lemmy.hjson
```
But this `lemmy.hjson` does not include this field.

Now the problem is solved.

**Comment by Nutomic** [comment]
You're right, thanks for the report! I fixed it here:

https://yerbamate.dev/LemmyNet/lemmy/pulls/120
