### ISSUE TITLE
Add a pending column to community_follower

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1239]
https://github.com/LemmyNet/lemmy/blob/main/lemmy_apub/src/inbox/user_inbox.rs#L132

Set `pending` = true for a received accept follow.

From Nutomic: in activities::send::user::send_follow(), it needs to add the follow relation to community_follower (as pending)
then in inbox::user_inbox::receive_accept() it needs to check that there is actually a "pending" follow in the table
and change it to not pending

**Comment by Nutomic** [comment]
Fixed in https://yerbamate.ml/LemmyNet/lemmy/pulls/130
