### ISSUE TITLE
Anti-spam measures

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#124]

**Comment by mister-monster** [comment]
What sort of measures? Rate limits for the API? Or something else?

We will definitely need rate limits for the API as a whole.

**Comment by dessalines** [comment]
Ya so far I'm gonna start working on an in-memory IP address cache that rate-limits signups to one every X for something for a certain IP address.

I want all the limiting and security to be "at the door", IE on registration, I don't *really* wanna rate limit the websocket API as a whole.

**Comment by dessalines** [comment]
https://stackoverflow.com/questions/667508/whats-a-good-rate-limiting-algorithm

**Comment by mister-monster** [comment]
I think it is probably a good idea to rate limit the API as a whole. Once an instance scales to hundreds of users, a group of bots could make accounts and then spam things like comments, community creation (as we have seen) or votes.

Pretty much every public API I have seen rate limits all requests to prevent abuse.

**Comment by nikhiljha** [comment]
This is a *really* hard problem with decentralized social networks. It's fairly trivial to get a few million IP addresses (esp with IPv6) to spam votes with and get whatever posts to the top you want.

Some existing solutions to maybe consider...

- Require all users to be invited by another user, so if someone makes a billion accounts, you just go as far up the tree as necessary and ban all derivative accounts from voting.
- Allow instance owners to require phone verification to vote. They can then blacklist instances they're getting spam from, or whitelist popular instances that request it.

**Comment by dessalines** [comment]
Def don't want phone (for privacy reasons) or email invite chain (not a fan of this method). There is a ticket for this tho, which is a solution used in a lot of places that I really like. #209

**Comment by PopeRigby** [comment]
Yeah. I'm also against using a phone for that.

**Comment by Nicedude-git** [comment]
Hello. So finally is there any anti spam method? I would like to suggest a captcha.

**Comment by dessalines** [comment]
We will never support google recaptcha, but I'm open to PRs for other potential ones. Right now the main only spam method prevention is the strong moderation abilities, the [tunable rate_limits for signups.](https://github.com/LemmyNet/lemmy/blob/master/docker/lemmy.hjson#L30)

**Comment by Nicedude-git** [comment]
9 

> We will never support google recaptcha, but I'm open to PRs for other potential ones. Right now the main only spam method prevention is the strong moderation abilities, the [tunable rate_limits for signups.](https://github.com/LemmyNet/lemmy/blob/master/docker/lemmy.hjson#L30)

Fair enough. There is hCaptcha as well (i don't have a strong opinion either in favor or against it).

The solution proposed seems good. However, i am a bit confused about the definition of interval. In the example, is it 180 or 60 messages per second? I don't see a limit for community creation either. 

# maximum number of messages created in interval
    message: 180
    # interval length for message limit
    message_per_second: 60

**Comment by dessalines** [comment]
Community creation follows the same limits as register.

180 reqs / minute.

3 register reqs / hour.

**Comment by Nicedude-git** [comment]
> Community creation follows the same limits as register.
> 
> 180 reqs / minute.
> 
> 3 register reqs / hour.

So where it says message_per_second it actually means "size of interval in seconds"?

**Comment by dessalines** [comment]
No, it means per_second. 3 register posts per 3600 seconds.

**Comment by dessalines** [comment]
Outside of captcha, this is done.
