### ISSUE TITLE
Problems with banning

### ISSUE THREAD

**Issue by DuelTheBearded** [LemmyNet/lemmy#1251]
If you are banned, you still get emails of new things in your inbox.

Also, I would like to be unbanned from dev.lemmy.ml. I was banned for calmly sharing my opinion. You have not replied to my email or done anything about the real rule violators (@StaticallyTypedRice and a user on Lemmy by the name of BlackCentipede).

Also, thanks to the Lemmy user **Stoned_Ape** for defending me.

![image](https://user-images.githubusercontent.com/37164157/98024620-8fefdb00-1dd6-11eb-9c69-a7bb88465e10.png)

**Comment by dessalines** [comment]
> If you are banned, you still get emails of new things in your inbox.

Hrm... that looks like an issue, as currently all actions check for a site-wide ban. #1255 

Your ban is definitely staying, we don't allow pro-trump covid deniers on any instances.

![image](https://user-images.githubusercontent.com/930215/98247292-77500400-1f41-11eb-8c5d-3dbd2b7792b3.png)

![image](https://user-images.githubusercontent.com/930215/98247348-89ca3d80-1f41-11eb-963b-7ae3047f13c9.png)

![image](https://user-images.githubusercontent.com/930215/98247502-b1210a80-1f41-11eb-830d-ca1cb7586dae.png)
