### ISSUE TITLE
Delete, Remove community not federating (invalid signature)

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1253]
When doing a `Delete/Community`, `Remove/Community`, `Undo/Delete/Community`, `Undo/Remove/Community`, I'm consistently getting the error `Invalid signature on request: /inbox`. Both locally and on test servers. Posts and comments are received fine though.

We should add some tests for this as well.

**Comment by Nutomic** [comment]
Ah, must be because `actor` is set to the community creator, but it is signed by the community so of course it wont work. Who do you think should be the actor @dessalines?

**Comment by dessalines** [comment]
Ya I'm good with the community being the actor.
