### ISSUE TITLE
Ignore site ban check for some API actions.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1255]
- SaveUserSettings

@Nutomic can you think of any other actions besides SaveUserSettings that need to ignore a site ban check? I don't think they should be able to update / delete posts or comments after a ban, that should be up to the admins / mods IMO.

**Comment by Nutomic** [comment]
I'm not sure its a good idea to allow free edits of the user profile, they might put something malicious and then what are you gonna do as mod or admin? You'd have to manually edit the database to prevent them from logging in again, and manually clear the profile.

If anything, I would allow a banned user to delete their profile, and possibly their posts/comments. But this could also be done by contacting the admins (then there should be an option on the frontend to delete users).

**Comment by dessalines** [comment]
Hrm... yeah that's a tough one, they could potentially put malicious things in there.

**Comment by dessalines** [comment]
This is moot now, since `get_user_from_jwt` does a ban check.
