### ISSUE TITLE
Deny missing docs

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1257]
If we compile with `#![deny(missing_docs)]` in lib.rs, the compiler will warn us about any public functions and items without documention. I think it would be very useful to add this documentation, both for potential contributors and for our own understanding of the code. This might even be a good task for new contributors, because it doesnt require knowledge of the code (we can always answer questions if something is unclear). PRs for this should only include one or a couple files each, to make reviewing easier.

While adding the missing docs, it would also be a good opportunity to reduce the visibility of methods if possible, like changing `pub` to `pub(crate)`.

Here is a similar issue for diesel: https://github.com/diesel-rs/diesel/issues/563

**Comment by dessalines** [comment]
I've started working on this one, its not too bad.

**Comment by Nutomic** [comment]
Closing this, I think it makes sense for a library but not so much for an application.
