### ISSUE TITLE
Modlog unable to load on german instance

### ISSUE THREAD

**Issue by r0qstr** [LemmyNet/lemmy#1258]
### Issue Summary

Opening the modlog on a german instance (https://lemmy.161.social) takes forever to load end finishes with "504 Gateway Time-out". The console reads:
 The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. modlog

I would guess the problem occurs because of german umlauts

### Steps to Reproduce

1. open https://lemmy.161.social
2. Click on modlog

**Comment by Nutomic** [comment]
```
curl "https://lemmy.161.social/api/v1/modlog"
Unexpected null for non-null column             
```

Doesnt sound like this has anything to do with the language or encoding. Could you check if there are any errors in the server log?

Coole Instanz übrigens :)

**Comment by dessalines** [comment]
Hrm this one is a bit strange, as I have `<meta charset="utf-8">` at the top, which should handle that fine. I'll have to investigate.

BTW would you like us to add lemmy.161.social to the joinlemmy instances? If so give me a 1 line description of your instance.

**Comment by r0qstr** [comment]
I'll provide the server log as soon as I get it. 

sure we'd like to be featured there. "An anti-authoritarian and emancipatory space for german speaking anti-fascists." should do the trick, I hope.

**Comment by dessalines** [comment]
I've got you added to https://join.lemmy.ml

I can't figure out this one tho, I don't think if it has to do with utf8 encoding:
![image](https://user-images.githubusercontent.com/930215/98716438-9099eb80-2359-11eb-9ae1-1678272119e5.png)

I'd need to see the docker logs after running `curl "https://lemmy.161.social/api/v1/modlog"` to figure out whats going on.

**Comment by r0qstr** [comment]
so far I din't find anything suspious in the docker logs, only error is:
"[2020-11-16T12:47:31Z ERROR lemmy_websocket::handlers] Error during message handling missing field `auth` at line 1 column 2"

does that ring a bell? I'll repeat the test after running the curl command as soon as possible, sadly i'm not the person with server access so there is always a bit of delay until I get my hands on it.

**Comment by r0qstr** [comment]
(node:1) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://lemmy:8536/api/v1/modlog?page=1&limit=20 reason: Unexpected token U in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:1) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://lemmy:8536/api/v1/modlog?page=1&limit=20 reason: Unexpected token U in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:1) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://lemmy:8536/api/v1/modlog?page=1&limit=20 reason: Unexpected token U in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:1) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://lemmy:8536/api/v1/modlog?page=1&limit=20 reason: Unexpected token U in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
`(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)`

**Comment by dessalines** [comment]
Those are the lemmy-ui logs, and that sounds right, but I'd need to see the lemmy logs: `docker-compose logs lemmy > lemmy_logs`

**Comment by r0qstr** [comment]
that appears to be the only output from there

# docker-compose logs lemmy
Attaching to lemmy_lemmy_1
lemmy_1     | Starting http server at 0.0.0.0:8536
lemmy_1     | federation enabled, host is lemmy.161.social
lemmy_1     | [2020-11-19T20:01:00Z ERROR lemmy_websocket::handlers] Error during message handling missing field `auth` at line 1 column 2
lemmy_1     | [lemmy_api/src/site.rs:336] &data = Search {
lemmy_1     |     q: "https://youtu.be/bUQlIPpxcG8",
lemmy_1     |     type_: "Url",
lemmy_1     |     community_id: None,
lemmy_1     |     community_name: None,
lemmy_1     |     sort: "TopAll",
lemmy_1     |     page: Some(
lemmy_1     |         1,
lemmy_1     |     ),
lemmy_1     |     limit: Some(
lemmy_1     |         6,
lemmy_1     |     ),
lemmy_1     |     auth: Some(
lemmy_1     |         "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NTIsImlzcyI6ImxlbW15LjE2MS5zb2NpYWwifQ.I1TFFESQdSWNqZYTUrsE02ZSZyRWnJMLXr5XlWsArpo",
lemmy_1     |     ),
lemmy_1     | }
lemmy_1     | [2020-11-19T20:01:02Z ERROR lemmy_websocket::handlers] Error during message handling missing field `auth` at line 1 column 2
lemmy_1     | [lemmy_api/src/site.rs:336] &data = Search {
lemmy_1     |     q: "https://de.indymedia.org/node/118070",
lemmy_1     |     type_: "Url",
lemmy_1     |     community_id: None,
lemmy_1     |     community_name: None,
lemmy_1     |     sort: "TopAll",
lemmy_1     |     page: Some(
lemmy_1     |         1,
lemmy_1     |     ),
lemmy_1     |     limit: Some(
lemmy_1     |         6,
lemmy_1     |     ),
lemmy_1     |     auth: None,
lemmy_1     | }
lemmy_1     | [lemmy_api/src/site.rs:336] &data = Search {
lemmy_1     |     q: "https://vimeo.com/472013933",
lemmy_1     |     type_: "Url",
lemmy_1     |     community_id: None,
lemmy_1     |     community_name: None,
lemmy_1     |     sort: "TopAll",
lemmy_1     |     page: Some(
lemmy_1     |         1,
lemmy_1     |     ),
lemmy_1     |     limit: Some(
lemmy_1     |         6,
lemmy_1     |     ),
lemmy_1     |     auth: None,
lemmy_1     | }
lemmy_1     | [2020-11-19T20:01:03Z ERROR lemmy_websocket::handlers] Error during message handling missing field `auth` at line 1 column 2

**Comment by dessalines** [comment]
Ugh, no error messages, this is gonna be tough. Contact me [on matrix](https://matrix.to/#/@happydooby:matrix.org) so you can send me a backup of your DB, I can pull it down locally, and try to figure out what's happening.

**Comment by dessalines** [comment]
Found the issue using a DB file for that server, and I'm showing my solution in case anyone has similar issues.

When accessing the mod log page, I get this error: 

```
lemmy_1     | [2020-11-20T21:08:35Z INFO  actix_web::middleware::logger] 192.168.50.20:59236 "GET /api/v1/modlog?page=1&limit=20 HTTP/1.1" 400 35 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0" 0.014704
lemmy_1     | [2020-11-20T21:08:40Z DEBUG actix_web::middleware::logger] Error in response: LemmyError { inner: Unexpected null for non-null column }
```

So its a null column somewhere.

I checked the views in the DB file, and it turns out the mod_sticky_post table is the culprit:

```
lemmy=# select * from mod_sticky_post_view;
 id | mod_user_id | post_id | stickied |           when_            | mod_user_name |                 post_name                 | community_id | community_name
----+-------------+---------+----------+----------------------------+---------------+-------------------------------------------+--------------+----------------
  1 |           5 |       6 | t        | 2020-09-11 12:14:10.957545 | zedi          |                                           |              |
  2 |           5 |      15 | t        | 2020-11-02 11:41:30.167627 | zedi          | Lemmy Ankündigung                         |            2 | main
  3 |           5 |      35 | t        | 2020-11-04 11:40:39.301307 | zedi          | Sonntag: Filmeabend: Thema Anti-Atomkraft |            2 | main
  4 |           5 |      35 | f        | 2020-11-10 09:13:44.673587 | zedi          | Sonntag: Filmeabend: Thema Anti-Atomkraft |            2 | main
(4 rows)
```

Has a missing post_name which was suspicious, and it turns out its a missing row (which should be impossible due to foreign key constraints)

So I checked those contraints, and while the other mod_ tables do have foreign keys to `post` table, the `mod_sticky_post` doesnt:

```
Foreign-key constraints:
    "mod_lock_post_mod_user_id_fkey" FOREIGN KEY (mod_user_id) REFERENCES user_(id) ON UPDATE CASCADE ON DELETE CASCADE
    "mod_lock_post_post_id_fkey" FOREIGN KEY (post_id) REFERENCES post(id) ON UPDATE CASCADE ON DELETE CASCADE
Access method: heap
...
Indexes:
    "mod_sticky_post_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "mod_sticky_post_mod_user_id_fkey" FOREIGN KEY (mod_user_id) REFERENCES user_(id) ON UPDATE CASCADE ON DELETE CASCADE
Access method: heap
```

I'll give a quick solution to the server owner, but as a longer term fix, I need to create a migration to add that foreign key relation to the mod lock table.

**Comment by dessalines** [comment]
Actually that constraint looks good on a fresh DB, somehow you removed it manually? I also just checked our production databases, and the constraint is there. @r0qstr

**Comment by r0qstr** [comment]
Yeah it looks line someone uncautiously removed some constraints. Sorry for that

**Comment by dessalines** [comment]
No probs.
