### ISSUE TITLE
Error handling for federation

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1259]
We need to implement better error handling for our federation code. At the moment, most of it uses stringly typed errors, like `Err(anyhow!("Activity is not addressed to public").into())`. We should implement a separate error type instead, and make sure that returned status codes are in accordance with the activitypub standard.

**Comment by Nutomic** [comment]
I'm pretty much out of ideas on this one. Here is the best solution I could come up with:

```rust
#[derive(Debug)]
pub struct LemmyError {
  pub inner: anyhow::Error,
  pub status_code: Option<StatusCode>
}

impl<T> From<T> for LemmyError
where
  T: Into<anyhow::Error>,
{
  default fn from(t: T) -> Self {
    LemmyError { inner: t.into(), status_code: None }
  }
}

impl From<diesel::result::Error> for LemmyError {
  fn from(e: diesel::result::Error) -> Self {
    let status_code = match e {
      diesel::result::Error::NotFound => Some(StatusCode::NOT_FOUND),
      _ => None
    };
    LemmyError { inner: e.into(), status_code }
  }
}

impl actix_web::error::ResponseError for LemmyError {
  fn status_code(&self) -> StatusCode {
    self.status_code.unwrap_or(StatusCode::INTERNAL_SERVER_ERROR)
  }
}
```

But there are two problems with this code:

- It requires `#![feature(min_specialization)]`, and for that reason only works on nightly
- It means that utils depends on diesel, which can slow down the compilation

**Comment by Nutomic** [comment]
Error codes are already correct as far as I see. As for the error messages, we could wrap them in an `ApubError` type, but in the end they are still going to be strings describing what went wrong, so I'm not sure if it would improve anything.

**Comment by dessalines** [comment]
This doc really doesn't say anything about specific error messages, only that they return appropriate http error codes: https://www.w3.org/TR/activitypub/ . We're probably fine with string errors.

**Comment by Nutomic** [comment]
Actually, based on https://yerbamate.ml/LemmyNet/lemmy/pulls/165 it might be good to create an `ApubError` type like this, to help with debugging:

```
struct ApubError {
  inner: Option<anyhow::Error>, // the cause, if any
  apub_id: Url, // id of the object which caused the error (for debugging)
  message: String, // human readable description of what happened
  status_code: StatusCode, // if this error is served over http, use this as status code
}
```
