### ISSUE TITLE
Frontpage showing posts from communites not subscribed to (sometimes)

### ISSUE THREAD

**Issue by Whateverest** [LemmyNet/lemmy#1262]
Hi, 

sorry, I'm not sure if this is a front or back end problem. 

### Issue Summary
When I open https://lemmy.161.social in a new tab while logged in I see posts from all communities. After refreshing the page, the posts are limited to the communities I am subscribed to as expected. 
It looks like I see the same frontpage as a not logged in user. 

See the  screenshot below for an illustration of the problem.

### Steps to Reproduce

1. Be logged in to an instance.
2. Open a new Tab 
3. Refresh the page

### Technical details

Browser is Firefox 82.0.3 on Linux
Here is the complete browser console log (though it does not look very useful in this case):
```
httpbase: http://lemmy.161.social client.js:2:737767
wsUri: wss://lemmy.161.social/api/v1/ws client.js:2:737796
isLoggedIn = true client.js:2:1295784
Object { op: "UserJoin", data: {…} }
client.js:2:231012
Fetching unreads... client.js:2:1302949
Object { op: "GetReplies", data: {…} }
client.js:2:231012
Object { op: "GetUserMentions", data: {…} }
client.js:2:231012
Object { op: "GetPrivateMessages", data: {…} }
client.js:2:231012
Object { op: "CommunityJoin", data: {…} }
client.js:2:231012
The Notification permission may only be requested from inside a short running user-generated event handler. lemmy.161.social
Connected to wss://lemmy.161.social/api/v1/ws client.js:2:1038158
Object { op: "CommunityJoin", data: {…} }
client.js:2:1154140
Object { op: "GetPrivateMessages", data: {…} }
client.js:2:1154140
Object { op: "UserJoin", data: {…} }
client.js:2:1154140
Object { op: "GetUserMentions", data: {…} }
client.js:2:1154140
Object { op: "GetReplies", data: {…} }
client.js:2:1154140
```
![issueExample](https://user-images.githubusercontent.com/5324711/98819782-98c35b00-242d-11eb-91b5-bd73d1e93663.png)

**Comment by dessalines** [comment]
This should be fixed by: https://github.com/LemmyNet/lemmy-ui/issues/66 . I'll have `v0.8.3` later today which should have the fix.

**Comment by dessalines** [comment]
You can re-open this if after you deploy that, you still have issues.
