### ISSUE TITLE
Profile posting statistics

### ISSUE THREAD

**Issue by felipeforte** [LemmyNet/lemmy#1265]
Would be nice to see the number of upvotes and downvotes a user has received, or a proportion of those. This information was very useful in other link-aggregator websites when dealing with undesirables and trolls.

**Comment by Nutomic** [comment]
We had that before, but removed it because it creates an unhealthy obsession with upvotes, like we can see on Reddit. But maybe we could think about making the user vote count only visible to admins and mods?

**Comment by felipeforte** [comment]
> We had that before, but removed it because it creates an unhealthy obsession with upvotes, like we can see on Reddit. But maybe we could think about making the user vote count only visible to admins and mods?

This is true, you can really see that obsessive behavior happening on Reddit. I wonder, however, if this obsession isn't actually a byproduct of the unhealthy environment of Reddit itself?

One way to resolve all of this is to have this feature, but as an option that admins can easily disable. That way, if admins realize that the public upvote counting is leading to some unhealthy obsession with this feature, with a click of a button, it can be disabled.

Besides the obsession, one other thing I've noticed with the public upvote counting is that it's a subtle behavioral reinforcement of content creation and social interaction. And considering Lemmy is a competitor to Reddit, a strategy to promote content creation doesn't sound like a bad idea. With the option to disable it when needed, this could prevent any unhealthy behavior caused by this feature, ensuring psychological health of all users.

**Comment by dessalines** [comment]
Somewhat related to this, but I'd really like to see some articles written by some psychology nerds about potential ways that we could still show comment / post scores, and have it be transparent, but maybe hide it behind a layer or something? to  mitigate the damage of approval seeking. Could be an optional setting too.

**Comment by felipeforte** [comment]
Returning to this discussion, I still maintain that public up/down vote counting is very useful. In my experience with Lemmy, in most communities you are upvoted or downvoted rarely based on your opinion, but mainly on how you present it. Approval seeking cannot be eliminated both with or without public vote counting, because it's a natural human behavior.

But I believe the arguments both @Nutomic and @dessalines have presented are not considering the conditions of Lemmy, but of Reddit. On Reddit, it is indeed possible to see this phenomenon, because it's a bourgeois social media, it allows the use of bots to promote political and market propaganda and the vote counting feels extremely sketchy. 

While in Reddit, the up/down vote counting presents an unhealthy "social score" based on sketchy algorithm, in Lemmy, it would simply establish a quick way to determine which users have more negative or positive scores, which helps administrators when dealing with undesirables, such as trolls and provocateurs.

To mitigate an attachment with the growth of a number, typical of capitalist thinking, we could assign a percentage of approval of posts and comment based on an algorithm as well. Users who post too much undesirable content, would have a lower percentage than those whose posts have more positive reception, or something like that. It's my suggestion

**Comment by Nutomic** [comment]
I still think that a percentage of upvotes/downvotes would be way too simplistic to judge a user. You cant tell if a low score comes from trolling, or from expressing controversial opinions. And its clear from Reddit that such a system can be manipulated relatively easily, eg by reposting popular memes. So i dont think it would be a positive feature, its much better to take the time and judge people by what they say.

**Comment by felipeforte** [comment]
> And its clear from Reddit that such a system can be manipulated relatively easily, eg by reposting popular memes.

Yeah, considering that, I have to agree with you partially. But I believe it's possible to envision a scoring system that could prevent those issues. A percentage-based scoring system would prevent those who post only seeking to increase their score. There are many ways to design something like this, and this would be my suggestion: 

All new users would automatically have 100% score, and only when they are downvoted they lose it, or could be a ratio between up and downvotes. However, users with low scores would have less "weight" in determining other users' score, and users above a certain threshold would have normal weight determining other users' score. Users below a certain threshold do not count towards score-rating. Those who are eventually banned would have their votes discarded in determining other users' score. This would prevent the issue of those who raid a Lemmy just to downvote posts, which has happened before. This is also something that I believe is not implemented in Lemmy, which is removing the votes of banned users from the posts they like or dislike.

This is merely a crude suggestion I thought when taking into consideration the points raised here, which obviously has some flaws. But they can be fixed by further enhancing the ranking algorithm. A ranking system isn't simply to "judge" others, is to promote good and accepted behavior from users. A ranking system, if well designed, can be very useful in promoting the social health and well-being of a community.
