### ISSUE TITLE
`GetPosts` can return results for wrong community

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1271]
The problem happens if we are following a remote community which is named identically to a local community. When viewing the local community, the frontend sends a request `GetPosts` with the `community_name` parameter set. This parameter doesnt differentiate between local or remote community, so it is essentially random which community posts are returned. 

One potential solution would be changing the parameter to `local_community_name`, and only searching local communities so there can be no ambiguity. But then we still need to change the frontend to set `community_id` instead, so that remote communities are shown correctly. I think it might be better to completely remove the `community_name` to avoid confusion.

The same problem likely exists wth `GetComments`.

Edit: The same problem can happen with `GetUserDetails.username` as well.

**Comment by dessalines** [comment]
The main issue here is to avoid double fetching.

We have two types of urls:
- /c/community_name
- /community/id (which we have to use for federated communities)

So not just lemmy, but any front end client, without the optional community_name one, if all they have is the name, would have to fetch to get the community id, then do a second fetch to get the posts.

We have two types of urls:
- /c/community_name
- /community/id (which we have to use for federated communities)

I think lemmy-lite asked for this first, but I ended up using it in lemmy-js too cause its faster.

> This parameter doesnt differentiate between local or remote community, so it is essentially random which community posts are returned.

That's true, but its also not an issue as long as we only use the `/community/id` urls for federated communities.
