### ISSUE TITLE
RSS feeds dont validate

### ISSUE THREAD

**Issue by phelix001** [LemmyNet/lemmy#1274]
### Is your proposal related to a problem?
Not totally.

Currently you have feeds of the sites that posts point to, but you do NOT have feeds of the links of the posts.  I think this might be a mistake, because generally you **want** to use the feed to promote the community via social media.   You have twitter and og tags in the posts, so it looks like you were cognizant of making it look good on social media.

### Describe the solution you'd like

I'd like a feed address like the one you have now that is 
instance/feeds/community.xml  
but maybe instance/feeds2/community.xml

<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="https://www.w3.org/2005/Atom">
<channel>
    <atom:link href="https://instance/community/feed/" rel="self" type="application/rss+xml" />
<title>instance community RSS FEED</title>
<link>https://instance/community</link>
<description>This is an RSS feed for the links of instance - community</description>
<language>en-us</language>

<image>
        <title>https://Instance/community RSS FEED</title>
        <url>https://instance/community/image.jpg</url>
		<link>https://instance/community</link>
</image>

<item>
 		<title>PostTitle</title>
  		<pubDate>Thu, 14 Feb 2019 11:51:39 -0800</pubDate>
		<guid isPermaLink="false">ItemImage</guid>
		<link>https://instance/community/postlink </link>
     	 	<description>Body if no body then title</description>
 </item>

This will allow community members to automate promotion of links in the communities via social media.

**Comment by dessalines** [comment]
I'm not exactly sure what this means. You mean that link posts should also include the `/post/id` url, and not just the link?

**Comment by phelix001** [comment]
yes, when using sites like twibble or dlvr.it, they use the rss feed, but the post link isn't in it.

**Comment by phelix001** [comment]
Melissa V. (dlvr.it support)Nov 17, 2020, 10:15 PSTHello,You are correct that the feed is malformed. I've provided more information about that below. Unfortunately, while the feed is malformed, we cannot correctly implement any resolutions to problems because our system isn't going to function predictably when the feed is malformed. [https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdev.lemmy.ml%2Ffeeds%2Fc%2Fannouncements.xml](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdev.lemmy.ml%2Ffeeds%2Fc%2Fannouncements.xml)   Melissa V. \| Exceptional Experience Advocatedlvr.it \| dlvr.it blog \| dlvr.it supportEverQueue: Recycle Your Evergreen Content. Endlessly.
--

**Comment by dessalines** [comment]
I've tried 2 different local RSS clients and it works. They'll need to be more specific about how the feed is malformed.

**Comment by Nutomic** [comment]
@dessalines The validator link shows a couple of errors: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdev.lemmy.ml%2Ffeeds%2Fc%2Fannouncements.xml
