### ISSUE TITLE
Get rid of Match in lemmy_websocket.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1277]
The timings using `cargo bloat --release` show that the match in lemmy_websocket is our slowest function. Options:

- Try to replace with a hashmap
- Split out the function a bit?

**Comment by Nutomic** [comment]
I did another try without sccache, and the compilation got even slower (https://github.com/LemmyNet/lemmy/issues/1139#issuecomment-732318295). No idea whats going on, but its possible that this wouldnt actually help.

**Comment by dessalines** [comment]
I don't think this one is really valid, bloat shows that its the largest, but that's because it contains all the websocket route logic. Greatly doubt anything's gonna be faster than a match. We can re-open later if necessary.
