### ISSUE TITLE
Can view posts, profiles, and communities without signing up

### ISSUE THREAD

**Issue by DuelTheBearded** [LemmyNet/lemmy#1278]
As you know, I had been unjustly banned. I have been keeping my eye on Lemmy, as I think it is an interesting idea, and I would like to replicate the idea of a Rust reddit-like platform, but better. 
I have found a glitch, where I do not have to sign up to view people's profiles, posts, and communities.
![image](https://user-images.githubusercontent.com/37164157/100136065-83502700-2e58-11eb-94a4-7ef724c06db8.png)
As you can see, I can view posts
![image](https://user-images.githubusercontent.com/37164157/100136267-d0cc9400-2e58-11eb-8eb9-2ae6d7fb2bbe.png)
And profiles. I would also suggest fixing the visual problems that are on this page.

I would suggest fixing these problems.

**Comment by Nutomic** [comment]
Yes thats how Lemmy works.
