### ISSUE TITLE
Login hangs forever on login on Firefox for iPhome

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy#1288]
### Issue Summary

When I try to login on lemmy.ml using firefox (and only on firefox) there is an endless spinner.

Im using an iPhone 6s on the latest ios

I tried disabling the tracking protection but that doesnt fix it.

### Steps to Reproduce

1. I clicked login, and an endless spinner shows up.

**Comment by Nutomic** [comment]
Can you view the browser logs somehow, and see if there are any errors?

**Comment by NIXOYE** [comment]
That sadly doesn’t seem to exist on iPhones

**Comment by dessalines** [comment]
I don't have an iphone so I can't replicate / test this.

**Comment by NIXOYE** [comment]
any tips on what I can do to help figure out what's causing the bug?

**Comment by dessalines** [comment]
Not sure, I also don't have a mac so I wouldn't be able to help there either.

**Comment by NIXOYE** [comment]
Oh, I meant so I can test it. I tried using lambdatest.com and browserstack.com but browserstack's free time limit ran out after about a minute so I couldn't get any information and lambdatest only allowed me to test on an iphone 11 with firefox which allowed me to login.

**Comment by eiknat** [comment]
are you using autofill?

**Comment by NIXOYE** [comment]
I was but even when I copy paste my password it doesn't work

**Comment by MarcusE1W** [comment]
Same problem here. iPad with latest iOS and Firefox for iOS
