### ISSUE TITLE
Deleting account does not work

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy#1289]
### Issue Summary

Clicking the "Delete account" button having entered the password seems to delete the account but doesn't. I can still login to it.

I read on #730 that the data is not removed, but the login to that account should be unabled; and the account should disappear completely, also from instance users.

**Comment by dessalines** [comment]
This is fixed on `main`, but not deployed yet. Federated deletes will come with https://yerbamate.ml/LemmyNet/lemmy/pulls/144
