### ISSUE TITLE
Forum mode \ sort by recently commented

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy#1294]
I think it would be really useful to have a Forum mode sorting option. Especially for smaller\slower communities it would be great to see topics go to the top based on which has been recently commented on and have any thread I comment on give me a notification if there's been new replies whether or not its been to my comment.

**Comment by dessalines** [comment]
What is forum sorting? The default is currently activity sort, so new comments will push them up, but there's also hot, new, etc.

**Comment by NIXOYE** [comment]
What does Activity mean exactly? I thought it was a mix of comments and upvotes. Pressing the ? takes you to the doc page but it doesn't have any info on Active view mode only hot new and top.

Also the Forum Mode im referring to would give you notifications on new comments on threads you comment on or decide to "watch"

**Comment by dessalines** [comment]
Ah thanks, I better add a line there for activity. Its described more here: https://lemmy.ml/docs/about_ranking.html

**Comment by NIXOYE** [comment]
Thanks. 

Active is great and definitely better than Reddit but doesn't quite do what I was referring to. For example on the Blender forum we might be discussing a technique used to create water that looks like a Studio Ghibli movie's water. This thread could go on for weeks\months and continue to be updated with new and more efficient techniques. With the way it works in forums people going to the recently updated section (which would be people changing to forum\recently updated Sort Type on lemmy) people who have never seen the thread will see it as new posts\techniques are added to the thread. and if I ever commented in the thread or clicked on "watch" thread I can continue to receive notifications on the whole thread.

I think this is a great way to make it feel more like a community and it also can cut down on the same threads\questions being posted multiple times.

**Comment by dessalines** [comment]
For long-running things like that, it'd be good to use a stickied post. But also you'll still get notifications, but only if you're tagged. I spose we could add another `recently_commented` sort, just like we have for `new`. Might have time to work on that much later tho, only two of us juggling a lot of priorities.

**Comment by NIXOYE** [comment]
A stickied post would require mod approval though and would keep it stickied even after people stop posting on the thread. The idea is for a thread the community is active in can stay in the public sphere of attention and die off when people stop commenting but have the possibility of being revived when new information\techniques are found out. This way there can be one post about Blender water studio ghibli that can be posted on even a year after if a new technique is discovered. So information on the past and current approaches can be found in one place instead of spread throughout many threads. 

When googling an issue and looking for the solution on reddit you need to search through dozens of threads all with different information. Threads posted sometimes days apart with the most recent threads not having the solution but the past threads having the solution. Reddit also forcefully locks a thread after some time forcing a whole new thread being needed to be created instead of a past one being updated. 

The current way reddit and kinda lemmy work makes things much more ephemeral instead of how forums etc used to work which was more "stuff on the internet last forever" way where old posts etc can be updated throughout the years making information much easier to find\update instead of creating a ton of unnecessary waste and confusion.

I don't mean to write paragraphs and keep hammering this since I understand y'all have a ton of work on your plates. I just think this would be an extremely useful feature that has been overlooked in websites\apps which I think contributes to social media addiction of where we always need to constantly check things because after a couple days it'll be gone and basically be unsearchable (reddit, instagram, etc)

I'll stop now hehe

P.S. love the work being done on\for Lemmy  <3

**Comment by Nutomic** [comment]
Sounds like a sort by `New`, except that it takes the time of the last comment, instead of the post time. So basically like `Active` without considering the score.

**Comment by NIXOYE** [comment]
Yeah basically Active without score and then a separate option to enable watching threads (and option to watch threads automatically when commenting in it) like how it works on github

**Comment by dessalines** [comment]
I'll re-open as the new comment sort is a possibility.
