### ISSUE TITLE
Federated user bans

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1298]
When a user is banned from a community, let other instances know about it. This will require implementing a `Block/User` activity.

**Comment by dessalines** [comment]
This one is the most important to me atm out of the others. Copying from matrix:

So if user A is banned from Community B, instance B, they can still comment on their instance, and everyone on A can see it, and it doesn't show them as banned. Meanwhile on B it correctly rejects the comment and shows them as banned.
