### ISSUE TITLE
Option to hide subscribed communities for users

### ISSUE THREAD

**Issue by lapete** [LemmyNet/lemmy#1303]
### Is your proposal related to a problem?
Everyone can see which communities I subscribed to. I would like to keep that private.

### Describe the solution you'd like
I would like to have an option (rather opt out than opt in but both is fine) to have the subscriptions hidden. This should federate since instances display subscribed communities for remote users as well.

### Describe alternatives you've considered
I checked my settings and couldn't find such an option.

### Additional context
Since this should federate, I don't think it's an lemmy-ui issue.

On a side note, the contribution template here is a nightmare for anyone who doesn't already know markdown well. Github doesn't offer previews. There's a h3 section (triple hash), a outcommented block and something in () for each of the 4 points and it's unintuitive what's supposed to stay or be replaced. Going through some other feature requests, nobody uses the template so probably I'm not the only one who found it to be more confusing rather than seeing it as a guide.

**Comment by dessalines** [comment]
We don't have hides / blocks / or private communities yet, those are coming in the future.

**Comment by Nutomic** [comment]
@dessalines They are talking about this on the user profile:

![Screenshot_20201203_135106](https://user-images.githubusercontent.com/1044450/101020337-42e25e80-3566-11eb-9020-2a6cfa9626fa.jpg)

@lapete About the issue template, feel free to make a PR to improve it.

**Comment by aproposnix** [comment]
Sorry to ask, but will this be applied on the next release? I'm still seeing my subscribed subs on my public profile (on Lemmy.ml). 

Thank you.

**Comment by dessalines** [comment]
Yep.
