### ISSUE TITLE
Regression in transparent .png rendering?

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy#1305]
See top icon here:
https://lemmy.ml/c/opensourcegames

I think the transparency was working until very recently, and it works in other places on Lemmy with the same .png file.

**Comment by poVoq** [comment]
How come the transparency is working for the smaller icons then?

**Comment by dessalines** [comment]
Seems to be for specific thumbnail sizes, again, not inside lemmy. Open up an issue on pictrs.

Compare 
- https://lemmy.ml/pictrs/image/feJQkwnP0r.png?format=webp&thumbnail=96
- https://lemmy.ml/pictrs/image/feJQkwnP0r.png?format=webp&thumbnail=1000

**Comment by poVoq** [comment]
Cutting off a few pixels and reexporting the png from GIMP suddenly made it work.

On the other hand .gif files show an error in Lemmy when I try to upload them. Something about failing to validate, but the popup is gone too quickly.

**Comment by poVoq** [comment]
Also, if uploading a banner, would it be possible to not render the icon on the community page then? It looks really strange when both is enabled.

**Comment by dessalines** [comment]
> Also, if uploading a banner, would it be possible to not render the icon on the community page then? It looks really strange when both is enabled.

Both are optional, but you can't choose to not render one if the other exists.

I haven't messed with gif / mp4 support with pict-rs yet, especially since loading them by default would be a lot to download.

**Comment by poVoq** [comment]
This is rather confusing, did all the pictures got re-rendered on the upgrade to 0.8.10? Because again pictures that worked perfectly fine in 0.8.9, suddenly broke in regards to transparency.

Honestly, if this is really an upstream issue, than that library seems super flaky and it might be better to replace it with something working better.
