### ISSUE TITLE
Increase community names to more than 20 characters

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy#1306]
In version `0.8.9`, community names can not have more than 20 characters and this is very limiting, even strange because there's no any message explaining this.

Please, increase this length to at least 50 characters.

**Comment by dessalines** [comment]
No, this is why I have community display names. Community names are the short, url versions, use the display names for longer titles, with spaces, etc.

**Comment by Porrumentzio** [comment]
In some languages words are larger than in English. That's the reason why 20 characters can be too short.

**Comment by dessalines** [comment]
Then use the longer word for the community display name, and an abbreviation or shortened version for the URL.

**Comment by Nutomic** [comment]
I agree with this, not every language is as short as english. At least we can make it configurable.

**Comment by dessalines** [comment]
This is a bad idea, soon we're gonna have community short urls like `!communitynreallllllllllllllllllllllllllylongname@reallllyyyyyylongurl.com`

**Comment by Nutomic** [comment]
The worst problem that might cause is that the layout gets messed up a bit. And if needed we can easily ban such communities or instances. 

[Here is a website which shows word length in different languages](http://www.ravi.io/language-word-lengths). It might not be very accurate, but still gives a general idea. English has an average of 8.2 characters per word, while German has 11.6. So while a community name can comfortably contain 2 English words, thats wont be possible for German. So a hardcoded limit will just make Lemmy worse  for many people.

**Comment by Porrumentzio** [comment]
This was just my case, with Basque languages (take into account that declinative languages get larger).
I think there's no problem having larger names or at least letting it configurable by instance
