### ISSUE TITLE
Add ability to define a default language for the instance

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy#1307]
As some instances are language-oriented, it would be useful to be able to define which language would be the default for that instance.

The consequences are that the UI of that instance is the same language for all users and visitors, but that they are able to change that language on their preferences.

**Comment by dessalines** [comment]
> As some instances are language-oriented, it would be useful to be able to define which language would be the default for that instance.

Lemmy's default language is whatever your browser is set to. Language is a user preference, not an admin preference.
