### ISSUE TITLE
Feat. request: Could there be an option for sorting post(s) titles by the number of comments they've received?

### ISSUE THREAD

**Issue by marek-lach** [LemmyNet/lemmy#1312]
The posts with most/least number of comments on top, or bottom (regardless of how many upvotes a post has).

**Comment by dessalines** [comment]
Assuming this doesn't use time as a factor, it would be simple enough.

**Comment by marek-lach** [comment]
> Assuming this doesn't use time as a factor

No reason to, I think? Simply the number of comments on a post/link.
