### ISSUE TITLE
Content is not updated on previews

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy#1314]
### Issue Summary

When changing some content into a post, for example the title, the previews on links get the show content. This is a quite big problem. Maybe it has to see with #1310

### Steps to Reproduce

1. Create a post.
2. Send the link to somewhere where the preview is shown.
3. Edit the title of the post.
4. Send again the link and you'll see that the title remains as first. No matter if you refresh.

**Comment by dessalines** [comment]
What does "Send the link to somewhere where the preview is shown" mean? Like posting it to another platform? Of course they're going to cache that, it has nothing to do with lemmy.

**Comment by Porrumentzio** [comment]
Posting it into Discourse, Telegram... anywhere were the preview is showed.

I suppose that the software can manage what is shown into previews, so isn't it possible to show the current content?

**Comment by dessalines** [comment]
We have no control over other services caching page previews. You'll have to open tickets with them.
