### ISSUE TITLE
error message shows IP address of docker bridge 

### ISSUE THREAD

**Issue by tateisu** [LemmyNet/lemmy#1318]
### Issue Summary

![image](https://user-images.githubusercontent.com/333944/102172611-7618dc00-3edc-11eb-9731-77e0168d4ea3.png)

please don't show IP address in error message.
its  IP address is docker bridge, I don't want show it to end user.

### Steps to Reproduce
post Lemmy's content link to mastodon, then many link thumbnail crawler access to it.

### Technical details
   image: dessalines/lemmy:v0.8.10
    image: dessalines/lemmy-ui:v0.8.10

**Comment by Nutomic** [comment]
Sorry thats our mistake. We had the same problem on lemmy.ml and fixed it there, but forgot to add the fix to this repo. I added it now, so you can either manually apply the fix in https://github.com/LemmyNet/lemmy/commit/998e824bd84680fab4f815d8116fada9952ab0e4, or run the Ansible playbook to do it automatically.

**Comment by tateisu** [comment]
I will wait the docker image of next release…
