### ISSUE TITLE
Option to view nsfw posts for unauthenticated users

### ISSUE THREAD

**Issue by tateisu** [LemmyNet/lemmy#1320]
I created commus that named nsfw_on / nsfw_off  on my server,
then I created topics  that named nsfw_on / nsfw_off  on each commus.

(1) Of course, everything is visible to NSFW-allowed login user.
https://m1j.zzz.ac/media_attachments/files/105/388/472/944/578/885/original/d3d94170808b6f91.png

(2) After logout, I can see only the topics where both the community and the topic are NSFW OFF.
https://m1j.zzz.ac/media_attachments/files/105/388/477/109/808/543/original/2ff92ce4cc088b99.png

(3) After logout, I can see only the NSFW OFF community on the community list.
https://m1j.zzz.ac/media_attachments/files/105/388/480/210/034/459/original/d02a2bb999ca0e67.png

(4) After logout, I can see only the NSFW OFF topic on the topic list of NSFW OFF community.
https://m1j.zzz.ac/media_attachments/files/105/388/484/059/044/760/original/e67391f09d63bc84.png

My question is "How to discover NSFW commus/topics of remote server?"

After someone builds his Lemmy server, does he need to create each NSFW-allowed accounts for each remote server to explore the federation's content?

I've only been using Lemmy for a day, but I haven't found a way to receive spread(RTed/BTed) topics from other users. If so, the user has to explore the content himself.

If we need to create each account for each server just to explore NSFW content, that would greatly reduce the value of the federation concept.

**Comment by Nutomic** [comment]
We probably need to add an option for servers to display nsfw posts by default. Or an option for users without login to show nsfw (or both).

**Comment by tgxn** [comment]
I added this as a query param on the `/community/list` api in https://github.com/LemmyNet/lemmy/pull/3363
