### ISSUE TITLE
Have a way of purging "orphaned" user-uploaded images

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#1331]
This was discussed in the Lemmy Council Matrix room and I was told to make an issue. 

Once an image that has been uploaded to an instance's built-in pictrs instance no longer appears in the actual Lemmy instance's post, comment, user profile or community data, it is largely inaccessible and  should be deleted. Thumbnails grabbed from links where the link has been changed on the parent post should also be deleted. 

For example: If I uploaded image A.jpg for a post, but later decided to remove the URL to A.jpg or replace it, A.jpg should be scheduled for deletion since it no longer appears in the Lemmy instance. Similarly, if I linked to `example.com` and Lemmy grabbed a thumbnail image from it, but later changed the URL to `example.org`, the thumbnail to `example.com` should be deleted and a new thumbnail grabbed from `example.org` (currently the thumbnail forever stays the one from `example.com`, which can be confusing to viewers if the link has changed). 

The main reason is to save space (especially on tiny instances) and to honour user privacy by deleting images the uploader wants deleted. It also prevents people from taking advantage of the built-in pictrs instances by uploading images and hotlinking to them from other sites, which can fill a small instance up with irrelevant images. Finally, it is good for moderation as if the content the image is attached to is offensive to the point that the admin decided not just to remove it but purge its from the database, the associated images are most likely also problematic, plus images uploaded by people but were never linked to the actual Lemmy and thus difficult to moderate will also be deleted.

**Comment by dessalines** [comment]
This goes along with #904

**Comment by Nutomic** [comment]
Fixed by https://github.com/LemmyNet/lemmy/pull/1809.
