### ISSUE TITLE
Build for ARM

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1334]
This is mostly finished on the [ci-on-arm](https://github.com/LemmyNet/lemmy/tree/ci-on-arm) branch, but needs testing.

ARM builds for the frontend still need fixing (https://github.com/LemmyNet/lemmy-ui/pull/114)

**Comment by dessalines** [comment]
The only issue with this one, is that `node-prune` (which greatly decreases the lemmy-ui docker image size), is a go binary that doesn't work for arm. I'll probably just remove it so we can have arm builds, and although it'll increase the size of the docker image, its not that big a deal.

**Comment by dessalines** [comment]
I'm trying another build, but I'm not sure what to do if they keep timing out: https://cloud.drone.io/LemmyNet/lemmy/241/2/7

**Comment by dessalines** [comment]
If I comment everything else out, the ARM build finished in 57 minutes: https://cloud.drone.io/LemmyNet/lemmy/247/1/1

If an arm builder isn't immediately available, I don't know if they'll allow it to go over their 1 hour build clock.

**Comment by Nutomic** [comment]
@dessalines You can edit your comment on discourse.drone.io that we dont need the increased time limit after all.

**Comment by dessalines** [comment]
Done.

**Comment by Nutomic** [comment]
ARM builds are on Docker Hub now. We might have to adjust the Ansible playbook though, not sure about that.

https://hub.docker.com/r/dessalines/lemmy/tags

**Comment by dessalines** [comment]
Its kinda unfortunate because docker buildx lets you combine them into a single image with multiple archs, but I don't think we can do that with drone.

We can just add instructions in the ansible and docker that if you're using arm, you need to add the `-arm64` suffix to the images. I'll do that now.

**Comment by Nutomic** [comment]
With Ansible we can detect the architecture of the server, and adjust the image name (or use a different docker-compose.yml).
