### ISSUE TITLE
Lemmy not reporting local users, posts, comments accurately

### ISSUE THREAD

**Issue by realkinetix** [LemmyNet/lemmy#1340]
As per [this discussion](https://lemmy.ca/post/1185/), it appears Lemmy is not generating correct information in it's nodeinfo URL.

At the time of this writing, lemmy.ca is reporting 333 local users, but a DB select shows:

`lemmy=# select count(*) from user_ where local = 't';

 count 
-------
    10
(1 row)
`
The other stats information also appears to be inflated, showing all cumulative users, posts and comments that an instance knows about, rather than just the local count.

Also, it appears that the "openRegistrations" item is being shown as a child of "usage", rather than up as a heading/item on it's own at the same level as "usage".  I hope I have described that well enough.

### Steps to Reproduce

Check an instance's "/nodeinfo/2.0.json" against specific DB counts for local items.

Also, check https://lemmy.ca/nodeinfo/2.0.json for openRegistrations vs https://social.isurf.ca/nodeinfo/2.0 and https://yo.isurf.ca/nodeinfo/2.0.json

**Comment by realkinetix** [comment]
As of 0.9.0-rc.12 this isn't quite right yet with respect to the number of users being reported.

ldemo.isurf.ca is reporting 40 users, when it only has 3 local users.

**Comment by dessalines** [comment]
You probably ran this after I altered one of the migrations.

```
delete from site_aggregates;
insert into site_aggregates (site_id, users, posts, comments, communities)
  select id as site_id,
  ( select coalesce(count(*), 0) from user_ where local = true) as users, 
  ( select coalesce(count(*), 0) from post where local = true) as posts,
  ( select coalesce(count(*), 0) from comment where local = true) as comments,
  ( select coalesce(count(*), 0) from community where local = true) as communities
  from site;
```

**Comment by realkinetix** [comment]
I'm not sure if that ran or not... wasn't done manually, though.

Recommendations on what I should do with it currently?  Just wait for the non-RC code to get applied, or should I run something at moment?

**Comment by dessalines** [comment]
Run that in your database above.
