### ISSUE TITLE
Translate Readme

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1341]
It looks like Github doesn't support this, so we have to create files like `README.de.md` and link to them from the main readme.

**Comment by danielbartsch** [comment]
Why does the readme need to be translated?
I highly doubt that somebody who doesn't understand English is capable of deploying lemmy to their own server anyways. (since all the guides are english, too)

**Comment by Nutomic** [comment]
@danielbartsch Thats what the [lemmy-docs repo](https://github.com/LemmyNet/lemmy-docs#adding-a-new-language) is for.
