### ISSUE TITLE
Reddit Enhancement Suite.  Can we have some features from this?

### ISSUE THREAD

**Issue by Leopere** [LemmyNet/lemmy#1346]
Namely things like expanding all images/videos on a page for one.  This kind of expansion on the UI would be a wonderful value add.

**Comment by dessalines** [comment]
These are issues for lemmy-ui, not lemmy.

lemmy-ui already expands images by default also.

**Comment by Leopere** [comment]
Oh, weird, and yeah, sorry didn't know it was expanded now.  The last post I laid down here was last year. It was all in one repo.
