### ISSUE TITLE
Docker swarm stack

### ISSUE THREAD

**Issue by Leopere** [LemmyNet/lemmy#1347]
I'm a docker swarm user and a Traefik reverse proxy user, is it possible to not use the docker-compose.yml that's downloadable from the git source and still be maintainable?

**Comment by dessalines** [comment]
I don't know anything about docker swarm, or how that's different from docker-compose. You're welcome to try to figure out how to get swarm and traefik working, but we'll only support docker / ansible and nginx.

**Comment by Leopere** [comment]
That's a bummer, could you at least support just docker without nginx?

**Comment by dessalines** [comment]
If you want to use traefix instead of nginx, you'll have to build your own traefik config, we can't help there. A reverse proxy server is required tho.
