### ISSUE TITLE
Host Code Elsewhere than M$ Github

### ISSUE THREAD

**Issue by Digit** [LemmyNet/lemmy#1354]
gitlab, gogs, notabug, forgefed/vervis (federated git hosting!), others... https://alternativeto.net/software/github/?license=opensource

" any project that starts afresh as Microsoft-hosted is doomed to fail " -- schestowitz, upon seeing lemmy amidst discussion of reddit's shortcomings, several of which are shared with github.

**Comment by dessalines** [comment]
https://github.com/LemmyNet/lemmy#code-mirrors
