### ISSUE TITLE
Mark accounts as bot

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1357]
It should be possible for account owners to mark their account as "bot" through a checkbox in the profile. Other users should then have the option to hide posts from bot accounts. This is basically the same thing Mastodon does.

[Relevant discussion regarding glasgow.lemmy.social](https://lemmy.ml/post/47662)

**Comment by dessalines** [comment]
As part of this, I think bot accounts shouldn't be allowed to vote, and probably not be allowed to comment.

**Comment by Nutomic** [comment]
I agree on voting, but if they cant comment then that will just encourage bot owners to not use the bot tag. I would just add a user setting "show bot posts and comments", which would allow users to choose if they want to see content from bots or not.

**Comment by dessalines** [comment]
Ahh I see.
