### ISSUE TITLE
Reverse proxy with a directory?

### ISSUE THREAD

**Issue by BrianAllred** [LemmyNet/lemmy#1363]
I'd like to proxy to my Lemmy instance using `<domain>/lemmy`, but I'm not overly familiar with nginx. I've got directory proxies working with various services (Portainer, Deluge), but Lemmy has a few different location blocks with syntax I've never seen before.

Thanks.

**Comment by Nutomic** [comment]
If you want to use federation, it is not possible to run Lemmy in a subfolder, because certain paths need to be at the root. I suggest you use a subdomain instead.
