### ISSUE TITLE
Directly use `Url` type in database structs

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1364]
That would give us more type safety, as it ensures that we cant accidentally insert invalid Urls. It also means that we wont have to convert types manually all the time.

Problem is with these two errors:
`the trait AppearsOnTableschema::community::table is not implemented for Url`
`the trait diesel::Expression is not implemented for Url`

I didnt find any info in the docs about how to implement these traits. And its possible that we cant implement them in Lemmy, but they have to be implemented directly in diesel or url.

**Comment by weiznich** [comment]
You have two options here:
* Implement a new type wrapper for `url::Url` and then follow the normal procedure to add support for [custom types](https://github.com/diesel-rs/diesel/blob/master/guide_drafts/custom_types.md) (Note that this guide applies to the current state of the master branch, therefore you likely need do adjust some function signatures. The basic principle remains the same)
* Use `#[diesel(deserialize_as = "WrapperType")]` in combination with [`Queryable`](http://docs.diesel.rs/1.4.x/diesel/deserialize/trait.Queryable.html#deriving), which will you give at least read support. (A similar feature is implemented on master for `Insertable`, but this isn't released yet.)

**Comment by Nutomic** [comment]
Thanks @weiznich! We need write support, so the type wrapper seems like the right solution in our case. I tried to implement that based on the docs, but now I'm getting some errors which I dont understand. Maybe you could have a look at it in #1371?

In general it would be nice if you could add some more documentation for this. I checked the diesel docs before opening this issue, but didnt find anything related. It might be worth linking the guide drafts from http://diesel.rs/guides/ (with a disclaimer). And the custom types draft only talks about enums, a separate explanation for (wrapper) structs is probably necessary.

**Comment by weiznich** [comment]
> In general it would be nice if you could add some more documentation for this. I checked the diesel docs before opening this issue, but didnt find anything related. It might be worth linking the guide drafts from http://diesel.rs/guides/ (with a disclaimer). And the custom types draft only talks about enums, a separate explanation for (wrapper) structs is probably necessary.

Any help here is welcome. There is unfortunately only that much time each day, so I cannot do everything myself. The code for the web page is [here](https://github.com/sgrif/diesel.rs-website/) :wink:
