### ISSUE TITLE
Make Ansible Playbook work with ARM

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1366]
It should detect if the server is running ARM, and use the correct Docker images in that case (or a separate `docker-compose.yml` file). 

I dont have any ARM server to test with, so it would be good if someone could help with this.

**Comment by dessalines** [comment]
We could potentially avoid this by doing this what they call "the old hard docker manifest way" that can take images and combine them. https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by dessalines** [comment]
Not necessary anymore, since we just got multi-arch images working. The system will now which images to pull for its arch. 

iframely is the only one that doesn't have a multi-arch image now.

**Comment by Nutomic** [comment]
Okay, I opened #1369 for that.
