### ISSUE TITLE
"Captcha incorrect." is shown when creating admin user from /setup 

### ISSUE THREAD

**Issue by tateisu** [LemmyNet/lemmy#1372]
### Issue Summary
- create new lemmy instance, using docker, `dessalines/lemmy:0.9.0` and `dessalines/lemmy-ui:0.9.0`.
- setup section in `lemmy.hjson` was ignored, browser shows `https://{server-name}/setup` page.
- "Captcha incorrect." is shown when registering admin user. but captcha is not shown at all.
```
lemmy_1     | [2021-01-25T20:10:58Z ERROR lemmy_websocket::handlers] Error during message handling {"error":"captcha_incorrect"}
```

**Comment by tateisu** [comment]
![image](https://user-images.githubusercontent.com/333944/105761200-2b3bbb00-5f96-11eb-9f16-5db19e08acfb.png)

**Comment by dessalines** [comment]
Thanks, I'll take a look.

**Comment by dessalines** [comment]
I just tested this a ton, and its working correctly. Do you already have an admin in the DB?

`if !no_admins && Settings::get().captcha.enabled {`

It would only throw an error if you already have an admin created somehow in the DB.

**Comment by tateisu** [comment]
if this site already have admin, why this site redirects from / to /setup ?

2021年1月27日(水) 3:33 Dessalines <notifications@github.com>:

**Comment by dessalines** [comment]
I'm guessing because you somehow set up an admin user, but never set up the site:

```
    if (!this.state.siteRes.site_view) {
      this.context.router.history.push('/setup');
    }
```

Clear out the admin user, or start from a fresh `volumes` folder / DB.

**Comment by tateisu** [comment]
I haven't manually connected to the DB. The admin user must have been created in the setup section of lemmy.hjson.

**Comment by tateisu** [comment]
following steps works for me. thanks!
- docker-compose down
- sudo, then rm -fr volumes/postgres/*
- comment out setup section in lemmy.hjson
- docker-compose up -d

**Comment by dessalines** [comment]
Ya you got it, if the volumes folder gets not you sometimes have to clear it out if things got set up wrong.
