### ISSUE TITLE
RSS feed that returns the link to the post and not the the link to the content

### ISSUE THREAD

**Issue by phelix001** [LemmyNet/lemmy#1378]
[lemmy](https://github.com/LemmyNet/lemmy)

  The current rss feed of a discussion is located at 
https://dev.lemmy.ml/feeds/c/blender.xml
This returns an rss feed with the links to the original content.

I need an rss feed exactly like that but returns links to the post on lemmy for twtter posting to drive traffic to the conversation, not the content.

(Write your answer here.)

### Describe the solution you'd like

I'd like soemthing like 
https://dev.lemmy.ml/feeds2/c/blender.xml
that returns the link to the conversation, not the link to OC.

### Describe alternatives you've considered

  Let us know about other solutions you've tried or researched.

(Write your answer here.)

### Additional context

  Is there anything else you can add about the proposal?
It appears that the current feed creator doesn't work when its a selfpost because there is no OC to point to.
  You might want to link to related issues here, if you haven't already.

(Write your answer here.)

**Comment by Nutomic** [comment]
Check the `<comments>` or `<guid>` fields, those link to the post and should be exactly what you need.

**Comment by dessalines** [comment]
I'm actually in favor of changing even the main link field, to point to the lemmy post link instead. Not necessarily to drive traffic to lemmy (i don't care about that), but just that the conversations around the links can often be more important than the links themselves.

**Comment by Nutomic** [comment]
Can we still put the link somewhere in the RSS then? I'm not sure if there's a good field for that.

**Comment by dessalines** [comment]
```rust
    let mut description = format!("submitted by <a href=\"{}\">{}</a> to <a href=\"{}\">{}</a><br>{} points | <a href=\"{}\">{} comments</a>",
    p.creator.actor_id,
    p.creator.name,
    community_url,
    p.community.name,
    p.counts.score,
    post_url,
    p.counts.comments);

    if let Some(body) = p.post.body {
      let html = markdown_to_html(&body);
      description.push_str(&html);
    }

    i.description(description);
```

We could add it above the body, something like:

```rust
if let Some(url) = ....
```

**Comment by kixiQu** [comment]
Well, I was relying on that link. :/ Is there a reason not to use some other XML field for the external link? I've been under the impression that any parsing of the description was going to be extremely, uh, subject to change, so I really don't want to formally depend on its unspecified structure beyond what I'm already doing.

**Comment by Nutomic** [comment]
Before this change, we used to have the Lemmy post URL in `<comments>` and `<guid>` fields, and the external link (if any) in the `<link>` field. Now we have the Lemmy URL in all three fields, which really seems useless. I propose that we revert the commit https://github.com/LemmyNet/lemmy/commit/37ad9e9a099afe8852eeb5b43491423ab1a95465.

**Comment by dessalines** [comment]
We have a case here where someone wants the rss link field to go to the lemmy post link (which includes the conversation), and another wants it to go to the url link (not always there). Not sure how to resolve it other than taking it to a vote on lemmy.

**Comment by Nutomic** [comment]
@phelix001 Is there any reason why you want the `link` field specifically to go to Lemmy? Cant you read the Lemmy link from `comments` instead?

**Comment by kixiQu** [comment]
I would be perfectly happy, by the way, with the external URL being in some other field, if that's judged to be appropriate -- I'm just hoping it'll land in its own little XML field (perhaps in addition to the description). The current state is pretty close to what Reddit does, so it's certainly not unreasonable _prima facie_.

**Comment by Nutomic** [comment]
Well the only field that seems to make sense for the external URL is `link`. And it seems that phelix001 isnt active on Github, so we shouldnt expect a response from them anytime soon.

**Comment by phelix001** [comment]
I use an rss reader to post lemmy conversations to twitter to drive traffic to my lemmy instance.

For instance, posts in a Mars group would be autoposted to my @marsinfo twitter.  When twitter users click on the link it (should) go to my lemmy instance instead of to the article.

**Comment by dessalines** [comment]
Here are the items we are able to use with the current rss library:

```rust
    /// The title of the item.
    pub title: Option<String>,
    /// The URL of the item.
    pub link: Option<String>,
    /// The item synopsis.
    pub description: Option<String>,
    /// The email address of author of the item.
    pub author: Option<String>,
    /// The categories the item belongs to.
    pub categories: Vec<Category>,
    /// The URL for the comments page of the item.
    pub comments: Option<String>,
    /// The description of a media object that is attached to the item.
    pub enclosure: Option<Enclosure>,
    /// A unique identifier for the item.
    pub guid: Option<Guid>,
    /// The date the item was published as an RFC 2822 timestamp.
    pub pub_date: Option<String>,
    /// The RSS channel the item came from.
    pub source: Option<Source>,
    /// The HTML contents of the item.
    pub content: Option<String>,
    /// The extensions for the item.
    pub extensions: ExtensionMap,
    /// The Atom extension for the channel.
    #[cfg(feature = "atom")]
    pub atom_ext: Option<atom::AtomExtension>,
    /// The iTunes extension for the item.
    pub itunes_ext: Option<itunes::ITunesItemExtension>,
    /// The Dublin Core extension for the item.
    pub dublin_core_ext: Option<dublincore::DublinCoreExtension>,
```

**Comment by Nutomic** [comment]
@phelix001 Good that I was wrong and you saw the comments here. Could you please answer my previous question, why dont you read the Lemmy URL from the RSS `<comments>` field instead?

**Comment by phelix001** [comment]
dlvr.it or rss.app or other RSS readers don't let me map the fields.  The comments field WOULD work if it was listed as the link.  And if the link htmll has OG and or twitter tags it will look great.  I appreciate all the fine work you're doing on this project.  Thanks.

**Comment by dessalines** [comment]
I created a poll for this: https://lemmy.ml/post/55045

**Comment by dessalines** [comment]
The vote seemed to be clear that the lemmy url is preferred. But feel free to re-open this if there's anything I could do to make the post link easier to parse.

**Comment by phelix001** [comment]
@dessalines I'm not trying to be dense, but the lemmy link is the link to the lemmy instance, not the post, right?

**Comment by Nutomic** [comment]
@phelix001 correct

@kixiQu What you can do to get the external link is `curl -H 'Accept: application/activity+json' https://lemmy.ml/post/xxx` and extract it from the json.

**Comment by Nirose** [comment]
@dessalines would it be possible to output the external link with an additional URL query string? I'm trying to add lemmy to one of my [project](https://github.com/jucktion/swen) and it would be nice to not have to parse the description for the link. 

[Lemmy Tech](https://swen.ml/#tech,lemmytech)

## Describe the solution you'd like

You get the comments url with the default RSS, but add a `link=external` (just a suggestion) to get the external link in `<link>`.

Default:

`https://lemmy.ml/feeds/c/technology.xml?sort=Hot`

With external link:

`https://lemmy.ml/feeds/c/technology.xml?sort=Hot&link=external`

**Comment by Nutomic** [comment]
@Nirose Please open a new issue. And I think it makes more sense to just add another xml field for the external link, although i am not familiar enough with RSS format to know which field might be appropriate.

**Comment by bhepple** [comment]
Strange this is still a bug as the poll taken in 2021 was quite clear _and_ the RSS-2.0 [definition](https://www.rssboard.org/rss-specification#requiredChannelElements) of \<link> is

```
The URL to the HTML website corresponding to the channel.
```

so clearly, it should point to the lemmy post. No other RSS feed that I know of has this problem.

I have a fix for `elfeed` in case anyone wants it:
```
(defun bh/fix-entry (type xml entry)
  (let ((feed (elfeed-entry-feed-id entry)))
    (cond ((string-match-p ".*lemmy.*" feed)
           ;; lemmy links to subject matter instead of the discussion
           ;; - revert that:
           (let ((link (elfeed-entry-link entry)))
             (unless (string-match-p "https://lemmy\\.ml/feeds/c/" link)
               (setf (elfeed-entry-link entry) (cdr (elfeed-entry-id entry)))))))))
(add-hook 'elfeed-new-entry-parse-hook #'bh/fix-entry)
```

**Comment by dessalines** [comment]
I'm looking at the code right now, and both the comments and the link field go to `/post/xx`, which was the preferred option in that poll above.

**Comment by bhepple** [comment]
Hmmm, strange. I'm still getting rogue elements in \<link>. eg I got this feed from the linux feed in the last couple of days (specifically May 14 19:51 AEST 10 hours ahead of UTC)
```

    <item>
      <title>Recently started working on a collection of nix-colors adapters, what do you think?</title>
      <link>https://beehaw.org/pictrs/image/28e496e2-0d15-4781-ada3-6e3c1ce43e4a.webp</link>
      <description><![CDATA[submitted by <a href="https://beehaw.org/u/vfosnar">vfosnar</a> to <a href="https://lemmy.ml/c/linux">linux</a><br>39 points | <a href="https://lemmy.ml/post/15558006">0 comments</a><br><a href="https://beehaw.org/pictrs/image/28e496e2-0d15-4781-ada3-6e3c1ce43e4a.webp">https://beehaw.org/pictrs/image/28e496e2-0d15-4781-ada3-6e3c1ce43e4a.webp</a><p>cross-posted from:  <a href="https://beehaw.org/post/13758256">beehaw.org/post/13758256</a></p>
<blockquote>
<p>You can change the color theme of your whole desktop with a single line of code.</p>
<p>Currently supported adapters:</p>
<ul>
<li>Adwaita (GTK3, GTK4)</li>
<li>Alacritty</li>
<li>dunst</li>
<li>Firefox (hijacking the default theme with userchrome.css)</li>
<li>GTK2</li>
<li>Rofi</li>
<li>swaylock</li>
<li>Wezterm</li>
</ul>
<p>repo: <a href="https://gitlab.com/vfosnar/nix-colors-adapters">gitlab.com/vfosnar/nix-colors-adapters</a> / <a href="https://github.com/vfosnar/nix-colors-adapters">github.com/vfosnar/nix-colors-adapters</a></p>
</blockquote>
]]></description>
      <comments>https://lemmy.ml/post/15558006</comments>
      <guid>https://lemmy.ml/post/15558006</guid>
      <pubDate>Sun, 12 May 2024 16:27:41 +0000</pubDate>
      <dc:creator>https://beehaw.org/u/vfosnar</dc:creator>
    </item>
```

Let's try again with the emacs feed right now (May 17 07:30 AEST):

```

    <item>
      <title>[video] Emacs: modern minibuffer packages (Vertico, Consult, etc.)</title>
      <link>https://protesilaos.com/codelog/2024-02-17-emacs-modern-minibuffer-packages/</link>
      <description><![CDATA[submitted by <a href="https://sh.itjust.works/u/NanoooK">NanoooK</a> to <a href="https://lemmy.ml/c/emacs">emacs</a><br>16 points | <a href="https://lemmy.ml/post/15556390">0 comments</a><br><a href="https://protesilaos.com/codelog/2024-02-17-emacs-modern-minibuffer-packages/">https://protesilaos.com/codelog/2024-02-17-emacs-modern-minibuffer-packages/</a>]]></description>
      <comments>https://lemmy.ml/post/15556390</comments>
      <guid>https://lemmy.ml/post/15556390</guid>
      <pubDate>Sun, 12 May 2024 15:37:38 +0000</pubDate>
      <dc:creator>https://sh.itjust.works/u/NanoooK</dc:creator>
    </item>

``` 
I got those feeds directly with wget, so no possibility of any shenanigans.

**Comment by bhepple** [comment]
```
wget "https://lemmy.ml/feeds/c/emacs.xml" -O ~/tmp/emacs2.xml
```

**Comment by dessalines** [comment]
Anyway here is the line for link: https://github.com/LemmyNet/lemmy/blob/1a4aa3eabaed2b197d014fb99261e33b6d5dc656/crates/routes/src/feeds.rs#L581

**Comment by bhepple** [comment]
You mention that beehaw is out of date - I don't know how this all works but are you saying that when I wget from lemmy, the feed is composed on the originating instance ie beehaw? ie lemmy.ml might be doing the right thing but beehaw ain't?

**Comment by dessalines** [comment]
If the rss feed is `https://lemmy.ml...`, then it should be fine. I'll double check the code tho, there might be an issue with non-post feeds.

**Comment by dessalines** [comment]
Okay I figured it out:

The tag that contains this fix commit isn't deployed yet. It'll be in the next release.

`git tag -l --contains 8a6a86c1bb`
