### ISSUE TITLE
Use Url type in remaining database structs

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1385]
There are a couple fields in `crates/db_schema/` which contain URLs but have type String, for example `Post.url` or `Community.icon`. These should use the same `Url` type introduced in #1371.

Edit: These should be all fields which need to be changed to URL:

- `Post.url`
- `Post.thumbnail_url`
- `User_.avatar`
- `User_.banner`
- `Community.icon`
- `Community.banner`
- `PostReport.original_post_url`
- `Site.icon`
- `Site.banner`
- `Activity.ap_id`

**Comment by Nutomic** [comment]
When this is fixed, we can also remove the function [check_optional_url()](https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/lib.rs#L175).

**Comment by ajyoon** [comment]
I can take a crack at this

**Comment by dessalines** [comment]
Sure thing!
