### ISSUE TITLE
'Invalid type' WebSocket API response to SaveUserSettings

### ISSUE THREAD

**Issue by gazconroy** [LemmyNet/lemmy#1388]
### Issue Summary

Attempts to update profile with SaveUserSettings return error message 'invalid type: null, expected struct SaveUserSettings at line 1 column 4'

### Steps to Reproduce

1. Access ws://enterprise.lemmy.ml/api/v2/ws with WebSocket client
2. Attempt to update a test profile with the following form data:

```
{
  "op": "SaveUserSettings",
  "show_nsfw": false,
  "theme": "darkly",
  "default_sort_type": 1,
  "default_listing_type": 0,
  "preferred_username": "Queen of the Griddle",
  "email": "jane.doe@humanity.org",
  "bio": "I am a watercolour artist. I am happy to share the paintings I am working on, give and receive critiques, and post resources such as tutorials.",
  "matrix_user_id": "string",
  "new_password": "lemmy",
  "new_password_verify": "lemmy",
  "show_avatars": true,
  "send_notifications_to_email": false,
  "auth": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzcsImlzcyI6ImVudGVycHJpc2UubGVtbXkubWwifQ.8UbfUE1v4mfH88s2diX2h6_5bzLHSa_5wIlpOZmHbMQ"
}
```

### Technical details

* Using WebSocket Client for MacOS - https://websocket-client.com/

**Comment by dessalines** [comment]
```
export interface SaveUserSettings {
  show_nsfw: boolean;
  theme: string; // Default 'default'
  default_sort_type: number; // The Sort types from above, zero indexed as a number
  default_listing_type: number; // Post listing types are `All, Subscribed, Community`
  lang: string;
  avatar?: string;
  banner?: string;
  preferred_username?: string;
  email?: string;
  bio?: string;
  matrix_user_id?: string;
  new_password?: string;
  new_password_verify?: string;
  old_password?: string;
  show_avatars: boolean;
  send_notifications_to_email: boolean;
  auth: string;
}
```

Might be missing `lang`. Also if you set a new password, you need to provide the old_password.

**Comment by gazconroy** [comment]
I'm still getting the same error message if _lang_ and _old_password_ are specified...

**Comment by dessalines** [comment]
Ah my bad I see. All websocket requests musts be `let send = { op: UserOperation[op], data: data };`

For some reason you have everything at the top level. Only op and data should be at the top level. And data contains that form.

**Comment by gazconroy** [comment]
Apologies. A 'doh!' moment from me. That works perfectly well.

**Comment by gazconroy** [comment]
User error

**Comment by dessalines** [comment]
Haha no probs :smile:
