### ISSUE TITLE
Repeated voting doesn't work as expected

### ISSUE THREAD

**Issue by nogerine** [LemmyNet/lemmy#1389]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

When up- or down- voting twice in a row, 2 things happen: the number of points updates correctly, BUT the button remains "lit up".
Pressing the same button again, the points momentarily go in the opposite direction and the button remains colored.

Alas, I suck at explaining stuff. There should be an attached video showing this bug.

### Steps to Reproduce

1. Upvote a random post
2. Upvote the same post again
3. Observe
4. Upvote it the third time
5. Notice the incorrect behavior

### Technical details

There were no console errors. There were 3 `"CreatePostLike"` objects, the first one had `score: 1`; second and third both had `score: 0`.

---

https://imgur.com/a/49NJIa9 (can someone recommend a good platform for sharing small videos like this one). For some reason I couldn't attach via github.

**Comment by dessalines** [comment]
This was a bug that got introduced with the diesel migration. 

Before, the post and comment `my_vote` was `0`, and after the migration, (because of how the join changed), it was `null`. I now changed it back to `0`, for that case of it being your vote.
