### ISSUE TITLE
Add Lemmy to awesome-humane-tech list

### ISSUE THREAD

**Issue by fsondej** [LemmyNet/lemmy#1394]
[Amesome Humane Tech](https://github.com/humanetech-community/awesome-humane-tech) is a list aggregating some great projects focusing on freedom and human well-being. Lemmy would certainly fit there, and listing it there would attract more users, who have never heard of it.

**Comment by dessalines** [comment]
Could you do a PR over there to add lemmy? Thx.

**Comment by fsondej** [comment]
Done
https://github.com/humanetech-community/awesome-humane-tech/pull/67

**Comment by dessalines** [comment]
Sweet thx!

**Comment by aschrijver** [comment]
This is just a FYI comment to notify that you were added via @fsondej PR to the curated awesome-humane-tech in the 'Fediverse' category, and - if you like that - are now entitled to wear our badge:

[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)

By adding this to the README:

```markdown
[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)
```

https://github.com/humanetech-community/awesome-humane-tech

**Comment by dessalines** [comment]
Will do!
