### ISSUE TITLE
No responses from GetModLog 

### ISSUE THREAD

**Issue by gazconroy** [LemmyNet/lemmy#1413]
I can't seem to get a response to GetModLog from the API (connected to the enterprise.lemmy.ml WebSocket). I've tried:

```
{
  "op": "GetModLog",
  "data": {
    "mod_user_id": 7,
    "community_id": 76,
    "page": 0,
    "limit": 0
  }
}
```

And

```
{
  "op": "GetModLog",
  "data": {
    "mod_user_id": 7
  }
}
```

And

```
{
  "op": "GetModLog",
  "data": {
  }
}
```

All with no joy. What am I missing?

**Comment by Nutomic** [comment]
This is what the frontend sends according to the browser console:

```
{
  data: {
    community_id: undefined
    limit: 20
    page: 1
  ​​}
  op: "GetModlog"
}
```

**Comment by dessalines** [comment]
I'm guessing its cause @gazconroy is using page `0` and not page `1`

**Comment by gazconroy** [comment]
Same (no) result if page is set to 1...

**Comment by dessalines** [comment]
```
export interface GetModlog {
  mod_user_id?: number;
  community_id?: number;
  page?: number;
  limit?: number;
}
```

Limit should also not be 0, and both it and page are optional. As far as the mod_user_id and community_id, I don't have your specific id numbers so I can't verify.

**Comment by gazconroy** [comment]
This is the request for 'The Deafult Community' (id 2) and 'Nutomic' (id 2) on the Enterprise server.

```
{
  "op": "GetModLog",
  "data": {
    "mod_user_id": 2,
    "community_id": 2
  }
}
```

Aplogies for my error, there _is_ a response but the response is _Matching variant not found_. Omitting mod_user_id gives the same response

**Comment by gazconroy** [comment]
Getting a similar 'Matching variant not found' on GetCommunity:

```
{
  "op": "^GetCommunity$",
  "data": {
    "id": 2,
    "name": "The Default Community",
    "auth": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzcsImlzcyI6ImVudGVycHJpc2UubGVtbXkubWwifQ.8UbfUE1v4mfH88s2diX2h6_5bzLHSa_5wIlpOZmHbMQ"
  }
}
```

**Comment by dessalines** [comment]
Oops you're right, this is a bug in the modlog code having to do with paging.

**Comment by dessalines** [comment]
nm, lowercase `L` is your issue:

```
websocat wss://enterprise.lemmy.ml/api/v2/ws
{ "op": "GetModlog", "data": { "mod_user_id": 77, "community_id": 281 } }
```

`GetCommunity` also checks out fine, you have some weird characters in the op.

```
websocat wss://enterprise.lemmy.ml/api/v2/ws
{ "op": "GetCommunity", "data": { "id": 2, "name": "The Default Community", "auth": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzcsImlzcyI6ImVudGVycHJpc2UubGVtbXkubWwifQ.8UbfUE1v4mfH88s2diX2h6_5bzLHSa_5wIlpOZmHbMQ" } }
```

**Comment by gazconroy** [comment]
Actually seems like a bug in the WebSocket client I am using. I will use websocat in the future
