### ISSUE TITLE
Faster communities' search

### ISSUE THREAD

**Issue by Kohoshi12** [LemmyNet/lemmy#1417]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

I can't understand why I can't search for a community using the "!" sign and it's instance adress.

### Describe the solution you'd like

Let the user search directly for communities using "!" on the search area, for example !test inside of lemmy.ml and !test@lemmy.ml outside or inside of lemmy.ml. The user won't need to select the "communities" filter in this way. This will make the search faster and reliable.
I noticed it's not possible to search for the communities using the instance adress anymore. maybe because now the communities nicknames now are acting like the real communities' adresses, I would love to do the searches like before.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by dessalines** [comment]
We're not going to add a custom query language for searching for specific entities right now. Filtering needs to be done by those filters. We'll even be adding more filters to that search page in the future.

**Comment by Nutomic** [comment]
Is this what you mean? It should work fine, though we currently dont support the format `!announcements` for local communities.

![Screenshot_20210208_130751](https://user-images.githubusercontent.com/1044450/107217621-539bce80-6a06-11eb-9423-e718fa76a599.jpg)

![Screenshot_20210208_130757](https://user-images.githubusercontent.com/1044450/107217627-55fe2880-6a06-11eb-9e9a-ce0f5dfe763c.jpg)

**Comment by Kohoshi12** [comment]
Yes
