### ISSUE TITLE
Uploaded images in posts not being saved

### ISSUE THREAD

**Issue by revmischa** [LemmyNet/lemmy#1418]
### Issue Summary

When I create or edit a post with an image in it, the image usually does not appear on the post page after saving.
I can add images in comments and they seem to appear without issue.
After refreshing the page my deleted comment (with the image) re-appears as undeleted for some reason which is strange as well.

Video: https://imgur.com/a/m7wtQYv

### Steps to Reproduce

1. Create or edit a post with an uploaded image in the body

### Technical details

Running 0.9.6 on backend and main on lemmy-UI (with my WS patch)

**Comment by Nutomic** [comment]
Is there anything relevant in the logs of lemmy, lemmy-ui or pictrs?

**Comment by revmischa** [comment]
Tried to reproduce to get logs and now it's working. Will reopen this if I encounter it again and have more useful logs.
