### ISSUE TITLE
Support different Accept headers for ActivityPub routes

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1420]
I've seen these accept headers mentioned by other devs:

`application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams", text/html;q=0.1`
`application/ld+json`

At the moment, Lemmy only supports `application/activity+json` and `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` which are mentioned in the Activitypub standard. We should probably implement some parser which allows those different headers, without having to hardcode them. Need to figure out how this works in actix.

**Comment by dessalines** [comment]
As part of a cleanup to this, I found a few hard-coded refs to `activity+json`: 

```
✗ rg 'activity\+json' .
./crates/apub/src/lib.rs
51:pub static APUB_JSON_CONTENT_TYPE: &str = "application/activity+json";

./crates/apub/src/activities/send/comment.rs
427:    .find(|l| l.type_.eq(&Some("application/activity+json".to_string())))
428:    .ok_or_else(|| anyhow!("No application/activity+json link found."))?;

./crates/routes/src/webfinger.rs
83:        type_: Some("application/activity+json".to_string()),
```

**Comment by Nutomic** [comment]
Those are for webfinger, not sure if those should be handled differently, but it should be a separate issue.

**Comment by Nutomic** [comment]
from @asonix:

> looks like you'd need to write a custom Guard implementation that pulls the Accept header and parses with this: https://docs.rs/actix-web/4.0.0-beta.10/actix_web/http/header/struct.Accept.html
> actually, it looks like parsing an Accept from a request requires an HttpMessage type, and RequestHead (available from a guard) doesn't implement HttpMessage
> so it may be more complicated

**Comment by Nutomic** [comment]
@dessalines Actually this is not just a problem in the backend, but we would also have to handle all these different, valid headers in nginx somehow. I dont think that would work well. A much better (and easier) solution would be to remove these conditionals in nginx, so that all requests go through lemmy-ui, and then lemmy-ui forwards all requests to the backend which do **not** have `Accept: text/html`. Then we would also remove the header guards in the backend.

**Comment by dessalines** [comment]
I don't think its a good idea for the back end to rely on lemmy ui rewriting requests. Some instances might even not want to run the ui, or run their own custom thing. 

I think it might be possible to do with nginx, but also don't we already support multiple accept types in the back end?

**Comment by Nutomic** [comment]
Then we can mention on the [custom frontend page](https://join-lemmy.org/docs/en/client_development/custom_frontend.html) that they need to forward these requests for federation to work. And wouldnt be "relying on lemmy-ui to rewrite requests". The backend would simply always respond with the json (no matter the headers), and the frontend would decide (based on Accept header), which requests to handle directly, and which to pass to the backend. So basically [these if statements](https://github.com/LemmyNet/lemmy-ansible/blob/main/templates/nginx.conf#L63) would move to lemmy-ui.

**Comment by dessalines** [comment]
This will route any of the application accepts to the back end:

https://github.com/LemmyNet/lemmy-ansible/pull/14
