### ISSUE TITLE
Temporary bans

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1423]
Mods/admins should be able to ban users for a limited amount of time.

**Comment by MrLuxuri** [comment]
But they should also be required to give proper reasoning before banning, also other few people in the community should accept the step taken by mod in-order to fully proceed with the temporary ban, if not, they can just give any reasoning and ban anyone. There should also be a limited number of times like 2 times to ban the same user in a month or so, if not they can keep banning after the limited time of a single temporary ban is finished.

**Comment by Nutomic** [comment]
@MrLuxuri I dont think those things should be enforced on a technical level. If a mod does that and causes problems, the users should tell the admins, who can remove the mod if needed.

**Comment by MrLuxuri** [comment]
> @MrLuxuri I dont think those things should be enforced on a technical level. If a mod does that and causes problems, the users should tell the admins, who can remove the mod if needed.

I mean't what if the admin itself does it? Like the admin of the community? Who created it?

**Comment by MrLuxuri** [comment]
> > @MrLuxuri I dont think those things should be enforced on a technical level. If a mod does that and causes problems, the users should tell the admins, who can remove the mod if needed.
> 
> I mean't what if the admin itself does it? Like the admin of the community? Who created it?

There should at least be a limit to temp ban the same person in a month or so.

**Comment by dessalines** [comment]
I disagree. These should not be in the code.

**Comment by Nutomic** [comment]
> I mean't what if the admin itself does it? Like the admin of the community? Who created it?

If the instance admin does bad things, they can also recompile Lemmy to remove any limits. The only thing you can do against a bad admin is look for a different instance.
