### ISSUE TITLE
Add Two-factor Authentication (2FA)

### ISSUE THREAD

**Issue by Kruger984** [LemmyNet/lemmy#1434]
### Description
I believe you are already aware about what I am trying to suggest here. 2FA plays a major role in improving the security of an account on Social Media sites (nowadays, it is very much needed on every platform which has accounts). 2FA using a third party mobile app like Aegis, AndOTP, Google Authenticator, Authy etc is a very good security feature imo. Reddit also has it and it would be really nice to see it on Lemmy.

**Comment by dessalines** [comment]
We have wayyy too many other things on our plate right now, but if someone else wants to take a crack at it go ahead.

**Comment by StaticallyTypedRice** [comment]
Just curious, what kind of 2FA are you looking at right now? Email? Text? Authenticator app?

**Comment by TuxKruger** [comment]
I personally prefer Authenticator App (and sometimes Text) over Email because if your Email is compromised, 2FA can do nothing. In case of Authenticator app, you can locally store the tokens instead of relying on a cloud service and in case of Text, only you have your SIM card. Ofcourse there are various ways to  steal Tokens and Text messages but they are much difficult compared to Email.

**Comment by Mart-Bogdan** [comment]
Relates to #1368


PS. Doesn't using google authenticator go against Federation ideas?

**Comment by TuxKruger** [comment]
> Relates to #1368
> 
> 
> PS. Doesn't using google authenticator go against Federation ideas? 

Google authenticator only stores the tokens just like any other 2FA app. How is it against federation? It isn't affecting decentralisation and federation for Lemmy at least. Also I only used it as an example because I think most people know about it unlike other FOSS 2FA apps like Aegis.

**Comment by Mart-Bogdan** [comment]
> Google authenticator only stores the tokens just like any other 2FA app. How is it against federation? 

Actually my bad. I thought the backend needs to talk to the google server, to verify TOTP.

It seems it could be made offline.

I am wondering are there available libs that are supporting different 2fa providers at the same time like Aegis, AndOTP, GoogleAuthnticator etc? it don't have to be in Rust

**Comment by TheEvilSkeleton** [comment]
I'm pretty sure Computerphile explains how 2FA works: https://www.youtube.com/watch?v=ZXFYT-BG2So

**Comment by Kellegram** [comment]
> 
> 
> > Google authenticator only stores the tokens just like any other 2FA app. How is it against federation?
> 
> Actually my bad. I thought the backend needs to talk to the google server, to verify TOTP.
> 
> It seems it could be made offline.
> 
> I am wondering are there available libs that are supporting different 2fa providers at the same time like Aegis, AndOTP, GoogleAuthnticator etc? it don't have to be in Rust

All 2FA apps will work, it's a standard.

**Comment by StaticallyTypedRice** [comment]
> Relates to #1368
> 
> PS. Doesn't using google authenticator go against Federation ideas?

The authenticator protocol is an open standard I'm pretty sure. There are fully open source authenticator apps

**Comment by TheEvilSkeleton** [comment]
I'm really surprised this isn't a priority to be honest.

**Comment by dessalines** [comment]
We have about 100 other priorities for lemmy. But this is an open source project, anyone is free to take a crack at it.

**Comment by Kellegram** [comment]
Basic security features should kind of be much more of a priority, 2FA is just expected for a while now and usually comes out with a product.

**Comment by dessalines** [comment]
Lemmy is not a "product", its an open source project, and I don't appreciate priorities being dictated when I have a million things to do. I'm assigning this ticket to you @Kellegram, let me know if you need any assistance.

**Comment by Kellegram** [comment]
> Lemmy is not a "product", its an open source project, and I don't appreciate priorities being dictated when I have a million things to do. I'm assigning this ticket to you @Kellegram, let me know if you need any assistance.

The word "product", just like most words, has multiple definitions. A quick Google search returns a second definition for product which goes as follows: "a thing or person that is the result of an action or process". Is your project not a result of an action or process?

Very mature though, I won't be working on this as I am doing other things and this among other things made me lose interest in Lemmy temporarily.

**Comment by Kellegram** [comment]
If you want to act friendlier to the idea of giving security of this account based system a security boost I would be more than happy to help with at least researching implementation methods, maybe help figure out potential issues, but this thread from the start felt like this wasn't being taken as seriously as it should. I feel like this isn't some school project, Lemmy could be really good but some standards should be met and 2fa is a simple step for big gains. The video linked a while ago demonstrates why pretty well iirc. If you have no time because this wasn't planned in advance then that's fine, but this isn't some random feature request, that's of little importance or impact, so be less dismissive and people are more likely to want to help beyond leaving comments. Now take that assignment off of me please as we both know it was done in spite and nothing more.

**Comment by dessalines** [comment]
Your use of the word product is illuminating: it shows that you think we're selling you something. We're not, this is an open source project, made by volunteers and community contributors. You don't get to tell them their priorities, **you do the work** if you want a feature that no one else has time to do.

> Very mature though, I won't be working on this as I am doing other things

You're asking others to do free labor for you, while refusing to do anything to make this project better. 

I'll remove you if you continue belligerently dictating our priorities whilst providing nothing in return.

**Comment by TheEvilSkeleton** [comment]
Hmm... I think you are taking this personally. They didn't really dictate anything to anyone. They were just suggesting what should be prioritized. I believe you're confusing suggestions with demands.

I believe you are cherry picking as well. Kellegram literally said:

> If you want to act friendlier to the idea of giving security of this account based system a security boost I would be more than happy to help with at least researching implementation methods, maybe help figure out potential issues

They're willing to spend time to help with research and provide necessary information. You don't need to pick the very few words and take them out of context. You have your chance to ask for assistance, it's best to take advantage of it.

**Comment by dessalines** [comment]
@TheEvilSkeleton are you able to work on this?

**Comment by TheEvilSkeleton** [comment]
No, I don't code.

**Comment by Nutomic** [comment]
I had to hide some comments for being off topic. If what you write doesnt bring us closer to implement the feature, then it probably doesnt belong on the issue tracker. As mentioned by @dessalines, we have a lot of tasks that are more important than 2FA. If that is a problem for you, then dont use Lemmy for now.

**Comment by LiftedStarfish** [comment]
Can somebody reopen this issue? Lemmy *still* does not have 2FA, and the user who opened it has been deleted.
