### ISSUE TITLE
Community / user outbox fetching oldest items

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1436]
[from here](https://lemmy.ml/post/53911/comment/35792)

Might be fetching the oldest items due to not having a sort in here:

https://github.com/LemmyNet/lemmy/blob/f45f2ec202b462057c1d44b8a1aacfb3df3df9d9/crates/db_queries/src/source/activity.rs#L101

**Comment by Nutomic** [comment]
Fixed here: https://yerbamate.ml/LemmyNet/lemmy/pulls/169
