### ISSUE TITLE
Appointing a mod is reflected twice in the modlog / Add TransferMod modlog entry

### ISSUE THREAD

**Issue by shilangyu** [LemmyNet/lemmy#1437]
### Issue Summary

When visiting https://lemmy.ml/modlog one can see that most _Appointed <user> as a mod to the community <community>_ entries are duplicated:

![image](https://user-images.githubusercontent.com/29288116/108333616-6fa32b00-71d1-11eb-81db-b8e7c2c479f1.png)

Weirdly enough this isn't always the case:

![image](https://user-images.githubusercontent.com/29288116/108333674-8053a100-71d1-11eb-8b5a-64b24bd957c0.png)

(the appointment of a new Elm mod appears only once)

This might perhaps be just that the action was indeed performed twice each time, I'm not sure how to debug that.

### Technical details

I know this isn't a lemmy-ui issue because I am experiencing the same thing when consuming the API directly in lemmur

**Comment by dessalines** [comment]
So what's going on is that these aren't just appoints. I'm appointing them as a mod, then I'm transferring the community ownership to them. For both these I'm just using the `ModAddCommunity` type.

**Comment by shilangyu** [comment]
Ah gotcha, not a bug then

> Not sure if an additional `ModTransferCommunity` type is necessary.

Probably makes sense for completeness but doesn't seem too necessary
