### ISSUE TITLE
Federate Matrix ID

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1438]
Not sure which ActivityPub field would make sense for that.

**Comment by dessalines** [comment]
Most likely attachment: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-attachment

**Comment by Nutomic** [comment]
> The intent is to provide a model that is at least semantically similar to attachments in email. 

That doesnt seem right. Mastodon uses `as:alsoKnownAs` for migration to a new account, we could reuse that. 

https://docs.joinmastodon.org/spec/activitypub/

**Comment by dessalines** [comment]
That seems to be used for migration followers from one masto acct to another : "Move = migrate followers from one account to another. Requires alsoKnownAs to be set in both directions."

A matrix ID has nothing to do with lemmy, and we could potentially add a lot more public contact type fields (maybe xmpp too).

**Comment by Nutomic** [comment]
Correct, but we can use it for something different. Or come up with a completely different name, but `alsoKnownAs` sounds very appropriate to me.
