### ISSUE TITLE
Searchfilter "All" does not show Community, when searchin with https://... link

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#1439]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

If i search for a community on a foreign host, for example for https://lemmy.ml/c/opensource in my searchfield (own instance), i get no result with Filter "All", only with filter "communitys"

### Steps to Reproduce

1. fill in https://lemmy.ml/c/opensource in search-lense, klick enter and get
![grafik](https://user-images.githubusercontent.com/5894829/108380362-11913a80-7207-11eb-8428-ecb4fcccfe45.png)
2. Change filter to "communities" i get
![grafik](https://user-images.githubusercontent.com/5894829/108380455-2372dd80-7207-11eb-8fa2-85c8bb61d887.png)
3. change all filters permutative, i get the link also with filter "All"

2. I tried to install lemmy via official guide, havin a reverseproxy on another machine and changed the proxy-ip to lemmy-hosts ip

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
* What OS are you trying to install lemmy on? : Debian Buster
* Any browser console errors?: No

**Comment by xundeenergie** [comment]
it looks like first try searching is not shown in "All"-Filter. If it's found once, it's there and get shown. I tried this also with other community-links

**Comment by Nutomic** [comment]
This is actually a frontend issue: https://github.com/LemmyNet/lemmy-ui/issues/188
