### ISSUE TITLE
For remote communities, read follower count from `/c/xxx/followers`

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1440]
It returns something like this, where `totalItems` is the total number of followers.
```json
{
  "totalItems": 2189,
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "category": "sc:category",
      "stickied": "as:stickied",
      "comments_enabled": {
        "kind": "sc:Boolean",
        "id": "pt:commentsEnabled"
      },
      "sensitive": "as:sensitive",
      "sc": "http://schema.org#"
    }
  ],
  "id": "https://lemmy.ml/c/opensource/followers",
  "type": "Collection"
}
```

At the moment, follower count for remote communities only represents the amount of followers from the local instance.

**Comment by Hikiru** [comment]
So is this being worked on? How high priority is it?

**Comment by Nutomic** [comment]
@Hikiru see https://github.com/LemmyNet/lemmy/commit/beb63ca7ddc5fcd7630a00e945dc03872acc9a9f
