### ISSUE TITLE
Unstable rustfmt options force committing on nightly

### ISSUE THREAD

**Issue by ajyoon** [LemmyNet/lemmy#1448]
### Issue Summary

This is an internal dev-only issue. This repo's rustfmt toml file uses `imports_layout` and `imports_granularity`, both of which are unstable features that can't be used on the stable toolchain. Since the repo also uses cargo husky, which attaches a pre-commit `cargo fmt` hook, this means devs must be on the nightly toolchain to run commits, or else `cargo fmt` will add cause massive reformatting diffs.

Normally I wouldn't notice this since I typically use nightly, but #1270 means the build doesn't work on nightly so I was poking around on stable 1.47 and ran into this. There are a couple ways to address this:

- Suggest devs just use nightly
- Update the cargo husky setup to use custom hooks which run `cargo +nightly fmt`, then document somewhere that the nightly toolchain must be installed (even if not set as the default). I was able to get this working locally without much pain.
- Remove the unstable features from the rustfmt toml until the features stabilize for rustfmt 2.x is released, which will allow use of unstable features on the stable toolchain.

### Steps to Reproduce

1. switch to a recent stable rust toolchain, e.g. `rustup override set 1.47.0`
2. create a test commit; cargo fmt emits a bunch of warnings like:
```
Warning: can't set `imports_layout = HorizontalVertical`, unstable features are only available in nightly channel.
Warning: can't set `unstable_features = true`, unstable features are only available in nightly channel.
Warning: Unknown configuration option `imports_granularity`
Warning: can't set `imports_layout = HorizontalVertical`, unstable features are only available in nightly channel.
```
3. run a `git status` and observe how `cargo fmt` has introduced dozens of changes from the config difference.

**Comment by ajyoon** [comment]
Sounds good, I'll take a stab at a PR on the contributing docs to recommend nightly

**Comment by Mart-Bogdan** [comment]
Only **rust fmt** could be used from nightly, not the whole toolchain.

I've used `cargo +nightly fmt`
