### ISSUE TITLE
Add copy&paste functionality

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#1453]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

Making a Screenshot to clipboard, copy an image from a website or a document or from a picture-viewer to clipboard and paste it to lemmys posting-box does not work. I have to save it to disk and search for it to add it via dialog... that is frustrating.

### Describe the solution you'd like

So please add copy&paste functionality to lemmys posting-function.
This works on mastodon and pleroma... and so many other user interfaces too...

**Comment by dessalines** [comment]
Wrong repo.
