### ISSUE TITLE
Add "new communities" column above "trending communities"

### ISSUE THREAD

**Issue by MrLuxuri** [LemmyNet/lemmy#1457]
> Trending communities

Should show top communities that are growing with major subscribers. 

> New communities

Should show communities that was created most recently like it is showing now in "trending communities".

![Screen Shot 2021-02-25 at 6 14 42 PM](https://user-images.githubusercontent.com/71905307/109232546-7b28c000-7796-11eb-8bca-3c02c81bc022.png)

**Comment by Nutomic** [comment]
Anyway trending communities seems to be kind of broken, it might be worth reworking that completely.

**Comment by MrLuxuri** [comment]
> Anyway trending communities seem to be kind of broken, it might be worth reworking that completely.

Yeah, trending should show top communities but instead, it shows new communities created.

**Comment by MrLuxuri** [comment]
> > Anyway trending communities seem to be kind of broken, it might be worth reworking that completely.
> 
> Yeah, trending should show top communities but instead, it shows new communities created.

**Comment by MrLuxuri** [comment]
> > > Anyway trending communities seem to be kind of broken, it might be worth reworking that completely.
> > 
> > 
> > Yeah, trending should show top communities but instead, it shows new communities created.

Also forgot to mention, it would be great if lemmy get's a whole new UI redesign, it just looks a bit outdated compared to reddit, there should also be more customizable options for mods

**Comment by dessalines** [comment]
`ListCommunities` is properly doing a hot sort for the trending communities:

```rust
      _ => {
        query = query
          .order_by(
            hot_rank(
              community_aggregates::subscribers,
              community_aggregates::published,
            )
            .desc(),
          )
          .then_order_by(community_aggregates::published.desc())
      }
```

We just haven't had a situation where lots of people are subscribing to new communities quickly, for it to be anything other than effectively being the same as new communities.

The communities page currently sorts by default by `Top` communities, which we're going to change to `Users / month` descending. I *spose* we could have a section for top communities on the main page, but I'm not sure if that's a good idea.

**Comment by MrLuxuri** [comment]
> `ListCommunities` is properly doing a hot sort for the trending communities:
> 
> ```rust
>       _ => {
>         query = query
>           .order_by(
>             hot_rank(
>               community_aggregates::subscribers,
>               community_aggregates::published,
>             )
>             .desc(),
>           )
>           .then_order_by(community_aggregates::published.desc())
>       }
> ```
> 
> We just haven't had a situation where lots of people are subscribing to new communities quickly, for it to be anything other than effectively being the same as new communities.
> 
> The communities page currently sorts by default by `Top` communities, which we're going to change to `Users / month` descending. I _spose_ we could have a section for top communities on the main page, but I'm not sure if that's a good idea.

I think we should have a "new communities" section and the "trending communities" section only show top communities with most subscribers or with most growth, if you know what I mean:)

**Comment by dessalines** [comment]
I don't see a need for this, and it would just add clutter, as they would at this point with so few new communities being added, be the same list twice.
