### ISSUE TITLE
Feature proposal: Turn categories into filterable hashtags instead, to make them useful

### ISSUE THREAD

**Issue by marek-lach** [LemmyNet/lemmy#1459]
Right now, the concept of 'Category' when creating a community has very little practical use.

However, if Categories were instead actual #Hashtags, then they could be useful as an option to quickly filter between themes.

As an example:

Having a community like Kant, or Schopenhauer, could have a category of #Philosophy, clicking on which would filter out all Philosophy communities.

Or a community with the category #Geography could filter out (sort) communities like /c/Canada, /c/Spain if this category is what is assigned to these communities.

**Comment by MrLuxuri** [comment]
This is an awesome feature request, we really do need this:)

**Comment by Nutomic** [comment]
Categories have been removed, and there is https://github.com/LemmyNet/lemmy/issues/317 for tags.
