### ISSUE TITLE
Write an article about Lemmy on wikipedia

### ISSUE THREAD

**Issue by MrLuxuri** [LemmyNet/lemmy#1460]
One of the biggest things that will make it harder for new users coming for reddit is to find Lemmy's website itself. 
I recently moved to Lemmy from reddit and took me 10 mins just to find lemmy, whenever I searched up Lemmy, this is what popped up instead.
![Screen Shot 2021-02-26 at 10 16 33 AM](https://user-images.githubusercontent.com/71905307/109318440-cc2ec780-781b-11eb-9ad7-286baccb0d78.png)
And that is because we don't have a wiki page for Lemmy like reddit. 
![Screen Shot 2021-02-26 at 10 18 16 AM](https://user-images.githubusercontent.com/71905307/109318712-1a43cb00-781c-11eb-934f-30f9cadcce33.png)

Creating a wiki page will allow users to find lemmy faster and easier, we can also link lemmy's join website.

**Comment by dessalines** [comment]
Sounds like a good first issue.

**Comment by MrLuxuri** [comment]
> Sounds like a good first issue.

Who will do this though? It's very important...

**Comment by HorseJump** [comment]
I just submitted a draft for review!

**Comment by HorseJump** [comment]
It was very quickly rejected with the following reason:
This submission's references do not show that the subject qualifies for a Wikipedia article—that is, they do not show significant coverage (not just passing mentions) about the subject in published, reliable, secondary sources that are independent of the subject. Before any resubmission, additional references meeting these criteria should be added (see technical help and learn about mistakes to avoid when addressing this issue). If no additional references exist, the subject is not suitable for Wikipedia.

**Comment by dessalines** [comment]
Relevant post: https://lemmy.ml/post/73812

If lemmy hasn't had enough outside coverage, then we'll have to wait for that to happen. Their software inclusions do seem pretty arbitrary: etherpad has an entry, but hedgedoc doesn't.

**Comment by Craftplacer** [comment]
An alternative solution (in other words, not Wikipedia) to the problem that OP raised, would be to have a website that satisfies Google's SEO criteria first. (in the solution proposed we're only abusing Wikipedia's higher SEO rating, so we're more visible, but why?)

One of the criteria would be to add metadata tags on the website, which the current one barely does:

![Screenshot showing the <head> of join-lemmy.org](https://user-images.githubusercontent.com/22963120/128780354-d29797f3-7371-4626-a699-a1ac1a253afb.png)

There are other criteria of the performance of the web page (does get served over HTTPS?, is it served fast?, does the page re-layout itself while the browser pulls in data?).

Also possible is that you make the page stand out:[Overview of Search appearance topics](https://developers.google.com/search/docs/advanced/appearance/overview)

**Comment by dessalines** [comment]
We do support opengraph and twitter cards, take a look at `html-tags.tsx` in lemmy-ui. But its mainly for posts and user profiles.

**Comment by felipeforte** [comment]
Unfortunately I think it's currently too hard to compete with the singer of Motörhead to have any gain with search engines. We need to wait for him to become irrelevant :sweat_smile:

**Comment by dessalines** [comment]
Lemmy does have a [wiki entry](https://en.m.wikipedia.org/wiki/Lemmy_(software)) now, so this can be closed.
