### ISSUE TITLE
JWT tokens rejection/revocation upon user credentials reset

### ISSUE THREAD

**Issue by Mart-Bogdan** [LemmyNet/lemmy#1462]
Currently, 
1. JWT tokens live forever 
2. JWT tokens aren't revoked if user resets or changes it's password.

If addressing first one would require big change of workflow, the second one could be addressed in short term.

The first point could be covered with implementation of AUTH 2 and proper refresh tokens as an option. #1368

I would update this issue with more details in few days. Placeholder for now. 

As discussed in https://app.element.io/#/room/#lemmydev:matrix.org
<details>
  <summary>Excerpt from chat discussion</summary>
  
> winnie_ua
> Hello.
> 
> I was digging into Lemmy code on last week.
> 
> I've noticed one thing. That JWT tokens are basically issued forever. And only way to block a token is to block user on site entirely.
> I can see two cases for making old tokens invalid:
> 
> when user performs password reset, and
> when user changes password in UI (not sure about this)
> Perhaps I've just didn't noticed something. but seems like this isn't addressed, as it looks from code.
> 
> P.S. I'm sorry, I am new to Rust. but I have solid back-end background in Java and C#
> nutomic
> if the token isnt reset in those cases, then we should definitely do that (i guess dessalines knows how its done now)
> it might also be good to invalidate the tokens after 30 days or something like that
> winnie_ua
> Yes, I've thought about this. We jsut currently don't have iat/exp claims on token
> currently we are changing password in this two places
> 
> https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/user.rs#L411
> https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/user.rs#L1004
> 
> and inside it is changing updated column on User_ table
> 

> and verify it against timestamp of password change
> nutomic
> ah, please dont use too many abbreviations like that, makes everything harder to understand ;)
> i think jwt token validity time should be counted from the time since last login
> and all tokens revoked on password change (maybe with a checkbox "logout other lemmy clients")
> hope that makes sense
> winnie_ua
> I'm afraid rovokation on password change would break existing clients :c
> 
> IDK what clietns actually exist, but I know that there are lemmy-ui witch could be easily changed and there are third party mobile cleint at least
> we currently have field updated insied Users_ table whisc is changed on password change and on apub::fetch::user::get_or_fetch_and_upsert_user
> 
> I belive it's related to fedration

> I'd actually suggest adding more claims to JWT standard ones

> https://tools.ietf.org/html/rfc7519#page-9

> Leave current "id" for backward comptability (web client is decoding claims)

> but add standard ones.

> "iat" issued at
> "sub" it's jsut copy of "id"
> "exp" Expiration Time Optional

> how does remove users work?

```rust
  match user {
    // If its older than a day, re-fetch it
    Ok(u) if !u.local && should_refetch_actor(u.last_refre
```

> nutomic
> we can definitely make breaking changes, dont worry too much about that
> but i think its better you open an issue to explain this, chat is gone after a few days
> your suggestions definitely sound good to me

> everything in the `crates/apub/` folder is for activitypub, and has nothing to do with jwt tokens
> you should only have to look and `crates/api` and maybe `crates/db_*`

> winnie: hm, then updated field can't be used

> nutomic  ah yes, for jwt updates you should use a different field

</details>

**Comment by dessalines** [comment]
The only way I can think of doing this, is to add another timestamp column to the user table, maybe called validator_time, and have that column update on either password changes, or when a user clicks a big log out of all devices button. 

Then the JWT could include that timestamp in the token and check it when the back end inevitably has to fetch the user from the DB. 

https://security.stackexchange.com/questions/82640/best-practices-to-invalidate-jwt-while-changing-passwords-and-logout-in-node-js

I really dislike auto logouts or expirations so I don't wanna go that route.

**Comment by Mart-Bogdan** [comment]
Hmm, regarding coulmn name, some suggestions for name
* validator_time
* password_invalidated_at 
* login_invalidated_ts

Ok, then I suggest the following changes that I can make as PR.

1. Add field `password_invalidated_at -> Optional<Timestamp>` (or whatever name we chose)
2. Add "iat" claim with unix timestamp if when token was issued
3. Add "sub" claim with copy of "id" just to comply with JWT spec
4. Add "exp" claim and set it to time delay set in config (can be disabled in config). @Nutomic suggested to issue tokens only for 30 days.
4. On password reset always set password_invalidated_at field to the current timestamp
5. On change password:
    a. Add to model optional field reset_login_tokens 
    b. if it's set -- password_invalidated_at field, and in response return new token.

> I really dislike auto logouts or expirations so I don't wanna go that route.

Or we could not do expiration then, but it could be optional.


Actually, these changes won't break current clients.  (except if we would want to auto-reset token on password change if user has not explicitly opted out)

Only question then is should lemmy reject old formatted tokens and force users to re-login.

**Comment by dessalines** [comment]
> Add "exp" claim and set it to time delay set in config (can be disabled in config). @Nutomic suggested to issue tokens only for 30 days.

Don't bother with that one, I don't want time-based tokens. There's no reason I should have to log in every 30 days.

> Add "sub" claim with copy of "id" just to comply with JWT spec

We can just remove id in that case.

> On password reset always set password_invalidated_at field to the current timestamp

Yep. We should probably add a `LogoutOfAllDevices` endpoint, but we could always do that later.

> Actually, these changes won't break current clients.

This will definitely break current clients, because the back end will need to check the `validator_time` field. If its not there, (and it doesn't match that column) it has to assume its a bad login.

**Comment by Mart-Bogdan** [comment]
> We can just remove id in that case.
I've noticed that lemmy-ui is decoding Claims, but I haven't checked if it uses them afterward.

**Comment by dessalines** [comment]
> Well it would break current sessions, but not current frontends (client apps which I was referring as clients)

Ah I gotcha. 

> I've noticed that lemmy-ui is decoding Claims, but I haven't checked if it uses them afterward.

It does use the id, but that's super easy to change, and we always do releases with UI versions packaged along with it so its no problem.

**Comment by Mart-Bogdan** [comment]
To summarize. 

1. We don't touch  user::save, when we can update password
2. We lock tokens when we reset password
3. We add new REST api and websocket to lock tokens (LogoutOfAllDevices) that would return new usbale token
4. we provide two claims "sub" and "id" with the same value
5. we add "iat" claim with a time of token creation
6. we add a new column to users table holding NULL, or time since which tokens are valid. 

But how should it be named? Naming seems important in long term to me. 

I hope maintainers could choose.

**Comment by dessalines** [comment]
That looks mostly correct. 

> We lock tokens when we reset password

As in, update the `validator_time` with a new timestamp, yes.

> We add new REST api and websocket to lock tokens (LogoutOfAllDevices) that would return new usbale token

Hrm... yes I suppose it could return a new token, in addition to updating that validator_time. It should probably be called `LogoutOtherDevices` then.

> we add a new column to users table holding NULL, or time since which tokens are valid.

Don't do null, check the other time columns, but it should be `not null default now()`.

**Comment by Mart-Bogdan** [comment]
To be honest, the name `validator_time` doesn't look clear to me, from point of view of a person who would look at a table.
But I do not object against it, it's up to you to choose. 

I'll try implementing it after the weekend.

**Comment by Nutomic** [comment]
How about simply `last_password_reset`?

And instead of a new API call `LogoutOtherDevices`, I think it would be enough to make this a boolean parameter on `SaveUserSettings` (shown as a checkbox next to the change password field).

**Comment by dessalines** [comment]
Either name works for me.

But this one isn't a saved user setting, its more of a single action button

Also me adding the `changepassword` stuff into `SaveUserSettings` isn't really a good practice either, I'll open up an issue to separate that out.

We can also hold off on the `LogoutOfAllDevices` thing for now, change password is the only reason I can think that you'd want to do this anyway.

**Comment by Mart-Bogdan** [comment]
I've made code changes to validate the token. But need to figure out with tests. 
And I'll hold LogoutOfAllDevices for now. Would just count password resets for first PR.

**Comment by dessalines** [comment]
This is fixed.
