### ISSUE TITLE
Add ability for admins to add words to slur filter

### ISSUE THREAD

**Issue by bpepple** [LemmyNet/lemmy#1464]
### Feature Proposed

It would be nice to give the ability to add words not already included in the slur filter. This could be done either on the admin level or user level settings

### Describe the solution you'd like

Add an option in the settings to add a list of word to the slur filter. The default slur words in the code should be shown in the help text to prevent duplication.

**Comment by dessalines** [comment]
This should be a new `additional_slurs: ["slur1", "slur2"]` setting in the `hjson`.

**Comment by Nutomic** [comment]
It should probably be a regex. More complicated, but also more flexible and allows working around false positives.

**Comment by dessalines** [comment]
I agree, I just mean it would be appended to our current slur regex by the `|` delimiter: `...|slur_1_regex|slur_2_regex|...`

**Comment by ba1ash** [comment]
Hello there!
I am working on this one.
