### ISSUE TITLE
Create integration suite for federation.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#147]

**Comment by Nutomic** [comment]
This could be done in the following way: 

- Create a Python script (or basically any other language) that interacts with a local Lemmy instance running in Docker
- The script does some actions via the API (eg create a user + community, make a post, etc)
- Reads the apub responses with HTTP calls and compares them with correct responses (replacing variables)
- That only tests part of the apub implementation, something similar could be done by sending apub activities to Lemmy and checking with the API that it was applied correctly.

Contributions are welcome, we wont be able to implement this any time soon.

**Comment by Nutomic** [comment]
Partially solved by #658. We need to add more tests though as we add more federation features.

**Comment by dessalines** [comment]
This is done, we just have to add them as we add more API calls.
