### ISSUE TITLE
failed run emmy_server on Mac

### ISSUE THREAD

**Issue by icoco** [LemmyNet/lemmy#1470]
### Issue Summary

compile issue , while exec cmd : RUST_BACKTRACE=full  cargo run

failed to run,  report error : 
` Finished dev [unoptimized + debuginfo] target(s) in 12m 59s
`target/debug/lemmy_server`
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<std::string::String, value::Value>` uninitialized, which is invalid', /`

### Steps to Reproduce
1)  exec cmd : RUST_BACKTRACE=full  cargo run
2)  look build success , but failed run : 
    
   `Finished dev [unoptimized + debuginfo] target(s) in 12m 59s
     Running `target/debug/lemmy_server``

### Technical details

Mac OS

Running `target/debug/lemmy_server`
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<std::string::String, value::Value>` uninitialized, which is invalid', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0:        0x106ffd114 - std::backtrace_rs::backtrace::libunwind::trace::h3440e89bdeed3ddf
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x106ffd114 - std::backtrace_rs::backtrace::trace_unsynchronized::hfa68bcc7baf06ad7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x106ffd114 - std::sys_common::backtrace::_print_fmt::h483e161a2ffbfba4
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x106ffd114 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h34f76b2ca42fab41
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10701dacd - core::fmt::write::h8f13d857463c51c1
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:        0x106ff5016 - std::io::Write::write_fmt::h0a6214ccb1a8468b
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:        0x106fff049 - std::sys_common::backtrace::_print::h7f3525175df798e8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x106fff049 - std::sys_common::backtrace::print::hf68eec1a3c535c32
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x106fff049 - std::panicking::default_hook::{{closure}}::hb14d90e928578cc7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:        0x106ffebd0 - std::panicking::default_hook::h460969f1dc8f738d
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:        0x106fff83b - std::panicking::rust_panic_with_hook::h28bf9d6c3916221e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:        0x106fff309 - std::panicking::begin_panic_handler::{{closure}}::h99569328be4adae9
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:495:13
  12:        0x106ffd5b8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9a7e5cc6475b496b
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x106fff29a - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:        0x10701b62f - core::panicking::panic_fmt::h65997884a2662b8c
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:        0x10701b587 - core::panicking::panic::h2ca2e9d2b0a1f2bf
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
  16:        0x106123d9a - linked_hash_map::LinkedHashMap<K,V,S>::insert::heafdda7c80273f6c
  17:        0x106114265 - <linked_hash_map::serde::LinkedHashMapVisitor<K,V> as serde::de::Visitor>::visit_map::h5548103e71ff1e79
  18:        0x10611eb66 - <<serde_hjson::value::Value as serde::de::Deserialize>::deserialize::ValueVisitor as serde::de::Visitor>::visit_map::h0c8b3effa7386b42
  19:        0x1060f72db - serde_hjson::de::Deserializer<Iter>::parse_value::he9ea62d24db6c000
  20:        0x106101144 - <serde_hjson::de::Deserializer<Iter> as serde::de::Deserializer>::deserialize::h03ca3cd9448a67ac
  21:        0x10611e304 - <serde_hjson::value::Value as serde::de::Deserialize>::deserialize::hcf5b87ff54b2b075
  22:        0x106103ae8 - <serde_hjson::de::MapVisitor<Iter> as serde::de::MapVisitor>::visit_value::h25dc8bf2c3cfa7f5
  23:        0x1060f22a3 - serde::de::MapVisitor::visit::hd2b7a70cf53f58da
  24:        0x106113fe8 - <linked_hash_map::serde::LinkedHashMapVisitor<K,V> as serde::de::Visitor>::visit_map::h5548103e71ff1e79
  25:        0x10611eb66 - <<serde_hjson::value::Value as serde::de::Deserialize>::deserialize::ValueVisitor as serde::de::Visitor>::visit_map::h0c8b3effa7386b42
  26:        0x1060f72db - serde_hjson::de::Deserializer<Iter>::parse_value::he9ea62d24db6c000
  27:        0x106101144 - <serde_hjson::de::Deserializer<Iter> as serde::de::Deserializer>::deserialize::h03ca3cd9448a67ac
  28:        0x10611e304 - <serde_hjson::value::Value as serde::de::Deserialize>::deserialize::hcf5b87ff54b2b075
  29:        0x1061048a2 - serde_hjson::de::from_iter::h92f64a9a98644bff
  30:        0x106104fac - serde_hjson::de::from_slice::haa20573e604d9381
  31:        0x10610501c - serde_hjson::de::from_str::h51dc25a3ae13d86c
  32:        0x1060e5b4c - config::file::format::hjson::parse::h38a3e381478b2d61
  33:        0x1060d833d - config::file::format::FileFormat::parse::hda37ebcbd018d740
  34:        0x105f746c3 - <config::file::File<T> as config::source::Source>::collect::hf9a5a147afe7a788
  35:        0x105f73f06 - config::source::Source::collect_to::h3ea744116e0ca51c
  36:        0x1060ef3b4 - <alloc::vec::Vec<alloc::boxed::Box<dyn config::source::Source+core::marker::Send+core::marker::Sync>> as config::source::Source>::collect::h9a2246c38ae60f9a
  37:        0x1060eee86 - config::source::Source::collect_to::h32f4571d9841d965
  38:        0x1060d1397 - config::config::Config::refresh::h8414b06962694449
  39:        0x105f6ec41 - config::config::Config::merge::hed94492044516cec
  40:        0x105f7ae93 - lemmy_utils::settings::Settings::init::h6304e41b0a50af2f
  41:        0x105f700fb - core::ops::function::FnOnce::call_once::h11c274cdc239078f
  42:        0x105f950d1 - lazy_static::lazy::Lazy<T>::get::{{closure}}::h1bffbf18992c6fa3
  43:        0x105f7d508 - std::sync::once::Once::call_once::{{closure}}::h1bae4804f964c2b0
  44:        0x106ffc834 - std::sync::once::Once::call_inner::h755b6d60054eea69
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sync/once.rs:420:21
  45:        0x105f7d0b5 - std::sync::once::Once::call_once::h705a5f27653e6f92
  46:        0x105f7cf35 - <lemmy_utils::settings::SETTINGS as core::ops::deref::Deref>::deref::h9c4f47b42afac9c3
  47:        0x105f7b282 - lemmy_utils::settings::Settings::get::h3af2c60148c791d2
  48:        0x1049ab09d - lemmy_server::main::{{closure}}::h065ee6d9e0eb5c1b
  49:        0x10487aa94 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3d7221c611e0f157
  50:        0x10486ae90 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}::h4b7a0ecaad43bee6
  51:        0x1049bc773 - tokio::coop::with_budget::{{closure}}::h64d9959ce3a8d6d1
  52:        0x1049adfa1 - std::thread::local::LocalKey<T>::try_with::hc5a85e49eb5433ac
  53:        0x1049ac6a8 - std::thread::local::LocalKey<T>::with::h375ffc870ba6c6c0
  54:        0x10486ad55 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::h4a50e448077a1210
  55:        0x10488a9e7 - tokio::macros::scoped_tls::ScopedKey<T>::set::h9aa76b1f04d21863
  56:        0x10486a80a - tokio::task::local::LocalSet::with::he9c6b9ca6a755022
  57:        0x10486ac3d - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h9837573326c93436
  58:        0x10486aa79 - tokio::task::local::LocalSet::run_until::{{closure}}::hd3760e45ebf62ac0
  59:        0x10487c644 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h99ec78780c6b28c1
  60:        0x1049640cd - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::h9b0db41c1ac1aba4
  61:        0x1049bc933 - tokio::coop::with_budget::{{closure}}::he37c48167e654011
  62:        0x1049ad0e1 - std::thread::local::LocalKey<T>::try_with::h2c6a82fdf5fadaa9
  63:        0x1049aca98 - std::thread::local::LocalKey<T>::with::hb842ff752fccd87e
  64:        0x104963a8e - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::h690962fcc0b84951
  65:        0x104964530 - tokio::runtime::basic_scheduler::enter::{{closure}}::h4cefe226498cd0d1
  66:        0x10488ab1d - tokio::macros::scoped_tls::ScopedKey<T>::set::hc0985e92c6ae38f6
  67:        0x10496441c - tokio::runtime::basic_scheduler::enter::hc40944c2f006e9c6
  68:        0x1049638e3 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h6d6a9988044e62d8
  69:        0x104901920 - tokio::runtime::Runtime::block_on::{{closure}}::he3686c12c84b4dd7
  70:        0x10495f48d - tokio::runtime::context::enter::h8e172e02349b8a48
  71:        0x10499815c - tokio::runtime::handle::Handle::enter::h0cc59adf0394c926
  72:        0x104901889 - tokio::runtime::Runtime::block_on::h7a49355ea226948c
  73:        0x10486a887 - tokio::task::local::LocalSet::block_on::h6ef12c0d0a7f6772
  74:        0x1049f0e3b - actix_rt::runtime::Runtime::block_on::hcf371804bb537af7
  75:        0x1049e7869 - actix_rt::builder::SystemRunner::block_on::he7ea04984d06dc53
  76:        0x1049bc095 - lemmy_server::main::hb67956017a2af29e
  77:        0x10499aafa - core::ops::function::FnOnce::call_once::hb7a622a2131fe8c1
  78:        0x1048c5a5d - std::sys_common::backtrace::__rust_begin_short_backtrace::h7189627650f0a7b5
  79:        0x104901290 - std::rt::lang_start::{{closure}}::hc31de26eb9dd59e1
  80:        0x106fffc94 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hde238ec10b1f717d
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:259:13
  81:        0x106fffc94 - std::panicking::try::do_call::h41236cf2e2b1c5e6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  82:        0x106fffc94 - std::panicking::try::h0b8723b0a7df810a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  83:        0x106fffc94 - std::panic::catch_unwind::heaaf12506fa6bab8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  84:        0x106fffc94 - std::rt::lang_start_internal::h1faf79574185df6d
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:51:25
  85:        0x104901265 - std::rt::lang_start::hbd9df8de73427e8d
  86:        0x1049bc102 - _main
Panic in Arbiter thread.

**Comment by Nutomic** [comment]
You need to use Rust 1.47 for now. There is already an open issue, but I'm on mobile so I wont search that.

**Comment by icoco** [comment]
ok... thanks

**Comment by Nutomic** [comment]
We fixed this yesterday, you can use any Rust version to build/run the latest main branch.
