### ISSUE TITLE
Slur packs depending on language?

### ISSUE THREAD

**Issue by scarlet-tobar** [LemmyNet/lemmy#1475]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

Slur filter only works on American English with some success. There are word that are a Slur in English but harmless in other languages.

### Describe the solution you'd like

Create "slur language packs" that are installed/used depending on the language that the individual instance uses.

### Describe alternatives you've considered

Editable Slur filter, but that is being discussed as far as I know.

### Additional context

I'm not sure how could this be implemented tho.

Thank you.

**Comment by Nutomic** [comment]
This depends on #440.

**Comment by ptman** [comment]
https://www.dolthub.com/repositories/dolthub/bad-words

**Comment by Nutomic** [comment]
The slur filter is configurable for instance admins now, so there is no reason to change anything in Lemmy.
