### ISSUE TITLE
Help with starting a Lemmy Server

### ISSUE THREAD

**Issue by PatMulligan** [LemmyNet/lemmy#1482]
I should first preface this with saying that I am not very experienced in running servers, so there may be something very fundamental that I am misunderstanding here...

I would like to run a Lemmy server and I am trying to follow the directions to [install with Ansible](https://join.lemmy.ml/docs/en/administration/install_ansible.html) and I'm running into an error that I don't know how to resolve.

So firstly, I am installing Ansible and the docker_compose plugin on **my local computer** (i.e., not the Linode server where I would like the deploy the Lemmy Server). I have installed them with: 

```
// ansible install on my local desktop
$ sudo apt update
$ sudo apt install software-properties-common
$ sudo apt-add-repository --yes --update ppa:ansible/ansible
$ sudo apt install ansible

// docker_compose install on my local desktop
$ ansible-galaxy collection install community.docker

```

After the above, I follow the directions for the Ansible installation, cloning the repo to my computer and copying the inventory.example file to `inventory`. I replace `myuser@example.com` with my credentials for the Linode server I set up which is `root@192.46.xxx.xx`

I don't have a `domain` yet, so I'm not entirely sure what to do there but I just filled it out with `domain=192.46.xx.xxx`. In the end, my `inventory` file looks like this:
```
[lemmy]
# to get started, copy this file to `inventory` and adjust the values below.
# - `myuser@example.com`: replace with the destination you use to connect to your server via ssh
# - `domain=example.com`: replace `example.com` with your lemmy domain
# - `letsencrypt_contact_email=your@email.com` replace `your@email.com` with your email address,
#                                              to get notifications if your ssl cert expires
# - `lemmy_base_dir=/srv/lemmy`: the location on the server where lemmy can be installed, can be any folder
#                                if you are upgrading from a previous version, set this to `/lemmy`
root@192.46.xxx.xx domain=192.46.xxx.xx letsencrypt_contact_email=my_email@gmail.com lemmy_base_dir=/srv/lemmy

[all:vars]
ansible_connection=ssh
```

As an effort to make the process smoother, I set up a [SSH Public Key Authentication](https://www.linode.com/docs/guides/use-public-key-authentication-with-ssh/) with no password set. From my local computer, I am able to simply ssh root@192.46.xxx.xx and gain access no problem.  

However, when I run the following on my local machine: `sudo ansible-playbook lemmy.yml --become`, I receive an error:

> PLAY [all] *******************************************************************************************************************************
>
>TASK [check lemmy_base_dir] **************************************************************************************************************
skipping: [root@192.46.xx.xxx]
>
>TASK [install python for Ansible] ********************************************************************************************************
fatal: [root@192.46.xx.xxx]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@192.46.xx.xxx: Permission denied (publickey,password).", "unreachable": true}
>
>PLAY RECAP *******************************************************************************************************************************
root@192.46.xx.xxx         : ok=0    changed=0    unreachable=1    failed=0    skipped=1    rescued=0    ignored=0

Can anyone point out where I am misunderstanding how this all works? Thank you very much for your help in advance!

**Comment by PatMulligan** [comment]
It was using the ssh private key from ~/.ssh/ but since I was sudo'ing the process ~ was /root instead of /home/me so it wasn't finding the ssh-key I had created.

So if you've created and copied your ssh-key pair in the user directory, then when you `sudo ansible-playbook lemmy.yml --become`, Ansible is now looking in /root/.ssh for your private ssh key, but it's not there because you created it as a user, which placed it into /home/user_name/.ssh.

So either you have to:

1. copy your private key from /home/user/.ssh over into /root/.ssh
2. create an ssh-key pair as root and upload it to linode/digitalocean/etc
2. hardcode the path to the user in the `inventory` file; something like:
```
[all:vars]
ansible_connection=ssh
ansible_ssh_private_key_file=/home/your_name/.ssh/private_ssh_key
```

**Comment by Nutomic** [comment]
You were running Ansible as root? There is absolutely no need for that, you can run it as your normal user.
