### ISSUE TITLE
Resetting a password doesn't work

### ISSUE THREAD

**Issue by Rynach** [LemmyNet/lemmy#1488]
### Issue Summary

On my instance Sopuli.xyz when an user tries to reset their password, no email for resetting it will be sent. Instead, an error message appears : _error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:332:_ . The page may keep on loading and nothing appears.

### Steps to Reproduce

1. Create a new account with email on [http://sopuli.xyz](http://sopuli.xyz)
2. Logout and press "forgot password" in the login screen

### Technical details

An excerpt from my Docker logs, mainly the same error message. 
[lemmy.log](https://github.com/LemmyNet/lemmy/files/6110391/lemmy.log)
This has something to do with Nginx and SSL, even though my instance's SSL is all fine [https://www.ssllabs.com/ssltest/analyze.html?d=sopuli.xyz&latest](https://www.ssllabs.com/ssltest/analyze.html?d=sopuli.xyz&latest). I also noticed that my instance didn't have postfix installed when these errors started to appear, even though installing Lemmy with Ansible sets also email for it.

**Comment by dessalines** [comment]
Did you search for that error?

**Comment by Rynach** [comment]
I have searched for the error. The error seems to be a SSL handshake failure and some kind of mismatch between TLS versions. One answer I got was that the error "an also be caused by trying to connect to something that is not an HTTPS server" and can happen if one's proxy settings are wrong.

**Comment by dessalines** [comment]
Are you using the postfix email, or your own smtp email? Because we haven't tested the smtp one yet.

**Comment by Rynach** [comment]
I am using postfix email. That block in docker-compose.yml is correct. I restarted postfix and my instance but the same error still persists.

**Comment by Nutomic** [comment]
Did you enable TLS for email in Lemmy settings? Can you reproduce the error when sending emails to different providers?

**Comment by Rynach** [comment]
TLS is enabled for email in the settings file. I have reproduced the error with Hotmail, Gmail and Onzmail.

**Comment by Nutomic** [comment]
If you are using the postfix thats included in our docker-compose.yml, then tls needs to be off.

**Comment by Rynach** [comment]
I set TLS off in the email sending configuration.... but the problem still persists.

**Comment by Rynach** [comment]
No need to solve this issue anymore, I had to restart the instance with `docker-compose restart` and now resetting a password works! I feel really stupid right now.
