### ISSUE TITLE
Finally that far and then i'm stuck...

### ISSUE THREAD

**Issue by anon238** [LemmyNet/lemmy#1492]
I'm looking for some help here. I got finally my Docker containers running, however. I still can't access the UI or do anything at all.

### lemmy_lemmy-ui_
```
Inferno is in development mode.
httpbase: http://domain.org:8536
wsUri: wss://domain.org:8536/api/v2/ws
No JWT cookie found.
http://localhost:1234
```

### lemmy_lemmy_
```
Starting http server at 0.0.0.0:8536
[2021-03-12T20:07:38Z ERROR r2d2] could not connect to server: Connection refused
    	Is the server running on host "postgres" (172.18.0.4) and accepting
    	TCP/IP connections on port 5432?
```

### iFramely logs and Postegres too long, put them in a hashbin.
[LOG: lemmy_postgres_](https://hashb.in/#CoCwpgBAZglgNmAzhARmOB7AdgcxriAFwyJBmQBMBDQqlKxSRAT0ULAFsIB3eOVSBm5YwFVMwgBXRgCcIAIgAOGNjhlJ5AOgBQoclNkQO0whCpxEJIVlJMwMgG72IimRgDGSRDt3gI1WnpGCHc4E2deOH40CHwYQhhzGAAvUR54kAhMd3NIeTAsAH0AVQBlTUlCKAAOLV9ICjAoKkk4UwC6BkgC9wwKfBwIEAYzd16Zftw4CTQCiEZTYgVi4AAxWp1QBqaWtqIwAA9TRioZd0zerFgcSRkaGGx0qIF5sEWSfKnyEDrtABEaFQXFQcJBzmB3ABrRCSDjIU4Nch0BAUHywA4DFz2DjkRAPLDIR6HcgJAj9dTuYgyCQAegcpxpcBgKBpylU6kQAEc4DSOhBNAKIBhIdp3Op7gQYShyRCqTAkPzBcLtIwEJTMRRmFgqDj3PNhuoxBxOBhqbEOIoEMasLQEo8BZoXCoYAcVehZRqdq1TBwqAdCpcROrsMgHRAAIwABkjbrVpMGjWa3v1CIohRQkigUHsocF4YATNUALIAIVjHrJXr2CWNEGS2EgYZWAGFReL4yFsNdbvdHrAELnHcqZJIsFhMSgMBhCGw7op5mKYIpTGHlYp7FBTTiCGzCABaSfT2dUedxBJJZK9myrkUsLDuDWAogkfqISGKoci7TaUqSMZeR0AE0MEkEIqBsLAhHmWgZEWPwOiCOxHGcaQBgALm/CAsJcHAA0Ifg9z+CA6QZJkWV3NQkG5Xknz3fhMBwfsmBgwhv24Kh4kxTc5FkJw5CWNhTkIB1NHzSN83DPdIwAZj3AsIDEtDIwAdjQ6SAE5NHU7SIBbCAAG1pIAVgAXQgAAZAB5ABxNCsME2DMQABRUQhKNKABFcyI3zTQADYhRsA5qj8wo/IAFj3RR3Do/BJAOPdjEQOAABpOwteA0hQCQcDGCAAAoAEE4EUfBICjUTNHDQpXDAcMAEoI0jSrwwU8TIwLGS0oig94m0MSJKk2T5MUlS1M07T1N04BmwM4yzKs2ysKZNgCkxR5inHA55g8SE3gUEiZBpEcsFZVzKK5HlNG8JzrM88zNCM8LpPzeR+vEySZLk/M2qU1Twua8TpOm2bDL8habLs/xAUQ+ZWHYLh2OQRAQEqfxrDMUwBs+4aftG1SNJB97Bq+kbIz+tCAc0SNqlavTDNMizIawhCujh1auH0cVNWfUZPGXTsxw9ENtHRkQ3WQniWNEbRmwAJQAUUK4AFYgP5lcKktCtKBXv20GlpCO7JzBpFB8F5Xb7D3ApCGpZR8GElG7JgHBIJkTELahK2bbtjAHb3M8KBQTQKBpAAqNiOI7bjXkl3mUbRihrAdbGhu+36xqp4ypvp+amaWiAKTAGAnDEZo2H1Sok+EQuwE5SQkFY1PSbx8nM+a7OQbmxnFqhuhTQ7cCJCodUnCIO4CRHu0CW0USPrTsmKazvy6Zm7uIYL+goTUECsDEbhTT2uR5AYmAcn4dRLTPq8shae9wBkeQCqcgBJIjwvzRriXYfeMggb/OyNAjMTHG6d8aUw7ivLuhllIbyhgnQgHZq5YBAQvVuS9IEBVzj3Zm0NAhsxYBzWIyNUbtGsKLJO4teLODYBgRQ64KDfhcuyMA91YjjlMK4DwXh0qWjeGAAA3LXKgPMY4OVMJIRQPgnZZA8LkOykFTCblHIw5uuMM4E2qFpAG0DpKRjMgAdUKnLAAci/ExBdIIGGREweGnBZHnwVNwewkBlF720IHFAdl2IyHHLgOyBRkSYnkLbEwT8WiEHADaa+09oCmgceYQWQZp6IG0MBUCOQbDnHAqCUg+hsr/36B2RQuEQD0E0JcKAQo5CoQIJEwQy58QQD3IVNKpptB7j3BEkAdE5H8HAmITp3S9wgFcmlepEARBHCIDAWszAQKF1HOw+IQcdBqLAW3f6zVwrKWqNA8McD7IsWcuddQbCCz+UChAYKoUerRVilgeKiVpCpV4ZlMQBTcp6iKiVMqTUWo1XUA1f5vlWoDQ6mJaS3VIpmybvPFuGiIGaB2Xs+mBz85QxWuwPxgxHgvycg4cKZgKAUA5MgeQgNqbU3kGlZQsEIBPReqghF4CqYov2YcrIJI1oEDxQSgKIjSU8PkGhNCNKnT0sZfmZl6jWXbOUjnNe+l0W92WtynFVzNouh2l7Uw8hDrHVHGdFhl0aTXU0Lde6j1nqvRlRsjByKdL03CupTlrNgiEIRjwEYCD0Y1xoG1EmsrNkQKJusxe7dHr5iwUqlVuD3W2KIVzMAIiJBLBHvzUwgZhYzyAA)
[LOG: lemmy_iframely_](https://hashb.in/#NgbQzGC2DuCGBOA7UYCckBcACHWC0ekAlogKoAOALkZAKZaID2lWAzrZQHRYAitAZrACuAG2qIA5lkqNsARgAMSyKwBQKKHCQp02XAVbkSAZRG1a5ACo16TFuy5YAmoyHw2AY3hEqWaERERLFoADyIWIn4scKwAE0ZaVgZmNkpYAE8sIXIsfkZ3WBYzWFYWRWU1FAAmYkQ8nUxcLAAxfNoAN1p3cnhGD0TWEil+ANpsUFQFSA8RIVKuzgArVgb1cE0EZHBdJoJaimo6ZPsObj5BUXEpGXklKcr1mE2GvRwDI0RTcysbY7ZT5yudysLw+Fj+QLBMIRKIxeKJP6lDJZHJ5ApFWglMp3FRrMA1Ej1baNXCteAdLpYHp9AZDXKjcYgSbTWbzeBLFbEvEbbTE174QgkA6/Oz/RznYRiOk3LDle7cp68tAkt54QwmMwWaxHUUObguNyeby+CFBUIxSLRFjwpK6tKZbK5fJYQpYYqlWU4h742pE5X8skU7q9fqsQaSelmRnMmZzSgLZarDSKrb+3aCshUEUpPW8ASSq7SWSeioKrSpnb6NUfL5a7MnRwG4Ggk0BM3Q6Kw60JW05+0op3ot2Yj1y3HVX2MF5NQOdYM0sN0kZRrATKaxtkcpNMqaxQqwae4FAAVhZcYTnP9+PwWFI4akHlgHgAFvRaJISGNkrFaHhHy/aDWZk9zSQ8cBPM9N0TPlrzwLAADlGDdPpYCCaBn3CWgRCID1l3oH94w8eNYk4UigN3fcwNXcBTw3eN2Wgq8qhvAgsBAKo5DwBQwDwORmKqBQMAUAB2DAABYqgAXQwa8ABlGFgWI6XQzDsNw3pICwZ9KEochWAwAB6AzIngWA6BEdJOA8RhIAMgBHWADJU+M1K4ZZGEQcjIBAg8+SaCC6IvF5YKwABJfhTPMzJyFmCQSCSEQFJ/WIMC8nyqIC1l6K3GDmLg/QsA8OMbLiGzYHi+QxOEtLKL8o8aMg7LGN0EKCokd8uiIDwsAAMiwOg0mwVBjxq0C6vAhrAoYy8WrygU2I4rieL4rABKE0SJOk68AGEsq6bBoHyABrSkxLE1IEGIzhRt8tN6rAWi9um4K5tY9jOO43j+MEkTxKkmTmN2894AO47TuPC74Cum6Msmp6cqYli4PepavtWn6Nv+nantB+ATvcY85Eh6G1282q7omh7GqC3KkYWj7lu+9a/q2wGcb8MGCeYpEodoEiYfG6iqamhHZpvO86X/V9gg/RAvyYH8/yfV8BYpoXHuB0XMBCiWIylt9ZflxhFf11XK0pjWoJm7W5t1h9lYNuK5ewBXf1N0n0sFzLNeam3xfvQqHZlp2jZNh2zZVdXqee2m4LexbPpWtbfrEsBWawAB1DCXJwlgn2odpCj5s4yvigAaaJEFjJSIwAIxEJ8jtcvn5GPAA2KoI/5b2rZem9EOQx80OzrDc8jfCOFoIji7Ij3yfNqORd9gG6ZRxOmZTtPxIh+TFOUkfXNyDStJ0vTDOMiKzKwyzrNshynIP3OOQ8rv/Lhn3rZXuCB8Soe/Ef3Cow4iT2niRWeO4yZjTVj3Jqn8QrxwZmjZOG0t5nSwLvGuUhnKj3UiVbSul9JGRMlfCyVkbL2Uctg1yz9PJzygQvGBNNEbfyQr/VC/9VJjzwsAwiV1wHAXnpHRhMdmHzTXozdGzNU7SWPMxDB+9OG4M0vgs+RDL5RTIXfShAC3KsBfnQ26DD3691jghVhKFh6KJYNwgiU8+HXQMbDYW8Nl7wORgnCRyDxJiRkUTeREYqFcOPiowhF9IrX00RQh+ViaGv3upbWBfc4LhXCRZKksV4rIUUi3OJFto5ay/rsQqxVNLxEgOVRA+lZRVVyYvFxcC5ptQ6t4bqfUBqwCGiNRxXtjGJNMcYNIUM6QpJIZZfhFF6FCN6UwsWcEABCJR6CkAAEqyUHMESAtc+ZJEoM+V05I7JCCIOSLSjB5ixCwOSRAP54BVJUefdIQIykVM0bU4RBSQojKiukoQTsEpJRyd06B0yRGzKKUVUoJVnkVWqdVIFRjnEfySUU9qcsWm9X6hwDpWBhpvJBR8uaAzLrDPURE8ZkDDFTMRSY0RCz2C3lWes2gmztnSD2SwA5RyTnPjOcRS574bl3NPg8p5pdECvPhVShJMy/b5TgqwbI5B8iUAAALEI0bfG8lpHlCAYOYC5r4RDkDxdSvpoibyUH8DpBYt8wmjJvHLaASQ+rZBAokE10rQWyreFgOKuyhC10ieEQijA7XfPlYMjF1lECUG8LXIQ8YPX5NcXNdV19ohJHgEIRAiA6QeSwAoTghbi0YAABwKCTUvBpN4ACCAAFUKMtYhKpIJQKpBkEgsoubAa5WAw3XwANx5njRIdq7hSChWwAZH8I7K31ORV89NMVfmZMStklKc6kWmIKhCmQpSxVVLkDUyV3d8UppvE0tFXUMXtM6ZumlYKAAUrtt4AEpM6bCGNgYwHBCy7PoPBAA8jwAAogAfUsLJYwYHlkgYAFIge2pYMDpB4I1tIJYAAEoB5ZoUABaIGeAy3aMcjydAY1YELt4WA9d6AyCwAAcgUAx/qsATpJEg8YQqHk5ZESIB5JIPaLmYcsJYOtXHOWJDbZXdgRUTm10yEpVgNHsJ6y6NQEYj54yUc6ppwo/HxX3rNWColQyIyLtIeSz2wLTUysKXSpZjK0QbK2bEHZ7L+WHOOfQHl5z+XXK6EK3SIq3DQvFbfIzdnWrysVcqtVpLSGargtq1weq+ZaSwsak9b9bNesKRaq12VbVprSXBR1zqURuoeAIyZp7csEovXBP1z4A1ButdZftpXIZRo8rGog8bE3Zficm6tyWEuZBwpc7NuaIz5uLUWotZaK1DbyVW5F9bG0CpbTG9tnbXMul7Z19IQ6+AjrHbeSdfaZ2/Mi3lz542fl/KyclVKK26lbvNT63dUKD2VThRA6zCLPUNfyj61FnVWmYsGjirpAPBF1eB+euCpnCwWbGQ4uHtWcuI9Gz6hV5AlVQ3i6km+JUxtYB1Wlg1mXbsg59Za4NNryElcyGV2gTqMWuqLtViZlKEcjeRTeZrrXivtdDSzm8PMesxrjQmwCb33lI6wA5hlaznPMtc+5/ZtAvPct5elq5grsD3KMjq+AYWJWY759jgXpjn3GzGGdd9GdP2SG/b+6U0sgOgYg1BmD8HEPIdQ+hrDOH8OEeI6RxA5GWBUaICpujSEmMsfKexrAnHuM5rsQZwTvaRNiYkzroQUmkjxSnm4egCm4g4RU5LdTkQupFx094PT1APIY5q9b4ba27cvtkc713Eh3c6U9wB4D4HOP+4Q0hlDaGMPYdwwRoj74SO9Gj++WPCB4+0aLIx5jrG08Z+jbxtvlSDvCdE+JzzxfSil8qeX+Tima/1zr0M1v9A5wN60wZjvvOnE4+RQl0myzRzTzUQALQWxLXLVpyVw2ybW2zbSnT23SyEz7RZxO1oDO0pAnSnWuwkBgNx0l1iyJxZ00S1SiEpzlnS0NSyyt3/1t3NTggZ2tXZGKwezZw5xdXICqwIMFya3CBa0DVFxDSO0l0jT6mjT6wG3lzoJ6XqyV3tx/AwEJgHyQC/SwB/RHwjH/QQnH192g1g2nyDzn1D0XwjxXyjxj0oy3wT132TwPwRCPx42zwE3PywHzyv0k1vxkwf0ryf2UxfzUzf0b200/1bx/14NMSAMzWmzAIgPm0EmgIVzPVxzgK20YFbV2w1xQMO3QOHV+XOxwKu0wJu2SPkNxwQVRiTgxm8WkjEghizisRdD40Liul4APQrhIGrjpHrkbmbhSllHbk7jKIANMUqPXkkRTh8W8Uzh0WaILiLhInaPKXLkrm6Lrgbg8CblzhbkGI7kiNEXGM8RqLOhkWYkaJzg9HziIFaOLmWIqVYE6KrlmEwSwF6K2P6Nbn2JGIYLBSOKQROOmMJlmKaOuNuKWJ4A6LWJeJ6M2O2POS+OGPADkDoHgF6HgDAm2h7VFBGF7TRCDCpBDAGGwGW2RNRPRMxOxJSFxIuXxLnEJIXCqVJLABRK6ApPGixJzWpJIFpLaHpOpFDCZNUCAA===)

I really hope you could help me out. I really dig this project and I'd love to have an instance myself.
I'm running Ubuntu 18.04.5 LTS‬ with Plesk Obsidian, although I have followed the Docker tutorial [here](https://join.lemmy.ml/docs/en/administration/install_docker.html) and started it with CLI, however I can configure them also in the Docker's Plesk module.

**Comment by Nutomic** [comment]
Make sure the database login details are identical in `docker-compose.yml` and `lemmy.hjson`. If you changed anything after the first start, you probably need to wipe the volumes folder and start over.

**Comment by anon238** [comment]
> Make sure the database login details are identical in `docker-compose.yml` and `lemmy.hjson`. If you changed anything after the first start, you probably need to wipe the volumes folder and start over.

I wiped the volumes and restarted over but have exact the same problem.

**Comment by dessalines** [comment]
1. Which guide did you follow?
2. Post your docker-compose.yml and lemmy.hjson files as nutomic suggested above, because it can't connect to the DB.

**Comment by anon238** [comment]
Didn't read the logs and didn't helped me out. Closing this issue for now. All other Docker-containers are working fine, however this one isn't. I tried all the guides followed on lemmy.ml, but none succeed. Thanks although. Passing by.

**Comment by thistehneisen** [comment]
Did you have any success? I'm interested in setting up Lemmy with Plesk also.

**Comment by anon238** [comment]
Nope

On Fri, 9 Apr 2021 at 18:03, LemmyNet/lemmy -
reply+asfyd57nl7skrcmpmcrqwbn6prn4pevbnhhdc72fyq at reply.github.com <

**Comment by thistehneisen** [comment]
@dessalines is there any particular instruction for integration with Plesk? I just also tried pulling the Docker image via Plesk Extensions, but it had problems with manifest.

**Comment by Nutomic** [comment]
We only support the installation via Docker or Ansible, as described in our docs.

**Comment by dessalines** [comment]
I don't know anything about plesk, and wouldn't be able to help test it. You'd have to provide logs for me to help in some way.

**Comment by anon238** [comment]
That’s difficult since Plesk is using their own software packages and
repo’s.

On Fri, 9 Apr 2021 at 18:42, LemmyNet/lemmy -
reply+asfyd5534i6kkjerpfthp4f6prrinevbnhhdc72fyq at reply.github.com <

**Comment by thistehneisen** [comment]
I am open to collaborate with this if there's a channel where discussion might be quicker. That way, upon solving, I could create a documentation for Plesk users also.

**Comment by anon238** [comment]
Matrix?

On Wed, 21 Apr 2021 at 12:27, LemmyNet/lemmy -
reply+asfyd54vocjxfwg3pqsyx5n6rppp7evbnhhdc72fyq at reply.github.com <
