### ISSUE TITLE
Add a user setting to show / hide scores / votes

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1503]
Will reduce a lot of anxiety related to ppl not wanting to see downvotes.

Coulda swore we had an issue for this, but I spose not.

**Comment by Nutomic** [comment]
We can probably implement this together with the bot tag/filter (#1357).

**Comment by dessalines** [comment]
I still have to do all the front end work for this, so I'll add issues to lemmy-ui for all these.
