### ISSUE TITLE
Create default helper methods for DB forms

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1511]
Nearly all the DB forms, especially used in tests, are basically dupes, and every migration requires a lot of these. A simple way to clean this up would be to use default forms.

Problem:

This, 30 times all over the code: 

```rust
    let new_person = PersonForm {
      name: "timmy".into(),
      preferred_username: None,
      avatar: None,
      banner: None,
      banned: None,
      deleted: None,
      published: None,
      updated: None,
      actor_id: None,
      bio: None,
      local: None,
      private_key: None,
      public_key: None,
      last_refreshed_at: None,
      inbox_url: None,
      shared_inbox_url: None,
      matrix_user_id: None,
    };
```

Solution:

`let new_person = PersonForm { name: "timmy", PersonForm::default() };`

**Comment by Nutomic** [comment]
Good to see so much red in a diff :D
