### ISSUE TITLE
Fork RTV reddit terminal viewer for a command line client

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#152]

**Comment by Findarato** [comment]
Maybe just improve RTV to support lemmy?

**Comment by dessalines** [comment]
Yes, basically all it needs is to wire up the API calls. I assume this would be better as a fork, maybe called LTV or something, rather than putting it all in the same codebase.

This is more of a wishlist item, that would be sweet if anyone interested wanted to take on. I could see myself getting to it way down the road otherwise.

**Comment by Restioson** [comment]
Haha, LTV is a fun name
