### ISSUE TITLE
Polish translation causes minor problem with the UI

### ISSUE THREAD

**Issue by harcesz** [LemmyNet/lemmy#1528]
If you change the interface language to polish (in 0.9.9), one of the top menus will drop bellow the others.

![Zrzut ekranu z 2021-03-30 19-39-46](https://user-images.githubusercontent.com/1368026/113032649-5e661a80-9190-11eb-8448-a2e13b9d8a11.png)

I'm guessing that's because "top all time" is "najpopularniejsze kiedykolwiek" and no sane person would expect that much text there. I could somehow abbreviate the translation, but decided to use the proper wording to make it easier to understand for end users. 

But it doesn't seem it's a case of the first entry being to long, just one or some of the positions. Despite that the entire menu is always dropped to the new line. Would it be possible to tie the drop-down menus position to the current choice, or maybe trim it to match the space?

**Comment by harcesz** [comment]
Sorry, I assumed it's is self explanatory, that's the most active/top posts menu. It' perfectly fine for mobile, but on basic desktop it makes the interface look more complicated (2 rows of menus, instead of a single streamlined one).

**Comment by dessalines** [comment]
This isn't a bug, depending on your browser text size, and zoom level, that menu will either stay on that line, or get pushed to the next line if there's not enough space. The only other alternative is to change those translations to abbreviations of some kind.
