### ISSUE TITLE
Sometimes Lemmy eat sent private messages

### ISSUE THREAD

**Issue by felipeforte** [LemmyNet/lemmy#1531]
It happens from time to time, I'm not sure if my unstable connection has to do with it, probably. But my personal messages to other users tend to not get sent from time to time.

**Comment by Nutomic** [comment]
Do you know any way to reproduce this? Any errors in the browser console? Without additional info this is impossible to solve.

**Comment by felipeforte** [comment]
I will close this issue considering it has never happened again and was probably a problem with my browser.
