### ISSUE TITLE
Rewrite remote Post/Comment URLs to open in local instance

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [LemmyNet/lemmy#1540]
### Is your proposal related to a problem?

When clicking on a link to something that comes from another instance (which is very often since I use sopuli.xyz and most Things are on lemmy.ml), it links me to the link in that instance, which can be pretty frustrating if I wish to interact with it.

### Describe the solution you'd like

Making it so that when a link directs to something from another instance, instead of taking me to it, making it federate it to the current instance and open it there instead. Blocked instances would be exempt from this.

### Describe alternatives you've considered

The way I work around this is having an account on lemmy.ml and using it when a post hasn't been federated to sopuli.xyz, I just upvote it so that it gets to sopuli. For communities or users I just search them in the !name@instance format.

**Comment by dessalines** [comment]
IMO that's pretty dangerous, what if someone in their comment wants to link to the other instances version? If we rewrote their comment, that would get overwritten.

**Comment by Nutomic** [comment]
I dont see any reason why a user would want to view a post or comment on a random, unrelated instance. But one thing that would be useful to add is a button "show on source instance".

**Comment by Nutomic** [comment]
Same as https://github.com/LemmyNet/lemmy/issues/2987 which has more discussion.
