### ISSUE TITLE
Support bridging communities of other news aggregators

### ISSUE THREAD

**Issue by Victor239** [LemmyNet/lemmy#1542]
### Is your proposal related to a problem?

There are various news aggregators I read - [Hacker News](https://news.ycombinator.com/), [Lobsters](https://lobste.rs/), as well as many communities I read periodically on [Reddit](https://reddit.com/), [SaidIt](https://saidit.net/), [Postmill](https://postmill.xyz/), [Tildes](https://tildes.net/), [Steemit](https://steemit.com/), [Ruqqus](https://ruqqus.com), etc.  It's time-consuming to follow multiple news aggregators/Reddit clones, so it would be great if there was a way that a user can bridge an off-site community into a new Lemmy community (similar to how [Matrix](https://github.com/matrix-org) bridges IRC, Discord, Slack etc into it's chat network). 

This also helps prevent Lemmy becoming [just another competing standard](https://xkcd.com/927/), and again is a similar approach to what Matrix is doing for chat technology by integrating with everything in order to overcome the [network effect](https://en.wikipedia.org/wiki/Network_effect).

### Describe the solution you'd like

When creating a community a user can choose to bridge an existing off-site community instead. They then get to pick from a menu and choose a community on one of the aforementioned websites. Then the link and text posts get mirrored to the Lemmy community. 

### Describe alternatives you've considered

There's not really another solution. Currently all these news aggregator sites are silo'd from each other, so it will take someone bridging the communities together in order to change there being so many Reddit clones with similar features yet no cross-compatibility. 

### Additional context

To reiterate it is _really_ time-consuming to follow multiple news aggregators, a factor which is preventing Lemmy getting as popular as it could as well as being an obstacle for optimal user experience.

**Comment by Nutomic** [comment]
I suppose this could be done by following an RSS feed from the other site (or possibly using the API). But we certainly wont have time to implement something like this anytime soon. It might be better to write a bot which uses the Lemmy API for this purpose.

#119 is very similar to this.

**Comment by dessalines** [comment]
2nded, this would be very easy for someone to script out using the lemmy-api.

**Comment by Nutomic** [comment]
I think this is out of scope for Lemmy itself, but could be implemented with an API client.
