### ISSUE TITLE
Customizable markup language?

### ISSUE THREAD

**Issue by andreymal** [LemmyNet/lemmy#1548]
If I understand correctly, Markdown support is hardcoded throughout the whole Lemmy code, and all post bodies are expected to be in Markdown. However, this is a subjective choice. There are other markup languages which may be more convenient for some specific instances, like reStructuredText (so powerful), BBCode (so nostalgic), raw HTML (properly sanitized to prevent XSS, of course) or maybe some proprietary format that I could invent on my own. As an instance administrator, I would like to be able to choose the markup language for my needs.

I don't suggest implementing languages other than Markdown - the Lemmy developers are probably not interested in this and it will be difficult to maintain.

Instead, I suggest just doing some refactoring which would be helpful to make it easier to add custom markup languages.

First of all, it would be nice to define a `body_format` string somewhere. I see three options where it could be defined:

1. As a database field in all markup-related tables (posts, private messages, bio etc.). This will allow to use different formats at the same time. However, the disadvantage is that Lemmy have to do additional migrations for all related tables and affect a lot of API.
2. As an instance configuration variable from `config.hjson`. This means that all posts must have the same format, but I hope this is pretty easy to implement without touching the database schema. But what worries me is that `settings` is [a local variable that is not accessible outside of the main function](https://github.com/LemmyNet/lemmy/blob/main/src/main.rs#L32) 🤔
3. As a field in [the Site table](https://github.com/LemmyNet/lemmy/blob/96efe302cea000b3fa721454232a8fc1ca2a962e/crates/db_schema/src/source/site.rs#L6), but I'm not sure if it's a good idea to touch this table so frequently.

Using this `body_format` string, the `markdown_to_html` function could be refactored something like this:

```rust
pub fn content_to_html(format: &str, text: &str) -> String {
  match format {
    "markdown" => comrak::markdown_to_html(text, &comrak::ComrakOptions::default()),
    // "html" => some_html_sanitizer(text),
    // "supercoolformat" => convert_some_cool_format_to_html(text),
    _ => html_escape(text), // fallback for unknown markup language
}
```

...and something similar in the [frontend mdToHtml function](https://github.com/LemmyNet/lemmy-ui/blob/7ddcac5fc0ce9c25ef147201aba8aac6dc129748/src/shared/utils.ts#L233).

As I said earlier, I don't expect support for formats other than Markdown, but if a similar refactoring was done, then I could easily add support for any markup language I need and make a custom Lemmy build without losing backward compatibility with vanilla Lemmy 😊

**Comment by Nutomic** [comment]
> As a database field in all markup-related tables (posts, private messages, bio etc.). This will allow to use different formats at the same time. However, the disadvantage is that Lemmy have to do additional migrations for all related tables and affect a lot of API.

This is not much of a problem, anyway we will have to store the mime type for all posts, comments etc for federation with other projects, which might send their data as html (see #1461).

But all of this will require an alternative frontend which takes advantage of the functionality. At the moment there is not a single alternative frontend being actively developed, so I'm tagging this as far-future until that changes.

> But what worries me is that settings is a local variable that is not accessible outside of the main function thinking

The config is available everywhere in the code, simply by calling `Settings::get()`.

**Comment by dessalines** [comment]
Anyone could work on this, but its not a priority for us.

**Comment by dessalines** [comment]
I can re-open this if someone wants to work on it.
