### ISSUE TITLE
Make the ansible config.hjson settings overwrite the server settings.

### ISSUE THREAD

**Issue by the-digital-anarchist** [LemmyNet/lemmy#1549]
### Is your proposal related to a problem?
Right now the config.hjson settings only gets set on the first deploy with ansible.
If you want to set further changes you have to do it manually on the server.
This way your settings in your repo don't reflect your settings locally and in the repo making it harder to share and more confusing.

### Describe the solution you'd like

It might be beter to have the settings in the repo rewrite the server settings everytime a deploy gets made.
This way the code in the repo is the source of truth.

**Comment by dessalines** [comment]
I'm not sure which way I'd prefer it, @Nutomic might be more opinionated on it since he knows ansible best. It does seem strange that we allow overwriting of the docker-compose, but not the lemmy.hjson... both are essentially configs, that need some customization.

**Comment by Nutomic** [comment]
I think it makes sense to overwrite the config as well, I will just add a comment into the file about this.

**Comment by 4caoi** [comment]
A note from an upgrade from 9.9 to 10.3, it was required to go into lemmy.hjson on the server to update allowed_instances to the new format ["..."] as it did not get overwritten despite changing on ansible side. Works as expected after manual update.
