### ISSUE TITLE
Forum frontend for Lemmy

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1554]
![Screenshot_2021-04-07 phpBB • Community Home](https://user-images.githubusercontent.com/1044450/113863893-be188300-9799-11eb-8d72-d9f167cc68c9.png)

It would be interesting if someone created a frontend for Lemmy in the style of a traditional forum, such as phpBB in the screenshot above. This would be relatively easy to do, as frontend and backend are completely separate in Lemmy, so you could easily remove lemmy-ui completely, and replace it with the forum frontend. [We have more information about writing a custom frontend in our documentation](https://join.lemmy.ml/docs/en/client_development/custom_frontend.html). In the Lemmy backend this would only need minor changes (namely, config options to disable votes and nested comments).

I was thinking to write something like this myself, but unfortunately I dont have the time. It would be very cool if someone could start such a project.

**Comment by EchedeyLR** [comment]
If you can, take UXP-based web browsers into account which where not taken in the tweaking of Lemmy frontend.

http://thereisonlyxul.org/

phpBB, Discourse and Invidious are compatible at all with these browsers.

**Comment by harcesz** [comment]
Forum frontend would be brilliant, but one thing really missing for full functionality of a forum is private/closed communities. This feature would allow us to finally kind-of compete with FB's functionality of both having news and a safe(ish) space to talk, without random people watching. Also possibly would make Lemmy the first full-blown Fediverse forum engine eventually.

**Comment by Nutomic** [comment]
This exists now in the form of [lemmybb](https://github.com/LemmyNet/lemmyBB).
