### ISSUE TITLE
Mark posts as seen / hide read posts option

### ISSUE THREAD

**Issue by akomoy** [LemmyNet/lemmy#1561]
### Describe the solution you'd like

A button that marks posts as seen and removes them from the front page.

### Describe alternatives you've considered

An option that makes lemmy mark posts as seen if they are opened.

**Comment by Nutomic** [comment]
So this would only hide them from the front page, but they would still show up on the community or user pages? Because there should be a way to unhide them somehow.

**Comment by dessalines** [comment]
We already have a `post_read` table, but aren't doing anything with it yet. Basically we'd just insert to that on every `GetPost`.

Then we'd add a setting for `hide_read_posts`, and alter the view queries to not show. I think this should also hide them from the front page, and community pages.... basically everything but search.

**Comment by ajitam** [comment]
How come this issue is closed? but I do not see any "mark as read" button on UI?
I would really like to see this and as far I understand it is quite simple. Basically you do GET to post URL.

Currently I'm just doing Command+click to open post in new tab and then closing that tab

**Comment by NicolasPA** [comment]
I think it was closed by mistake, the referenced commit does not seem to provide the requested feature. Please reopen.

**Comment by GokulDas027** [comment]
> Then we'd add a setting for `hide_read_posts`, and alter the view queries to not show those. I think this should also hide them from the front page, and community pages.... basically everything but search.

I would suggest hiding it only from the front page feeds and not from the community page. It's difficult to find something once seen. Thought it was a bug until i saw this.

**Comment by Nutomic** [comment]
> How come this issue is closed? but I do not see any "mark as read" button on UI?
> I would really like to see this and as far I understand it is quite simple. Basically you do GET to post URL.

That would be an issue for lemmy-ui.
