### ISSUE TITLE
When building untagged commit, include commit hash in version

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1563]
At the moment it is impossible to tell which exact commit Lemmy is built from, as the version number always refers to the last version. We should make it similar to the output of `git describe --tags` (eg `0.10.3-1-gd566e57`), so that we can tell when an instance is running a dev version.

**Comment by dessalines** [comment]
The frustrating thing about these, is that you always need to write a version file, in our case : 

`echo "pub const VERSION: &str = \"$new_tag\";" > "crates/utils/src/version.rs"`

But then you have to commit that change... which creates a new hash, so there's always two hashes, the current ( which really only updated some versioning files ), and the current - 1, which is what the website would display. So the site can never display the actual current commit hash. As long as you're okay with that, I've got no problem doing it, even for prod versions.
