### ISSUE TITLE
Move fetching ActivityPub objects to separate API endpoint

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1584]
At the moment fetching ActivityPub objects is handled through search, which is not completely logical. I think it would be better to move this functionality to a separate API endpoint (maybe `/api/v3/fetch_object`). This would also give us a concrete place to document the functionality.

**Comment by dessalines** [comment]
Agree, it is a little strange to have that in search, which should really only be for local things anyway.
