### ISSUE TITLE
Lock community if the mods are inactive

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1585]
We have a lot of communities on lemmy.ml, because anyone can create one. But many times the community creator stops using the community, or stops using Lemmy, leaving us with an unmoderated community. This causes more work for admins, because they have to manage these unmoderated communities (delete or transfer to another user).

As a solution for this, we could automatically lock the community is inactive, for example if no community mod has posted or commented in the community for 30 days. Then an automatic warning would be sent to the community mod team, and if that isnt acknowledged within 3 days, the community is locked, so that no new posts or comments can be made. To unlock the community, either a mod needs to unlock it by button click, or another user needs to request a transfer from the admins (there could be a specific contact form for this).

**Comment by dessalines** [comment]
I'd prefer the code not add complicated rules for auto-locking communities and things like that.... these are the things that tend to get more and more complicated as things go on and exceptions need to be made.

A simple way to deal with inactive communities would be to add a tab or page to the admin panel, that admins could then take manual action on. Now that we have `monthly_active_users` in `community_aggegates`, this is probably as simple as adding sort type or boolean to `ListCommunities`

**Comment by Nutomic** [comment]
Not necessary as admins can handle it manually.
