### ISSUE TITLE
Hide names of mods/admins in mod log

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1601]
The `GetModlog` request should include `auth`, and only return the mod name if you have permission ( IE, you're an admin, or you mod that community)

Once that's fixed the front end hacks can be removed:

https://github.com/LemmyNet/lemmy-ui/issues/285

**Comment by Nutomic** [comment]
We should probably also federate mod actions from the community and not from the mod user then. Would be another rather big rewrite with breaking changes.

**Comment by dessalines** [comment]
That might not be necessary. Its not the back-ends talking to each other, that we need to hide info about mod actions. Just unprivileged users of those back-ends.

**Comment by Nutomic** [comment]
A modified Lemmy could show the names of admins/mods publicly. But I agree thats not really a priority.

**Comment by dessalines** [comment]
A front-end hack is being used for this, it still needs a back-end solution.

**Comment by Nutomic** [comment]
This was implemented in https://github.com/LemmyNet/lemmy/pull/2313

**Comment by dessalines** [comment]
Ah woops.

**Comment by maltfield** [comment]
Sorry, what was the reason for this? It hampers transparency. At the very least, it should be an option that's opt-in (ie: mod log includes names of mods/admins by default)

**Comment by dessalines** [comment]
To avoid targeted mod harassment.

**Comment by sant0s12** [comment]
Isn't the mod name still accessible through the `mod_person_id`? You would need to do a lot of queries though.

**Comment by dessalines** [comment]
Yes, its impossible to hide that info from federated server runners doing queries.
