### ISSUE TITLE
Federate moderation actions like post and comment removals

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#1610]
For example, if someone makes a rule breaking post or comment in lemmy.ml, and a mod on the instance to which it was posted removes it, that post is still visible on lemmygrad.ml unless a mod on there also removes it. It would be nice if moderation actions were also federated.

**Comment by Nutomic** [comment]
This is already implemented, but only works if at least one user from the remote instance follows the community. It is also possible that you found a bug, in which case we need more details (you can send in private if needed).
