### ISSUE TITLE
Auto-title grabber doesn't work for Phoronix

### ISSUE THREAD

**Issue by LiamDawe** [LemmyNet/lemmy#1613]
This is a front-end thing, when posting to lemmy.ml.

Despite Phoronix using standard HTML tags to set the title, like every other website does, Lemmy seems to grab the wrong title when you use the "copy suggested title" link.

Lemmy will always grab a Phoronix post as:

> Linux Hardware Reviews, Open-Source Benchmarks & Linux Performance - Phoronix

You can use this as an example https://www.phoronix.com/scan.php?page=news_item&px=Libreboot-20210522

**Comment by dessalines** [comment]
This is an iframely issue, we can't control or fix those.

**Comment by LiamDawe** [comment]
> This is an iframely issue, we can't control or fix those.

Want to expand upon that? Doesn't really give me much to go on. I might even be able to help. The correct title is there inside the plain title tag as expected.

**Comment by Nutomic** [comment]
Its a separate project, their repo is here: https://github.com/itteco/iframely
