### ISSUE TITLE
NSFW posts are shown for non-logged in users

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1614]
Verified locally:

![image](https://user-images.githubusercontent.com/930215/119577491-be400280-bd88-11eb-8ff3-b38da4775082.png)

**Comment by Nutomic** [comment]
This should probably be configurable. Imagine someone making a porn instance for example, they would want to mark everything as nsfw (for federation), but still have it visible for users who are not logged in, because the site would look empty otherwise.

**Comment by dessalines** [comment]
I spose that would require a `show_nsfw_posts_for_anonymous_users` column in the site table.
