### ISSUE TITLE
Make removing content optional upon account deletion

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy#1617]
### Is your proposal related to a problem?

When deleting an account it would be nice if the user could decide wether or not their old posts should be removed.
See context: https://lemmy.ml/post/66254/comment/56422

### Describe the solution you'd like

Just a dialog with a choice.

**Comment by dessalines** [comment]
I don't really understand the use case of wanting to delete your account, but still have all your data there. Why not just not log in anymore.

**Comment by poVoq** [comment]
The name could be changed to *deleted* or so and sensitive data (as by GDPR) like email deleted from the account.

I kinda felt the same, but on the normal forum I moderate I get the request to delete an account from time to time and usually they just want their nick and personal data gone.

**Comment by EchedeyLR** [comment]
To add some ideas I expressed in the duplicated issue I opened:

> GitHub and Disqus move or can move posts to a “Guest”/“Ghost” account.

> So the content can be conserved at user desires.

**Comment by Nutomic** [comment]
@EchedeyLR Can you suggest a better title for this issue?

**Comment by dessalines** [comment]
A *really* easy fix privacy-wise, would just be to change the username to a randomly generated one for all acct deletion. And give an option of whether to delete content or not. Then we wouldn't have to deal with the DB nightmare of moving data around to different "ghost" user ids.

**Comment by EchedeyLR** [comment]
> A _really_ easy fix privacy-wise, would just be to change the username to a randomly generated one for all acct deletion. And give an option of whether to delete content or not. Then we wouldn't have to deal with the DB nightmare of moving data around to different "ghost" user ids.

I don't think that a ramdomly generated one is a good solution.

A person could link both accounts in some cases. 

Having a common account to move the owner of all of the posts and comments would ensure this doesn't happen.

PD: I will suggest new title in a little.

**Comment by Nutomic** [comment]
We also expose the numeric user id, so we would have to change that as well. And the apub actor id as well. Moving things to a different actor might be easier after all.

**Comment by EchedeyLR** [comment]
A good title would be: "Make remove content optional upon account deletion"
