### ISSUE TITLE
No validation for avatars source

### ISSUE THREAD

**Issue by dziewxc** [LemmyNet/lemmy#1618]
### Issue Summary

Users can put any url in their avatar and banner. By using it to pass their own website they can get information about IP addresses of other users as soon as they visit lemmy instance. There is also no check of the link, so it could introduce some other problems eg when user will use some big file.

### Steps to Reproduce

1. Send "SaveUserSettings" ws request with chosen url in "avatar" or "banner" field

### Proposal

Check if the host of image is the same as instance host and maybe if there is "pictrs/image" in url

**Comment by blackandred** [comment]
Looks like a serious privacy issue, and possibly can harm additionally when bigger files would be used - page load times could go down drastically.

**Comment by dessalines** [comment]
Somewhat related but we need a decentralized image host yesterday. I hate the idea that every single image in every post and comment needs to be duplicated across every instance. This is the largest piece of data and right now I've gone with allowing external images in favor of massive duplication.

**Comment by Nutomic** [comment]
Its easy enough to allow avatar/banner images only from the local domain when a user/community profile is edited. As for federation, we simply need to check that the actor domain and avatar/banner image domain are identical. Mirroring or proxying images to each instance for extra privacy would be a separate task imo.

Decentralized image hosting sounds nice, but then you need to store every file in multiple places and generally get a lot of extra complexity.
