### ISSUE TITLE
Website lemmy.ml appears to be down

### ISSUE THREAD

**Issue by IvoAndonov** [LemmyNet/lemmy#1622]
I'm sorry to post this here but I don't see any other way to contact support. For about 36-ish hours now trying to open lemmy.ml returns an error that the page is inaccessible. I tried opening it through my mobile phone internet service as well but to no avail. What's curious is that pinging lemmy.ml runs fine and the server seems to be responding but when performing a trace route, there are a few gaps. However, even with these gaps, the destination of the trace route seems to be responding, so I can't find a reason for not being able to open the page. All of the other websites I'm visiting are working perfectly, so it's not my internet service at fault.

[rado@arch]: ~>$ traceroute lemmy.ml
traceroute to lemmy.ml (51.38.33.237), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.307 ms  0.238 ms  0.265 ms
 2  212.25.58.0 (212.25.58.0)  0.833 ms  0.789 ms  0.826 ms
 3  10.1.14.1 (10.1.14.1)  1.428 ms  1.390 ms  1.418 ms
 4  10.1.14.4 (10.1.14.4)  0.704 ms  0.720 ms  0.744 ms
 5  ae51-117.bar2.sofia2.level3.net (212.162.31.81)  2.029 ms  1.985 ms  1.941 ms
 6  * * *
 7  fra-5-a9.de.eu (54.36.50.32)  24.829 ms  24.627 ms  24.567 ms
 8  * * *
 9  * * *
10  * * *
11  be105.gra-g2-nc5.fr.eu (91.121.131.18)  33.436 ms  33.366 ms be105.gra-g1-nc5.fr.eu (213.186.32.212)  35.914 ms
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  vps-5174633d.vps.ovh.net (51.38.33.237)  35.338 ms  35.243 ms  35.112 ms
[rado@arch]: ~>$ ping lemmy.ml
PING lemmy.ml (51.38.33.237) 56(84) bytes of data.
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=1 ttl=3 time=35.3 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=2 ttl=3 time=35.3 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=3 ttl=3 time=35.2 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=4 ttl=3 time=35.3 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=5 ttl=3 time=35.4 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=6 ttl=3 time=35.3 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=7 ttl=3 time=35.4 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=8 ttl=3 time=35.2 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=9 ttl=3 time=35.3 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=10 ttl=3 time=35.3 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=11 ttl=3 time=35.2 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=12 ttl=3 time=36.1 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=13 ttl=3 time=35.3 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=14 ttl=3 time=35.3 ms
64 bytes from vps-5174633d.vps.ovh.net (51.38.33.237): icmp_seq=15 ttl=3 time=35.5 ms
^C
--- lemmy.ml ping statistics ---
15 packets transmitted, 15 received, 0% packet loss, time 14024ms
rtt min/avg/max/mdev = 35.152/35.352/36.140/0.225 ms

**Comment by thangisme** [comment]
I'm experiencing the same issue

**Comment by samuraikidXDA** [comment]
Yep it's down

**Comment by IvoAndonov** [comment]
Well, whatever the reason was, after posting this "ticket" here, it has been fixed and works fine.

**Comment by dessalines** [comment]
https://lemmy.ml/post/67821
