### ISSUE TITLE
Show users in admin-UI

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#1643]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

I opened my instance for registration. Then i saw at https://the-federation.info/node/lemmy.schuerz.at there are 4 users on my instance... I did not know, which other users this are and recognized, one was a spam-account... so i blocked this user and removed all of his spam.

But i don't know, which are the other accounts. 

(Write your answer here.)

### Describe the solution you'd like

In admin-UI a list of all local registrated users and their roles. even in all local communities. And the best... give a editing-interface in userlist to block, delete or promote a user in other roles. 

It would be also a good thing to create new users via this interface (especially for instances with closed registration to give the admin the possibility for a new user).

Also make it possible, that admin can reset a users password, so he/she must set a new one at next login.

And also invalidate a users login (no login possible futher).

**Comment by dessalines** [comment]
This is a UI issue, and one already exists for this on lemmy-ui.

> Also make it possible, that admin can reset a users password, so he/she must set a new one at next login.

That'd be a separate issue.

> And also invalidate a users login (no login possible futher).

This is already done.

**Comment by mio-19** [comment]
> This is a UI issue, and one already exists for this on lemmy-ui.

May I ask which issue is it? I tried to search on lemmy-ui's github repo but I failed to find a similar issue

**Comment by dessalines** [comment]
https://github.com/LemmyNet/lemmy-ui/issues/456
