### ISSUE TITLE
Federated bans aren't working

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1650]
1. Ban a federated user
2. They are still able to post / comment

- [ ] Create a federation test for this
- [ ] Double check federated ban code.

**Comment by Nutomic** [comment]
There is [already a test for this](https://github.com/LemmyNet/lemmy/blob/main/api_tests/src/post.spec.ts#L332), but it must be broken. Or the bug is only happening with comments, not posts.

**Comment by dessalines** [comment]
This is dependent on #1808 , and creating an instance actor.

**Comment by Nutomic** [comment]
This is implemented now.
