### ISSUE TITLE
Have user ban post and comment deletion also remove communities where they're the top mod.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1659]
Currently, when banning a user, and clicking yes on the option to remove posts and comments, doesn't delete the communities they've created. This means that admins manually have to remove those communities, which is an annoying extra clean up step.

**Comment by weex** [comment]
Isn't there a good possibility over time of top mods going rogue and earning a ban, yet their communities remaining valuable? Perhaps this can be limited to communities in which they're also the only poster.

**Comment by dessalines** [comment]
That could probably be handled by https://lemmy.ml/c/community_requests . Anyone can request any removed / banned communities.
