### ISSUE TITLE
Have plaintext URLs for federated communities and users.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1662]
Associated back end task for https://github.com/LemmyNet/lemmy-ui/issues/317 .

**Comment by dessalines** [comment]
Realized this will be a breaking change, as I'm getting rid of these for user and community:

```rust
pub struct GetCommunity {
  pub id: Option<CommunityId>, // Getting rid of this
  pub name: Option<String>, // Letting this be a federated name now, and non-optional: example: star_trek , or star_trek@xyz.tld
}
```

I'll do this but it might be good to push this to a later release. I wanna do a smaller release before any breaking changes.

**Comment by Nutomic** [comment]
What exactly is this issue about?
