### ISSUE TITLE
Mount pictrs to additional disk

### ISSUE THREAD

**Issue by military1** [LemmyNet/lemmy#1669]
Hello!
Thank you very much for such an interesting project.
How to move folder pictrs to additional disk? I use a docker version of lemmy. 
Is it enough to specify a new mount point in the config  - ./volumes/pictrs:/mnt ?
Please tell me how to do it right?

**Comment by Nutomic** [comment]
Yes, it should work fine if you replace the part `./volumes/pictrs` with an absolute path.
