### ISSUE TITLE
iframely_1 | standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by Jojonintendo** [LemmyNet/lemmy#1670]
### Issue Summary

After a successful Docker install on a Rock64 (Pine64 SBC), I can browser my instance but the iframely_1 container is constantly giving the same error:

```
lemmy_iframely_1 exited with code 1
iframely_1  | standard_init_linux.go:228: exec user process caused: exec format error
iframely_1  | standard_init_linux.go:228: exec user process caused: exec format error
iframely_1  | standard_init_linux.go:228: exec user process caused: exec format error
iframely_1  | standard_init_linux.go:228: exec user process caused: exec format error
iframely_1  | standard_init_linux.go:228: exec user process caused: exec format error
iframely_1  | standard_init_linux.go:228: exec user process caused: exec format error
```

### Steps to Reproduce

1. Follow Docker install steps at [https://join-lemmy.org/docs/en/administration/install_docker.html](https://join-lemmy.org/docs/en/administration/install_docker.html)
2. Browse your instance, which apparently works.
3. Watch the logs and see above error repeating constantly.

### Technical details

* Docker-compose logs attached.
* The OS is openSUSE Tumbleweed on Rock64.
* Federation is enabled, although even a default install without it gives the same error.

[lemmy_logs.txt](https://github.com/LemmyNet/lemmy/files/6858037/lemmy_logs.txt)

**Comment by Nutomic** [comment]
The problem is because there is no ARM image for iframely on Docker Hub (that I could find). https://github.com/LemmyNet/lemmy/issues/1369

**Comment by dessalines** [comment]
I'll also say we could really use an iframely alternative in rust, if anyone's looking for a project.
