### ISSUE TITLE
Don't allow the same user to necrobump their own thread.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1675]
[Context](https://lemmy.ml/post/75346)

Lemmy's `Active` sort allow threads to be bumped for activity by commenting on them (limited up to 2 days). This is fine and its the purpose of it, but the post creators themselves should not be able to bump their own threads. "Activity", here really means community engagement, so that means other people.

**Comment by Nutomic** [comment]
I understood the problem is that deleted comments are counted towards the total comment count. Imo they should be excluded.

**Comment by dessalines** [comment]
Ahh, that is a separate thing then. I can open up one for that too.
