### ISSUE TITLE
Replace Iframely with simple opengraph scraping.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1681]
We could scrape the `html` ourselves, and use an opengraph parser like this to get our embeds and thumbnails: https://github.com/kumabook/opengraph or https://crates.io/crates/webpage

I'm not sure how many sites it would work for, certainly not as many as iframely currently supports. But it'd be nice because we could have this all bundled within lemmy.

**Comment by justjosias** [comment]
Is using oEmbed an option? It's a bit more difficult to use (dealing with whitelists, etc.), and not nearly as nice (in my opinion), but it provides HTML embed information for rich HTML content and videos, like you currently are using.

**Comment by dessalines** [comment]
This isn't about lemmy serving up those things, iframely is for scraping other sites when people post links.

**Comment by justjosias** [comment]
I understand the purpose. I wasn't clear, sorry. I was referring to scraping in those comments, not serving.

**Comment by dessalines** [comment]
That's correct, but that's also where it gets complicated, and where most of the work of iframely is, because each site is going to have their own specific oembed URLs and response return types. It might be enough of a start to just do a few of the major ones. 

Ideally this should be its own crate, that can either do the fetching for you, or just manually take in a URL.

**Comment by dessalines** [comment]
I think for now, we're fine to just not use the embed html. The front end has expandable buttons / iframes for that, but it really isn't too necessary, its a security risk, and probably mostly unused. All I really care about is the title, description, and main image. The WebPage crate above should be able to handle all that nicely.
