### ISSUE TITLE
Use tokio-diesel crate for database calls

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1684]
https://github.com/mehcode/tokio-diesel

As far as i understand, this is functionally equivalent to the blocking wrapper we use now, but much less verbose at the callsite. So it would be nice if we could replace that. Rewriting manually would take a long time, so it needs some automated tooling.

**Comment by dessalines** [comment]
I'd really be in favor of that, but whichever of us does this, its worth it to test just one case, running in the server, before replacing them all. Because you're right, this is every DB call.

**Comment by Nutomic** [comment]
I'm still very busy with the apub rewrite, so i'd be glad if you could take care of it.

**Comment by dessalines** [comment]
I've got the setup for this done, now just a lot of tedious work over the hundreds of calls.

**Comment by dessalines** [comment]
We'll have to shelve this right now for two reasons:

- That crate is currently unmaintained, and its latest release doesn't work for current versions of tokio or diesel. There's a hack to specify the git version, but it hasn't had commits in a while.
- More importantly, it doesn't work for boxed diesel queries currently, which we absolutely need.

**Comment by Nutomic** [comment]
I see, that crate definitely needs to be forked. The code looks pretty short so it shouldn't be hard to maintain. We might also contact the diesel developers about it

**Comment by dessalines** [comment]
I'll ping weiznich in that thread.

**Comment by Nutomic** [comment]
What do you think of [this crate](https://github.com/djc/bb8)? From what I can tell it solves the same problem, and it is actively maintained.

**Comment by dessalines** [comment]
The deadpool one seems like a good possibility.
