### ISSUE TITLE
Censorship resistant?

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#1694]
Is it possible to have a community be censorship resistant by having multiple instances host a copy of the community. This way if instance alpha goes offline or decides to censor a community, post or comment other instances will still keep a copy of the community and its posts and comments preventing communities, posts and comments from being purged from the internet.

**Comment by Nutomic** [comment]
Content is already mirrored via federation, and will remain available if the original instance goes down. And by "censorship", I think you are referring to admins/moderators removing content that violates the rules, or users deleting their own posts? I dont think that can be considered as censorship, and it would violate their trust if other instances could easily ignore it.

**Comment by trymeouteh** [comment]
By censorship I do not mean content that violates any terms. On mainstream platforms today people get censored for posts that do not violate any terms and it is removed.

But your saying that weather an instance takes down a community, post or comment or if thr instance goes offline, other instances will have mirrored this content?

**Comment by Nutomic** [comment]
If an instance goes down then the content will still be available on other instances if it was federated before. But if a mod or admin removes something, it will also be removed on other instances. And admins/mods can remove whatever they want, we have the mod log to make that more transparent. If you dont like their removals, you need to switch instances.

**Comment by dessalines** [comment]
We will also try our best to federate deletions too. 

Also, lemmy is most definitely not intended to be "censorship resistant". We hope and expect community and instance moderators to be very vigilant about removing content against their rules.

**Comment by trymeouteh** [comment]
An admin on instanceA can take down a post or comment inside a community which will delete it from all instances? Is it possible to have an instance which will ignore any takedowns of a post its mirroring from any given instance if there is a censoring crazy instance and to only allow deletion from instances with trusted admins/mods?

**Comment by dessalines** [comment]
The content really should "live" on the instance it was created on, and the host admins and community mods should have final say on those representations everywhere, so that they match what exists on the host community. 

If someone on another instance wants to start their own community, they're free to do so.
