### ISSUE TITLE
Feature requeset: Change binary like/dislike to floats/ranges

### ISSUE THREAD

**Issue by LoveIsGrief** [LemmyNet/lemmy#1702]
### Is your proposal related to a problem?

After reading a few articles, I'm agreeing with some authors that one problem with social media is it presents and purports many of  our decisions as binary. In this case like and dislike (well, if you add "no opinion" then it's tertiary). We are however quite fluid and chaotic.

When we like/dislike stuff, we do so with different quantifications: somewhat, a little, greatly, vehemently, absolutely, "just dis|agree", etc.

### Describe the solution you'd like

It could start with just a slider for dis|agreement that goes from 0-100 and starts at 50. That should replace the up|down vote buttons.
However, the future goal would be to add more dimensions when voting on comments: relevance (slider: 0-100), tone (checkbox: kind, abrasive, factual, engage, angry, funny ...).

### Describe alternatives you've considered

 - Sliders from -1 to +1 and starts at 0
 - Sliders from -100 to +100 and starts at 0
 - 5 stars that start unset, shine when clicked upon, and unset when the same one is clicked/tapped upon again
 - sliders or stars for the different tones

### Additional context

**Expected Effects**
This would probably change the existing ranking algorithm. It could use the sum of all votes (maybe it already does), the median, the average, standard deviation, or whatever else you prefer.

An additional effect would be the ability to separate comments e.g jokes in a serious thread could be marked as less relevant but still be appreciated, a filter for comment length could be provided to filter out lengthy or short comments ("Like", "This!", et al), a reward system for kind, factual, thoughtful, funny, or whatever other tone users have most, probably more.

**Reading**

The relevant article I read today »[He predicted the dark side of the Internet 30 years ago. Why did no one listen?](https://archive.is/coxmb#selection-326.0-326.1)«

> [...] Agre wrote in the paper that the mass collection of data would change and simplify human behavior to make it easier to quantify. [...] social media and other online networks have corralled human interactions into easily quantifiable metrics, such as being friends or not, liking or not, a follower or someone who is followed.

A related article is »['Likes' and 'shares' teach people to express more outrage online](https://phys.org/news/2021-08-people-outrage-online.html)«

**Comment by Nutomic** [comment]
I think this would be way too complicated to implement, and also to complicated to understand. Maybe in the future it could be done in a custom Lemmy frontend, or in some kind of extension. By the way I wouldnt say that the choices on Lemmy are binary, if you want to express something different than like or dislike, you can do that in a comment (or upvote a comment which expresses your thought).

Leaving this open for discussion, but my answer is no.

**Comment by dessalines** [comment]
I'm a big fan of range voting / olympic score voting, and on one of my pet projects that was a precursor to this, flowchat, I did use sliders and a float 0-10 scale. reddit and lemmy use approval voting, which is a subset of range voting. Overall tho it was just more cumbersome and people didn't like it, voting took more clicks, and you had to *think* more about it, which lead to less votes. 

My [SimpleVote](https://simplevote.tk) also uses range voting, and is meant for specific questions, not link aggregations.

But ya I agree with @Nutomic , we likely won't change the voting algorithm, and just stick to the simple approval voting that everyone else uses.

**Comment by LoveIsGrief** [comment]
I didn't know about SimpleVote. It's bookmarked and will hopefully see some use.

IMO, forcing people to think a little about their choices isn't bad.

> Leaving this open for discussion, but my answer is no.

No as isn "**I** won't implement this" or "This is not a feature I'd accept even as a PR"?

**Comment by Nutomic** [comment]
The latter. Even if someone else made a PR for this, we are the ones who have to maintain it forever. Such complex code would definitely make our job harder.

**Comment by LoveIsGrief** [comment]
That's fair. Well, in that case, happy programming.

I hope the project becomes a nice reddit alternative.
