### ISSUE TITLE
lemmy on a lxc with caddy as reverse_proxy, federation problems

### ISSUE THREAD

**Issue by rototom** [LemmyNet/lemmy#1708]
I run caddy on a lxc with docker and nginx and it works beautifully so far.
Unfortunatly I can't use federation in this setup. How do I have to configure caddy (on the host machine) to reverse proxy the federation port(s)?
Thank you!

**Comment by dessalines** [comment]
We cannot do support for anything but nginx, but if anyone who knows caddy and can help, feel free.

**Comment by Nutomic** [comment]
Make sure that `curl -H 'Accept: application/activity+json' https://lemmy.ml/u/nutomic` gives you json and not html. Requests with that header should go to the backend, and not lemmy-ui. That should be the only thing thats required for federation to work.

**Comment by rototom** [comment]
I get:
  ` {"matrixUserId":null,"publicKey":{"id":"https://lemmy.ml/u/nutomic#main-key","owner":"https://lemmy.ml/u/nutomic","publicKeyPem":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0lP99/s5Vv+XbPdkeqIJ\nwoD4GFnHmBnBHdEKChEUWfWj1TtioC/rGNoXFQeXQA3Amhy4nxSceiDnUgwkkuQY\nv0MtIW58NzgknEavtllxL+LSds5pg3gANaDIk8UiWTkqXTg0GnlJMpCK1Chen0l/\nszL6DEvUyTSuS5ZYDXFgewF89Pe7U0S15V5U2Harv7AgJYDyxmUL0D1pGuUCRqcE\nl5MTHJjrXeNnH1w2g8aly8YlO/Cr0L51rFg/lBF23vni7ZLv8HbmWh6YpaAf1R8h\nE45zKR7OHqymdjzrg1ITBwovefpwMkVgnJ+Wdr4HPnFlBSkXPoZeM11+Z8L0anzA\nXwIDAQAB\n-----END PUBLIC KEY-----\n"},"inbox":"https://lemmy.ml/u/nutomic/inbox","outbox":"https://lemmy.ml/u/nutomic/outbox","preferredUsername":"nutomic","endpoints":{"sharedInbox":"https://lemmy.ml/inbox"},"source":{"mediaType":"text/markdown","content":"Lemmy maintainer. Interested in politics, video games, and many other things."},"content":"<p>Lemmy maintainer. Interested in politics, video games, and many other things.</p>\n","icon":{"type":"Image","url":"https://lemmy.ml/pictrs/image/ed9ej7.jpg"},"published":"2020-01-17T01:38:22.348392+00:00","updated":"2021-08-13T00:11:15.941990+00:00","@context":["https://www.w3.org/ns/activitystreams",{"matrixUserId":{"type":"sc:Text","id":"as:alsoKnownAs"},"stickied":"as:stickied","sensitive":"as:sensitive","moderators":"as:moderators","sc":"http://schema.org#","comments_enabled":{"type":"sc:Boolean","id":"pt:commentsEnabled"},"pt":"https://join-lemmy.org#"},"https://w3id.org/security/v1"],"id":"https://lemmy.ml/u/nutomic","type":"Person","mediaType":"text/html"}'''`
What is json, isn't it?

**Comment by Nutomic** [comment]
You need to replace the url with that of a user on your instance. Or simply post a link to your instance here.

**Comment by rototom** [comment]
Ok, so this: 
`curl -H 'Accept: application/activity+json' https://lemmy.okaris.de/u/thomas`

gives me exactly nothing in return when I run it from my desktop pc. lemmy.okaris.de is my instance.

**Comment by Nutomic** [comment]
Thats just as bad. The output should look similar to the one for my profile. For that you need to change the reverse proxy config, so that requests with that header are passed to the backend. You can check how our nginx config does it, but I have no clue how caddy works.

**Comment by rototom** [comment]
I use nginx on the lemmy lcx. I just wonder how to reroute the traffic from/to the host system.

**Comment by rototom** [comment]
I can't let lemmy community directly to the internet, because I only habe one machine at home.
