### ISSUE TITLE
https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/iframely.config.local.js not found

### ISSUE THREAD

**Issue by volanar** [LemmyNet/lemmy#1717]
An error occurs when installing via docker
https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/iframely.config.local.js not found, error 404

**Comment by dessalines** [comment]
Apologies, we're preparing to do a new release shortly, so our main branch is missing that file. You can run this to get our last release tag:

`git clone -b  0.11.3 https://github.com/LemmyNet/lemmy`

and then follow the guide as normal.
