### ISSUE TITLE
warning: invalid logging spec 'info"', ignoring it

### ISSUE THREAD

**Issue by loid345** [LemmyNet/lemmy#1719]
ubuntu 20,04
lemmy 0.11.3
install via docker.
I made a new installation.  An error occurs when entering the "sudo docker-compose logs" command
warning: invalid logging spec 'info"', ignoring it
The site is working. Does this warning affect the operation of the site or can it be ignored?

**Comment by dessalines** [comment]
Could you output more of the log?

**Comment by loid345** [comment]
I will wait for the platform update. If the warning does not disappear, I will output logs
