### ISSUE TITLE
error Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 12

### ISSUE THREAD

**Issue by loid345** [LemmyNet/lemmy#1720]
ubuntu 20.04
UI: 0.11.4-rc.1
BE: 0.11.3
install via docker compose
When inserting an any external link into a post, an error occurs
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 12
![2021-08-23_02-24-16](https://user-images.githubusercontent.com/20200970/130373337-6abbe273-7a69-4582-8dfd-769632a382ec.png)

**Comment by loid345** [comment]
I found an error
https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/lemmy.hjson
# the domain name of your instance (eg "lemmy.ml")
  hostname: "my_domain" -   remove the quotation marks

# the domain name of your instance (eg lemmy.ml)
  hostname: my_domain

**Comment by loid345** [comment]
iframely is not in nginx

**Comment by dessalines** [comment]
We're also getting ready to deploy lemmy with iframely completely removed in a week or two.
