### ISSUE TITLE
iframely.config.local.js error 404

### ISSUE THREAD

**Issue by altilunium** [LemmyNet/lemmy#1721]
https://join-lemmy.org/docs/en/administration/install_docker.html
![image](https://user-images.githubusercontent.com/70379302/130403935-03a09b5f-0824-44bb-a030-57ee07ecfbc0.png)

![image](https://user-images.githubusercontent.com/70379302/130403902-da330bfc-99c5-4285-90f1-b41b739b4618.png)

**Comment by dessalines** [comment]
Also dupe of #1717

**Comment by Nutomic** [comment]
Lets leave this open in case more users run into it (until the new version is out).

**Comment by dessalines** [comment]
This is out now.
