### ISSUE TITLE
Image uploads are currently broken on the federation test instances.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1725]
When uploading any image on ds9.lemmy.ml ( which has the new rc's ), we get this error:

```
pictrs_1    | Aug 24 00:19:37.451  INFO request{uuid=03f312a8-bb94-44ec-ad9a-004072a0e522}:upload: pict_rs: Uploaded Emma-Goldman.jpg as "h
IiTifuULr.jpg"
pictrs_1    | Aug 24 00:19:37.453  INFO actix_web::middleware::logger: 172.25.0.3:43682 "POST /image HTTP/1.1" 201 74 "https://ds9.lemmy.ml
/settings" "pict-rs-frontend, v0.1.0" 0.035824
lemmy_1     | [2021-08-24T00:19:37Z DEBUG actix_web::middleware::logger] Error in response: Deserialize(Error("expected value", line: 1, co
lumn: 1))
lemmy_1     | [2021-08-24T00:19:37Z INFO  actix_web::middleware::logger] 172.25.0.1:52044 "POST /pictrs/image HTTP/1.1" 400 57 "https://ds9
.lemmy.ml/settings" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0" 0.042575
pictrs_1    | Aug 24 00:20:23.442  INFO request{uuid=d67c0ad2-b0e1-406b-ad9c-c577c9d0aaa9}:upload: pict_rs: Uploaded Emma-Goldman.jpg as "y
3K9od7QTt.jpg"
pictrs_1    | Aug 24 00:20:23.447  INFO actix_web::middleware::logger: 172.25.0.3:43710 "POST /image HTTP/1.1" 201 76 "https://ds9.lemmy.ml
/settings" "pict-rs-frontend, v0.1.0" 0.041803
lemmy_1     | [2021-08-24T00:20:23Z DEBUG actix_web::middleware::logger] Error in response: Deserialize(Error("expected value", line: 1, co
lumn: 1))
```

The image actually uploaded fine if you go to that pictrs URL, but the response still fails.

This might be the issue:

https://git.asonix.dog/asonix/pict-rs/src/tag/v0.2.6-r2#api

which should just return {msg, files: {delete_code, file: FILENAME_ONLY}

whereas we have:

```
#[derive(Debug, Serialize, Deserialize)]
struct Images {
  msg: String,
  files: Option<Vec<Image>>,
}
```

Problem is it seems like image uploading would be broken currently, because we are currently using that same version of pictrs on our prod servers..

**Comment by Nutomic** [comment]
So this is a problem in Lemmy, and we need to change the Image struct? Did pictrs change anything?

cc @asonix

**Comment by dessalines** [comment]
That's what's strange, it doesn't seem like pictrs changed anything, so I have no idea why its currently working.

**Comment by Nutomic** [comment]
Same pictrs docker image running in prod and test?

**Comment by dessalines** [comment]
Yup.

- prod: `asonix/pictrs:v0.2.6-r2           lemmyml_pictrs_1`
- test: `asonix/pictrs:v0.2.6-r2 ds9lemmyml_pictrs_1`

**Comment by dessalines** [comment]
I thought of one possibility. The front end code has:

```ts
    fetch(pictrsUri, {
      method: "POST",
      body: formData,
    })
      .then(res => res.json())
      .then(res => {
        console.log("pictrs upload:");
        console.log(res);
        if (res.msg == "ok") {
          let hash = res.files[0].file;
          let url = `${pictrsUri}/${hash}`;
          i.state.loading = false;
          i.setState(i.state);
          i.props.onUpload(url);
        } else {
```

So the front end code is using `files.file` as a string, which matches pictrs exactly. Maybe our current nginx is referencing pictrs directly, not our passthrough.

**Comment by Nutomic** [comment]
The nginx config only uses variables `lemmy_port` and `lemmy_ui_port`. Also both of those servers are deployed from the same ansible playbook which uses the same nginx config.

From the error log i'm not sure which line exactly is throwing the error, so its probably worth narrowing that down. Would be nice to have stack traces tbh. The relevant frontend code hasnt changed since 0.11.3?

**Comment by asonix** [comment]
Nothing has changed in that pict-rs code in a while. All my recent effort has been around 0.3.0. I can't think of a reason the same container would respond with properly formatted json in one environment and improper json in another

**Comment by dessalines** [comment]
This was a combination of 2 issues, neither to do with pictrs or our code:

- `awc 3.0.0-beta.7` the `.json()` function is broken.
- That same version requires the default features to be able to handle gzip content. Without it, this failed.
