### ISSUE TITLE
Integration with Plausible Analytics

### ISSUE THREAD

**Issue by loid345** [LemmyNet/lemmy#1727]
Plausible Analytics (AGPL-3.0) fits perfectly with the open source philosophy and requires few resources. 
https://github.com/plausible/analytics
It would be great to add a setting for its interation. If this is not possible, can you tell me where to insert the integration code?

**Comment by dessalines** [comment]
If you want to add a custom html header, that's easy to do: https://github.com/LemmyNet/lemmy-ui

Use the `LEMMY_UI_CUSTOM_HTML_HEADER` env var.
