### ISSUE TITLE
Pin docker dependencies in Dockerfiles to stable generics.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1730]
Go through all the Dockerfiles and docker-compose.yml 's, and change to more generic images, so as not to have to constantly update or keep track of security changes.

Example for [alpine](https://hub.docker.com/_/alpine): change `3.14` to `3`

**Comment by Nutomic** [comment]
Dupe of https://github.com/LemmyNet/lemmy/issues/1759
