### ISSUE TITLE
Change community filtering from "Name" to "Display Name"

### ISSUE THREAD

**Issue by loid345** [LemmyNet/lemmy#1742]
The "name" is actually a url address and does not allow writing in Cyrillic and other letters other than Latin. If the platform is in Cyrillic, it is very difficult to understand the names of the community. I suggest replacing the filtering of communities not by "Name", but by "Display Name". 
Can the "Name" be changed to "URL"?

**Comment by dessalines** [comment]
The rationale here is that community names are unique, display names are not. And the name is used in the URL, not the display name.

**Comment by dessalines** [comment]
The filtering already searches using either the person name or display name.
