### ISSUE TITLE
ansible setup does not work

### ISSUE THREAD

**Issue by richardARPANET** [LemmyNet/lemmy#1743]
I followed these instructions https://join-lemmy.org/docs/en/administration/install_ansible.html

The result is that the default 'Welcome to Nginx' web page is served at the domain name in my configuration.

How do I fix this issue?

**Comment by richardARPANET** [comment]
Looks like it's something todo with cloudflare proxy being enabled.. when I run the install with that turned off it seems to work.

**Comment by richardARPANET** [comment]
Re-enabling cloudflare post-installation breaks everything again

**Comment by dessalines** [comment]
We don't use and can't help troubleshoot cloudflare-related issues.
