### ISSUE TITLE
SMTP error

### ISSUE THREAD

**Issue by loid345** [LemmyNet/lemmy#1744]
Lemy 0.11.3
Ubuntu 20.04
Install via docker

I tried to build smtp with several providers. Everything works on other sites, an error occurs on the lemmy server when sending an email in the logs:
 thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/utils/src/email.rs:29:7

My settings lemmy hjson:
  email: {
    smtp_server: "smtp.mailgun.org"
    smtp_login: "postmaster@sandboxe***.mailgun.org"
    smtp_password: "20*****77e6"
    smtp_from_address: "postmaster@sandboxe***.mailgun.org"
    use_tls: true
  }

**Comment by dessalines** [comment]
Are you sure the username includes an @ like that?

**Comment by loid345** [comment]
> Вы уверены, что в имени пользователя есть такой символ @?

**Comment by loid345** [comment]
> > Вы уверены, что в имени пользователя есть такой символ @?

Yes, full name is required. I have checked on other sites. The full name is not indicated, for example, for regular email Gmail, yandex, etc.

**Comment by Nutomic** [comment]
The error comes from [this line](https://github.com/LemmyNet/lemmy/blob/0.11.3/crates/utils/src/email.rs#L29), so it seems you need to specify a port for smtp_server. We should probably use a default port if that isnt supplied, or at least throw a better error (that expect message would only be shown if port is not a number).

**Comment by loid345** [comment]
> The error comes from [this line](https://github.com/LemmyNet/lemmy/blob/0.11.3/crates/utils/src/email.rs#L29), so it seems you need to specify a port for smtp_server. We should probably use a default port if that isnt supplied, or at least throw a better error (that expect message would only be shown if port is not a number).

Thanks for the answer. Tell me which Smtp provider is guaranteed to work with lemmy with default settings?

**Comment by Nutomic** [comment]
SMTP is included in the docker-compose file and should work automatically. Your existing smtp server should also work, you just need to specify the port.
