### ISSUE TITLE
Upload images to folders by upload date

### ISSUE THREAD

**Issue by loid345** [LemmyNet/lemmy#1746]
The images are now being saved to a shared folder. Big performance problems are bound to arise in the future. You must upload files to folders by upload date (for example, current year - current month - current date). The more scalable the platform, the deeper the folder structure. This is a standard mechanism and is used in CMS and various web applications (for example, WordPress, drupal, IPS, XenForo, etc.)
![WordPress-media-folder-organization-structure-Crunchify](https://user-images.githubusercontent.com/20200970/131466042-70edd9d1-b019-4324-bf2a-08a435639544.png)

**Comment by Nutomic** [comment]
This is a good point, but image storage is handled by [pictrs](https://git.asonix.dog/asonix/pict-rs/). 

cc @asonix

**Comment by asonix** [comment]
This, or something similar, is something I definitely want to do in pict-rs in the future. It's not a top priority right now for 0.3, but maybe for 0.4 I can get something implemented

**Comment by asonix** [comment]
I've actually put pictures into Sled before in a previous application, and although it was very small-scale I can imagine that working pretty well. Maybe I'll play around with that idea. Again, not until 0.4, but 0.3 is nearing completion already :)

**Comment by dessalines** [comment]
pictrs-related.
