### ISSUE TITLE
Add TLS 1.3

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1750]
https://git.radicallyopensecurity.com/nlnet/off-ngid-lemmy/-/issues/9

**Comment by EchedeyLR** [comment]
That link cannot be checked without login in.

**Comment by dessalines** [comment]
None of those links can, these are placeholders for a security audit from https://www.radicallyopensecurity.com/ we recently had.

**Comment by Nutomic** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=ds9.lemmy.ml&hideResults=on&latest still gives A+ so I dont think this is important.
