### ISSUE TITLE
Add HSTS headers on some resources.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1752]
The [HTTP Strict Transport Security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) headers are not present on every served resource.

Observed paths without the correct headers:
* `/api/v3/ws`
* various `/pictrs/image/*` paths

Depending a number of preconditions, this may be beneficial to an attacker during man-in-the-middle (MitM) network attacks against clients that visit a Lemmy site. Practical security impact is likely limited, for example since other resources do carry the correct header and users will be protected after the first correctly marked resource download.

Make sure to set proper HTTP Strict-Transport-Security headers for all web resources.

https://git.radicallyopensecurity.com/nlnet/off-ngid-lemmy/-/issues/11

**Comment by Nutomic** [comment]
Lemmy doesnt send these headers, they are part of nginx config. Closing this as out of scope.
