### ISSUE TITLE
Ansible password differences

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1760]
https://git.radicallyopensecurity.com/nlnet/off-ngid-lemmy/-/issues/31

**Comment by Nutomic** [comment]
I figured it out. These tasks are in a `block`, so the vars from the bottom apply to all tasks in the block. So it is correct, but confusing like that thanks to significant whitespace in yml.

[start of block](https://github.com/LemmyNet/lemmy/blob/f6f169b4eb7542825cf17712b474b6a6ab71cb64/ansible/lemmy.yml#L62)
[vars belonging to block](https://github.com/LemmyNet/lemmy/blob/f6f169b4eb7542825cf17712b474b6a6ab71cb64/ansible/lemmy.yml#L90)
