### ISSUE TITLE
Allow non-Latin characters as usernames and community names

### ISSUE THREAD

**Issue by gary-host-laptop** [LemmyNet/lemmy#1764]
The internet is pretty anglocentric, URLs don't allow non-Latin characters to begin with but I think you can display them within your browser, or at least within the website. 

### Describe the solution you'd like

Supporting non-Latin characters would be really awesome to help make the net a more open space.

### Describe alternatives you've considered

N/A

### Additional context

Things should be considered to prevent security threats, for example the use of different but very similar characters in phisin attempts and stuff like that. Maybe allowing only one language per instance?

**Comment by LongJohn-Silver** [comment]
Yeah, and ultimately it is not like you can achieve much, the most relevant part if one would want to  make some phisin is the instance's name, i dont think one can steal much with a similar username or community.

**Comment by dessalines** [comment]
I'd like a lot more discussion around this, esp by devs who have some expertise in non-latin characters. The concerns:

- More international support.
- Browser support for non-latin URLs. Remember that user and community names **are the URLs**, and display name currently can have any characters or spaces.
- Duplicate user / community name attacks.
- Complication by potentially adding specific alphabets to DB, and URLs.
