### ISSUE TITLE
Instance not federating 

### ISSUE THREAD

**Issue by pixlguru** [LemmyNet/lemmy#1780]
### Issue Summary

instance is not receiving content updates from federation  

### Steps to Reproduce

e.g.  community linux community on lemmy.ml:
https://lemmy.ml/c/linux 
vs federated:
https://sopuli.xyz/c/linux@lemmy.ml 
or 
https://feddit.de/c/linux@lemmy.ml

**Comment by dessalines** [comment]
Verified.

I see that we implemented open federation 9 days ago, but updates seemed to stop after 4 days? This is strange. 

Its not limited to a few communities either... asklemmy is also not federating: 
- https://sopuli.xyz/c/asklemmy@lemmy.ml
- https://lemmy.ml/c/asklemmy

**Comment by dessalines** [comment]
I'm not exactly sure why, but a simple restart seemed to fix it: 

- https://sopuli.xyz/post/16842/comment/46411
- https://feddit.de/post/1079/comment/3281

**Comment by dessalines** [comment]
From what we can tell from the logs, it seems lemmy.ml was receiving every new activity fine for the past 4 days, but wasn't sending them. `background_jobs` lacked any log entries for the past 4 days, until we restarted it today.

@asonix is there a possible way that we could check / restart our background jobs queue if it fails or crashes? I'm not exactly sure what caused the crash, because I don't have logs that far back.

**Comment by asonix** [comment]
I think the library needs more work to be able to recover from crashes like that. I'll see what I can do this evening

**Comment by kromonos** [comment]
Unfortunately, the problem occurs with me as well. Often the topics themselves are transferred to my instance, but comments and ratings often fail to appear.

Example:
On lemmy.ml: https://lemmy.ml/post/82517
Same on my instance: https://fapsi.be/post/1836

**Comment by dessalines** [comment]
@kromonos Our background jobs still seem to be working, could you post your `config.hjson`?

**Comment by kromonos** [comment]
Server already restarted several times. I tried now with recreating all the container.

```
{
  hostname: "fapsi.be"
  bind: "0.0.0.0"
  port: 8536
  jwt_secret: "abc123"
  pictrs_url: "http://pictrs:8080"
  actor_name_max_length: 32

  database: {
    database: "lemmy"
    user: "lemmy"
    password: "password"
    host: "postgres"
    port: 5432
    pool_size: 5
  }

  rate_limit: {
    message: 180
    message_per_second: 60
    post: 6
    post_per_second: 600
    register: 3
    register_per_second: 3600
    image: 6
    image_per_second: 3600
  }

  federation: {
    enabled: true
    #allowed_instances: [  ]
    #blocked_instances: [  ]
    #strict_allowlist: false
  }

  captcha: {
    enabled: true
    difficulty: medium # Can be easy, medium, or hard
  }

  email: {
    smtp_server: "abc123"
    smtp_login: "abc123"
    smtp_password: "abc123"
    smtp_from_address: "abc123"
    use_tls: true
  }
}
```

**Comment by dessalines** [comment]
Considering you're getting recent comments from other instances: https://fapsi.be/home/data_type/Comment/listing_type/All/sort/Active/page/1

My only guess is that someone from your instance needs to resubscribe there to pick up new updates.
