### ISSUE TITLE
Add a `description` field to community.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#1783]
Communities would then have: name, title, description, and sidebar.

Discussion: https://github.com/LemmyNet/lemmy-ui/issues/385

**Comment by Nutomic** [comment]
I wonder how we can federate this. At the moment we are using the `summary` field to federate the sidebar, but I dont see anything that could be used to federate the new short description. We might need a new field.

**Comment by dessalines** [comment]
Looks like we are using content for the current sidebar: https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/objects/community.rs#L135

So we could use summary still.
