### ISSUE TITLE
Tombstone/link communities

### ISSUE THREAD

**Issue by heylix** [LemmyNet/lemmy#1789]
would be nice if you could "tombstone" communities so they redirect to the canonical version similar to the [Matrix.org spec's m.room.tombstone event](https://matrix.org/docs/spec/client_server/latest#m-room-tombstone).

E.g. closing !community@lemmy.ml and redirecting to !community@lemmygrad.ml when you're moderator of both communities.

Similarly you might want to link communities so they appear as a local community in the interface, but technically are federated.

**Comment by Nutomic** [comment]
I think this could lead to problems if people create communities for the sole purpose of redirecting to their own community (or their own instance). Making a remote community appear as local would also make things more complicated, especially for new users. 

Even if we ignore these potential problems, I dont really think it would be a useful feature.

**Comment by boehs** [comment]
I think the best implementation here is to make it only for community admins

**Comment by Nutomic** [comment]
[Unbound Actor](https://socialhub.activitypub.rocks/t/fep-8485-unbound-actor/2200) looks like a better solution for this.
