### ISSUE TITLE
Remove site.creator_id

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1808]
We have already removed creator_id from community, and I think we should also remove it from site. The problem is that it forces me to federate that field, but I would prefer to work on other things before federating the instance admin list (thats very low priority imo). 

Related to #1798.

**Comment by dessalines** [comment]
Its basically the same as this PR removing community creator: https://github.com/LemmyNet/lemmy/pull/1541

**Comment by Tmpod** [comment]
Gotchu, will probably take a look at this today.

**Comment by dessalines** [comment]
Correct, the main admin is the oldest or first id one.

**Comment by Nutomic** [comment]
I dont think the admin hierarchy works correctly now. Basically admins are supposed to be sorted by the time they gained admin status, but in fact they are simply sorted by user id. So if two users are made admin, the one that registered earlier will be listed earlier in the admin list, regardless of the time they became admin. The solution separate `admins` table which stores them in the correct order.

**Comment by dessalines** [comment]
I'll try to make this a priority within the next few weeks.
