### ISSUE TITLE
Unable to start Lemmy using docker-compose: Permission denied (os error 13)

### ISSUE THREAD

**Issue by alexbouchard123** [LemmyNet/lemmy#1811]
I'm unable to start Lemmy using docker-compose:

```
2021-10-02T14:48:26Z INFO  lemmy_server::scheduled_tasks] Reindexing table  post_aggregates ...
Error: LemmyError { inner: Permission denied (os error 13) }
warning: invalid logging spec 'info"', ignoring it
```

I did try : `docker-compose exec postgres psql -d lemmy -U MY_USER -c "reindex table post_aggregates; reindex table comment_aggregates; reindex table community_aggregates;"`
then `docker-compose restart`

I also `chmod 777` the `volumes` folder, in order to try to make it work.

And it still doesn't work.

I'm able to connect to the Postgres database  using local `psql`.

Any idea?

**Comment by dessalines** [comment]
In searching for your error, my best guess is that you've misconfigured some permissions for your docker install, and are probably running either windows linux subsystem or mac osx.  What's your docker version, docker-compose version, and system you're running docker on?

https://github.com/rust-lang/cargo/issues/6757

https://stackoverflow.com/questions/56784492/docker-compose-permissionerror-errno-13-permission-denied-manage-py

**Comment by alexbouchard123** [comment]
I'm running on a plain CentOS 7.5 VPS. Docker is at the very latest version ( `yum install docker docker-compose docker.io`, from scratch).

**Comment by alexbouchard123** [comment]
Wow, I found it. Thanks to https://stackoverflow.com/a/49492644 .

By running `sudo setenforce Permissive`, it did work.
