### ISSUE TITLE
Comment notifications are not marked as read when replied to

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy#1812]
### Issue Summary

When a comment is replied to from the notification page, it is not marked as read, and instead has to be manually checked.

### Steps to Reproduce

1. Go to your notifications page and unmark an old notif if you don't have new ones.
2. Reply to it

### Technical details
N/A

### GIF

![Peek 2021-10-02 13-03](https://user-images.githubusercontent.com/35771816/135715307-4d542e7c-b094-4c5a-acee-7171df5eae98.gif)

**Comment by dessalines** [comment]
This is done.
