### ISSUE TITLE
Fetch a remote post when searching for an exact post url. Even if community was never subscribed to.

### ISSUE THREAD

**Issue by Houkime** [LemmyNet/lemmy#1845]
### Is your proposal related to a problem?

Yes. On a small instance like https://fapsi.be a lot of remote communities have zero local subscribers.
Even if one subscribes to a community, the older posts won't  be fetched and thus one **cannot write a reply to such a post**.

This renders a lot of Lemmy posts (probably even the majority of them) non-interactable from small instances.
I think with time this will get worse - with even newer servers that were not there to begin with when the majority of posts on Lemmy were made people will be crippled and inclined to use larger servers, which is the opposite of lemmy's federation goals.

I skimmed through the [lemmy protocol](https://join-lemmy.org/docs/en/federation/lemmy_protocol.html) and it seems like the problem is not with the ui, but with Lemmy federation mech itself. It is possible to post a comment to a post, but it is not possible to request the body of a post (at least without scraping?) to present it to the user.

### Describe the solution you'd like
Fetch any post, even a post not received as a part of any subscription, when searching for the post's url in the Lemmy search bar.
This way if one discovers a post one wants to interact with, one can always do that (unless one's server or a target server are explicitly banned at least)
On the protocol level it probably amounts to ability to request post's body from another instance.

### Describe alternatives you've considered
Fetch all of the older posts when subscribing to community.
That could be uneconomic and is just more complex overall.
Post url contains all the info needed and fetching using the url feels like a minimal-effort approach.

**Comment by Houkime** [comment]
There is GetPost in the API https://join-lemmy.org/api/interfaces/GetPost.html but can it be employed server-to-server with this auth used?

**Comment by dessalines** [comment]
> Fetch any post, even a post not received as a part of any subscription, when searching for the post's url in the Lemmy search bar.

It works exactly like this already.

**Comment by Houkime** [comment]
i will try to replicate this on lemmy ml with some rare remote unsubscribed communities.

**Comment by Houkime** [comment]
In fact, https://lemmy.ml/post/82214 is not currently searchable from lemmy.ml itself

**Comment by Nutomic** [comment]
Another thing is about fetching posts in a community. Lemmy is supposed to fetch the last 20 posts in a remote community when it is fetched for the first time (currently broken, https://github.com/LemmyNet/lemmy/issues/1582). Something similar could be done to fetch the comments in a post when the post is fetched. The problem is with scaling, as fetching a community could trigger hundreds of http requests to fetch posts and comments.
