### ISSUE TITLE
Connecting to database doesn't work

### ISSUE THREAD

**Issue by Rynach** [LemmyNet/lemmy#1847]
### Issue Summary

I'm trying to get Lemmy running on my server after reinstalling it with Ansible. Nginx is giving a 502 error message so I can't access my instance.

The command _docker-compose logs_ is giving the following error messages that are related to the Docker containers _lemmy_ and _lemmy-ui_. The images seem to restart after a short amount of time because of the errors. The containers for _postgres_, _pictrs_ and _postfix-relay_ seem to run fine. 

``
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | httpbase: https://lemmy:8536
lemmy-ui_1  | wsUri: wss://lemmy:8536/api/v3/ws
lemmy-ui_1  | isHttps: true
lemmy-ui_1  | No JWT cookie found.
lemmy-ui_1  | http://0.0.0.0:1234
lemmy-ui_1  |
lemmy-ui_1  | /app/node_modules/node-fetch/lib/index.js:1461
lemmy-ui_1  |                   reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
lemmy-ui_1  |                          ^
lemmy-ui_1  | FetchError: request to http://lemmy:8536/api/v3/site?auth=AUTHKEY>
lemmy-ui_1  |     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
lemmy-ui_1  |     at ClientRequest.emit (node:events:390:28)
lemmy-ui_1  |     at Socket.socketErrorListener (node:_http_client:447:9)
lemmy-ui_1  |     at Socket.emit (node:events:390:28)
lemmy-ui_1  |     at emitErrorNT (node:internal/streams/destroy:157:8)
lemmy-ui_1  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
lemmy-ui_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
lemmy-ui_1  |   type: 'system',
lemmy-ui_1  |   errno: 'ECONNREFUSED',
lemmy-ui_1  |   code: 'ECONNREFUSED'
lemmy-ui_1  | }``

`` lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | httpbase: https://lemmy:8536
lemmy-ui_1  | wsUri: wss://lemmy:8536/api/v3/ws
lemmy-ui_1  | isHttps: true
lemmy-ui_1  | No JWT cookie found.
lemmy-ui_1  | http://0.0.0.0:1234
lemmy-ui_1  |
lemmy-ui_1  | /app/node_modules/node-fetch/lib/index.js:1461
lemmy-ui_1  |                   reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
lemmy-ui_1  |                          ^
lemmy-ui_1  | FetchError: request to http://lemmy:8536/api/v3/site? failed, reason: connect ECONNREFUSED 172.19.0.5:8536
lemmy-ui_1  |     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
lemmy-ui_1  |     at ClientRequest.emit (node:events:390:28)
lemmy-ui_1  |     at Socket.socketErrorListener (node:_http_client:447:9)
lemmy-ui_1  |     at Socket.emit (node:events:390:28)
lemmy-ui_1  |     at emitErrorNT (node:internal/streams/destroy:157:8)
lemmy-ui_1  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
lemmy-ui_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
lemmy-ui_1  |   type: 'system',
lemmy-ui_1  |   errno: 'ECONNREFUSED',
lemmy-ui_1  |   code: 'ECONNREFUSED'
lemmy-ui_1  | } ``

``lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:DB_PASSWORD@localhost:5432/lemmy', src/main.rs:45:25
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``

Even though I added the new generated database password to _config.json_ from _docker-compose.yml_, connecting to the database doesn't work. When database connection doesn't work, Inferno seems to crash too.

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
* What OS are you trying to install lemmy on? 
Ubuntu 20.04.2 LTS
* Any browser console errors?
None

**Comment by dessalines** [comment]
`'Error connecting to postgres://lemmy:DB_PASSWORD@localhost:5432/lemmy'`

Are you migrating an existing install? If so I put instructions down for that: https://github.com/LemmyNet/lemmy-ansible#migrating-your-existing-install-to-use-this-deploy

Post your docker-compose file, because the lemmy back end still can't talk to your database. Is anything currently running on that machine, because if so you need to stop those processes.

**Comment by Rynach** [comment]
`docker ps` shows the containers _lemmy_, _lemmy-ui_, _postfix-relay_, _pictrs_ and _postgres_ running.
I have the _passwords_ file with just the password.
Here's the docker-compose file:
---------

version: '2.2'

services:
  lemmy:
    image: dessalines/lemmy:0.13.1
    ports:
      - "127.0.0.1:8536:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lem>
    volumes:
      - ./lemmy.hjson:/config/config.hjson:ro
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.13.1
    ports:
      - "127.0.0.1:1235:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=sopuli.xyz
      - LEMMY_HTTPS=true
    depends_on:
      - lemmy

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=uVEjDK3VSTSCnoolMNkz
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:v0.2.6-r2
    user: 991:991
    ports:
      - "127.0.0.1:8537:8080"
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 200m

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=sopuli.xyz
    restart: "always"

------------

**Comment by Rynach** [comment]
Okay, the password and username are set the same in _lemmy.hjson_ and other config files, I also altered the user _lemmy_'s password with the _alter user_ command. After stopping all the Docker containers, I deleted the _volumes_ folder again, ran ansible-playbook and then restored the database from a backup. Connecting to the database still doesn't work but the restored data is still intact. The same error messages with _lemmy_ and _lemmy-ui_ still appear, I attached the log output of _postgres_1_ here. 
[postgres.log](https://github.com/LemmyNet/lemmy/files/7476672/postgres.log)
.

**Comment by dessalines** [comment]
You need to alter your password **after** the DB restore.

**Comment by Rynach** [comment]
I have altered the password and a text "ALTER ROLE" appears. However the same errors with _lemmy_ and _lemmy-ui_ still appear.

**Comment by dessalines** [comment]
So the error is still `lemmy_1 | thread 'main' panicked at 'Error connecting to postgres://lemmy:DB_PASSWORD@localhost:5432/lemmy', src/main.rs:45:25` ?

**Comment by Rynach** [comment]
>So the error is still lemmy_1 | thread 'main' panicked at 'Error connecting to postgres://lemmy:DB_PASSWORD@localhost:5432/lemmy', src/main.rs:45:25 ?

Yes, and _lemmy-ui_ is stil giving the same Inferno ECONNREFUSED thing.

**Comment by dessalines** [comment]
Then your error is still the exact same as it has been before, your config is using the wrong user and / or password. 

Did you try setting up a fresh install and connecting to it before doing a restore?

**Comment by jonathonf** [comment]
I appear to have hit the same thing when trying to [migrate to `lemmy-ansible`](https://github.com/LemmyNet/lemmy-ansible#migrating-your-existing-install-to-use-this-deploy). In my case, after finding this issue I have verified the password is correct in as many places as I can find it, as well as dumping, clearing, and restoring the database, but the root cause seems to be that the postgresql container isn't exposing a port:

```
# docker ps -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS              PORTS                       NAMES
f439e559b46b   dessalines/lemmy-ui:0.14.1   "docker-entrypoint.s…"   22 minutes ago   Up 22 minutes       127.0.0.1:25879->1234/tcp   lemmy_lemmy-ui_1
7dbf7427bdb6   dessalines/lemmy:0.14.1      "/app/lemmy"             22 minutes ago   Up 16 seconds       127.0.0.1:22295->8536/tcp   lemmy_lemmy_1
32f4c52e7020   asonix/pictrs:v0.2.6-r2      "/usr/bin/tini -- /u…"   22 minutes ago   Up 22 minutes       127.0.0.1:20500->8080/tcp   lemmy_pictrs_1
442a78de4b4b   mwader/postfix-relay         "/root/run"              2 hours ago      Up 2 hours          25/tcp                      lemmy_postfix_1
a488ab8eb090   postgres:12-alpine           "docker-entrypoint.s…"   2 hours ago      Up About a minute   5432/tcp                    lemmy_postgres_1
```

```
# ss -lntp
State     Recv-Q    Send-Q         Local Address:Port          Peer Address:Port    Process                                                                                                                                 
LISTEN    0         511                  0.0.0.0:80                 0.0.0.0:*        users:(("nginx",pid=44241,fd=6),("nginx",pid=44240,fd=6),("nginx",pid=44239,fd=6),("nginx",pid=44238,fd=6),("nginx",pid=1422,fd=6))
LISTEN    0         4096               127.0.0.1:20500              0.0.0.0:*        users:(("docker-proxy",pid=43822,fd=4))
LISTEN    0         4096               127.0.0.1:22295              0.0.0.0:*        users:(("docker-proxy",pid=50207,fd=4))
LISTEN    0         4096               127.0.0.1:25879              0.0.0.0:*        users:(("docker-proxy",pid=44131,fd=4))
LISTEN    0         4096               127.0.0.1:36855              0.0.0.0:*        users:(("containerd",pid=1023,fd=13))
LISTEN    0         20                 127.0.0.1:25                 0.0.0.0:*        users:(("exim4",pid=1445,fd=4))
LISTEN    0         511                  0.0.0.0:443                0.0.0.0:*        users:(("nginx",pid=44241,fd=8),("nginx",pid=44240,fd=8),("nginx",pid=44239,fd=8),("nginx",pid=44238,fd=8),("nginx",pid=1422,fd=8))
LISTEN    0         5                    0.0.0.0:44321              0.0.0.0:*        users:(("pmcd",pid=1432,fd=0))
LISTEN    0         128                  0.0.0.0:44322              0.0.0.0:*        users:(("pmproxy",pid=1499,fd=15))
LISTEN    0         128                  0.0.0.0:44323              0.0.0.0:*        users:(("pmproxy",pid=1499,fd=17))
LISTEN    0         128                  0.0.0.0:422                0.0.0.0:*        users:(("sshd",pid=1031,fd=3))
LISTEN    0         5                    0.0.0.0:4330               0.0.0.0:*        users:(("pmlogger",pid=2072,fd=7))
LISTEN    0         511                     [::]:80                    [::]:*        users:(("nginx",pid=44241,fd=7),("nginx",pid=44240,fd=7),("nginx",pid=44239,fd=7),("nginx",pid=44238,fd=7),("nginx",pid=1422,fd=7))
LISTEN    0         20                     [::1]:25                    [::]:*        users:(("exim4",pid=1445,fd=5))
LISTEN    0         511                     [::]:443                   [::]:*        users:(("nginx",pid=44241,fd=9),("nginx",pid=44240,fd=9),("nginx",pid=44239,fd=9),("nginx",pid=44238,fd=9),("nginx",pid=1422,fd=9))
LISTEN    0         5                       [::]:44321                 [::]:*        users:(("pmcd",pid=1432,fd=3))
LISTEN    0         128                     [::]:44322                 [::]:*        users:(("pmproxy",pid=1499,fd=16))
LISTEN    0         4096                       *:9090                     *:*        users:(("systemd",pid=1,fd=60))
LISTEN    0         128                     [::]:44323                 [::]:*        users:(("pmproxy",pid=1499,fd=18))
LISTEN    0         128                     [::]:22                   [::]:*        users:(("sshd",pid=1031,fd=4))
LISTEN    0         5                       [::]:4330                  [::]:*        users:(("pmlogger",pid=2072,fd=8))
```

**Comment by dessalines** [comment]
You don't want the postgres to be accessible outside of the docker-compose setup, so that should be fine. That's what it looks like on our prod deploy:

`   postgres:12-alpine                 "docker-entrypoint.s…"   8 months ago   Up 3 days     5432/tcp                   lemmyml_postgres_1`

Did you alter your password to the correct one in this restore? 

https://join-lemmy.org/docs/en/administration/backup_and_restore.html#restoring-the-db

Was your DB username also `lemmy`?

**Comment by dessalines** [comment]
Oh damn I think I figured out the problem!

https://github.com/LemmyNet/lemmy-ansible/blob/main/examples/config.hjson#L6

@Rynach Your host should be `postgres`, not `localhost`.

**Comment by jonathonf** [comment]
Looks like we hit the answer at the same time. :grin:
