### ISSUE TITLE
Add homepage and docs Cargo metadata to `crates` libs

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy#1849]
### Is your proposal related to a problem?

At the moment, only `lemmy_server` has this metadata, but for consistency sake, all other published crates under `/crates` should have them as well.

### Describe the solution you'd like

Add the same homepage and docs links to all published crates.

**Comment by Nutomic** [comment]
Do you want to make a PR for this? The metadata for lemmy_server is defined in the root Cargo.toml, and you basically need to copy it to crates/*/Cargo.toml.
