### ISSUE TITLE
Picture upload not possible, pictures on the instance not visible

### ISSUE THREAD

**Issue by sthaydn** [LemmyNet/lemmy#1863]
### Issue Summary
The error is the same as
https://github.com/LemmyNet/lemmy/issues/1645
but it isn't "magically resolving" on my instance. ;-)

### Steps to Reproduce
Uploading a picture, e. g. Avatar gives error:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### Technical details
OS Debian bullseye
Lemmy 0.13.0

Firefox output when trying to upload:
Error 502 Bad Gateway, referrer policy "same-origin"

PICTR has permission 991:991

Rebooting or rebuilding Lemmy doesn't work.

I don't really know when it started, but it was before 0.13.0 as well.

**Comment by Tealk** [comment]
I also get the message when I try to upload an icon or banner in the admin section.

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

```
{
  opentelemetry_url: "http://otel:4137"

  hostname: "lemmy.rollenspiel.monster"
  bind: "0.0.0.0"
  port: 8536
  pictrs_url: "http://pictrs:8080"
  database: {
    database: "lemmy"
    user: "lemmy"
    password: "xxx"
    host: "postgres"
    port: 5432
    pool_size: 5
  }
  federation: {
    enabled: true
    allowed_instances: [
    ]
    blocked_instances: [
    ]
    strict_allowlist: true
    worker_count: 64
  }
  captcha: {
    enabled: false
    difficulty: "medium"
  }
  slur_filter:
    '''
    (fag(g|got|tard)?\b|cock\s?sucker(s|ing)?|ni((g{2,}|q)+|[gq]{2,})[e3r]+(s|z)?|mudslime?s?|kikes?|\bspi(c|k)s?\b|\bchinks?|gooks?|bitch(es|ing|y)?|whor(es?|ing)|\btr(a|@)nn?(y|ies?)|\b(b|re|r)tard(ed)?s?)
    '''
}

```
