### ISSUE TITLE
Broken federation?

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy#1869]
### Issue Summary

Content from/to other instances doesn't seem to reach the endpoint.
e.g., https://fapsi.be/c/dnd ⇋ https://lemmy.ml/c/dnd@fapsi.be

Also: sometimes, when I try to open a remote community on my instance, I get a “Community not found” on first try. Second try mostly works, but not always.

### Technical details

Docker logs are like:
```
lemmy_1     | [2021-10-29T10:26:23Z INFO  lemmy_apub::fetcher::fetch] Fetched remote object https://feddit.de/c/netzpolitik/moderators
lemmy_1     | [2021-10-29T10:26:23Z INFO  lemmy_apub::fetcher::fetch] Fetched remote object https://feddit.de/c/netzpolitik/outbox
lemmy_1     | [2021-10-29T10:26:23Z WARN  lemmy_utils] invalid type: string "https://feddit.de/c/netzpolitik", expected tuple struct ObjectId at line 1 column 540
lemmy_1     | [2021-10-29T10:41:43Z INFO  lemmy_apub::fetcher::fetch] Fetched remote object https://lemmy.ml/c/selfhosted/moderators
lemmy_1     | [2021-10-29T10:41:46Z INFO  lemmy_apub::fetcher::fetch] Fetched remote object https://lemmy.ml/c/selfhosted/outbox
lemmy_1     | [2021-10-29T10:41:46Z WARN  lemmy_utils] data did not match any variant of untagged enum AnnouncableActivities at line 1 column 1795
```

Running Lemmy 0.13.3
docker-compose version 1.21.2, build a133471
Docker version 20.10.10, build b485636

I've already restarted and recreated my containers, but nothing changed.

**Comment by dessalines** [comment]
That looks fine to me. Did you see if its the system clock issue? Try updating your system clock then restarting.

**Comment by kromonos** [comment]
Ok, don't know what happened, but it just started to work again. 🤔
Time on my system and in the docker container seems good. The system time has an offset of -0.001081 sec.

**Comment by dessalines** [comment]
Apologies, this was this bug again, not your system time: https://github.com/LemmyNet/lemmy/issues/1820. Restarting lemmy.ml fixed it. Damn things running fine for 3 weeks then crashing. :(

**Comment by kromonos** [comment]
> Apologies, this was this bug again, not your system time: #1820. Restarting lemmy.ml fixed it. Damn things running fine for 3 weeks then crashing. :(

No need to apology 😊 We all know, that Lemmy is still in development and bugs can happen 😊
