### ISSUE TITLE
Username change (as long as the new one is available)

### ISSUE THREAD

**Issue by je-vv** [LemmyNet/lemmy#1872]
I do believe the ability to change one's username is pretty important, carrying it out without losing one's history of activities by closing/terminating one account to start a new different one.  There's a lot of value on that.  When doing so, all the activity history, upvotes, downvotes, comments, posts, etc, should change the username identity to the new one after the change.  Such change might take time to complete, since the process can be long, depending on the user history, but it's just fine, and preferred to just closing one's account to start a new one.

AFAIK reddit doesn't offer such feature, but Lemmy is not reddit, and I believe the feature would be really great.  I do want a different username, but I don't want to lose what I've posted, commented, and so on.  Meaning, I want to keep my Lemmy's history of activities, I just want to change my username, but that's not currently possible.  Perhaps this is a feature that can be developed not immediately, not as a high priority one, but still be included in plans to be developed and supported.

Thanks !

**Comment by je-vv** [comment]
Are followers implemented?  AFAIK, it was still not...  But regardless, it would make the followers of the particular user changing its username, stop following him/her, right?  Nothing else would break.  That seems a reasonable compromise for those making the change (in the end it's not forced)...

There's nothing wrong with changing the display name, but is there guarantee that your display name can't be linked to your username?  And if by any chance you used a username you commonly use for some other accounts (no matter what they are for, email, xmpp, whatever), then perhaps you might be easily identified, when perhaps you want to avoid it, or you just want to get rid on purpose of some followers, whatever reason you might want to go beyond just a display name change....

**Comment by Nutomic** [comment]
Changing the username will break many aspects of federation. For other instances you will look like a completely new user, so you wont be able to edit or delete any old posts/comments. I really dont think its worth all the trouble when you can simply create a new account.

**Comment by je-vv** [comment]
I won't insist, then.  BTW, in case this is brought back in the future, you could avoid having to fix all federation issues.  In the end the username is tight to a single instance/service, and what stops working for that particular username on other instances/services should not be of a big concern.

One thing to consider though, is the ability to export the subscriptions some how, to restore them in a different account.  So at least that much is not lost when deactivating an account.

**Comment by Nutomic** [comment]
> One thing to consider though, is the ability to export the subscriptions some how, to restore them in a different account. So at least that much is not lost when deactivating an account.

That is true. Honestly I would prefer to leave that to some external tool because it can be done perfectly fine through the API. So there is no real need for us to implement and maintain it. Anyway, feel free to open an issue if there isnt already.
