### ISSUE TITLE
Add unique constraint for column activity.ap_id

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1878]
Then remove function `is_activity_already_known()`. No need to make a separate query and check in Rust, when we can simply rely on db constraints. The migration needs to delete any existing, duplicate values first.

**Comment by dessalines** [comment]
I think this already exists:

```
Indexes:
    "activity_pkey" PRIMARY KEY, btree (id)
    "idx_activity_unique_apid" UNIQUE, btree ((data ->> 'id'::text))
```

**Comment by Nutomic** [comment]
I tried and was able to insert duplicate values without any problem.

Btw, another thing I would like to do is change community.public_key into String (instead of Option<String>). Same for person.public_key.
