### ISSUE TITLE
couldn't update site

### ISSUE THREAD

**Issue by ncorder** [LemmyNet/lemmy#1879]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Lemmy states that I cannot update site when I attempt to add federation block via graphical interface.

### Steps to Reproduce

1. Log in as admin
2. Go to admin settings
3. place the following directly above the line stating` setup: {`
<details open>
<summary>Federation Block</summary>
<code>
{
  hostname: lemmy-alpha
  federation: {
    enabled: true
  }
  slur_filter:
    '''
    (fag(g|got|tard)?\b|cock\s?sucker(s|ing)?|ni((g{2,}|q)+|[gq]{2,})[e3r]+(s|z)?|mudslime?s?|kikes?|\bspi(c|k)s?\b|\bchinks?|gooks?|bitch(es|ing|y)?|whor(es?|ing)|\btr(a|@)nn?(y|ies?)|\b(b|re|r)tard(ed)?s?)
    '''
}
</details>

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
* What OS are you trying to install lemmy on? 
* Any browser console errors?

- https://paste.debian.net/1218286/

**Comment by dessalines** [comment]
1. That needs to be formatted correctly, you seem to have no line breaks in any of your pastes.
2. I'm fairly sure that live updating config is broken currently, I suggest editing your `lemmy.hjson` manually then restarting lemmy for now.

**Comment by ncorder** [comment]
>     1. That needs to be formatted correctly, 

Thanks for letting me know, I'll see if I can fix that but it appears to not allow multi-line code blocks this long. 
also debian paste: https://paste.debian.net/1218286/

> I'm fairly sure that live updating config is broken currently, I suggest editing your lemmy.hjson manually then restarting lemmy for now.

:+1: thanks

> lemmy.hjson

Just to confirm, is this the proper formatting for this:

```
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

{
  hostname: lemmy-alpha
  federation: {
    enabled: true
  }
  slur_filter:
    '''
    (fag(g|got|tard)?\b|cock\s?sucker(s|ing)?|ni((g{2,}|q)+|[gq]{2,})[e3r]+(s|z)?|mudslime?s?|kikes?|\bspi(c|k)s?\b|\bchinks?|gooks?|bitch(es|ing|y)?|whor(es?|ing)|\btr(a|@)nn?(y|ies?)|\b(b|re|r)tard(ed)?s?)
    '''
}

  setup: {
    # username for the admin user
    admin_username: "lemmy"

[...]

```

**Comment by Axeltherabbit** [comment]
Looks like it still is broken, I manually changed it from ansible and it worked fine
