### ISSUE TITLE
Backend doesnt convert spoiler tags from markdown to HTML

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1884]
The Lemmy frontend supports spoiler tags like these:
```
::: spoiler details
content
:::
```
Results in
```
<details><summary>details</summary>
content
</details>
```
But the backend doesnt support these spoiler tags at all, meaning they dont get transformed at all in ActivityPub messages and RSS feeds.

The spoiler tag not part of CommonMark, but is a custom tag from [markdown-it-container](https://github.com/markdown-it/markdown-it-container), so its unlikely that [comrak](https://github.com/kivikakk/comrak) which we use on the backend would support it.

From https://github.com/LemmyNet/lemmy/issues/1871#issuecomment-959845459

**Comment by academician** [comment]
I'm just wondering - why this syntax for spoiler text? I realize there's no standard for it, but it's just not one I've seen before. From the lemmy-ui issues it looks like it was a custom syntax from `markdown-it`?

```markdown
::: spoiler details
content
:::
```

For comparison, Reddit and some other sites I've seen use:

```markdown
>!content!<
```

Before the above was introduced, Reddit spoilers used this (which supports visible text but I don't love it):

```markdown
[details](/s "content")
```

Stackexchange just has spoiler blocks, with:

```markdown
>!content
```

Discord uses:

```
||content||
```

IMO it could be worth supporting one of those syntaxes as well, at least.
