### ISSUE TITLE
Community outbox should only contain activities from community

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#1906]
At the moment it contains Create/Post activities, which were sent by other users. Should be changed to contain Announce/Post (or Announce/Create/Post), which were sent by the community itself.

**Comment by dessalines** [comment]
We might need to start adding labels for priority, like you see some trackers do. `p1`, `p2`, etc.

**Comment by Nutomic** [comment]
This is already fixed (the outbox contains Announce/Post now).

Priority labels could be useful, but then we have to go through all issues and decide which priority they are.
