### ISSUE TITLE
Image posts federation uses "wrong" url in post

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy#1910]
When image posts get federated with Lemmy or Mastodon, they receive a link to the picture, but not the link to the post on the Lemmy instance.   

For example: 
![20211117-2356 - Screenshot](https://user-images.githubusercontent.com/1553902/142296163-3a93315f-16d0-4cd8-b728-b3931ab69a72.png)  

The original post is https://fapsi.be/post/2989, but Mastodon uses the direct URL to the image in the post.

**Comment by Nutomic** [comment]
Looks like Mastodon cant correctly display posts which have both link and body. You need to report it to them, it has nothing to do with Lemmy.
