### ISSUE TITLE
Federated permalinks have borked URLs

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy#1912]
### Issue Summary

When viewing a lemmy comment from mastodon, the "permalink" doesn't have the "post ID" so it 404's :scream: 
![Screenshot from 2021-11-17 15-52-59](https://user-images.githubusercontent.com/578515/142301013-989f9d5b-22f7-45ee-a705-1d2b97f1f537.png)

### Steps to Reproduce

1.  Go to https://mastodon.social/web/@dessalines@lemmy.ml/107295063707349748 or any post from a lemmy instance on mastodon.
2.  Click on the date,
3. observe 404 page

**Comment by Nutomic** [comment]
Its a problem in lemmy-ui, i opened an issue there.

https://github.com/LemmyNet/lemmy-ui/issues/493

**Comment by dessalines** [comment]
This is also a problem in lemmy, since we don't have `GetComment` in the API. See the linked issue for more detail.
