### ISSUE TITLE
Don't send notifications on post/comment edits

### ISSUE THREAD

**Issue by realkinetix** [LemmyNet/lemmy#1925]
Recently had an email notification when someone responded to a comment of mine.

And then 5 or 6 more email notifications as they edited and saved a bunch of times.  The extra notifications seem unnecessary.

**Comment by dessalines** [comment]
That might be unavoidable, because if they edited the comment, they might've added a mention. If we don't email edits, you might miss a mention.

**Comment by Nutomic** [comment]
This is fixed by https://github.com/LemmyNet/lemmy/pull/1914.

**Comment by poVoq** [comment]
I think this also effects pure lemmy users.

Some of the edits were just tiny typo corrections like adding an "s". Maybe there could be some filter to send only emails when a significant enough edit is made?

**Comment by Nutomic** [comment]
Oh this is about notifications on the lemmy website? Then #1914 has nothing to do with it, my bad.

**Comment by realkinetix** [comment]
Well, the intention on opening this up was due to email notifications.  I don't know that the site was harassing me, I didn't catch any notifications in the browser about it.

**Comment by dessalines** [comment]
I wouldn't want to add any complicated logic to edit notifications, I'd rather them just be on or off.
