### ISSUE TITLE
how to config image upload for ./target/debug/lemmy_server ?

### ISSUE THREAD

**Issue by goodforever** [LemmyNet/lemmy#1929]
I build lemmy_server and pict-rs and run them . like this :

vi /etc/hosts
127.0.0.1  pictrs 

for  lemmy
cargo build 
./target/debug/lemmy_server

for  pict-rs
cargo build 
mkdir -p ./volumes/pictrs_alpha
./target/debug/pict-rs -a 0.0.0.0:8080 -p ./volumes/pictrs_alpha

But I cannot upload image , error  : failed for fetch . 
How to config ?

log 

./target/debug/lemmy_server 
Starting http server at 0.0.0.0:8536
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
thread 'actix-rt|system:0|arbiter:1' panicked at 'No auth header for picture upload', crates/routes/src/images.rs:55:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt|system:0|arbiter:3' panicked at 'No auth header for picture upload', crates/routes/src/images.rs:55:6
thread 'actix-rt|system:0|arbiter:4' panicked at 'No auth header for picture upload', crates/routes/src/images.rs:55:6

**Comment by dessalines** [comment]
We can't help debug manual installs, only docker or ansible setups. Follow every step in those dockerfiles to see whats wrong.
