### ISSUE TITLE
Whitelist or Blacklist for specific communities when federating

### ISSUE THREAD

**Issue by pscodes4fun** [LemmyNet/lemmy#1952]
### Is your proposal related to a problem?

Instances can include many very different communities. Some might be compatible with other instances and some may not. At the moment it is an all or nothing thing - either federate the whole instance or don't.

As an instance owner, you may decide against federating with an instance due to some specific communities - this hinders federation

or

As an instance owner, you may have communities on your instance that you think are going to be incompatible with another instance and you do not want to upset the environment other instance owner has created or create work for them banning users in these communities,

### Describe the solution you'd like

When Federating with another instance, being able to choose:
- All Communities
- Whitelist - just federate these communities
- Blacklist - federate all communities except these

### Additional context

This was originally included as a comment here https://github.com/LemmyNet/lemmy/issues/1487 

Creating a separate issue as requested.

"Do you have to federate all communities on an instance - maybe a setting like

- All Communities
- Whitelist - just federate these communities
- Blacklist - federate all communities except these

I suggest this because 2 instances may have an overlap of interests where it makes sense to federate communities relating to those interests. But there maybe communities on the other instance that are not compatible with yours or worse communities on your instance that may not be compatible with the other instance and will upset the other instance owner.

Rather then federating all the communities and having users banned by the other instance as a result - it might be smarter and create more cohesion to be able to select the communities that you will allow federation with.

**Comment by Nutomic** [comment]
FYI it is already possible to stop federation with specficic remote communities. You can do that as admin by removing the community, which means it wont be shown to local users, and incoming federated messages will be rejected. Nevertheless, this would be a nice feature.

**Comment by dessalines** [comment]
The solution above, IE removing the communities, is much cleaner and easier from a UI perspective already.

Also users can block communities now if they want.
