### ISSUE TITLE
Block same url in same community

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy#1953]
I saw this now more than once, that one and the same URL is posted in one and the same community within a very short time.  
As example:
![image](https://user-images.githubusercontent.com/1553902/143130350-f6322819-6ef5-4f43-8a6c-9320904e310a.png)

You can find it at https://fapsi.be/post/5828 as well as https://fapsi.be/post/5829.  
I would suggest making it configurable in the settings in seconds and 0 for disable.

**Comment by Nutomic** [comment]
Too much effort for such a minor problem.
