### ISSUE TITLE
How to increase maximum post size of an image in a message.

### ISSUE THREAD

**Issue by hklm-win** [LemmyNet/lemmy#1957]
I did an docker install of lemmy and everything is working great, only an direct upload of an video in a post can have a max size off 1MB
I did put  
**client_max_body_size 20M;** 
in the file /etc/nginx/sites-enabled/lemmy.conf in every section, but that is not working.

**Comment by Nutomic** [comment]
I think neither Lemmy nor pictrs have any file size limit by default. Is it possible that there is a limit defined in the global nginx config, or somewhere else on your server?

**Comment by hklm-win** [comment]
root@Lemmy:/etc# grep -R client_max_body_size *
nginx/sites-available/default: client_max_body_size 20M;
nginx/nginx.conf: client_max_body_size 20M;
nginx/sites-enabled/default: client_max_body_size 20M;
nginx/sites-enabled/lemmy.conf:    client_max_body_size 20M;
nginx/sites-enabled/lemmy.conf:    client_max_body_size 20M;
nginx/sites-enabled/lemmy.conf:    client_max_body_size 20M;
nginx/sites-enabled/lemmy.conf:   client_max_body_size 20M;
nginx/sites-enabled/lemmy.conf:   client_max_body_size 20M;
nginx/sites-enabled/lemmy.conf:   client_max_body_size 20M;
nginx/sites-enabled/lemmy.conf:   client_max_body_size 20M;

Not that I can find do you have any other suggestions ?

**Comment by Nutomic** [comment]
No idea, sorry. Maybe ask the nginx community.
