### ISSUE TITLE
I finish translation for Chinese traditional on Weblate. I don't know how to push it.

### ISSUE THREAD

**Issue by ianiiaannn** [LemmyNet/lemmy#1965]
[https://weblate.yerbamate.ml/projects/lemmy/lemmy/zh_Hant/](https://weblate.yerbamate.ml/projects/lemmy/lemmy/zh_Hant/) has been fully translated. Sorry for bad English writing.

**Comment by ianiiaannn** [comment]
I created a [pull request](https://github.com/LemmyNet/lemmy-translations/pull/19).
Chinese in the dropdown menu now is Simplified Chinese, this pull request is for Traditional Chinese.

**Comment by dessalines** [comment]
You don't need to open up a pull request, your translations will automatically be added when we do the next release. Thanks!
