### ISSUE TITLE
[Feature Discussions] New feature request

### ISSUE THREAD

**Issue by aryan1107** [LemmyNet/lemmy#1970]
-  Add option to buy coins and award post with gifts from those coins.
- Add option to Create talks(like clubhouse thing reddit copied)

**Comment by dessalines** [comment]
Could you split these into separate issues? And what are talks?

**Comment by aryan1107** [comment]
Both are just a suggestions by talks, I mean live audio talks in a community. Will be a cool feature like [this](https://www.reddit.com/talk).

But is not required now maybe in future.

**Comment by Nutomic** [comment]
There is no reason why something like that should be part of Lemmy. It should just be a separate project.
