### ISSUE TITLE
[ Feature request] Add option to buy coins

### ISSUE THREAD

**Issue by aryan1107** [LemmyNet/lemmy#1971]
Add option to buy coins and award post with gifts from those coins. You can add more gifts in future with their value. People can purchase gifts and award to certain post.

**Comment by Nutomic** [comment]
No, Lemmy is not a commercial project.

**Comment by aryan1107** [comment]
Okay

**Comment by Denaton** [comment]
@Nutomic i would like to address this again, even tho Lemmy is not a commercial project, it would be cool to have Award like in Reddit that we can buy from the instances we are users of, this could help support the admins of an instance and also boost comments that help. Letting the instance owners set the price (possible free) and their own reward images and have instances able to disable the feature like we can already do with downvote.
