### ISSUE TITLE
Make Lemmy LibreJS Compliant

### ISSUE THREAD

**Issue by TomatDividedBy0** [LemmyNet/lemmy#1973]
The FSF began an initiative a few years back to push website owners to begin using open-source JS, given how in the modern day a lot of the non-free software we run is in JS scripts and the various telemetries they mask.
 
To accompany this, they release a Firefox extension which automatically blocks scripts which are both non-trivial in size and non-free. One can mark a script as free by embedding the source code in a custom Web Labels table, [as described in the docs here.](https://www.gnu.org/software/librejs/manual/librejs.html#JavaScript-Web-Labels) A site whose scripts are either trivial or marked in the table with the source code is considered compliant.

IMO this is important towards the end of creating a free web, we have to be able to trust that the software we run on a daily basis is free, especially given how people continue to spend more and more of their time with computers in their web browser. If these ideologically-driven open-source passion projects aren't meeting compliance, that sends a bad message to the rest of the wider world, so I think it makes sense to start here.

Playing around with the site a bit, looks like the main script I'm seeing which gets blocked is `/static/js/client.js`. Without this, it's impossible to do basic actions such as posting or subscribing to communities.

**Comment by dessalines** [comment]
Front end issue, and this is already done: https://lemmy.ml/static/js/client.js.LICENSE.txt

**Comment by Integral-Tech** [comment]
I visited https://lemmy.ml with LibreJS enabled, but it told me "Javascript is disabled. Actions will not work."

**Comment by Integral-Tech** [comment]
@dessalines

**Comment by dessalines** [comment]
Someone more familiar with librejs will have to take a look at that. I have no idea how their plugin works or what its looking for.
