### ISSUE TITLE
Need help with setting up changing theme. 

### ISSUE THREAD

**Issue by aryan1107** [LemmyNet/lemmy#1974]
As someone who is very new and has never used docker before. Yesterday I managed to run Lemmy version on docker on my ubuntu. 

Now I see few themes on github lemmy-UI repo how do I try these various themes and see different themes on lemmy which is running on my ubuntu?

**Comment by dessalines** [comment]
Go to your profile settings in the top right, and one of the options will be theme.

![image](https://user-images.githubusercontent.com/930215/144728646-53126ab4-3953-4dbf-b68a-8ab27a513f25.png)

**Comment by aryan1107** [comment]
Thank you so much very helpful. I find the default theme good. But however suppose I need to change certain buttons colour from green to something else I suppose I will have to edit front end codes.

In doc creating custom front end section you need to fork it. After I fork lemmy-ui what command do I use to run it locally to edit and test my custom front end?

**Comment by dessalines** [comment]
> After I fork lemmy-ui what command do I use to run it locally to edit and test my custom front end?

https://join-lemmy.org/docs/en/client_development/theming.html

Read the section on front end development:

https://join-lemmy.org/docs/en/contributing/local_development.html#run-a-local-development-instance

**Comment by darkzbaron** [comment]
> > After I fork lemmy-ui what command do I use to run it locally to edit and test my custom front end?
> 
> https://join-lemmy.org/docs/en/client_development/theming.html
> 
> Read the section on front end development:
> 
> https://join-lemmy.org/docs/en/contributing/local_development.html#run-a-local-development-instance

Link for themin (https://join-lemmy.org/docs/en/client_development/theming.html) is broken

**Comment by dessalines** [comment]
https://join-lemmy.org/docs/en/administration/theming.html
