### ISSUE TITLE
Need Help for adding more features

### ISSUE THREAD

**Issue by aryan1107** [LemmyNet/lemmy#1975]
I am new and I have lemmy running in localhost through docker. Now I need to edit some codes to play with it and possibly try to add more features. One thing is adding coin options allowing new users to buy coins and award it to certain posts. This would be later on. Right now suppose I want to add one more link in footer how do I edit code?

How how do I change source code? It's running on docker but how do I run it locally to make few changes on the files to test and see the results?

**Comment by dessalines** [comment]
Make the changes in the back-end code, then re-rerun `./docker_update.sh` , or `./docker_update_volume_mount.sh`
