### ISSUE TITLE
Hide community from trending section

### ISSUE THREAD

**Issue by dayinjing** [LemmyNet/lemmy#1980]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

(Sometimes I don't want to remove a community but I also don't want new users to see it on the front page.)

### Describe the solution you'd like

(Allow admins to hide communities from trending section and also all.)

### Describe alternatives you've considered

(Shadow ban it.)

### Additional context

(Probably be good if the user who made it still sees it so they don't create a bunch of crap communities.)

Lets take for example Ruqqus, when MGTOW came to ruqqus the whole front trending page turned into divorced men complaining about life. It would be mean to not allow such people to have a space to help each other but people also don't want to see it when they first come to the site. If a user wants to search it up in the list and subscribe to it then it could show up in trending and all the same way. 

This way a site admin can better control their front page without turning away communities entirely.

**Comment by dayinjing** [comment]
I'm ready to work on this now btw. Would just like a sign off from the main maintainers on a design.

Should we create a seperate end point for trending? should we make a new endpoint that gets a list of blacklisted communities and pass it to the community list endpoint?

**Comment by Nutomic** [comment]
I think there are a few ways that this could implemented, and the end result will depend on which one you pick. One option would be a new config option to hide communities, that would be pretty simple, and without changes in the api/frontend. It could be in the community settings, which means mods can also change it. Or it could be a separate table, and even changes on the frontend to hide/unhide communities. 

Anyway it seems like an interesting and useful feature. Only problem might be if the feature is intransparent to people. So it might be necessary to indicate the hiding in some way. But in general i dont see any reason against merging something like this.

**Comment by dessalines** [comment]
The easiest way to do would be to add an optional `hidden_communities` string array to the config... database-wise it wouldn't be optimal, because it'd require a `not in(` query. I don't like that too much.

The best DB wise would probably be a `hidden` column on the `community` table, default false. And then add a `HideCommunity` endpoint, and some way through the UI for admins to update that column. Then you'd only have to do `.filter(community::hidden.eq(false)`

**Comment by dayinjing** [comment]
> I think there are a few ways that this could implemented, and the end result will depend on which one you pick. One option would be a new config option to hide communities, that would be pretty simple, and without changes in the api/frontend. It could be in the community settings, which means mods can also change it. Or it could be a separate table, and even changes on the frontend to hide/unhide communities.
> 
> Anyway it seems like an interesting and useful feature. Only problem might be if the feature is intransparent to people. So it might be necessary to indicate the hiding in some way. But in general i dont see any reason against merging something like this.

I would like the community to be hidden from trending communities and all but still be shown in the community list. Maybe if it's really bad also have it not show up on the communities list but users can still see it if they are subscribed or enter in the url. 

Maybe if that is to complicated we can just hide it from all of it for now. I'm ok with that.

**Comment by dayinjing** [comment]
Initial PR for backend https://github.com/LemmyNet/lemmy/pull/2017
