### ISSUE TITLE
Error: LemmyError { inner: Failed with: permission denied to create extension "pgcrypto" }

### ISSUE THREAD

**Issue by milahu** [LemmyNet/lemmy#1993]
this error message is confusing

```
Error: LemmyError { inner: Failed with: permission denied to create extension "pgcrypto" }
```

the actual reason is `permission denied`
when a user has no write access to the lemmy database

solution in my case: add user mapping

```sh
echo "idmap1 lemmy lemmy" | sudo tee -a /var/lib/postgresql/*/pg_ident.conf
```

docs: `/usr/share/postgresql/pg_ident.conf.sample`
https://www.postgresql.org/docs/current/auth-username-maps.html

**Comment by dessalines** [comment]
Which install guide did you use to install lemmy?

**Comment by milahu** [comment]
from scratch, but thats not relevant ...

**Comment by Nutomic** [comment]
So whats the bug, that its showing the wrong error message? Not sure that can be fixed. I think its obvious that Lemmy needs write access to the database to work.

**Comment by milahu** [comment]
> So whats the bug, that its showing the wrong error message?

yepp, as i said

> this error message is confusing

psql adds a hint

```
psql -d lemmy -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

ERROR:  permission denied to create extension "pgcrypto"
HINT:  Must have CREATE privilege on current database to create this extension.
```

> Not sure that can be fixed.

```sh
psql -d lemmy -c "select has_database_privilege('lemmy', 'CREATE');"
```

returns true or false

https://pgpedia.info/h/has_database_privilege.html

---

to compare, other database errors ...

**no user**

```
FATAL:  password authentication failed for user "lemmy"
```

solution:

```sh
db_user=lemmy
db_password=1234
sudo -iu postgres psql -c "CREATE USER \"$db_user\" WITH PASSWORD '$db_password';"
```

**no database**

```
FATAL:  database "lemmy" does not exist
```

solution:

```sh
db_user=lemmy
db_name=lemmy
sudo -iu postgres psql -c "CREATE DATABASE \"$db_name\" WITH OWNER \"$db_user\";"
```

**Comment by dessalines** [comment]
This has nothing to do with lemmy. Look up how to create a postgres database with proper full permissions.

**Comment by milahu** [comment]
yeah, RTFM kids!

at least now people can google what the error means
