### ISSUE TITLE
Can't connect to SMTP server with StartTLS

### ISSUE THREAD

**Issue by ashemsay** [LemmyNet/lemmy#1997]
### Issue Summary

Can't make lemmy work with my smtp server with starttls for e-mail notifications

### Steps to Reproduce

1. Set up mail configuration, here's mine
   ```
   # hostname and port of the smtp server
   smtp_server: "domain.tld:587"
   # login name for smtp server
   smtp_login: "mailuser"
   # password to login to the smtp server
   smtp_password: "password"
   # address to send emails from, eg "noreply@your-instance.com"
   smtp_from_address: "mailuser@domain.tld"
   # whether or not smtp connections should use tls
   use_tls: true
   ```
2. Create a dummy account
3. Use the forgotten password link when logging in

### Technical details

* Error message:
  ```
  2021-12-14T20:59:46.737930Z  WARN lemmy_utils: Connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:332:
    at crates/utils/src/lib.rs:60
  2021-12-14T20:59:46.738056Z ERROR lemmy_websocket::handlers: Error during message handling {"error":"email_send_failed"}
    at crates/websocket/src/handlers.rs:78
  ```
* I think there's something with the way lemmy handles the tls part, when I do this test on the command line:
   ```
   openssl s_client -showcerts -connect domain.tld:587 -starttls smtp
   ```
   Everything works fine but when I remove the starttls part (so I do a direct TLS negociation) I get the same error that lemmy throws at me:
   ```
   openssl s_client -showcerts -connect domain.tld:587
   # returns
   # 140001075209536:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
   ```

NOTE: I tried setting use_tls to false, of course it did not work, some error message about no authentication mechanism found

**Comment by dessalines** [comment]
I tried looking in our email client's issues, didn't see anything with that error: https://github.com/lettre/lettre/issues

Searching for that error gives a lot of results tho, that seem to be a misconfigured nginx for your mail server.

https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number/50842202

https://stackoverflow.com/questions/63308489/nginx-error-https-curl-35-error1408f10bssl-routinesssl3-get-recordwrong

**Comment by ashemsay** [comment]
I kind of doubt it, all my e-mail clients use those settings, I've got multiple thunderbirds, fair email, other web tools (matrix, nextcloud, wordpress, ...) sending mail via this smtp server, everything is working fine.
To try to eliminate this possibility though I made a test using gmail (on 587 port for starttls, not 465 which is SMTPS) and got the same error

**Comment by dessalines** [comment]
Open up an issue on the lettre repo asking about this.

**Comment by ashemsay** [comment]
Yes, maybe I'll do that after I have cleared some things up and tried a few others.

I tried capturing packets with tcpdump on my smtp server during the connection and compare with other connections that work.

Here is what I capture when Lemmy tries sending email:

I don't know how to add color to the code so I added the `<-- server`bits to show what wireshark colored as server communication
```
220 domain.tld Service ready <-- server
...........[some random chars but not sure if completely random so hiding them].
...9.	...3.....=.<.5./.....u........	domain.tld.........
...
...........#...........
.0.............	.
.................................+........-.....3.&.$... [some random chars but not sure if completely random so hiding them].....................................................................................................................................................................................................................
```

and here's what I capture when I send an e-mail from fair e-mail for example:
```
220 domain.tld Service ready <-- server
EHLO [127.0.0.1]
250-domain.tld <-- server
250-PIPELINING <-- server
250-SIZE 35914708 <-- server
250-ETRN <-- server
250-STARTTLS <-- server
250-ENHANCEDSTATUSCODES <-- server
250-8BITMIME <-- server
250-DSN <-- server
250 CHUNKING <-- server
STARTTLS
220 2.0.0 Ready to start TLS <-- server
...............[some random chars but not sure if completely random so hiding them]...	.
........./.5.
............	domain.tld..........
..........................
.......................[some random chars but not sure if completely random so hiding them]
```

We can see in the second case that the gibberish which I suppose is encrypted stuff only comes after a non encrypted communication was made between client and server and the command to begin the tls session was issued whereas in the first case it starts directly with tls.

This kind of confirms what I was thinking so I don't want to open an issue on lettre's project, at least not yet.

I took a look at lettre documentation and saw that there was some specific stuff to do for starttls communication but I don't know rust so I'm kind of lost but I will try a few things.

I will try to at least have a simple snippet of code that works with starttls following the docs.

Ironically my smtp server lies on the same host as my lemmy installation so I could just do smtp without authentication on the loopback interface but I don't see how to do a non authenticated connection in the lemmy settings, but maybe that's for another issue.

**Comment by dessalines** [comment]
I'll just reiterate that lemmy handles TLS and STARTTLS in the exact same way that lettre reccommends. That [code is here](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/email.rs).

**Comment by ashemsay** [comment]
Ok I opened the issue on their repo.

**Comment by ashemsay** [comment]
In the meantime I found this example in the docs that I wanted to try but I don't know how: https://docs.rs/lettre/0.10.0-rc.4/lettre/transport/smtp/index.html#authentication

**Comment by dessalines** [comment]
A one file rust project would be the best way to test, and if it doesn't work, you can share it with the lettre devs.

**Comment by ashemsay** [comment]
I could send an e-mail using their example code, I took the suggestion from paolobarbolini [here](https://github.com/lettre/lettre/issues/709#issuecomment-997273159):

> If you'd like you can also clone the repository, edit examples/smtp_starttls.rs locally and run it with cargo run --example smtp_starttls

Also check the answer from amousset [here](https://github.com/lettre/lettre/issues/709#issuecomment-997274019):

> You code shows Tls::Wrapper(tls_config) which makes lettre use a TLS-wrapped connection and not STARTTLS. The error message you gets also looks like the remote end expects plain text.

**Comment by dessalines** [comment]
The main difference I can see between ours and their example: https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/email.rs#L80

Is that we use `let mut builder = SmtpTransport::builder_dangerous(smtp_server).port(smtp_port);`, while starttls needs `SmtpTransport::starttls_relay("smtp.gmail.com")`

That should be easy enough to code. Is starttls always `587`? Or should we change the `use_tls` to a string that must be `TLS` or `STARTTLS`.

**Comment by ashemsay** [comment]
587 is the default port used for starttls, even though people can change it I think it is very unlikely.

That being said I find it much clearer and good practice to be explicit about using SMTPS or SMTP+StartTLS so I would choose the latter.

**Comment by dessalines** [comment]
Sounds good. I'll do a PR for this sometime soon.

**Comment by ashemsay** [comment]
> Sounds good. I'll do a PR for this sometime soon.

Awesome, thanks!
