### ISSUE TITLE
localhost to .com (Running local development)

### ISSUE THREAD

**Issue by aryan1107** [LemmyNet/lemmy#1998]
Hi I made some changes in ui by running local development as mentioned here https://join-lemmy.org/docs/en/contributing/local_development.html

Now I want it to be accessed by a domain which I have how do I set it up?

**Comment by dessalines** [comment]
Why do you need a domain for local development?

What are you working on?

**Comment by aryan1107** [comment]
Development is done I just changed some colours

**Comment by dessalines** [comment]
That all depends on how you are running lemmy in production. 

You'll likely need to create a docker image for lemmy-ui and reference that in your production docker-compose file, since you aren't doing PRs for any of your changes to lemmy-ui. There is a `Dockerfile` in the lemmy-ui repo.
