### ISSUE TITLE
after installing lemmy with docker

### ISSUE THREAD

**Issue by shveli96** [LemmyNet/lemmy#2001]
after installing lemmy with docker. lemmy works on localhost: 1235 I want to work on the domain instead of the localhost. I read in the instructions that you need to add nginx and I did everything according to the instructions. and used this code:

wget https://raw.githubusercontent.com/LemmyNet/lemmy-ansible/main/templates/nginx.conf
# Replace the {{vars}}
# The default lemmy_port is 8536
# The default lemmy_ui_port is 1235
sudo mv nginx.conf /etc/nginx/sites-enabled/lemmy.conf

domain turned on http://topix.ge it works.

but now how to make it so that together what is written here lemmy was displayed.

I want instructions with commands.
what exactly should be psi in docker-compose .yml
what to change in nginx.conf

and then what commands to use.

I am new to this work and I will be very glad if you can help

**Comment by dessalines** [comment]
> but now how to make it so that together what is written here lemmy was displayed.

> I want instructions with commands.

I don't know what you're asking.

**Comment by shveli96** [comment]
> > but now how to make it so that together what is written here lemmy was displayed.
> 
> > I want instructions with commands.
> 
> I don't know what you're asking.

https://i12bretro.github.io/tutorials/0583.html 
I want an instruction similar to this . 
this is a very good instruction, but it is old and does not work. I install Docker, docker-compose And after that I continued As written in the instructions but I can't add domain

**Comment by shveli96** [comment]
after using the commands
mkdir -p volumes / pictrs
sudo chown -R 991: 991 volumes / pictrs
what can i do how to add a domain?
from docker-compose.yml this will not be done

- LEMMY_INTERNAL_HOST = lemmy: 8536
- LEMMY_EXTERNAL_HOST = your-domain.com
- LEMMY_HTTPS = false

here change domain name to my domains
- LEMMY_INTERNAL_HOST = lemmy: 8536
- LEMMY_EXTERNAL_HOST = topix.ge
- LEMMY_HTTPS = false
and then run the command
sudo docker-compose up -d
does not cope with the task. opening a domain still does not work this domain site

**Comment by shveli96** [comment]
???????

**Comment by dessalines** [comment]
I don't know what the problem is. Have you set up a DNS A record pointing to your server IP?

I don't know where you found those instructions, because they aren't anywhere in our docs. Here are the official install instructions: https://join-lemmy.org/docs/en/administration/administration.html

If it still "doesn't work", you need to provide a your config files, as well as the docker logs.

**Comment by shveli96** [comment]
> If it still "doesn't work", you need to provide a your config files, as well as the docker logs.

are you a fool? write how the domain is added! i have installed and running on localhost: 1235 i want it to work on example.com domain. I do not know how to do this. 4 days already I am writing to you and waiting for you

**Comment by dessalines** [comment]
Not a good look to make demands and call me a fool when I'm telling you exactly what I need to help you. You'll have to find support elsewehere until you learn some manners.

**Comment by rishabh-modi2** [comment]
hi i am a noob can you please help me how you attached domain

**Comment by dessalines** [comment]
You mean how do you set a DNS A record? Look it up online, that has nothing to do with lemmy.
