### ISSUE TITLE
I want my site to be in one and the same language. 

### ISSUE THREAD

**Issue by ProjectMakerGeorgia** [LemmyNet/lemmy#2013]
I want my site to be in one and the same language in Georgian. How to do it? I don’t want the hassle of changing the language from the browser language

**Comment by Kradyz** [comment]
The languages are handled by the user interface ([LemmyNet/lemmy-ui](https://github.com/LemmyNet/lemmy-ui)).

The default behavior is to get the preferred language from the browser. This is managed by the file [lemmy-ui/src/shared/utils.ts](https://github.com/LemmyNet/lemmy-ui/blob/4c6713d3f2c1c29002add380950e85642fe90a18/src/shared/utils.ts).

In this file you should be able to change the default to behavior to displaying the user interface in Georgian by changing "browser" to "ka" in the following piece of the code:

```
// TODO
export function getLanguage(override?: string): string {
  let myUserInfo = UserService.Instance.myUserInfo;
  let lang =
    override ||
    (myUserInfo?.local_user_view.local_user.lang
      ? myUserInfo.local_user_view.local_user.lang
      : "browser");
```

You can then build a lemmy-ui docker image using this modified source code. This process is explained [here](https://join-lemmy.org/docs/en/client_development/custom_frontend.html).

**Comment by ProjectMakerGeorgia** [comment]
where is this file located?

**Comment by ProjectMakerGeorgia** [comment]
![image](https://user-images.githubusercontent.com/96426701/147494812-f9fb74ef-eaac-432a-8ca0-c1b21a5f6fd6.png)

**Comment by asonix** [comment]
The file is not present in a deployed version of lemmy. It must be edited before lemmy is compiled into the containers. If you want to change it, you will need to learn how to set up a lemmy development environment and build lemmy containers yourself.

**Comment by dessalines** [comment]
I'm not necessarily opposed to a setting enforcing a language, but lemmy is designed to always prefer user preferences over community or admin ones... so things like language and theme check their settings or browser preferences.

For someone more knowledgeable than me, is it common for browsers in OS's with non-english installs to come with a browser language preference still set as **en-US**?
