### ISSUE TITLE
`LemmyError { inner: {"error":"No slurs - "}` on docker

### ISSUE THREAD

**Issue by traverseda** [LemmyNet/lemmy#2021]
A few minor changes to the standard lemmy deploy, as I wanted to put the config file in a volume and run it under caddy.

[lemmyError.txt](https://github.com/LemmyNet/lemmy/files/7802829/lemmyError.txt)
[lemmyDocker.yaml.txt](https://github.com/LemmyNet/lemmy/files/7802833/lemmyDocker.yaml.txt)

I tried replacing the slurs regex in the config with `(a^)` as I thought it might be overzealous in the matching, and that did not seem to fix is. As an aside, I had a discussion with my little brother yesterday about how he wanted to r**ard the timing on his engine for some complicated turbo thing.

Not sure why I'm getting a "no slurs" error during setup. I presume it's not because I need to use more slurs?

**Comment by traverseda** [comment]
Just noticed I forgot the config.hjson, rest assured I'll be changing passwords once I've got this working.
[config.hjson.txt](https://github.com/LemmyNet/lemmy/files/7802912/config.hjson.txt)

Let me know if there's anything I can do to help, I can investigate more or even give you access to the portainer system this is running on if need be.

**Comment by dessalines** [comment]
I don't know anything about portainer, but try removing that slur filter field entirely.

**Comment by Nutomic** [comment]
Best use [/c/lemmy_support](https://lemmy.ml/c/lemmy_support) or [Matrix chat](https://matrix.to/#/#lemmy:matrix.org) for help.
