### ISSUE TITLE
Reorganize admin and mod API endpoint locations

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2022]
Currently we have admin ( and mod ) actions under a lot of different scopes, like :

- `POST site` (create a site)
- `POST community/mod` (add a mod to a community)
- `POST user/ban`

It *might* make sense to move these from their item scope, to a separate admin or mod scope. Not sure what's better.

#1927

**Comment by Nutomic** [comment]
Other endpoints to reorganize are `PasswordChange` and `ChangePassword`, as the names are very confusing.
