### ISSUE TITLE
i want to remove from frontend

### ISSUE THREAD

**Issue by ProjectMakerGeorgia** [LemmyNet/lemmy#2023]
![viber_image_2021-12-25_20-51-20-100](https://user-images.githubusercontent.com/96426701/148619734-4574a86b-8b67-42d7-8a45-fdc9fb933a12.jpg)

where is the code

**Comment by dessalines** [comment]
The front end code is here. What do you want to remove?

**Comment by dessalines** [comment]
You'll need to fork this code, build an image with the included dockerfile, and reference that image in your docker compose file.

**Comment by ProjectMakerGeorgia** [comment]
> You'll need to fork this code, build an image with the included dockerfile, and reference that image in your docker compose file.

how to do it ? I don't understand what you say

**Comment by ProjectMakerGeorgia** [comment]
How to edit frontend code

**Comment by ProjectMakerGeorgia** [comment]
I want to delete everything that is indicated in the picture

**Comment by dessalines** [comment]
This is probably not doable for you. You need to know some javascript, react, docker, and server administration to do this. Also you need to be able to follow my instructions.

**Comment by dessalines** [comment]
@ProjectMakerGeorgia how are you deploying / running lemmy? After you make changes to the front end, you need to build an image, and then deploy that image. If you don't know docker, you likely won't have the expertise to do this.

**Comment by ProjectMakerGeorgia** [comment]
> @ProjectMakerGeorgia how are you deploying / running lemmy? After you make changes to the front end, you need to build an image, and then deploy that image. If you don't know docker, you likely won't have the expertise to do this.

wget https://raw.githubusercontent.com/ProjectMakerGeorgia/lemmy/main/docker/prod/docker-compose.yml
wget https://raw.githubusercontent.com/ProjectMakerGeorgia/lemmy/main/docker/lemmy.hjson

docker-compose up -d
I changed the links of your github to mine everywhere on all repositories

**Comment by dessalines** [comment]
>  I changed the links of your github to mine everywhere on all repositories

That isn't how deploying works. You need to have some expertise in programming and docker which its clear you don't have.

```
 lemmy-ui:
    image: dessalines/lemmy-ui:0.14.3
```

That is our image, not a custom one. I cannot help you learn docker, you will have to do that on your own.
