### ISSUE TITLE
Failed to compile `lemmy_server v0.14.5` - error[E0659]: `Handler` is ambiguous

### ISSUE THREAD

**Issue by AbrakaDabraSK** [LemmyNet/lemmy#2025]
Compiling lemmy_websocket v0.14.5
error[E0659]: `Handler` is ambiguous (glob import vs glob import in the same module)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lemmy_websocket-0.14.5/src/routes.rs:90:6
   |
90 | impl Handler<WsMessage> for WsSession {
   |      ^^^^^^^ ambiguous name
   |
note: `Handler` could refer to the trait imported here
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lemmy_websocket-0.14.5/src/routes.rs:6:5
   |
6  | use actix::prelude::*;
   |     ^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `Handler` to disambiguate
note: `Handler` could also refer to the trait imported here
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lemmy_websocket-0.14.5/src/routes.rs:7:5
   |
7  | use actix_web::*;
   |     ^^^^^^^^^^^^
   = help: consider adding an explicit import of `Handler` to disambiguate

For more information about this error, try `rustc --explain E0659`.
error: failed to compile `lemmy_server v0.14.5`, intermediate artifacts can be found at `/usr/bin/`

Caused by:
  could not compile `lemmy_websocket` due to previous error

**Comment by dessalines** [comment]
Our docker builds are passing fine, which tells me you're using the wrong rust version. Check the dockerfiles in the prod and dev folders.

**Comment by Nutomic** [comment]
@AbrakaDabraSK How exactly are you compiling Lemmy?

**Comment by rscmbbng** [comment]
Might be that this solves your problem:
https://github.com/LemmyNet/lemmy-docs/pull/117/commits/215e93d273d8fa745cd279f4e3fb2dd45da9f942
