### ISSUE TITLE
Three strike system

### ISSUE THREAD

**Issue by ajr-dev** [LemmyNet/lemmy#2026]
To let users change their behavior it would be nice to implement a three strike system instead of the ban system. If a mod decides to ban every person who breaks the rules of their sub, most people wouldn't know what hits them, because they usually don't read the rules, and it would be to late to change their behavior. But if they get a strike they'll be more careful and read the rules before posting again. Also the mods wouldn't need to keep track of how many times a user has broken the rules.

**Comment by dessalines** [comment]
Temp bans will also be in the next release, so you could use that to put people in time out. It will show up in the modlog, so you can use that to remember. But I'd rather not create overly complicated rules and systems preventing bans. Usually a troll will break all three strikes within a few minutes anyway.

**Comment by Nutomic** [comment]
I dont think this would be flexible enough. In severe cases it might be necessary to ban after one warning, and in other cases a ban after three warnings might be too harsh (eg minor violations over a long time). 

A more flexible solution would be a built-in system for mods/admins to give warnings to users, which they can see on the user profile. Then they can decide on a case by case basis if a user should be banned. There is already an issue for adding such warnings.

**Comment by ajr-dev** [comment]
[Native support for warnings](https://github.com/LemmyNet/lemmy/issues/1424).
