### ISSUE TITLE
Had to clear cookies before opening lemmy.ml

### ISSUE THREAD

**Issue by felipeforte** [LemmyNet/lemmy#2030]
I wasn't able to enter lemmy.ml probably because of new methods for calling JSON cookies. Here's the error it returned:
`FetchError: invalid json response body at http://lemmy:8536/api/v3/site?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMxMzksImlzcyI6ImxlbW15Lm1sIiwiaWF0IjoxNjIzMDk1NTEzfQ.P_mzToWDb1D-nDa0YEEP1YjEKYK_vwAr55lJ2HuiBaU reason: Unexpected number in JSON at position 28`

I managed to fix this issue by clearing out browser cookies on lemmy.ml.

**Comment by felipeforte** [comment]
Closing issue, added solely for reference

**Comment by Nutomic** [comment]
You should change your password, otherwise that auth token can be used by anyone to log into your account.

**Comment by felipeforte** [comment]
> You should change your password, otherwise that auth token can be used by anyone to log into your account.

My goodness. I changed the password after reading this message, thanks for the heads up.
