### ISSUE TITLE
Deleted Posts already counted

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#2031]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

When i delete Postings from a community they are still counted

![grafik](https://user-images.githubusercontent.com/5894829/149020041-b87e4476-9e45-4c67-bdc7-476f3afa3fba.png)

I have a Testcommunity for some testing-purpose. And i deleted all my postings (you can see at the left red arrow), but they are still counted in the statistics... (see the right red arrow

### Steps to Reproduce

1. Create a new Community and post some postings there
2. Delete all the postings.
3. see statistics-block on the right of the community and the community-overview

### Technical details

I run lemmy 0.14.3 with docker on debian bullseye 11.2

**Comment by dessalines** [comment]
This probably has to do with the SQL trigger that updates that count.

**Comment by dessalines** [comment]
Yes, the SQL trigger is probably missing or not firing.

**Comment by rgroothuijsen** [comment]
I suspect the problem is that posts and comments are only soft-deleted in the database, which means that a DELETE trigger for either of them will never run.

**Comment by Nutomic** [comment]
Cant reproduce anymore.
