### ISSUE TITLE
Banned users can vote

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy#2033]
### Issue Summary

I can vote on banned users comments, but not on the direct descendants.  
![lemmy_ban_bug](https://user-images.githubusercontent.com/578515/149194487-c0ed6d97-cd0f-4725-9a5a-7bf0747d5cf6.png)

### Steps to Reproduce

1. Create three users: A, B, & C
2. Have user A, ban user B
3. Have user A make a comment
4. Have user C reply to the previous comment.
5. Have user B vote on both comments.

I expected the vote on comment A to fail, and the vote on comment C to work, but the opposite is true.

**Comment by LunaticHacker** [comment]
[this is the bug](https://github.com/LemmyNet/lemmy/blob/55bb68f6f9b4dd79e1072f4e507ba87aadd9bf9f/crates/api/src/comment.rs#L172) but it's better to remove this check entirely and  make this consistent with #1969
