### ISSUE TITLE
Personal-blocks undermine sublemmy moderation

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy#2036]
### Issue Summary

If I personally-block someone, I can't see their posts on subs I moderate, and therefore can't see that I need to ban them from the sub too!

### Steps to Reproduce

1. Create two users: A & B
1. Have user A create a sublemmy
1. Have user A personally-block user B
1. Have user B post or comment in user A sub
1. Try to view user B's comment from user A's perspective
1. Notice that user A cant see user B's comment and therefore cant delete it or realize they need to ban user B from the sub

### Technical details

I see three different resolutions:
1. do nothing, users will have to manually sub-ban users from all subs they moderate.
1. Ignore personal-blocks when querying subs that a user moderates, so they can see the banned users comments and therefore ban them  (maybe also include a UI feature to highlight comment).
1. Auto-ban users from subs when a mod personally-blocks a user, or becomes a mod. side-effect is block-lists should probably become public so mods know who will get banned when they promote another user to mod.

**Comment by Thann** [comment]
Perhaps, when some "spoiler" feature is implemented in the UI, we could use it to conceal the blocked perons

**Comment by Thann** [comment]
(Whoops)

**Comment by Nutomic** [comment]
Most communities should have more than one moderator, and it is unlikely that multiple mods have the same user blocked. There are also reports, and as long as those work fine for blocked users, i dont think there is a problem. 

What i would consider is to add a suggestion in lemmy-ui to add more mods to a community if there is only one.
