### ISSUE TITLE
[Activity Pub + Webfinger] user/community name collision

### ISSUE THREAD

**Issue by realaravinth** [LemmyNet/lemmy#2037]
### Issue Summary

When a user and a community share the same name, webfinger query groups both resources together, producing a single response:

```json
{
  "subject": "acct:cuzimbatman@lemmy.ml",
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://lemmy.ml/c/cuzimbatman"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://lemmy.ml/c/cuzimbatman"
    },
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://lemmy.ml/u/cuzimbatman"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://lemmy.ml/u/cuzimbatman"
    }
  ]
}
```
> Please note that there is a [community](https://lemmy.ml/c/cuzimbatman) and a [user](https://lemmy.ml/u/cuzimbatman) named `cuzimbatman` so there are four items in `links`. [Webfinger query](https://lemmy.ml/.well-known/webfinger?resource=acct:cuzimbatman@lemmy.ml).

I'm not sure how other activity pub servers choose which actor to contact but it looks like Mastodon is traversing in the reverse order(per the above linked webfinger response) and [choosing the user actor](https://mastodon.social/web/@cuzimbatman@lemmy.ml).

### Steps to Reproduce

1. create new user and create a community with same name
2. query webfinger for that user/community name
3. try to access both using other activity pub servers

**Comment by Nutomic** [comment]
Good find! In fact i intentionally put the community first so that it would be prioritize. You can make a PR to change the order [here](https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/webfinger.rs#L58).

**Comment by realaravinth** [comment]
This is a deficiency in Activity Pub, collisions are bound to haolen if various types of actors share the same namespace.

The GNU Social folks have proposed [FEP-2bca](htps://notabug.org/diogo/gnu-social/issues/267)
([socialhub discussion](https://socialhub.activitypub.rocks/t/decentralised-group/2200)) to address some of these issues, would the Lemmy team care to participate?

**Comment by Nutomic** [comment]
Webfinger works fine in Lemmy with identically named users/groups, as it goes through all of them and uses the one that has the expected type. Even Pleroma handles it fine, its just Mastodon thats causing trouble.

The FEP looks pretty complex, so i dont think we would implement it anytime soon.

**Comment by realaravinth** [comment]
I'm from [ForgeFlux](https://forgeflux.org), a project that's involved in implementing Activity Pub based federation for software forges. A micro-blogging program like Mastodon has no real use for Group actors but projects like ours do. I feel, being stakeholders we should represent our requirements and I'd be grateful for any inputs the Lemmy devs could provide.

As for implementing the spec, if the maintainers feel Lemmy could benefit from it, I'll gladly assist in it's implementation :)

**Comment by dessalines** [comment]
There are [5 different actor types in activitystreams](https://www.w3.org/TR/activitystreams-vocabulary/#actor-types), yet they all share the same namespace :frowning:

**Comment by realaravinth** [comment]
I've been loosing sleep over this. For all it's flexibility, activity pub is not flexible enough to make Groups first class citizens.

**Comment by Nutomic** [comment]
@realaravinth I suggest you open a new issue for discussing about groups compatibility. Alternatively we can chat on Matrix (@nutomic:matrix.org).

**Comment by Nutomic** [comment]
Actually our dev chat room would be better: #lemmydev:matrix.org

**Comment by silverpill** [comment]
@Nutomic 

>Webfinger works fine in Lemmy with identically named users/groups, as it goes through all of them and uses the one that has the expected type.

How Lemmy selects the actor? Webfinger query response doesn't contain any information about the actor type. It seems that the only way to find the specific actor is to fetch all objects with `rel=self` and then choose one with the requested type

**Comment by Nutomic** [comment]
> How Lemmy selects the actor? Webfinger query response doesn't contain any information about the actor type. It seems that the only way to find the specific actor is to fetch all objects with rel=self and then choose one with the requested type

That is exactly what we are doing. Its like this, Lemmy has one database table for communities and one for users. So the names are completely independent and cant collide. I had originally represented this as `https://lemmy.ml/.well-known/webfinger?resource=group:news@lemmy.ml` but other software wasnt compatible. Is there a better way to do this in webfinger?

**Comment by silverpill** [comment]
You can add some metadata to a link relation object. Webfinger spec says that members of the `links` array can have `properties`: https://datatracker.ietf.org/doc/html/rfc7033#section-4.4.4.5

>The "properties" object within the link relation object comprises zero or more name/value pairs whose names are URIs (referred to as "property identifiers") and whose values are strings or null. Properties are used to convey additional information about the link relation. 

But I'm not sure what property identifier should be used in this case. Perhaps we can refer to ActivityStreams namespace:

```json
{
  "subject": "acct:activitypub@lemmy.ml",
  "links": [
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://lemmy.ml/u/activitypub",
      "properties": {
        "https://www.w3.org/ns/activitystreams#type": "Person"
      }
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://lemmy.ml/c/activitypub",
      "properties": {
        "https://www.w3.org/ns/activitystreams#type": "Group"
      }
    }
  ]
}
```

**Comment by Nutomic** [comment]
Thanks, I will try that when i have time. It would at least make parsing easier for Lemmy, though it wouldnt help with Mastodon compatibility.

**Comment by Nutomic** [comment]
@silverpill Thank you for suggesting this solution :)
