### ISSUE TITLE
Community-List on small screens is awful

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#2038]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

On small screens (Smartphone) the overview of communities does not handle long names very well. See screenshot

![grafik](https://user-images.githubusercontent.com/5894829/149543853-538f3503-ffff-4d1d-8d74-189557b4df09.png)

### Technical details

Lemmy 0.15.1

**Comment by dessalines** [comment]
Wrong repo, and I made one here: https://github.com/LemmyNet/lemmy-ui/issues/546
