### ISSUE TITLE
Empty text field bodies should be trimmed and set to null if empty

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2039]
Occasionally browsers will set an empty space for text fields, which makes clients show an empty body. The back end should trim all optional text fields and do a replace with null if empty.

**Comment by Nutomic** [comment]
Could probably be done using deserialize_with, like here: https://github.com/LemmyNet/lemmy/pull/1962/files

**Comment by dessalines** [comment]
This is happening at the API level, when posts are getting inserted.
