### ISSUE TITLE
Problems getting Lemmy running

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2041]
What's the question you have about lemmy?

I installed it using Ansible. which gave a Play Recap as follows:

PLAY RECAP *********************************************************************
root@exploding-heads.com   : ok=12   changed=9    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0 

This is the task that it skipped:

TASK [check lemmy_base_dir] ****************************************************
skipping: [root@exploding-heads.com]

When I try and access Lemmy through the browser for first time, depending on the browser I either get:

Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

or 

This page isn’t workingexploding-heads.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

I have tried clearing my cookies.

Do you have any idea what I am doing wrong or what I should do next?

Thanks in advance

Kap

**Comment by dessalines** [comment]
Something is going on with the nginx on your system, searching for that error, it looks like its an SSL issue. Our ansible script sets up SSL certs for you, so my guess is you're on an old or outdated version of nginx.

**Comment by Nutomic** [comment]
Please use https://lemmy.ml/c/lemmy_support or https://matrix.to/#/#lemmy:matrix.org for support,
