### ISSUE TITLE
Can't read RSS to most of RSS reader

### ISSUE THREAD

**Issue by woodruffandtheschnibbleofazimuth** [LemmyNet/lemmy#2044]
### Issue Summary

RSS does not work on most of RSS reader

### Steps to Reproduce

1. Copy RSS link from any communities, like: https://lemmy.ml/feeds/c/opensource.xml?sort=Active
2. Paste on RSS reader like Newsblur and have an error: "There was a problem trying to add this site. Please try a different URL."

### Technical details
The problem is not for all the RSS reader but with a lot of them does not work.
[Feed Valitaion Service says](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flemmy.ml%2Ffeeds%2Fc%2Fopensource.xml%3Fsort%3DActive): This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

    line 57, column 221: Missing atom:link with rel="self" 

I have asked to the community and [they tell me](https://lemmy.ml/post/152505) it is a "know issue" but I can't find any issue on the repo so I hope this one.

I think fix this bug will help people try to follow communities, for example I would have liked to add an RSS feed to my Telegram group to entice people to use Lemmy instead of Reddit.

**Comment by dessalines** [comment]
I tried with two different RSS clients, and both worked fine. That tester also says the feed validated, and I doubt that rel=self would break readers, although it could be added.

**Comment by dessalines** [comment]
Newsblur looks like a US-hosted RSS site, meaning they're probably blocking the domain.

**Comment by woodruffandtheschnibbleofazimuth** [comment]
> I tried with two different RSS clients, and both worked fine. That tester also says the feed validated, and I doubt that rel=self would break readers, although it could be added.

Well, you are right! It's a Newsblur fault, thank you.
I will write to the author.
