### ISSUE TITLE
Notifications from users that have blocked you are impossible to dismiss

### ISSUE THREAD

**Issue by LongJohn-Silver** [LemmyNet/lemmy#2045]
### Issue Summary

You are user 1 and you make comment A, then user 2 makes comment B, and after reading comment A decides they want to block you. Now user 1 can't dismiss the notification produced by user 2 making comment B.

### Steps to Reproduce

1. Get a notification from a user
2. Said user blocks you
3. You get an impossible to dismiss notification

### Technical details

N/A

**Comment by dessalines** [comment]
Ooh yeah this seems pretty serious, it might not let you mark the message as read. That's what you're referring to by *notification* right?

**Comment by LongJohn-Silver** [comment]
Yeah, it's quite annoying. Well, it's not a message, I don't know how Lemmy back end treats everything but it's not a direct message, but rather a reply which would be a comment, although I assume the same should happen if this were a message.

**Comment by Nutomic** [comment]
This is in the inbox? I tested this locally, and i can dismiss comment notifications from a user that blocked me without any problems (using link button or checkmark button under the notification).

**Comment by LongJohn-Silver** [comment]
Yes, I tried using the chain icon, and tick icon and nothing works. I just noticed it tells me "You have been banned from this community", so maybe the user didn't block me, but rather the community and the bug lies there.

**Comment by Nutomic** [comment]
Ah yes you are right, there is no reason to check for a ban when marking a comment as read.
