### ISSUE TITLE
Cannot log-in to Lemmy site via iOS device

### ISSUE THREAD

**Issue by SukinoSenze** [LemmyNet/lemmy#2058]
### Issue Summary
Cannot log in to Lemmy (try with lemmy.ml) via an iOS device.
Screenshot -> https://i.ibb.co/ZdpZKPP/IMG-5013.jpg

### Steps to Reproduce
1. Open `lemmy.ml` site via any browser on your iOS 15 device (I try with iPhone 13).
2. Try to log in with your own credential.
3. Got an "Unknown" error message.

### Technical details
- iOS 15.2.1
- Safari, Firefox, and Brave experienced the same issue, probably related to WebKit.

**Comment by dessalines** [comment]
I don't have an iOS device, so its tough for me to verify / test. Try creating an account with a simple password on https://ds9.lemmy.ml/ , to make sure the password length / complication isn't an issue. I know also some people had some issues with password filling tools on iOS, but I'm not sure how to make sure that's turned off.

**Comment by SukinoSenze** [comment]
@dessalines thanks for bringing up the password manager topic. I just try to copy-paste the password without filling it with password management (Bitwarden) and it works!

So, it's must be an issue with password-filling tools instead. 😂
