### ISSUE TITLE
Troll attacks

### ISSUE THREAD

**Issue by DonPicciotto** [LemmyNet/lemmy#2059]
I'm sorry if this is not the right place, but imho this need to be addressed as a technical issue too. We really need a way to address and block those troll attacks. The attacks happened yesterday and today aren't supposed to be a daily thing. Please, this should be the top priority now, otherwise I really think lemmy couldn't survive. Maybe just block new subscription until someone find a solution

**Comment by dessalines** [comment]
https://lemmy.ml/post/159922

We have several methods to stop trolls that came with the `0.15.0` release, in addition to the strong mod tools (like ban and remove all content) that we already have had for a while. That includes:

- Requiring email verifications
- Required registration applications
- Closing signups

We recently turned on registration applications for lemmy.ml, and encourage other instances to do the same.

If there's other specific features / ideas to stop trolling, open them up as their own issues.
