### ISSUE TITLE
I want to make changes to the site

### ISSUE THREAD

**Issue by ProjectMakerGeorgia** [LemmyNet/lemmy#2060]
I MISS DELETE FROM SITE THIS LINKS:
------
https://join-lemmy.org/donate
https://join-lemmy.org/docs/en/about/guide.html#sorting
https://join-lemmy.org/
https://github.com/LemmyNet
https://join-lemmy.org/docs/en/index.html
AND TEXT BE: 0.14.3.
![Untitled](https://user-images.githubusercontent.com/96426701/150964916-112b5a67-3332-4fcc-99cd-c30114d89b4b.png)

-----
I downloaded all the repositories and changed the links that were sent to your repositories. deleted everywhere where these tapes were used ideally as it should and did. I wanted to set the main language to Georgian changed in the place of the browser wrote ka . I added all this to my git and installed from there https://github.com/ProjectMakerGeorgia/ . why hasn't anything changed?

**Comment by dessalines** [comment]
Duplicate of #2023
