### ISSUE TITLE
[Feature request] Block mail domain from register

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy#2061]
There are well-known domains, such as trashmail.com, that one would like to exclude from registration because they are often used by trolls and spammers.  
Likewise, it might be possible to lock out many trash mail providers with this.

**Comment by dessalines** [comment]
This would probably have to be an optional list in the config.hjson . I don't have time to do this anytime soon, but anyone feel free to do a PR.

**Comment by rgroothuijsen** [comment]
@dessalines Given that a lot of settings have been moved into database tables recently, would this new list of blocked e-mail domains likewise become a table?

**Comment by dessalines** [comment]
It could yes, although if you are trying to use this as a signup-spam prevention method, its still not going to be as good as registration applications.

**Comment by Nutomic** [comment]
On the other hand, a list of allowed email domains could be very useful. Would make it possible to allow signups only from your organization. Of course email verification should be mandatory then.

**Comment by Nutomic** [comment]
Looks like this can be done using [LemmyAutomod](https://github.com/RikudouSage/LemmyAutomod?tab=readme-ov-file#4-add-rules-to-database).
