### ISSUE TITLE
Multiple default communities

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy#2068]
Currently, new users are automatically subscribed to a single default community when they sign up. Instead, users should be auto-subscribed to a list of default communities. This will allow for multiple general communities (i.e. c/announcements and c/askchapo), similar to how Reddit works.

**Comment by dessalines** [comment]
The easiest way would be to add a boolean column on the community table.

**Comment by Nutomic** [comment]
Alternatively it could be defined in the config file.

**Comment by SamWhited** [comment]
Currently new admins get added to the main community as mods. Would we want this to be the same for all default communities, or is main special?

**Comment by dessalines** [comment]
It could... but its kind of a moot point too, because admins have full powers over every community anyway.

**Comment by SamWhited** [comment]
Do they? I don't see a way to edit a communities description and sidebar as an admin, for example. It does seem like this is a thing admins should be able to do though, and from the API maybe it is, but at least in the UI I don't seem to be able to do it.

**Comment by dessalines** [comment]
Yes they can't edit communities, but they can remove them.

**Comment by Nutomic** [comment]
There are no more default communities in 0.17, instead users see the local timeline by default. So this issue isnt relevant anymore.
