### ISSUE TITLE
Ability for admins to hide communities from the default main feed

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy#2072]
Ideally users should not see the most controversial communities in their default feed.

In Hexbear this is implemented as an option in community settings:

![](https://www.hexbear.net/pictrs/image/Y1p3rlvC5p.png)

**Comment by Nutomic** [comment]
Already wip in https://github.com/LemmyNet/lemmy/pull/2055

**Comment by not-layla** [comment]
Ah, thank you. I'll close this issue in favour of that PR :pray:
