### ISSUE TITLE
Sitewide taglines

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy#2074]
See https://github.com/LemmyNet/lemmy-ui/issues/556

~~Taglines should be specified in the config file.~~ (See below)

**Comment by dessalines** [comment]
Not the config file, but as another database table, with API actions to add / edit / delete them. Otherwise admins wouldn't be able to edit these via the site.

**Comment by not-layla** [comment]
If they were defined in the config file, couldn't they change them via the site in `Admin Settings -> Site Configuration`? I had a go implementing it that way and it looked like this:

![](https://www.hexbear.net/pictrs/image/ZpU1C2TNVw.png)

**Comment by dessalines** [comment]
Couple things:

- Unfortunately saving that no longer works as a hot reload, and requires a server reboot.
- If there were more of me, I'd work to take nearly everything in that config.hjson apart from what docker requires, and put it into the `site` or other tables. Going forward I definitely don't want to add more to that config.
- You can see on the left side of that page are a bunch of site-related settings already, so these taglines would go under that.
- I know it takes more work, (adding tables, joins, and more UI), but having API actions is muuuch preferred to putting things in that startup config file because its easier.

**Comment by Nutomic** [comment]
I disagree about putting everything in the database, particularly when we are talking about minor gimmicks like these taglines. Not only is it more work to implement, its also more work to maintain (and we have to maintain it forever). These taglines would probably be set once when the instance is installed, and then changed very rarely, if ever. So its really not worth all the extra effort.

I didnt know that config changes require a Lemmy restart now, if thats a problem we can fix it.

**Comment by not-layla** [comment]
[I had a quick go](https://github.com/hexbear-collective/lemmy/commit/b876b743591b996e5a8b986ad577fd0eb0074104) implementing them (WIP), it is indeed a lot more effort but yeah Hexbear for example has a lot of admins/sitemods but very few server admins, and since only server admins can change taglines etc they're never changed. The less technical it is to maintain an instance the better

**Comment by makotech222** [comment]
Starting to pick this one up now. General plan (based on layla's branch) for backend changes
- New table, 'taglines'
- New endpoints for GET(One), GET(All), PUT, POST of taglines
- Only admins can do GET(All), PUT, POST
- Update GetSite endpoints to pull a random tagline

Does this plan seem okay?

**Comment by dessalines** [comment]
Yep that seems good. The only other thing I could think of is to possibly add a `lang_id` column (to only show taglines for your lang) , but imo that's overkill, unless nutomic thinks that should be done.

**Comment by dessalines** [comment]
@not-layla what's the status of these hexbear tagged issues?

**Comment by not-layla** [comment]
@dessalines There's no active development from our side right now, unfortunately. Is it cool to keep them open, until that changes?

**Comment by dessalines** [comment]
Sure no probs, was just checking in cause its been a while with nothing done.
