### ISSUE TITLE
Allow admins and mods to lock answered posts to avoid deletion.

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [LemmyNet/lemmy#2083]
There are some instances that may want to archive all posts, like in case of a q/a instance.

Admins could choose to lock answered posts instance wide, for either deletion or editing. Or they could give the permission of choosing in a per community basis to the mods.

**Comment by dessalines** [comment]
We don't have the concept of answered posts, nor do we have any type of mass database deletion other than a user deleting their own content. 

And admins and mods can already lock posts.
