### ISSUE TITLE
All of these port binds are unnecessary.

### ISSUE THREAD

**Issue by Leopere** [LemmyNet/lemmy#2086]
https://github.com/LemmyNet/lemmy/blob/6b1894faf062532a107f91527ae7a6a214e1ee32/docker/prod/docker-compose.yml#L17-L18 

There's intra-compose stack networking by default.

**Comment by Leopere** [comment]
https://github.com/LemmyNet/lemmy/blob/6b1894faf062532a107f91527ae7a6a214e1ee32/docker/prod/docker-compose.yml#L42-L44

Also these and

https://github.com/LemmyNet/lemmy/blob/6b1894faf062532a107f91527ae7a6a214e1ee32/docker/prod/docker-compose.yml#L30-L31

binding port 1235 should be on port 80 without `127.0.0.1:` OR have some kind of reverse proxy and omit the full ports: directive. 

This may be completely off target from what you intend but just saves on complexity and redundancy and port binds that just decrease security through unnecessary binds to the hosts localhost interface.

**Comment by dessalines** [comment]
If you want to do a PR for removing these, that'd be welcome. The `dev/docker-compose.yml` is more used tho, the prod docker compose could probably be deleted altogether.
