### ISSUE TITLE
Can't create a post with a https://www.cbc.ca url

### ISSUE THREAD

**Issue by smorks** [LemmyNet/lemmy#2089]
### Issue Summary

Can't create posts with a https://www.cbc.ca/ url.

### Steps to Reproduce

I've tested this on both lemmy.ca and lemmy.ml

1. Click "Create a post" button in a community
2. Enter any url to an article from https://www.cbc.ca/, for example: https://www.cbc.ca/sports/olympics/winter/hockey/beijing-olympic-womens-hockey-world-playing-catch-up-canada-us-1.6341266
3. Click "Create". The button will just spin.

### Technical details

I believe this is the relevant line from the logs. i don't see any other errors?

```
lemmy-lemmy-1  | 2022-02-06T03:33:24.347547Z  INFO Websocket Request{trace_id=00000000000000000000000000000000}:perform{self=CreatePost { name: "testing 1 2 3", community_id: CommunityId(3), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("www.cbc.ca")), port: None, path: "/sports/olympics/winter/hockey/beijing-olympic-womens-hockey-world-playing-catch-up-canada-us-1.6341266", query: None, fragment: None }), body: None, honeypot: None, nsfw: Some(false), auth: Sensitive }}:fetch_site_data:fetch_site_metadata: lemmy_utils::request: Fetching site metadata for url: https://www.cbc.ca/sports/olympics/winter/hockey/beijing-olympic-womens-hockey-world-playing-catch-up-canada-us-1.6341266
```

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
* What OS are you trying to install lemmy on? arch linux using docker
* Any browser console errors? no

I'm a new lemmy admin, so let me know if you need any more info. Maybe this is something broken on the cbc website itself?

**Comment by dessalines** [comment]
The HTML tokenizer that's required for fetching the site metadata is failing on that site, not sure why: https://enterprise.lemmy.ml/api/v3/post/site_metadata?url=https%3A%2F%2Fwww.cbc.ca%2Fsports%2Folympics%2Fwinter%2Fhockey%2Fbeijing-olympic-womens-hockey-world-playing-catch-up-canada-us-1.6341266

Looks like we're not the only one who has problems with that site: https://opengraphcheck.com/result.php?url=https%3A%2F%2Fwww.cbc.ca%2Fsports%2Folympics%2Fwinter%2Fhockey%2Fbeijing-olympic-womens-hockey-world-playing-catch-up-canada-us-1.6341266

Maybe they're blocking certain domains, checking browser agent, having circular references....no idea.

**Comment by Nutomic** [comment]
If it fails to fetch metadata, that should just be ignored and the link left with empty metadata. It shouldnt prevent the link from being posted.

**Comment by smorks** [comment]
thanks for looking into this, and thanks for all the work you've done on lemmy!
