### ISSUE TITLE
NSFW communities cannot be searched for in the create post section (NSFW communities are effectively broken)

### ISSUE THREAD

**Issue by bigOconstant** [LemmyNet/lemmy#2103]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

NSFW communities cannot be found in the community drop down in the create post menu. When using mobile this makes posting to them impossible. 

### Steps to Reproduce

1. Create a community and label it as nsfw
2. Click away from that community to the all or local tab.
3. Click Create Post in the top menu
4. Try to search up the community in the community Drop down.
5. Notice that you can't find it. Its a bug.

**Comment by dessalines** [comment]
Yep I'm aware of this bug. Will probably be a while till I can get to it. In the meantime, you can navigate to the NSFW community, then click create post.

**Comment by dayinjing** [comment]
> Yep I'm aware of this bug. Will probably be a while till I can get to it. In the meantime, you can navigate to the NSFW community, then click create post.

I am seeing this issue as well. On mobile you can't click create post from the community and the community be auto filled. Which is another bug I guess.

**Comment by dayinjing** [comment]
My idea of a fix https://github.com/LemmyNet/lemmy/pull/2105
