### ISSUE TITLE
Open Telemetry issue when installing with Docker

### ISSUE THREAD

**Issue by nothing2obvi** [LemmyNet/lemmy#2125]
Hello,

I'm not particularly knowledgeable at Linux in general, but am fairly comfortable with Docker. Whenever I try to run lemmy on an Ubuntu VPS server I have, I get this error:

```
OpenTelemetry trace error occurred. Exporter otlp encountered the following error(s): the grpc server returns error Unknown error
```

I've tried running it on Docker Desktop on my Mac and it works perfectly.

Any advice for a noob? Thanks!

**Comment by Nutomic** [comment]
Are you trying to use tracing with OpenTelemetry? If not, you can just ignore that.
