### ISSUE TITLE
Help setting up behind reverse proxy using Linuxserver.io's "SWAG" container.

### ISSUE THREAD

**Issue by nothing2obvi** [LemmyNet/lemmy#2126]
Hello,

I'm no expert. I was able to get Lemmy up and running using Docker, but I can only access it using my server's IP address and the port (e.g. "192.xxx.xxx.xxx:1235"). I'm comfortable using [Linuxserver's SWAG](https://github.com/linuxserver/docker-swag) container because it has reverse proxy .conf templates for several of their containers. See [this repo](https://github.com/linuxserver/reverse-proxy-confs).

Below is a a standard template they use. I used this file, named it "lemmy.subdomain.conf," and now at "lemmy.mydomain.name" I can access the UI, but cannot login. Could anyone provide any help as to how to set up Lemmy using this template? Thanks a lot.

```
## Version 2021/05/18
# REMOVE THIS LINE BEFORE SUBMITTING: The structure of the file (all of the existing lines) should be kept as close as possible to this template.
# REMOVE THIS LINE BEFORE SUBMITTING: Look through this file for <tags> and replace them. Review other sample files to see how things are done.
# REMOVE THIS LINE BEFORE SUBMITTING: The comment lines at the top of the file (below this line) should explain any prerequisites for using the proxy such as DNS or app settings.
# make sure that your dns has a cname set for lemmy and that your lemmy container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name lemmy.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app lemmy;
        set $upstream_port 1234;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
    }

    # REMOVE THIS LINE BEFORE SUBMITTING: Some proxies require one or more additional location blocks for things like API or RPC endpoints.
    # REMOVE THIS LINE BEFORE SUBMITTING: If the proxy you are making a sample for does not require an additional location block please remove the commented out section below.
    # location ~ (/lemmy)?/api {
    #     include /config/nginx/proxy.conf;
    #     include /config/nginx/resolver.conf;
    #     set $upstream_app lemmy;
    #     set $upstream_port 8080;
    #     set $upstream_proto http;
    #     proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    #
    #     # REMOVE THIS LINE BEFORE SUBMITTING: Additional proxy settings such as headers go below this line, leave the blank line above.
    # }
}
```

**Comment by Nutomic** [comment]
The easiest option is to follow [our instructions](https://join-lemmy.org/docs/en/administration/install_docker.html), which use a native nginx installation. 

Otherwise you can simply take the [nginx config](https://github.com/LemmyNet/lemmy-ansible/blob/main/templates/nginx.conf) from that setup, and adjust the ports. It configures a couple of things so the basic nginx config you have now will not work.

**Comment by dessalines** [comment]
I don't know whether to keep these type issues open or not. On the one hand someone might stumble on them and be able to help, but on the other, we're not going to provide support for every single install method people come up with.

**Comment by Nutomic** [comment]
Yes we can close it, people can still find it in that case.

Anyway [/c/lemmy_support](https://lemmy.ml/c/lemmy_support) is the better place for this.

**Comment by nothing2obvi** [comment]
Totally fair! Either way I think it would be helpful to stumble upon this question. Thanks.
