### ISSUE TITLE
Feature Request: Show number of unread comments

### ISSUE THREAD

**Issue by ElDifinitivo** [LemmyNet/lemmy#2134]
One of my favorite features of lemmy is the ability to sort posts by new comments, something I've been missing from the classic forums. I think that sorting method would be more useful with the addition of also showing the number of new comments since the last time you viewed that thread.

Dessalines had said this would involve some DB changes so I'm putting the request here instead of at [https://github.com/LemmyNet/lemmy-ui](lemmy-ui), but I envision it similar to how Slide for Reddit shows it, with a `(+N)` next to the total comments of the post `X comments (+Y)`

**Comment by dessalines** [comment]
I'm down for adding this, as long as a post viewed sets all comments as viewed ( IE not mess around with watching screen position or anything ).
