### ISSUE TITLE
What does the parameter(check_only) mean in the check_rate_limit_full function?

### ISSUE THREAD

**Issue by goldwind-ting** [LemmyNet/lemmy#2136]
```rust
pub(super) fn check_rate_limit_full(
    &mut self,
    type_: RateLimitType,
    ip: &IpAddr,
    rate: i32,
    per: i32,
    check_only: bool,
  )
```
when I read the source code, I found if `check_only` is equal to `true`, the allowance inside `RateLimiter` keeps increasing, and it will never be less than `1.0`, so how does it achieve `rate limit`? code is [here](https://github.com/LemmyNet/lemmy/blob/166ec196b02d82115ab178588604f4a780d0c135/crates/utils/src/rate_limit/rate_limiter.rs#L93)

**Comment by Nutomic** [comment]
Would be good to add that link to the code (or documentation).
