### ISSUE TITLE
Persistently store activity queue tasks

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2142]
In case that Lemmy fails to send an outgoing activity for some reason, the send is retried multiple times over the next minutes/hours. These retries are only stored in memory, meaning that if Lemmy is restarted, they are completely discarded. It would be good if we could store these tasks persistently in the database, so that they can be restored on start.

This would require implementing [background_jobs_core](https://docs.rs/background-jobs-core/0.12.0/background_jobs_core/index.html)::[Storage](https://docs.rs/background-jobs-core/0.12.0/background_jobs_core/trait.Storage.html#) for Postgres, or using [background_jobs_sled_storage](https://docs.rs/background-jobs-sled-storage/0.9.1/background_jobs_sled_storage/).

As most Lemmy instances are running permanently, and only restart every few weeks for updates, this is rather low priority.

**Comment by asonix** [comment]
fwiw I think a postgres backend would be preferable for lemmy, since it already has a postgres dependency

**Comment by Nutomic** [comment]
[Upstream issue](https://github.com/LemmyNet/activitypub-federation-rust/issues/31)

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3605
