### ISSUE TITLE
RUST_LOG being completely ignored.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2155]
I have `RUST_LOG=OFF` in the docker-compose.yml file, yet it's logging every DEBUG and INFO message. @asonix do you know what might be happening?

**Comment by Nutomic** [comment]
Sounds like this issue: https://github.com/tokio-rs/tracing/issues/1697

**Comment by dessalines** [comment]
Was just me not running docker-compose up -d
