### ISSUE TITLE
Add support for Scalable Vector Graphics (SVG).

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [LemmyNet/lemmy#2156]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

Yes. 

[Bitmap formats](https://wikipedia.org/wiki/Raster_graphics): GIF, PNG, and JPEG, are supported; but there are no [vector formats](https://wikipedia.org/wiki/Vector_graphics) supported, like [SVG](https://wikipedia.org/wiki/Scalable_Vector_Graphics).

Vector Graphics are popular with iconography and vexillography.

### Describe the solution you'd like

Allow SVG as a picture format.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

None.

**Comment by WhyIsEvery4thYearAlwaysBad** [comment]
Ok.

It's always possible to post the SVG source code and achieve the same effect.

**Comment by db0** [comment]
I want to use the .svg as a emojis, so posting the source every time won't work very well.

I asked the pict-rs developer to support this but it's very low on their priorities

**Comment by db0** [comment]
I did manage a workaround by hosting the image elsewhere and then putting the link in the emoji field: https://lemmy.dbzer0.com/comment/615979

but not everyone has an external host

**Comment by Nutomic** [comment]
See https://git.asonix.dog/asonix/pict-rs/issues/11
