### ISSUE TITLE
tls_type should *not* be required in the config

### ISSUE THREAD

**Issue by rysiekpl** [LemmyNet/lemmy#2168]
### Issue Summary

Seems like lemmy `0.16.x` *requires* `tls_type` in `config.hjson` (`email` section), even if `use_tls` is set to `false`).

Error in the logs:
> thread 'main' panicked at 'Couldn't initialize settings.: Lemmy Error { message: None, inner: "missing field `tls_type`" near 29:3, context: "SpanTrace" }', src/main.rs:52:35

### Steps to Reproduce

1. update from 0.15.4
2. observe that the `lemmy` container is `restarting`
3. check logs (`docker-compose logs -f lemmy`), see error message

Adding `tls_type: none` to the `email` section of the config file fixes the problem. The example config file does *not* contain the `tls_type` option in the `email` section either. I have not tested if the example file works.

**Comment by Nutomic** [comment]
The `use_tls` field doesnt exist anymore, it was completely replaced by `tls_type`.

**Comment by rysiekpl** [comment]
Ah, interesting. Thanks!
