### ISSUE TITLE
How do we see stats like web page views

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2185]
What's the question you have about lemmy?

Once we have our instance up and running, how do we see stats like web page views to see how many people are visiting the site (even if they do not sign in) and where the traffic is coming from etc?

**Comment by Nutomic** [comment]
There are no such stats. You can setup an external tool (for example [Plausible](https://plausible.io/)) to collect statistics.

**Comment by dessalines** [comment]
Yep, any bundling of statistics, you'll have to include manually. We aren't going to bundle anything like that into lemmy.
