### ISSUE TITLE
is it possible to install a *private* lemmy on aws?

### ISSUE THREAD

**Issue by suddenlyfleck** [LemmyNet/lemmy#2186]
What's the question you have about lemmy?
Intended for corporate use: We don't want to loose secrets.

Is this easily possible?

Or what is recommended best practice?

thanks :)

**Comment by Nutomic** [comment]
There is an option "Private Instance", which allows only logged in users to view the content. You can use it together with "registration applications", so that all new accounts need to be approved by admins. Note that if "private instance" feature is enabled, federation will not work.

**Comment by dessalines** [comment]
Also, we don't support AWS-specific instructions, just docker or ansible. [Here's the install guide.](https://join-lemmy.org/docs/en/administration/administration.html)
