### ISSUE TITLE
Add email verification

### ISSUE THREAD

**Issue by mlaunois** [LemmyNet/lemmy#219]
Can you add email verification in Lemmy?

I want to make the email address verification **required** for all new users to prevent bulk account creation and spam through multiple accounts.

https://git.radicallyopensecurity.com/nlnet/off-ngid-lemmy/-/issues/28

**Comment by dessalines** [comment]
I'm not really sure whether to do this one, or the one suggested in #209 , which I like a little better. It's fairly easy to make spam email accounts through different services, so I'm kinda preferring that one.
