### ISSUE TITLE
Give user reason for their application being denied

### ISSUE THREAD

**Issue by DShiller** [LemmyNet/lemmy#2191]
When a user sends an application to create a new account and their application is rejected, admins are able to give a deny reason. However that reason is not relayed to the user. It should be sent to them either by email or, preferably since email is optional, it should put that in the error message when they try to log in:

![image](https://user-images.githubusercontent.com/38543836/161624583-60d1e4d2-e2ca-4629-81c5-0666be056e10.png)

"Registration application denied. Reason given: [blahblah]"

**Comment by dessalines** [comment]
@Nutomic I think this is probably a good idea, although I wouldn't want to add it without your input. It would require changing [this static error string](https://github.com/LemmyNet/lemmy/blob/dfb0938738a5f85834654498d0b0969698eb1dae/crates/utils/src/lib.rs#L58) to non-static.

**Comment by Nutomic** [comment]
I believe the deny reason is already sent out over email, no? In any case, it makes sense to indicate to the user why it was rejected.
