### ISSUE TITLE
Personal Keyword Filtering

### ISSUE THREAD

**Issue by TheCoolZone** [LemmyNet/lemmy#2202]
I talked to Dess about this a while ago. A feature found on Twitter and Mastodon that Lemmy doesn't have yet is personal word filters, ie: automatically hiding posts with specific keywords in them. For Masto users, this allows them to browse without having to see triggering content or political content that turns them off using the site (some are just in it for culture stuff).

Usually it's considered the responsibility of the poster to CW their own work, but often this isn't done to a degree that is satisfactory for people sensitive to that sort of thing. Keyword filters would simultaneously allow them to avoid the act of seeing the post itself and the drama of making metaposts in reaction to it.

This would probably be found on the same page as the user-block lists in the UI.

**Comment by dessalines** [comment]
This would be doable, as long as its limited to post titles only. Feel free to take a crack at it.
