### ISSUE TITLE
Display sidebar of remote instance

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2208]
The sidebar and other metadata of federated instances is also being stored in the database in `Site` table (https://github.com/LemmyNet/lemmy/pull/1798). It would be good if we could expose it through the API, and display the instance sidebar to users when browsing a remote community. It would allow users to understand that there are different rules than the ones of their own instance.

**Comment by dessalines** [comment]
Not totally sure the best way this would be displayed, except as an expandable thing.

**Comment by Nutomic** [comment]
I was thinking to show it as an overlay window the first time you view a community from that instance. Of course thats complicated because we have to track which instances each user has viewed. 

Otherwise, just put it below the community sidebar? In most cases those arent very long, so it should be easy to see.
