### ISSUE TITLE
Many videos not embed / Line wrapping

### ISSUE THREAD

**Issue by soverxxx** [LemmyNet/lemmy#2219]
Many videos like
`<iframe width="1280" height="720" src="https://www.youtube.com/embed/BGlWbVc4BAw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
`<iframe width="1280" height="716" src="https://www.youtube.com/embed/3fy5_lMdbj0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
Cant be embed to any Lemmy federation, is give me  error "Video is not available. View on YouTube." 
But this videos can be embedded on any sites. It seems the problem is in lemmy, but it is not clear how to solve it.

**Comment by soverxxx** [comment]
And one more moment..
WhenI'm trying to start from a new line in the editor.
Like for example now. After publication, the new line is glued together with the previous one as its continuation.

And the only option is to make a new line, exclusively with a double press of "enter" - like this sentence.
It makes me sad.

**Comment by soverxxx** [comment]
And it would be cool to be able to skip a few lines.



Like here.

**Comment by dessalines** [comment]
In Commonmark markdown, you need two lines to for a new one, which you can already do.

And although there is some html support for the markdown parser, I'm surprised that Iframe works at all. I'd have to inspect why it allows that embed to work.

**Comment by soverxxx** [comment]
Do you want to remove video embedding?
Don't do it, it's a cool thing!

But I don't understand the problem when videos are embedded with an error. It would be cool to fix the errors.

**Comment by soverxxx** [comment]
> In Commonmark markdown, you need two lines to for a new one, which you can already do.
> 
> And although there is some html support for the markdown parser, I'm surprised that Iframe works at all. I'd have to inspect why it allows that embed to work.

Do you want to remove video embedding?
Don't do it, it's a cool thing!

But I don't understand the problem when videos are embedded with an error. It would be cool to fix the errors.

**Comment by dessalines** [comment]
Its a security issue to allow external content of any kind, it could run unwanted javascript. We may allow it as a setting at some point.

**Comment by soverxxx** [comment]
> Its a security issue to allow external content of any kind, it could run unwanted javascript, expose IPs, etc. We may allow it as a setting at some point.

I just don't quite understand why it works that way :D

In fact, it's the same iframe code from YouTube every time, the difference is only in the link characters after "youtube.com ". Strange things.

**Comment by dessalines** [comment]
This is moot now that we are turning off html in markdown.
