### ISSUE TITLE
Add instance software and version info

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2222]
Re: https://lemmy.ml/instances

The instances listed here are more then just Lemmy instances and it becomes confusing. Why not sort them by type? e.g.
Lemmy
Friendica
Peertube
etc

**Comment by dessalines** [comment]
We don't store the type, and I'm also not sure why this would be useful anyway. What's the use case for needing to know the type?

**Comment by Kap2022** [comment]
It is not that important - it was just a frustration I experience while looking through the available instances. I thought if you were doing work in that area, maybe it is something you could tidy up at that time.

If I have not said it before, thanks for all the hard work your team is doing. Lemmy is great.

**Comment by dessalines** [comment]
@Nutomic now that we have an instance table, do you think it'd be useful at all to store the software and maybe version from `nodeinfo` ?

**Comment by Nutomic** [comment]
I wont stop you from implementing it. Just want to clear some of these low priority issues which will be ignored forever, and might catch some false positives.
