### ISSUE TITLE
Federating with Mastodon - Don't boost comments

### ISSUE THREAD

**Issue by UserThre3** [LemmyNet/lemmy#2224]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

When I subscribe to a community through Mastodon, from my end the community is seen to boosts all new posts and it's working as expected.

When a Lemmy user comments on the post, the community boosts the individual comment as well. From my testing, all comments are already attached to the original post/boost as AP comments, so this comment boost seems unnecessary and is confusing.

### Describe the solution you'd like

Don't "boost" the comments in the same way as posts. Unless there's a technical reason for it, I'd prefer to see a Lemmy post as a Mastodon post/boost and Lemmy comments as comments to the mentioned Mastodon post/boost.

### Describe alternatives you've considered

Not federate with Lemmy-instances from Mastodon and instead create a unique user on a Lemmy instance. Seems counter to the federation idea.

**Comment by Nutomic** [comment]
The way following a Lemmy community from Mastodon works is like this. Mastodon doesnt support the `Announce/Create/Page` or similar activities used by Lemmy, so we send a specific `Announce/Page` activity for Mastodon compatibility. This is only done for posts, not comments. 

If you see comments boosted from Lemmy, my best guess is that Mastodon recently added support for `Announce/Create/Note` activities. Did you notice this after a Mastodon upgrade, or is your instance maybe running a Mastodon fork?

**Comment by UserThre3** [comment]
It's a newly created instance running regular Mastodon 3.5.1, so not sure when the change happened.

If it's relevant, I read that 3.5 (introduced at the start of april) introduced post editing, but it broke some backwards compatibility.

**Comment by Nutomic** [comment]
@clearlyclaire Do you know anything about this?

**Comment by ClearlyClaire** [comment]
Mastodon 3.5.0 added initial support for post editing (the interface to actually edit posts is not enabled yet, to give time to instances to update to compatible versions). I cannot recall any compatibility breakage.

I'm not sure what you mean by `Announce/Create/Note`, care to elaborate how Lenny behaves regarding to comments?

**Comment by Nutomic** [comment]
In Lemmy, groups send actions to their followers simply by wrapping them in `Announce`. So if a user does `Create/Note` inside a group (to create a comment), the group sends it to followers as `Announce/Create/Note`. 

When i implemented Mastodon federation last November or December, Mastodon couldnt handle such activities, so now we are also sending `Announce/Page` specifically so posts reach Mastodon/Pleroma. Note that we dont send any `Announce/Note` (removed in https://github.com/LemmyNet/lemmy/pull/1914). So the only reason I can think of that Lemmy comments would show as boosted in Mastodon is if you added support for receiving `Announce/Create/Note` activities.

**Comment by ClearlyClaire** [comment]
Oh, I understand better. We support `Announce (Note)` and `Announce (Page)` but we do not deliberately support `Announce (Create)`, although I can see two occasions where that could actually work:
- the `Create` activity itself has the same `id` as an already-known post. This isn't a new behavior and would be an error from the sender's end (although we should maybe to check the type of the activity)
- if the `Create` activity is dereferenceable, it will be fetched, then `Announce (Create (Object))` will be handled as `Announce (Object)`. This is a new behavior from 3.5.0 and not completely intended, need to think about it.

Looking at the code, there is one (admittedly incorrect) edge case that could result in an `Announce (Create)` to be “supported” is if the `Create` activity has the same `id` as an already-known

**Comment by Nutomic** [comment]
There is nothing we can do about this, it can only be fixed by Mastodon.
