### ISSUE TITLE
Users cannot register with applications enabled due to JSON syntax error

### ISSUE THREAD

**Issue by SamWhited** [LemmyNet/lemmy#2225]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

(I do not know if this is a frontend or a backend issue)

### Issue Summary

After a wave of spam yesterday we enabled applications for registration on https://community.xmpp.net. However, now whenever I try to sign up (via Firefox or Chromium) nothing happens. No error is visible, the button just spins forever. An error (see below) is visible in the developer console.

### Steps to Reproduce

1. Signup with a username and password.
2. Hit submit

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.

I do not have access to the backend as it's using the free lemmy hosting offer.

* Any browser console errors?

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    ws https://community.xmpp.net/static/js/client.js:2
    dispatchEvent https://community.xmpp.net/static/js/client.js:2
    dispatchEvent https://community.xmpp.net/static/js/client.js:2
    handleEvent https://community.xmpp.net/static/js/client.js:2
    handleMessageEvent
```

**Comment by dessalines** [comment]
I'd need to see the back-end logs to figure this out. Might be incorrectly configured email, who knows.
