### ISSUE TITLE
Shouldn't lurkers be allowed to contact users through matrix?

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [LemmyNet/lemmy#2228]
Perhaps someone has been using lemmy, but hasn't made an account. Shouldn't he be able to see the matrix name of someone to contact him?

Also I think creating matrix rooms for each community would improve the social aspect of lemmy.

**Comment by dessalines** [comment]
Lemmy profiles already have optional public matrix user ids. A send secure message button is on their profile if they have that set.

We wouldn't integrate with matrix closely enough to spawn chats automatically for every post, community, etc.
