### ISSUE TITLE
Comment Reply email has mailformed content.

### ISSUE THREAD

**Issue by kevincox** [LemmyNet/lemmy#2231]
### Issue Summary

I got a reply notification which looks like this:

```html
<h1>Post reply</h1><br><div>https://lemmy.ml/inbox - OsrsNeedsF2P</div><br><a href="They did it for the UI/UX, which I actually agree with. The other mainstream git solutions are deplorable">inbox</a>
```

Formatted

```html
<h1>Post reply</h1>
<br>
<div>https://lemmy.ml/inbox - OsrsNeedsF2P</div>
<br>
<a href="They did it for the UI/UX, which I actually agree with. The other mainstream git solutions are deplorable">inbox</a>
```

It looks like the link and message got swapped?

### Technical details

From lemmy.ml.

**Comment by DMTryptamines** [comment]
Can confirm this is happening on my instance and lemmy.ca. It only started after upgrading to 0.16.3, I use ansible if it matters. I have old emails from April 4-5th that display fine but recent emails from both sites are malformed as described above.

**Comment by Nutomic** [comment]
The way email texts are built is pretty confusing, with multiple nested functions that take lots of string parameters (so no effective type checking). Its likely that there is a parameter in the wrong place somewhere.

**Comment by dessalines** [comment]
Found the issue, rosetta seems to use a random order when multiple params are used. I opened up an issue. https://github.com/baptiste0928/rosetta/issues/8
