### ISSUE TITLE
View another community from another instance does not show comments

### ISSUE THREAD

**Issue by skariko** [LemmyNet/lemmy#2241]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

Hello, I am not really sure this is a bug or if it is just "how it should be".
I have tried what I found on this mini-guide by [@nutomic](https://lemmy.ml/u/nutomic): https://lemmy.ml/post/68360

Btw if I try to search for a community from another instance I see all the posts but I can't see any comments and no upvote/downvote.
Is it how it should works? Thanks!

### Steps to Reproduce

1. Go to https://baraza.africa/c/lealternative@lemmy.ml and see that there is only posts and not comments or upvote and downvote.

**Comment by dessalines** [comment]
Update to the new lemmy version, and also try resubscribing to the remote community.

**Comment by Nutomic** [comment]
Comments will only appear if a user is subscribed to the community, and only new comments. To see existing comments, you will have to fetch them one by one by pasting the fedlinks in the search bar.

**Comment by skariko** [comment]
ok thanks!

**Comment by kajover** [comment]
I think this needs to be reopened. I don't think it is intuitive for new users to copy/paste every comment in the search bar to have past comments federated. Also, the workaround does not work for replies of comments as the link is for the initial comment.
