### ISSUE TITLE
Expose CommunityFollower.pending field in API

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2246]
The pending field is necessary because of federation. In case of a federated community, a follow isnt valid immediately, but only after receiving an Accept activity. This usually happens immediately, but can be delayed in some cases, or not arrive at all in case of federation issues. In that case, Lemmy users see the "joined" indicator which is very misleading.

We should expose the pending field in the API, and if it is true, show neither the "joined" indicator nor "subscribe" button, but a "pending" indicator.

**Comment by dessalines** [comment]
I got this one.
