### ISSUE TITLE
Video in lemmy

### ISSUE THREAD

**Issue by rishabh-modi2** [LemmyNet/lemmy#2249]
I created a server for playing videos in lemmy instance 
support iframe
the url of player is https://videoplayer.rishabh.ml/v/?url=**Your_video_download_url**

my webapp is able to play direct links also 
for eg this link https://cdntube2.b-cdn.net/mp4/8408779614048c829301c455e619debf253f280d.mp4 cannot be played using iframe but
 now https://videoplayer.rishabh.ml/v/?url=https://cdntube2.b-cdn.net/mp4/8408779614048c829301c455e619debf253f280d.mp4 This can be played.

iframe code to embed videos 

<iframe src='https://videoplayer.rishabh.ml/v/?url=https://cdntube2.b-cdn.net/mp4/8408779614048c829301c455e619debf253f280d.mp4' height='360' width=100% allowfullscreen=True></iframe> 

Just paste this code in body

**Comment by dessalines** [comment]
Lemmy doesn't support images or video, our image host is pictrs, and videos would have to be something else.

**Comment by dessalines** [comment]
If its supported in pictrs, then its up to front ends to handle how they read video `post.url`s and render videos. Again, lemmy doesn't store pictures, it uses pictrs to do so.
