### ISSUE TITLE
Consider making federated deletes optional

### ISSUE THREAD

**Issue by dayinjing** [LemmyNet/lemmy#2259]
### Is your proposal related to a problem?

No

# Description
Many users turn to federated services because they are censorship resistant. One of the benifits of federeation is content exist in multiple places. 

As a site admin I would like the ability to toggle off federated deletes. That is a toggle that when enabled will not delete content that a moderator or admin of another instance has chosen to delete on it's home instance. 

### Describe the solution you'd like

Perhaps a switch, maybe multiple switches to enable and disable deletes from federated instances. When toggled on a post that was deleted by a moderator will not be deleted locally unless a mod or admin on the local instance deletes it. 

### Describe alternatives you've considered

Maybe give admins the ability to restore that content?

### Additional context

I think i've made the request clear. Let me know what you think about it!

**Comment by Nutomic** [comment]
This would be pretty easy to implement, by adding a config option and if it is set, return an error in the following two places.

https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/activities/deletion/delete.rs#L54
https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/activities/deletion/delete_user.rs#L29

But im a bit sceptical if such a feature should be merged, as user would expect that deletes actually work (especially if there is sensitive data). On the other hand, deletes are already very imperfect, for example, deletes will not federate if your instance doesnt follow that community, or if there is an instance block. Other platforms might also not handle Lemmy deletes correctly. So having a config option to reject federated deletes could help to emphasize the fact that deletion cant be relied on.
