### ISSUE TITLE
Make Lemmy work without Javascript / Isomorphic / Archivability / SEO previews.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#226]
It should be possible to use Lemmy while having Javascript disabled in the browser.

A checklist of things that need to be done for this.

- [x] Translations as submodule #1123 
- [x] Add communityjoin, postjoin, etc #1122 
- [x] Remove UI from this codebase
- [x] Fix nginx location for docs.
- [x] Fix nginx to use the express server port instead.
- [x] Set up jest tests.
- [x] Fix up docs
- [x] Lots of testing.

**Comment by dessalines** [comment]
Okay this didn't work for several reasons:

- The Websocket / RXJS module couldn't hydrate. (Not sure how exactly live data would work in an isomorphic app anyway). This was pretty much the killer. I spose in an isomorphic app thats already in ts / js, you could just rewrite the web service to just do local activity, but the backend for this is in rust. The only other alternative would be to have rust serve up static pages, but again that wouldn't be live-updating and defeat the purpose of this or any front end.
- Couldn't do things like detect and set browser language for translations.
- Couldn't do things like window scrolling... pretty much any dynamic activity.
- The browser routing would require a rewrite.

#155

**Comment by dessalines** [comment]
Try out a testbed using this: https://github.com/heineiuo/isomorphic-ws

**Comment by zacanger** [comment]
Next.js also works with Inferno (or did, last time I tried it, that might not be true in Next 8 according to [this issue](https://github.com/zeit/next.js/issues/6264)), and can work with websockets (open in a `componentDidMount`).

**Comment by dessalines** [comment]
I've tried and failed twice at this, including using the tutorial from tylermcginnis above. Other than for analytics, there just doesn't seem to be much point: since we upped the DB performance, the page already loads in less than 2 seconds. Basically a LOT of work, on every component just to minimize that initial page load, after which all that work is pointless.

**Comment by dessalines** [comment]
This is really a duplicate of #347 .

**Comment by StaticallyTypedRice** [comment]
Crazy idea: Do you think we can have a fork of the webclient run on the server to pre-render the initial page and just have hooks that the browser can execute which connects it to web sockets?

**Comment by dessalines** [comment]
That is what isomorphic means, and its not easy to implement.

**Comment by StaticallyTypedRice** [comment]
> That is what isomorphic means, and its not easy to implement.

As in literally having the same single page web app run on the server? I always imagined that the typical implementation would be (for Lemmy) to render the HTML using Rust through Actix.

**Comment by dessalines** [comment]
You can read about how isomorphic apps work in the links above.

**Comment by Toxu-ru** [comment]
> The only other alternative would be to have rust serve up static pages, but again that wouldn't be live-updating and defeat the purpose of this or any front end.

It may be worth defining the User-Agent and giving it the page using other templates, without Javascript. As far as I know in Discourse for example, this is exactly what they do. The user cannot use the site with Javascript disabled. A site without Javascript is available to search engines, but it has its own set of templates. There aren't many pages here.

**Comment by Toxu-ru** [comment]
> It should be possible to use Lemmy while having Javascript disabled in the browser.


Do I understand correctly that you want the site to be usable with JavaScript disabled? Answers etc.

Perhaps for search engines can be made easier. Look at Discourse with JavaScript disabled or under the User Agent of any search engine.

If Javascript is missing, the script displays the templates: https://github.com/discourse/discourse/tree/master/app/views

This is not for users, but for search engines.

Perhaps it is easier to do this in Rust, if there is no JavaScript, then a different template is shown. This will be more static, but this is normal for search engines. This is not for users.

**Comment by dessalines** [comment]
> Do I understand correctly that you want the site to be usable with JavaScript disabled? Answers etc.

In the future, yes, but currently, it will show a little message saying javascript needs to be enabled to view this site.

> This is not for users, but for search engines.

Correct, its mainly for search engines, but also important when other sites want to link to lemmy pages, so that they can build link previews, etc.

**Comment by Nutomic** [comment]
Dont forget that some people prefer to use the web without Javascript. A lot of sites today makes this impossible, so it would be great if we could set a good example!

**Comment by dessalines** [comment]
I personally don't have time to build a non-interactive / read-only client, but if someone else wants to make one, they could always do so.

**Comment by fifn2** [comment]
I love Lemmy but I don't run JS in my browser for security and privacy reasons.

**Comment by poVoq** [comment]
Could this be integrated and used for stuff like described above?
https://github.com/IronOxidizer/lemmy-lite

**Comment by dessalines** [comment]
We will likely add a route to make lemmy-lite available, once ironoxidizer gets a docker working, and feels its ready. But I don't know if it'd be usable to solve our problem here.

**Comment by dessalines** [comment]
Making lots of progress on this recently. https://github.com/LemmyNet/lemmy-isomorphic-ui
