### ISSUE TITLE
System notification via email when a user signup

### ISSUE THREAD

**Issue by nicfab** [LemmyNet/lemmy#2271]
Currently, there is no system notification when users signup for the community.
It will be appreciable if you implement it because it avoids the admin continuing to check the community on the web.

**Comment by dessalines** [comment]
I'm confused about what you're saying here, because we already have a panel for registration applications.

Any user that signs up to any community, it should email all the community mods?
Any user that signs up to the site, it should email all the admins?

**Comment by nicfab** [comment]
> I'm confused about what you're saying here, because we already have a panel for registration applications.
> 
> Any user that signs up to any community, it should email all the community mods? Any user that signs up to the site, it should email all the admins?

I mean that the admin doesn't receive an email notification when a user registers to Lemmy.
I have to refresh the webpage to see whether a user registered on my Lemmy instance.

**Comment by nicfab** [comment]
> Okay this makes sense, what you really mean is you'd like an email to all admins after a user has completed a registration application.

Yes. The admin should receive an email with the notice related to a new registration request or better with a choice to admit or deny the user’s registration request into the email.

**Comment by dessalines** [comment]
This should also be a site setting, `application_email_admins`

**Comment by nicfab** [comment]
> This should also be a site setting, `application_email_admins`

Should I edit inventory/hosts and add `application_email_admins`?
Will it work right away?

**Comment by Nutomic** [comment]
This wont work because it hasnt been implemented yet.
