### ISSUE TITLE
Lens Protocol: A PERMISSIONLESS, NON-CUSTODIAL  SOCIAL MEDIA PROFILE

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2276]
I saw they released the [Lens Protocol](https://lens.xyz/) which is a way for users to own their social media identity and relationships (social graph) instead of it owned by the social media company e.g. FB, Twitter, etc

Lemmy already does a good job of federating our content and I thought adding the ability for our users use a profile that they both own and is portable would be very complementary.

Since the Lens Protocol is looking for projects that use their protocol - enabling it with Lemmy might lead a whole new batch of users to discover how wonderful Lemmy is.

You might find their [FAQ](https://docs.lens.xyz/docs/faq) interesting as it explains how it works

It was launched by the company behind a major crypto currency (AAVE) and I also thought it might be a way to help instances and users generate revenue without ads. Your might want to [read this overview](https://cryptobriefing.com/aave-launches-lens-an-nft-based-social-media-protocol/)

**Comment by dessalines** [comment]
We want nothing to do with crypto, blockchains, or monetizing user's data in any way.

**Comment by Kap2022** [comment]
Fair enough.

I will trust your judgement.
