### ISSUE TITLE
A particular mod can edit posts

### ISSUE THREAD

**Issue by rishabh-modi2** [LemmyNet/lemmy#2280]
please add a feature with which particular mod(a bot)  has right to edit other users post

**Comment by Nutomic** [comment]
Could you give some more details, like why this would be useful, and how it should be represented in the user interface?

**Comment by dessalines** [comment]
I'm very against this. A mod should be able to remove a user's post, but not edit it. That's the kind of manipulation you see from reddit admins, editing other people's comments.
