### ISSUE TITLE
Mastodon federation: post with title and URL of Lemmy post

### ISSUE THREAD

**Issue by skariko** [LemmyNet/lemmy#2290]
I write here because but I am not sure if is a limitation of the UI, if it is wrong I apologize and I can rewrite it in the correct repository.

A user from Mastodon who follows a Lemmy community sees posts via Title + URL.

The problem is that if you enter for example a photo or an external URL the post on Lemmy becomes unreachable.

**Two examples.**

URL with picture: https://mastodon.uno/web/@skariko@feddit.it/108390814797213205 ([original post](https://feddit.it/post/6292))

URL with external video: https://mastodon.uno/web/@skariko@feddit.it/108390245859396179 ([original post](https://feddit.it/post/6267))

It would probably be better for the link to the original post to be inserted regardless otherwise it is in no way possible to retrieve the original link to the post which may also contain other information besides the image and external URL.

**Comment by dessalines** [comment]
Where's the unreachable post? I'm confused.

**Comment by skariko** [comment]
> Where's the unreachable post? I'm confused.

I hope to be able to clarify myself :)

Anyone who follows a Lemmy community from Mastodon sees (in case of image posted) this:

![Screenshot_20220602-160000](https://user-images.githubusercontent.com/25532821/171646686-4d74b434-9cd2-4033-afc0-19918fe7aac2.png)

In case of external URL this:

![Screenshot_20220602-160328](https://user-images.githubusercontent.com/25532821/171647325-461172d4-119e-4013-ba84-17804e8fc8d5.png)

In case of "normal post" with no image and no URL it shows this:

![Screenshot_20220602-160433](https://user-images.githubusercontent.com/25532821/171647518-50e91bb5-36f4-4f65-915b-0c7318ad8058.png)

As you can see on the first two it shows only the link to the pics or to the external URL and there is no way of seeing which is the link of the post on Lemmy.

I think it would be a good idea to always be able to insert the link to Lemmy's original post because there may be other things written besides the image or the URL.

**Comment by Nutomic** [comment]
This is a question of how Mastodon decides to render the objects that are sent by Lemmy. You should open an issue in the Mastodon repo, as there is nothing we can do about this (unless we completely cripple Lemmy-to-Lemmy federation).

**Comment by skariko** [comment]
> This is a question of how Mastodon decides to render the objects that are sent by Lemmy. You should open an issue in the Mastodon repo, as there is nothing we can do about this (unless we completely cripple Lemmy-to-Lemmy federation).

Thank you, if anyone is interested on this I have created a issue on Mastodon repo here: https://github.com/mastodon/mastodon/issues/18596
