### ISSUE TITLE
Download option when viewing federated Peertube videos from Lemmy

### ISSUE THREAD

**Issue by DMTryptamines** [LemmyNet/lemmy#2312]
This proposal improves federation by eliminating deltas in feature sets between federated websites.

I'm requesting a button to download a video directly from peertube when viewing a federated video from lemmy. 

I've been trying to find out if this is possible currently and whether I have to make a feature request on peertube. [I found this in their AP docs](https://docs.joinpeertube.org/api-activitypub#:~:text=url%3A%20ActivityUrlObject%5B%5D) which makes me believe it's possible [looking at the examples.](https://docs.joinpeertube.org/api-activitypub#:~:text=Raw%20URL%20to%20webtorrent%20compatible%20mp4%20file) 

Peertube has download options for resolution, audio only, direct vs torrent links, etc. It would be nice to have those as well but that seems more difficult. Since downloads will expose your IP to the instance then redirecting users to the site for advanced options seems fine to me and limiting options to just torrent/direct at default settings in the options for lemmy or something along those lines

![dloptions](https://user-images.githubusercontent.com/86132393/173187794-48c166f0-40f7-47ed-b419-0ec5701235fb.PNG)

**Comment by Nutomic** [comment]
This is not realistic to implement, as Lemmy would have to understand all this data about different video formats, and also store it all permanently in the database. Its just too much effort for something that will save one or two clicks at best. 

In the future Lemmy will have embeds for Peertube videos, so maybe that will have a download button.

**Comment by DMTryptamines** [comment]
That makes perfect sense. I'll make a feature request on peertube for download links in the embed api because after looking it over I don't think it supports it. 

https://docs.joinpeertube.org/api-embed-player
