### ISSUE TITLE
Docker-Compose Up Error - 0.16.5 - no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by bmcgonag** [LemmyNet/lemmy#2320]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary
Trying to run the docker-compose.yml I get an error stating
```
Pulling lemmy (dessalines/lemmy:0.16.5)...
0.16.5: Pulling from dessalines/lemmy
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```
A summary of the bug.
I'm trying to install the lemmy suite on a Ubuntu 20.04 server running as a VM in Proxmox-VE 7.  I have many other docker apps running int his setup already.  

When I run `docker-compose up` I get an output error message that there is no manifest list entry for linux/amd64, and the process stops.

Error as follows:
```
Pulling lemmy (dessalines/lemmy:0.16.5)...
0.16.5: Pulling from dessalines/lemmy
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

### Steps to Reproduce

1. (for example) I clicked login, and an endless spinner show up.
2. I tried to install lemmy via this guide, and I'm getting this error.
3. ...

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
  There are no logs, as the process is interrupted by the error listed above.
* What OS are you trying to install lemmy on? 
  Ubuntu Server 20.04
* Any browser console errors?
  Didn't get that far.

**Comment by dessalines** [comment]
https://github.com/LemmyNet/lemmy/blob/main/docker/prod/docker-compose.yml#L15

0.16.4 is the current backend version.

**Comment by bmcgonag** [comment]
Ok, saw the tag 0.16.5 on dockerhub, so didn't realize it wasn't ready.
