### ISSUE TITLE
how are communities synced to other instances? 

### ISSUE THREAD

**Issue by it1728166827** [LemmyNet/lemmy#2323]
Users create communities, but how are those communities synced to other instances? This includes creating new users as well. In the apub source, it seems that only Update Community can sync to other instances. Does anyone have any pointers?

**Comment by dessalines** [comment]
Copy the community URL into the search box of another instance. You might have to do it twice for it to work (weird async issue). Then click subscribe, and from that point on, new content from that community will be pushed to your instance.
