### ISSUE TITLE
Peertube channels not getting updated

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy#2331]
### Issue Summary
The peertube channels I follow on lemmy are not seeing new posts unless I search for them.
See: https://lemmy.ml/c/podcast@h3h3.club
doesn't show the last 4 videos from: https://h3h3.club/c/podcast/videos

### Steps to Reproduce

1. follow peertube channel from lemmy
2. wait for new post to be made to channel 
3. see that lemmy view of channel doesnt have new post.

### Technical details
works fine on mastodon =P

**Comment by Nutomic** [comment]
Looked into this, it seems that Peertube had a regression, and again cant handle HTTP signatures from Lemmy.

https://github.com/Chocobozzz/PeerTube/issues/4963#issuecomment-1184263516

**Comment by Nutomic** [comment]
There was an issue in Peertube which will be fixed in the next version. When that is released, you will have to resubscribe to Peertube channels.

https://github.com/Chocobozzz/PeerTube/issues/4963#issuecomment-1185379441
