### ISSUE TITLE
Question about federation from user that I do not know how to answer

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2337]
A user posted this question on my instance:

https://exploding-heads.com/post/15965

about why comments from other instances were not appearing on our instance. There does not seem to be blocking involved on either end from what I can see.

Can you suggest how I should answer the user?

Thanks for your help.

**Comment by dessalines** [comment]
https://gtio.io/instances

They look like they're using an explicit allowlist, and don't have you added.

**Comment by Kap2022** [comment]
One last question.

How do I tell if an instance is using an allowed list?

Just to make it easier for me to answer these questions in the future.

**Comment by Nutomic** [comment]
It looks like that is currently not really shown.You should open an issue about that in lemmy-ui repo.
