### ISSUE TITLE
No more updates/posts from remote/federated communities

### ISSUE THREAD

**Issue by forenta** [LemmyNet/lemmy#2342]
I'm a member of the lemmy.ca instance and have joined various communities from there on various instances - some of them on feddit.de. As usual in other fediverse services, posts from communities were not shown in my list until I (or another user of my instance) was part of the community. Now I had wondered in the last weeks that I got to see very few new posts on 'my' lemmy. When I now looked at feddit.de/c/deutschland, I noticed that there are regularly a lot of new posts there - but they just don't appear for me anymore.
If I search a post discovered there via URL directly via the search on lemmy.ca, it then also appears federated with me. Without looking manually, however, I apparently no longer receive any news about what's going on in the Lemmyverse.

Does anyone have any idea what this could be or what I can do about this?

### Technical details
On lemmy.ca:
UI: 0.16.5
BE: 0.16.4

On feddit.de
BE: 0.16.4

**Comment by smorks** [comment]
hello, i'm the admin of lemmy.ca, and i've been looking into this a bit. there's nothing obvious that i can see in the logs, and it looks to me like all the posts are coming over with no issues, but most comments are being federated properly.

i will keep investigation and update you here if i find anything.

**Comment by forenta** [comment]
Thank you for taking care of this. To make sure I'm not fooled by the impression, I deliberately didn't manually pull a post from the remote-community in the last 2 days. Today it looks like the screenshot: Left on lemmy.ca with the last 'fetched' post from 2 days ago at the top. On the right, the view directly on feddit.de with 2 post from today and one post from yesterday in the home view.
![](https://i.postimg.cc/sgc9pmwH/screenshot-67.png)

**Comment by smorks** [comment]
@forenta when i subscribed to https://lemmy.ca/c/deutschland@feddit.de, it looked like all posts & comments where coming through. now that i've unsubscribed, it looks like that's no longer the case. can you try unsubscribing and resubscribing to see if that helps with this issue?

**Comment by forenta** [comment]
> @forenta when i subscribed to https://lemmy.ca/c/deutschland@feddit.de, it looked like all posts & comments where coming through. now that i've unsubscribed, it looks like that's no longer the case. can you try unsubscribing and resubscribing to see if that helps with this issue?

At least several posts appeared immediately, which I didn't get before, when I just left and re-joined the community. Possibly that was the key now. Thanks for the tip, I keep an eye on that!

**Comment by smorks** [comment]
i'll monitor it too. thanks for your patience!
