### ISSUE TITLE
Remove "enabled" from lemmy.hjson optional config blocks.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2356]
When the block is optional in a config, its redundant to have an `enabled` flag, since the existence of the block itself should denote that its enabled.

**Comment by Nutomic** [comment]
How would this work when you want to tell someone to enable federation? I believe it would have to be one of the following:

```
federation: {}
# or
federation: {
    allowed_instances: []
}
```

Both are very confusing, because it appears as if the federation block is empty and can be removed.

**Comment by dessalines** [comment]
I'd just say:

```
# Uncomment this block to enable federation
# federation: {
#  blocked_instances: []
# }
```

Or in [this config doc](https://join-lemmy.org/docs/en/administration/configuration.html), but which blocks / fields are required, and which are optional.

**Comment by dessalines** [comment]
These are all gone now.
