### ISSUE TITLE
Use message queue to decouple modules

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2358]
Much of our code is coupled very tightly together. For example when a new private message is created, the create method has to explicitly call methods in other crates to:
- send websocket notification
- send email notification
- send message over federation

It would be much cleaner to use a message queue system such as [crossbeam_channel](https://docs.rs/crossbeam-channel/latest/crossbeam_channel/), so that "api create private message" would only send a message on the channel like "private message created", and other code would receive it to send necessary notifications. This would certainly require a big refactor, but would allow us to cleanly separate different parts of the code. Then api wouldnt have to depend on apub, websocket, email crates at all, which would also allow for more parallel compilation, and speed up builds.

**Comment by dessalines** [comment]
We already do some of this with websocket messages using the Actor method: https://actix.rs/book/actix/sec-2-actor.html 

An example of that in our code is in `crates/websocket/handlers.rs`

Basically you start an Actor, define some message structs (your inputs), make functions for what the actor does with the messages, then send the actor messages from anywhere and optionally wait for the results.

**Comment by Nutomic** [comment]
That is only used for communication with lemmy-ui and other api clients, no? Im talking about something that communicates between different parts of the Rust code.

**Comment by Nutomic** [comment]
So it would be a way to avoid pulling in another dependency. Will have to look into it more to see what the differences are.
