### ISSUE TITLE
Pictures cannot be uploaded

### ISSUE THREAD

**Issue by Mystuddent** [LemmyNet/lemmy#2359]
There is a problem with the image upload path 

`let pictrs_config = context.settings().pictrs_config();`

pictrs_config.url  */* repeat

![78ZELYNT5$D215$U0X$FY8M](https://user-images.githubusercontent.com/24928560/178863130-907b7b78-8634-4dfb-bee9-aa8b3b3580ee.png)

**Comment by Nutomic** [comment]
Do you mean because it ends up with path `//`? That shouldnt cause any problems. And its easy to fix by removing the trailing slash from pictrs_config.url.

**Comment by Mystuddent** [comment]
yes,but my  config not trailing    
`url: "http://127.0.0.1:8081"`

**Comment by Nutomic** [comment]
Oh so you are running Lemmy locally, not on a server? How exactly are you starting it?

**Comment by Mystuddent** [comment]
Yes, I debug the service locally。Start Lemmy local service and pictrs  local service and then upload community icon pictures。
I found that I couldn't upload pictures.
Finally, I directly deleted "/"  is No problem
`let image_url = format!("{}image", pictrs_config.url);`

Thank you very much for replying to me

**Comment by Nutomic** [comment]
>  I've made many changes and convert all "/image" to "image" then that bypass the bug.

Where exactly did you change it? And how did you install Lemmy?

**Comment by dessalines** [comment]
This *might* be because the URL crate always appends a `/`, but when using the docker pictrs, which is always at `http://pictrs:8080` internally, that doesn't matter because its already at the top level.

@umamawme Could you make a PR.

**Comment by Phlogi** [comment]
Coming from https://github.com/LemmyNet/lemmy/issues/2403. I hope this fixes 2403?

**Comment by Phlogi** [comment]
@Mystuddent What version did you use when initially reporting this bug?

**Comment by Phlogi** [comment]
@Nutomic I double checked. The change is not needed when using the correct v.16 release branch for testing. 

In other words: using docker + nginx setup with version tagged version 0.16.7-rc.2 and the following config _without_ a trailing slash, it works:

` pictrs_url: "http://pictrs:8080"`

if you want to really merge and release https://github.com/LemmyNet/lemmy/pull/2407 you might need to change the config and add a slash! Please also think about updating the documentation and close https://github.com/LemmyNet/lemmy/issues/2405

**Comment by Nutomic** [comment]
@Phlogi I tested this, the trailing slash is added automatically when the config is parsed. So whether or not you put that trailing slash in the config file doesnt make any difference.

**Comment by Phlogi** [comment]
Alright, in that case the change request makes sense.
