### ISSUE TITLE
Add 2FA ( two-factor authentication )

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2363]
A placeholder ticket for adding 2FA for lemmy logins.

**Comment by Kap2022** [comment]
Question - would requiring the use of 2FA (open source app) help with the spambot problem you are discussing?

**Comment by dessalines** [comment]
No, because we'd never require 2FA, it'd be optional.

**Comment by Nutomic** [comment]
Previously discussed in https://github.com/LemmyNet/lemmy/issues/1434. Seems like the user who opened the issue closed it for some reason.

**Comment by unusualevent** [comment]
@Nutomic - so in #30b38cc there's a commit that references adding TOTP support, but it doesn't seem like the UI has it?

**Comment by Nutomic** [comment]
It was implemented in the UI in https://github.com/LemmyNet/lemmy-ui/pull/939, but apparently not released yet.

**Comment by eoli3n** [comment]
When will this be available on lemmy.ml ?

**Comment by dessalines** [comment]
When we do the next release.
