### ISSUE TITLE
Extract local site fields to its own table, `local_site`

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2365]
Currently it simply assumes that the first site is the local one. This doesnt always work, for example when a remote site is fetched over federation before local site is setup. Better to use boolean site.local (just like other actor tables).

**Comment by Nutomic** [comment]
There seems to be a real-world bug which happens for unknown reasons, and would be fixed by this change.

https://lemmy.ml/post/472529

**Comment by DokStook** [comment]
https://github.com/LemmyNet/lemmy-ui/issues/775

**Comment by Nutomic** [comment]
Actually, I think a better solution for this would be to add a new table `local_community` which contains only columns that we dont need for remote sites (such as default_theme). This table would have a column `local_site_id`. Then we dont need a `local` column where only a single row would be true, and weird problems might happen if somehow more than one is marked as local.

**Comment by DokStook** [comment]
So I have captured the bug in https://github.com/LemmyNet/lemmy-ui/issues/775. The logs since the reboot [are here](https://hastebin.com/acotaqutav.apache
)

**Comment by dessalines** [comment]
I could see `local_site` being useful, in the same way we have `person` for all the federated fields, and `local_user` for all their settings and non-federated info.

**Comment by Nutomic** [comment]
The difference is that unlike users, there can only ever be one local site.

**Comment by dessalines** [comment]
This will now be extracted to its own 1-row table.
