### ISSUE TITLE
When doing search, I get errors of various kinds.

### ISSUE THREAD

**Issue by wiwikuan** [LemmyNet/lemmy#2371]
### Issue Summary

My instance: https://nicelink.me/

When doing search, after I type in a keyword and press enter:

- Sometimes I get no result when there should clearly be matches. 
- Sometimes I get a forever-spinning circle, and in Javascript console it says "SyntaxError: Unexpected end of JSON input".
- Sometimes I get a forever-spinning circle, but in Javascript console it returns an object with the correct search result in it, however, the search result doesn't appear on the actual webpage.
- Sometimes I get a blank page with the text "404: FetchError: invalid json response body at http://lemmy:8536/api/v3/search?....", with no browser console message.

I tried to search by directly go to this url: https://nicelink.me/search/q/web/type/All/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1

And still very often I get the "404 FetchError" thing.

If the search term is not in English, like this: https://nicelink.me/search/q/%E9%83%A8%E8%90%BD%E6%A0%BC/type/All/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1

Then it almost always lead to the "404 FetchError" error.

Only very rarely (like 1% of the time) that I get a correct search result (when using English search term), but it did happen once in a while. Never worked (yet) when searching in Chinese.

### Technical details

I checked docker-compose logs, I see no errors when I do the search. All I see are normal HTTP INFOs from pictrs.

Server is Debian 11 on Linode.

---

I'm guessing maybe there's something wrong with the Nginx settings?

The instance is live, you guys can check it out if you like. Any help is appreciated.

**Comment by wiwikuan** [comment]
Here's my Nginx config:
[lemmy.conf](https://github.com/LemmyNet/lemmy/files/9176740/lemmy.txt)

**Comment by Nutomic** [comment]
Found the problem. After the linked pull request is merged, the new code will automatically be deployed to ds9.lemmy.ml, so you can make an account there and test it further.

Also its great to see an instance from Taiwan! You should join the [Instance admin chat on Matrix](https://matrix.to/#/!OwmdVYiZSXrXbtCNLw:matrix.org) to talk with other admins.
