### ISSUE TITLE
Delete account error

### ISSUE THREAD

**Issue by nicfab** [LemmyNet/lemmy#2372]
I created a test account, and I tried to delete it.
I received the message "deleted by creator," but it has not been deleted.
What can I do to delete an account permanently?

**Comment by Nutomic** [comment]
Based on my testing, the deletion seems to work, but doesnt trigger a logout in lemmy-ui. It is also still possible to login to a deleted account, as there is apparently no check to prevent the login in that case. I was going to add such a check alongside the check for site ban, but that also isnt checked in Login, only in get_local_user_settings_view_from_jwt(). So im confused how this is supposed to work.

cc @dessalines

**Comment by dessalines** [comment]
We could easily add a check for deleted to prevent logging into it again. And also force a cookie clear and page refresh for lemmy-ui, coulda sworn it did that already tho.

I just checked and it does delete all the content in the DB.

**Comment by nicfab** [comment]
> We could easily add a check for deleted to prevent logging into it again. And also force a cookie clear and page refresh for lemmy-ui, coulda sworn it did that already tho.
> 
> I just checked and it does delete all the content in the DB.

I also tried changing the browser and deleting cookies and history.
Nothing; it logged in with the deleted account.
I don't know.
Please, let me know if there is something that I can do.
