### ISSUE TITLE
Pronoun flairs

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy#2383]
### Is your proposal related to a problem?

This is an issue of accessibility. People tend to get to know each other on smaller instances. Therefore, talking about users using third-person pronouns is more common, as is people getting them wrong. This is annoying at best and creates an unwelcoming environment at worst, silently driving away users.

### Describe the solution you'd like

The most effective fix to this is to display users’ pronouns next to their name on comments, posts, DMs, and on their profile. This would also require a pronouns field on signup and in user settings. Instance admins would be able to set validation for pronouns to prevent abuse of the field.

![Screenshot showing a comment from a user with a single set of pronouns](https://user-images.githubusercontent.com/94232689/181836522-e8cb6898-7e5b-4188-a367-2673eddd454d.png)

*Screenshot showing a comment from a user with a single set of pronouns*

![Screenshot showing a comment from a user with two sets of pronouns](https://user-images.githubusercontent.com/94232689/181836517-52bbc208-c2bd-4117-971f-dcd26f9031ae.png)

*Screenshot showing a comment from a user with two sets of pronouns*

#### Input Validation

Pronouns in general would need to be passed through the slur filter if it’s enabled. Beyond that, I see three approaches to validating input as users choose their pronouns:

* Unrestricted
* Allowlist
* Blocklist
* Pronoun requests

Unrestricted would be good for small communities who don’t have a lot of local traffic and like to keep things intimate. It would become a
problem for larger instances which require consistent moderation to keep out spammers and trolls. Unrestricted pronouns would be another vector for harassment (think attack/helicopter or fuck/admin name).

### Possible implementation paths

1. As an extension on top of a user flair system. Would require #1456 as a prerequisite. API would differentiate between a pronoun flair versus other kinds of flair so the frontend could display them in the correct place and so they'd be required on signup.
   Also, whilst user flairs are tied to a specific community, this would not be the case with pronoun flairs.

2. [Via something like the API Mastodon have for labels in users' profiles.](https://github.com/hexbear-collective/lemmy/issues/1#issuecomment-1194818844)

### Describe alternatives you've considered

- Pronouns in display names
- Pronouns on profiles
- User flairs

### Additional context

It’s an issue that disproportionately affects women and trans people due to people on the English-speaking internet habitually using “he” or “they” for everyone online. This is likely a holdover from the idea that [There Are No Women On The Internet](https://knowyourmeme.com/memes/there-are-no-girls-on-the-internet).

They are an extremely popular feature on Hexbear. We conducted a short and informal poll on the site, the results were overwhelmingly positive, with many saying the way we do it is the best pronoun integration on the internet.

![Screenshot of poll](
https://user-images.githubusercontent.com/94232689/181836636-c710780c-bc30-4888-82cf-435cc7612046.png)

**Comment by Nutomic** [comment]
I think this feature would be way too specific to integrate in a general-purpose software like Lemmy. For example, east Asian languages like Chinese dont even have gendered pronouns as far as i know. Even in German or Spanish i have rarely if ever seen it. As you say, its only really a phenomenon on the English language internet, and thats not the only target group for Lemmy.

That said, it makes sense to me to have a more general feature for tagging users in different ways. https://github.com/LemmyNet/lemmy/issues/1456 is one possibility for that, though i am unsure how it would work in detail, including over federation. Could users freely write their tag, or only select from an admin-approved list? And how to handle different instances which use the tag feature for different attributes? (pronouns, operating system, favourite color, etc). It would be helpful if you could comment there with more details on how youd expect it to work from a user/admin perspective.

https://github.com/LemmyNet/lemmy/issues/246 could potentially be another way to implement this, though im not sure how to show it on each comment. Maybe it could be visible on mouseover of username?

Gonna close this one as wontfix, please comment on the two issues above.

**Comment by dessalines** [comment]
Re-opening just for discussions sakes.

I don't think we should have forced / opt-out pronouns, because of the reasons nutomic mentioned ( lots of languages don't use them ), and the fact that a lot of people don't feel comfortable providing their gender / sexual identity. 

Currently as you mentioned, the best way to add pronouns, is to add `my name (pronouns here)` as your display name. This field is already federated too, so pronouns should display next to your name all over the fediverse.

The other option is to use your bio. Its a click away, but its there, and it seems to be where most twitter / masto ppl put pronouns.

Long term, user flair #1456 would probably be the best way to do it, while also accounting for the diversity necessary for this. And it would work for a lot of other applications too ( political affiliations, religion, or things like musical tastes (IE a `metalhead` flair on a music community)).


Also thanks for repping Simplevote lol, seems like something I need to rewrite in rust 😆 .

**Comment by timhexbear** [comment]
I have a more lengthy reply, but don't wanna get too deep in it before I confirm some assumptions.

You've both talked about user flairs as if it's going to be an arbitrary key-value store. Keys like pronouns, operating system, favourite color, political affiliation, religion, genre, etc.

I figure each community will have a dedicated list of post flairs and user flairs, but instance-wide flair would display everywhere. Maybe a proper name for the feature we're looking for would be "pinned flair", which is user flair which appears across all communities independent of what that community's options are, as well as in community-agnostic feeds. However, if user flair is an arbitrary key-value pair, then you'd need some kind of admin config option to specify which key(s) should be pinned instance-wide per user

**Comment by jcklpe** [comment]
The concept of a pinned flair seems smart to me. It's flexible.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/issues/1456
