### ISSUE TITLE
Only positive votes on comments for polls

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy#2395]
Negative votes shouldn't be allowed for posts in the [poll community](https://lemmy.ml/c/polls).

When labels are implemented, negative votes shouldn't be allowed for posts labeled `poll`

This is for polls in which users can add new choices as comments. For polls with fixed choices there is [another issue](https://github.com/LemmyNet/lemmy/issues/787).

**Comment by JediMaster25** [comment]
This is still necessary since the [other issue](https://github.com/LemmyNet/lemmy/issues/787) was dropped.
> I think https://lemmy.ml/c/polls shows that this isnt really necessary as a separate feature.

**Comment by dessalines** [comment]
I've re-opened the other issue, but we don't have time to work on it. If you're familiar with how mastodon polls work @JediMaster25 , you could try to implement this.
