### ISSUE TITLE
Federation with Peertube is problematic

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy#2402]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Issue Summary

A summary of the bug.
When i search for a specific peertube-channel from lemmy, i get no result.
Even Videos from this channel are not found any longer by lemmy.

### Steps to Reproduce

1. (for example) I clicked login, and an endless spinner show up.
2. I tried to install lemmy via this guide, and I'm getting this error.
3. ...

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
* What OS are you trying to install lemmy on? 
* Any browser console errors?

This is from lemmy log, when i klick search:
`lemmy_1     | 2022-08-14T07:51:12.307962Z  INFO Websocket Request{trace_id=00000000000000000000000000000000}:perform{self=ResolveObject { q: "!eisenbahn@kino.schuerz.at", auth: Some(Sensitive) }}:search_by_apub_id:webfinger_resolve_actor: lemmy_apub_lib::utils: Fetching remote object https://kino.schuerz.at/video-channels/eisenbahn    
lemmy_1     | 2022-08-14T07:51:12.323798Z ERROR Websocket Request{trace_id=00000000000000000000000000000000}: lemmy_websocket::handlers: Error during message handling couldnt_find_object: Failed to resolve actor for eisenbahn@kino.schuerz.at
lemmy_1     |    0: lemmy_apub::fetcher::webfinger::webfinger_resolve_actor
lemmy_1     |              at crates/apub/src/fetcher/webfinger.rs:30
lemmy_1     |    1: lemmy_apub::fetcher::search::search_by_apub_id
lemmy_1     |              at crates/apub/src/fetcher/search.rs:20
lemmy_1     |    2: lemmy_api::site::resolve_object::perform
lemmy_1     |            with self=ResolveObject { q: "!eisenbahn@kino.schuerz.at", auth: Some(Sensitive) }
lemmy_1     |              at crates/api/src/site/resolve_object.rs:19
lemmy_1     |    3: lemmy_websocket::handlers::Websocket Request
lemmy_1     |            with trace_id=00000000000000000000000000000000
lemmy_1     |              at crates/websocket/src/handlers.rs:68
`
when i open the url in browser on my peertube https://kino.schuerz.at/.well-known/webfinger?resource=acct:eisenbahn@kino.schuerz.at
i get this
`
{"subject":"acct:eisenbahn@kino.schuerz.at","aliases":["https://kino.schuerz.at/video-channels/eisenbahn"],"links":[{"rel":"self","type":"application/activity+json","href":"https://kino.schuerz.at/video-channels/eisenbahn"},{"rel":"http://ostatus.org/schema/1.0/subscribe","template":"https://kino.schuerz.at/remote-interaction?uri={uri}"}]}
`

With other channels from the same peertube-instance, i have no problem, i can find them and join them.
I think, i joind this channel already, but get no updates on new uploaded videos, now it is not be found anymore... 

Is there a fix for the database maybe?

I run lemmy and peertube on Debian bullseye

The browsers console says:

```
Object { op: "ResolveObject", data: {…} }
​
data: Object { q: "!eisenbahn@kino.schuerz.at", auth: "eyJ0eXAiBLAFOOBLAFOObGciOiJIUzI1NiJ9.eyJzdWIiOBLAFOOBLAFOObW15LnBLAFOOBLAFOOHVlcBLAFOOBLAFOOQiOjE2NjAxMjEzNzh9.b6v6BLAFOOBLAFOOs3J9wXZky-iHBLAFOOBLAFOOc4" }
​
op: "ResolveObject"
​
<prototype>: Object { … }
client.js:2:183628

Object { error: "couldnt_find_object" }
​error: "couldnt_find_object"
​<prototype>: Object { … }
​​__defineGetter__: function __defineGetter__()
​​__defineSetter__: function __defineSetter__()
​​__lookupGetter__: function __lookupGetter__()
​​__lookupSetter__: function __lookupSetter__()
​​__proto__: 
​​constructor: function Object()
​​hasOwnProperty: function hasOwnProperty()
​​isPrototypeOf: function isPrototypeOf()
​​propertyIsEnumerable: function propertyIsEnumerable()
​​toLocaleString: function toLocaleString()
​​toString: function toString()
​​valueOf: function valueOf()
​​<get __proto__()>: function __proto__()
​​<set __proto__()>: function __proto__()
client.js:2:1726040
```

**Comment by xundeenergie** [comment]
When i move a video, from this channel, where it is not be found, to another channel, which is found by lemmy, i can find the video in search.
Move it back to the other channel, the vido disappears in search...

**Comment by xundeenergie** [comment]
is it possible, that i can not follow a remote community/peertube-channel, when the communityname exists local? Which is in my case, how i found out now.

**Comment by xundeenergie** [comment]
Lemmy says it coud not find the actor on peertube.

In peertube i get a request to webfinger and the output is ok, how you can see in the bugreport.

Another community, which i can find gives me this requeset to compare it with the broken one:

`Aug 14 10:27:39 tube peertube[272780]: [kino.schuerz.at:443] 2022-08-14 10:27:39.934 info: 10.0.100.27 - - [14/Aug/2022:08:27:39 +0000] "GET /.well-known/webfinger?resource=acct:h0e@kino.schuerz.at HTTP/1.0" 200
 323 "-" "Lemmy/0.16.6; +https://lemmy.schuerz.at"                                                                                                                                                                 
`

The output in Browser from this url is

`{"subject":"acct:eisenbahn@kino.schuerz.at","aliases":["https://kino.schuerz.at/video-channels/eisenbahn"],"links":[{"rel":"self","type":"application/activity+json","href":"https://kino.schuerz.at/video-channels/eisenbahn"},{"rel":"http://ostatus.org/schema/1.0/subscribe","template":"https://kino.schuerz.at/remote-interaction?uri={uri}"}]}`

It is almost the same as the broken one. The difference is only "eisenbahn" vs. "h0e"

**Comment by Nutomic** [comment]
Im trying to look into this now, but kino.schuerz.at is down. Please let me know when you fix it so I can have a look.

**Comment by xundeenergie** [comment]
Sorry, i have some troubles with a new dataspace, and i'm on holidays. Will fix it, when i'm back home.

I tell you, when it's up again

**Comment by xundeenergie** [comment]
My instance is up.
You can try now

**Comment by xundeenergie** [comment]
This peertube-channel i can find and join from lemmy

https://kino.schuerz.at/.well-known/webfinger?resource=acct:h0e@kino.schuerz.at
`{"subject":"acct:h0e@kino.schuerz.at","aliases":["https://kino.schuerz.at/video-channels/h0e"],"links":[{"rel":"self","type":"application/activity+json","href":"https://kino.schuerz.at/video-channels/h0e"},{"rel":"http://ostatus.org/schema/1.0/subscribe","template":"https://kino.schuerz.at/remote-interaction?uri={uri}"}]}`

This one not 
https://kino.schuerz.at/video-channels/eisenbahn
`{"subject":"acct:eisenbahn@kino.schuerz.at","aliases":["https://kino.schuerz.at/video-channels/eisenbahn"],"links":[{"rel":"self","type":"application/activity+json","href":"https://kino.schuerz.at/video-channels/eisenbahn"},{"rel":"http://ostatus.org/schema/1.0/subscribe","template":"https://kino.schuerz.at/remote-interaction?uri={uri}"}]}`

When i search for the second one, i get this error (still after upgrade to peertube 4.3.0)

`lemmy_1     | 2022-09-24T14:44:51.756703Z  INFO HTTP request{http.method=GET http.scheme="http" http.host=lemmy.schuerz.at http.target=/api/v3/resolve_object otel.kind="server" request_id=bb6df6e8-2f58-4da6-adc3
-d2046e1258df}:perform{self=ResolveObject { q: "!eisenbahn@kino.schuerz.at", auth: None }}:search_by_apub_id:webfinger_resolve_actor: lemmy_apub_lib::utils: Fetching remote object https://kino.schuerz.at/video-c
hannels/eisenbahn                                                                                                                                                                                                  
lemmy_1     | 2022-09-24T14:44:51.769643Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: couldnt_find_object: Failed to resolve actor for eisenbahn@kino.schu
erz.at                                                                                                                                                                                                             
lemmy_1     |    0: lemmy_apub::fetcher::webfinger::webfinger_resolve_actor                                                                                                                                        
lemmy_1     |              at crates/apub/src/fetcher/webfinger.rs:30                                                                                                                                              
lemmy_1     |    1: lemmy_apub::fetcher::search::search_by_apub_id                                                                                                                                                 
lemmy_1     |              at crates/apub/src/fetcher/search.rs:20                                                                                                                                                 
lemmy_1     |    2: lemmy_api::site::resolve_object::perform                                                                                                                                                       
lemmy_1     |            with self=ResolveObject { q: "!eisenbahn@kino.schuerz.at", auth: None }                                                                                                                   
lemmy_1     |              at crates/api/src/site/resolve_object.rs:19                                                                                                                                             
lemmy_1     |    3: lemmy_server::root_span_builder::HTTP request                                                                                                                                                  
lemmy_1     |            with http.method=GET http.scheme="http" http.host=lemmy.schuerz.at http.target=/api/v3/resolve_object otel.kind="server" request_id=bb6df6e8-2f58-4da6-adc3-d2046e1258df http.status_code=
400 otel.status_code="OK"                                                                                                                                                                                          
lemmy_1     |              at src/root_span_builder.rs:16                                                                                                                                                          
lemmy_1     | LemmyError { message: Some("couldnt_find_object"), inner: Failed to resolve actor for eisenbahn@kino.schuerz.at, context: "SpanTrace" }                                                              
`

But the community is joinable from friendica. And other communities on my peertube i can join also from lemmy... no problems. Only with this one.

**Comment by xundeenergie** [comment]
So... i tried to search on feddit.de and mander.xyz also for !h0e@kino.schuerz.at and !eisenbahn@kino.schuerz.at

the first is found, the second not. The same as on my lemmy too.

Please can you verify, what's wrong with this channel for lemmy? Other service i run myself (friendica, pixelfed, pleroma) will find this community as well as !h0e@kino.schuerz.at and allow to join.

**Comment by Nutomic** [comment]
That channel has the following:
```
"publicKey": {
    "id": "https://kino.schuerz.at/video-channels/eisenbahn#main-key",
    "owner": "https://kino.schuerz.at/video-channels/eisenbahn",
    "publicKeyPem": null
},
```

The publicKeyPem field is mandatory, it cant be null. Without it, its impossible to send any messages to the channel. Looks like a bug in Peertube to me.

**Comment by xundeenergie** [comment]
This is the raw-data? 
Where can i find this? 
What should i write in an issue in peertube?

**Comment by Nutomic** [comment]
Its from here: `curl -H 'Accept: application/activity+json' https://kino.schuerz.at/video-channels/eisenbahn | jq`

This is the data which is used for federation. So when you search for the channel, Lemmy needs to parse this data and store it in the database. That fails because publicKey.publicKeyPem cant be null.

**Comment by xundeenergie** [comment]
> Its from here: `curl -H 'Accept: application/activity+json' https://kino.schuerz.at/video-channels/eisenbahn | jq`
> 
> This is the data which is used for federation. So when you search for the channel, Lemmy needs to parse this data and store it in the database. That fails because publicKey.publicKeyPem cant be null.

Thanks!

I found this channel in the database. And it really had no pub/priv-key pair... don't know, how this could happen... 

I think, this Issue can be closed.

**Comment by xundeenergie** [comment]
The problem was indeed the missing pub/priv-key in peertube. 
Solution is described in https://github.com/Chocobozzz/PeerTube/issues/5335
