### ISSUE TITLE
SSL missing on main homepage

### ISSUE THREAD

**Issue by ShalokShalom** [LemmyNet/lemmy#2406]
https://dev.lemmy.ml/

Firefox reports that the site is unsafe, when I access it the first time.

**Comment by Nutomic** [comment]
That domain is not in use for a long time now. We had a redirect to lemmy.ml, but that was lost in a migration. Where did you find the link?

**Comment by ShalokShalom** [comment]
https://codeberg.org/hydis/awesome-alternatives

**Comment by Nutomic** [comment]
You shoud ask them to change the link to our project website: https://join-lemmy.org/

**Comment by ShalokShalom** [comment]
https://codeberg.org/hydis/awesome-alternatives/pulls/1
