### ISSUE TITLE
Posts deleted by creators aren't really deleted

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy#2410]
I can still see the title, the content and the author of a post marked as deleted by creator.

**Comment by dessalines** [comment]
Could you give an example?

**Comment by JediMaster25** [comment]
https://lemmy.ml/post/417095

**Comment by Nutomic** [comment]
Post more details, like screenshot, your browser etc. I see none if the details you mention.

**Comment by JediMaster25** [comment]
![Screenshot from 2022-08-18 12-53-08](https://user-images.githubusercontent.com/105824751/185378367-2697620e-c3ba-4531-93f6-fffb64b90680.png)

**Comment by dessalines** [comment]
Deleting a post just removes it from feeds, its still accessible to ppl who know the url.

**Comment by Nutomic** [comment]
Okay so if you are logged in, it shows the title and text. Without login it looks like this:

![Screenshot_20220818_231016](https://user-images.githubusercontent.com/1044450/185495622-7aae17a6-9217-4329-8d46-6b53ca1fce44.png)

**Comment by TheHelloDev** [comment]
Shouldn't the post be __completely__ deleted from the servers though?

**Comment by dessalines** [comment]
No, an actual database delete would delete a lot of other people's content, such as their comments. 

When you delete your account, it does overwrite all your content in the database tho. And we've also added an admin "purge" which does do a potentially very destructive database delete.
