### ISSUE TITLE
Allow resize to be set in config to reduce max image size, pictrs does support this

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2416]
### Describe the solution you'd like
The goal is to reduce the image sizes to a reasonable size to avoid gigabytes of image sizes. 

- pictrs supports the resize= argument when uploading images
- make a default value configurable in lemmy.hjson e.g. to 2048

**from pitcrs API:** 
`resize={int}: produce a thumbnail of the image fitting inside an {int} by {int} square using a Lanczos2 filter. This is slower than sampling but looks a bit better in some cases`

(Describe your proposed solution here.)

### Describe alternatives you've considered
- can't see any

### Additional context
Maybe related: https://github.com/LemmyNet/lemmy/issues/766

**Comment by sam365724** [comment]
https://github.com/LemmyNet/lemmy/issues/766

**Comment by dessalines** [comment]
Probably a good idea to have this. Our only current limit is just an nginx line that limits max upload size.

**Comment by asonix** [comment]
pict-rs does not support resizing on upload (only on fetch)...

but maybe it could 👀

**Comment by sam365724** [comment]
> Probably a good idea to have this. Our only current limit is just an nginx line that limits max upload size.

There is "trick" to do it more precisely in pict-rs, like this in docker-compose: 
`    entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 12`
e.g. limits to 12MB

**Comment by sam365724** [comment]
> pict-rs does not support resizing on upload (only on fetch)...
> 
> but maybe it could 👀

That would be great, e.g. a --scale-down-if-exceeds-max-image-area

**Comment by sam365724** [comment]
> pict-rs does not support resizing on upload (only on fetch)...
> 
> but maybe it could 👀

How would i open a feature request? Can you add me at your asonix repo?

**Comment by asonix** [comment]
I've opened an issue on pict-rs for this: https://git.asonix.dog/asonix/pict-rs/issues/3

**Comment by sam365724** [comment]
@asonix I saw the ticket. I like the second approach with a more generic pre-processing a lot. Because there is another feature i'd like to see in the future: Watermark an uploaded image automatically with the username. I think that would go into that direction, correct?

**Comment by dessalines** [comment]
I don't have an account there so I can't add an issue. Another request I have, is that pictrs specify a format to store the file in, when uploading. IE make sure all uploads are converted and stored as webp, in order to save space.

**Comment by sam365724** [comment]
> I don't have an account there so I can't add an issue. Another request I have, is that pictrs specify a format to store the file in, when uploading. IE make sure all uploads are converted and stored as webp, in order to save space.

Well, you'd just have to set --media-format on the pictrs instance. This can be done like this in docker-compose already:
in the pictrs-service section:
`    entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt --media-format webp`

Not tested though (-m 10 is tested), but not sure about supported formats.

**Comment by asonix** [comment]
yes, pict-rs already supports this, and has for a while (it's present in 0.1.x - current)

**Comment by sam365724** [comment]
@asonix Is it possible to set compression parameters too?

**Comment by asonix** [comment]
the arguments passed to imagemagick are intentionally very restricted. If you would like something more complex (like choosing a resize filter) I could maybe add that as a new feature, but I'm not going to allow user-supplied strings as arguments to 3rd party binaries

**Comment by sam365724** [comment]
@asonix Alright. So i pass now arguments with the PICTRS__MEDIA__PREPROCESS_STEPS variable. 

Are these exact magick arguments? I mean does **resize** also scale a small image up? This would not satisfy my use case here i guess.

What do i need to pass to resize images to a max size of 3MB for example?

**Comment by asonix** [comment]
There's no file-size metric for resizing, you can only specify a target resolution. And those are not magick arguments, the preprocess_steps config takes the same query parameters that the `/process.{ext}` endpoint takes in the same format.

If you need more control over existing processing operations, or the addition of new processing operations, that would be an additional feature request.

**Comment by sam365724** [comment]
Oh, just updated my question. So "resize=6000000@>" should work to define a max area of an image i hope.

**Comment by asonix** [comment]
Resizing to a max area is not currently supported, but that seems like it wouldn't be too difficult to add.

**Comment by sam365724** [comment]
Ok, so only max width or how is that parameter used then? I hope it does not scale up?

**Comment by asonix** [comment]
It does not scale up, it limits the maximum width & height to the provided value, maintaining the image's original aspect ratio

**Comment by asonix** [comment]
I've opened a new issue around area-based resizing

**Comment by sam365724** [comment]
> It does not scale up, it limits the maximum width & height to the provided value, maintaining the image's original aspect ratio

Ok cool, that should work for my use case then!

**Comment by loid345** [comment]
Nodebb uses the sharp library, which is a wrapper for libvips. This is several times more productive than imagemagick
https://www.npmjs.com/package/sharp
There is also a library for rust
https://github.com/olxgroup-oss/libvips-rust-bindings
Discourse has its own solution written in rust
https://blog.discourse.org/2021/07/faster-user-uploads-on-discourse-with-rust-webassembly-and-mozjpeg/
Maybe this will help solve the problem

**Comment by asonix** [comment]
@loid345 the problem is solved already, however, it is nice to see some alternative image processing libraries. I might have a look at some of these to see if they'll fit pict-rs's use case

**Comment by dessalines** [comment]
Another request:

Could you add the ENV vars for pictrs configuration / startup settings to the README? We use the docker image and the README only lists the command line args.

**Comment by asonix** [comment]
The pict-rs toml file in the repo has every configuration option and related environment variable documented.

**Comment by sam365724** [comment]
I think we can close this one, thanks for the quick implementation.
