### ISSUE TITLE
Expiration of jwt user token

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2418]
How long is a jwt token of a user valid? Is there an expiry mechanism? Where in the database is the expiration saved?

**Comment by Nutomic** [comment]
Expiration for jwt tokens is [explicitly disabled in the code](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/claims.rs#L20). 

See https://github.com/LemmyNet/lemmy/pull/2176#discussion_r838588657

**Comment by sam365724** [comment]
Alright, thanks for the information!
