### ISSUE TITLE
Implement remote follow

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2420]
This has been requested a lot recently. Basically remote follow allows you to interact directly with content while browsing another instance where you dont have an account. For example, I am browsing nrsk.no but my account is on lemmy.ml. Currently, if i click on the subscribe button, it shows an error about not being logged in. 

Instead it could show a form like below, which redirects to my instance (lemmy.ml), lets me login, and then shows a confirmation form for subscribing to the community. This workflow is supported by multiple different fediverse platforms, including Peertube and Mastodon.

![](https://lemmy.ml/pictrs/image/8d93eb70-08ad-4877-b067-9a4482d8c4aa.png)

Here is a discussion about how it works: https://socialhub.activitypub.rocks/t/what-is-the-current-spec-for-remote-follow/2020

**Comment by Kap2022** [comment]
I think it would be better if it just did the steps to let you comment from your own instance - rather then having to copy the nrsk.no url and paste it into the servch on Lemmy.ml and then subscribe - just do those steps for you seamlessly.

That way you are making it easier to keep the traffic inside the Lemmy family and would help communities spread across instances.

**Comment by Kap2022** [comment]
To put it another way, if I am an existing Lemmy user - I want it as easy as possible to comment/vote using my existing Lemmy account - not to be pushed to some other system.

If I am not an existing Lemmy user - but am a user on multiple different fediverse platforms, including Peertube and Mastodon - then your suggestion makes sense. (Not sure how we know if they are)

If I am not a Fediverse user (Lemmy or others) we probably want to take them to the sign up page on the instance they are currently visiting.

**Comment by dessalines** [comment]
What makes this difficult are that there are other actions besides commenting: there's subscribing, voting, creating new posts, etc. Basically any action that could give a "not logged in" error should maybe bring up a dialog to either:

- Log in
- Sign up here
- Show content on my instance

The 3rd option could then cache either the post or comment on your instance, and show you the page from your instance.

**Comment by Nutomic** [comment]
@dessalines This issue is only about remote follow, i dont think something like that exists for other functionality like voting or commenting. And based on the socialhub thread above, it would be *a lot* of effort to implement this for multiple types of actions. So lets keep it simple for now.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy-ui/pull/1875
