### ISSUE TITLE
Manually set / reset a password of the user via database?

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2421]
How can i set that, what is the hashing algorithm? Is updating the public.local_user table field password_encrypted enough?

**Comment by Nutomic** [comment]
Yes that should be enough. And passwords are hashed with bcrypt.

**Comment by sam365724** [comment]
Lookup how to create the bcrypt hash and use this sql query that supports username:

`UPDATE local_user set password_encrypted='<hash-goes-here>' where person_id=(select id from person where name='<username-goes-here>' limit 1);
`
