### ISSUE TITLE
Anonymization of content after period of time

### ISSUE THREAD

**Issue by ColdHotman** [LemmyNet/lemmy#2425]
### Is your proposal related to a problem?

Some users want to auto-delete their post and/or comments after a period of time to avoid potential brigading, stalking, doxxing and other abuse.

### Describe the solution you'd like

A compromise between content deletion for privacy reasons and maintaining content for the community:

**_Allow posts to be anonymized after a period of time._**

This should be opt-in. The time limit before content anonymization could be set by the developers to maintain a universal standard, by the instance admins or the users themselves. There should be a warning for inexperienced users that this only deletes content on the lemmy network and does not "scrub" it from the internet.

### Describe alternatives you've considered

- Manually deleting comments and posts
- Using scripts like on reddit
- Not using lemmy or social media for privacy reasons

### Additional context

Original discussion
https://github.com/LemmyNet/lemmy/issues/2415

**Comment by Nutomic** [comment]
Seems too complex for little benefit.
