### ISSUE TITLE
Versions in docker/prod/docker-compose.yml in minor release

### ISSUE THREAD

**Issue by Kradyz** [LemmyNet/lemmy#2435]
Someone following the instructions to set up an instance using docker at the moment would end up with lemmy 0.16.4 and lemmy-ui 0.16.15. Is there a reason for not pulling v0.16.6 directly?

https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/prod/docker-compose.yml

**Comment by dessalines** [comment]
Ah my bad, looks like its good in lemmy-ansible, but not fixed here.

**Comment by Nutomic** [comment]
I think the problem is that we ran the release script on `release/v0.16` branch, so docker-compose.yml was only updated on that branch. The problem will repeat for every minor release, unless we fix the script. Reopening the issue.
