### ISSUE TITLE
Opening new communities 

### ISSUE THREAD

**Issue by GitFoss** [LemmyNet/lemmy#2436]
i have an account at beehaw instance,when i tried to open a community i received an error massage that says that only admins can create communities.

I Wanted to ask if that is the way that lemmy is supposed to behave or is it a preference by the admins ?

**Comment by dessalines** [comment]
Admin preference, its an instance setting.

**Comment by Nutomic** [comment]
@GitFoss Where do you see the option to create communities? On beehaw website it seems to be hidden.
