### ISSUE TITLE
Automatically redirect to working instances of privacy-oriented alternative frontends, such as Nitter, Invidious, Piped, etc

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2439]
Can you give admins an option to make inserting the [Farside](https://github.com/benbusby/farside) prefix in front of all links to youtube etc. This would make it easy for us to drive traffic to open source front ends instead of big tech. Might need a fall back where if the farside preview does not pull through, then it removes the prefix.

> Farside also accepts URLs to "parent" services, and will redirect to an appropriate front end service, for example:
> 
> https://farside.link/https://www.youtube.com/watch?v=dQw4w9WgXcQ will redirect to a [Piped](https://github.com/TeamPiped/Piped) or [Invidious](https://github.com/iv-org/invidious) instance
> https://farside.link/reddit.com/r/popular will redirect to a [Libreddit](https://github.com/spikecodes/libreddit) or [Teddit](https://codeberg.org/teddit/teddit) instance
> etc.

> Also it avoids the CloudFlare choke point as they try and centralize web traffic through their service:
> 
> Instances for each supported service that are deployed behind Cloudflare are not included when using [farside.link](https://farside.link/). . . Their mission to centralize the entire web behind their service ultimately goes against what Farside is trying to solve. 

Maybe include Farside in the standard installation.

**Comment by dessalines** [comment]
That seems a bit dangerous to me, these routing services go down all the time. I'd rather people rely on configurable browser plugins for these redirect-type services.
