### ISSUE TITLE
"Unknown" error in red when creating a post

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2442]
I randomly get an "unknown" with a red background when creating posts - maybe 15% of the time.

See screenshots.
![Screenshot_20220916-162949](https://user-images.githubusercontent.com/97898454/190728902-773b8c9e-f4cf-4722-8667-0512038c06fa.png)

![Screenshot_20220916-111146](https://user-images.githubusercontent.com/97898454/190728927-c2a18b59-e381-43c3-9c34-c975abdbdcef.png)

![Screenshot_20220916-104939](https://user-images.githubusercontent.com/97898454/190728950-2dbad6a6-491b-4b7d-b10d-e9444a18e4e2.png)

I have not worked out a way to repeat it - just seems random.

If I go back to the home page and recreate the post from scratch, then it always works that second time.

Thanks in advance for checking this out.

**Comment by dessalines** [comment]
Try changing your rate limits in `lemmy.hjson`, doing `docker-compose restart lemmy`, and see if the problem still occurs.
