### ISSUE TITLE
pictrs is clearing / removing any exif data: bug or feature

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2454]
pictrs is clearing / removing any exif data of an uploaded image, e.g. camera info or gps location. Is this by design or accidental? I like this feature, but need to know if it's by design. 
@asonix

**Comment by asonix** [comment]
Yes, that is intentional. It was one of the original motivations for building it. Maybe I should document that 😅

**Comment by sam365724** [comment]
Very good, thanks - please document it.
