### ISSUE TITLE
lemmyserver not checking auth (jwt cookie) for images

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2455]
### Issue Summary

A link to a picture is publicly accessible even for a private instance. The user requesting the image does not need to be authorized. This makes not much sense if all other content is hidden. Also there is a risk that an attacked abused an instance for private massive image hosting (could be done without even posting the image links).

As image requests are routed through lemmy-server anyway they should be checked against auth.

### Steps to Reproduce

1. Login to private instance
3. Upload image and copy link
4. open private browser window and access image

### Technical details

v 0.16.6

**Comment by dessalines** [comment]
This would have to be the case only for a private instance, because public instances should have those pictures openly accessible. 

I'd accept a PR for this.

**Comment by sam365724** [comment]
Yes only for private instances. 
Unfortunately I'm not very familiar with rust, so it would be super hard for me to implement. I guess it's not a lot of effort for you though, as you check auth in lemmy server already? Would be great to have this implemented soon in 0.17 or so.

**Comment by dessalines** [comment]
I'd rather have you do it. The check needs to be added here: https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/images.rs#L119

**Comment by IFcoltransG** [comment]
Looks like this can be closed.
