### ISSUE TITLE
Lemmy does not supply correct back link

### ISSUE THREAD

**Issue by utzer** [LemmyNet/lemmy#2459]
### Issue Summary

Lemmy does not return the correct URL to its posts to ActivityPub contacts (tested on Friendica and Mastodon). 

### Steps to Reproduce

1. Choose your favorite platform, Friendica or Mastodon.
2. Obtain a link to some post/comment on Lemmy.
3. Search for the Link in Friendica or Mastodon. 
4. See the post or comment and click on the Link to the remote post/comment. 

For example search for this [link](https://feddit.de/comment/75235), it is some comment on Feddit.de, you'll see the post, it will look like this, the red marked is the link to the remote post, or should be it. 

**Friendica:**
![Screenshot_2022-09-26_20-53-47](https://user-images.githubusercontent.com/8361662/192357763-607cb62b-4a72-48de-b6bf-33fe743cbde2.png)

This is linked to: https://feddit.de/comment/75235

**Mastodon:**
![Screenshot_2022-09-26_20-55-05](https://user-images.githubusercontent.com/8361662/192357723-bd2f5c57-d1b3-464b-9e62-578f88b69e6b.png)

This is linked to: https://lemmy.rollenspiel.monster/comment/501

The links return a 404 fault on either feddit.de or lemmy.rollenspiel.monster. 

In [this issue](https://github.com/friendica/friendica/issues/11937) over at Friendica they devs are suggesting to open an issue here and also imply that Lemmy does not supply the correct URL, it seems other systems do so. 

Please feel free to ask over there, the devs will be happy to help.

**Comment by utzer** [comment]
@Nutomic the other issue looks like some UI issue, this issue here is not UI related. Can you explain how this can be a duplicate then?

**Comment by dessalines** [comment]
That link will work in the next release, the comment threading stuff is done, just not released yet.

**Comment by utzer** [comment]
Ah, now it makes much more sense. Thanks.
