### ISSUE TITLE
Add Mastodon-style custom profile fields

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#246]
Can be either links or plaintext. Mastodon allows a maximum of 4 such fields. Example:

![Screenshot_20220801_200412](https://user-images.githubusercontent.com/1044450/182213079-e4fe1b6e-6faf-4fb9-b9e0-9a65d2ab56ae.png)

**Comment by growl360** [comment]
Flairs would be better than nicknames

**Comment by Nutomic** [comment]
This is basically done, we are just missing the 4 link fields. But I dont think thats important, I've already seen someone reproduce it with a markdown table. So I'd say we can close this issue.

**Comment by dessalines** [comment]
No I think we need this open, because those special URL link fields can be used to verify identity: 

IE like `<a rel="me" href="https://mastodon.social/@dessalines">Mastodon</a>`

**Comment by Nutomic** [comment]
Okay, but might be worth to open a new issue specifically for that identity verification, because it would need some additional work which isnt mentioned here.

**Comment by Nutomic** [comment]
Unnecessary.

**Comment by m-p-3** [comment]
Sorry to comment on a closed issue, but would it be a good idea to automatically add the `rel="me"` tag on all links in the Lemmy bio? That way they could be used to *verify* Lemmy accounts on Mastodon profiles without having custom URL fields like on Mastodon.

**Comment by dessalines** [comment]
That re-writing would probably be best in lemmy-ui. I'll re-open and transfer this.
