### ISSUE TITLE
Diesel async was released, use it with bb8

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2465]
Diesel async just had its first release, we could use it with the bb8 connection pool:

https://docs.rs/diesel-async/0.1.0/diesel_async/pooled_connection/bb8/index.html

**Comment by Nutomic** [comment]
According to the announcement here its not production ready yet.

https://old.reddit.com/r/rust/comments/xpo2dd/initial_release_of_dieselasync/
