### ISSUE TITLE
Cannot get lemmy:dev version to work: connection refused to lemmyserver

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2467]
### Issue Summary

`lemmy_frontend | FetchError: request to http://0.0.0.0:8536/api/v3/site?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6IjE5Mi4xNjguMS40MiIsImlhdCI6MTY2NDQ0MzYzNX0.UdJc5zWyGXgixHbu6UgAt_BEKskLkd281VVH2PGk0xo failed, reason: connect ECONNREFUSED 0.0.0.0:8536
lemmy_frontend |     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1483:11)
lemmy_frontend |     at ClientRequest.emit (node:events:513:28)
lemmy_frontend |     at Socket.socketErrorListener (node:_http_client:481:9)
lemmy_frontend |     at Socket.emit (node:events:513:28)
lemmy_frontend |     at emitErrorNT (node:internal/streams/destroy:151:8)
lemmy_frontend |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
lemmy_frontend |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
lemmy_frontend |   type: 'system',
lemmy_frontend |   errno: 'ECONNREFUSED',
lemmy_frontend |   code: 'ECONNREFUSED'
lemmy_frontend | }`

### Steps to Reproduce

1. I set lemmy-ui to lemmy server host in docker-compose: 
```
environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
```

Why does the request got to 0.0.0.0? Did something change on how to specify the lemmy server host compared to 0.16.7?

### Technical details

lemmy-dev docker containers from today Sept-29

**Comment by sam365724** [comment]
It seems that lemmy ui in debug mode sets the host, the root cause is that the ENV variables here are wrong: 
https://github.com/LemmyNet/lemmy/blob/main/docker/prod/docker-compose.yml
(and possible in other docker-compose as well)
They are named "LEMMY_INTERNAL_HOST" instead of "LEMMY_UI_LEMMY_INTERNAL_HOST".

The fix is to check and update all docker-compose files.

**Comment by sam365724** [comment]
Even wrong on https://github.com/LemmyNet/lemmy-ansible/blob/main/templates/docker-compose.yml

**Comment by dessalines** [comment]
The docker-compose file you linked to uses `lemmy-ui:0.16.6`, which doesn't use the new env vars.

**Comment by sam365724** [comment]
Ah, i see. But for dev i need the new env vars? There some discrepancy here. The compose files on main/dev should be updated then right? See my pull request.

**Comment by dessalines** [comment]
Yes. For dev, I don't use lemmy-ui images. I run `yarn start` in the lemmy-ui folder, and make sure I have my local nginx correctly routing requests to my local lemmy back-end.

**Comment by sam365724** [comment]
I see. So you don't have to rebuild the lemmy-ui container after each change.
