### ISSUE TITLE
Add a docker-compose prod example with nginx as reverse proxy and internal networks + ngxinx caching example

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2470]
May i add an additional prod_nginx folder to docker and add an annotated docker-compose with an integrated nginx reverse proxy similar to the updated dev docker-compse https://github.com/LemmyNet/lemmy/pull/2469?

Or should i update the prod/docker-compose to include an nginx? 
I honestly think that most people want nginx to be part of the docker stack. It would also be less confusing with the opened ports, etc. 

Just let me know, i'm pretty experienced with productive docker stacks and I've seen people running into too many issues with the setup here. This new docker-compose should just get everyone up and running within seconds and without any need for a reverse proxy outside the docker stack. I believe that with the lemmy stack architecture we should make use of the docker networking capabilities and not use opened ports on localhost as it's done now with ansible. 

Also i have an updated nginx that actually allows more caching. I think lemmy is not using any browser caching as of now. This can reduce traffic for images dramatically.

**Comment by dessalines** [comment]
> Just let me know, i'm pretty experienced with productive docker stacks and I've seen people running into too many issues with the setup here.

I think you're probably right. Its best if we don't rely on system installed nginx's, but include our own. I def welcome your expertise in building this out.

There's currently a `docker/dev/nginx.conf`, you could move that up a directory, make any changes you'd like to it, and have both the `dev/docker-compose.yml` and `prod/docker-compose.yml` use that.


> Also i have an updated nginx that actually allows more caching. I think lemmy is not using any browser caching as of now. This can reduce traffic for images dramatically.

That would be really useful, thanks. We have to remember to apply these updates to lemmy-ansible as well.

**Comment by Nutomic** [comment]
> I think you're probably right. Its best if we don't rely on system installed nginx's, but include our own. 

I dont think so. Nginx is directly exposed to the internet, so it needs to be kept up to date, which seems more likely with system package manager (eg using unattended-upgrades for security fixes). Also docker nginx doesnt allow you to run multiple different sites.

In general i agree though, the setup can likely be improved. Contributions welcome :)

**Comment by sam365724** [comment]
I see, you can easily setup automatic updates with docker too though (e.g. watchdog or future projects, or a simple docker compose up cronjob). 
Not sure why you think that docker nginx can not run multiple sites, i don't think that's true. 

Let's say we at least something that works easily and reliable for new users who just want to run a lemmy instance fully with docker. I guess most user will not start with ansible as a first step. 
Same for the dev environment, on which i'm working already.

**Comment by sam365724** [comment]
https://github.com/LemmyNet/lemmy/pull/2487

**Comment by dessalines** [comment]
Thanks for these!
