### ISSUE TITLE
Inbox says "1 Unread Message", clicking it shows no message

### ISSUE THREAD

**Issue by dginovker** [LemmyNet/lemmy#2471]
### Issue Summary

Inbox says "1 Unread Message", clicking it shows no message

### Steps to Reproduce

I do not have a repro at this time

### Technical details

On the current live version of Lemmy.ml (BE: 0.16.7)

Gif of the issue:

![lemmy in a nutshell](https://user-images.githubusercontent.com/32943174/193036353-78a69bac-162e-4f81-8bc5-e274c3b92f33.gif)

Potentially useful console screenshots:

![image](https://user-images.githubusercontent.com/32943174/193037103-4d44a472-4645-49f4-9338-ebe9f8e5bad4.png)
![image](https://user-images.githubusercontent.com/32943174/193037214-74d5f8d5-09c7-4fae-96a7-ae7e34f8d5f8.png)

**Comment by Nutomic** [comment]
This?

![Screenshot_20220929_224903](https://user-images.githubusercontent.com/1044450/193139307-91c8d897-1e6b-458d-a107-81f6476d90de.png)

**Comment by wravoc** [comment]
Still happening with comments like this one:
https://lemmy.world/comment/4203076

**Comment by dessalines** [comment]
Should be fixed by the new notification service, it'll be in the next release, and is available for testing on https://voyager.lemmy.ml
