### ISSUE TITLE
Reporting license violation

### ISSUE THREAD

**Issue by wahballat** [LemmyNet/lemmy#2476]
https://www.dwanya.co/ uses Lemmy's source but so far have refused to share back their changes and improvements that enable RTL using Lemmy.

**Comment by dessalines** [comment]
Whoa... they should really share that work, we've been needing RTL support for a long time. 

Could you or someone contact them for that? I don't speak Arabic or Farsi.

**Comment by wahballat** [comment]
> Whoa... they should really share that work, we've been needing RTL support for a long time.
> 
> Could you or someone contact them for that? I don't speak Arabic or Farsi.

They are Arabs and they speak English proficiently. I tried asking for it and they answered "we spent a lot of time and money on it, no". I am not affiliated with Lemmy nor am I a lawyer, there's nothing I can do about it beyond that.

**Comment by Nutomic** [comment]
Thanks for reporting this, I will get in contact with them.

**Comment by dessalines** [comment]
> we spent a lot of time and money on it, no

oof, not good. Thanks @Nutomic for doing that. I honestly don't care about anything other than them sharing their code... could you tell them that the license owners know about this now, and we won't not pursue legal action if they share their code.

**Comment by wahballat** [comment]
> > we spent a lot of time and money on it, no
> 
> oof, not good. Thanks @Nutomic for doing that. I honestly don't care about anything other than them sharing their code... could you tell them that the license owners know about this now, and we won't not pursue legal action if they share their code.

I can’t now. They banned me from their website, I don’t know why. Maybe because I asked them, maybe because they found this post.

**Comment by avidseeker** [comment]
Repo is moved to: https://github.com/dwanyaco/diwanya-ui
