### ISSUE TITLE
Consider using Wulf/dsync to auto-generate simple table functions

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2478]
This project takes a diesel schema file, and can auto-generate a lot of simple table CRUD functions for you. Might be useful.

https://github.com/Wulf/dsync

**Comment by Nutomic** [comment]
Came across this as well. As far as I understand, its not a macro which runs during compilation, but a helper tool for development, meaning we have to commit the generated code into git anyway. So you can use this as part of your dev process, to write code a bit faster, but in the end PRs would look identical with or without the tool.
