### ISSUE TITLE
Sent private messages are always marked as unread

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2484]
This makes it a bit awkward to use the api, when you want to do something like list all private messages, and show an indicator if there are unread items. It would be good if the `read` field could always be set to true, if my own user sent the message.

**Comment by dessalines** [comment]
I'm not sure I understand. https://github.com/LemmyNet/lemmy/blob/main/crates/db_views/src/private_message_view.rs#L89

If its unread, it will only show the unreads where you're the recipient. Otherwise, it will show all. The counts you should get from `GetUnreadCount`

**Comment by Nutomic** [comment]
I am showing both read and unread PMs together, with an icon that shows if there are unread messages in a given thread. Check out the latest commit in lemmybb repo.

**Comment by dessalines** [comment]
Here's your issue: https://github.com/LemmyNet/lemmyBB/commit/48e406f55793341327179a7a3f798d70c2eaaa11#diff-3387174908b768829664ae2d414a01c7562f6f8b50e51e484e3c35ffefc7a1d7R72

Don't get unread counts from the list of messages (the same not only goes for private messages, but also comments and mentions). Get the unread count from the `GetUnreadCount` endpoint.

**Comment by Nutomic** [comment]
Actually that line works just fine, the problem is here (that extra filter shouldnt be necesary): https://github.com/LemmyNet/lemmyBB/blob/main/src/routes/private_message.rs#L129
