### ISSUE TITLE
Non-functional registration at lemmy instance with gmail adress 

### ISSUE THREAD

**Issue by Bluetoothbrot** [LemmyNet/lemmy#2488]
### Googlemail addresses do not receive registration mails 

When registering in an lemmy instance it appears that Googlemail addresses do not receive emails.
Can anyone confirm this behaviour?

I'm not sure whether this is an internal mail server problem, Gmails behaviour regarding the internal mail server or some of the attributes of the domain or anything else...
It works with other mail providers though.

### Steps to Reproduce

1. Register with Gmail address in lemmy instance
2. Do not receive confirmation mail

So registration with a Gmail address is currently not possible?

**Comment by dessalines** [comment]
Did you check the spam folder? Google usually doesn't block the domain entirely, but considers emails from some domains as spam.

**Comment by Bluetoothbrot** [comment]
yep, for sure! neither in spam

**Comment by dessalines** [comment]
I spose I can't debug this without the postfix logs. I have an account using a gmail on one instance, and they go through fine, but google might have some weird rules for what they let through. If its sending correctly to other addresses, its not on the sending side.

**Comment by RGBok** [comment]
if anyone else has this issue, you have to configure correct SPF with your DNS.
