### ISSUE TITLE
CommunityLanguage::read() should return empty vec if all languages are selected

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2495]
Right now it just returns a list of all languages in that case, which means that the following command returns a total of 700 lines, listing all the languages.
`curl -H 'Accept: application/activity+json' https://enterprise.lemmy.ml/c/main  | jq .language`

This doesnt make any sense, it should just return an empty vec if all languages are enabled in db, analogue to how CommunityLanguage::update() called with empty vec means that all languages should be enabled. The same goes for LocalUserLanguage::read and SiteLanguage::read.

However im not sure how to write a query which achieves this.

**Comment by dessalines** [comment]
And the site_language and community_language tables do need to be populated, otherwise joins won't work. If they are equivalent tho, you could just turn them into empty vectors in code.

**Comment by Nutomic** [comment]
I dont want to change anything about the way data is stored in the db, i just want to change how its returned from read() functions. In Rust it would look like this:
```rust
  pub fn read(conn: &mut PgConnection, for_site_id: SiteId) -> Result<Vec<LanguageId>, Error> {
    use crate::schema::{language::dsl as language, site_language::dsl as site_language};

    let site_languages = site_language::site_language
      .filter(site_language::site_id.eq(for_site_id))
      .select(site_language::language_id)
      .load(conn)?;
    let all_languages: Vec<LanguageId> = language::language.select(language::id).load(conn)?;

    if site_languages.len() == all_languages.len() {
      Ok(vec![])
    } else {
      Ok(site_languages)
    }
  }
```
