### ISSUE TITLE
Simplify activitypub verifying

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2503]
There's a lot of double function calls, and duplicated code having to do with:

- Verifying the source of the incoming activity.
- Verifying activities coming in from activitypub.
- Verifying the objects themselves. 

`verify` is currently a trait function, but a lot of the code is repetitive, and could be turned into trait default functions, since `ActivityHandler` already knows the actor_id and item_id.

**Comment by Nutomic** [comment]
verify methods are removed in https://github.com/LemmyNet/activitypub-federation-rust/pull/21, just need to update to the latest version. Gonna close this issue now because we will most likely forget it later.
