### ISSUE TITLE
Admin-selected pinned / highlighted communities

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2504]
The trending communities on the lemmy-ui sidebar isn't too useful, and not that great for showing what communities your site has to offer. 

It would be better to have a list of admin-selected "highlighted" / pinned communities, shown both on the community page, and on the sidebar of the front page.

This would also be useful for lemmyBB's front page.

Related to #2068

**Comment by Nutomic** [comment]
In lemmyBB its not a simple list, but rather a `HashMap<String, Vec<Community>>`, like this:
```json
{
  "Open Source": [
    "https://lemmy.ml/c/opensource",
    "https://lemmy.ml/c/linux",
    "https://lemmy.ml/c/rust"
  ],
  "General": [
    "!main@voyager.lemmy.ml",
    "!lemmybb@lemmy.ml"
  ]
}
```
![Screenshot_20221021_120324](https://user-images.githubusercontent.com/1044450/197170364-2b1f8914-5779-4e8b-a358-07825ccd7517.png)

**Comment by dessalines** [comment]
This would entail adding a `HighlightCommunity` endpoint, doable by admins only, and a `highlighted` column to the community table. Wouldn't be too difficult.

**Comment by Nutomic** [comment]
This would also be useful to automatically subscribe new users to a predefined set of communities.

**Comment by dessalines** [comment]
We've removed trending communities from the sidebar now.

I can re-open this issue if necessary, but I think the site sidebar is the best place to highlight / display a list of admin-promoted communities. Another possibility would be a community specifically for promoting new communities.

Doing all the work and adding fields or endpoints for highlighting communities just seems like a waste, when the best place to display them is the site sidebar anyway.
