### ISSUE TITLE
Temporary instance blocks and reason

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2506]
Its common that we block instances due to spam accounts. In such cases, it would be good if admins could specify the block reason, so that we can check later if the block is still necessary, or can be reverted. Similarly, it would be useful to specify temporary instance blocks. Additionally, it would make sense to show instance blocks in the mod log.

**Comment by dessalines** [comment]
This would be possible, especially now that the blocklist is in the DB.

It would require:

- Adding reason and expires column to the blocklist table, similar to the mod_ban table.
- Adding specific API endpoints for the allowlist and blocklist: Add and Remove. Once #2285 is done, these are `Option<Vec<String>>` for `SaveSiteSettings`, and would need to be removed from there.

**Comment by ThisIsMissEm** [comment]
Would it also make sense to introduce federation severance notifications whilst implementing this? (I'm assuming that relationships are severed when an instance blocks another instance, in which case it's probably worthwhile users being notified of any relationships that were severed)
