### ISSUE TITLE
Make rate limiter and Federation settings live-updating

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2508]
Now that we're moving the rate limit settings from the config to the database, we need a way to read that from the DB, and update the rate limit singleton's config. Same for federation settings.

**Comment by dessalines** [comment]
@asonix We need to be able to make the rate limiter config live-update, but I'm unfamiliar with how this middleware works:

https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/rate_limit/mod.rs#L135

How would we go about altering this config after its been loaded as middleware?

**Comment by asonix** [comment]
Maybe with a watch channel: https://docs.rs/tokio/latest/tokio/sync/watch/index.html

Make the config a Receiver<Config> and then use Receiver::borrow() to access the current configuration

**Comment by dessalines** [comment]
I'm not too sure how that would work, because the ratelimited middleware only gets instantiated once (as a singleton), so it needs a function to update that config.
