### ISSUE TITLE
Controversial posts and comments

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy#2515]
Posts and comments ordered by most total votes but that are close to zero score. I guess this should only be available on instances with the downvotes active.

**Comment by dessalines** [comment]
I don't have time to do this but someone else could.

**Comment by iByteABit256** [comment]
Can I give this a try?

**Comment by dcormier** [comment]
@iByteABit256 I was just digging into this. 🫠 I came back to propose a calculation for "controversialness". You can have this one. I'll share where I was at, anyway.

I was thinking something like this (but implemented in SQL, similar to the existing `hot_rank` SQL function).

```rust
fn controversy_rank(upvotes: u32, downvotes: u32, score: i32) -> u32 {
    (upvotes + downvotes) / if score == 0 { 1 } else { score.unsigned_abs() }
}
```

Some examples of how this would work with various inputs can be seen [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cb1489d05738475b5a453d1cb07dbfee).

**Comment by iByteABit256** [comment]
Not bad, but it has a flaw that small changes in like/dislike ratio can lead to huge changes in "controversialness".

For example 98/100 ratio isn't that different than 99/100, but it would have half the score.

My thinking was something like this:

```
fn controversy_rank(upvotes: u32, downvotes: u32, score: i32) -> u32 {
  if downvotes != 0 { upvotes / downvotes * score.unsigned_abs() } else { 0 }
}
```

Which seems more intuitive to me and gives more balanced scores, what do you think?

**Comment by dcormier** [comment]
> it has a flaw that small changes in like/dislike ratio can lead to huge changes in "controversialness".

Does it matter? Will that value be shown, or used for anything other than sorting the comments?

**Comment by dcormier** [comment]
> My thinking was something like this:
> ```rust
> fn controversy_rank(upvotes: u32, downvotes: u32, score: i32) -> u32 {
>   if downvotes != 0 { upvotes / downvotes * score.unsigned_abs() } else { 0 }
> }
> ```

[The results for that are surprising.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b844c7c2b9e24167271d0d5a3180d80d) 100 upvotes and 100 downvotes results in 0 controversialness. The same as if something has 0 upvotes and 100 downvotes. Similarly, I would expect these to have the same level of controverialness, but they don't:

```rust
    assert_eq!(5, controversy_rank(50, 45, 5));
    assert_eq!(0, controversy_rank(45, 50, -5));
```

**Comment by iByteABit256** [comment]
You're right, it needs some work. Also, what I was thinking for the multiplier was actually `(upvotes + downvotes) `to represent activity, since a 50-50 post with 2 total votes is much less controversial than a 50-50 post with 1000 votes.

**Comment by dcormier** [comment]
Yeah, that's what I was thinking, too. The total number of votes should be significant, here. 

It's definitely worth exploring.

Here's something to show the output better and let you fiddle with the math more. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=88700cc0210c942e0363e8fa1873f040

**Comment by iByteABit256** [comment]
[Printing it out as a table](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0875f9385ffa34e0a7ffd6533337f286) made it quite clearer, I think it's good enough to keep

**Comment by dcormier** [comment]
I agree. It seems good. I'd like to see some more people chime in with opinions, but maybe that'll come with a PR. At the very least, it's something that can be moved forward with.

**Comment by iByteABit256** [comment]
That's proof enough haha, really cool!

**Comment by dcormier** [comment]
Looking that that output makes me think it might be worthwhile to subsort by something like activity (descending), or some other existing sort. Things that aren't controversial get low numbers fairly quickly and otherwise may result in inconsistent ordering (if that's important in any way).

**Comment by jamesmcm** [comment]
It might also be helpful if the "controversy score" were visible in the UI when sorting this way too.

**Comment by qznc** [comment]
To throw in another idea:

    min(upvotes, downvotes)

However, its primary advantage is that it is simpler, so easier to understand for user.

**Comment by qznc** [comment]
Btw [reddit's algorithm in 2015 is here](https://github.com/reddit-archive/reddit/blob/master/r2/r2/lib/db/_sorts.pyx#L60).

**Comment by JediMaster25** [comment]
That seems like it has worked well in the past.

```
cpdef double controversy(long ups, long downs):
    """The controversy sort."""
    if downs <= 0 or ups <= 0:
        return 0

    magnitude = ups + downs
    balance = float(downs) / ups if ups > downs else float(ups) / downs

    return magnitude ** balance
```

**Comment by iByteABit256** [comment]
[Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0039c0d9f91bff88fd58ec6425380f90) is a comparison between @dcormier's, @qznc's and Reddit's method.

Reddit's looks like the most correct overall, but @dcormier's looks almost as good but much more performant since it doesn't involve float arithmetic and powers. @qznc's is the most performant, but the results are quite worse judging from this

**Comment by dcormier** [comment]
That's not a very effective way of benchmarking in this case, unfortunately. The results are wildly different from run to run, and even within the same run. I.e., not only do the number change quite a bit from run to run, but within the same run two algorithms that had similar times in one run might have disparate times in another. Using [`cargo bench`](https://doc.rust-lang.org/cargo/commands/cargo-bench.html) (requires nightly) or [Criterion.rs](https://docs.rs/crate/criterion/) would show differences more clearly.

Regardless, it's probably not worth benchmarking that in Rust. The [existing `hot_rank` function](https://github.com/LemmyNet/lemmy/blob/d97ff65fe1e9c31e9f7c977a66100816816e07be/crates/db_schema/src/utils.rs#L216) used to produce the value to sort by when sorting on `hot` lives in SQL, not Rust. I would expect this function to end up being similar.

**Comment by iByteABit256** [comment]
I had a pretty lucky streak when I first wrote it but yeah, unfortunately it seems completely indeterminate now that I tried it again some times
