### ISSUE TITLE
Wrong error message on password change

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy#2521]
### Issue Summary

Error "Invalid password. Password must be <= 60 characters." displayed when password too short (or possibly other criteria not matched?)

### Steps to Reproduce

1. Change password in setting to "hello"

### Technical details

lemmy recent dev version and in 0.16.7

**Comment by sam365724** [comment]
Error text is just wrong i guess: https://github.com/LemmyNet/lemmy-translations/blob/94b9b5debdaa40facf13a852cb096ef0cbd34ad7/translations/en.json#L236

It should also mention the minimal length of 10 characters?!

**Comment by Nutomic** [comment]
Only condition is that the password has between 10 and 60 characters. I fixed the error message, thanks for reporting!

https://github.com/LemmyNet/lemmy-translations/blob/main/translations/en.json
