### ISSUE TITLE
Federate post moderation Activities

### ISSUE THREAD

**Issue by mediaformat** [LemmyNet/lemmy#2522]
### Issue Summary

Followed communities Federate posts via Announce activity. When spam (or worse) content is posted, the community actor will Announce it to all followers. However when this content gets removed from lemmy servers, it doesn't seem that the local {Delete {object}} nor {Undo {Announce}} is federated, resulting in removed content still appearing in (ActivityPub) Community timelines. 

### Steps to Reproduce

1. Visit a community, ex: https://lemmy.ml/c/fediverse/ via a remote instance (Mastodon for example)
2. Visit this [community](https://lemmy.ml/c/fediverse/) via the web and compare the visible posts
3. The web view on the instance lemmy.ml is Moderate (no apparent spam)
4. The remote view of the community/group actor timeline shows:
 - A local [spam post](https://lemmy.ml/post/547327) dated Oct. 17th
 - Remote (offensive) Posts dated Oct. 18th 

#### Local (moderated) community timeline 
![Screen Shot 2022-10-31 at 11 14 40 AM](https://user-images.githubusercontent.com/2895351/199068384-d89d53f7-2e27-4b17-af24-564e1660b281.png)
#### Remote view of community timeline (seemingly unmoderated) 
![Screen Shot 2022-10-30 at 4 41 55 PM](https://user-images.githubusercontent.com/2895351/199067994-72153859-35fe-44c6-bbc0-720eb35b0ecb.png)

Perhaps related to this [Meta-moderation issue](https://github.com/LemmyNet/lemmy/issues/2277)

**Comment by mediaformat** [comment]
From my testing Mastodon works with Undo/Announce activity, and Delete for Posts

**Comment by Nutomic** [comment]
Lemmy doesnt send any Undo/Announce, so thats not compatible. I think you should ask Mastodon to support receiving Announce/Delete activities which Lemmy sends.

**Comment by mediaformat** [comment]
Sorry, I've combined 2 separate cases but both are related to the Group's outbox activities, and have more to do with spec than Mastodon.

1. In the case of a local [spam post](https://lemmy.ml/post/547327), the problem may not be sending an `Announce/Delete/Page`, but more that this post is still fully fetchable and should be replaced by a [Tombstone](https://www.w3.org/TR/activitypub/#delete-activity-outbox). 
2. In the case of a remote post, the Group actor doesn't have the authority to `Announce/Delete` a post that also hasn't been deleted.

In both cases because the Group Actor is only a relay doing `Announce`, its (federated) outbox contains the original `Announce/Create/Page` activity, and adding/sending a new `Announce/Delete/Page` doesn't remove or negate the 1st Announce, this is because `Announce` is an `Undo`able [activity](https://www.w3.org/TR/activitypub/#undo-activity-inbox).

**Comment by Nutomic** [comment]
Your first case is definitely a bug, thanks for reporting. 

Im not quite sure what you mean with the second case. Do you mean that group outbox contains `Announce/Create/Page` activity for pages which were deleted? That shouldnt happen because there is a check in the code. There is an `Announce/Delete/Page` send for items which are removed by mod, although it isnt included in the outbox.

> Edit: In case 1, I'm not sure how Lemmy backend works, but the Group actor also would not have the authority to send a Delete activity about the post, the original post Actor would be the one to do so (maybe the moderator triggers this).

I dont know how you define the authority, but Lemmy does send `Announce/Delete/Page`, including for remote objects which are removed by a community mod.

**Comment by mediaformat** [comment]
> I dont know how you define the authority, but Lemmy does send Announce/Delete/Page, including for remote objects which are removed by a community mod.

Pardon my assumptions here, as I haven't inspected payloads. My reading of the spec is that only the original `Person` actor has the authority to delete posts they have created. So a `Group` actor sending `Announce/Delete/Page` would be ignored by other implementations, unless the group actor is just doing `Announce`, of the person actors `Delete/Page`. 

Again I don't know if other implementations support that, because of the `Undo` able nature of `Announce`. 
Either way the side effect `Undo/Announce` is that other servers remove the announced post from feeds.

**Comment by mediaformat** [comment]
The ActivityPub spec is a bit more opinionated in this regard
https://www.w3.org/TR/activitypub/#delete-activity-inbox
> The side effect of receiving this is that (**`assuming the object is owned by the sending actor / server`**) the server receiving the delete activity SHOULD remove its representation of the object with the same id, and MAY replace that representation with a Tombstone object. 

Anyhow, hopefully the Activity semantics are inconsequential and those commits are enough to smooth out the interoperability!

**Comment by Nutomic** [comment]
In this case you can consider that the object is owned by the Lemmy group, not by the person that created it. So i would consider it a question of documentation.

Gonna close this issue, if mod actions still dont federate, you should probably open an issue with Mastodon.
