### ISSUE TITLE
Upgrade 0.14.3 to latest version

### ISSUE THREAD

**Issue by gnh1201** [LemmyNet/lemmy#2523]
Hello.

I previously built a community using Lemmy, and I'm going to upgrade this version.

I am using a custom port (51080) instead of general web(80/443) ports. In my experience, I understand that changing the address of the Lemmy instance requires deleting all user information.

What about now? Do I still have to give up my user information to change my address?

**Comment by dessalines** [comment]
Where are you finding these ports? And changing a port is not changing a domain name, so no you shouldn't have to delete anything.

Please follow the official install and upgrade instructions: https://join-lemmy.org/docs/en/administration/administration.html

**Comment by dessalines** [comment]
Changing a port is not changing a domain name. Could you be more specific, I don't understand your question.

**Comment by gnh1201** [comment]
Okay. My instance is https://catswords.info:51080/

I was looking for a way to change the port during installation and included the port in Lemmy's domain name.

I tried to change it to a regular web port, but all of the URL-dependent metadata (e.g. actor_id, priv/pub key, etc.) was broken and could not be changed.

At that time, the solution was to abandon all user and community information except content.

**Comment by dessalines** [comment]
Including the port in the domain name wasn't a good idea, I'm not sure what installation method you used. You could change the domain name to remove the port, but it would break federation. 

I highly recommend just reinstalling using ansible or docker, and follow the instructions closely.

https://join-lemmy.org/docs/en/administration/administration.html

**Comment by Nutomic** [comment]
You could also rewrite all the url fields in database to remove the port. In particular, these should be: `site.actor_id`, `person.actor_id`, `community.actor_id`, `post.ap_id`, `comment.ap_id`. Private and public keys are fine, no need to change them.
