### ISSUE TITLE
Commenting from non-Lemmy stopped working?

### ISSUE THREAD

**Issue by snan** [LemmyNet/lemmy#2525]
I used to be able to comment just fine from my instance running Mangane (fork of Pleroma), [here is an example from a while back](https://lemmy.ml/post/433877).

But today none of my comments have shown up, did something change?
🤷🏻‍♀️ 

For example, I commented on [this post](https://beehaw.org/post/175515?scrollToComments=true) right [here](https://idiomdrottning.org/notice/APBvF44LF9GFDFu2NM).

My instance isn't blocked according to Beehaw's list.

**Comment by snan** [comment]
[This thread](https://beehaw.org/post/175021) is probably a better example.

**Comment by dessalines** [comment]
I was able to sync the comment manually doing a search from beehaw. But neither show your instance in the linked instances page: https://beehaw.org/instances

@Nutomic I'm not sure how this one works.

**Comment by snan** [comment]
Normally I've been able to comment without being linked just as long as it's not one of those instances that only allow from an allow list, like http://merv.news

**Comment by snan** [comment]
[One of my comments did belately show up](https://beehaw.org/post/172464?scrollToComments=true). Weirdness within weirdness 🤷🏻‍♀️

**Comment by Nutomic** [comment]
I contacted Chris (Beehaw admin) to check the logs for any errors that might be related. Do you know if there were any recent changes on your instance, like a version upgrade? And can you still comment in Lemmy communities which are hosted on other instances?

> But neither show your instance in the linked instances page: https://beehaw.org/instances

At least in 0.16, this list is built only from communities.

**Comment by snan** [comment]
I haven't upgraded in a while and I don't think anything has changed on my end. (I realize that an issue like this is super hard to troubleshoot.)

Is there some, uh, "test threads" I can comment on?

**Comment by Nutomic** [comment]
You can use these:

https://lemmy.ml/c/test
https://voyager.lemmy.ml/

**Comment by snan** [comment]
The [comment appeared](https://lemmy.ml/post/553435?scrollToComments=true) only after someone replied.

**Comment by Nutomic** [comment]
So theres nothing useful in the Lemmy logs. Can you check with the admins of your instance if there are any error messages being logged when sending something to Lemmy?

**Comment by snan** [comment]
Good idea! I checked now with `journalctl`. No sending-related errors.
