### ISSUE TITLE
Include last reply 

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2530]
For lemmybb it is necessary to show the last reply for each thread/community when browsing overviews.

![Screenshot_20221103_124940](https://user-images.githubusercontent.com/1044450/199713459-0b6a041d-fe24-44e5-9d4f-a451b6d2472c.png)

![Screenshot_20221103_124949](https://user-images.githubusercontent.com/1044450/199713477-b847f491-4747-4626-9a97-a8b0fa5a3661.png)

For now im generating these by fetching comments in each thread with additional api calls, but this is very inefficient, and doesnt work at all unless you increase the rate limit. Current code is in [this file](https://github.com/LemmyNet/lemmyBB/blob/main/src/api/extra.rs). 

It would be good if we could upstream this into Lemmy, and include details about the last reply with `GET /api/v3/community` and `GET /api/v3/community/list`. So it should probably be part of CommunityView. 

One complication is that both posts and comments should be considered for last reply, so wed need a new datatype. However we could simplify it and only consider comments.

**Comment by dessalines** [comment]
I could def see both `last_post` and `last_comment` being useful. Doing it for CommunityList might be a tricky query, but doing it for the single community would be simple.

**Comment by Nutomic** [comment]
Closing this as lemmybb is unmaintained and unused.
