### ISSUE TITLE
Escape URL-unsafe characters in DB connection string

### ISSUE THREAD

**Issue by egasimus** [LemmyNet/lemmy#2532]
### Issue Summary

I like my passwords with extra weird characters. However Lemmy seems to do naive string templating when building the PostgreSQL connection string. So if the password happens to contain e.g. a colon, the whole thing break.

### Steps to Reproduce

Set a DB password containing a URL-unsafe character in `config.hjson`, and try to launch Lemmy.

### Technical details

Maybe you gotta percent-encode the data from the config that goes into the connection URL?

**Comment by dessalines** [comment]
Seems like something we shouldn't support, especially since the ansible install auto-generates a safe password anyway. What's preventing you from using a character only DB password?

**Comment by dessalines** [comment]
Ansible is how you install lemmy, from our docs: https://join-lemmy.org/docs/en/administration/administration.html

Read the link I provided you over in the other thread for why you shouldn't use special characters for postgres passwords, db names, etc.

**Comment by dessalines** [comment]
> Also what mandates the 60 char max password length enforced by the frontend? You guys are hashing em, right?

Hashing passwords is resource intensive, and some limit is necessary no matter what. No unhashed passwords are stored in the DB, we are hashing them with https://github.com/Keats/rust-bcrypt

**Comment by dessalines** [comment]
No probs, just know that DB connection strings / URLs are finicky, which is why pretty much every app you'll see uses no special characters for the DB password.
