### ISSUE TITLE
Include unread notifications in /api/v3/site

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2539]
Lemmybb needs this on every page for rendering the header. This means it needs to do 3 additional API requests for every page load (also see https://github.com/LemmyNet/lemmy/issues/2441). 

To optimize this, it would be good if unread notifications could be included directly in the output of /api/v3/site for logged in users.

https://github.com/LemmyNet/lemmyBB/blob/main/src/site_fairing.rs#L125

**Comment by dessalines** [comment]
Shouldn't you only need to call `GetUnreadCount` for every page?

Might be dangerous to *also* bundle it with `GetSite`, because it would be redundant, and we need one source of truth for that.

**Comment by Nutomic** [comment]
![Screenshot_20221107_132950](https://user-images.githubusercontent.com/1044450/200310762-be143832-c6c7-469f-8981-2055b0e04ec7.png)

It also shows a preview of the notifications in a header dropdown. And whats the problem with redundancy, anyway the data is retrieved with a database call, so the db is the single source of truth.

**Comment by dessalines** [comment]
I could see including the counts in getsite, but the API calls for the content of the 3 notif types should probably still be separate. And since its a dropdown, you can call it when they click the "expand notifications" thing.
