### ISSUE TITLE
Search by domain in URL search

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy#2542]
When I write `youtube.com` in the lemmy URL search I expect to see every post with a link to youtube. Right now URL search only works for exact matches, which isn't very useful.

**Comment by JediMaster25** [comment]
It would also be nice if searches that start with `https://` where searched directly as URL search.

Also the URL search could include urls in the post bodies besides the url field.

**Comment by Nutomic** [comment]
Closing in favor of https://github.com/LemmyNet/lemmy/issues/4748
