### ISSUE TITLE
increase character limit for post body

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmy#2546]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

It is not possible to publish long posts.

### Describe the solution you'd like

Remove the limit so that much longer posts can be created.

### Describe alternatives you've considered

Set the limit **much** higher

**Comment by dessalines** [comment]
Post titles, or post body? The titles should be pretty short, they are the headlines, and if they got too long, a single post row would take up an entire screen on some devices.

**Comment by Tealk** [comment]
Oh sorry, i mean the body.

**Comment by Tealk** [comment]
Then I would suggest 50k, so that even larger contributions can be written without problems.

**Comment by dessalines** [comment]
I'll create another lemmy-ui issue for this, because it needs both a back end and front end check.
