### ISSUE TITLE
Links to comments do not point to the right content

### ISSUE THREAD

**Issue by developedby** [LemmyNet/lemmy#2547]
### Issue Summary

Comments on lemmy can be accessed through an unique comment id that seems to be attached to the instance of the person making the comment (eg. [https://feddit.de/comment/82395]). On lemmy-ui, this link is accessible next to the name of the commenter, just right to the link to the comment relative to the current post (eg. https://lemmy.ml/post/589877/comment/331555).

It seems that this first link never points to the actual comment, either resulting in a 404 or pointing to some other comment.

This id seems to be the correct number. In a private instance that I created that only has 2 comments, the ids for the two comments are `1` and `2` as expected, but they result in 404s. Because of this, I believe it's a lemmy bug, and not a lemmy-ui / lemmybb one.

### Steps to Reproduce

404 Example:
- Go to https://lemmy.ml/post/589877.
- Order by "old" and go to the first comment, saying "I don’t think anyone would have a problem with it as long as you post in a related community"
- Click on the link to the comment (the colored graph icon). It should be https://midwest.social/comment/116247.
- Look that it leads to a 404 instead of the comment.

Wrong content example:
- Go to https://fedibb.ml/view_topic?t=2
- Click on the link of the first response (again the colored graph icon). Should be https://fedibb.ml/comment/4.
- See that it leads to a different post.

### Technical details
Logs don't show anything

**Comment by Nutomic** [comment]
> Wrong content example:
>
> - Go to https://fedibb.ml/view_topic?t=2
> - Click on the link of the first response (again the colored graph icon). Should be https://fedibb.ml/comment/4.
> - See that it leads to a different post.

Just fixed this: https://github.com/LemmyNet/lemmyBB/commit/a07abab123f93323b18557f6df1ddf9be0a4e459

**Comment by dessalines** [comment]
> It seems that this first link never points to the actual comment, either resulting in a 404 or pointing to some other comment.

The next update of lemmy includes better comment trees, and the `/post/post_id/comment/commentid` will be going away in favor of `/comment/id`
