### ISSUE TITLE
Sending Reports via mail

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy#2551]
Is it possible, to send reports and registration applications via mail to the administrator and/or moderators. Maybe optional to a configurable email address?

I'm using Zammad as support platform to keep incidents clean. Would be nice, if I could get notifications about new reports or applications directly as a ticket in Zammad.

**Comment by dessalines** [comment]
We already have a setting to email admins for new registrants, but I spose we could also add one to email admins when getting a report.

**Comment by kromonos** [comment]
> We already have a setting to email admins for new registrants

Looks like I'm blind. I can't find the setting :(

**Comment by dessalines** [comment]
Pry just hasn't been released yet, but its already merged, and will be in the next release.
