### ISSUE TITLE
Documentation - incorrect URL in getting-started section

### ISSUE THREAD

**Issue by bradmacpherson** [LemmyNet/lemmy#2552]
### Issue Summary

In the Docker Installation section of https://join-lemmy.org/, one of the URLs is missing the `prod/` path part.

### Steps to Reproduce

1. Navigate to [Docker Install](https://join-lemmy.org/docs/en/administration/install_docker.html) and copy/paste the commands to download Lemmy configuration.
2. Downloading `lemmy.hjson` will fail.

### Technical details

```
# wget https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/lemmy.hjson
--2022-11-11 11:19:52--  https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/lemmy.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-11 11:19:53 ERROR 404: Not Found.
```

The correct URL is https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/prod/lemmy.hjson

**Comment by Nutomic** [comment]
Thank you for reporting this. The fix should be deployed automatically by tomorrow.
