### ISSUE TITLE
How can we host each docker-compose.yml separately?

### ISSUE THREAD

**Issue by rishabh-modi2** [LemmyNet/lemmy#2555]
I wanna host lemmy on railway.app. It does not allow docker-compose so i had to deploy each service separately. Is There any way to use Custom urls(https) for lemmy api and pictrs in lemmy-ui image?

**Comment by dessalines** [comment]
Yes, check the configuration variables here. 

https://join-lemmy.org/docs/en/administration/configuration.html

If that pictrs location block doesn't work, try this one: 

https://github.com/LemmyNet/lemmy/blob/main/config/defaults.hjson#L19

Check the ansible template here for the env vars for lemmy-ui: https://github.com/LemmyNet/lemmy-ansible/blob/main/templates/docker-compose.yml#L17

**Comment by rishabh-modi2** [comment]
@dessalines One more question.

Do we need to store images locally in lemmy instance?

For eg. If we deploy pictrs in instance b and ises instance b pictrs url in lemmy so would it work? We do not wanna save any image in lemmy instance storage.

And how can we use imgur or reddit images inplace of local image storing?

**Comment by dessalines** [comment]
> Do we need to store images locally in lemmy instance?

You could just not include the pictrs block, so picture uploads won't work. Or you could host pictrs elsewhere.

> And how can we use imgur or reddit images inplace of local image storing?

You can use image urls as the post url, but they must be the actual image link (imgur has them, but they don't make it easy to find). Also remote images currently work in markdown bodies too.

**Comment by rishabh-modi2** [comment]
Thanks for reply. Once we done with our instance. Like hosting pictrs elsewhere and adding imgur option. I will drop the setting we changes and all here.
