### ISSUE TITLE
How do we add a second moderator to a community

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2558]
What's the question you have about lemmy?
Somebody has set up a community on my instance and wants to add a second moderator and cannot work out how to do so.

I have had a look and cannot work out how to do it either.

Can you tell me how:
1. An existing moderator can add an additional moderator to an instance, and
2. The instance owner can add an additional moderator to any instance.

Thanks in advance

**Comment by Kap2022** [comment]
2 more questions:
1. Does the person they are trying to add as a moderator need to be a user on my instance or can they be a user on another instance.
2. Can a user of say lotide.fbxl.net be made a moderator of a community on my instance or do they need to be a user on my instance?

These are not feature requests, just looking for answers, so I can provide the correct info to the questions I am being asked.

Thanks again.

**Comment by dessalines** [comment]
Instances have admins, communities have moderators.

All mod actions are done on comments or posts, so click the three dots and, appoint as admin.

You can appoint federated moderators, but not federated admins.
