### ISSUE TITLE
Automatically remove deleted accounts as community mods

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2560]
### Issue Summary

After a user deletes their account, it can still be listed as community moderator. Check the link below for an example, [@ericbuijs](https://lemmy.ml/u/ericbuijs) is listed as mod but the user is deleted.

https://lemmy.ml/c/mastodon

### Steps to Reproduce

1. Be community mod
2. Delete account
3. Account is still listed as mod

**Comment by dessalines** [comment]
If there are no other mods, we should also transfer their community to an admin.

**Comment by Bakcodi** [comment]
This is still a problem. There seems to be no way to delete and replace such a mod.
