### ISSUE TITLE
Custom embed code 

### ISSUE THREAD

**Issue by rishabh-modi2** [LemmyNet/lemmy#2563]
It would be great if site hosters could set embed codes for their sites.

For eg. 
Embed code for our html site "https://videoplayer2.rishabh.gq/rvideo2/?url=3znfhlyy640a1" should be 

`<div class='embed-responsive embed-responsive-16by9'><iframe src='https://videoplayer2.rishabh.gq/rvideo2/?url=3znfhlyy640a1' height='360' width=100% allowfullscreen=True></iframe></div>` 
If user enter this url in url section.
-------

We also have a video uploader site which uploads video and return the video direct link. So it would be great if we can add a feature to use the specific embed code for a specific domain.

---

If this is not possible is there any way to change user emebed_html code using admin bot account.?

**Comment by dessalines** [comment]
This is a lemmy-ui issue, and iirc there is already an issue for disabling csp and allowing potentially dangerous html.

**Comment by rishabh-modi2** [comment]
Thanks for reply
