### ISSUE TITLE
API: Simple authentication via JWT (even without a local user account)

### ISSUE THREAD

**Issue by hbroer** [LemmyNet/lemmy#2576]
### Is your proposal related to a problem?

I am planing a PWA which combines at least two applications: Lemmy and Mastodon. The user should only register and login one time. I plan to build a (open source) auth service (using the Mastodon API) and then use the Lemmy API with the generated JWT from that service.

### Describe the solution you'd like

No Lemmy user account needed to access the API. The JWT contains `@username@example.com` as subject and the role of the user. The user data will be fetched via ActivityPub API similar to how it is done when a federated user replies to a post. The roles can be mapped via config file. The issuer should be in a whitelist in the config file too. 

Context: 
- Lemmy server does not allow registration
- Lemmy server runs headless, no Lemmy UI used
- Lemmy server only federates with the Mastodon server
- Mastodon server runs headless too
- Custom open source microservice to get a JWT with username and role from the Mastodon API
- All Custom UI (PWA, maybe open source later too)

### Describe alternatives you've considered

I did not found another solution. It may be possible with OAuth in some way but I think that is a little too complex for this task. It also looks like it could be just a "small" change to Lemmy to make this possible because the API already uses JWT. But I can be wrong.

### Example JWT

```JWT
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJAdXNlcm5hbWVAZXhhbXBsZS5jb20iLCJpc3MiOiJhdXRoLmV4YW1wbGUuY29tIiwicm9sZXMiOiJhZG1pbiIsImlhdCI6MTY2ODk4NTIwMCwiZXhwIjoxNjY4OTg3MDAwfQ.G2tR9Uosd08IioCS4U0dw0JryEfQIieVE9o0O2apPKI
```
(public/private key pair should also be supported, this is just an example)

Payload:
```json
{
  "sub": "@username@example.com",
  "iss": "auth.example.com",
  "role": "admin",
  "iat": 1668985200,
  "exp": 1668987000
}
```

### Background

The Idea of this project is to combine microblogging application similar to Twitter with a application similar to Facebook groups and the classic bulletin boards. Maybe even more later.

### Benefit for Lemmy

It can be combined with any other application which supports ActivityPub if someone wants to combine them. It only needs a microservice to generate the JWT. Workflow: User logs into the main application, the WebApp requests the JWT from a custom microsorvice, the WebApp can now access the Lemmy API. This is not Mastodon specific.

**Comment by Nutomic** [comment]
I think you misunderstand how JWT works. It is basically a token which contains login details *for a specific account* and *is signed by the servers private key*. So first of all, you cant jwt to access Lemmy without a Lemmy account. The token also needs to be signed by Lemmys private key. Federation also doesnt allow performing actions as a remote account in the way you think.

So in any case you will have to create a separate Lemmy account if you want to write any posts from Lemmy. Then you would have one jwt token for Lemmy and one for Mastodon. Alternatively you could fetch federated objects on Mastodon and write responses there, while using the Lemmy API for reading only.

OAuth is not necessary for all this, but afaik would mainly make things more secure.

**Comment by dessalines** [comment]
> I am planing a PWA which combines at least two applications: Lemmy and Mastodon. The user should only register and login one time.

Then create two accounts for the two different services, log into them each, and save the tokens. Both have open APIs so you could easily automate this.

**Comment by hbroer** [comment]
@Nutomic No I understand how JWT works. But I may have missing knowledge in the ActivityPub ecosystem and for sue how internals of Lemmy and Mastodon work. 

Lemmy does not need a local account for a User. It would also be a problem because a automated copy of one user is still another user. Lemmy should not link the Post to a local user in this case, but should link it to the Mastodon user (`sub` from the JWT). If posting trugh Mastodon API to Lemmy would work then sure that can be done. But for now that does not work. JWT is great for micoservices, and I think of Lemmy as a microservice in this case, which don't need to know anything about users, only how to get information they need (in this case that's ActivityPub -> Mastodon). Lemmy get the pub key, my custom service get's the private key, it is signing the JWT after checking the usertoken with its apptoken over the Mastodon API. Lemmy get the JWT via API requests and can then see if the request is allowed or not.

@dessalines That will not solve the problem because then there is another user. The Post has to be related to `@name@example.com` and not to `@name@lemmy.example.com`. 

But because You just closed it I will go and search for another solution. Thank you, great discussion.

**Comment by dessalines** [comment]
Lemmy absolutely does need you to register locally to be able to do anything other than view it. a " jwt token without an account" makes zero sense, you need to learn about what a JWT token is.

**Comment by hbroer** [comment]
Yes currently Lemmy needs a local account to allow posts because the posts are related to a local user. But instead it could relate to a remote user. Then what Lemmy needs is something which tells it if a request is ok or not. English is not my native, but I absolute know what JWT can do and that it can't. JWT in this proposal is just the signed data which gives Lemmy everything it needs to know.

But it makes no sense to discuss this further because you closed it without any understanding of my intention and tell me that I don't know anything about JWT. Funny because it looks like you don't understand how service-oriented architecture works and what JWT can achieve. Because you just use it as "better" Session key with the ascending int userID only. So you always need to query the DB to even get the userGroup instead of using the signed data from the JWT.

But who cares. I am out. It was way too unfriendly here.

**Comment by Nutomic** [comment]
For this to work, Lemmy would have to take the JWT and pass your request on to Mastodon, essentially serving as a proxy. That would require a lot of complexity, and wouldnt have any advantage over sending your request to Mastodon directly.

**Comment by hbroer** [comment]
@Nutomic Not sure why you think that Lemmy need to pass the JWT to Mastodon?

1. User authenticates against Mastodon API and get a Usertoken via WebApp
2. WebApp requests JWT from custom Microservice with that Usertoken
3. Microservice requests userdata via Mastodon API with usertoken and respond with signed JWT containing `role` and `sub` (full username like `@user@example.com`)
4. WebApp requests Lemmy API with JWT to post in _whatever_
5. Lemmy verifies the JWT with pub key and if fine then just creates a post linked to `@user@example.com` instead of a local user, if more userdata is needed no problem, everything can passed via the JWT. No need for Lemmy to request anything from Mastodon. But for sure it could query Mastodon with the  username and domainname it knows (`@user@example.com`) via ActivityPub to get the user details. There is no JWT needed. This works already, else Lemmy could not federate.
6. Done.

Note: I absolutly know what JWT can offer but I don't know much about ActivityPub. I don't know if Lemmy can create posts in the name of a User from another instance and send out the notification via ActivityPub. BUT at least I can comment via Mastodon so it may be possible, that's something I can't answer. But it is also not important that Lemmy would send a notification out of that action. The WebApp can ask the User if he want to make a "tuut" of his group post.

If you both woulnd't have had that focus on JWT, and still have, and instead on how I can solve the problem instead, or what the limitations are with AcivityPub in this case, then I would have loved some feedback. I don't get why you focus on the JWT because that is absolute not any problem here. Closing this Issue with a "solution" which is absolute off, did make it only worse.

I came to the point where I only setup Mastodon for now, will do the custom UI and then will build a groups microservice myself. Sometimes it is better just to create things instead of using other peoples work and ask for help. ^^ Lemmy evalution server is deleted. Like I said, I am out. I rly tried to make clear what my intention is, it took me 3 hours to create the Issue... just sain.

Only for Info, this is the very simplified plan of the infrastructure:
![image](https://user-images.githubusercontent.com/14164004/203417921-41bb15d1-4397-46cf-bb9b-aa82c173e408.png)

**Comment by dessalines** [comment]
> I don't know if Lemmy can create posts in the name of a User from another instance and send out the notification via ActivityPub.

We've answered this with no three times now. You must register a lemmy account to be able to do actions, and it will give you a jwt auth token verifying your lemmy account.

**Comment by hbroer** [comment]
lol. awesome. it's like talking to a wall.

**Comment by Nutomic** [comment]
> 1. User authenticates against Mastodon API and get a Usertoken via WebApp
>   2.  WebApp requests JWT from custom Microservice with that Usertoken
> 3.    Microservice requests userdata via Mastodon API with usertoken and respond with signed JWT containing role and sub (full username like @user@example.com)
> 4.    WebApp requests Lemmy API with JWT to post in whatever
>  5.   Lemmy verifies the JWT with pub key and if fine then just creates a post linked to @user@example.com instead of a local user, if more userdata is needed no problem, everything can passed via the JWT. No need for Lemmy to request anything from Mastodon. But for sure it could query Mastodon with the username and domainname it knows (@user@example.com) via ActivityPub to get the user details. There is no JWT needed. This works already, else Lemmy could not federate.
>   6.  Done.

Okay your misunderstanding is not about JWT, but about Activitypub. What you explain might be possible if Mastodon implemented client-to-server Activitypub. Then Lemmy could connect to Mastodon as Activitypub client to send its actions, and Mastodon would publish them. Unfortunately neither Mastodon nor Lemmy implements Activitypub client-to-server (and no other project that i know of). So the only way to perform any actions with a Mastodon account is with the Mastodon API, which Lemmy obviously doesnt support.
