### ISSUE TITLE
PostgreSQL duplicate key error during registration `idx_community_lower_actor_id`

### ISSUE THREAD

**Issue by neutron37** [LemmyNet/lemmy#2594]
### Issue Summary

When trying to register a new user error "Unknown" pops up and error is logged by lemmy-instance_lemmy_1

### Steps to Reproduce

1. Visit https://lemmy.darcy.social/signup
2. Fill form + Captcha and submit
3. "Unknown" error pops up

### Technical details

* What OS are you trying to install lemmy on? 
  * Safari / MacOS Ventura 13.0.1
* Any browser console errors?
  * [Error] Refused to load https://lemmy.darcy.social/static/assets/manifest.webmanifest because it appears in neither the manifest-src directive nor the default-src directive of the Content Security Policy.
* Relevant `sudo docker-compose logs > lemmy_log.out`.

```
postgres_1  | 2022-11-29 16:38:46.982 UTC [29] ERROR:  duplicate key value violates unique constraint "idx_community_lower_actor_id"
postgres_1  | 2022-11-29 16:38:46.982 UTC [29] DETAIL:  Key (lower(actor_id::text))=(https://lemmy.darcy.social/c/main) already exists.
postgres_1  | 2022-11-29 16:38:46.982 UTC [29] STATEMENT:  INSERT INTO "community" ("name", "title", "description", "removed", "published", "updated", "deleted", "nsfw", "actor_id", "local", "private_key", "public_key", "last_refreshed_at", "icon", "banner", "followers_url", "inbox_url", "shared_inbox_url", "hidden", "posting_restricted_to_mods") VALUES ($1, $2, $3, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $4, DEFAULT, $5, $6, DEFAULT, DEFAULT, DEFAULT, $7, $8, $9, DEFAULT, DEFAULT) RETURNING "community"."id", "community"."name", "community"."title", "community"."description", "community"."removed", "community"."published", "community"."updated", "community"."deleted", "community"."nsfw", "community"."actor_id", "community"."local", "community"."private_key", "community"."public_key", "community"."last_refreshed_at", "community"."icon", "community"."banner", "community"."followers_url", "community"."inbox_url", "community"."shared_inbox_url", "community"."hidden", "community"."posting_restricted_to_mods"
lemmy_1     | 2022-11-29T16:38:46.983478Z ERROR Websocket Request{trace_id=00000000000000000000000000000000}: lemmy_websocket::handlers: Error during message handling duplicate key value violates unique constraint "idx_community_lower_actor_id"
lemmy_1     |    0: lemmy_api_crud::user::create::perform
lemmy_1     |              at crates/api_crud/src/user/create.rs:48
lemmy_1     |    1: lemmy_websocket::handlers::Websocket Request
lemmy_1     |            with trace_id=00000000000000000000000000000000
lemmy_1     |              at crates/websocket/src/handlers.rs:68
```

**Comment by Nutomic** [comment]
Okay the code in user registration function checks if a default community with hardcoded id 2 exists, and if not tries to create it. In your case the default community was apparently created with a different id, so it tries to create a new community with the same name, which fails. 

The problem will be fixed in 0.17.0 once we release that because there is no default community anymore. For now you can try to use sql and change the id of community with name `main` to 2 (in `community` table).

**Comment by neutron37** [comment]
Changing `main` community's is to `2` fixed it. Thanks!

**Comment by dessalines** [comment]
The installation process must have hit a bump too, because that community should be auto-generated and always have that id.
