### ISSUE TITLE
`honeypot_fail` when registering with 1Password

### ISSUE THREAD

**Issue by neutron37** [LemmyNet/lemmy#2595]
### Issue Summary

Registration fails when 1Password plugin is enabled in Firefox 

### Steps to Reproduce

1. Install 1Password plugin
2. Visit https://lemmy.darcy.social/signup
3. Fill form and submit
4. <img width="806" alt="Screenshot 2022-11-29 at 6 09 58 PM" src="https://user-images.githubusercontent.com/25222299/204596112-66d5b348-58f3-4275-a838-46c6604b8835.png">

### Technical details

* MacOS Ventura 13.0.1 / Firefox 107.0
* No browser console errors
* `sudo docker-compose logs > lemmy_log.out`.
```
lemmy_1     | 2022-11-29T17:04:28.622871Z ERROR Websocket Request{trace_id=00000000000000000000000000000000}: lemmy_websocket::handlers: Error during message handling honeypot_fail: honeypot_fail
lemmy_1     |    0: lemmy_api_crud::user::create::perform
lemmy_1     |              at crates/api_crud/src/user/create.rs:48
lemmy_1     |    1: lemmy_websocket::handlers::Websocket Request
lemmy_1     |            with trace_id=00000000000000000000000000000000
lemmy_1     |              at crates/websocket/src/handlers.rs:68
```

**Comment by Nutomic** [comment]
There is a hidden field `honeypot`, which we use to detect and reject signup attempts by bots. The input field is invisible to users, but bots tend to blindly fill all form fields they can find.

At first glance this seems like an issue with 1password, because there is no reason why it should put any data in a hidden form field. Can you tell what text it writes there?

**Comment by neutron37** [comment]
Ah ha! With 1Password plugin enabled in Firefox the value of honeypot is an empty string `""`, but when the plugin is disabled the value is `undefined`.

**Comment by Nutomic** [comment]
I see the check is too strict.

**Comment by Alaknar** [comment]
This is still an issue, tested right now with BitWarden, getting the same result.
