### ISSUE TITLE
Invalid term definition in JSON-LD returned when requesting application/activity+json data from lemmy

### ISSUE THREAD

**Issue by xenomachina** [LemmyNet/lemmy#2600]
### Issue Summary

It looks like some of the ActivityPub data returned by lemmy may be invalid JSON-LD.

### Steps to Reproduce

1. Fetch activity data from a lemmy instance. I tried `https://jeremmy.ml/` and `https://lemmy.ca/`, and got identical results with both.

   To fetch, I just did:
   ``` shell
   curl --header 'Accept:application/activity+json' https://lemmy.ca/
   ```

2. Use the JSON-LD expansion algorithm on the result. I tried this with both [PyLD](https://github.com/digitalbazaar/pyld) and [Titanium JSON-LD](https://github.com/filip26/titanium-json-ld), and both complained about an invalid term definition.

### Technical details

PyLd said:

> pyld.jsonld.JsonLdError: ('Invalid JSON-LD syntax; a term definition must not contain type',)  
> Type: `jsonld.SyntaxError`  
> Code: invalid term definition  
> Details: `{'context': {'stickied': 'as:stickied', 'pt': 'https://join-lemmy.org#', 'sc': 'http://schema.org#', 'matrixUserId': {'type': 'sc:Text', 'id': 'as:alsoKnownAs'}, 'sensitive': 'as:sensitive', 'comments_enabled': {'type': 'sc:Boolean', 'id': 'pt:commentsEnabled'}, 'moderators': 'as:moderators'}}`

Titanium JSON-LD said:

> An invalid term definition has been detected [code=INVALID_TERM_DEFINITION].  
> JsonLdError[code=An invalid term definition has been detected [code=INVALID_TERM_DEFINITION]., message=An invalid term definition has been detected [code=INVALID_TERM_DEFINITION].]

PyLD's error is more helpful: **"a term definition must not contain type"**. I only tried with Titanium JSON-LD to confirm that I wasn't running into a bug in PyLD.

**Comment by Nutomic** [comment]
Lemmy doesnt support json-ld, its only sent because Activitypub requires that. In fact i dont even know how json-ld works exactly. If there is something wrong with the context, it would be very helpful if you could make a pull request to fix it in the file below:

https://github.com/LemmyNet/lemmy/blob/main/crates/apub/assets/lemmy/context.json

**Comment by dessalines** [comment]
I'm guessing the word `type` is protected, but it seems to be standard in activitypub. Do you get this error with JSON-LD from other services?

**Comment by xenomachina** [comment]
I've tried this on several Mastodon and Calckey endpoints, and their output can JSON-LD expand without any error.

Comparing the output of...

``` sh
alias curlld="curl --header 'Accept: application/ld+json'"
curlld https://lemmy.ca/ | jq . | head
```

``` json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "stickied": "as:stickied",
      "pt": "https://join-lemmy.org#",
      "sc": "http://schema.org#",
      "matrixUserId": {
        "type": "sc:Text",
        "id": "as:alsoKnownAs"
```

with...

``` sh
curlld https://mastodon.social/users/Gargron/ | jq . | head
```

``` json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "toot": "http://joinmastodon.org/ns#",
      "featured": {
        "@id": "toot:featured",
        "@type": "@id"
```


it looks like `"type"` (and maybe also `"id"`) should have the `@` prefix.

I tried making that change to a local copy of the JSON-LD returned by lemmy.ca, and it runs through a JSON-LD expansion without any errors.

I've uploaded the files here, for comparison:
- [JSON returned by lemmy.ca (pretty-printed)](https://github.com/LemmyNet/lemmy/files/10143381/lemmy-ca.json.txt)
- [same as previous, but modified to have `@` prefix on `type` and `id`](https://github.com/LemmyNet/lemmy/files/10143379/lemmy-ca-modified.json.txt)
- [JSON-LD expansion of previous](https://github.com/LemmyNet/lemmy/files/10143380/lemmy-ca-modified-expanded.json.txt)

**Comment by xenomachina** [comment]
Looking at the file @Nutomic linked to, it looks like this issue has already been fixed in https://github.com/LemmyNet/lemmy/pull/2299! I guess https://jeremmy.ml/ and https://lemmy.ca/ are using older versions. :crying_cat_face: 

Testing against https://ds9.lemmy.ml/ (mentioned in that PR), the returned JSON expands with no issue.

Sorry to waste your time!
