### ISSUE TITLE
When viewed from mastodon or similar, communities would only boost top level posts, not every comment

### ISSUE THREAD

**Issue by ChristopherKing42** [LemmyNet/lemmy#2606]
### Is your proposal related to a problem?

When viewing a Lemmy community through mastodon, it boosts every post and comment, can be a bit overwhelming! It also feels a bit redundant since the comments are already in the same conversations as the top level post they are in.

### Describe the solution you'd like

Only the top level posts would be boosted.

### Describe alternatives you've considered

Alternatively, Lemmy could present what looks like a bot account that boosts top level posts, leaving the current implementation in place as well. Even if my suggestion is implemented, I think creating a handle that looks like a bot that boosts every comment could be useful for less active communities.

### Additional context

More generally, Lemmy could have multiple of these virtual bot accounts that boost things. For example, you could Lemmy present an account that boosts everything from the front page of the instance, or an account for each community that boosts only the top level posts of each post. These would be in addition to the current accounts.

This follows the general philosophy that bots can post and boost whatever, without needing to control what they boost or be cleanly separated from each other.

**Comment by Nutomic** [comment]
Lemmy needs to send these `Announce/Create/Note` activities so that other Lemmy (and Mastodon) instances know about the comments in the first place. If you dont like the way Mastodon handles them, you need to open an issue in their repo.
