### ISSUE TITLE
When accessed over activity pub, Lemmy says the URL of the post is the link being shared, not a link to the post itself 

### ISSUE THREAD

**Issue by ChristopherKing42** [LemmyNet/lemmy#2607]
### Issue Summary

When accessed over activity pub, Lemmy says the URL of the post is the link being shared, not a link to the post itself.

Tbf I'm not sure whether this is a bug or a feature request; I'm not super familiar with the semantics of activity pub. I'm guessing it's a bug though. (It's at least unexpected behavior though.)

### Steps to Reproduce

1. Go to https://mathstodon.xyz/@yogthos@lemmy.ml/107157084539721344 (for example) in a web browser.
2. Click the three dots and then "Open original page"
3. This opens the image instead of the original Lemmy post.

### Technical details

N/A

**Comment by Nutomic** [comment]
This is again a problem with Mastodon, report it in their repo.
