### ISSUE TITLE
Is it possible to use a different domain for the hosted instance and the webfinger domain?

### ISSUE THREAD

**Issue by Cardinal8501** [LemmyNet/lemmy#2608]
In [Mastodon](https://github.com/felx/mastodon-documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md) and [Pleroma](https://docs-develop.pleroma.social/backend/configuration/how_to_serve_another_domain_for_webfinger/) you can have your webfinger identifier be, e.g., Cardinal8501@example.com while your activity pub instance is hosted at mastodon.example.com.

With Lemmy the only place I can find to set a hostname is the hostname parameter. I also notice that the /.well-known/host-meta path which Mastodon, Pleroma, PeerTube etc. supply for this 404s.

Is this not supported?

**Comment by Nutomic** [comment]
Its not supported in Lemmy, but I dont really see why it has to be. The way I understand it, it would be enough to write a small server software for your main domain, which only handles webfinger requests. So just handle the route `https://lemmy.ml/.well-known/webfinger?resource=acct:nutomic@lemmy.ml`, check with the Lemmy api if a user/community with that name exists, and then serve a response which points to your actual Lemmy installation.

**Comment by Cardinal8501** [comment]
I've been investigating this a bit more and I think there's another (probably more significant) issue. I haven't tested this yet, but from looking at the code it doesn't look like Lemmy tries to resolve webfinger requests like this either? This means that if, e.g., I had a Mastodon instance at https://activitypub.example.com and my username on it was admin@example.com Lemmy would try to look up the user at https://example.com/.well-known/webfinger?resource=acct:admin@example.com and fail. What Mastodon would do is check https://example.com/.well-known/host-meta, find the webfinger URL there, and then query https://activitypub.example.com/.well-known/webfinger?resource=acct:admin@example.com.

>Its not supported in Lemmy, but I dont really see why it has to be. The way I understand it, it would be enough to write a small server software for your main domain, which only handles webfinger requests. So just handle the route https://lemmy.ml/.well-known/webfinger?resource=acct:nutomic@lemmy.ml, check with the Lemmy api if a user/community with that name exists, and then serve a response which points to your actual Lemmy installation.

I could do something like that and probably will if there's no plan to support this. I think it might be a significant hurdle for many users though. Lots of people might be comfortable activating a docker compose environment from the provided samples but not so comfortable writing a mini web app or complex proxy configuration (though possibly this could also be fixed via a documentation update).

Would you accept a PR for a feature that allows overriding the URL used in webfinger requests, and possibly also supplies a /.well-known/host-meta route and adjusts webfinger lookups to check it as well?

**Comment by Nutomic** [comment]
Can you link a Mastodon or Pleroma server which uses this kind of setup with different domains? Would be much easier to figure out how it works then.

**Comment by Nutomic** [comment]
Ah so if Lemmy respects `/.well-known/host-meta` then you only need to drop a static file with that content at your main domain. The relevant code is [in this file](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/fetcher/webfinger.rs), you would have to remove the hardcoded `/.well-known/webfinger` url, and instead hardcode `/.well-known/host-meta` to get the actual webfinger domain. This change looks really simple and straightforward.

Then theres a separate task of adding this `WEB_DOMAIN` config option (it really needs a better name). The urls for federation are generated by [these functions](https://github.com/LemmyNet/lemmy/blob/main/crates/api_common/src/utils.rs#L759). This will require careful testing, I guess many parts of the code assume that the domain is always identical.

**Comment by DomiStyle** [comment]
Is there a method to do this now?

I already run my mail, Matrix and Mastodon from the same server and the all have their own subdomain but link to the main domain.

So for the main domain `example.org` there is `mail.example.org`, `mastodon.example.org` and `matrix.example.org`.
That way the identifier is identical on all services, it's always `user@example.org`.

Matrix and Mastodon can deal with this by forwarding `/.well-known/webfinger` to Mastodon and `/.well-known/matrix/server` to Matrix.

I would now like to add `lemmy.example.org` which follows the same system but couldn't find anything about that in the documentation?
With both using `/.well-known/webfinger` it seems impossible to do this right now?

**Comment by Nutomic** [comment]
Closing in favor of https://github.com/LemmyNet/lemmy/issues/3400
