### ISSUE TITLE
INSTALL INSTRUCTIONS DO NOT WORK! 

### ISSUE THREAD

**Issue by codeswitched** [LemmyNet/lemmy#2609]
The installation instructions for Docker and Installing From Scratch are riddled with errors. They do NOT work! 

I tried both versions of your nginx config and neither works. In one version you have the UI port as 1235 and another version it's 1234.

1. [](https://github.com/LemmyNet/lemmy-ansible/blob/main/templates/nginx.conf)

Port 1235

>    # The default ports:
>       # lemmy_ui_port: 1235
>       # lemmy_port: 8536

2. [](https://github.com/LemmyNet/lemmy/blob/main/docker/prod/nginx.conf)

Port 1234

> upstream lemmy-ui {
> # this needs to map to the lemmy-ui docker service hostname
>  server "lemmy-ui:1234";

3. In the docker compose file you have the port as 1236

[](https://github.com/LemmyNet/lemmy/blob/main/docker/prod/docker-compose.yml)

> - LEMMY_EXTERNAL_HOST=localhost:1236

4. Incomplete Nginx instructions

**Your instructions for docker specifically state:**

> To make Lemmy available outside the server, you need to setup a reverse proxy, like Nginx. A sample nginx config, could be setup with:
> 
> wget https://raw.githubusercontent.com/LemmyNet/lemmy-ansible/main/templates/nginx.conf
> # Replace the {{ vars }}
> # The default lemmy_port is 8536
> # The default lemmy_ui_port is 1235
> sudo mv nginx.conf /etc/nginx/sites-enabled/lemmy.conf

**But since your docker-compose.yml has:**

>  volumes:
>       - ./nginx.conf:/etc/nginx/nginx.conf:ro
>       # setup your certbot and letsencrypt config 
>       - ./certbot:/var/www/certbot
>       - ./letsencrypt:/etc/letsencrypt/live

It won't start without nginx.conf being in the /lemmy directory! No where does it say in your instructions to have nginx.conf inside of the /lemmy directory. No wonder this project has gone absolutely nowhere.

**Comment by codeswitched** [comment]
No one should have to play detective and fix things to get your shit to work!

**Comment by Nutomic** [comment]
> No one should have to play detective and fix things to get your shit to work!

Lemmy is provided for free, you dont have any right to make demands like this. If you cant get it working then just dont use it.
