### ISSUE TITLE
How to have only Lemmy, no nginx, no postgres etc

### ISSUE THREAD

**Issue by idc77** [LemmyNet/lemmy#2613]
I have a server that hosts many domains.
I don't want to use ansible.
You're offering a docker-compose.yml that has nginx
I manage my own nginx and letencrypt certs.
I have my own system postgres server.

How can I have an "always up2date" Lemmy without all the rest?

p.s. the hjson file has a wrong link, it should be `https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/prod/lemmy.hjson`

**Comment by Nutomic** [comment]
You can follow the instructions to install from scratch, and use your existing nginx/postgres installations:

https://join-lemmy.org/docs/en/administration/from_scratch.html

**Comment by lf2rockman** [comment]
I use scratch to install, it show me this error.
```
root@lemmy:~/.cargo/registry/src/github.com-1ecc6299db9ec823# cargo install lemmy_server --target-dir /etc/lemmy --locked
    Updating crates.io index
  Installing lemmy_server v0.16.3
warning: package `cpufeatures v0.2.2` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
   Compiling lemmy_utils v0.16.3
error: failed to run custom build command for `lemmy_utils v0.16.3`

Caused by:
  process didn't exit successfully: `/etc/lemmy/release/build/lemmy_utils-647d0bf140caf90b/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=translations/email/en.json
  cargo:rerun-if-changed=translations/email/ko.json
  cargo:rerun-if-changed=translations/email/pt.json
  cargo:rerun-if-changed=translations/email/fi.json

  --- stderr
  Error: Fmt(Os { code: 2, kind: NotFound, message: "No such file or directory" })
error: failed to compile `lemmy_server v0.16.3`, intermediate artifacts can be found at `/etc/lemmy`
```

**Comment by Nutomic** [comment]
See https://github.com/LemmyNet/lemmy/issues/2614#issuecomment-1353234822

**Comment by dessalines** [comment]
Just a note that we do not support manual installs, way too many systems and intricacies for us to debug. Asking either on lemmy or at https://matrix.to/#/!BZVTUuEiNmRcbFeLeI:matrix.org would probably get more replies than here.

**Comment by idc77** [comment]
That's a joke, right? Do you want your software to be used or not?

**Comment by dessalines** [comment]
It is not a joke, and please adhere to the code of conduct and be respectful, or we will boot you.

We don't do support for manual installs, because there are **thousands of systems with different configurations** to debug. If we did that, we would pretty much never code for lemmy, but only do installation support for it, which already takes up too much of our time.

**Comment by Nutomic** [comment]
That said you can install Lemmy however you want, and ask for help from other users in [!lemmy_support](https://lemmy.ml/c/lemmy_support) or on Matrix.
