### ISSUE TITLE
Remove post rate limit for trusted users.

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy#2620]
The post rate limit is the most annoying thing about Lemmy and it's something that could be applied only to users with a low trust level if trust levels where implemented as mentioned in the [community moderation](https://github.com/LemmyNet/lemmy/issues/2619) issue.

**Comment by dessalines** [comment]
I don't want lemmy to become a reputation-based system with "power users", see my comments in the other issue. You can ask that an admin increase the post rate limit, but it should affect all users uniformly.

**Comment by Nutomic** [comment]
> I don't want lemmy to become a reputation-based system with "power users", see my comments in the other issue. You can ask that an admin increase the post rate limit, but it should affect all users uniformly.

Why not? We have a real problem with spam, and giving more capabilities to trusted users is a proven way to avoid or at least reduce spam.

**Comment by dessalines** [comment]
See my comments in the issue linked above, the "stackoverflow / forum power user effect", is something I want to avoid here. Also registration applications have pretty much eliminated our problem with spam, so I'd be good with relaxing all of these rate limits.
