### ISSUE TITLE
Votes are not federated from some instances?

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy#2622]
### Issue Summary
I noticed that posts from some connected instances (like feddit.de or lemmy.pt) do not show up the "all" feed of my slrpnk.net instance. Initially I thought it was some general issue with federation, but looking at remote communities on feddit.de it appears as if the votes do not get federated and thus all of them have "0" as their vote. I am assuming this "down-vote" like behaviour makes them disappear from the "all" feed.

Interestingly other instances like lemmy.ml and beehaw.org do seem to work normally.

This is happening with BE 0.16.7.

**Comment by Nutomic** [comment]
Does federation with these instances work normally otherwise? For example, can you successfully follow a community there, or make a post/comment and it shows up on the other instance?

**Comment by poVoq** [comment]
Yes, I think so. Initially I didn't even notice that something is wrong as everything seemed to work normally.

**Comment by poVoq** [comment]
Could this be related to disabled down-votes?

The sorting in general is very odd... some posts seem to stick to the top of the feed for days.

**Comment by poVoq** [comment]
Not sure what you did, but it seems much better now. Closing for now.

**Comment by Nutomic** [comment]
I restarted your instance. Its still a problem that this was necessary, but not sure what might cause it. Lemmy itself shouldnt store any state, so maybe this is a problem with the database.
