### ISSUE TITLE
Lemmy's API exception: password incorrect

### ISSUE THREAD

**Issue by TalOrenshtein** [LemmyNet/lemmy#2626]
Hey,
I saw that Lemmy's API tells the use when the password is wrong. Which means that if a malicious person wants to hack an account, and Lemmy says that the password is wrong, the malicious person knows he got an email/username that is registered to that instance. Which makes hacking one's account easier that it should be. I hope that you'll consider switching the prompt to "email or password is wrong" or something.

![image2](https://user-images.githubusercontent.com/13657005/208890803-fd00fbf3-d65f-48cd-97cf-57c3000c0445.jpg)

**Comment by Nutomic** [comment]
Relevant code is here, should be easy to fix: https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/local_user/login.rs#L40

**Comment by Nutomic** [comment]
Same as https://github.com/LemmyNet/lemmy/issues/1754
