### ISSUE TITLE
Feature to embed pict-rs in Lemmy binary

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2627]
It would be possible to add a feature flag to embed pict-rs directly in the Lemmy binary. This would be useful for development/testing as you dont need to clone and run a separate project. It could also make installation slightly easier, particularly for manual installation without Docker (one thing less to compile).

Making this possible would require two changes:
- pict-rs needs to move its init function from main.rs to lib.rs, so that other crates can access it (see https://github.com/LemmyNet/lemmy/pull/2618)
- Lemmy needs to add a feature flag `embed-pictrs` which runs the init function from pictrs, and also runs the Lemmy init function (see https://github.com/LemmyNet/lemmyBB/pull/73)

cc @asonix

**Comment by asonix** [comment]
https://docs.rs/pict-rs/0.4.0-beta.8/pict_rs/

**Comment by Nutomic** [comment]
Great, thank you!

**Comment by xximj** [comment]
One option to improve the scalability of the system might be to moving Pictrs tables from sqlite to Lemmy database, which uses postgresql. Lemmy can be scaled horizontally, which could be more effective compared to sqlite.

**Comment by dessalines** [comment]
pictrs doesn't use a SQL db, it uses sled.

**Comment by asonix** [comment]
regardless, 0.4 does lay the groundwork for alternative repositories. it's exposed in the `[repo]` configuration section, but the only provider currently is sled
