### ISSUE TITLE
Codebase also mirrored on Gitlab?

### ISSUE THREAD

**Issue by andreajparker** [LemmyNet/lemmy#2632]
New Lemmy user here. I saw that the Github codebase is mirrored / backed up on Gitea and Codeberg. Those sites don't have much name recognition, I don't think. Would it be possible to get the codebase replicated on Gitlab?

**Comment by dessalines** [comment]
I just attempted this, but gitlab grays out the option for pull mirroring, and doesn't allow simple pull mirroring without using an ssh connection. The three current locations will have to suffice.
