### ISSUE TITLE
Images no longer being displayed

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2637]
What's the question you have about lemmy?

I run my Lemmy on a linode and it stopped running because it ran out of disk space. So I upgraded the lincode so it had twice the disk space and it seems to be running fine now except it will not display images.

I tried going to settings to upload the logo again, but that did not work.

So I have 2 questions:
1. What should I do to get the images displaying again, and
2. Exactly where do I go to see what is suddenly taking up a chunk of space?

Thanks in advance for your help.

Kap

**Comment by dessalines** [comment]
We'd need the docker compose logs to see what's going on. Make sure you try a docker compose restart too. Hopefully the upgrade didn't clear out your pictures.

**Comment by Kap2022** [comment]
They do not display for new posts either.

Can you give me the exact commands to:
- do a docker compose restart and where I do it from
- generate the docker compose logs and how to limit the size if it is likely to be to big to upload to github and where to run the commands from.

I cannot tell you how much I appreciate all you do for us.

**Comment by Nutomic** [comment]
This is an issue tracker, not a support forum. You should ask such questions in [!lemmy_support](https://lemmy.ml/c/lemmy_support)

**Comment by Kap2022** [comment]
[Lemmy Image Error Log.txt](https://github.com/LemmyNet/lemmy/files/10367079/Lemmy.Image.Error.Log.txt)

This is the Docker-Compose log

**Comment by Kap2022** [comment]
[docker-compose up comand screen output.txt](https://github.com/LemmyNet/lemmy/files/10367505/docker-compose.up.comand.screen.output.txt)

This is the screen output from the up command
