### ISSUE TITLE
Older pinned posts do not get federated

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy#2640]
### Is your proposal related to a problem?

Only new posts seem to get federated, but older pinned posts that include important information do not. 
See:
https://lemmy.ml/c/scifi

Vs:

https://slrpnk.net/c/scifi@lemmy.ml

The pinned [What are you reading/watching?](https://lemmy.ml/post/53844) post at the top.

### Describe the solution you'd like

As pinned posts often describe important info about the community, it would be probably good if they could get a special treatment in federation and get properly federated regardless of age.

**Comment by dessalines** [comment]
This would require a change in the sorting when fetching historical posts on first connection.
