### ISSUE TITLE
Logging broken when using opentelemetry setting

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2642]
I'm developing locally, and when I have the open-telemetry setting in the `lemmy.hjson` (as is the default for our docker dev setup), for some reason, only the server startup lines get written to the console log, and everything else gets ignored. 

Removing the `opentelemetry_url` line from the config fixes the issue, and everything correctly gets written to the console.

https://github.com/LemmyNet/lemmy/blob/main/src/lib.rs#L184

asonix, I'm not familiar with otel, or how it works, maybe this is intended, I just don't know how to use it.

cc @asonix

**Comment by asonix** [comment]
I think there was a change in lemmy at some point that conflated opentelemetry with tokio-console. They're two separate concepts but both rely on tracing. if you enable the `console` feature with the current logic it should also fix logging, but really openelemetry shouldn't be gated behind the `console` feature

**Comment by dessalines** [comment]
This is fixed now.
