### ISSUE TITLE
Encoding aliases not supported when fetching webpages.

### ISSUE THREAD

**Issue by hanubeki** [LemmyNet/lemmy#2648]
### Issue Summary

Follow up for #1858 and #2015

Lemmy detects and decodes encoding when fetching articles, but not completely support encoding aliases such as `Shift_JIS`.
Example: https://www.itmedia.co.jp/news/spv/2212/16/news161.html

rust-encoding supports `Shift_JIS` as an alias of `Windows-31J`.
https://github.com/lifthrasiir/rust-encoding/blob/4e79c35ab6a351881a86dbff565c4db0085cc113/src/codec/japanese.rs#L454

Current implementation only checks for `name` but not `whatwg_name` which has `shift_jis`.
https://github.com/LemmyNet/lemmy/blob/ceff2ec686094364cd452f10314d7239c8a9763c/crates/api_common/src/request.rs#L60

So Lemmy doesn't currently decode Japanese pages which uses `Shift_JIS`.

### Steps to Reproduce

1. Create a post with a page encoded with `Shift_JIS`
2. Page title and content are not decoded correctly.

### Technical details

* I don't host any Lemmy instance, I report it as a Lemmy instance user.

**Comment by dessalines** [comment]
Feel free to make a PR, seems like an easy fix.

**Comment by hanubeki** [comment]
I never wrote any Rust code. That's why I opened an issue instead of a PR.

**Comment by dessalines** [comment]
Stale issue, can re-open if someone wants to take it on.

**Comment by Nutomic** [comment]
I dont think it makes sense to mark an issue like this as "stale" when it can still be reproduced and still needs to be fixed.

**Comment by Nutomic** [comment]
This appears to be fixed, the preview shows Japanese characters.

![Screenshot_20240920_121826](https://github.com/user-attachments/assets/0ff261f0-6d6e-485e-bc07-58922ae9a3c8)
