### ISSUE TITLE
Intermittent empty WebSocket responses

### ISSUE THREAD

**Issue by Elara6331** [LemmyNet/lemmy#2649]
### Issue Summary

Occasionally (not sure how often exactly), I get an empty (0B) WebSocket response when I make a request. This is what it looks like:

![image](https://user-images.githubusercontent.com/41810442/211416763-9769c4ac-d7e9-4a7b-983f-a0d734e97721.png)

I was testing changes I made to my bot, so this is likely a rate limit. If so, it should provide an error message rather than just sending an empty response.

### Steps to Reproduce

1. Attempt to create comment via WebSocket
2. Receive empty response

### Technical details

When this happens, the following error occurs in the console:
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

I also get an `unexpected EOF` from my bot for the same reasons.

**Comment by dessalines** [comment]
Error responses *should* be fixed in main, but its not deployed yet. We should leave this open until we have the newer versions running somewhere to test it.

**Comment by Nutomic** [comment]
Fix for this should be out.
