### ISSUE TITLE
Community federation

### ISSUE THREAD

**Issue by Oblomov** [LemmyNet/lemmy#2650]
I [recently asked on Mastodon](https://sociale.network/@oblomov/109650370661176499) if Lemmy allowed community-level federation, and I was told that this is not the case, and was suggested to open an issue here.
I am not sure however if this is kind of feature request involves primarily the front-end or the back-end, so please feel free to redirect me as appropriate.

### Describe the solution you'd like

The idea is the following: if both server A and server B have a community by the same name (/c/linux), and the two servers federate, it would be nice to have the possibility to browse a “merged” channel with content from both A and B (of course this would extend to multiple servers). Of course it should still be possible to choose between a local and a federated view.

(One of the interesting side-effects of this change is that it would make it possible to have a USENET-like system built on top of Lemmy.)

**Comment by Nutomic** [comment]
Communities do federate, thats the main feature of Lemmy. The way it works is just like users on Mastodon, so what you propose isnt how Activitypub works.

**Comment by jpbaril** [comment]
@Nutomic I don't think @Oblomov is saying to have a "merged" view of communities list. We already have that as you said.
I think Nutomic is saying to have a merged view of the threads of two or more identicially-named communities.
Eg. Being able to browse all threads of https://lemmy.ml/c/canada and https://lemmy.ca/c/canada in a single view as if they were part of a merged "meta/virtual" community.

**Comment by Oblomov** [comment]
It may not be how lemmy implements federation, but it's not an intrinsic property of federation. USENET was federated and offered a “merged” view nonetheless.

**Comment by ArthurJ** [comment]
What about a "light-merge" where, when both instances agree, the posts are shown in a unified feed in a transparent way. That feature could be turned-off at any time and the posts made on other instances will not be shown on that instance anymore.

**Comment by Visne** [comment]
I think this is basically a duplicate of LemmyNet/lemmy-ui#1113
