### ISSUE TITLE
Seperate upload field for large blender files that lets users automatically seed .blend files for an from an instances seedbox

### ISSUE THREAD

**Issue by nixoye** [LemmyNet/lemmy#2655]
sharing large files is very expensive and annoying on servers so it would be really convenient if there was an option on setup to allow access to so some\all logged in users to be like "watched" by seperate seedboxe server(s) to instantly seed the magnet\.torrent file so the uploader doesnt have to have their computers on and show their ips to everyone

downloaders who dont want to share their ips already have the option to use vpns\seedboxes so this would make it convenient for uploaders to have a similar protection option

**Comment by dessalines** [comment]
You can use the link field to share any links you want, but anything past that is beyond lemmy's control. 

Get a vpn if you are worried about your ip leaking, whether you are torrenting, or just visiting a website.
