### ISSUE TITLE
Multi-dimensional voting/moderation system

### ISSUE THREAD

**Issue by naught101** [LemmyNet/lemmy#2666]
### Problem statement

I recently posted a [mastodon thread](https://mastodon.social/@naught101/109701742342424279) suggesting a decentralised URL review service, focused on disrupting misinformation. Then I realised that Lemmy already does 80% of what is needed for this. 

One of the main missing things is a multi-dimensional voting system (for both posts and comments, similar to Slashdot's user moderation system, that would allow a more nuanced understanding of  what "upvote" and "downvote" means to any given user, and to the community as a whole.

### Proposed solution

Add more vote types/dimensions per post. Probably a standardised set, but potentially allowing instances add custom dimensions.

Suggested dimensions:

- Accurate (down votes imply misinformation) - maybe also something like
- Fresh (down votes imply old information)
- Lucid (down votes imply poorly written)
- Funny (down votes imply boring/unfunny)
- Calm (down votes imply aggression or volatility)

This system would help in flagging:
- Misinformation (down votes on Accurate)
- Good write-ups of existing information (Accurate +, Fresh -, Lucid +)
- Good news sources (Accurate +, Fresh +, Lucid +)
- Sarcasm (Accurate -, Funny +)
- Trolling (Accurate -, Calm -, Funny ?)  

### Describe alternatives you've considered

There is an existing issue for emoji-reactions: #2541, which is think is tangentially related, but aimed at a different problem. 

### Additional context

It's possible that Lemmy isn't the right vehicle for this, in particular in that it has a focus on forstering discussion, where this review service would aim to have minimal discussion only pertaining to the qualities of the URL in question, and ideally a strong incentive to reference claims about accuracy (which this issue isn't trying to address). But I thought I'd throw it out there as a suggestion.

**Comment by dessalines** [comment]
Lemmy probably isn't the right vehicle for this, as it uses a simple number score denoting liking to rank and sort posts, not a pre-defined set of different types of reactions to content.

We have a "report reason" in our reporting system, which is always custom, rather than a pre-defined set of terms.

Emoji reactions would be fun to add, but they won't affect sorting in any way.

It would probably be better to create a different project based on your suggested dimensions.

**Comment by naught101** [comment]
Fair enough, thanks for the response!
