### ISSUE TITLE
Invalid message ID for e-mails gets flagged by SpamAssassin

### ISSUE THREAD

**Issue by Kradyz** [LemmyNet/lemmy#2667]
### Issue Summary

The message_id of sent e-mails does not comply with a standard as it is not enclosed within angle brackets, so it is more likely to get sent into the spam folder by SpamAssassin.

### Steps to Reproduce

1. Create a new account and provide an e-mail tester as the user e-mail (for example, I used https://www.mail-tester.com/)

2. Accept the user, and see the results of the test.

3. In the section about the SpamAssassin filter, you will see:  -1.167 | INVALID_MSGID | Message-Id is not valid, according to RFC 2822

Here is an example of this test from mander.xyz: https://www.mail-tester.com/test-vjvhpqexh

It is also possible to see that something is wrong if you send the e-mail to yourself and check the message ID. You will see something like: "`63c812c2.170a0220.73286.456fSMTPIN_ADDED_BROKEN@mx.google.com`"

Looking into it, the issue is that the [RFC 2822 standard (section 3.6.4)](https://www.rfc-editor.org/rfc/rfc2822#section-3.6.4) requires the message id to be enclosed by angle brackets.

I have tested whether this can be fixed by adding the angle brackets to message_id  in [email.rs](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/email.rs#L61). Here is the improved test result after building a new docker image with the modification: https://www.mail-tester.com/test-roy9zwmom

**Comment by dessalines** [comment]
In the future, add `#fixes ISSUE_NUMBER` so that this will close automatically.
