### ISSUE TITLE
Cannot be reached

### ISSUE THREAD

**Issue by JoeMarxYT** [LemmyNet/lemmy#2672]
![image](https://user-images.githubusercontent.com/123623814/214781356-bffcd5db-8e25-441c-ad3f-b943465394b0.png)

I can't connect to this site

**Comment by JackFromWisconsin** [comment]
As per a discussion on the matrix chat, this is likely because of Google blocking .ml domain names on their DNS. Try again now, is it working again?

**Comment by dessalines** [comment]
https://dnschecker.org/#A/lemmygrad.ml

**Comment by JoeMarxYT** [comment]
> As per a discussion on the matrix chat, this is likely because of Google blocking .ml domain names on their DNS. Try again now, is it working again?

Hello, @JackFromWisconsin  this issue is now resolved. Thanks for the update
