### ISSUE TITLE
Unable to view posts on all feeds on v.0.17.0

### ISSUE THREAD

**Issue by JackFromWisconsin** [LemmyNet/lemmy#2682]
Found a bug? Please fill out the sections below. 👍

For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

If you have problems installing Lemmy, you should post in [!lemmy_support](https://lemmy.ml/c/lemmy_support).

### Issue Summary

My instance (midwest.social) just upgraded to v0.17.0. While logged into my account, all posts on all feeds are blank. Home page shows nothing, user pages show nothing, communities show nothing. All I see are posts created after (presumably) either the migration, or when I logged in after the migration. 

This only is affecting my account @JackFromWisconsin@midwest.social . Everything works as expected when logged-out. The admin of the instance @seahorse@midwest.social says he isn't experiencing this issue. 

Do note that I can still view a post via direct link while logged in. It's just that it doesn't show up in any feeds.

### Steps to Reproduce

1. Log into my account
2. All feeds don't contain posts made before the migration to v.0.17.0

### Technical details

* don't have logs
* Affects me on all of my devices: Windows 10 Microsoft Edge, Android 12 Firefox and Jerboa

### Screenshot
Note I made the test post after the migration.
![image](https://user-images.githubusercontent.com/118757222/215918825-fe7dff69-51e5-4685-bee4-6ffabb75ae90.png)

**Comment by JackFromWisconsin** [comment]
update: I am also experiencing the issue of not seeing any comments on any posts (even my test post shown in the screenshot above). One exception: I could see my own comment on that post. 
![image](https://user-images.githubusercontent.com/118757222/215924127-fabdd232-9974-4270-9e3e-122556f1c502.png)
in the screenshot, seahorse commented 'test'. I could not see it. However, he could still see my comment.

**Comment by JackFromWisconsin** [comment]
Update: looks like the issue was caused by me setting my language to "english" in my user settings page, and not realizing that "undetermined" was unselected. this filtered out all posts with "undetermined" language. Reselecting "undetermined" restored all missing posts.

**Comment by JackFromWisconsin** [comment]
I suppose I can close this as resolved.

**Comment by dessalines** [comment]
We should probably document the behavior of `Undetermined` somewhere.
