### ISSUE TITLE
Images not displaying - regular maintenance routine to prevent/resolve issue

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy#2692]
### Is your proposal related to a problem?
Images stopped displaying on my instance. I know of other instances that had this problem as well some of which resolved the issue by rolling back to an earlier backup.

Once you know how to fix it, the fix is pretty simple - but it has taken me a month and many hours to do it. I think the other instances with the problem just restored to an earlier back up.

Here are links to some of the problem reports:
https://lemmy.ml/post/696178
https://lemmy.ml/post/704851
https://lemmy.eus/post/3863
https://github.com/LemmyNet/lemmy/issues/2653
https://github.com/LemmyNet/lemmy/issues/2637

The instructions to fix from asonix was 
""empty/corrupt snapshot file" is a solvable issue. Look into pict-rs's storage in the sled directories. there should be some files that have .snap at the end. if any of these are zero-sized, delete them. if none of them are zero-sized, delete the most recently created one. then restart pict-rs"

But I did not have files ending in .snap and I was not confident enough I was even looking in the right place.

So this is how I ended up fixing it. Going to this directory /srv/lemmy/exploding-heads.com/volumes/pictrs/sled/db-0.34#

and deleting snap.00000003259F145D.generating that had a file size of zero

### Describe the solution you'd like

I would like to propose a regular maintenance routine that:
1. checks to make sure the instance is not running out of disk space and if it is, notifies that admin the same way the admin is notified on the instance about spam reports.
2. Checks the sled directory for any files that show zero size and automatically delete them

I know this stuff might be easy for people who have lots of experience, but for novices like me running an instance - an automated maintenance and notification system would save a lot of grief and provide a better user experience to my users who have suffered a month without images

**Comment by dessalines** [comment]
This is a pictrs issue, not lemmy (which doesn't take up that much space). Lemmy is also sandboxed in such a way that it can't and shouldn't know your system details like that, nor can it edit files in pictrs.
