### ISSUE TITLE
Self is reported as blocked in the settings multiple times

### ISSUE THREAD

**Issue by nycterent** [LemmyNet/lemmy#2693]
### Issue Summary

when going to settings block tab: self is reported as blocked multiple times 

### Steps to Reproduce

1. login and go to settings (https://group.lt/settings)
2. checked blocks tab and there is self reported as blocked multiple times without a context (and cannot be unblocked)

### Technical details

* version 0.17.0 from docker image

![image](https://user-images.githubusercontent.com/81133/216149709-58487dac-ea76-4718-9be2-235254d6b1b6.png)

**Comment by dessalines** [comment]
This ended up being an issue with the back end `MyUserInfo.person_blocks`
