### ISSUE TITLE
Switch from drone to woodpecker

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2711]
Its an open-source fork of drone: https://github.com/woodpecker-ci/woodpecker

**Comment by ravermeister** [comment]
Is it compatible with the external drone runners?

**Comment by Nutomic** [comment]
I dont want to rely on a company which changes its software license without any notice to users. Better to use the open source fork to be safe from future shenanigans.

**Comment by dessalines** [comment]
We've switched to using a "community edition" drone image on docker hub, but yeah woodpecker should be our long term goal. At least after they address this blocking issue for us: https://github.com/woodpecker-ci/woodpecker/issues/1582

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/issues/1582#issuecomment-1431660085

if you have anything missing dont hesitate to open an issue :)

PS: if you need cron ... you should use a pinned version of `next` until v1.0.0 is released ...

**Comment by 6543** [comment]
@dessalines did it worked?

**Comment by dessalines** [comment]
Yep! Except for this issue, which prevents us from doing ARM builds.

https://github.com/woodpecker-ci/woodpecker/issues/1677

**Comment by 6543** [comment]
hmm that's a shame ... we do look into arm runner for ourselves at the moment too ... so let's see

**Comment by 6543** [comment]
-> #2803 @dessalines
