### ISSUE TITLE
Use serde(skip) attribute for sensitive fields

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2712]
We currently use separate structs like `CommunitySafe` in order to avoid that sensitive data like federation private keys are exposed in API responses. In fact this seems completely unnecessary, we can remove these "safe" structs and use [serde(skip)](https://serde.rs/field-attrs.html#skip) instead.

Similarly the trait `DeletableOrRemovable` can be replaced using [serde(skip_serializing_if)](https://serde.rs/field-attrs.html#skip_serializing_if) and a function which checks if the item was removed/deleted.

**Comment by dessalines** [comment]
Makes sense.
