### ISSUE TITLE
Related Community visualizer

### ISSUE THREAD

**Issue by testman42** [LemmyNet/lemmy#2713]
### Is your proposal related to a problem?
no

### Describe the solution you'd like

[Anvaka's SayIt](https://github.com/anvaka/sayit) is a great visualisation tool that shows which subreddits are related to each other in regards to their themes and topics.
Example for how it looks for /r/fediverse: https://anvaka.github.io/sayit/?query=fediverse

I believe that having something like this built into Lemmy itself would allow members of the community to much more easily discover and connect with others who share their interests.

This thing seems to have two main components:
First is the logic that builds the list of relevant communities and the second one is the visualisation of that result.

Implementation wouldn't need to be anything too complex. Just a link in the community's sidebar that then opens a new tab where the similarity network would get displayed.

I'm opening this feature request in the main issue tracker because I believe that the graph-constructing logic could be used outside of visualisation as well.
Specifically, it could be used to suggest relevant communities when cross-posting an existing post.

### Describe alternatives you've considered

I'm not aware of any alternatives.

**Comment by dessalines** [comment]
I def agree, this could be useful.

**Comment by levnikmyskin** [comment]
This looks like a cool thing to do. I think there are a couple of things that should be decided:

1. to use such a tool "on the fly" (to recommend similar communities etc.), parts of the computation should probably be done offline; this tool might also be developed separately (which would relax the constraint of using Rust, for instance).
2. Anvaka's tool seems to build a network connecting subreddits based on "_Redditors who commented to this subreddit, also commented to..._". I don't think this approach would work super well for Lemmy, considering that the platform is still pretty fresh and new. I'd rather go with an approach (at least for now) where communities are clustered together if, e.g., the title of the posts are similar.

If I find some time in the next weeks I'll try working on at least the backend clustering code (probably in Python).

**Comment by dessalines** [comment]
I'll re-open should someone want to work on this.
