### ISSUE TITLE
Some posts can't be found when searching remotely by URL

### ISSUE THREAD

**Issue by kvibber** [LemmyNet/lemmy#2715]
At first I thought this was a problem with GoToSocial trying to find Lemmy posts, but I was able to reduce it down to a simple curl testcase against lemmy.ml

```
curl --header "Accept: application/json"  -i https://lemmy.ml/post/746709
```
returns the full JSON of the post, and searching for the URL on a remote Mastodon or GoToSocial instance finds the post.

```
curl --header "Accept: application/json"  -i https://lemmy.ml/post/741839
```
returns a 404 error with the text "Record not found", and searching for the URL on a remote Mastodon or GoToSocial instance does not find the post.

Both posts load when accessed in a web browser, whether logged into lemmy.ml or not.

**Comment by Nutomic** [comment]
To fetch a post or any other object you need to use its Activitypub id. In Lemmy that is shown with the colored Fediverse icon. In case of your second link, the id is `https://slrpnk.net/post/239172`. Fetching that works just fine.

**Comment by kvibber** [comment]
I see what happened. Because I follow the !fediverse community, which uses the same icon as the remote link on the post, I must have just skipped over the icon when I was looking for a canonical link on those posts!
