### ISSUE TITLE
Limit storage usage per user

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy#2722]
### Problem
beehaw ran out of storage space because their users gobbled it all up and there is no insight into which users are doing this or meaningful controls to limit this type of abuse.

### Solution
add controls to limit the total space-usage of media uploads per month and over-all.

### Describe alternatives you've considered
preexisting rate-limits could be tightened down, and perhaps more documentation about them could exist.
unfortunately they dont discriminate between an emoji and a video, so some users will use waaaay more space than others under those limits. 

### Additional context
I think you guys are awesome, and this could also pave the way for other features :thinking:

**Comment by Nutomic** [comment]
Images are all handled by pictrs, Lemmy doesnt have any insight how much storage they use. There is also currently no tracking which images were uploaded by which user.

cc @asonix
