### ISSUE TITLE
Ban requirements

### ISSUE THREAD

**Issue by c-vall** [LemmyNet/lemmy#2745]
I got a site ban (I believe), but I'm unaware of the reason for the ban, and I'm even more perplexed since I only wrote one reply to one post and I can't figure out what was bannable about it. Is there a way to find out what caused this?

usrn: info

**Comment by dessalines** [comment]
This is an issue tracker for the lemmy software, not how any given instance moderates. Lemmy comes with a public modlog so you can check the reason there.
