### ISSUE TITLE
404: rate_limit_error

### ISSUE THREAD

**Issue by Orygaw** [LemmyNet/lemmy#2747]
Hello, today I installed Lemmy from Ansible and everything was fine until I set the wrong values in the admin panel regarding limits. From now on my website I keep getting the message: 404: rate_limit_error

Is it possible to restore the database to default values? Or how to change the limits without access to the admin panel?

**Comment by dessalines** [comment]
It'd probably be easiest to just delete the volumes folder, then run docker compose down then up. Otherwise the ansible comes with an uninstall script.

**Comment by Orygaw** [comment]
> It'd probably be easiest to just delete the volumes folder, then run docker compose down then up. Otherwise the ansible comes with an uninstall script.

Thanks. I deleted the directory from postgresql restarted docker and it started working.
