### ISSUE TITLE
MITish vs Corporate AGPLish Licenses

### ISSUE THREAD

**Issue by Sondro** [LemmyNet/lemmy#2751]
Why is Lemmy using corporate IP protection strategies like the restrictive AGPL license -- can we plz get something MITish? I like your tech stack, but don't care about Mastodon, Fediverse, etc. Is there a partial MITish or dual AGPL/MITish license possible?

John Carmack has lamented his greatest work was the Quake 3 Engine, but he's disappointed it hasn't spread wide & believes it's because of restrictions in the GPL license. He was forced to adopt this license because his co-owners @ Id Software were afraid of anyone making a profit without them being paid.

However, the Quake 3 source code still lives on inside non-public licensed tech like the core of the latest Call of Duty engine.  If a company wanted to privately license Lemmy, they would just come to the Lead Dev & pay them off (& everyone sells out with enough zeros, especially when sick or in debt). So AGPL is really an invisible license for rich people only & not for the public.

--------------------

Lemmy AGPL, WORST CASE: Corporation forks Lemmy, obfuscates the code some & never releases the source. They are able to make billions of $$$. Lemmy Devs will never see $1, & if they take them to court they will lose at the cost of many -$. Lead Dev dies, Lemmy becomes outdated abandonware.

Lemmy AGPL, BEST CASE: Some fans of Lemmy contribute source code, mostly small bug & cosmetic fixes. Company offers to buy a Lemmy license to own the technology. Lead Dev dies, Lemmy becomes outdated abandonware.

--------------------

Lemmy is MITish, WORST CASE: Reddit forks Lemmy, they hire Lemmy devs to continue working on Lemmy with high salaries & set up a Lemmy foundation. Lemmy devs have so much money & free time they allow the source code quality to lower some. Lemmy becomes hyper popular & has many clones (some closed, others open). Useful bits of Lemmy likely live on after Lead Dev dies.

Lemmy MIT, BEST CASE: Lots of clones of Lemmy, some closed, some open. Tons of Lemmy based code available. Lemmy devs become consultants & set up a Lemmy foundation with their own money. Useful bits of Lemmy likely live on after Lead Dev dies.

**Comment by dessalines** [comment]
We don't plan on switching to a weaker / more-corporate-friendly copyleft license. If someone wants to work on lemmy, they must keep their work in public, and contribute back to the commons.

**Comment by Nutomic** [comment]
You seem to misunderstand what problem AGPL solves, read this article: https://medium.com/swlh/understanding-the-agpl-the-most-misunderstood-license-86fd1fe91275

Also its not so easy for a corporation to buy a proprietary license for Lemmy. This would require agreement from everyone who contributed code to the project. Obviously this is very unlikely to happen.

**Comment by Sondro** [comment]
I've read that before, it is clearly out of touch with reality.

The Richest people & corporations regularly don't pay taxes, but you think an AGPL is going to stop them? Really?

All Licenses are for NON-RICH PEOPLE. Rich people & large corporations can do whatever they want. Even if they go to court, they can just buy the judge or an army of lawyers to drag it out. 

Just like how Microsoft/GitHub is using everyone's code (regardless of license) to train GitHub Co-Pilot & with the goal to replace all human programmers with AI. The US Government (working for US corporations like Goldman Sachs/Microsoft) can claim (like with Tornado Cash Devs), that you are a 'threat to democracy'. Then they can freeze all your assets & GitHub will immediately ban anyone who worked on the code.

Then they can send the FBI/US Military to come to nearly any country (other than like Russia or China) & arrest & torture you forever or just make you disappear. They can torture inside any US police station/prison (if they even care), or they can send you to Gitmo/Egypt/etc, or on a ship to be held/tortured forever. 

AGPL does nothing to prevent any of the above, it just makes it difficult for normal/non-rich people to share & use the code (because it allows rich people & large corporations to use AGPL against them). 

Again, Lemmy is currently being use to train AIs for Microsoft/OpenAI/Google/etc & doesn't care about AGPL.

Do you think Jullian Assange & the Tornado Cash Devs are thinking right now: "IF ONLY I USED AGPL"?

**Comment by Nutomic** [comment]
We are not going to change the license and your rants wont change that.
