### ISSUE TITLE
Approve / Deny all pending applications API action

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2752]
lemmy.ml had a recent wave of applications after being posted to a telegram room with 30k users. On one day lemmy got 3k applications, and another getting 800. 

Since this touches 2 database tables: the `local_user.accepted_application`, and `registration_application.admin_id` , its not super easy to do mass approvals / denies in the database alone.

I still see value in keeping applications, while still having an `approve all` button, for massive user influxes like this. 

- By not getting onboarded instantly, it still wards off trolls and spammers
- Many people still put work into the answers, which by itself keeps out a lot of spammers.

**Comment by Nutomic** [comment]
I dont think we should encourage this kind of mass approval.
