### ISSUE TITLE
allow for multiple community banners

### ISSUE THREAD

**Issue by JackFromWisconsin** [LemmyNet/lemmy#2766]
I would like to see an option to upload multiple community banners. 

Only one would be displayed at a time, and there would be two options:
Carousel display - this would switch between banners every so many seconds. 
Random - this would display a random banner each time someone loads the page

Not sure the feasabilty for federation with other services (Mastodon or whatnot) but I think it'd be neat for Lemmy.

**Comment by dessalines** [comment]
I don't think we'd want to support multiple banners or multiple icons for users or communities. 

If you'd like multiple pictures, you can put them in the markdown of your sidebar.
