### ISSUE TITLE
`local_only` seems to allow http fetching

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2773]
I'm trying to trace down what `local_only` does in the apub code, and its difficult to follow. It says its stated purpose is to only allow local DB gets for non-authenticated users, but it still seems to allow http fetching: https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/fetcher/webfinger.rs#L36

There are a few other examples too when I traced them down.

**Comment by Nutomic** [comment]
Thats correct, to make webfinger work locally would require storing the mapping `@name@instance` to user/community in the database. So that parameter is misleading, im actually planning to remove it.
