### ISSUE TITLE
[RFC] Personalized experience

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy#2774]
This is a request for comment issue to share ideas on how we could have a more personalized experience. My ideas are:

- Filter system. Admin or user can choose domains to block. That way they never see links from those domains.
- AI recommendation. There is no alternative to Google Discovery/Now/News, or whatever it's called, and a `custom` filter like active/hot/top would accomplish this on Lemmy. With a package like [gorse](https://gorse.io/) and based on votes or other metadata this would provide a personalized experience.

What other ways are there to accomplish a personalized experience?

**Comment by Nutomic** [comment]
Instance allowlist and blocklist are already implemented.

The second point is much too vague, it would need to be much more concrete how such functionality would integrate with existing Lemmy features, and what advantages it would give. Specifically considering that votes already serve as a type of recommendation system.

**Comment by JediMaster25** [comment]
With domains I'm referring to websites, not federation to other lemmy instances.

The thing with votes is that since votes are federated it only makes each instance more of the same, they don't contribute to a personalized experience.

**Comment by dessalines** [comment]
I don't understand this either. Subscribing to a set of communities creates a personalized experience. Some people create 1-person instances, or make posting in a community limited to mods only, in order to prevent others from posting, to have a personalized experience.

With blocking, you're referring to post and comments with a certain domain being blocked / hidden? I'm not sure we'd want to support that.

**Comment by JediMaster25** [comment]
This could be used in a  personalized filter similar to `Best` on Reddit that takes into account affinity with each user based on the score to provide a more customized feed.

Related to https://github.com/LemmyNet/lemmy/issues/2370
