### ISSUE TITLE
Option for users to request communities to be approved by administrators

### ISSUE THREAD

**Issue by felipeforte** [LemmyNet/lemmy#2779]
Currently, Lemmy supports the option to restrict the creation of communities to admins only. Many Lemmy instances which use this feature end up developing their own metacommunity for community requests, showing a demand for a feature like this. This may be an option that Lemmy could have from the get go, similar to how account requests are made

**Comment by dessalines** [comment]
I don't know that we'd want to add this into lemmy in some automated way. Seems much easier to create a post about it, pm or ping admins, have a `new_community_requests` type community. 

All these ways are going to be much more explicit, allow back and forth conversation, and are one less complicated moderation-queue for admins to deal with.
