### ISSUE TITLE
Database migration failing

### ISSUE THREAD

**Issue by olynch** [LemmyNet/lemmy#2784]
### Issue Summary

Whenever the lemmy server starts, it immediately crashes with the error message:

```
thread 'main' panicked at 'Couldn't run DB Migrations', crates/db_schema/src/utils.rs:161:25
```

The logs for postgresql have this:

```
[10289] ERROR:  permission denied: "RI_ConstraintTrigger_a_16639" is a system trigger
[10289]: [10289] STATEMENT:  -- Remove the comment.read column, and create a new comment_reply table,
-- similar to the person_mention table.
--
-- This is necessary because self-joins using ltrees would be too tough with SQL views
--
-- Every comment should have a row here, because all comments have a recipient,
-- either the post creator, or the parent commenter.
create table comment_reply(
  id serial primary key,
  recipient_id int references person on update cascade on delete cascade not null,
  comment_id int references comment on update cascade on delete cascade not null,
  read boolean default false not null,
  published timestamp not null default now(),
  unique(recipient_id, comment_id)
);

-- Ones where parent_id is null, use the post creator recipient
insert into comment_reply (recipient_id, comment_id, read)
...
```

### Steps to Reproduce

1. Setup the lemmy server on nixpkgs-unstable
2. `systemctl start lemmy`

### Technical details

`lemmy_server` 1.17.1, with the nixos options:

```nix
  services.lemmy = {
    enable = true;

    settings = {
      hostname = "localcharts.org";
      federation.enabled = true;
    };

    caddy.enable = true;

    database.createLocally = true;
  };
```

**Comment by olynch** [comment]
OK, I've updated postgresql to version 15, and now I get:

```
[11567] ERROR:  permission denied for schema public at character 28
[11567] STATEMENT:  CREATE TABLE IF NOT EXISTS __diesel_schema_migrations (
               version VARCHAR(50) PRIMARY KEY NOT NULL,
               run_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
```

**Comment by olynch** [comment]
I made the `lemmy` user a postgres SUPERUSER, and now I get the error:

```
Error: LemmyError { message: None, inner: no PostgreSQL user name specified in startup packet, context: "SpanTrace" }
```

**Comment by dessalines** [comment]
You should not be manually trying to set up diesel migration tables, those automatically get generated by the lemmy service. 

Reinstall lemmy using the official docs, because there's no way to recover if you've manually altered those migration tables. https://join-lemmy.org/docs/en/administration/administration.html

**Comment by dessalines** [comment]
Also, use [!lemmy_support](https://lemmy.ml/c/lemmy_support) or the matrix channel to get help with installation.

**Comment by Nutomic** [comment]
@CobaltCause Based on the [documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING), `postgres://` and `postgresql://` should be equivalent. Its odd that only one would work for you.

**Comment by Cmdrd** [comment]
@CobaltCause I tried your manual migration steps but get failures at this point:

`lemmy=> insert into comment_reply (recipient_id, comment_id, read)
select p.creator_id, c.id, c.read from comment c
inner join post p on c.post_id = p.id
where c.parent_id is null;
ERROR:  column c.read does not exist
LINE 2: select p.creator_id, c.id, c.read from comment c
`

Not versed enough in Postgres (yet) to know how to fix this.

**Comment by CobaltCause** [comment]
Hmm, I can't reproduce that from commit `1c9f0c2bed51eb240d8514d28993c5516c019afc` (current main branch) running the migrations with my change (minus the diesel table update) on a fresh postgresql container.

**Comment by CobaltCause** [comment]
Sounds like you didn't follow step 1?

**Comment by CobaltCause** [comment]
(I've just updated https://github.com/LemmyNet/lemmy/issues/2784#issuecomment-1578337686 to reflect what'll ship with future versions of Lemmy (via https://github.com/LemmyNet/lemmy/pull/3002), the old SQL is still available but hidden in a details section underneath it.)

**Comment by glacials** [comment]
@CobaltCause I applied the old solution (before you updated with the new) and it worked swimmingly! Thanks for your help here. But I've now noticed the instance cannot post any comments. I get this error on Lemmy 0.17.3 and 0.17.4:

```
Jun 14 23:49:09 fediverse lemmy_server[298617]: 2023-06-14T23:49:09.474034Z ERROR HTTP request{http.method=GET http.scheme="http" http.host=l.twos.dev http.target=/api/v3/ws otel.kind="server" request_id=02c66a9c-ca12-4b6b-b3cd-2e3ad9ebc7ae http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: couldnt_create_comment: no binary output function available for type ltree
Jun 14 23:49:09 fediverse lemmy_server[298617]:    0: lemmy_api_crud::comment::create::perform
Jun 14 23:49:09 fediverse lemmy_server[298617]:            with self=CreateComment { content: "testing", post_id: PostId(1548), parent_id: None, language_id: None, form_id: Some("comment-form-IedzxiQlxXYN2m09eEQg"), auth: Sensitive }
Jun 14 23:49:09 fediverse lemmy_server[298617]:              at /home/glacials/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lemmy_api_crud-0.17.4/src/comment/create.rs:42
Jun 14 23:49:09 fediverse lemmy_server[298617]:    1: lemmy_server::root_span_builder::HTTP request
Jun 14 23:49:09 fediverse lemmy_server[298617]:            with http.method=GET http.scheme="http" http.host=l.twos.dev http.target=/api/v3/ws otel.kind="server" request_id=02c66a9c-ca12-4b6b-b3cd-2e3ad9ebc7ae http.status_code=101 otel.status_code="OK"
Jun 14 23:49:09 fediverse lemmy_server[298617]:              at /home/glacials/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lemmy_server-0.17.4/src/root_span_builder.rs:16
```

Do you know what I should do to fix this?

**Comment by CobaltCause** [comment]
Unfortunately no, I only ever used 0.17.2. I was able to post comments from my instance, though.

**Comment by adisbladis** [comment]
> @CobaltCause I applied the old solution (before you updated with the new) and it worked swimmingly! Thanks for your help here. But I've now noticed the instance cannot post any comments. I get this error on Lemmy 0.17.3 and 0.17.4:
> 
> ```
> Jun 14 23:49:09 fediverse lemmy_server[298617]: 2023-06-14T23:49:09.474034Z ERROR HTTP request{http.method=GET http.scheme="http" http.host=l.twos.dev http.target=/api/v3/ws otel.kind="server" request_id=02c66a9c-ca12-4b6b-b3cd-2e3ad9ebc7ae http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: couldnt_create_comment: no binary output function available for type ltree
> Jun 14 23:49:09 fediverse lemmy_server[298617]:    0: lemmy_api_crud::comment::create::perform
> Jun 14 23:49:09 fediverse lemmy_server[298617]:            with self=CreateComment { content: "testing", post_id: PostId(1548), parent_id: None, language_id: None, form_id: Some("comment-form-IedzxiQlxXYN2m09eEQg"), auth: Sensitive }
> Jun 14 23:49:09 fediverse lemmy_server[298617]:              at /home/glacials/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lemmy_api_crud-0.17.4/src/comment/create.rs:42
> Jun 14 23:49:09 fediverse lemmy_server[298617]:    1: lemmy_server::root_span_builder::HTTP request
> Jun 14 23:49:09 fediverse lemmy_server[298617]:            with http.method=GET http.scheme="http" http.host=l.twos.dev http.target=/api/v3/ws otel.kind="server" request_id=02c66a9c-ca12-4b6b-b3cd-2e3ad9ebc7ae http.status_code=101 otel.status_code="OK"
> Jun 14 23:49:09 fediverse lemmy_server[298617]:              at /home/glacials/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lemmy_server-0.17.4/src/root_span_builder.rs:16
> ```
> 
> Do you know what I should do to fix this?

I saw the same issue earlier and resolved it by upgrading my postgresql daemon. 
I was always building against version 14 but my host was running on version 12 which is apparently too old for some features that lemmy depends on.

**Comment by CobaltCause** [comment]
FWIW I was using PostgreSQL 14 at the time so that's probably why I didn't hit this

**Comment by glacials** [comment]
I was running PostgreSQL 12 but continue to see the same error after upgrading to 15 (both my database server and web server, to be sure). Was there any other action you had to perform as part of the upgrade?

**Comment by adisbladis** [comment]
> I was running PostgreSQL 12 but continue to see the same error after upgrading to 15 (both my database server and web server, to be sure). Was there any other action you had to perform as part of the upgrade?

Even after upgrading with `pg_upgrade` I was still experiencing issues. I made a dump of the old db and imported into the new one and that worked.

**Comment by glacials** [comment]
@adisbladis Wow that worked, thanks! I have no idea why. All I did:

```sql
CREATE DATABASE lemmy_v1;
```
```sh
pg_dump    -h MY_DB_HOST -U MY_LEMMY_USER lemmy > dump.sql
pg_restore -h MY_DB_HOST -U MY_LEMMY_USER lemmy_v1 < dump.sql
```
And then edited by `/etc/lemmy/lemmy.hjson` to point to `lemmy_v1`, rebooted it, and now I can comment perfectly. ⁉️
