### ISSUE TITLE
Separate emojis from GetSiteResponse

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2785]
Currently, `GetSiteResponse` returns the federated instances, and soon it will return all the emojis.

This was fine for small numbers, but now the connected instances, and emoji counts I'm told may number in the thousands, making these candidates for their own endpoints with paging.

#2616 
#1931

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/4580
