### ISSUE TITLE
Inability to make API routes independent of federation data. 

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2787]
Currently, most of the API is untouchable, because a lot of routes are dependent on outside data:

https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/api/mod.rs#L18

https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/lib.rs#L188

The Chatserver must be able to generate its own context, which is impossible now that relies on outside data: a request counter, and federation config. 

This "extra federation context" is irrelevant for both the HTTP and Websocket API, they only matter for server -> server communication.

This is blocking the chatserver being able to be reverted to a proper Actor.

**Comment by Nutomic** [comment]
That federation data is necessary because a websocket request can also trigger a federation activity send. You can share your code then I will see how to fix it.

**Comment by dessalines** [comment]
One out of many places where reverting becomes impossible. This code is such a mess and I couldn't get very far because of all the circular interlocking dependencies.

https://github.com/LemmyNet/lemmy/blob/websocket_revert_2/src/api_routes.rs#L615

Essentially this is the main issue:

`perform_crud::<Data>(data.0, context, apub_data).await`

There are now **2 contexts**, when there should only be one, with the federation abilities getting bundled into `LemmyContext`.

To be honest, I'm not sure the best way to design and get around this problem.

**Comment by Nutomic** [comment]
I fixed the code and pushed a commit to your branch. Its working but needs cleanup.

**Comment by dessalines** [comment]
Thanks! That helps a ton. I'll try to get this cleaned up within a few days and submitted.
