### ISSUE TITLE
Double websocket messages when joining both the postroom and community room.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2800]
See file: https://github.com/LemmyNet/lemmy/pull/2793/files/9d3f5a4561b8e9784313494c4adff88bd7adad14#diff-8e949c6f814ee8d03b3dcfa0e95a6b3fb6af45d0bf32ca49d49c1f2bd8d6491c

**Comment by Nutomic** [comment]
Websocket is being removed.
