### ISSUE TITLE
Send cache headers for API responses and other endpoints

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#2815]
Yesterday I added [HTTP caching to LemmyBB](https://github.com/LemmyNet/lemmyBB/pull/92) and it works very well, previous errors because of rate limit seem to have disappeared completely. However Lemmy doesnt actually send any HTTP headers related to caching, so its possible that responses are cached too long or too short. This also applies to Activitypub endpoints and RSS feeds.

I think a good solution would be to add a `Last-Modified` header because we already store an `updated` column for most database rows. That way clients can use [heuristic caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#heuristic_caching), and cache items longer if they havent been modified for a long time. We can also set explicit cache durations, but that seems more difficult to get right.That way clients can use [heuristic caching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#heuristic_caching), and cache items longer if they havent been modified for a long time. We can also set explicit cache durations, but that seems more difficult to get right.

Exposing the `updated` time as a header is tricky though. The best solution I can think of is a trait `LastModified` which is implemented for all database structs (returning the `updated` value). Database views and API response structs also need to implement the trait (returning most recent modified time of all members). Thats a lot of code unless we use macros. Or maybe theres a better solution with SQL?

Additionally we should set `Cache-Control: private` in case the client is authenticated, so that the cached value is not shared with anyone else.

**Comment by dessalines** [comment]
You can use the `updated` or `published` column from sql for most items, but IMO its kind of pointless to add, because things like `GetPosts` are variable as it uses a time-decay to sort posts, and `GetComments` might have any number of child comments added at any time. I spose you could use the newest item's published / updated column for those list type ones though too.

**Comment by Nutomic** [comment]
The question is how to read the `updated` or `published` field from `api_routes_http.rs`. Its all generic code, so we cant read from the response structs directly.

Sure things might be outdated for a while, but I dont think it matters if a vote or comment arrives a few minutes later. Caches are handled by the client so they can always request fresh data from the server to update intentionally.

**Comment by dessalines** [comment]
That's a tough one. The `perform_crud` function does get the results, so an optional `last_modified` could be added to all the relevant response types.

**Comment by Nutomic** [comment]
Generics cant access struct fields, so the solution is a trait like `LastModified` with a function that returns the modification date. Problem is that it needs to be implemented for a lot of structs.

**Comment by dessalines** [comment]
Might not be too big a problem, if you can make the default trait impl be `naive_now()`
