### ISSUE TITLE
Comments as indicated by comment count aren't shown

### ISSUE THREAD

**Issue by aschrijver** [LemmyNet/lemmy#2826]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

On lemmy.ml posts do not show the correct number of comments that are listed at the summary in the top of the post.

For this post https://lemmy.ml/post/968357 there should be (now) 5 comments, but zero comments are listed below. When opening the URL in Mastodon I can see 4 comments.

PS. I posted this problem to lemmy-support in https://lemmy.ml/post/970161 which says there should be 12 comments, of which 8 are shown below.

### Steps to Reproduce

1. Navigate to https://lemmy.ml/post/968357
2. See the number of comments: 5 (currently)
3. Find the comments missing below.

### Technical details

There are 3 browser console errors (second error occurs twice):

```
Websocket closed. client.js:2:1157015
    ws https://lemmy.ml/static/js/client.js:2
    dispatchEvent https://lemmy.ml/static/js/client.js:2
    dispatchEvent https://lemmy.ml/static/js/client.js:2
    handleEvent https://lemmy.ml/static/js/client.js:2
    handleCloseEvent https://lemmy.ml/static/js/client.js:2
The Notification permission may only be requested from inside a short running user-generated event handler. 2 968357
```

This on Firefox 111.0.1 on Ubuntu.

The URL's of the comments as seen from Mastodon UI are (one comment not visible on Mastodon too, as viewed from [@smallcircles@social.coop](https://social.coop/@smallcircles)):

- https://szmer.info/comment/72774
- https://aus.social/@ajsadauskas/110233828903055835
- https://lemmy.ml/comment/418756
- https://universeodon.com/@atomic/110241153910392764
- https://emeraldsocial.org/@ch0ccyra1n/110240577519453181

**Comment by dessalines** [comment]
These are federation related issues with other projects.

> In addition I notice that jumping from Notifications to the particular comment also does not work in all cases. I.e. clicking https://lemmy.ml/comment/419075 does not lead me to https://lemmy.ml/post/970161 as it should.

Its working correctly, going to the comment context.

> Lastly, just below comment https://lemmy.ml/comment/418864 it says "One more reply -->" but clicking that does not nothing (and no new errors in console).

My browser's just show the rest of there being just two.

**Comment by Nutomic** [comment]
There is definitely something wrong with the comment counter. [This post](https://lemmy.ml/post/968357) mentioned above says that it has 6 comments, but only 5 are shown. I also checked in the database (`select id from comment where post_id = 968357;`) and it only returned 5 comments. So it doesnt sound like deletion triggers are the problem.

**Comment by aschrijver** [comment]
I wonder if this problem is restricted to specific setups. For me the issue is such that Lemmy has become totally unusable as most comments aren't shown at all. But I'd expected more people to mention similar problems if it was universal issue.

**Comment by Nutomic** [comment]
Do you have "Undetermined" language selected under `/settings`? That could be one reason why comments are missing. It also looks like the displayed count is just incorrect as mentioned in my last comment.

**Comment by aschrijver** [comment]
No, the language is set to 'English'.

**Comment by Nutomic** [comment]
Most of these comments probably dont specify a language and use the default of "undetermined". So you need to enable that in your settings to see them.

**Comment by Nutomic** [comment]
I opened an issue about this here: https://github.com/LemmyNet/lemmy-ui/issues/999

**Comment by aschrijver** [comment]
Yes, thank you @Nutomic, this is the issue indeed. I will add a comment to the UI issue with a suggested improvement to Settings.

**Comment by dessalines** [comment]
This is a back-end issue. Now that there are language filters, that means that comment counts are going to be specific to specific users, and that's not accounted for in the `post_aggregates` table. 

I'm not really sure the best way to handle that without adding more inefficient on-demand queries.

**Comment by Nutomic** [comment]
I believe all the issues with comment counts have been resolved.
