### ISSUE TITLE
How to make default sort setting to "ALL" instead of "Subscribed"? 

### ISSUE THREAD

**Issue by Bakcodi** [LemmyNet/lemmy#2835]
This is one critical problem that is killing many new sites as most sites are small enough that it doesn't matter what they are subscribed to. But, most users don't subscribe properly when they signup. This means most users have their feed restricted and they see less content, which can make them feel site is not active and leave forever.

Apart from that, even when site is active, everyone knows the default sub "General" is subscribed by the most people, so everyone posts everything in "General" ignoring all other communities, thus rendering the community selection feature useless.

I want to know what code change or setting change I should do to change the default setting for all new users to "ALL"

And also what SQL query should I run to reset all existing users settings to "ALL".

**Comment by Nutomic** [comment]
You are looking for "Listing type" setting under /admin. This should also apply to all existing users who didnt change the listing type manually in the user settings.

**Comment by Bakcodi** [comment]
> You are looking for "Listing type" setting under /admin. This should also apply to all existing users who didnt change the listing type manually in the user settings.

@Nutomic I am on the latest 17.2 version. I don't see any such "Listing type" option  under /admin. 

"Type" option is only there in /settings in user settings. Not in admin setting.

**Comment by Bakcodi** [comment]
Ok I saw it show up when I turned on federation with option local and federation. It is no showing up for those who have not enabled federation.

Is there anyway to force reset all existing users settings to "all" instead of "subscribed" in a non federated site?

**Comment by Nutomic** [comment]
The only difference between "Local" and "All" is that the latter includes posts from federated instances. So if federation is disabled, there is no difference between them.
