### ISSUE TITLE
For blocked users, do like what RES does and essentially put a spoiler cover over the username and comment

### ISSUE THREAD

**Issue by PrincessMiki** [LemmyNet/lemmy#2838]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

Yes

Like I might not want to see comments by gamergate69, but i want to see furry4ever's replies to gamergate69 because i get along with furry4ever.

### Describe the solution you'd like

Matrix also has a spoiler function that does basically this. If a user clicks on the blurred content, it reveals it.

### Describe alternatives you've considered

Just talking with furry4ever over matrix

### Additional context

no

**Comment by PrincessMiki** [comment]
> Currently, we join to the `person_block` and `community_block` table to make sure those comments aren't returned at all. We account for missing branches in the tree through the UI comment tree building code.
> 
> I think you have a point, that maybe we should let those comments through, but set the `creator_blocked` field on them, and use that to say `blocked_user`.
> 
> I don't think the same should be done for posts tho.

Yeah not as useful for posts. Like if tom blocks someone, he prob don't care about about discussion on their post

**Comment by Nutomic** [comment]
This needs to be handled by frontends. https://github.com/LemmyNet/lemmy/pull/3965 is related.
