### ISSUE TITLE
[Discussion] Alternative frameworks for HTTP and Websocket?

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2841]
I wanted to get your thoughts @Nutomic , and anyone elses, about Actix as our server for both the HTTP and websocket servers. Some new alternatives to actix are reaching its level of performance, getting some traction, and might be more maintainable and future-proof.

- HTTP alternatives: [axum](https://github.com/tokio-rs/axum)
- Websocket: [Tungstenite](https://github.com/snapview/tungstenite-rs)

This isn't a priority or anything, actix is already very performant, just want to get people's thoughts, and see if there's any interest in these down the road.

**Comment by Nutomic** [comment]
I used axum a bit, its quite nice and a bit less verbose than actix-web. But in terms of features I dont think there are any important differences, you can do the same things with both frameworks. So its really not worth rewriting everything for some minor usability improvements. 

For websocket Im not sure what the difference is between crates. But its probably much easier to switch if there is a good reason for it, because our websocket code is all in a single file.

What I would really like to see is some crate which helps to expose the same API over both HTTP and websocket. We are handling that on our own now and its rather messy, so a dedicated crate could be very helpful. Not sure if this exists. Even just seeing how other projects handle this could be useful.

**Comment by dessalines** [comment]
You're gonna hate me for saying this, since I've been so strongly for websockets before, but I've been rethinking using websockets altogether. 

Pros:

- Live / pushed comments and posts (which people don't seem to like).
- Live vote scores
- Live updates for things like comment / post edits, new comments, appointing moderators, bans, etc.

Cons:

- Huge burden to maintain, both on the server and in lemmy-ui.
- Possible memory leaks.
- Not scalable.
- The server side as you say, requires messy code duplication via that `Perform` trait. It'd be much easier to just support HTTP, and maybe one optional websocket route that's just for `unread_counts` or something. But that could also be done with polling every minute.
- The UI side is a pain to maintain, having to keep lists of data, scan through them for the ids, and update the data in place on receiving new info. Having to join and leave websocket rooms, dealing with duplicated received messages, etc. Its not fun on either the UI or server side.
- The UI has to fetch data when getting to a new route anyway, so a lot of the websocket is pointless.
- Bad on battery and network. Lemmy-ui probably wastes a lot more network and battery than it should.
- Useless for phones (for obvious battery life reasons), which (should) use push notifs for live data.
- People seem to not want new posts and comments moving things around on their page anyway.

As I've been thinking about redoing lemmy-ui in perseus / rust, there wouldn't be any choice anyway: we'd have to use the HTTP API.

AFAIK lemmy-ui and maybe the tankiereplybot are the only clients of the websocket. 

> What I would really like to see is some crate which helps to expose the same API over both HTTP and websocket. We are handling that on our own now and its rather messy, so a dedicated crate could be very helpful. Not sure if this exists. Even just seeing how other projects handle this could be useful. Maybe actix-web maintainers know something in this regard.

I did some googling, and there are some javascript / node type frameworks that organize things to support both. But it seems they all handle the messages differently.

**Comment by Nutomic** [comment]
I have never been an advocate for websocket. If you ask me, tear it all out from top to bottom and use HTTP instead. Notifications can easily be handled with [long polling](https://www.pubnub.com/blog/http-long-polling/). But to be honest I dont need live updates, they make things too rushed.

**Comment by dessalines** [comment]
Very well, I'll make an issue for it. 

As far as timing tho, this should be in the far future, since lemmy-ui is entirely dependent on websockets. And if we rip out its heart, then we might as well create a lemmy-ui-v2 using sycamore / perseus, and get all the benefits of rust, rather than go through a ton of work to convert lemmy-ui from websockets to using the HTTP client.

So maybe 2 or three minor versions in the future.

**Comment by Nutomic** [comment]
I think we can switch lemmy-ui to HTTP for 0.18 without problems. The js library already supports HTTP, so it would only require adding some endpoints for long polling (notifications etc). Then I would remove websocket code from the backend in 0.18 as well so we can cleanup all that code. And in that case it probably doesnt make sense to finish #2819.

**Comment by SleeplessOne1917** [comment]
> The UI has to fetch data when getting to a new route anyway, so a lot of the websocket is pointless.

While I haven't poked around much in the backend code, this really stood out to me as a consumer of the API. For example, the [bot library](https://www.npmjs.com/package/lemmy-bot) I made has to poll using a websocket connection to get things to respond to. If polling is what needs to be done, I don't really see the point of using websocket.
