### ISSUE TITLE
Word filter

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#2842]
This shouldn't be confused with the existing slur filter. Instead of defining one regex that matches any word an instance admin considers naughty that turns it into the string "*removed*", word filters would instead be a list of regexes that convert strings into different strings that admins can specify. I'll give an example so that my idea is more clear.

Consider an antifascist instance. To spice things up, they might use some of the following word filters:

- /Mussolini/i => "ᴉuᴉlossnW"
- /Ron DeSantis/i => "Ron DePantsPiss"
- /libertarian/i => "lolbertarian"
- the n word (not gonna type that one out) => "Look at me, I'm a dumb racist! Everyone make fun of me!"

It would basically be a more versatile slur filter that allows not just shutting up bigots, but giving communities flavor. I think this could be added so that it doesn't conflict with the existing slur filter functionality: the regular "bad word" => "*removed*" filtering could be another word filter that defaults to "*removed*".

**Comment by dessalines** [comment]
I wouldn't be opposed if someone wanted to add it.

**Comment by dullbananas** [comment]
Moderators of individual communities should also be able to configure this

**Comment by Nutomic** [comment]
Its better to implement this as a plugin. In fact the existing slur filter could also be moved to a plugin.

**Comment by dessalines** [comment]
I don't think we should prioritize features as plugins, rather than building them into lemmy, especially ones that should be available to everyone, or could benefit everyone. Obvi we should take these on a case-by-case basis. 

Anyways we can re-open this if someone wants to work on it.
