### ISSUE TITLE
Lemmy Installation Problems

### ISSUE THREAD

**Issue by Bag72** [LemmyNet/lemmy#2854]
I like the look of Lemmy.  It looks like it could be exactly what I am looking for but I am just unable to get it installed.  I have a QNAP NAS and I have tried to install it on that.  I've also tried on a stand alone system and it fails with obscure errors.   Giving up I have asked others to try in case it was something silly I was doing and they can't install it either.

Yet I see many people using it and they don't seem to have any issues.  I was wondering if anyone has managed to install Lemmy from scratch using the latest docker images.     I suspect the latest images are missing something important.

Is there any other ways to install it beside Ansible?  Is there any Linux installs available or preferably different docker images?

I'd still like to use Lemmy.

**Comment by Nutomic** [comment]
Please post in https://lemmy.ml/c/lemmy_support (you can also comment from other platforms like Mastodon) or use the Matrix chat. Make sure to include actual error messages. The docs also have information for manual docker installation or even without docker.

**Comment by dessalines** [comment]
https://join-lemmy.org/docs/en/administration/administration.html
