### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#2862]
This definitely falls more under nice to have than necessity, but after using Lemmy's API for awhile I think it's the kind of use-case that GraphQL was designed to address (the client-server API at least: I couldn't say for the server-server activitypub API). For instance, consider the `PostView` type:

```rust
pub struct PostView {
  pub post: Post,
  pub creator: Person,
  pub community: Community,
  pub creator_banned_from_community: bool,
  pub counts: PostAggregates,
  pub subscribed: SubscribedType,
  pub saved: bool,
  pub read: bool,
  pub creator_blocked: bool,
  pub my_vote: Option<i16>,
  pub unread_comments: i64,
}
```

On the one hand, it's pretty useful to be able to get all of this related information back on the client. On the other hand, it's also far more information than is needed for any given request. This is one of the problems GraphQL was made to solve. Suppose I need the name and body of a post, the name and display name of the person who made it, the name of the community it was posted on, and the number of upvotes and downvotes a post received. A GraphQL query to fetch that would look something like the following:
```graphql
query GetPost($postId: ID) {
    post(id: $postId) {
        name
        body
        creator {
            name
            displayName
        }
       community {
            name
        }
        upvotes
        downvotes
    }
}
```

What makes GraphQL nice in this case is that the only data that will be returned to the client will be what the client asked for. Another nice thing about GraphQL API's is that they enforce a typed contract between the client and the server. If a client tries to send a datatype that the API was not expecting, the request will fail without the need for any extra validation logic. There are a couple of Rust GraphQL libraries out there that can be used like [juniper](https://github.com/graphql-rust/juniper) and [async-graphql](https://github.com/async-graphql/async-graphql).

**Comment by dessalines** [comment]
As long as it wouldn't alter how we're storing the data in SQL, but only how we're returning it, it could be beneficial... but I don't know if the amount of work it'd require would be worth the data savings. GraphQL is meant for massive data sets right, where you have a single endpoint serving up your entire database. Since we're not just reading, but also creating and updating data, we need specific endpoints and result types that show what data got updated anyway.

Also with `ts-rs`, we now auto-generate typescript objects directly from the rust source code ones ( and I also just wrote my own from ts -> kotlin to get types up to date for jerboa). I'm not sure that any front-end client for graphql would be able to provide that strict of type-checking.

**Comment by SleeplessOne1917** [comment]
Fair enough. I'll close the issue.

**Comment by bqv** [comment]
> Since we're not just reading, but also creating and updating data, we need specific endpoints and result types that show what data got updated anyway.

For the record, GraphQL can do this just fine. Query is one operation, you can also Modify and Delete, etc.

GraphQL is also type checked by definition. It's actually literally what you're doing at the moment by hand, but automated and in a more organized manner. It also leads to free implementations in just about every language under the sun.

This suggestion is a +1 from me, it's getting frustrating that the API keeps changing in subtle ways that aren't telegraphed anywhere clear

I can understand if you don't want to do it yourself, but don't dismiss the suggestion; you want GraphQL

**Comment by SleeplessOne1917** [comment]
> For the record, GraphQL can do this just fine. Query is one operation, you can also Modify and Delete, etc.

To add more information for anyone reading, there are 3 types of operations in GraphQL: query, mutation, and subscription. Queries are basically GET requests that retrieve data without changing anything on the server. Mutations are like POST, PUT, PATCH, and DELETE requests in that they are used to change data on the server. Subscriptions are for realtime messages and are often implemented with websockets.

The main complications I can see in using GraphQL are:
1. It's harder for admins to set up caching for
2. There is no agreed upon way to upload files

I'll gladly try to implement it if there is more widespread demand for it. [I've implemented GraphQL APIs before](https://github.com/5e-bits/5e-srd-api/tree/main/src/graphql), granted only in javascript. I still have to both git gud at rust and learn the backend codebase more.
