### ISSUE TITLE
Add a default registration application question to the DB

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2864]
When setting up a new lemmy instance, the default mode is Registration Required.

But the registration question is empty / blank, so the front end has a sign-up form with no registration questionnaire field. If the user tries to sign up, they get an error because they didn't provide a registration application answer.

A default should be provided, so that the front end can show that field.

**Comment by Nutomic** [comment]
Just tested this with a clean db from latest main. There is definitely a default question which is: `to verify that you are human, please explain why you want to create an account on this site`

**Comment by dessalines** [comment]
Hrm... must have been an old version I was using, sry about that.
