### ISSUE TITLE
Banned Moderators Can Do Actions

### ISSUE THREAD

**Issue by carolynzech** [LemmyNet/lemmy#2868]
### Issue Summary

`check_community_banned` and `check_community_deleted_or_removed` aren't called in all controllers restricted to mod/admins.

This allows for some weird edge cases. For example, the perform trait for BanFromCommunity doesn't enforce restrictions on who is getting banned, so it's technically possible for an admin/mod to ban another mod. Since `check_community_banned` isn't called, that banned person can come back and use their mod permissions to unban themselves.

I could see a case where an admin wants to ban a mod from a community, so probably worth checking for.

**Comment by dessalines** [comment]
Good catch, thx.

**Comment by Nutomic** [comment]
Do you want to make a pull request to fix this?

**Comment by kartikynwa** [comment]
If a moderator of a community is banned, should they be removed as moderator as well?

**Comment by Nutomic** [comment]
On the one hand it makes sense to see when a community is actually unmoderated. On the other it will cause complications if a user is banned and later unbanned. Not sure.

**Comment by Dekker3D** [comment]
My novice take on it: it might be best to err on the side of caution.

Keep the "moderator" role for that user, which they can't do anything with while banned (right?). When you try to unban that person, Lemmy shows you a message that this person was a moderator, and gives you the choice to let them regain that role or not.

**Comment by scottmerchant** [comment]
I've been testing this a bit locally and I can't see a way to ban a user from a community they mod. I might be wrong but from what I can see it doesn't come up with the option?

In the screen cap below `user2` is a mod and `user3` is not and you can see the difference in the options.
<img width="587" alt="image" src="https://github.com/LemmyNet/lemmy/assets/97430840/9c573cb2-9260-4629-b5a6-81db0d7b0aa3">

Is there another way to do it that I'm not aware of?
