### ISSUE TITLE
`Error: unknown` given when no language is provided, to a limited language post.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2869]
The dev of Mlem found this. When providing no / missing language to a create post or create comment on a limited language post, it gives error unknown.

If the wrong language is given, it does correctly give the full error.

**Comment by Nutomic** [comment]
What are the steps to reproduce this?

**Comment by buresdv** [comment]
> What are the steps to reproduce this?

Send the following `CreateComment` command to this post: https://lemmy.ml/post/1095084 (WebSocket command in my case):
`{"op": "CreateComment", "data": {"auth": "[auth token]", "content": "[comment body]", "post_id": 1095084}}`, make sure to not specify a language ID.

The API will return `{"error":"Unknown"}`

**Comment by Nutomic** [comment]
I just deployed a new release candidate which includes some language related fixes. Can you try again to see if that helps? If not, tell me which user languages you have configured under /settings because that is relevant for automatic language selection.

**Comment by buresdv** [comment]
Apologies for my (very) late response. Your fixes worked!

Unfortunately, some instances, like Kbin, still require that `language_id` field to be set, so I still had to implement a language tagger regardless

**Comment by Nutomic** [comment]
Great! About Kbin you should open an issue in their repo.
