### ISSUE TITLE
Lemmy Error message enums

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#2871]
Currently, when a `LemmyError` is made, it's done like this: `LemmyError::from_message("passwords_dont_match")`. Instead of having the errors use a string for the message, I'm wondering if an enum would be better. It would get rid of magic string slices, and it could perhaps also be used to generate typescript types for the js client so that clients have a better idea of what the possible errors are.

**Comment by dessalines** [comment]
i18n translations for these errors do need to be simple string keys anyway. And tagged enums might be a little complicated to deal with on the client-side, especially when all we care about is the string error message from the server.

**Comment by Nutomic** [comment]
Error enums could be serialized as strings, see [enum representations](https://serde.rs/enum-representations.html).

**Comment by lionirdeadman** [comment]
Closing based on merged PR
