### ISSUE TITLE
Notify admins of sign up after new user has verified email

### ISSUE THREAD

**Issue by SerenadeX** [LemmyNet/lemmy#2881]
### Is your proposal related to a problem?

When new users apply to sign up, the admin gets an email before they have verified their email.  If their email is not verified they will not show in the registration application list.

### Describe the solution you'd like

Do not notify admins of applications until emails are verified

### Describe alternatives you've considered

None, pretty basic solution

### Additional context

Obviously this situation only happens when the options to require email verification and registration application are selected

**Comment by SerenadeX** [comment]
I guess one alternative could be to show all registrations even if they haven't verified but I think you avoid more spam with my proposed solution

**Comment by dessalines** [comment]
This is def a good idea, just might be a while before we can get to it.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3995
