### ISSUE TITLE
Concerns over the name of the project

### ISSUE THREAD

**Issue by acerspyro** [LemmyNet/lemmy#2896]
I have some concerns over the name of the Project, Lemmy.

This has already been discussed [here](https://github.com/LemmyNet/lemmy/issues/1460), but I am repoening an issue as I don't think a simple Wikipedia article will help the project's SEO woes.

Although it is pretty fun to name a project after someone, it quickly becomes an SEO nightmare. Anyone trying to join Lemmy is now bombarded with results about Lemmy, the bassist from Motörhead.

This means you always have to do the awkward dance of typing in "lemmy app" or "lemmy site" instead, followed by your query.

Here I am trying to get to lemmy.ca, the Lemmy instance for Canada:

![image](https://github.com/LemmyNet/lemmy/assets/4400999/561e19f9-1e18-46b3-acf5-4f0a30d8d70d)

Even when a search engine understands your request, results are polluted with results about Lemmy the bassist:

![image](https://github.com/LemmyNet/lemmy/assets/4400999/dfe6d449-53ae-4fb9-98a8-8550bbecbbd8)

**Comment by dessalines** [comment]
We've been with this name for over three years now and have no interest in changing it to satisfy search engine optimization.

**Comment by aerkiaga** [comment]
@acerspyro seems to be a Google issue. E.g. on DDG:

![image](https://github.com/LemmyNet/lemmy/assets/38228836/fe269010-286b-4b58-b836-17c3015978f1)

Yahoo Search:

![image](https://github.com/LemmyNet/lemmy/assets/38228836/0fbf5961-4159-4a17-a34a-69d78ea09b47)

Bing:

![image](https://github.com/LemmyNet/lemmy/assets/38228836/147e9224-2d6b-498a-a885-2c8e61a2c78a)
