### ISSUE TITLE
A Broken slur filter regex can stunlock the site

### ISSUE THREAD

**Issue by makotech222** [LemmyNet/lemmy#2900]
A regex that fails to compile gives the following error 

![image](https://github.com/LemmyNet/lemmy/assets/4389156/2318f455-a183-4987-97ea-9b285de871af)

Which will prevent people from posting/commenting. Also prevents admins from saving site settings, required admin to make manual changes to db to clear the regex.

**Comment by dessalines** [comment]
Hrm, could have sworn we validate that it's okay regex before saving, but maybe not. This is a good first issue.

**Comment by tuxiqae** [comment]
I would love some pointers on how to confront that issue

**Comment by tuxiqae** [comment]
@makotech222 Could you please provide examples to the pattern which caused this issue?

**Comment by makotech222** [comment]
[slrfilter.txt](https://github.com/LemmyNet/lemmy/files/11682443/slrfilter.txt)

excuse the slurs, obviously.

**Comment by Nutomic** [comment]
Slur filter is updated here, so you need to compile the regex from data and return an error if it fails.

https://github.com/LemmyNet/lemmy/blob/main/crates/api_crud/src/site/update.rs#L113

**Comment by multiplicitypoe** [comment]
This happened to me with a very simple filter, and prevented any user from posting on the site or the admins from updating settings to fix it.

```(foo|bar|)` 

Note how the last part of the regex has nothing after the `|`, meaning it matches anything. 

To fix this, I followed these steps

```
ssh you@yourdomain.com
sudo docker ps | grep postgres # This prints the container you'll need to go into 
# Example output: be98b4276de6   postgres:15-alpine           "docker-entrypoint.s…"   3 days ago       Up 3 days       5432/tcp                             website_name_postgres_1
sudo docker exec -it /bin/bash website_name_postgres_1
psql -U lemmy # get into the postgres database
# The following commands are to be typed/pasted into the psql prompt
# Confirms you can see slur_filter_regex as a column in the local site table
SELECT column_name FROM information_schema.columns WHERE table_name   = 'local_site';
# See the value of slur_filter_regex, confirming it's incorrect
SELECT slur_filter_regex FROM local_site;
# Adjust slur filter regex to something that won't soft lock the site. Note that this affects all slur filter regexes, if you have more than one in your psql database for some reason
UPDATE local_site SET slur_filter_regex = '(dont-edit-this)';
```

And this resolved my issue 😄 

Hope this helps anyone seeing this in the future

 I'd suggest prioritizing this issue, since new moderators coming from Reddit in the next few days will probably want to import slur filters and make mistakes while doing so.

**Comment by dcormier** [comment]
@ContemporaryArtwork, I'd recommend against using `catch_unwind()` for this. Instead the error should be handled. `build_slur_regex()` may need to be modified to return a [`Result`](https://doc.rust-lang.org/std/result/enum.Result.html) so the error so that it can be handled.

From [the `catch_unwind()` docs](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html):

> It is **not** recommended to use this function for a general try/catch mechanism. The [Result](https://doc.rust-lang.org/std/thread/type.Result.html) type is more appropriate to use for functions that can fail on a regular basis. Additionally, this function is not guaranteed to catch all panics, see the “Notes” section below.

**Comment by ContemporaryArtwork** [comment]
Yeah, that makes sense. Somehow I missed that part of the docs.
