### ISSUE TITLE
Don't announce / boost replies to improve interoperability with other fediverse clients

### ISSUE THREAD

**Issue by finnim** [LemmyNet/lemmy#2901]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

Currently the community account (eg. @technology@lemmy.ml) boosts every single reply or comment made in the local instance. Now that there's much more traffic if you're subscribing from other fediverse clients like Mastodon, the feed provided by community accounts like @technology@lemmy.ml is becoming very very "spammy" and not very useful since any new posts are hidden by countless comments.

### Describe the solution you'd like

The community accounts should only boost / announce posts to fediverse subscribers instead of all replies. Then, users could click on a post and it should load all its comments.

I've been looking a bit at the code and there seems to be an activitypub related crate that checks whether a certain activity was created remotely or locally. It then proceeds to announce the activity if it was created locally. I'm not an expert on ActivityPub but in order to implement the improvement/solution it could be enough to check on whether an activity has the "inReplyTo" property and simply not announce it if that's the case.

(Describe your proposed solution here.)

### Describe alternatives you've considered
Not using Mastodon to subscribe to lemmy communities.

However, I believe that this is far from ideal, especially since Lemmy communities will only benefit from the added traffic, visibility and participation in the comments. Lemmy itself has a lot of advantages such as upvotes, downvotes, post ordering by activity, scores, etc... which make it unique.

Allowing mastodon/pleroma/calckey etc... users to have access to a community's feed that is more useful by only showing posts will not hurt the instance or detract from the usefulness of using a local accounts. On the contrary, it would drive engagement and communication, while power users would definitely want to have a local/lemmy account.

**Comment by Nutomic** [comment]
The announce is used so that actions can reach other Lemmy instances, see [FEP 1b12](https://codeberg.org/fediverse/fep/src/branch/main/feps/fep-1b12.md). Lemmy cant influence how other platforms decide to render this. So this needs to be fixed in Mastodon.
