### ISSUE TITLE
Lemmy.ml consistently going down, having slow loading times, and a huge amount of CLS.

### ISSUE THREAD

**Issue by jazir5** [LemmyNet/lemmy#2905]
I do not know whether these are bugs specific to Lemmy.ml, or affect all Lemmynet instances.  I'm currently utilizing the lemmy.ml instance.

### Issue Summary

Lemmy.ml has gone down repeatedly, but it is completely sporadic, over the last few days since I registered on the site. It seems to go offline every 30-60 minutes, and then randomly become accessible again. In addition, loading times are frequently exceptionally slow, and there is a huge amount of CLS going on occasionally when loading a page. 

![lemmy ml down](https://github.com/LemmyNet/lemmy/assets/31750063/0b713d5f-9cd8-4e88-b36d-2322f61bde26)

Isitdownrightnow.com confirms that Lemmy.ml is down for everyone when I cannot access the site. Sometimes I will receive an Nginx error, sometimes it's some variation of can't connect, there doesn't seem to be a consistent error that occurs every time it goes down.

The CLS occurs on pretty most page loads. Here is one example of what the broken layout looks like:

![Lemmy UI totally breaking](https://github.com/LemmyNet/lemmy/assets/31750063/45598504-3904-42da-b7c4-0ef477ebe365)

In the example provided, the actually formatted UI that Lemmy.ml is supposed to have did not load after any amount of time at all. The page simply remains broken until refreshed. Normally when the CLS occurs, it breaks for about .2-.8 seconds, then rectifies itself and loads the correct layout.

I have ublock origin installed just so you are aware, that may or may not be relevant to the CLS issue, I wanted to mention it just in case. I doubt that it is however, as sometimes Lemmy.ml pages will load without CLS.

### Steps to Reproduce

1. Load any page on the website, any of the 3 issues may occur sporadically, sometimes the site loads very slowly and the CLS breaks as well. 
 
2. Sometimes there is no CLS, but there does not seem to be any rhyme or reason as to when the CLS issue occurs. I can load the same page multiple times, and it will only break temporarily seemingly at random.

3. Loading Lemmy.ml pages is all that is required to see these issues when they occur, but there is seemingly no indication of when these errors may happen. To reproduce them, you will have to continuously refresh a page, or navigate around the site until you encounter them.

**Comment by dessalines** [comment]
We're having stability issues, and lots of DB fighting, due to the increased load. 

We're pretty sure most of it is related to websockets, which is why the next release will have them removed. The back-end for this is done, and the front-end for that is close to being done.

These stability issues seem to be affecting only the larger instances right now.

**Comment by RocketDerp** [comment]
I also observe that the instances don't seem to have a "Error Landing Page" to send the end-user to when they run into an internal site error. It just seems to spit a single line on the HTML output page with a technical error.

**Comment by Nutomic** [comment]
Server was upgraded and works much smoother. Anyway this is not what the issue tracker is for.

**Comment by beedell-roke** [comment]
> https://github.com/LemmyNet/lemmy/issues/2905#issuecomment-1591287033

@Nutomic, does no issue tracker for the flagship instance exist? I ask per https://github.com/LemmyNet/lemmy/issues/4884#issuecomment-3065258100.

**Comment by dessalines** [comment]
You can use https://lemmy.ml/c/meta for issues there.

**Comment by beedell-roke** [comment]
@dessalines, thanks. Posted to [`lemmy.ml/post/33203159`][1].

[1]: https://lemmy.ml/post/33203159
