### ISSUE TITLE
Add `limit` and `after` parameters to rss feed results

### ISSUE THREAD

**Issue by tillcash** [LemmyNet/lemmy#2906]
Allow the `limit` and `after` parameters similar to Reddit’s RSS feed to fetch a specific number of results from a community.
https://stackoverflow.com/questions/8292143/reddit-rss-feed-more-than-just-the-25-results

**Comment by dessalines** [comment]
This would be a good first issue for someone. The relevant file is `feeds.rs`

**Comment by sgbasaraner** [comment]
This issue is now resolved, right?

**Comment by Nutomic** [comment]
Yes
