### ISSUE TITLE
Lemmy as an alternative front-end

### ISSUE THREAD

**Issue by avidseeker** [LemmyNet/lemmy#2907]
One of the things that may hold people back from switching to Lemmy is FOMO on Reddit. Adding a way to view Reddit posts from Lemmy, would significantly make it more appealing to switch to, especially since many people are already used to 3rd party apps to view Reddit.

There already exist frontend projects like Libreddit and Teddit. So that should make it easier to port into Lemmy.

URL can be a pseudo instance like: https://lemmy.ml/c/linux@reddit.com, and comments/interactions can be disabled to reflect the status of the actual Reddit post.

As for how the API changes will affect FOSS front-ends of Reddit, I'm not [yet sure](https://github.com/libreddit/libreddit/discussions/816) but I hope there would still be a way, even if by non-api methods like scrapping.

**Comment by dginovker** [comment]
Functionality-wise, this doesn't seem related to what the Lemmy protocol should do. Maybe a Lemmy instance could run this.

**Comment by RocketDerp** [comment]
I expect you would run into legal battles with Reddit.

**Comment by Nutomic** [comment]
This is completely out of scope.

**Comment by avidseeker** [comment]
If it's not possible to completely mirror Reddit, then can there be cross-posting feature? Just like [Mastodon tools](https://moaparty.com/) to cross-post between Twitter and Mastodon. This also depends on the Reddit API for letting the user post from 3rd party tools.

**Comment by dessalines** [comment]
You're free to build one, as lemmy has an open API. But most people would prefer the content on their own instances to come organically, not from cross-post bots.
