### ISSUE TITLE
Comments that are removed/deleted still return content

### ISSUE THREAD

**Issue by makotech222** [LemmyNet/lemmy#2909]
If a comment is removed/deleted I think that the api should not return the CommentView.content field. Some third party frontends do not properly hide that content, and I think the intention if a user removes content should be that it is no longer public.

**Comment by Nutomic** [comment]
I believe that it is only returned if you are the comment creator, and possibly for admins/mods. Did you test this without login?

**Comment by makotech222** [comment]
Ever considered dropping diesel? something like this is trivial in other ORMs i've worked with. Diesel has been probably the most difficult i've ever worked with and its so weak

**Comment by Nutomic** [comment]
What do you suggest? And how exactly is it easier than diesel?

**Comment by makotech222** [comment]
I know there are other orms for rust, just from casual browsing of programming forums, they seem to be more liked. Here's how c#  efcore does it

![image](https://github.com/LemmyNet/lemmy/assets/4389156/1b32063f-161c-4fe4-8bdc-fc3225f5c17a)

Literally trivial. I would have no idea how to accomplish that in diesel cause its so incredibly rigid

**Comment by dessalines** [comment]
That's **also** a post-select, code-manipulation solution to the problem. The correct solution to this should happen at the postgres / select layer.

Its probable that diesel can do proper postgres conditional `case when` selects, you'd just have to look into the diesel docs or ask them how to do this.

**Comment by makotech222** [comment]
Nope, all sql

![image](https://github.com/LemmyNet/lemmy/assets/4389156/f4ba0093-28b0-47a8-b71e-8c3025445081)

**Comment by dessalines** [comment]
Okay then, I'm not familiar with that library so it looked like the closure was moving the row results into them. Did you look into whether diesel supports case when conditionals?

**Comment by pe1uca** [comment]
I'm wondering, wouldn't it be better to actually delete the content instead of just setting the flag?  
And I mean in addition to the flag, so still have the row but the content will be empty (also for posts) plus the deleted flag.  

Also, seems deletes aren't federated   
You can see in here the comment in my instance has been deleted https://lemmy.pe1uca.dev/comment/13578  
But it still shows up in other instances https://beehaw.org/comment/107195

**Comment by Nutomic** [comment]
Deletes federate, but in a distributed system like Lemmy there is no guarantee that they will be delivered successfully.
