### ISSUE TITLE
SQL Trigger/function 'person_aggregates_comment_count' is broken

### ISSUE THREAD

**Issue by makotech222** [LemmyNet/lemmy#2910]
This particular subquery in the function: 
![image](https://github.com/LemmyNet/lemmy/assets/4389156/8acc113a-bb1d-4450-95c9-81c20a31f93c)

Is causing performance to blow out. Its nonsensical, and doesn't work as intended. Will always set persons comment score to 0 and needlessly sums up every comments score.

**Comment by phiresky** [comment]
wow, this is great. I didn't even realize. that means we can get rid of all those expensive O(n^2) triggers since they don't even work 🤣

**Comment by phiresky** [comment]
I still don't understand why it has to recompute anything at all though. Can't it just subtract the already computed value from comment_aggregates instead? something like

`update person_aggregates ua set comment_score = comment_score - (select score from comment_aggregates where comment_id = OLD.id) where id = OLD.person_id`

**Comment by phiresky** [comment]
Could be because of trigger order - on DELETE, if `comment_aggregates_comment` runs before this one, then the row in aggregates will be missing. Fixable by merging the triggers or renaming them (they are run in alphabetic order)

**Comment by phiresky** [comment]
Merging them shouldn't be *too* hard. #3727 is a start but incomplete so far. Alternatively maybe we can just those parts of the triggers for now since they don't work anyways.

**Comment by phiresky** [comment]
I've created a PR to simply remove that part of the trigger for now: https://github.com/LemmyNet/lemmy/pull/3739

**Comment by RocketDerp** [comment]
> Can't it just subtract the already computed value from comment_aggregates instead?

I have discussed this approach in other related TRIGGER logic-bomb issues, and such logic is demonstrated in pull request https://github.com/LemmyNet/lemmy/pull/3727

**Comment by RocketDerp** [comment]
With the release of 0.18.3 today, this issue can be closed?

**Comment by phiresky** [comment]
I think so, though it simply doesn't update the comment_score value at all for now, that sti has to be implemented, probably in a merged trigger like #3727
