### ISSUE TITLE
docker modifications?

### ISSUE THREAD

**Issue by NathanTech7713** [LemmyNet/lemmy#2912]
Hello,

Sorry if this is the wrong place for this, I'm a little stuck.
the docker installation is for Nginx, but i am using apache.

As an addition to that, I already run several websites through my web server, so having Lemmy bind to port 80 by default will not work for me. I figured I'd set up a proxy for lemmy.mydomain.com to point to localhost:port, but I've not got that faryet.

I've also tried building from scratch, cloning the github repo and following the guide (except instead of using /usr/bin in the cargo install I used /lemmy. It ended u placing the install file in /home/myusername/.cargo. It then throws me errors for bootup whether it's not being able to find a settings file, or not seeming to see my config file. It all goes wrong.

to that end, is there:
1. a way for me to start completely from scratch here?
2. 2. Is there a docker that works with apache2?
3. 3. Or is there a way for me to modify the docker installation?

thanks in advance,

**Comment by Nutomic** [comment]
This repo is not for support, you can post in https://lemmy.ml/c/lemmy_support
