### ISSUE TITLE
Add a top-level `/version` route, that redirects / loads the nodeinfo

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2914]
This would be really useful to have. Should probably be in the lemmy code directly rather than an nginx redirect.

Example: https://enterprise.lemmy.ml/nodeinfo/2.0.json

... or on 2nd thought, it could just load the version string. Either one works for me.

**Comment by Nutomic** [comment]
Whats the advantage compared to requesting `/nodeinfo/2.0.json` directly?

**Comment by dessalines** [comment]
For app devs. @buresdv had no idea about that nodeinfo route, and its fairly common for both users and devs to expect a `/version` at the top level.

**Comment by Nutomic** [comment]
Alright, though alternatively we could mention it in the docs.
