### ISSUE TITLE
How to tell if Enum will be serialized to String or Int?

### ISSUE THREAD

**Issue by Flex4Reddit** [LemmyNet/lemmy#2916]
I'm working on a Kotlin client that deserializes Lemmy responses into Kotlin data classes. When I deser `GET /api/v3/site`, I noticed that `site_view.local_site.registration_mode` is a String, while `my_user.local_user_view.local_user.default_listing_type` is an Int. 

[However, both of these enums are declared similarly,](https://github.com/LemmyNet/lemmy/blob/1b4f9957061e978333904ca32c7d379d51795c6d/crates/db_schema/src/lib.rs#L84) yet surprising they are serialized to different types. How can I tell if an enum will be serialized into Strings or Ints? I'm not familiar with Rust, so please point me to the right direction if I've been looking at the wrong file this whole time.

Thanks

**Comment by dessalines** [comment]
I've pretty much already written one. It's in the jerboa `autogen_types` branch. It intelligently generates them from the typescript ones, which generated them from rust.

If you can figure out how to publish a kotlin library tho, i'd love to do so. The ppl at sonatype couldn't help me.

**Comment by Flex4Reddit** [comment]
I see, some types are hard-coded to be overridden in the copy script:
```
sed -i 's/listing_type: String/listing_type: ListingType/g' "$kt_file"
```

And these types are already declared [here](https://github.com/dessalines/jerboa/blob/466195d05f85b0da52ab2fcd4f99cc9568a88de3/app/src/main/java/com/jerboa/datatypes/Source.kt#L439)

However, `ListingType` and `SortType` are declared as Strings. So why are they sent as Ints from the server?

```
// GET /api/v3/site
{
  "site_view": {
    "site": {
      "default_post_listing_type": "Local", << this is fine
  ...
  "my_user": {
    "local_user_view": {
      "local_user": {
        "default_sort_type": 0, << huh?
        "default_listing_type": 1, << huh?
      },
```

**Comment by dessalines** [comment]
Because that server isn't running our `main` branch, that has more updated code.

**Comment by Flex4Reddit** [comment]
I see, guess I'll make some hotfixes on the client side to workaround these inconsistencies. 

Hopefully there will be a single source of truth for data schemas someday.

**Comment by dessalines** [comment]
The tagged versions of lemmy-js-client are the best source of truth. 

That auto-gen kotlin types script works off the lemmy-js-client codebase, so you'd simply check out the tag you want, and run the script.


It was a nightmare before I started these auto-generated types, having to manually keep track of changes by diffs.
