### ISSUE TITLE
Moderation & Ads/trackers

### ISSUE THREAD

**Issue by AidenY69** [LemmyNet/lemmy#2918]
I read the /docs/ page and still have the question of how everything is interconnected. I know that users can signup on one self-hosted instance and then that account can be used on other self-hosted instances, but does that mean that there's also a central admin that can exert power/influence on a technical level for self-hosted instances?

For example, lets say someone hosts an instance of Lemmy, and the user base goes into right wing propaganda, etc., would the creators of Lemmy (you), be able to shutdown that platform, or ban the users, or whatever the case is?

I'm trying to understand where the connection between what the creators are capable of doing to other self-hosted instances.

Second question is why are ads not allowed if the server can be self-hosted? Would it not be appropriate for an admin hosting that instance to make revenue to cover server costs? What would happen if I edited the source code to include ads? Is this just frowned upon or is there other issues?

Thank you!

**Comment by Nutomic** [comment]
You can put advertising on your site, though I am not sure how this will work with the AGPL license which requires all code changes to be published as open source. And the Fediverse has very few (if any) ad-based servers so it seems like an unpopular option. Its much more common to finance instances with donations.
