### ISSUE TITLE
Remove captchas

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2922]
I think its safe to say bots have pretty much beaten captchas, and they're not very useful for signups anymore. We might as well remove them. Registration applications and email verification are already in place anyway.

**Comment by Nutomic** [comment]
Sounds good, and saves me a bunch of work because I was moving the captcha storage from chatserver to db.

**Comment by dessalines** [comment]
Unfortunately captchas don't stop those signup bots either. We know from experience. They probably have no signup IP-rate limiting on their server, which is causing all the signups.

**Comment by lflare** [comment]
> Unfortunately captchas don't stop those signup bots either. We know from experience. They probably have no signup IP-rate limiting on their server, which is causing all the signups.

IP rate limits are naive at best. If someone has a simple captcha bypassing mechanism, do you really think they won't have proxies to bypass it? If anything, industry-standard captchas like recaptcha (or hcaptcha) will probably fare better than whatever cursed captcha solution (seriously, some of the words are completely illegible) is already implemented currently.

**Comment by maltfield** [comment]
See also this ticket to implement hashcash as a better alternative to CAPTCHAs.

 * https://github.com/LemmyNet/lemmy/issues/3204

Hash-cash is a cryptographically proven method to rate-limits by session, which cannot be bypassed like CAPTCHAs and is doesn't harm at-risk users of VPNs and Tor like IP rate limiting.

**Comment by alyazabirze** [comment]
> If anything, having both a good captcha solution, and email verification, will help to alleviate the spam issue at least a couple folds.

i'd like to second, at least, this. i don't _care_ for CAPTCHAs, and am perfectly fine with them being replaced by something better down the road, but as far as i can tell:

1. their impact (particularly when accompanied by additional measures such as email verification and an application to approve) is currently non-trivial and;
2. there are only four anti-spam measures currently in place total including CAPTCHA. the other three are email verification, closing registrations so every user has to apply, and defederation. for instances not like my own (Beehaw) where the standard for entry is intended to be less rigorous and open-to-all, that presents some really obvious future headaches.

with that in mind, unless i'm missing something--or until that "something better" i just described is implemented--i think removal is currently a *really* bad idea. it'll give us less options collectively to work with in a time where we need more.

**Comment by cloventt** [comment]
There is an open issue to bring back captcha: #3200 , I'd suggest posting feedback there rather than on this closed ticket.

**Comment by ForbodingAngel** [comment]
> I think its safe to say bots have pretty much beaten captchas, and they're not very useful for signups anymore. We might as well remove them. Registration applications and email verification are already in place anyway.

No offense, but this take is a bit braindead imo. Captcha aren't perfect, that is correct, but they do serve as a barrier.

Consider the swiss cheese approach to signup security where you have captcha as one layer, email verification as another, and signups as a third.

Individually, each one has holes, but if you put them together, each layer catches things that another misses. Is it perfect? No, but it's pretty damn good.

Don't let perfect be the enemy of good.

**Comment by dessalines** [comment]
Seconded, lets continue the discussion there.
