### ISSUE TITLE
No longer receiving `CreateComment` events on websocket when subscribed to community ID 0

### ISSUE THREAD

**Issue by Elara6331** [LemmyNet/lemmy#2923]
### Issue Summary

Subscribing to community ID 0 used to provide WebSocket messages for all events, including `CreateComment`. In 0.17.3, `CreateComment` events are no longer being sent. This means bots have to use polling to receive new comments, which is not ideal.

### Steps to Reproduce

1. Connect to Lemmy WebSocket
2. Log in
3. Subscribe to community ID 0 using `CommunityJoin`
4. Try to post a comment from a different account
5. No `CreateComment` is received

**Comment by Nutomic** [comment]
We are currently removing the websocket code so this wont get fixed. Instead switch to the HTTP API, its much more efficient. Later we might add limited websocket functionality back in, but only for a couple of client to server notifications.
