### ISSUE TITLE
Synchronise User Accounts Between Instances

### ISSUE THREAD

**Issue by TwentySeven28** [LemmyNet/lemmy#2931]
### Is your proposal related to a problem?

With the recent news from Reddit, more users are exploring Lemmy. This led to the owner of lemmy.ml asking users to subscribe to other instances (https://lemmy.ml/post/1147770?scrollToComments=true). To my astonishment, I discovered that doing so would result in multiple accounts, complete with all of the frustration associated with multiple accounts:

* I would need to re-subscribe to all of my communities. I would also need to re-block all of my blocked communities.
* I would need to track which account I used to comment in each location. To reply to users I would need to log into the relevant account on the relevant instance.
* Should an instance disappear, I would lose all of my comments, messages, and community subscriptions and blocks.

### Describe the solution you'd like

Synchronise user accounts between all federated instances, including login information, comments, messages, subscribed and blocked communities.

**Comment by Nutomic** [comment]
This would be much easier to solve with an export/import functionality for account data.

https://github.com/LemmyNet/lemmy/issues/506
