### ISSUE TITLE
Create a `hot_rank` column for the `post_aggregates` table, remove index rebuilds.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2932]
In short:

- Create a `hot_rank` column for the post_aggregates table.
- Calculate hot_rank in rust code, not in postgres.
- Add a periodic job to update that column, with the time decay function. Run it frequently, but only updating the last week of posts.
- Remove that postgres hot_rank function.
- Add indexes for that column.
- Cut out all the `rebuild index` jobs.

Context #2877

**Comment by johanndt** [comment]
Looks good. :-) And just to state the obvious, but get all the last week's posts in a single query, then calculate the hotrank for all of them in rust and update it in the db with a single UPDATE statement. Don't loop through them and issue an UPDATE for each post. That will be slow and tie up multiple db connections.
