### ISSUE TITLE
Support following accounts on other federated services (e.g. mastodon)

### ISSUE THREAD

**Issue by zacharylawrence** [LemmyNet/lemmy#2938]
### Is your proposal related to a problem?

I would like to use lemmy to access parts of the fediverse outside of lemmy. For example, following specific people on mastodon.

### Describe the solution you'd like

On my lemmy instance, I can search for a user on mastodon and follow them. This would appear like a community that I'm subscribed to and all responses on mastodon would appear like comments on lemmy.

### Describe alternatives you've considered

It's possible to use mastodon to follow lemmy communities, but I prefer using lemmy since most of the content I enjoy digesting is in the "link aggregator" / "comments" format.

### Additional context

I think it would be ideal if following accounts on other fediverse servers would appear like a community you could subscribe to on lemmy. Comments on mastodon could appear like nested comments on lemmy depending on the structure of who's replying to what comment.

**Comment by dessalines** [comment]
We had a user following issue, but I think it was wrongly closed by a commit.

Anyways this would take a LOT of work, and is very far in the future (we've got a lot on our plate as I'm sure you can tell), but I'm open to it at some point.

**Comment by Nutomic** [comment]
I dont think it makes any sense to implement this in Lemmy, when there are already so many platforms which support user following in different ways. Eg Mastodon, Kbin, Calckey and so on. Doesnt make much sense to repeat their work, we should focus on being a forum/link aggregator.
