### ISSUE TITLE
Impossible to get comment tree using lemmy_api_common without `full` feature

### ISSUE THREAD

**Issue by derivator** [LemmyNet/lemmy#2939]
The `path` field of the `Comment` struct [is gated behind `#[cfg(feature = "full")]`](https://github.com/LemmyNet/lemmy/blob/3565ad984a0270c7dd29051a9ff6d15fc5a8ed47/crates/db_schema/src/source/comment.rs#L36) because it uses `diesel_ltree::Ltree`, which seems to make it impossible to get the comment tree without using the `full` feature and pulling in all the dependencies. Perhaps it would be possible to just fall back to a string in this case?

Edit: My apologies on the label, didn't know Github would do that automatically.

**Comment by Nutomic** [comment]
You can probably add a line like this:
```rust
  #[cfg(not(feature = "full"))]
  pub path: String,
```
