### ISSUE TITLE
Personal saved posts are show on any users profile.

### ISSUE THREAD

**Issue by 7eter** [LemmyNet/lemmy#2942]
doesn't matter on whose profile I am on, I see my saved posts when I navigate to "saved".
![](https://github.com/LemmyNet/lemmy/assets/15588476/2ab061ba-94a6-462b-8bbc-3c9322b7cde9)
so basically `https://my.instance/u/ANYUSER/view/Saved/sort/New/page/1`
will show the profile of `ANYUSER` but with my saved posts.

That is not terrible but confusing.

**Comment by dessalines** [comment]
UI issue: https://github.com/LemmyNet/lemmy-ui/issues/1090
