### ISSUE TITLE
Allow admins to silence remote instance without blocking their users

### ISSUE THREAD

**Issue by finnim** [LemmyNet/lemmy#2943]
Especially for NSFW instances there's a strong use case in which an admin will want to federate with a remote nsfw instance but not have its posts show up in public timelines.

Users from the nsfw instance would still be allowed to post and send messages to the sfw instance without a problem. It's just that the content itself would not be visible unless a user is explicitly subscribed to a community from that nsfw instance.

**Comment by finnim** [comment]
Thank you for your quick reply,

My concern here is that once a user follows a remote community it will also appear in the "All" timeline to other users.

Let's say the remote instance is focused around something more fringe like furry porn, which I don't want to block for my users if they're subscribed to it but neither do I want it to appear in the All section to all users.

This would be similar to Mastodon's "limit federation" where posts from a limited instance don't appear in public timelines but appear to people who follow users from that instance. Posts from that instance are de-facto "follower only" posts.

**Comment by Nutomic** [comment]
There is also an endpoint to hide posts from a specific community from the frontpage (`/api/v3/community/hide`). Note that this isnt implemented in lemmy-ui yet.

https://github.com/LemmyNet/lemmy/issues/1980

**Comment by finnim** [comment]
> 



> There is also an endpoint to hide posts from a specific community from the frontpage (`/api/v3/community/hide`). Note that this isnt implemented in lemmy-ui yet.

Thank you! That looks like it would solve most issues.
In summary this is how I view it:

Admins should be able to shadow ban:
- All communities of an instance (lemmy.example/c/*)
- All NSFW subs of a whole instance (lemmy.example/c/*|nsfw)
- Individual subs of a whole instance (lemmy.example/c/IndividualCommunity)

(Between paretheses is a pseudo-syntax just for demonstration purposes of different levels of granularity)

Shadow banning makes communities and posts disappear from:
- The list of communities
- The All timeline

Users can still manually search for communities that are shadowbanned and subscribe to them and see them in "subscribed".
Users from the shadowbanned community can also still comment and create posts in the local instance since what is shadowbanned are the communities, not its users.

This would solve most conflicts or problems with having some instances with NSFW communities that aren't everyone's taste but without blocking their users.

**Comment by dessalines** [comment]
We don't have the concept of "shadowbanning", but you can already remove federated / remote communities.
