### ISSUE TITLE
database configuration abstraction is very leaky

### ISSUE THREAD

**Issue by CobaltCause** [LemmyNet/lemmy#2945]
https://github.com/LemmyNet/lemmy/blob/e97c30b930199ef35ff0cf9e04a3b3b6e6b239b3/crates/utils/src/settings/mod.rs#L45-L55

This doesn't handle the use of unix domain sockets properly, for example. It looks like converting everything into a connection URI is forced upon you by the database connection management crate being used by [this function signature](https://docs.rs/diesel-async/0.3.0/diesel_async/pooled_connection/struct.AsyncDieselConnectionManager.html). As such, it might be best/easiest to change

https://github.com/LemmyNet/lemmy/blob/e97c30b930199ef35ff0cf9e04a3b3b6e6b239b3/crates/utils/src/settings/structs.rs#L11

to `pub database: String` (which would then take a connection URI from the file without having to transform it) to reflect this, instead of trying to expose a structured interface but failing to handle the possible options.

I know the `LEMMY_DATABASE_URL` environment variable exists and can take a raw connection URI without transforming it, but I think the file configuration should be able to be just as powerful as the environment variable. Having to use the environment variable just to work around this issue feels pretty hacky.

**Comment by CobaltCause** [comment]
If the maintainers are interested in a change to address this issue, I'd be happy to try to contribute it.

**Comment by Nutomic** [comment]
Sure, contributions are always welcome.
