### ISSUE TITLE
Federating/Proxying links and media

### ISSUE THREAD

**Issue by 0xDEADCADE** [LemmyNet/lemmy#2947]
### Is your proposal related to a problem?

Somewhat, since I wouldn't classify it as a bug, but it is an issue I ran into. When a user shares a link to a post, comment, community, or shares media (such as an image hosted on their instance), that link is directly copied over. While using Lemmy, the client contacts a lot of other instances for media. Browsing linked posts or communities is often done by manually searching, as the link to the item is likely linking to another instance.

### Describe the solution you'd like

Converting links to posts, comments, communities, or media from other instances to one directly handled by the instance that's displaying it. For posts, comments, and communities it should retrieve the item from the other instance similar to if it was searched for, then display it on the local instance. For media, it should either download media similar to what happens when trying to view Mastodon posts from Lemmy, or proxy it to the other server directly (maybe with caching).

This ensures the client does not contact other instances "at random", which prevents correlation of which accounts belong to which clients and their IP addresses. It would be more similar to Matrix approach, where a client can access any local or federated content only by connecting directly to their chosen homeserver.

Converting links locally would retain compatibility with other Fediverse projects, unlike the alternative below.

### Describe alternatives you've considered

A system similar to `matrix.to` or `mxc` URIs could be used, but it would need to be adopted across multiple instances for it to function, and other Fediverse projects would no longer be able to interact easily with Lemmy posts. It would also have the downside of requiring more features to be implemented on each client for proper use, breaking compatibility with existing clients.

For links to posts, comments, or communities, there isn't much of an advantage to using something similar to `matrix.to`, as the link to an item could simply be detected and converted locally. For media, there would be an opportunity to decentralize more, and save bandwidth, by caching media on each server, and by optionally specifying a protocol. A "lemmy content" URI could look similar to this: `lmc://direct/lemmy.ml/MEDIA-ID`, where the only difference to Matrix `MXC`s is the `direct` "protocol" specifier. This could be used to link directly to other media sites, such as imgur: `lmc://imgur/lemmy.ml/IMGUR-ID`. Keeping the originating instance included means that instances not capable of handling the `imgur` "protocol" could simply proxy the media request similar to `direct` "protocol" media.

This would require a lot of extra work and effort, wouldn't be compatible with instances not running the newer version, or other Fediverse projects. It would probably be preferred to detect and convert links on each instance separately.

### Additional context

As a frequent Matrix user, I found it quite surprising that Lemmy is so quick to load media from other servers. Both the web UI and Jerboa don't even show a warning, prompt or anything before loading images, profile pictures, and other media directly from an instance that you're not logged in on. This is a concern for privacy, as any instance that federates with the instance you're using has essentially as much info about your client as the instance you're logged in on. It also heavily impacts the general browsing experience being linked to a post, and not being able to open it in your preferred instance (where you're likely already logged in). It could also have impact on users in countries where a lot of censorship or blocking of URLs or domains occurs, as they would not be able to view most linked posts, unless those links are locally converted to an instance that isn't blocked in their country.

**Comment by Nutomic** [comment]
This could be implemented with the `GET /image/download?url={url}` endpoint in [pict-rs](https://git.asonix.dog/asonix/pict-rs/). However it would probably require some changes so that images are not reencoded in that case, and also deleted after some time (or if the cache gets too big).

In any case, contributions welcome!

**Comment by 0xDEADCADE** [comment]
That would be the media part of it, yes. The user experience of browsing around different communities and posts would be a more difficult change, but still important to not confuse users by sending them to other instances.

**Comment by dessalines** [comment]
Agreed, having an image proxying service would be nice to have.

**Comment by poVoq** [comment]
I am actually quite confused by this. I always thought proxying of media is not implemented by Lemmy (other than some small thumbnail previews), but it turns out that very inconsistently it does already proxy images.

Take this post for example: https://slrpnk.net/post/433623

This is a post by a remote user, in a remote community, yet the image is clearly served from my domain.

While I understand that there are certain scaling advantages to this, it would be very much preferrable to be able to turn this media-proxy off or at least have an allow-list for it, as smaller instances might not be able to afford the storage space and bandwidth needed for it. In addition there is the legal consideration to not replicate images on your server due to copyright and other problems such as CSAM.

**Comment by RocketDerp** [comment]
> Take this post for example: https://slrpnk.net/post/433623
> 
> This is a post by a remote user, in a remote community, yet the image is clearly served from my domain.

When I view your community posting list, https://slrpnk.net/c/imageai@sh.itjust.works - the thumbnail is served from the originating site - not from slrpnk.net or imgurl.  the URL is: https://sh.itjust.works/pictrs/image/0441bb00-4ac3-403e-b5ca-f4361e8f4ed4.jpeg?format=webp&thumbnail=256

**Comment by poVoq** [comment]
I also recently observed that while the home instance does proxy images from places like imgur for local users, it seems to send the original URL via federation to other servers, which in turn try to load it directly from Imgur.

I also noted that the behaviour I described in a post further up, changed after updating to a later version Lemmy.

**Comment by cperrin88** [comment]
A very simple first step we could take is to allow setting a media proxy url. If that is set this url is prepended to the media url. This way it would be easy to create a pull through proxy for images with nginx or whatever.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/4035
