### ISSUE TITLE
404: couldnt_find_community

### ISSUE THREAD

**Issue by stephen-hill** [LemmyNet/lemmy#2953]
Unable to access remote communities.

- https://lemmy.ml/c/formuladank Works
- https://lemmy.one/c/formuladank@lemmy.ml Returns 404

**Comment by Klobenda** [comment]
Note: works if the instance you're on has at least 1 user subscribed to the target community

**Comment by stephen-hill** [comment]
@Klobenda So, how does a user become subscribed in the first place?

**Comment by Klobenda** [comment]
> @Klobenda So, how does a user become subscribed in the first place?

They have to search for the community in the standard format, twice (once to trigger federation, once to display it), in the current instance's search system.

I've written up a couple idea/solution tickets around the "discovery"/subscription UX problem: https://github.com/LemmyNet/lemmy-ui/issues/1106 https://github.com/LemmyNet/lemmy/issues/2951

**Comment by stephen-hill** [comment]
@Klobenda 

No results

- https://sopuli.xyz/search/q/!formuladank%40lemmy.ml/type/All/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1
- https://sopuli.xyz/search/q/formuladank%40lemmy.ml/type/All/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1

What is the correct way to do this? What is the "standard format"?

**Comment by Klobenda** [comment]
> @Klobenda
> 
> No results
> 
> * https://sopuli.xyz/search/q/!formuladank%40lemmy.ml/type/All/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1
> * https://sopuli.xyz/search/q/formuladank%40lemmy.ml/type/All/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1
> 
> What is the correct way to do this? What is the "standard format"?

`!communityname@instance.domain` it looks like.

After a few attempts I was able to get a private instance to see it: 
<img width="425" alt="image" src="https://github.com/LemmyNet/lemmy/assets/135837933/73fb9df9-8b1f-4257-984a-7788af8071c9">

**Comment by dessalines** [comment]
https://lemmy.one/c/formuladank@lemmy.ml seems fixed now.

Yes sometimes resolveResponse / search doesn't always work on the first try, that's our bad.
