### ISSUE TITLE
Error when creating a user with a non-unique name.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#2955]
This happens with any error, not just with email verification.  

For example here's the log if I try to sign up when registration is closed
```
2023-06-07T18:03:35.070511Z ERROR HTTP request{http.method=GET http.scheme="https" http.host=lemmy.pe1uca.dev http.target=/api/v3/ws otel.kind="server" request_id=bd92d4fa-90e5-4d03-b2e3-8a1c39b645fa http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: registration_closed: registration_closed
```

Here's when a duplicate user exists
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'couldnt create local user: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"local_user_person_id_key\"")', crates/db_schema/src/impls/local_user.rs:157:8
```

All of them don't send a response to the UI.  
It can be easily verified in the network tab of the browser watching the websocket interaction, it sends the operation `Register` and the server never gets back.

_Originally posted by @pe1uca in https://github.com/LemmyNet/lemmy-ui/issues/1062#issuecomment-1581293967_

**Comment by RocketDerp** [comment]
I find the webapp UI also hangs if you try to create a Community of the same name as one that already exists on the instance.

**Comment by Nutomic** [comment]
User registration is handled [here](https://github.com/LemmyNet/lemmy/blob/main/crates/api_crud/src/user/create.rs#L102). There is an attempt to check for duplicate usernames but apparently its not working correctly. You can setup a dev environment and test how to get it working properly.

**Comment by th3raid0r** [comment]
What version do I need to roll back to, to get this working? v0.17.2? 

There are a LOT of reddit communities looking to switch over right now, and this is a COMPLETE AND  TOTAL showstopper of a bug.

**Comment by RocketDerp** [comment]
See also: https://github.com/LemmyNet/lemmy-ui/issues/1151

**Comment by th3raid0r** [comment]
I noticed that my particular issue was half pebkac and half bug. 

My issue - SMTP misconfiguration on TLS (needed to be starttls instead of just tls for Protonmail)

When this type of misconfiguration occurs, it appears that it's creating stub user that isn't rolled back after failure. So when the issue is resolved, any further attempts to create the user run into constraint issues since the user is half created. 

So I think the bug here is that user creation needs to roll back on SMTP issues when email verification is enabled.

**Comment by AndydeCleyre** [comment]
I've been trying to sign up to various instances, and always get the infinite hanging. I think it's this issue. For now, is there a quick and dirty way to check if a username is available, to help with the sign up process?

**Comment by dev0T** [comment]
Hi! I've been attempting to register the past few days and I also get stick in the loading state forever. I tried multiple usernames but no feedback on what's going on whatsoever.
