### ISSUE TITLE
coordination across the fediverse

### ISSUE THREAD

**Issue by SignalProcessingJobs** [LemmyNet/lemmy#2958]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

Per [this discussion](https://news.ycombinator.com/item?id=36215914) it would really be nice to "merge" all fediverses so its very simple from a user perspective. 

> If there is to be any success for Lemmy in the wake of Reddit shooting itself in the foot, it needs to make the federation part completely invisible and transparent, unless someone intentionally seeks it out. join-lemmy.org makes me choose from a list of servers before I can sign up (https://join-lemmy.org/instances). Without having a really solid understanding of how and why I need to choose a server, I'd be surprised if the conversion rate is higher than 5%.

### Describe the solution you'd like

make the federation part completely invisible and transparent, unless someone intentionally seeks it out. 

### Describe alternatives you've considered

None

**Comment by Nutomic** [comment]
Centralization is not the solution, it would create another central point of failure. Users need to understand how the platform works. I dont think its really so difficult, after all they can also use email. Just needs better docs and ux.
