### ISSUE TITLE
Implement community wiki

### ISSUE THREAD

**Issue by Huy-Ngo** [LemmyNet/lemmy#2959]
### Is your proposal related to a problem?

One of the useful features Reddit has is subreddit's wiki, in which mods can write pages on 

### Describe the solution you'd like

Communities can have a wiki that should be federated well at least among Lemmy instances.

### Describe alternatives you've considered

Currently some communities use external documents, such as google docs, which is not ideal.

### Additional context

None

**Comment by Nutomic** [comment]
A federated wiki would be a major project on its own. I dont think it would make sense to integrate this in Lemmy.

**Comment by aerkiaga** [comment]
@Huy-Ngo as a workaround, I suggest that you make one or more locked text posts in your community with all the desired content and link them to each other, plus a link in the sidebar. This offers the same capabilities as a Reddit-style wiki (Markdown, editing, multiple pages), except for edit permissions (and maybe discoverability/UX?).

**Comment by dessalines** [comment]
The sidebar is also editable by and mod. Not a wiki, but still can be collaborative.

**Comment by Huy-Ngo** [comment]
Putting too much information into the sidebar would be counter-productive IMO, but the text-post workaround sounds good enough.

**Comment by Oneechan69** [comment]
@aerkiaga A community wiki wouldn't need to be federated or mirrored, it could work just like Reddit wikis, to have wiki pages with comprehensive information and guides / tutorials about thbe community's topic.

@dessalines You should reconsider this.
