### ISSUE TITLE
Federation issues when trying to access a community hosted on another instance

### ISSUE THREAD

**Issue by mxmvncnt** [LemmyNet/lemmy#2964]
Hi there, not sure where this issue belongs here on in lemmy-ui. The error code leads me to think this belongs here so let me know if does not belong.

### Issue Summary

Some communities cannot be accessed from a remote instance. Take for example the !androidbeta@lemmy.ml community. It can be accessed from Lemmy.ml, but there is no way that I found using the front-end to access it from another instance (I have tried Lemmy.ca). I also get the following error on screen: 

![image](https://github.com/LemmyNet/lemmy/assets/43153657/eb131c76-aba9-4e62-b175-36cfb2738ea9)
(image says: `404: couldnt_find_community`)

I have also attempted to access the community from other servers such as beehaw.org, but I get the same result. The weird thing is some instances do work like they should, but some don't (lemmy.ml/c/android works)

### Steps to Reproduce

1. Go to an instance
2. Try to access a remote instance (lemmy.ml/c/androidbeta is confirmed not working at the moment)
3. Get the 404 error message 

### Technical details

- Websocket connection error, automatically retries and then works successfully
- Tried on Firefox 113.0.1 and GNOME Web 44.3
- All tested instances run version 0.17.3 both on front-end and on the back-end
- I have also checked the Network tab in the developer tools, and nothing 
- There seems to be some sort of data exchange, but all the data is empty (check image, you can see I tried opening 3 of the objects but they are all empty)
![image](https://github.com/LemmyNet/lemmy/assets/43153657/4d05f8bb-b827-4d9d-97fc-e1ee2e782e59)
(this image is trying to access https://lemmy.ca/c/androidbeta@lemmy.ml)

**Comment by Nutomic** [comment]
Are you logged in on lemmy.ca? Otherwise you are not able to fetch new remote communities. You also might have to fetch it through the search first (again with login) before being able to access the community page.

**Comment by mxmvncnt** [comment]
Yes, I am fully logged in to my account, but it is pretty new, does the account age usually affect this sort of things?

Also while logged in: search gave me no results. The only thing that came up when searching for "androidbeta" was the mention of the community by a crosspost from /c/androidbeta to /c/android. When filtering for communities only, the search is empty.

**Comment by dessalines** [comment]
Search for either `!androidbeta@lemmy.ml` , or `https://lemmy.ml/c/androidbeta` from your search bar.

I was able to subscribe to it from lemmygrad: https://lemmygrad.ml/c/androidbeta@lemmy.ml

**Comment by mxmvncnt** [comment]
That solves the issue, thanks! But is this intentional/desired behaviour? It seems to me like it would prevent new users like me from discovering communities from other instances since they just would not see them.

**Comment by dessalines** [comment]
It is, because instances don't do any crawling or "automatic" connections to communities they don't know about. Some explicit connection is required (a subscribe), and then at that point your activitypub ID can be added to that community's follower list, and updates pushed to the relevant instances.

**Comment by Atemu** [comment]
Could a query for `/c/unkown_community@other.instance` not trigger a connection?

From a UX perspective, doing that synchronously (with reasonable timeout) could even be advantageous. For the user, it'd just take unusually long to load (not too unusual tbh) which is leagues ahead of a 404.

Also, why do you need to search for `!unkown_community@other.instance` (with the `!`)? I just ran into this case and tried searching for just `unkown_community@other.instance` (no `!`) but that did not trigger any connection.
