### ISSUE TITLE
Provide a Helm chart to easily deploy Lemmy in a Kubernetes cluster

### ISSUE THREAD

**Issue by Djiit** [LemmyNet/lemmy#2969]
### Is your proposal related to a problem?

Nope -- or just being able to install it on kubernetes-managed resources in an "official" way

### Describe the solution you'd like

An official and/or community-supported Helm file that people could use to deploy Lemmy on Kubernetes.

### Describe alternatives you've considered

Writing my own or using plain kubernetes objects to deploy it.

Cheers

**Comment by Nutomic** [comment]
We maintainers dont know Kubernetes so you have to write it yourself. I suggest making a blog post (or post it on Lemmy), then make a PR to link it from the docs.

**Comment by JustinLex** [comment]
I'm in the process of setting up Lemmy on my cluster. I'll share manifests when I'm done, and put together a helm chart/ cdk8s chart.

**Comment by usmcamp0811** [comment]
ha.. so I'm not alone here.. nice..

**Comment by JustinLex** [comment]
These are still a bit messy and not very portable, but here is a working example of Lemmy running in Kubernetes from my cluster: [https://github.com/JustinLex/jlh-h5b/tree/main/applications/lemmy](https://github.com/JustinLex/jlh-h5b/tree/main/applications/lemmy)

These manifests assume that you have an Ingress installed, cert-manager set up with a ClusterIsssuer for generating certs, Crunchy Postgres operator installed for creating Postgres databases, and that you are using the onepassword operator to download the lemmy-hjson and pictrs secrets from 1password.

**Comment by Just-Insane** [comment]
I'd also be interested in this, I've got Lemmy running in my cluster with these charts, but it probably won't work for anyone else.

https://github.com/Just-Insane/lemmy_help

Note that I've actually replaced the postgres chart in the repo with a bitnami one because I was having issues using nfs storage.

**Comment by ananace** [comment]
I've ended up writing a Lemmy chart as well, running a pair of test instances and one production one on it.

https://gitlab.com/ananace/charts/-/tree/master/charts/lemmy - no readme or anything like that yet, I want to make sure that the chart has enough logic in it to know when it's trying to deploy a broken setup.

**Comment by Just-Insane** [comment]
> I've ended up writing a Lemmy chart as well, running a pair of test instances and one production one on it.
> 
> [gitlab.com/ananace/charts/-/tree/master/charts/lemmy](https://gitlab.com/ananace/charts/-/tree/master/charts/lemmy) - no readme or anything like that yet, I want to make sure that the chart has enough logic in it to know when it's trying to deploy a broken setup.

It looks pretty good to me, going to test it out.

**Comment by anthr76** [comment]
https://github.com/anthr76/lemmy-ks

I have a Kustomization deployment set here that anyone is free to use or contribute with. The issues show what I have planned before I consider it ready for "the average user"

**Comment by arifwn** [comment]
Has anyone tried to scale up their Lemmy deployment in kubernetes? I can't seem to scale up `pictrs` pods due to `pictrs` using a filesystem-based database (sled). `pictrs` would crash if its database lockfile is already opened by another pod.

**Comment by ananace** [comment]
I'm running Lemmy with multiple pods for both the backend and frontend deployment, but pict-rs is indeed limited to only one active connection to the sled database. And since sled saw it's latest commit on october last year that's likely to not improve any time soon.

**Comment by dessalines** [comment]
I can re-open should anyone take this on, but it seems like this should live in lemmy-docs, as lemmy doesn't require or rely on kubernetes in any way.
