### ISSUE TITLE
Is it possible that Lemmy makes the format of "note" type messages fully readable by users of microblogging platforms, as Kbin is able to do today?

### ISSUE THREAD

**Issue by informapirata** [LemmyNet/lemmy#2972]
Good morning everyone.
I love Lemmy, but one of the aspects that has often frustrated me is that Lemmy "note" messages are not fully readable by users of microblogging platforms. I also had this frustration with Friendica which is undoubtedly my favorite Fediverse platform. I've always thought this was a problem with Mastodon and its clones. But I saw that this problem could be fixed.

I'm exploring the features of Kbin, another link aggregator like Lemmy, but which also has social features (for example kbin users can follow other users), and I noticed an interesting feature that, in my opinion, could be taken from Lemmy.

As you can see from the page https://feddit.it/c/test I sent three posts:
1) from Kbin ( https://kbin.social/m/test@feddit.it/t/6559 )
2) from Lemmy ( https://feddit.it/post/288614 )
3) from Friendica ( https://poliverso.org/objects/0477a01e-1164-81fa-93a2-c5b390871156 )

In all three cases, the messages were correctly interpreted by the feddit.it test community

1) from Kbin ( https://feddit.it/post/288613 )
2) from Lemmy ( https://feddit.it/post/288614 )
3) from Friendica ( https://poliverso.org/objects/0477a01e-1164-81fa-93a2-c5b390871156 )

The only difference is, viewing those posts from Mastodon there are differences:
_NB: I apologize but these links are broken: to see the links on Mastodon or on other social networks, you need to paste them into the search box of the social network in question_
~~1) from Kbin (https://mastodon.social/@informapirata@kbin.social/110509398536728330)~~
~~2) from Lemmy (https://mastodon.social/@informapirata@feddit.it/110509412013779138)~~
~~3) from Friendica ( https://mastodon.social/@informapirata@poliverso.org/110509417535544497 )~~

In fact, while with Friendica and Lemmy, the Mastodon user only sees the title/subject of the "note" type message + the link to the post, in the case of Kbin, the user is able to read all three characteristics that distinguish the message of a link aggregator: the title/subject of the "note" type message + the body of the message text + the published link.

Kbin therefore proves to be a very interesting compatibility and readability towards microblogging systems such as the widespread Mastodon.

I wonder if it's not appropriate to think about the possibility of making Lemmy's writing format equally compatible with what is currently the largest audience of the Fediverse, namely that of Mastodon.

PS: I sent [a similar issue to the Friendica](https://github.com/friendica/friendica/issues/13206) developers, so don't be surprised if you see almost the same words

![View from Lemmy](https://github.com/LemmyNet/lemmy/assets/99956935/7147df27-1239-4be1-9cd6-a1b7216151a8)
![View from Mastodon](https://github.com/LemmyNet/lemmy/assets/99956935/5a64ae56-9cfc-4a4f-b45a-89c12ab3f984)
![View from Friendica](https://github.com/LemmyNet/lemmy/assets/99956935/1b70c0f2-6f12-4b64-b2e8-33cf24990686)

**Comment by Nutomic** [comment]
> The only difference is, viewing those posts from Mastodon there are differences:
> 
> 1. from Kbin (https://mastodon.social/@informapirata@kbin.social/110509398536728330)
> 2. from Lemmy (https://mastodon.social/@informapirata@feddit.it/110509412013779138)
> 3. from Friendica ( https://mastodon.social/@informapirata@poliverso.org/110509417535544497 )

These links dont work because they all redirect away from mastodon.social. Anyway this sounds like an issue with Mastodon rendering federated content wrong, you should report it there.

**Comment by informapirata** [comment]
> If Mastodon displays something wrong, why do you think that the problem is Lemmy? And you indicated that both Friendica and Lemmy send it in the same way, which also points to a problem with Mastodon.

I didn't say it's wrong, but since the solution adopted by Kbin makes the message readable both by Mastodon and by other microblogging platforms, it could be useful to understand what is the trick used by Kbin to make its posts more readable

**Comment by db0** [comment]
Just so I understand, the reason why a post [like this](https://hachyderm.io/@db0@lemmy.dbzer0.com/110554021781896909) Is not displaying the [embedded image in the URL field](https://lemmy.dbzer0.com/post/29149), is because mastodon is not respecting the activity pub protocol properly? I.e. this should be an issue on the mastodon tracker?

**Comment by db0** [comment]
https://github.com/LemmyNet/lemmy/issues/2611 is the other way around, about images in mastodon appearing in lemmy properly. Basically the interaction is broken both ways :D

**Comment by Nutomic** [comment]
This is a problem in Mastodon which needs to be fixed on their side, [described here](https://fediversity.site/display/?mid=https://fediversity.site/item/7ac903a0-efcf-46ee-a818-bab85c01240f). The only possible solution from us would be to federate posts as `Note` which doesnt make any sense.
