### ISSUE TITLE
Invite links for registration

### ISSUE THREAD

**Issue by TomatDividedBy0** [LemmyNet/lemmy#2973]
A serious issue we're going to be dealing with in the coming months with this recent Reddit exodus is that a ton of users are coming in and getting discouraged at the manual approval process. Obviously, this process is in place to keep out the volumetric ton of spam accounts that are created on the Fediverse. I'm already seeing a lot of people giving up the same way they gave up on Mastodon with the registration issue

My suggestion to mitigate this problem is to add invite links. Existing Lemmy users should be able to give out invite links to their instance, whereby one can bypass the manual registration process. Given that Lemmy is spreading by word-of-mouth, why not have word-of-mouth also do the vetting and spread the invites to legitimate human beings.

Have a log of who invites who for accountability, and if volume is really that much of an issue, maybe have a weekly quota of invites or something for each user. By doing this, we're keeping out spam much more than open registration, while also expediting the process for a ton of people.

**Comment by dessalines** [comment]
We don't have time to work on a separate, email-based onboarding system, but someone else is free to if they wish.

**Comment by TomatDividedBy0** [comment]
> We don't have time to work on a separate, email-based onboarding system, but someone else is free to if they wish.

Just to confirm, if someone else were to work on it, you'd have no issue with the concept itself being implemented?

**Comment by dessalines** [comment]
I would not be opposed. It would be quite a large undertaking though.
