### ISSUE TITLE
API Caching

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#2975]
This is probably too big of an undertaking to get done before the flood of redditors, but using something like redis to cache API requests could help keep things snappy and reduce strain on the postgres database. It seems like a good to have for some point in the future.

**Comment by Nutomic** [comment]
I dont think it makes much sense to do caching inside Lemmy, as it would require various config options. Its better to send the right cache-control headers, so that admins can configure caching in nginx according to their specific requirements.
