### ISSUE TITLE
Allow all admins to purge content

### ISSUE THREAD

**Issue by gaywallet** [LemmyNet/lemmy#2976]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

Someone posted CSAM on another instance last night and we had to wait for the top admin to purge content. To minimize burden on all admins a site should be allowed to set it up so any admin can purge content. 

### Describe the solution you'd like

Checkbox, something to set, whatever solution allows an instance to let all admins to purge content

### Describe alternatives you've considered

No alternative available

### Additional context

This really needs to be added ASAP with new user growth correlating with an influx of trolls

**Comment by Nutomic** [comment]
Need to change the check in file below and in other files next to it. Looks like the frontend already shows purge options to all admins so there is no change needed.

https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/site/purge/comment.rs#L27

**Comment by dessalines** [comment]
I want to stress that its incredibly dangerous to add this. 

Anyone you appoint as an admin, can potentially wipe out entire communities, users, and *years* of content, none of it being resurrectable in any way (unless you were doing backups, and even then, very difficult to restore).

**Comment by gaywallet** [comment]
Then make it a per-admin setting with an additional pop-up to confirm the setting with a message that informs them of this risk. 

For those of us that have decided we are okay with the risk (making regular backups and trusting the admin team), being able to purge CSAM content without requiring more people to observe said content in order to purge it is extremely desirable.

**Comment by Nutomic** [comment]
> Anyone you appoint as an admin, can potentially wipe out entire communities, users, and years of content, none of it being resurrectable in any way (unless you were doing backups, and even then, very difficult to restore).

That would be very easy to notice, so at that point you would restore a full db backup and remove the offending admin. Anyway we are not responsible for what people to with Lemmy. Sometimes its just necessary to act fast, and waiting for a single person to come back online is not a good option.

**Comment by dessalines** [comment]
Shouldn't be too difficult to add, but everything needs to come after this http rework, with v0.18. I'm going on strike w/ respect to more cherry-picking to `v0.17` 😆

**Comment by krestenlaust** [comment]
Isn't there a way for admins to suspend content, and just leave it for the top admin later?

**Comment by 0xpr03** [comment]
Also supporting a suspend option, if you really need it fast, add an option to disable accessing the content

**Comment by TKilFree** [comment]
this should be resolved by: https://github.com/LemmyNet/lemmy/pull/3271

**Comment by krestenlaust** [comment]
Has the talk about security also been resolved? Is it possible to restore purged content?

**Comment by Nutomic** [comment]
Purge means that the affected content is permanently gone, so it cant be restored.
