### ISSUE TITLE
`tests::test_should_not_validate_user_token_after_password_change` is flaky

### ISSUE THREAD

**Issue by CobaltCause** [LemmyNet/lemmy#2981]
With a fresh database after running migrations, running the following command from the repo root repeatedly will yield different results. Sometimes it passes, sometimes it fails. Usually the latter.

```
$ LEMMY_CONFIG_LOCATION=../../config/config.hjson LEMMY_DATABASE_URL=postgresql://lemmy:password@localhost/lemmy cargo test -p lemmy_api --lib --no-fail-fast
```

**Comment by dessalines** [comment]
Make sure you use the `scripts/test.sh`, which helps clear out the DB and runs things in their correct order. Without that, test failures might leave residual content which breaks other tests.

**Comment by CobaltCause** [comment]
Here're the steps I'm doing, all in the repo root at https://github.com/LemmyNet/lemmy/pull/3002/commits/072e7444a4aa430ab241393898d12c5241e0b639 with a clean working tree:

1. `sudo rm -r docker/volumes` to wipe the database state
2. `(cd docker; docker compose up postgres -d)` to start postgres
3. `DATABASE_URL=postgresql://lemmy:password@localhost:5433/lemmy diesel migration run`
4. `LEMMY_CONFIG_LOCATION=../../config/config.hjson LEMMY_DATABASE_URL=postgresql://lemmy:password@localhost:5433/lemmy cargo test -p lemmy_api --lib --no-fail-fast` repeatedly until it fails
 
Just now I got 4 successful runs, then 1 failure, then 2 successful runs, then 1 failure, then 3 successful runs, then 1 failure, then 1 successful run. The failure output is always

```
---- tests::test_should_not_validate_user_token_after_password_change stdout ----
thread 'tests::test_should_not_validate_user_token_after_password_change' panicked at 'assertion failed: check_after.is_err()', crates/api/src/lib.rs:95:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I'm reading you correctly, this is expected and the database needs to be fully reset before re-running the tests? If so, it's probably safe to close this since I just wasn't doing that.

**Comment by RocketDerp** [comment]
I ran scripts/test.sh and that was the only test to fail test_should_not_validate_user_token_after_password_change
