### ISSUE TITLE
Featured posts don't appear on instances other that its 'home' instance

### ISSUE THREAD

**Issue by kittle-over-the-middle** [LemmyNet/lemmy#2984]
### Issue Summary

Some posts can't even be seen while on different instances. For example, I'm logged on my account in lemmy.fmhy.ml. There is a post on lemmy.ml/c/piracy (https://lemmy.ml/post/426993). I'm not logged in to that instance, I'm looking at it as a guest. But when I go to my hope, browse to /c/piracy and try to see the post, it doesn't even exists there. Then I tried to copy the post number (426993) and paste it after lemmy.fmhy.ml/post/, but I receive:

`404: couldnt_find_post`

The same happens with this post https://lemmy.one/post/1600. I can't see it from lemmy.fmhy.ml. 

Looks to be an issue with featured posts.

### Steps to Reproduce

1. Login to your instance and have another tab as a guest on any other featured post in any other instance
2. Copy post code number
3. Paste it to your instance post URL

Happens on Desktop with the previous steps. But Jerboa also is unable to show these posts if I navigate to the target community home and try to find it there.

**Comment by derivator** [comment]
Post is here: https://lemmy.fmhy.ml/post/90 but not pinned.

**Comment by Nutomic** [comment]
It shows as pinned for me. If you want to fetch a remote post which doesnt exist on your instance yet, you can paste the post url in the search field (eg https://lemmy.ml/post/426993).

**Comment by kittle-over-the-middle** [comment]
Okay, both of the posts I mentioned appear after I paste the post URL in the search field and I'm able to find them this way. Thanks.

Still, they don't appear as pinned and appear to not show the correct number of upvotes. One of the communities doesn't appear to even show any upvotes at all in my instance.

![image](https://github.com/LemmyNet/lemmy/assets/61358845/3f16acfa-dd05-4640-9e06-4b18b7691992)
![image](https://github.com/LemmyNet/lemmy/assets/61358845/d8cd8105-a5a3-48c7-87d1-c36c40021963)
![image](https://github.com/LemmyNet/lemmy/assets/61358845/f96e12ed-1cfd-4af8-a62a-113367a45e5d)
![image](https://github.com/LemmyNet/lemmy/assets/61358845/4211aabd-cd93-4dbd-9dd9-2535208d8f11)
![image](https://github.com/LemmyNet/lemmy/assets/61358845/cd1fa82c-699c-48a2-8aa9-a75e6aaed60b)

**Comment by Nutomic** [comment]
Federation doesnt currently fetch historic data/actions. You will receive those things over time after following.

It looks like there is actually a bug with federating featured items, will make a fix for that.
