### ISSUE TITLE
I WANT A FAVICON - said karen

### ISSUE THREAD

**Issue by Fimeg** [LemmyNet/lemmy#2999]
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by boehs** [comment]
Excuse me?
