### ISSUE TITLE
Local development install error when running cargo check

### ISSUE THREAD

**Issue by mitchellss** [LemmyNet/lemmy#3000]
### Issue Summary

Attempting to install Lemmy for local development. While running `cargo check`, I encountered this error. I have attempted installing on both WSL and native Ubuntu and get the same identical error.

### Steps to Reproduce

1. Run `cargo check` from the lemmy directory

### Technical details

```
error: failed to run custom build command for `lemmy_utils v0.17.1 (/home/stephen/dev/lemmy/crates/utils)`

Caused by:
  process didn't exit successfully: `/home/stephen/dev/lemmy/target/debug/build/lemmy_utils-c5e1e9f2e82627ad/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=translations/email/en.json
  cargo:rerun-if-changed=translations/email/pt.json
  cargo:rerun-if-changed=translations/email/fi.json
  cargo:rerun-if-changed=translations/email/ko.json

  --- stderr
  Error: Fmt(Os { code: 2, kind: NotFound, message: "No such file or directory" })
warning: build failed, waiting for other jobs to finish...
```

Similar error to #2967

**Comment by ivanjermakov** [comment]
Have you cloned the repo with `--recursive` flag?

**Comment by mitchellss** [comment]
Yes

**Comment by fheft** [comment]
Same problem for me, freshly cloned with the `--recursive` flag.

**Comment by Crayolable** [comment]
I'd been experiencing this issue too with WSL, even after verifying Rust was upgraded.
After removing Rust and then [installing rustup](https://www.rust-lang.org/tools/install), I could build without error.

**Comment by fheft** [comment]
Thanks @Crayolable, on my Ubuntu installation removing Rust as it was installed by `apt` and replacing it with the latest version from rustup fixed the issue.

So... my bad, as the [docs](https://join-lemmy.org/docs/en/contributors/02-local-development.html#install-build-requirements) mention that you should install Rust using rustup.
