### ISSUE TITLE
Lemmy federation broken on new deployment

### ISSUE THREAD

**Issue by lucyrose39** [LemmyNet/lemmy#3001]
A summary of the bug.
Lemmy federation is broken on install using ansible. error listed below
### Steps to Reproduce
install lemmy using ansible, attempt to search any federated instance
1. (for example) I clicked login, and an endless spinner show up.
2. I tried to install lemmy via this guide, and I'm getting this error.
3. ...

### Technical details
Debian 11 server

[lemmy-log.txt](https://github.com/LemmyNet/lemmy/files/11708807/lemmy-log.txt)

**Comment by lucyrose39** [comment]
It's worth noting it claims it isn't in the allowlist, yet neither field is populated.
![feddit](https://github.com/LemmyNet/lemmy/assets/42224091/2beaf059-a4e3-489d-95c6-836c66746850)

**Comment by Nutomic** [comment]
Use https://lemmy.ml/c/lemmy_support for support.
