### ISSUE TITLE
Lemmy cannot bind to an ipv6 address

### ISSUE THREAD

**Issue by Veraticus** [LemmyNet/lemmy#3013]
- [ x ] Did you check to see if this issue already exists?
- [ x ] Is this only a single bug? Do not put multiple bugs in one issue.
- [ x ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support .
- [ x ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Issue Summary

Lemmy cannot bind to an ipv6 address. Attempts to do so cause the app to fail with:

```
thread 'main' panicked at 'Failed to load settings file: LemmyError { message: None, inner: "invalid IP address syntax" near 3:24, context: "SpanTrace" }', crates/utils/src/settings/mod.rs:18:33
```

### Steps to Reproduce

1. Set any ipv6 address (for example, `::/0`) as `bind` in `config.hjson`

**Comment by frebib** [comment]
```
frebib@Poseidon C:\s\social> grep bind lemmy.hjson
  bind: "::"
```
or
```
frebib@Poseidon C:\s\social> grep bind lemmy.hjson
  bind: "2a02:<snip>:9::15"
```
```
frebib@frebib-PC ~> curl -v 'http://[2a02:<snip>:9::15]:8536'
*   Trying [2a02:<snip>:9::15]:8536...
* Connected to 2a02:<snip>:9::15 (2a02:<snip>:9::15) port 8536 (#0)
> GET / HTTP/1.1
> Host: [2a02:<snip>:9::15]:8536
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 200 OK
< content-length: 1471
< content-type: application/activity+json
< date: Sun, 11 Jun 2023 10:11:27 GMT
<
{"@context":["https://www.w3.org/ns/activitystreams", ...
```

Works for me with both `::` and a specific address. Try to drop the netmask

**Comment by Veraticus** [comment]
You're right, my mistake!
