### ISSUE TITLE
Curl command to test federation returns EOF

### ISSUE THREAD

**Issue by desigi** [LemmyNet/lemmy#3016]
### Issue Summary

When running the curl command
`curl -H 'Accept: application/activity+json' https://lemmy.iswhereits.at/u/SmugBedBug`
I get the following error
`curl: (35) error:0A000126:SSL routines::unexpected eof while reading`

I get an XML as expected when executing the example curl command in the setup guide at https://join-lemmy.org/docs/en/administration/first_steps.html

### Steps to Reproduce

1. Enter this command `curl -H 'Accept: application/activity+json' https://lemmy.iswhereits.at/u/SmugBedBug`

### Technical details

Server is running Ubuntu 22.04
Docker version 24.0.2
Docker compose version 2.18.1

**Comment by Nutomic** [comment]
Use https://lemmy.ml/c/lemmy_support
