### ISSUE TITLE
Following a Kbin community from Lemmy is broken

### ISSUE THREAD

**Issue by pimeys** [LemmyNet/lemmy#3020]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.

### Issue Summary

Subscribing to a Kbin magazine is not working on a new Lemmy instance (0.17.3).

### Steps to Reproduce

1. Try to open a Kbin community from my instance https://lemmy.nauk.io/c/linux@kbin.social
2. 404 not found
3. Wait a few minutes, retry, 404 not found

### Technical details

```
2023-06-11T11:01:46.475407Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: couldnt_find_community: error decoding response body: missing field `properties` at line 1 column 182
   0: lemmy_apub::fetcher::resolve_actor_identifier
             at crates/apub/src/fetcher/mod.rs:16
   1: lemmy_apub::api::read_community::perform
           with self=GetCommunity { id: None, name: Some("linux@kbin.social"), auth: Some(Sensitive) }
             at crates/apub/src/api/read_community.rs:30
   2: lemmy_server::root_span_builder::HTTP request
           with http.method=GET http.scheme="http" http.host=lemmy.nauk.io http.target=/api/v3/community otel.kind="server" request_id=e1b55819-fd89-4c89-a145-3ba606fb28b7 http.status_code=400 otel.status_code="OK"
             at src/root_span_builder.rs:16
LemmyError { message: Some("couldnt_find_community"), inner: error decoding response body: missing field `properties` at line 1 column 182

Caused by:
    missing field `properties` at line 1 column 182, context: "SpanTrace" }
```

**Comment by chaorace** [comment]
I think that this may be due to kbin having [turned on CloudFlare protection](https://kbin.social/m/kbinMeta/t/10415/kbin-quick-update) recently?

**Comment by Nothing4You** [comment]
that HTML is indeed the cloudflare challenge

**Comment by pimeys** [comment]
What is the correct way to communicate this with them? I think they also don't want to break federation with the Cloudflare challenge...

**Comment by mirisbowring** [comment]
I get "Failed to dereference site for https://kbin.social/: error decoding response body: expected value at line 1 column 1" errors from kbin. Is this related to the Cloudflare thing?

I am able to subscribe to kbin magazines and can see comments but I CANNOT comment (they are only on my site, not on kbin).
