### ISSUE TITLE
sorting comments by new only sorts the top level comments 

### ISSUE THREAD

**Issue by ericjmorey** [LemmyNet/lemmy#3021]
### Issue Summary

When sorting comments on a post, the comments are sorted by top level comments only. If the newest comment on a post is nested as a reply, the newest comment will not have an effect on the sorting. 

### Steps to Reproduce

- Go to any post with multiple comments. 
- Sort by new
- add comment as a reply to the oldest comment
- refresh the page
- sort by new
- see that your newest comment did not have an effect on the sort order.

**Comment by ericjmorey** [comment]
The correct sorting results should have the top level comment with the newest nested comment show first. This logic should also be reflected for the sorting of nested comments as well. For example, if there are multiple 2nd level comments, they should be sorted by the second level comment with the newest nested comment first.

**Comment by dessalines** [comment]
That's because your newest comment did not bump the published time on every single one of its parents. I don't think that's easily doable or desirable, because it would mean that sorting comment trees need to look through every one of their children / parent's published time.
