### ISSUE TITLE
Editing a comment increases the number of comments

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy#3023]
I just saw real time someone from another instance edit his comment and the number of comments went up. There are 3 comments but the post now says there are 6 comments meaning he has edited his comment 3 times.

**Comment by Nutomic** [comment]
You need to fill in the issue template and provide links to affected comments.

**Comment by JediMaster25** [comment]
No, I don't want to fill the issue template or link my identities. Sorry.
