### ISSUE TITLE
RSS feed uses old comment url

### ISSUE THREAD

**Issue by JetpackJackson** [LemmyNet/lemmy#3051]
### Issue Summary
I've subscribed to my inbox RSS feed with Newsboat.
When clicking the link to a comment from my Newsboat feed, the lemmy webpage gives error "404: TypeError: Cannot read properties of undefined (reading 'send')"

### Steps to Reproduce

1. Select inbox message from Newsboat.
2. Follow the link underneath the date section.
3. Error is shown

### Technical details
I just use lemmy on my browser on Arch Linux so I don't have any logs to give.

**Comment by Nutomic** [comment]
I see, RSS feeds still use the old comment link format of `/post/123/comment/456`. Should be changed to only `/comment/456`. Can you make a pull request?

https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/feeds.rs#L405

**Comment by JetpackJackson** [comment]
Alright, I made a pull request. Let me know if I need to change anything, it's my first time doing this kind of thing.
