### ISSUE TITLE
Add community tags

### ISSUE THREAD

**Issue by Hypersapien** [LemmyNet/lemmy#3052]
As Lemmy grows, along with the number of communities in a server, it can become increasingly difficult to find a community for a specific interest and can lead to duplication. I would suggest letting mods add tags to communities for the different categories the community would fall into. Things like philosophy, sports, memes, technology, gaming, etc... They could be displayed in the sidebar and clicking on one would bring up a list of all other communities that have that same tag. I would also suggest adding a page to list all of the tags that are being used on that server and the ability to search for communities by multiple tags.

**Comment by Nutomic** [comment]
This is not a bug and was already requested before.
