### ISSUE TITLE
Dynamically subscribe to other instances communities

### ISSUE THREAD

**Issue by jordan1776** [LemmyNet/lemmy#3055]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

**Describe the feature request below**

**Problem**
An issue I (and I'm sure many other people have) is finding an instance with plenty of communities which interest them and then realizing that you have to pick though every single community (browsing from your home instance) to get them into your subscribe feed. I know pruning your feed is nice but if you found a instance where 95% of the communities are up your alley it is annoying, and when new communities are made, you have to go back and check for them. Your only ever truly in the loop of your home instance. I feel like federation should appear nearly invisible to the common user.

**Solution** 
Under 'communities', there should be a 4th tab (subscribed, local, all) for looking at and searching instances your instance is federated with. The usual headers (subscribers,  users/month, posts, comments) should be there but instead of Subscribe it should say Dynamic Subscribe. Pressing the button should add all communities to your sub list and when a new community is made, it would automatically appear in your subscribed list. Pressing the button to unsubscribe should unsub from all communities in that instance so probably having an "are you sure" popup saying you are about to unsubscribe from x number communities. The user would still have the ability to manually remove communities that been dynamic subscribed from there subscribe list

**Alternatives** 
Manually subbing by hand is too time consuming. If there were a "subscribe all communities" button you would miss out on new communities being made.

**Comment by TortoiseWrath** [comment]
I think it would be very helpful to automatically import the community list from federated instances (perhaps servers could publish a list of their communities as an activitypub feed or something?). I just had some folks explain this mechanism to me at https://lemmy.world/post/146792 and it seems like there's a common opinion that the way it works now is pretty unintuitive, particularly for those of us using smaller instances on which fewer federated communities will have already been "discovered."

**Comment by jordan1776** [comment]
That could be one way of doing it. I'm not sure about how it should work in the backend, but as long as it leads " I'm interested in this set of up and coming communities, bam, it will all be in my feed now," I would be happy.

**Comment by n3oney** [comment]
It is annoying to have to use a third party website to discover communities, and I believe this is a rather important problem.

**Comment by ThinkSalat** [comment]
This is definitely something I'd be interested in. It's a little slow propagating new communities as well, so sharing your community you've made across instances is pretty annoying. I don't want to manually check each potential instance to see if it's available there yet, and I don't want to tell people to just wait until it shows up. This should be of highest priority as people are migrating away from reddit and creating new communities.

**Comment by dessalines** [comment]
We don't want to implement "automatic community crawling and subscribing" into lemmy, but there is some work being done to streamline federated community subscribes. Then you could use one of the global community tools people have made like https://lemmyverse.net/communities , and easily subcribe with its redirect back to your home instance.
