### ISSUE TITLE
Hot sorting is easily flooded by very active communities 

### ISSUE THREAD

**Issue by ISibboI** [LemmyNet/lemmy#3056]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support .
- [x] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Issue Summary

I assume hot sorting works similar as in Reddit via the lower limit of a confidence interval of the expected value of `upvotes/(upvotes+downvotes)`.

Hot sorting seems to strongly prefer new posts, in the range if one hour old, even if there are posts with a lot better time-independent score. This leads to very active communities like "196" which encourage users to post every time they visit to easily dominate the hot page of my subscriptions at times where other communities are less active. Right now, all but 4 posts on my hot page are from "196", mostly less than an hour old. Even though other communities I follow have been active as well in the last e.g. 12 hours.

### Steps to Reproduce

1. Follow a single community that gets a lot of posts, say one per minute.
2. Follow many communities that get say 5 posts a day with a break in the evening.
3. Look at posts from subscribed communities sorted by hot.

### Technical details

- ~~Please post your log: `sudo docker-compose logs > lemmy_log.out`.~~ not an instance admin, doubt this is a "logged bug"
- ~~What OS are you trying to install lemmy on?~~ unrelated to the described behaviour 
- ~~Any browser console errors?~~ mobile browser doesn't show these, and l doubt that sorting is done by the front end, and there are a lot of posts on my hot page, so nothing is missing. Also, nothing is repeated.

**Comment by JediMaster25** [comment]
Similar to [The rank of a post in the aggregated feed should be inversely proportional to the size of the community](https://github.com/LemmyNet/lemmy/issues/1026)

**Comment by ISibboI** [comment]
Call it a feature request if you want. It impacts me in the way that I must unsubscribe from some communities if I want to keep a heterogeneous overview of what is going on in all my subscribed communities.

**Comment by JediMaster25** [comment]
You should say what you want if it's a feature request, be specific.

**Comment by krestenlaust** [comment]
Dupe: #1026
