### ISSUE TITLE
Don't Display Votes for Your Own Content

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy#3064]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [x] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

**Describe the feature request below**
A mental well-being feature that functions similarly to hiding all votes, but with the exception that it shows all votes except for those on your own content, posts, or comments.

**Comment by csm10495** [comment]
I think this is an interesting idea but I'd want it to be user-opt-in. (and opt-out able). I wouldn't want this to be a non-changeable behavior.

**Comment by JediMaster25** [comment]
You are right, I forgot to mention that this would be a user setting, similar to "Show Scores."

**Comment by JediMaster25** [comment]
Sorry I made a [duplicate](https://github.com/LemmyNet/lemmy-ui/issues/1290) of this one. It's a front-end feature so I'll close this one.
