### ISSUE TITLE
add tradional chinese translation

### ISSUE THREAD

**Issue by lokyinng** [LemmyNet/lemmy#3067]
- [*] Did you check to see if this issue already exists?
- [*] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [*] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [*] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

**Describe the feature request below**

**Comment by Nutomic** [comment]
Use https://weblate.join-lemmy.org/
