### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by Aloso** [LemmyNet/lemmy#3070]
**Describe the feature request below**

Having to specify the language every time I write a comment or post is tedious. It would be nice if communities could set a "default language", which is pre-selected whenever writing a post or comment (but can be changed by the user).

Another idea is that when writing a comment, the post's language could be pre-selected in the comment, but this only solves half of the problem.

I understand that communities can have posts in many different languages. However, if most moderators only speak English, they can't effectively moderate posts in other languages, so I guess that most communities only want posts in a single language.

**Comment by Nutomic** [comment]
You can already configure languages in the community settings. When only a single language is enabled (excluding undefined), it is selected as default for all posts and comments.

**Comment by hillbicks** [comment]
Maybe one thing to keep in mind: Sometimes users will post comments in english in communities that are using non using languages. So while it makes sense to set the default language to german for example, then you're forcing everyone to use this setting. Having a "default" language would help with that. 

I think setting the one language is a good workaround for the moment though.

**Comment by Nutomic** [comment]
If the language is set to German then there should be no English posts...

**Comment by Aloso** [comment]
@Nutomic The default language of lemmyrs.org was set to English, but when creating a post, there is still no language pre-selected:

![image](https://github.com/LemmyNet/lemmy/assets/15658558/f97facd6-f520-4567-be81-9a74834dc5a2)

The dropdown initially says "Select language" instead of "English". Is this a bug?

**Comment by Nutomic** [comment]
No the default gets set on the backend if you didnt select anything in the dropdown.
