### ISSUE TITLE
Add ability to save draft 

### ISSUE THREAD

**Issue by elishamint** [LemmyNet/lemmy#3072]
Add the necessary backend changes to enable saving of unpublished/unsent messages, for posts/comments as well as private messages.

This feature is directly related to this FR for the UI:
Add ability to save draft: https://github.com/LemmyNet/lemmy-ui/issues/1180

#3069 might require a similar DB structure to be added.

**Comment by rosalogia** [comment]
I'd be happy to have a go at this if no one else has already claimed it. I've started putting something together at https://github.com/rosalogia/lemmy/tree/add_drafts. I can make a PR if/when others would like for ease of viewing. It's my understanding that creating what's more or less a subset of the Post table for storing Drafts (without columns for things like time posted, locked, deleted, etc.), and then implementing some CRUD routes in the API for managing drafts should be more or less enough here? Correct me if I'm wrong or am misguided.

**Comment by elishamint** [comment]
@rosalogia
I'm not a developer here, and I do not know the DB structure exactly, but I have some knowledge about databases. In order to make it as efficient as possible, I would assess in which way the DB is going to be used. Meaning, whatever functionality that related ticket on the UI will bring to plan will in the end influence the new DB structures. I will add some more detailed suggestions to https://github.com/LemmyNet/lemmy-ui/issues/1180 .

The main (and perhaps most DB-intensive) action will probably be writing comments directly in the comment tree, then saving, and later re-loading the comment tree. Then, if there are any drafts in that tree, we'd have a button to load and continue editing, or we could have the editor load automatically.

With this procedure, we would have to retrieve information about the presence of drafts every time a comment tree is loaded. Having the drafts in a separate table however, will make for at least one more select operation. Additionally, we would have to sort the drafts into their places withing the tree.

So by making that thought experiment, I already get some clue that I could perhaps make it tremendously more efficient if I'd just add an "isdraft" flag to the Post table. That way I would make the draft(s) sort naturally into the tree, without much additional computation.

The other operations will likely be done from the "messages" pane (private message as well as comments), but those selects will probably be less demanding.

**Comment by elishamint** [comment]
#3069 might require a similar structure to be added.

**Comment by dullbananas** [comment]
Lets try to implement drafts for comments before Reddit does it

**Comment by Nutomic** [comment]
I thought about this and really dont think its worth the effort. If you want to write a draft, you can already do it in the text/markdown editor of your choice. Implementing this in Lemmy would be a lot of work as it would essentially require separate implementations for post draft, comment draft and private message draft.

**Comment by dessalines** [comment]
If someone wants to take this on we can re-open and assign it to them, we're really busy with other things.
