### ISSUE TITLE
Reddit-compatible API

### ISSUE THREAD

**Issue by Daniel15** [LemmyNet/lemmy#3078]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

**Describe the feature request below**
There's a lot of existing apps and scripts that use Reddit. If Lemmy had another API that replicated Reddit's one (same data types, same endpoints), it'd be relatively straightforward to update those existing apps/scripts to support Lemmy. We've seen the same thing in other industries: A lot of cloud storage providers have S3-compatible APIs, VictoriaMetrics has both Prometheus-compatible and InfluxDB-compatible APIs, some search engines have Elasticsearch-compatible APIs, etc.

I understand that the data model may not map 1:1, but maybe it could be fully mapped across with some minimal API changes.

Maybe instead of building this into the core (to avoid feature creep / bloating it out), there could be a separate daemon for an adapter that converts Reddit API requests to Lemmy API requests.

Bad idea? Useful idea? I'll let you decide. 😛

**Comment by dessalines** [comment]
Way too much work for us to support. This is a completely different service. It'd be much easier, and a better long-term solution for apps to transition to lemmy's API, since reddit is killing them anyway.

**Comment by Nutomic** [comment]
You are looking for this: https://github.com/derivator/tafkars

**Comment by Daniel15** [comment]
Thanks for the feedback. @Nutomic That looks promising!
