### ISSUE TITLE
Community Feedback in Mod Log

### ISSUE THREAD

**Issue by maltfield** [LemmyNet/lemmy#3081]
- [X ] Did you check to see if this issue already exists?
- [X ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [X ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [X ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

**Describe the feature request below**

This ticket will track a new feature where users are able to "flag" items on the `/modlog/` page for review

## Why?

Moderators have a hard job. Sometimes they get inundated with spam or hate messages and they have to do mass cleanup of content on Lemmy.

Unfortunately, mistakes happen. False-positives happen. Transparency is important; that's *why* we have the Mod Log. But, as linus says, with enough eye all bugs are shallow.

Currently, someone who is reviewing the Mod Log and spots a mistake doesn't have an easy way to raise that mistake to the Moderators for a second-glance.

## Solution

I suggest that logged-in users reviewing the Mod Log have a "flag" icon next to each action. When the flag is clicked, they can type a simple message that will be sent to the mods & admins as to why the user thinks the moderator's action was a mistake.

On the mod/admin side, there should be a queue to review this "Mod Log Feedback" (or "Community Appeals"). This queue should group the feedback together, such that it's much, much more noticeable if many users flag the same item (and items only flagged by one user would be less prevalent).

The moderators/admins reviewing the "Mod Log Feedback" page can choose to either [a] ignore or [b] reverse the action. Either action should be recorded in the Mod Log.

**Comment by dessalines** [comment]
I could see this being useful, but also don't like the idea of re-creating private group chats in lemmy (which dispute resolution really needs), when matrix or other platforms do that better. Maybe adding a matrix contact id for communities and admin teams would be enough, and the flag could link to that.

As for larger issues, its probably best to have community feedback on moderator / admin decisions as its own community: ie a community called `/c/meta`, `/c/mod_feedback` or `/c/admin_feedback`, with posts linking those actions, would probably serve this better.

**Comment by dessalines** [comment]
As stated above, meta / feedback communities are the best place for mod discussion, not the modlog queries.
