### ISSUE TITLE
Custom IP:PORT for pict-rs?

### ISSUE THREAD

**Issue by yaneony** [LemmyNet/lemmy#3082]
Right now it's hardcoded. Any way for some kind parameter to change listen IP and PORT?

Proof: https://github.com/LemmyNet/lemmy/blob/v0.17.3-rc.2/src/main.rs#L13

**Comment by Nutomic** [comment]
Yep this hardcoded config is only used if you compile with feature `embed-pictrs` (which is disabled for official releases.

**Comment by yaneony** [comment]
Also i will need to compile it by myself first?

Nutomic ***@***.***> schrieb am Mi., 14. Juni 2023, 15:51:

**Comment by Nutomic** [comment]
No pictrs runs separately by default and doesnt use that config block at all.

**Comment by yaneony** [comment]
Now I'm bit curious... Followinf this guide https://join-lemmy.org/docs/en/administration/from_scratch.html and doing:
```cargo install lemmy_server --target-dir /usr/bin/ --locked --features embed-pictrs```
also add **embed-pictrs** feature as you mantioned before. But, that doesn't include/accept any config options. Is that right so far?

So, what do i need to do to be able to specify defferent listen IP and not the hardcoded 127.0.0.1? Sorry if that question sound dumb. And yes, I'm aware i can install pict-rs as separate process.

**Comment by Nutomic** [comment]
You can remove that feature flag and compile pictrs separately. Didnt know that you are using from scratch install.

https://git.asonix.dog/asonix/pict-rs/

**Comment by yaneony** [comment]
Thanks!
