### ISSUE TITLE
`couldnt_find_object: invalid query` on fresh Ansible installation

### ISSUE THREAD

**Issue by hllywluis** [LemmyNet/lemmy#3083]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support .
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Issue Summary

Federation isn't working on a fresh install of Lemmy using Docker.

### Steps to Reproduce

1. Spin up a new VPS server (I used AWS)
2. Clone lemmy-ansible and follow all the steps
3. Visit instance
4. Try searching for a community in another instance (I used lemmy@lemmy.ml)

The issue I'm encountering is `couldnt_find_object: invalid query`. I've also tried using the Docker steps to install Lemmy onto a macOS machine with the same results.

### Technical details

```sh
2023-06-14T01:40:08.614945Z ERROR HTTP request{http.method=GET http.scheme="http" http.host=kleptonix.com http.target=/api/v3/ws otel.kind="server" request_id=504c505f-5398-49cc-9986-3b1569def2ed http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: couldnt_find_object: invalid query
   0: lemmy_apub::fetcher::search::search_query_to_object_id
             at crates/apub/src/fetcher/search.rs:17
   1: lemmy_apub::api::resolve_object::perform
           with self=ResolveObject { q: "lemmy@lemmy.ml", auth: Some(Sensitive) }
             at crates/apub/src/api/resolve_object.rs:21
   2: lemmy_server::root_span_builder::HTTP request
           with http.method=GET http.scheme="http" http.host=kleptonix.com http.target=/api/v3/ws otel.kind="server" request_id=504c505f-5398-49cc-9986-3b1569def2ed http.status_code=101 otel.status_code="OK"
             at src/root_span_builder.rs:16
```

**Comment by timp80** [comment]
i was getting the same error with mine, but I've just tried searching for !lemmy@lemmy.ml, and now the error has gone away and i've got lemmy@lemmy.ml showing up under communities now.

**Comment by Nutomic** [comment]
Pretty sure only `!lemmy@lemmy.ml` format is supported, not `lemmy@lemmy.ml`. Instead you can also search for the full community url `https://lemmy.ml/c/lemmy`
