### ISSUE TITLE
Password max length of 60 characters?

### ISSUE THREAD

**Issue by Jappie3** [LemmyNet/lemmy#3085]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support .
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Issue Summary

When setting up Lemmy using Ansible, Docker & Traefik, I repeatedly ran into the issue that I could not log in using my password specified in `lemmy.hjson`. Here is an excerpt from that file (I have since changed the password, this one is no longer in use):

```
  setup: {
    # Username for the admin user
    admin_username: "admin"
    # Password for the admin user. It must be at least 10 characters.
    admin_password: "oDM6UoR2441B20IOy4LfuPBlGz5hqSnecmaOTdR0ETlUyCqUa5JJtrJIPIn9xRvG"
    # Name of the site (can be changed later)
    site_name: "My Lemmy Instance"
    # Email for the admin user (optional, can be omitted and set later through the website)
    admin_email: "[redacted]"
  }

```

The Docker logs of the container only showed the following, while I was sure I entered the correct password.

```
2023-06-14T06:47:20.001887Z ERROR HTTP request{http.method=GET http.scheme="https" http.host=[my_domain_name] http.target=/api/v3/ws otel.kind="server" request_id=7aeb5d4b-fa50-4e6d-90c4-52a2b12c24bb http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: password_incorrect: password_incorrect
   0: lemmy_api::local_user::login::perform
           with self=Login { username_or_email: Sensitive, password: Sensitive }
             at crates/api/src/local_user/login.rs:17
   1: lemmy_server::root_span_builder::HTTP request
           with http.method=GET http.scheme="https" http.host=[my_domain_name] http.target=/api/v3/ws otel.kind="server" request_id=7aeb5d4b-fa50-4e6d-90c4-52a2b12c24bb http.status_code=101 otel.status_code="OK"
             at src/root_span_builder.rs:16
```

After quite a while I looked at the websocket connection in Firefox's developer tools:

![image](https://github.com/LemmyNet/lemmy/assets/42720120/f54f8f96-2005-4eba-b0fb-9eefaab56905)

The password shown here ends in `n9`, if you look at the file above, that means 4 characters are cut off. So somehow, the max password length that gets sent along via the websocket is 60 characters. I have never read anything about this in the documentation, so my conclusion is the following:
1) I'm blind
2) This is undocumented / badly documented (and should imo be added to the [default config file documentation](https://join-lemmy.org/docs/en/administration/configuration.html#full-config-with-default-values), just like how it says that the minimum length is 10 characters)
3) This is a bug

### Steps to Reproduce

1. Install Lemmy using Docker. Make sure to generate a password for the admin user that has 60+ characters in `lemmy.hjson`.
2. Try logging in to your new Lemmy instance.
3. Observe the spinning wheel and the cryptic 'password_incorrect: password_incorrect` error in the Docker logs. Look at the websocket connection in developer tools, click on 'response' & identify the login request. Inspect the json of that request, you'll see the first 60 characters of your password.

**Comment by Jappie3** [comment]
Update: decided to look around for a bit, found this in the lemmy-ui repo:
https://github.com/LemmyNet/lemmy-ui/blob/f61037f5d89f12818c8100f907a98b74e980112a/src/shared/components/home/login.tsx#L131

It seems like the input field has a `maxLength` attribute. I don't think it's up to me to decide what should happen now, either document this or change the field to a higher value (and still document it).

**Comment by pproe** [comment]
Please see https://github.com/LemmyNet/lemmy-ui/issues/1120.

I don't personally see any reason for not allowing a higher limit for password-length (say 256 characters). Especially considering wide-spread use of password managers & phrase passwords.

**Comment by Jappie3** [comment]
Thank you for linking that issue, I didn't search the lemmy-ui repo when checking for this problem... Since people are aware of the 'problem', I'll close this issue for now.
