### ISSUE TITLE
E-Mail sending

### ISSUE THREAD

**Issue by IngwiePhoenix** [LemmyNet/lemmy#3097]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support .
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Issue Summary

When trying to send E-Mails through Mailgun via TLS/465 or StartTLS/587, it encounters a timeout.

### Steps to Reproduce

1. Setup and register for Mailgun.
2. In their Dashboard, chose your domain
3. Then in the left sidebar, select "Domain Settings"
4. Here, you can use "SMTP Credentials" to set some up for Lemmy to use.
5. Enter your creds into `lemmy.hjson`, appending the port to the hostname (`smtp.eu.mailgun.org` in my case).
  * Append `:465` to the hostname and set `tls_type` to `tls`.
  * Or: use `587` instead and set `tls_type` to `starttls` instead.
6. Restart the Lemmy server
7. Log in, head to your settings, set an E-Mail address - and click "Save".
8. Wait approximately a minute, the error will show up in your server logs now.

Here's mine.

```
lemmy_1     | 2023-06-14T14:07:52.537067Z ERROR HTTP request{http.method=GET http.scheme="https" http.host=drachennetz.com http.target=/api/v3/ws otel.kind="server" request_id=fb772b7d-8f1c-4e24-8b8e-e3fc65c0bc69 http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: email_send_failed: Connection error: timed out
lemmy_1     |    0: lemmy_api::local_user::save_settings::perform
lemmy_1     |            with self=SaveUserSettings { show_nsfw: Some(true), show_scores: Some(true), theme: Some("browser"), default_sort_type: Some(0), default_listing_type: Some(1), interface_language: Some("browser"), avatar: None, banner: None, display_name: Some("Ingwie Phoenix"), email: Some(Sensitive), bio: None, matrix_user_id: Some("@ingwiephoenix:ingwie.me"), show_avatars: Some(true), send_notifications_to_email: Some(false), bot_account: Some(false), show_bot_accounts: Some(true), show_read_posts: Some(true), show_new_post_notifs: Some(false), discussion_languages: Some([LanguageId(0), LanguageId(32), LanguageId(37)]), auth: Sensitive }
lemmy_1     |              at crates/api/src/local_user/save_settings.rs:29
lemmy_1     |    1: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=GET http.scheme="https" http.host=drachennetz.com http.target=/api/v3/ws otel.kind="server" request_id=fb772b7d-8f1c-4e24-8b8e-e3fc65c0bc69 http.status_code=101 otel.status_code="OK"
lemmy_1     |              at src/root_span_builder.rs:16
```

Here's an example config snippet:
```
  email: {
    smtp_server: "smtp.eu.mailgun.org:587"
    smtp_login: "lemmy@mailgun.drachennetz.com"
    smtp_password: "**snip**"
    smtp_from_address: "lemmy@mailgun.drachennetz.com"
    tls_type: "starttls"
  }
```

### Technical details

- Please post your log: `sudo docker-compose logs > lemmy_log.out`.
  * See above.
- What OS are you trying to install lemmy on?
  * Ubuntu 22.04 on arm64 via Docker (append `-linux-arm64` to a version tag.)
- Any browser console errors?
  * There was nothing in the browser console.

**Comment by ruudschilders** [comment]
Did you add an external network to your lemmy container in the docker-compose?

**Comment by Nutomic** [comment]
This issue tracker is not for support, use matrix or !lemmy_support

**Comment by krestenlaust** [comment]
A !selfhosted-community post could also help you
