### ISSUE TITLE
Local community falsely becoming remote

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy#3099]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support .
- [x] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Issue Summary

See: https://github.com/LemmyNet/lemmy-ui/issues/1141

Apparently my instance thinks this community is remote, despite clearly being local. I have also had this happen on communities on lemmy.ml

### Steps to Reproduce

? No idea. Just seems to randomly happen to some communities.

**Comment by Nutomic** [comment]
Sounds like https://github.com/LemmyNet/lemmy/issues/3075
