### ISSUE TITLE
Cryptographically signed content

### ISSUE THREAD

**Issue by avidseeker** [LemmyNet/lemmy#3106]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [x] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

Are there any plans for including signed posts and comments? In a manner similar to Nostr protocol. So far Mastodon only include identity authentication via Keyoxide. But signing actual posted content will put less trust in the instance server.

**Comment by Nutomic** [comment]
There are no such plans. And if you dont trust your instance, you can switch to another one so I fail to see the purpose.

**Comment by avidseeker** [comment]
Mastodon issue for this feature:

https://github.com/mastodon/mastodon/issues/928
