### ISSUE TITLE
PM email notifications are using "Private Message From [your username]" rather than Sender's Username

### ISSUE THREAD

**Issue by 100000BC** [LemmyNet/lemmy#3107]
As you can see below, this was the conversation we had:

![image](https://github.com/LemmyNet/lemmy/assets/67931296/a4a0e90f-d959-445a-b521-daae3d4e35f1)

But the email notifications came into my inbox saying his messages were from myself:

![image](https://github.com/LemmyNet/lemmy/assets/67931296/7bb07855-6fb3-4bd8-8914-293f271cab5d)

**Comment by Nutomic** [comment]
This was already fixed recently.
