### ISSUE TITLE
Blocking communities from an instance

### ISSUE THREAD

**Issue by Antik79** [LemmyNet/lemmy#3113]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Is there any way to block a community from a server/instance. It looks like it’s only
possible on a user-level, unless I’m missing something it’s not in the
documentation on join-lemmy.

### Describe the solution you'd like.

Possibility for admins to block communities from an instance

### Describe alternatives you've considered.

Looked into the official documentation, doesn't seem there's that option currently

**Comment by Nutomic** [comment]
Yes you can remove the community, then it will be gone from your server and not federate anymore.

**Comment by Antik79** [comment]
> 

Just to be clear I mean removing specific communities from a remote instance on an entire server - so for all users. I know we can block complete instances

**Comment by Nutomic** [comment]
Yes in the community sidebar under subscribe buttons etc there is the remove button which does exactly that.

**Comment by Antik79** [comment]
Thank you!
