### ISSUE TITLE
Question: Banning community names using keywords

### ISSUE THREAD

**Issue by Antik79** [LemmyNet/lemmy#3115]
### Question

Is there an option to ban certain keywords from being used in community names on our server? Communities with the n-word for example

**Comment by servoparmi** [comment]
No, but any enhancement should be admin configurable per instance rather than hardcoded, to avoid defaultism around the developers' language preferences

**Comment by Antik79** [comment]
> 
Yes definitely not hard-coded. Ofcourse the instance admin should be able to add strings like n*gger and such that are banned.

**Comment by Nutomic** [comment]
Admins can configure a slur filter. This is used to check community names, user names and other things.
