### ISSUE TITLE
[Bug]: docker-compose.yml file version is not correct

### ISSUE THREAD

**Issue by jmaister** [LemmyNet/lemmy#3116]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Running the docker-compose.yml file provided in the docker folder fails with this message:

```sh
jordi@xxx:~/projects/lemmy$ docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "x-logging". Valid top-level sections for this Compose file are: version, services, networks, volumes, secrets, configs, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

### Steps to Reproduce

1. Follow steps on page https://join-lemmy.org/docs/en/administration/install_docker.html to download the docker-compose.yml file
2. Make required changes
3. docker-compose up -d

### Technical Details

```
jordi@xxx:~/projects/lemmy$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

```
jordi@xxx:~/projects/lemmy$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2
```

### Version

main

**Comment by jjakc-76** [comment]
Also getting this error message. Using docker-compose version 1.25.0

**Comment by jmaister** [comment]
I fixed it setting the version to '3.7'

**Comment by cperrin88** [comment]
You don't need the `version` at all. See https://docs.docker.com/compose/compose-file/04-version-and-name/

**Comment by cudla100** [comment]
> You don't need the `version` at all. See https://docs.docker.com/compose/compose-file/04-version-and-name/

This created:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for x-logging: 'driver'
Unsupported config option for networks: 'lemmyexternalproxy'
Unsupported config option for services: 'pictrs'
```
Should I create new issue?

**Comment by cperrin88** [comment]
Do you use the old `docker-compose` command or do you use the new docker compose plugin (`docker compose`)? If you are not using the plugin you should switch over.

**Comment by johanbcn** [comment]
Correct, docker-compose has been deprecated for a long time now.

https://docs.docker.com/compose/migrate/

The new version has been rewriten in go and distributed as a docker plugin (i.e. invoked as "docker compose up -d", notice the lack of a dash between docker and compose).

New version is backwards compatible with the old syntax, so it should be safe for you to upgrade.

**Comment by cudla100** [comment]
Docker compose is stuck on [+] Building 0.0s (0/0). I am trying to run this on pi 4 8GB so I had to add "platform" into docker-compose.yml. Also, manual says docker-compose so you might get this often from new users, if you do not change it.

**Comment by Downy** [comment]
Getting the same issue, getting stuck on `Building 0.0s (0/0)`. Can't stop the "building" either, have to close the terminal

**Comment by RyantHults** [comment]
I have found that exiting the terminal after getting `Building 0.0s (0/0)` and attempting to run `docker compose up -d` again allows it to complete. Seems like something is hanging on that first build

**Comment by Downy** [comment]
No such luck on my end unfortunately

**Comment by Nutomic** [comment]
Version of docker-compose.yml was updated
