### ISSUE TITLE
Question: OriginNotAllowed when making UI requests to backend in development setup

### ISSUE THREAD

**Issue by alastor-erinyes** [LemmyNet/lemmy#3118]
### Question

I followed the instructions [here](https://join-lemmy.org/docs/en/contributors/02-local-development.html) to setup a local development environment but after setting up postgres, the lemmy backend and the lemmy-ui frontend (single-box) all requests made from the frontend to the backend fail with the following error:

```
2023-06-14T23:07:30.408294Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: Origin is not allowed to make this request OriginNotAllowed
```

Is there a recommended way to setup such that OriginNotAllowed isn't triggered?  My (admittedly limited) understanding of this is it's there to prevent cross-site scripting, but I'm unsure of whether I should be doing something different to avoid it or disabling the header entirely due to being single-box.

Thanks for the help!

**Comment by cdbrendel** [comment]
I was having this exact issue and was in the process of preparing a pull request, but https://github.com/LemmyNet/lemmy/pull/3191 was just merged and should fix your issue. Just set `LEMMY_CORS_ORIGIN=your.frontend.tld`  when executing the `lemmy_server` backend.

**Comment by cinderisles** [comment]
I can confirm `LEMMY_CORS_ORIGIN` works. Keep in mind that a different port number is considered a different origin. so make sure you include protocol, hostname, and port

If you don't include the environment variable [this line](https://github.com/LemmyNet/lemmy/blob/main/src/lib.rs#L161) suggests that `http://localhost` will be the default, which may not be what you want. 

If you are following some of the documentation and using default config files and such, your `LEMMY_CORS_ORIGIN` will probably be this:

```
LEMMY_CORS_ORIGIN=http://localhost:1236
```
