### ISSUE TITLE
[Bug]: email_send_failed: Connection error: timed out

### ISSUE THREAD

**Issue by delendum** [LemmyNet/lemmy#3126]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Hi,

I'm hitting my head against a wall here. I have docker lemmy installed and configured to send mail via my mailcow mailserver on the same network. 

No matter what I try, sending e-mail just times out.

Some more troubleshooting info:
1. The webserver is reachable from the lemmy host; it also works fine with similar setups for other services on my network.
2. There's nothing in the mailserver postfix logs, lemmy's not reaching it at all as far as I can tell.
3. There's nothing in the router or mailserver firewall logs to indicate they're blocking the lemmy instance for some reason.
4. There's no local firewall on the lemmy instance (still playtesting).
5. I've tried all possible combination of ports and TLS options in the settings, nothing works.
6. I've re-rolled the lemmy install several times.

I honestly don't know what else to try, any help would be appreciated!

### Steps to Reproduce

1. Update admin account with e-mail address
2. The Lemmy UI sits at the spinning circle after applying
3. Docker logs for lemmy_lemmy_1 eventually display a time-out error

### Technical Details

```
2023-06-15T09:07:26.048827Z ERROR HTTP request{http.method=GET http.scheme="http" http.host=192.168.30.199 http.target=/api/v3/ws otel.kind="server" request_id=2459cb90-a5ec-4a69-82a0-613724c57b62 http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: email_send_failed: Connection error: timed out
   0: lemmy_api::local_user::save_settings::perform
           with self=SaveUserSettings { show_nsfw: Some(false), show_scores: Some(true), theme: Some("browser"), default_sort_type: Some(0), default_listing_type: Some(1), interface_language: Some("browser"), avatar: None, banner: None, display_name: None, email: Some(Sensitive), bio: None, matrix_user_id: None, show_avatars: Some(true), send_notifications_to_email: Some(false), bot_account: Some(false), show_bot_accounts: Some(true), show_read_posts: Some(true), show_new_post_notifs: Some(false), discussion_languages: Some([]), auth: Sensitive }
             at crates/api/src/local_user/save_settings.rs:29
   1: lemmy_server::root_span_builder::HTTP request
           with http.method=GET http.scheme="http" http.host=192.168.30.199 http.target=/api/v3/ws otel.kind="server" request_id=2459cb90-a5ec-4a69-82a0-613724c57b62 http.status_code=101 otel.status_code="OK"
             at src/root_span_builder.rs:16
```

The server is running on Debian 12

### Version

BE: 0.17.4

### Lemmy Instance URL

not public yet

**Comment by adamboutcher** [comment]
I have the same issue, I suspect it's something to do with NAT reflection, I was attempting to get around it by using the local device IP however the SSL verification fails and there seems to be no bypass.

Possible related issue: https://github.com/LemmyNet/lemmy/issues/3058
Possible workaround feature request: https://github.com/LemmyNet/lemmy/issues/3141

**Comment by NickGeek** [comment]
Also have the same issue with SMTP over TLS

**Comment by Nutomic** [comment]
This issue tracker is not for support.
