### ISSUE TITLE
Adding tags for smaller languages

### ISSUE THREAD

**Issue by harcesz** [LemmyNet/lemmy#3127]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

Poland has two smaller language minorities who's languages are not featured in the list

### Describe the solution you'd like.

Adding options for;
Silesian language - https://en.wikipedia.org/wiki/Silesian_language - ślōnskŏ gŏdka
Kashubian language - https://en.wikipedia.org/wiki/Kashubian_language - kaszëbsczi

### Describe alternatives you've considered.

Allowing admins to add local languages/dialects locally.

### Additional context

User asked for this while creating a regional community; https://szmer.info/post/365023

**Comment by harcesz** [comment]
So maybe some option for local languages to be added by admins?

**Comment by Nutomic** [comment]
You can insert them directly in the `language` table. Best make some tests to ensure it doesnt break anything, but should be okay.

**Comment by harcesz** [comment]
Note; just adding the language in database is not enough for it to work.
