### ISSUE TITLE
End user verifiable releases 

### ISSUE THREAD

**Issue by jszejner** [LemmyNet/lemmy#3130]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

As a user I find it valuable to be able to evaluate a Lemmy instance for truth and transparency, one of those metrics is knowing that the instance is running the same code as others and is not modified from official Lemmy releases

### Describe the solution you'd like.

Some sort of release signing that can be verified by an API and/or through the Lemmy UI 

### Describe alternatives you've considered.

None

### Additional context

Cannot submit form without checking " Is this a UI / front end issue?" That is incorrect this request is only the part for the backend.

**Comment by jszejner** [comment]
Going to close this per discussions on the matrix chat currently it is not technically possible to implement this in a secure manner and an academic discussion on whether this would make sense to implement.

**Comment by s0er3n** [comment]
What's the point? You can still change the database.
