### ISSUE TITLE
Question: Comments Not Consistent Across Instances?

### ISSUE THREAD

**Issue by livejamie** [LemmyNet/lemmy#3133]
### Question

Hello I'm new to Lemmy and I'm trying to decide which instance to use. I've largely read that it doesn't really matter.

As a test use case I found a random post on the pathofexile lemmy that I wanted to interact with which is found here:
https://pathofexile-discuss.com/post/62

I then tried subscribing and loading that post in several different instances and found that most of them don't load the comments, or only load some. Why is this happening?

| Instance                           | Number of Comments | Notes                                                                                             |
|------------------------------------|--------------------|---------------------------------------------------------------------------------------------------|
| https://sh.itjust.works/post/75968 | 4/12               | Originally only my comment I left only showed up, after 24 hours 3 other comments have showed up. |
| https://partizle.com/post/9413     | 0/12               |                                                                                                   |
| https://beehaw.org/post/519636     | 5/12               | Initially only had one comment, after 24 hours 3 other comments have showed up                    |
| https://lemmy.world/post/74747     | 10/12              |                                                                                                   |
| https://lemm.ee/post/31886         | 0/12               |                                                                                                   |
| https://possumpat.io/post/25570    | 0/12               |                                                                                                   |

**Comment by livejamie** [comment]
Similar discussion here: https://www.reddit.com/r/RedditAlternatives/comments/1498m3u/discrepancies_between_instances/

**Comment by RocketDerp** [comment]
Issue #3101 is open about this from yesterday, I suggest you close this issue, the developers are busy on both lemmy server and lemmy-ui.

**Comment by livejamie** [comment]
Ah thanks.
