### ISSUE TITLE
[Bug]: Stuck at a Spinning well when you try to login using your email

### ISSUE THREAD

**Issue by spellbind0127** [LemmyNet/lemmy#3136]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

If I try to login with my email I get a spinning well that doesn't stop spinning so I am never able to logging in. If I put in my username I am able to login like normal

### Steps to Reproduce

1. Register for an account on a Lemmy (I register with an email user a custom domain)
2. confirm your email using the email you get in your email inbox
3. try to login using your email and you will get a spinning well of death

### Technical Details

 no error on the console and I don't have access to the docker as I am not the instance admin.

### Version

BE 0.17.4

### Lemmy Instance URL

infosec.pub

**Comment by RocketDerp** [comment]
This is probably front-end project https://github.com/LemmyNet/lemmy-ui

**Comment by rosenjcb** [comment]
@RocketDerp The UI doesn't get any updates on a failed login. This is what the websocket traffic looks like:
![image](https://github.com/LemmyNet/lemmy/assets/8102129/8a0bf890-f981-4fce-b45a-0fa63c1ac657)

The Lemmy instance doesn't respond back.

**Comment by Nutomic** [comment]
This is a frontend issue and might be fixed already

**Comment by spellbind0127** [comment]
Yah it does seem to be fixed

**Comment by AtoMops** [comment]
No it's not fixed. Got the same issue.

**Comment by RocketDerp** [comment]
Confirmed, the very latest GItHub code for lemmy_server and lemmy-ui is in production here: https://lemm.ee/login

Put in a wrong username (not an email) and password, no message of any kind returns! Same with e-mail address that is unknown. General Internet convention is if the account itself is not found, you return a message.

Delving into the API layer:

```
node lemmyhelper_commandline.js testlogin --username nevermatch0 --password nevermatch0 --server "https://lemm.ee/"
node lemmyhelper_commandline.js testlogin --username "nevermatch999@gmail.com" --password nevermatch0 --server "https://lemm.ee/"
```

You do not get a JSON response, you get a 404 HTTP status for unknown username, but 400 status for unknown email address.

**Comment by rosenjcb** [comment]
> Confirmed, the very latest GItHub code for lemmy_server and lemmy-ui is in production here: https://lemm.ee/login
> 
> Put in a wrong username (not an email) and password, no message of any kind returns! Same with e-mail address that is unknown. General Internet convention is if the account itself is not found, you return a message.
> 
> Delving into the API layer:
> 
> ```
> node lemmyhelper_commandline.js testlogin --username nevermatch0 --password nevermatch0 --server "https://lemm.ee/"
> node lemmyhelper_commandline.js testlogin --username "nevermatch999@gmail.com" --password nevermatch0 --server "https://lemm.ee/"
> ```
> 
> You do not get a JSON response, you get a 404 HTTP status for unknown username, but 400 status for unknown email address.

Because of the inconsistencies in the API response, I argue that this should be addressed in the backend project as well. There will probably need to be front and changes, but the back and changes are also necessary.
