### ISSUE TITLE
[Bug]: Enabling "Private Instance" and Federation at the same time locks you out of the instance

### ISSUE THREAD

**Issue by austinvaness** [LemmyNet/lemmy#3138]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

I restarted lemmy recently and got this error in the console:

Error: LemmyError { message: Some("Cannot have both private instance and federation enabled."), inner: Cannot have both private instance and federation enabled., context: "SpanTrace" }

At first, I didnt know this error was preventing startup and spent a bunch of time troubleshooting front end error messages. The only way I was able to get rid of the error message was to go into the postgres database and turn private_instance to false in the local_site table. Only then did it start up properly.

Why is lemmy refusing to start with these two settings enabled at the same time? How am I supposed to fix it if I cant access the admin site settings?

### Steps to Reproduce

1. Enable "Private Instance"
2. Turn on "Federation enabled"
3. Restart lemmy

### Technical Details

Running lemmy via Portainer (docker) on an Ubuntu VM

### Version

v0.17.4

**Comment by dyslexicjedi** [comment]
Had this happen to me as well, same resolution. Thanks for the tip.

**Comment by caffineehacker** [comment]
For anyone hitting this in the future, here are the exact steps to resolve it with docker (took me a while to figure it all out):

1) Go to your server and cd to your lemmy docker directory (e.g. /lemmy)
2) Run `docker ps` to list the docker instances
3) Run `docker -it <instance ID from above command for postgres> bash`
4) Run `psql -U lemmy`
5) Run `\c lemmy`
6) Run `UPDATE local_site SET private_instance = false WHERE 1=1;`
7) `\q` and `exit` to get back to your main system and run `systemctl restart docker`

**Comment by Nutomic** [comment]
This is fixed.
