### ISSUE TITLE
Question: couldnt_find_community but if accessed with full url, it resolves

### ISSUE THREAD

**Issue by snowe2010** [LemmyNet/lemmy#3139]
### Question

One of my admins created the `cpp` community. It worked for a day or two, then suddenly broke. It is no longer resolvable at `https://programming.dev/c/cpp`, but it _is_ resolvable at `https://programming.dev/c/cpp@programming.dev`. I checked the db, and read through the code, but I am not seeing what could be causing this. Is this a known problem? Is there any more information I can provide to help diagnose this?

**Comment by som-cs** [comment]
the thing is search only shows communities know by the instance. There is not 1 place where you can find all lemmy communities. so many times url will resolve but the search won't show it since instance does not have that in their search index.

**Comment by snowe2010** [comment]
@som-cs I'm not talking about search though, I'm talking about just loading the url.

**Comment by som-cs** [comment]
my bad, I misunderstood. Hmm this does seem weird.

**Comment by RocketDerp** [comment]
It could be issue #3099, or some variation. Where it became a 'remote community' even though it was created on your system at first as a 'local community'.  Look at the db difference between local and remote rows.

There have been situations where both user accounts and communities have had their 'local' damaged by a matching 'remote' federation data.

**Comment by FriederHannenheim** [comment]
Can confirm what @RocketDerp suspected. Calling GET on `https://programming.dev/api/v3/community?name=cpp@programming.dev` yields
```json
{
    "community_view": {
        "community": {
            "id": 786,
            "name": "cpp",
            "local": false,
            "instance_id": 1,
        },
}
```
I removed most of the fields for readability

**Comment by snowe2010** [comment]
@RocketDerp @FriederHannenheim thank you very much, you two were correct! Changing the local column from false to true fixed it immediately.
