### ISSUE TITLE
Disable SSL (TLS/STARTTLS) Verifcation on email

### ISSUE THREAD

**Issue by adamboutcher** [LemmyNet/lemmy#3141]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Can't send emails if your certificate doesn't match the domain name.

### Describe the solution you'd like.

An option in the config to disable SSL/TLS/STARTTLS verifcation for emails such as smtp_tlsverify

### Describe alternatives you've considered.

Fixing the certificate would be ideal however due to other bugs (https://github.com/LemmyNet/lemmy/issues/3126 https://github.com/LemmyNet/lemmy/issues/3058) and possibly docker/router NAT reflection issues I cannot send emails.

**Comment by Nutomic** [comment]
You can set `tls_type: none` which is also the default.

**Comment by adamboutcher** [comment]
I believe this just sends in plain text, if SSL/TLS is presented it fails even with SSL/TLS disabled if the certificate doesn't match the system name it expects an option to not verify is required rather than not to use it.
