### ISSUE TITLE
Question: How do I get an RSS feed for Lemmy search results?

### ISSUE THREAD

**Issue by tillcash** [LemmyNet/lemmy#3142]
### Question

I want an RSS feed that only contains results from the Linux communities that have `debian` in the title.

For instance, on Reddit, you can obtain an RSS feed by adding `.rss` before the query in the URL.

Original URL: https://old.reddit.com/r/CrackWatch/search?q=flair%3ARelease+-Daily&restrict_sr=on&include_over_18=on&sort=new&t=all

Feed URL: https://old.reddit.com/r/CrackWatch/search.rss?q=flair%3ARelease+-Daily&restrict_sr=on&include_over_18=on&sort=new&t=all

**Comment by grigio** [comment]
I also need this
