### ISSUE TITLE
[Bug]: GetCommunity sometimes not working with remote communities

### ISSUE THREAD

**Issue by FriederHannenheim** [LemmyNet/lemmy#3144]
### Summary

This is a bug I encountered while searching for new communities on browse.feddit.de. When I clicked on the link and they opened up in Jerbora the app got into a weird state and it didn't show the community. My home instance is lemmy.one but it happens on other instances too. GetCommunity returns
`
{
    "error": "couldnt_find_community"
}
`
A community I've seen this happen with is dresden@feddit.de but there are others.

### Steps to Reproduce

1. Perform a GET request on https://lemmy.one/api/v3/community?name=dresden@feddit.de
2. Try the same with https://feddit.de/api/v3/community?name=dresden@feddit.de and it works
3. This is also not working: https://infosec.pub/api/v3/community?name=dresden@feddit.de

### Version

lemmy.one is on 0.17.3 and infosec.pub is on 0.17.4

**Comment by FriederHannenheim** [comment]
Ok it is a local community. My bad

**Comment by Nutomic** [comment]
Are you logged in when making these requests? Because a community only gets fetched from a remote server if the request is made by an authenticated user.

**Comment by dessalines** [comment]
Stale
