### ISSUE TITLE
Add Security.txt

### ISSUE THREAD

**Issue by rcmaehl** [LemmyNet/lemmy#3147]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Lemmy instances do not have a way to privately report security concerns

### Describe the solution you'd like.

By default, security.txt should point issues with the software itself to the same place the github security.txt does, with the option for instance owners to add their own contact info for any modification / hosting security concerns.

### Describe alternatives you've considered.

Alternatively:

- Have the same security.txt everywhere without the hoster contact info
- Have security.txt 301/308 directly to the github security.txt
- HackerOne?

### Additional context

https://securitytxt.org/
https://en.wikipedia.org/wiki/Security.txt

**Comment by rcmaehl** [comment]
If I can figure out the source code, I'll create a PR for this myself

**Comment by RocketDerp** [comment]
Since this would be a public facing text file, wouldn't you want to add it to the front-end application. lemmy-ui? This project is the API backend application, lemmy-server

**Comment by rcmaehl** [comment]
> Since this would be a public facing text file, wouldn't you want to add it to the front-end application. lemmy-ui? This project is the API backend application, lemmy-server

Possibly. I didn't see an index html/php page on either repo so I wasn't sure if they were generated automatically or if I'm just out of date.

**Comment by tgxn** [comment]
It'd be implemented in a similar wqay robots.txt is.

See:
https://github.com/LemmyNet/lemmy-ui/blob/87613009b8d2d15ae9730bae90f18b8eee61f586/src/server/index.tsx#L25
https://github.com/LemmyNet/lemmy-ui/blob/87613009b8d2d15ae9730bae90f18b8eee61f586/src/server/handlers/robots-handler.ts

Also, not a backend issue.

**Comment by rcmaehl** [comment]
Created https://github.com/LemmyNet/lemmy-ui/pull/1408
