### ISSUE TITLE
Allow Images on Link Posts

### ISSUE THREAD

**Issue by randomletters** [LemmyNet/lemmy#3149]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

I would like an engaging image to appear in the feed along with the link to external content.  This does not appear to be possible, or is not intuitive.  I imagine the comparisons to reddit are tiresome but this is standard and greatly increases engagement with stories (imo, citation needed).

### Describe the solution you'd like.

When creating a post and providing a URL, the interface should scrape the metadata and suggest the "og:image" like it suggests the title.  Currently if you first click the title and then click the image icon, it overrides the URL with the image you upload, creating an image post with the article headline and no link to the article.

### Describe alternatives you've considered.

This functionality could save the image url from the metadata and load it remotely.
It could upload a copy of the image.
It could allow the user to upload an alternate image but still link to the article.

### Additional context

Lemmy is already a site that highlights images in the feed, so this does not seem to be a drastic change of intended functionality.  I have seen the core developers mention that they see the site as more of a text forum than an image site, but the internet has long standardized on providing an image associated with every url for engagement, so I don't think this is an unreasonable feature.  If users don't like image clutter, options to hide images or display modes that downplay them are very desirable whether this feature is implemented or not.

**Comment by randomletters** [comment]
I have noticed that some link posts have images associated with them.  I asked one of the posters how they did it and they said they just posted the link and it happened automatically.  Not sure if this is an interface issue.

**Comment by Nutomic** [comment]
Posts can only have a single link (either to a website or image). You can put embed additional images in the body though.
