### ISSUE TITLE
Hiding read posts should still keep pinned posts visible

### ISSUE THREAD

**Issue by dev-lew** [LemmyNet/lemmy#3155]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

When the show read posts checkbox is deselected, pinned posts are hidden as well as normal posts. 

### Describe the solution you'd like.

I think pinned posts should always be visible. So, when deselecting the check box, all pinned posts should remain visible.

### Describe alternatives you've considered.

It is also possible to enable this requested functionality with a nested checkbox/option eg. "Hide Read Posts" -> "Include pinned posts"

**Comment by Undertakerrip** [comment]
"Hiding read posts" should also hide pinned posts. Users should not be patronized and pinned posts do so. Hiding after a user has already seen the post is obvious if set up that way. I don't see advantages if a user has seen the post.

**Comment by Rebouz** [comment]
in my humble opinion splititng it into two checkboxes could do the trick.
Don't make one option do two things.

**Comment by WayneSheppard** [comment]
Does editing a post reset the "read" flag?

**Comment by dessalines** [comment]
No it shouldn't. I agree with the above that hiding read posts should override pinned.
