### ISSUE TITLE
[Bug]: Row is added in 'person' DB even if application sign up fails - No user notification for this failure

### ISSUE THREAD

**Issue by Security-Chief-Odo** [LemmyNet/lemmy#3156]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

When a user signs up to an instance that requires applications, the user entry is created in the backend `person` DB when submitting, even if there is an error and the application doesn't actually get sent through.

* User signs up with duplicate email
* User gets spinning icon on clicking `Sign up` button

* DB row for the `person` is added
* `local_user` row _is not added_, because it violates the unique constraint for emails
* `registration_application`  row _is not added_, because of the above error

---

The user should be notified of this issue and told to use a different email address. (_I'd suggest not responding the user with any extra information such as the other users information. Though this still causes a security problem with possible email address enumeration_). This results in the user being "in limbo". The admin do not see or receive their application, the user cannot sign-up again using the same email address and neither can they log in. 

The `person` entry (and thus local_user) *should not* be created until after the `registration_application` is *actually* approved, not on user completing it. 

### Steps to Reproduce

1. Sign up on an instance with a different username, but having the *same email address* as another user
2. Check the technical details

### Technical Details

Lemmy shows log errors around this specific sign-up issue with:

```
thread 'actix-rt|system:0|arbiter:12' panicked at 'couldnt create local user: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"local_user_email_key\"")', crates/db_schema/src/impls/local_user.rs:157:8
2023-06-16T---Z ERROR lemmy_server::api_routes_websocket: couldnt_find_object: invalid query
   0: lemmy_apub::fetcher::search::search_query_to_object_id
             at crates/apub/src/fetcher/search.rs:17
   1: lemmy_apub::api::resolve_object::perform
           with self=ResolveObject { q: "<user>", auth: None }
             at crates/apub/src/api/resolve_object.rs:21
   2: lemmy_server::root_span_builder::HTTP request
           with http.method=GET http.scheme="http" http.host=beehaw.org http.target=/api/v3/ws otel.kind="server" request_id=------
             at src/root_span_builder.rs:16
```

User `<user>` exists in the DB:
```
docker exec lemmy_postgres_1 /usr/local/bin/psql -t -q -A -U lemmy -d lemmy -c "SELECT name,id,local from person WHERE person.name ilike '<user>';"
<user>|1234|t
```
User `<user>` web profile shows as existing and a join date:
`https://example.com/u/<user>`

User `1234` _(From first query results)_ **does not** have a corresponding entry in `registration_application`:
```
docker exec lemmy_postgres_1 /usr/local/bin/psql -t -q -A -U lemmy -d lemmy -c "SELECT COUNT(*) from registration_application where local_user_id = 1234;"
0
$ 
```
 

### Version

BE 0.17.4

### Lemmy Instance URL

beehaw.org

**Comment by michalkkkd** [comment]
Is this issue real? We are encouraged to switch from reddit, to app, which can't correctly handle uniq user signup?

**Comment by Security-Chief-Odo** [comment]
Yes this issue is real. Really experienced and troubleshooting to give the above information. That is, a user cannot have multiple usernames assigned to one email; and the lack of notice for such, yet the username is still created whilst a user application is not.

However, I want to explicitly say, Lemmy and instances are not a replacement for Reddit; and shouldn't be expected as such.

**Comment by Nutomic** [comment]
Tested this, its already fixed because the duplicate email check is now done before any data is inserted in db.
