### ISSUE TITLE
[BUG]: Need help with setting 0.17.4v (federation not working)

### ISSUE THREAD

**Issue by life8853** [LemmyNet/lemmy#3162]
So i have used this nginx.conf 
https://github.com/LemmyNet/lemmy/blob/0.17.4/docker/prod/nginx.conf
and it responds with error like
```
lemmy-proxy-1     | 2023/06/17 09:40:01 [emerg] 1#1: "upstream" directive is not allowed here in /etc/nginx/nginx.conf:5
lemmy-proxy-1     | nginx: [emerg] "upstream" directive is not allowed here in /etc/nginx/nginx.conf:5
```
and just restarts.

**Comment by ffolkes** [comment]
What OS are you using?

**Comment by life8853** [comment]
I did from the scratch yes (linux docker, ubuntu to be exact), i think i did manage to set it up but the federation isn't working for me, although during boot it says it should work
