### ISSUE TITLE
Question: deleting cached media to free up space? + object storage?

### ISSUE THREAD

**Issue by finnim** [LemmyNet/lemmy#3163]
### Question

Hello, I wasn't able to find this mentioned anywhere so I thought I might as well ask here:

What's the recommended way of clearing cached media after x amount of days in order to free space? I don't want to accidentally nuke local media

What's the recommended way of attaching object storage to Lemmy so that media can be stored there instead of locally?

Thank you!

**Comment by poVoq** [comment]
Pict-rs 0.4 supports object storage.

But I agree, a better way to clean up images and maybe allow-list the sources from which images are cached is severely needed.

**Comment by finnim** [comment]
I just downloaded a batch of files from my server and found many images from remote communities. What is weird, though is that when I find the corresponding post, it points at a remote url from the instance that originally posted that image. 

Why am I keeping a copy if the image is fetched from the remote server? Is this expected?
Thanks!

**Comment by poVoq** [comment]
See my comment here: https://github.com/LemmyNet/lemmy/issues/2947#issuecomment-1595730459

I was also surprised seeing this happening, but it is somehow inconsistent.

**Comment by ActuallyRuben** [comment]
I might be wrong, but this is the behaviour I've observed: If the image is uploaded to and hosted by a lemmy instance, then the image doesn't get cached. If the image is hosted by another source, such as imgur or discord, then the image gets cached by your instance.

**Comment by finnim** [comment]
> 



> I might be wrong, but this is the behaviour I've observed: If the image is uploaded to and hosted by a lemmy instance, then the image doesn't get cached. If the image is hosted by another source, such as imgur or discord, then the image gets cached by your instance.

I've found this image in my cache and the only reference I can find is this post:
https://lemmy.ml/post/1130919

But the image here is hosted on lemmy.ml?
Weird.

Another example I just found:
https://lemmy.ml/post/708995

These are all stored on my server but also on lemmy.ml apparently.

@poVoq thank you! I'm sure it'll be fixed at some point.
In the mean time do you know of the best way to use s3 object storage without having to updgrade to pict-rs-4.0 which isn't still out yet? (Only RCs are available). 

I could create a mountpoint a {installpath}/volumes/pictures but I'm afraid that either permissions will be wrong or that docker will have problems trying to mount to the same location.

If anyone knows the best way to do this, please let me know. Thank you <3

**Comment by poVoq** [comment]
Sorry, I don't know other than Pict-rs 0.4, but quite a lot of people are running the 0.4-rc3 already in production and it seems to work fine. I also upgraded yesterday to it and no problems so far, other than that the ENV variables all changed and the readme is outdated. I am not using object storage however.

**Comment by sunaurus** [comment]
Hey, I hope you figured out your problems already, but if not, I suggest posting in !lemmy_support@lemmy.ml for further support.
