### ISSUE TITLE
[Bug]: Can't have custom themes whose names are longer than 20 characters

### ISSUE THREAD

**Issue by n3oney** [LemmyNet/lemmy#3166]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

When you create a custom theme with a name longer than 20 characters, you can't save it to your settings, because the DB type is `varying(20)`.

I'm currently trying to port Catppuccin to Lemmy, and that theme has 4 variants, and each of those has 14 colors - 56 CSS files.
I've named each of those `catppuccin-${variant}-${color}.css`, and it's just too long.

Even excluding "catppuccin" from the name, the longest you would get is `macchiato-rosewater.css`, which is 19 characters excluding the extension. And it doesn't include any information that it's from catppuccin!

### Steps to Reproduce

1. Create a theme longer than 20 characters
2. Try to set it in your instance defaults or user settings
3. It fails, because it's too long

### Technical Details

```
Jun 17 14:21:56 cryn lemmy_server[92079]: 2023-06-17T12:21:56.244962Z ERROR HTTP request{http.method=GET http.scheme="https" http.host=lemmy.neoney.dev http.target=/api/v3/ws otel.kind="server" request_id=e0460f91-b1d1-4591-bfc6-744881b5d34a http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: user_already_exists: value too long for type character varying(20)
Jun 17 14:21:56 cryn lemmy_server[92079]:    0: lemmy_api::local_user::save_settings::perform
Jun 17 14:21:56 cryn lemmy_server[92079]:            with self=SaveUserSettings { show_nsfw: Some(true), show_scores: Some(true), theme: Some("catppuccin-macchiato-lavender"), default_sort_type: Some(1), default_listing_type: Some(2), interface_language: Some("en"), avatar: Some("https://lemmy.neoney.dev/pictrs/image/8ea93dc3-c89d-4948-acad-65d442a5c472.png"), banner: Some("https://lemmy.neoney.dev/pictrs/image/507789d0-9c19-4377-8b9e-2b06eb879471.webp"), display_name: None, email: Some(Sensitive), bio: Some("[neoney.dev](https://neoney.dev)\n\nPGP 0x1261173A01E10298"), matrix_user_id: Some("@neoney:matrix.org"), show_avatars: Some(true), send_notifications_to_email: Some(false), bot_account: Some(false), show_bot_accounts: Some(true), show_read_posts: Some(true), show_new_post_notifs: Some(false), discussion_languages: Some([LanguageId(0), LanguageId(37), LanguageId(128)]), auth: Sensitive }
Jun 17 14:21:56 cryn lemmy_server[92079]:              at crates/api/src/local_user/save_settings.rs:29
Jun 17 14:21:56 cryn lemmy_server[92079]:    1: lemmy_server::root_span_builder::HTTP request
Jun 17 14:21:56 cryn lemmy_server[92079]:            with http.method=GET http.scheme="https" http.host=lemmy.neoney.dev http.target=/api/v3/ws otel.kind="server" request_id=e0460f91-b1d1-4591-bfc6-744881b5d34a http.status_code=101 otel.status_code="OK"
Jun 17 14:21:56 cryn lemmy_server[92079]:              at src/root_span_builder.rs:16
```

### Version

0.17.4

### Lemmy Instance URL

lemmy.neoney.dev

**Comment by scme0** [comment]
I took a quick look and it turns out the `default_theme` column in the `local_site` table has type `text` so I've created a PR to update the `local_user` table's `theme` column to use the same type. From my quick test it seems to work as expected.
