### ISSUE TITLE
[Bug]: Backend sign-up bugs — No error messages for duplicate keys

### ISSUE THREAD

**Issue by xximj** [LemmyNet/lemmy#3169]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.

### Summary

I was able to reproduce some back-end bugs while testing the sign-up process in lemmy-ui.  
So for lemmy-ui I made a comment on https://github.com/LemmyNet/lemmy-ui/issues/1151

For lemmy back-end :

- When a username is already in use, it returns a "502 Bad Gateway" error. The Lemmy log shows the following error message:
`thread 'actix-rt|system:0|arbiter:5' panicked at 'couldn't create local user: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"local_user_person_id_key\"")', crates/db_schema/src/impls/local_user.rs:157:8`

-  Similarly, if an email is already in use, it also returns a "502 Bad Gateway" error. The Lemmy log displays the following error message:
`thread 'actix-rt|system:0|arbiter:4' panicked at 'couldn't create local user: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"local_user_email_key\"")', crates/db_schema/src/impls/local_user.rs:157:8`

Expected Behavior: Lemmy should provide an error message when username is already taken or email is registered.

### Steps to Reproduce

1. Attempt to sign up with a username that is already registered.
2. Try signing up with an email address that is already associated with an existing account.

### Technical Details

BE : 0.17.4
UI : 0.17.4

### Version

0.17.4

**Comment by RocketDerp** [comment]
see also: issue #3156

**Comment by Jeremy-Code-F** [comment]
I'd like to take a shot at this.

Seems like it'd be as simple as returning a [409](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409) when the unique violation happens for emails

Then the frontend could display a nicer message to the user

**Comment by RocketDerp** [comment]
What is the status of this bug? 0.18 is in release-candidate testing and I think these login and Sign Up issues need attention. Thank you

**Comment by Jeremy-Code-F** [comment]
Seems like it is fixed in https://github.com/LemmyNet/lemmy/pull/3093

**Comment by xximj** [comment]
Yup, the backend errors have been fixed. But I haven't got a chance to test the front end, so I can't say for sure if that's resolved too.

I'll go ahead and close the issue now. Thanks for the great work!
