### ISSUE TITLE
[Bug]: New posts get added to top of sorts by `Top`/`Hot`

### ISSUE THREAD

**Issue by zig1000** [LemmyNet/lemmy#3170]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Observed on lemmy.world, both in All and Local mode, and both when sorting by Top Day, Hot, etc.

The sort will initially work as expected but any posts created after the sort was initiated will start to show up and fill the top of the feed. Thus this effect can be observed faster if you switch to `All` instances mode.

### Steps to Reproduce

1. Go to any instance or All home feed with a non-new sort, e.g.
    https://lemmy.world/home/data_type/Post/listing_type/All/sort/TopDay/page/1
2. Wait for a few seconds. New posts will eventually start filling the top of the feed, bypassing the sort.

### Technical Details

I assume this is a backend not a UI issue.

### Version

0.17.4

### Lemmy Instance URL

lemmy.world

**Comment by RocketDerp** [comment]
This is a 'ui / front-end issue', it belongs on https://github.com/LemmyNet/lemmy-ui

It is also a well known issue and generally described as version 0.18 removal of the websockets API interface.
