### ISSUE TITLE
[Bug]: ActivityPub user outbox returns no items

### ISSUE THREAD

**Issue by markcellus** [LemmyNet/lemmy#3171]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

I was checking out the different ActivityPub endpoints that Lemmy provides. And while not using specifically, I noticed that the [outbox for users](https://join-lemmy.org/docs/en/contributors/05-federation.html#user) doesn't return any items. 

### Steps to Reproduce

1. `GET` the outbox AP endpoint of any user who has posted content with `Accept` header set to `application/ld+json` 
2. Verify there are no returned items

### Technical Details

N/A

### Version

0.17.4

**Comment by Nutomic** [comment]
Not a bug, the user outbox is only implemented as an empty placehoder for now.

**Comment by markcellus** [comment]
The idea behind AP is to allow a user's content to be followed from other fediverse apps. If there's content to follow, but it's not included in an outbox, that definitely seems like a bug imo. [Lemmy's API page for the User](https://join-lemmy.org/docs/contributors/05-federation.html#user) says the User actor "Can be followed from other platforms". That's technically not true if the user's content doesn't appear in its outbox.

Whether this is classified as a bug or a feature, at the very least the API page should be clear about this being expected behavior. So if it's a placeholder, it would be great if that's communicated on the docs.

**Comment by Nutomic** [comment]
You can follow the user just fine by sending a Follow activity, the outbox is unrelated to that.

**Comment by markcellus** [comment]
Not sure what you mean, I realize you can send Follow activity. Are you saying a Follow request is required to see a user's public posts? [5.1 Outbox of the AP spec](https://www.w3.org/TR/activitypub/#outbox) says (emphasis mine):

> The outbox stream contains activities the user has published, subject to the ability of the requestor to retrieve the activity (that is, the contents of the outbox are filtered by the permissions of the person reading it). **If a user submits a request without Authorization the server should respond with all of the Public posts**.

Fediverse apps shouldn't have to send a Follow request to see a user's public posts.

**Comment by Nutomic** [comment]
It says **should**, not **must**. So Lemmy is in compliance with the spec as long as outbox is an OrderedCollection.

**Comment by markcellus** [comment]
My organization will just fork the repository and use it from there. The whole idea behind the fediverse is to make fedi apps compatible with one another. There's no way apps can work if we have applications that refuse to integrate.

**Comment by YamiOdymel** [comment]
My ActivityPub software is trying to backfill posts from Lemmy because the remote user was just created locally (*because someone searched for it*), but the outbox Lemmy returns is empty.

So users have to follow the account first, and only then will Lemmy send me updates. But how would anyone even be interested in following an empty account? How... is this a feature?

_EDIT: Remote user = actor. Sorry for the confusion. This means it’s probably a User or a Group Actor._

**Comment by dessalines** [comment]
Lemmy is made to follow communities, not users. Its not a microblogging platform.

**Comment by Nutomic** [comment]
You are welcome to make a pull request which changes the behaviour. Its just not a priority for us.
