### ISSUE TITLE
[Bug]: Images fail to load after upgrading to v0.17.4

### ISSUE THREAD

**Issue by corgana** [LemmyNet/lemmy#3173]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

I updated http://startrek.website to 0.17.4 and now our images (all) aren't showing. Attempting to _upload_ an image (banner, avatar, etc) gives the error: 

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

In a big red banner on the lower-left of the screen.

This is an ansible-install with nothing else on the system.

Images not hosted on startrek.website (thumbnails and avatars of users on other instances) appear to load fine

### Steps to Reproduce

1. Log in to startrek.website
2. Attempt to set an avatar in profile settings

### Technical Details

Ubuntu 23.04

[lemmy_log.zip](https://github.com/LemmyNet/lemmy/files/11779815/lemmy_log.zip)

### Version

0.17.4

### Lemmy Instance URL

startrek.website

**Comment by glitchbirdnew** [comment]
the same issue with my instance. i cant upload avatar nor banner.

**Comment by peterklipfel** [comment]
To add a bit more context here. I'm seeing this issue locally with the following behavior:

## Request:

### Headers

```
POST /pictrs/image HTTP/1.1
Host: localhost:3003
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: multipart/form-data; boundary=---------------------------395216730326577154161342808613
Content-Length: 256064
Origin: http://localhost:3003
Connection: keep-alive
Referer: http://localhost:3003/admin
Cookie: BetterErrors-2.10.1-CSRF-Token=<token>; BetterErrors-has-used-console=true; _mastodon_session=<session_cookie>; _session_id=<id>; jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6ImxlbW15LWFscGhhIiwiaWF0IjoxNjg3MDQzODU3fQ.2jUMMqaxkj3iuI6v5dziz1RrD-dquhYhCWIqlRm1V3U
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
```

### Payload

<the image>

## Response:

### Headers
```
HTTP/1.1 400 Bad Request
Server: nginx/1.18.0 (Ubuntu)
Date: Sat, 17 Jun 2023 23:27:54 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 153
Connection: keep-alive
access-control-allow-credentials: true
access-control-allow-origin: http://localhost:3003
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
access-control-expose-headers: access-control-allow-origin, content-type
```

### Payload: 
```
Request error: error sending request for url (http://localhost:8080/image): error trying to connect: tcp connect error: Connection refused (os error 111)
```

**Comment by jakejack13** [comment]
For more context, the `lemmy-ui` console displays the backtrace

`Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/Users/jakejack/Documents/open/lemmy/lemmy-ui/node_modules/send/index.js:386:13)
    at SendStream.send (/Users/jakejack/Documents/open/lemmy/lemmy-ui/node_modules/send/index.js:613:10)
    at onstat (/Users/jakejack/Documents/open/lemmy/lemmy-ui/node_modules/send/index.js:725:10)
    at FSReqCallback.oncomplete (node:fs:199:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/Users/jakejack/Documents/open/lemmy/lemmy-ui/node_modules/send/index.js:386:13)
    at SendStream.send (/Users/jakejack/Documents/open/lemmy/lemmy-ui/node_modules/send/index.js:613:10)
    at onstat (/Users/jakejack/Documents/open/lemmy/lemmy-ui/node_modules/send/index.js:725:10)
    at FSReqCallback.oncomplete (node:fs:199:5)`

and the `lemmy` console displays the error message

`thread 'actix-rt|system:0|arbiter:18' panicked at 'No auth header for picture upload', crates/routes/src/images.rs:97:6`

**Comment by glitchbirdnew** [comment]
> ### Requirements
> 
>     * [x]  Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
> 
>     * [x]  Did you check to see if this issue already exists?
> 
>     * [x]  Is this only a single bug? Do not put multiple bugs in one issue.
> 
>     * [ ]  Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.
> 
> 
> ### Summary
> 
> I updated http://startrek.website to 0.17.4 and now our images (all) aren't showing. Attempting to _upload_ an image (banner, avatar, etc) gives the error:
> 
> `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
> 
> In a big red banner on the lower-left of the screen.
> 
> This is an ansible-install with nothing else on the system.
> 
> Images not hosted on startrek.website (thumbnails and avatars of users on other instances) appear to load fine
> ### Steps to Reproduce
> 
>     1. Log in to startrek.website
> 
>     2. Attempt to set an avatar in profile settings
> 
> 
> ### Technical Details
> 
> Ubuntu 23.04
> 
> [lemmy_log.zip](https://github.com/LemmyNet/lemmy/files/11779815/lemmy_log.zip)
> ### Version
> 
> 0.17.4
> ### Lemmy Instance URL
> 
> startrek.website
i resolved the issue on my server.  check config.hjson 

 Address where pictrs is available (for image hosting)
    i changed url: "http://**localhost**:8080/" to url: "http://**pictrs**:8080/"

**Comment by corgana** [comment]
>I resolved the issue on my server. check config.hjson

Where is this file for a default ansible install? I have lemmy.hjson in /srv/lemmy/startrek.website but it already has the pictrs URL correct

**Comment by Kap2022** [comment]
> Where is this file for a default ansible install? I have a lemmy.hjson in /srv/lemmy/startrek.website but it already has the pictrs URL correct.

Same here - I have the same problem and that line already has pictrs in it

**Comment by corgana** [comment]
> > > I resolved the issue on my server. check config.hjson
> > 
> > 
> > Where is this file for a default ansible install? I have a _lemmy.hjson_ in /srv/lemmy/startrek.website but it already has the pictrs URL correct.
> 
> to be honest with you, this is the first time I've used Ansible, and apart from /srv/lemmy/fedit.io, I don't know where the other folders are. I changed the code in lemmy-ansible/inventory/host_vars/fedit.io nano config.hjson. on my server this fixed the error. So i did it via ansible (ansible-playbook -i inventory/hosts lemmy.yml --become) from my laptop.

Ah ok, thanks for clarifying, this is new to me too. My config.hjson in Lemmy-ansible/inventory/host_vars/ unfortunately already says pictrs. 

Here's hoping someone else notices and can help me out.

**Comment by corgana** [comment]
> What logs does pict-rs print when it's restarting

Thanks for the response, it's just 

```
Caused by:
    Read corrupted data at file offset None backtrace ()
2023-06-20T15:10:40.204807Z  WARN sled::pagecache::snapshot: empty/corrupt snapshot file found    
2023-06-20T15:10:40.205140Z  WARN sled::pagecache::snapshot: empty/corrupt snapshot file found    
Error: Error in DB, Read corrupted data at file offset None backtrace ()
```

Over and over

**Comment by asonix** [comment]
I've seen that issue before. It normally happens when the drive fills up and pict-rs crashes while trying to write more to the database. Can you look for a few things:
- Is your drive full? (if yes, please get more disk)
- In the pict-rs volume, in the sled or sled-repo folder, are there files that contain `.snap` in the name that are zero-sized? If yes, delete them.

**Comment by RyantHults** [comment]
I am also seeing this on my instance running 0.17.4, but I do not see any 0-byte files/files with snap in the name, and my drive is not full.
