### ISSUE TITLE
[Bug]: Mod-Deletion/Restoration of comment not federated, then making a new comment can result in a duplicate id

### ISSUE THREAD

**Issue by Christoph-Wagner** [LemmyNet/lemmy#3174]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

This is a bit complicated, and I’m not 100% if this is a single bug. 
A comment of mine got deleted, then restored. Then my next two comments had the same id.

### Steps to Reproduce

Unsure

### Technical Details

[This comment](https://beehaw.org/comment/314431) was deleted by a mod (probably accidentally) and almost instantly restored. 

The deletion did, but the restoration did not federate to my instance (this might be the extra bug, but I don’t know for sure, might also be a server hiccup). In any way, I was the person to write the next two posts from my instance:

* https://discuss.tchncs.de/comment/226788
* https://beehaw.org/comment/314354

On both instances, these are the links of two different comments.  
The first one starting with

> I wish I could continue

and the second:

> This is a test comment for a mod to please delete and then restore ;)

![image](https://github.com/LemmyNet/lemmy/assets/1609329/278e5396-62fa-46f8-a94e-87ef660fa86e)

### Version

BE: 0.17.4

### Lemmy Instance URL

https://discuss.tchncs.de

**Comment by Nutomic** [comment]
Deletions dont change comment ids. I dont understand the rest of your issue. If it can still be reproduced, do explain it more clearly.

**Comment by Christoph-Wagner** [comment]
Simplified: 2 different comments have the same ID. If that’s expected behavior, then I guess this whole issue is moot.

**Comment by Nutomic** [comment]
Thats impossible because the id is a postgres primary key so it would be rejected on insert. Unless you are talking about ids on different instances, where ids can of course be duplicated.

**Comment by Christoph-Wagner** [comment]
Looking at it again, I just assumed the link button links to a specific comment in normal cases. But apparently it does not, but instead sometimes to the parent, making this an UX issue. Sorry about that.
