### ISSUE TITLE
Moderator only discussions

### ISSUE THREAD

**Issue by ftatateeta** [LemmyNet/lemmy#3178]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

There is an ask to improve the moderation experience to allow admin and mods to talk to each other privately.

### Describe the solution you'd like.

from this discussion 
https://lemmygrad.ml/comment/511863

I don’t have a github account 😔 but in the simplest way I can think of, it would essentially be DMs with multiple parties. Maybe in a different page than the inbox (bell icon). There could be a button or link in the sidebars to message the mods of a community or the admins of the instance, and the DM would be sent out to the whole team. Then when someone replies to the DM it sends the reply to everyone in the group.

Being able to mark them as resolved would also be useful, and would mark the DMs as read to everyone in the convo and maybe even add a [resolved] mention somewhere on the DMs.

That way it could be asynchronous and essentially send the DM X times in one click, once to each participant.

### Describe alternatives you've considered.

Maybe we can use communities for this, i.e. have a private hidden community for each community that's only visible to the mods of that community and admins. Reported post becomes a post in this community and mods can figure out what to do with it in the comments. Mods can have other discussions in it.

### Additional context

Also I know the devs must be overloaded right now so I can help with this.

**Comment by noenfugler** [comment]
I support this enhancement.  Need to chat to fellow mods in a private forum.

**Comment by kartikynwa** [comment]
This is like how Reddit has modmail right?

**Comment by boehs** [comment]
> This is like how Reddit has modmail right?

No, this proposal is to allow mods to cord with each other. We've just began using matrix as a mod team, which works well so far

**Comment by DraconicNEO** [comment]
Yeah I think this would be a great idea, like how Reddit has modmail, it could also be a way for users to message the modteam of a specific community, or even the admins of an Instance, currently you have to DM each one of them specifically and that's not ideal since if only one of them is active or online it could take longer or you'll have to DM multiple people at once, with this system you could send a message to the community or the Instance admins and they'll all receive and have access to the same message.

**Comment by dessalines** [comment]
We don't want to recreate private group chats in lemmy when other platforms like matrix already do that much better.
