### ISSUE TITLE
[Bug]: Unable to start lemmy_server after installation from scratch

### ISSUE THREAD

**Issue by chofstede** [LemmyNet/lemmy#3180]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

After installing lemmy, according to the documentation at https://join-lemmy.org/docs/en/administration/from_scratch.html , I can´t start the application.

It always fails with the following error message:
```
2023-06-18T12:34:10.859283Z  INFO lemmy_db_schema::utils: Running Database migrations (This may take a long time)...
thread 'main' panicked at 'Couldn't run DB Migrations', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lemmy_db_schema-0.17.4/src/utils.rs:165:25
```

I can see database tables are created inside the postgre database. Unfortunately I couldn't find a way to get more detailed troubleshooting information out of it. The backtrace seems not pretty helpful: 

`lemmy@lemmy:~$ RUST_BACKTRACE=full PICTRS_PATH=/var/lib/pictrs PICTRS_ADDR=127.0.0.1:8080 LEMMY_CONFIG_LOCATION=/etc/lemmy/lemmy.hjson /usr/bin/lemmy_server -vvv
2023-06-18T12:34:10.859283Z  INFO lemmy_db_schema::utils: Running Database migrations (This may take a long time)...
thread 'main' panicked at 'Couldn't run DB Migrations', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lemmy_db_schema-0.17.4/src/utils.rs:165:25
stack backtrace:
   0:     0xaaaaec16be78 - <unknown>
   1:     0xaaaaea632788 - <unknown>
   2:     0xaaaaec1685ac - <unknown>
   3:     0xaaaaec16bc8c - <unknown>
   4:     0xaaaaec16e388 - <unknown>
   5:     0xaaaaec16d158 - <unknown>
   6:     0xaaaaec16e834 - <unknown>
   7:     0xaaaaec16e704 - <unknown>
   8:     0xaaaaec16c310 - <unknown>
   9:     0xaaaaec16e4f8 - <unknown>
  10:     0xaaaaea3d67b8 - <unknown>
  11:     0xaaaaeb4334b0 - <unknown>
  12:     0xaaaaeb968410 - <unknown>
  13:     0xaaaaeb988950 - <unknown>
  14:     0xaaaaebc10f18 - <unknown>
  15:     0xaaaaeb85b688 - <unknown>
  16:     0xaaaaebaa47d4 - <unknown>
  17:     0xaaaaeb85b18c - <unknown>
  18:     0xaaaaeb817810 - <unknown>
  19:     0xaaaaeba2ef0c - <unknown>
  20:     0xaaaaeb987ec8 - <unknown>
  21:     0xaaaaebbd0144 - <unknown>
  22:     0xaaaaec1612cc - <unknown>
  23:     0xaaaaeba2ef70 - <unknown>
  24:     0xffffb57073fc - <unknown>
  25:     0xffffb57074cc - __libc_start_main
  26:     0xaaaaea42eff0 - <unknown>
  27:                0x0 - <unknown>
`

### Steps to Reproduce

1. Install lemmy by cargo install lemmy_server --root /usr/ --locked --features embed-pictrs
2. Starting lemmy with RUST_BACKTRACE=full PICTRS_PATH=/var/lib/pictrs PICTRS_ADDR=127.0.0.1:8080 LEMMY_CONFIG_LOCATION=/etc/lemmy/lemmy.hjson /usr/bin/lemmy_server

### Technical Details

I try to install lemmy on a fully up to date Ubuntu 22.04 from scratch on an ARM based server (AMPERE ALTRA CPUs) without containerization. 

### Version

0.17.4

**Comment by xximj** [comment]
Fix is not released yet. But there's a workaround, check this out:

https://github.com/LemmyNet/lemmy-docs/issues/201

**Comment by chofstede** [comment]
Thank you! It worked!
