### ISSUE TITLE
Let moderators pin comments to the top

### ISSUE THREAD

**Issue by kekkoudesu** [LemmyNet/lemmy#3182]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

It's useful to pin comments for the same reasons it's useful to pin posts (to increase visibility). Some scenarios:

1. The comment is very high-value in some way that's useful to every user who sees the post
2. The subject of a post (say, the writer of the article) sees the post and writes a comment to add context or clarification. Most users would find this useful.

### Describe the solution you'd like.

An option to pin the comment to the top of the comments thread. Add an icon that indicates the post has been featured by a moderator/admin. It would be useful to pin multiple comments.

### Describe alternatives you've considered.

If a comment is greatly upvoted, it will rise to the top. However, comments that should be visible are not necessarily comments that get upvoted.

**Comment by kekkoudesu** [comment]
Whoops...I guess this qualifies as a frontend/UI issue. Closing and re-opening on lemmy-ui.

**Comment by krestenlaust** [comment]
@kekkoudesu can you try to close this as wontfix instead? There's a dropdown when pressing close :)

**Comment by kekkoudesu** [comment]
Closing as wontfix.
