### ISSUE TITLE
[Bug]: Contributing guidelines links are no longer available

### ISSUE THREAD

**Issue by ismailghedamsi** [LemmyNet/lemmy#3184]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Contributing guidelines links are no longer available

### Steps to Reproduce

1. Click on Contributing instructions, Docker Development or Local Development

2 - An 502 Bad Gateway error is shown

### Technical Details

No details

### Version

N/A

**Comment by Nutomic** [comment]
These are fixed.
