### ISSUE TITLE
[Bug]: Certain links take very long to submit

### ISSUE THREAD

**Issue by sacerdoted** [LemmyNet/lemmy#3194]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Certain links take tens of minutes to submit, if they succeed at all

### Steps to Reproduce

1. Submit this link: https://www.washingtonpost.com/business/2023/06/18/foes-inflation-reduction-act-race-repeal-climate-drug-pricing-programs/?pwapi_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJpZCI6IjE3NDgxNDQ5IiwicmVhc29uIjoiZ2lmdCIsIm5iZiI6MTY4NzA2MDgwMCwiaXNzIjoic3Vic2NyaXB0aW9ucyIsImV4cCI6MTY4ODM1Njc5OSwiaWF0IjoxNjg3MDYwODAwLCJqdGkiOiJmOGZiYmIxZC0xN2MwLTQ1YmEtYThlNy02ZjNmZWM4ZTU4ZjciLCJ1cmwiOiJodHRwczovL3d3dy53YXNoaW5ndG9ucG9zdC5jb20vYnVzaW5lc3MvMjAyMy8wNi8xOC9mb2VzLWluZmxhdGlvbi1yZWR1Y3Rpb24tYWN0LXJhY2UtcmVwZWFsLWNsaW1hdGUtZHJ1Zy1wcmljaW5nLXByb2dyYW1zLyJ9.n0KkXwJZ3cP8pGG-gtOJQFryg0RJQE3pH9uNQrVzcMI
2. Observe that the submission spinner does not complete for 20+ minutes 
3.

### Technical Details

Using firefox on windows or android

### Version

BE: 0.17.4

**Comment by daviessm** [comment]
Which Lemmy instance are you using and what community are you posting to?

**Comment by sacerdoted** [comment]
slrpnk.net/c/climate

This is not a large community, and the long-time-to-post thing mainly happens with Washington Post links.

**Comment by sacerdoted** [comment]
Another link with the same problem: https://www.washingtonpost.com/weather/interactive/2023/heat-extremes-china-mexico-texas-india/

**Comment by sacerdoted** [comment]
Another one https://www.nytimes.com/2023/07/18/climate/al-gore-on-extreme-heat-and-the-fight-against-fossil-fuels.html?unlocked_article_code=fAcve1lwiH3CuvDVSdrz-qUK_7M-_Fn3UA1pkV9hsnyERcJMcjHc_le0iEWbxpGyhZg7wmk1KJ4FtyFes1FP0P1CfooNTE7reTU0Feahqox4IrL8ZZNYlLacG1CyhcyfMV3BPsXlPJGMv9p3Kw5uz25FExCAVPmhnbWbGkx7PbeDZ0gls98cLc2yrc6kQ-Ki_7QWzqV1AiuN3UbrmbIQffz7EoNekjpYxUcCVigcRY7iIDLYKglikOTMt17ykTqOD9HJXTKwTO5TNjX2pJSLROqGhfd1Tgi7R-KRNbdAi6TCAJ-O3ebUbRF3AzXMB1zfZqSl_U5RUH9Vdz-7EYyy1GBUBqyPICoGGx3Fu-YaBSoW4JRUqG3_hlSiKky-qvF4j5t_QQ

**Comment by dessalines** [comment]
Not much we can do about that other than reduce our timeout.
