### ISSUE TITLE
Question: Can we use object storage on instances?

### ISSUE THREAD

**Issue by xaegreal** [LemmyNet/lemmy#3195]
### Question

I am the admin of lemmynsfw.com. We currently allow media uploads on the instance. The downside is that the disk fills up quickly. Looks like Pict-rs has S3 uploads feature. Can we use it? If yes, how? If no, will we be able to use it in the future?

I'm opening this issue because I couldn't find any official explanation.

**Comment by sunaurus** [comment]
You can use the `pictrs` configuration block to tell Lemmy where your pict-rs server is:

https://github.com/LemmyNet/lemmy/blob/d97ff65fe1e9c31e9f7c977a66100816816e07be/config/defaults.hjson#L41

Setting up pict-rs with object storage is possible, you should be able to do it by just following their readme: https://git.asonix.dog/asonix/pict-rs/

**Comment by xaegreal** [comment]
> You can use the `pictrs` configuration block to tell Lemmy where your pict-rs server is:
> 
> https://github.com/LemmyNet/lemmy/blob/d97ff65fe1e9c31e9f7c977a66100816816e07be/config/defaults.hjson#L41
> 
> Setting up pict-rs with object storage is possible (may instances are doing so already), you should be able to do it by just following their readme: https://git.asonix.dog/asonix/pict-rs/

Are we sure Lemmy will work the same on object storage as it does locally? I can't be sure as I don't know how the integration between Lemmy and pict-rs works. Also Ansible instructions uses an old version of pict-rs.

**Comment by asonix** [comment]
Hi, pict-rs developer here. The goal with pict-rs is that whatever application is using pict-rs (lemmy here) doesn't need to know or care about how images are stored. As mentioned here, some folks have been migrating to object-storage and having success. I would recommend updating pict-rs to `0.4.0-rc.5` (latest at the time of writing) before migrating to object-storage.

**Comment by asonix** [comment]
Answered this via email, but posting here as well: pict-rs will always proxy requests for files regardless of which storage backend is in use. This is expected behavior
