### ISSUE TITLE
Editing community settings as a moderator from another instance breaks the local URL

### ISSUE THREAD

**Issue by obosob** [LemmyNet/lemmy#3198]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Editing the description or other settings, such as banner or avatar, of a community on another instance causes the local URL to give a 404 error. 

This appears to be because the `local` field in the `community` table gets set to false as a result of this action. See this description of the issue and how to restore the functionality: https://lemmy.dbzer0.com/post/68260

E.g. 

Say you have a lemmy instance on `lemmy1.com` and another on lemmy2.com and there is a community on `lemmy1.com` called `foo` and a user on `lemmy2.com` called `bar` who is a moderator of `!foo@lemmy1.com`.

If `bar@lemmy2.com` navigates to `https://lemmy2.com/c/foo@lemmy1.com` and edits the description, `https://lemmy1.com/c/foo` henceforth responds with "404: couldnt_find_community" 

### Steps to Reproduce

1. Create a community on one instance, add a moderator as a user from another instance
2. Have that user edit the community description 
3. Visit local community URL, observe 404

### Technical Details

Refer to https://lemmy.dbzer0.com/post/68260

### Version

BE 0.17.4

**Comment by Neshura87** [comment]
Bug should already be addressed in [3088](https://github.com/LemmyNet/lemmy/pull/3088)
