### ISSUE TITLE
Bring back Captcha

### ISSUE THREAD

**Issue by ruudschilders** [LemmyNet/lemmy#3200]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

We just had a spam wave. I enabled captcha to prevent the automated spam signups.
Has helped on mastodon as well.

The spam accounts didn't get verified, but they caused the e-mail to be blocked for this domain, because they used non-existent Gmail addresses. That's why the captcha would be a gooed extra step.

(Account approvals aren't useful with a few thousand new accounts per day.)

### Describe the solution you'd like.

Bring back captcha. 

### Describe alternatives you've considered.

Mail verification doesn't always work, and in this case it got my mail for the domain blocked.
Approvals are too much work for a big server

### Additional context

No

**Comment by sunaurus** [comment]
Related to #2922

**Comment by RGBok** [comment]
Cannot stress this enough. captchas saved my server just now from getting spammed. I had over 800 spam signups overnight and after I enabled captcha it stopped. whoever is doing this is an amateur that can't use captcha bypassing bots but that's the purpose of captcha in my opinion, to mitigate spam from at least some bad actors. Of course it won't stop the more experienced spammers with captcha bypassing bots but it should be kept.

**Comment by dessalines** [comment]
See #2922 , captchas will not stop those signup bots, we know from experience, because someone has written a signup bot that can bypass them. You need to turn on registration IP rate-limiting.

**Comment by ruudschilders** [comment]
But they are all from different IPs. So IP-ratelimiting wouldn't work.
I know captcha's don't keep all out. But they keep out a fair deal. So what's the downside to keeping it in?

**Comment by ctsrc** [comment]
Two days ago I had 6 users on my instance. Today I have 669. I don't even need to look at any logs to tell that this is obviously a whole bunch of bot users that have been created.

Captcha is necessary in order to fend off these bots. 

If we don't, the spam bots will kill Lemmy just like spam bots killed Usenet discussions years ago.

**Comment by maltfield** [comment]
See also this feature request to implement hashcash as a better alternative to CAPTCHAs

 * https://github.com/LemmyNet/lemmy/issues/3204

**Comment by sunaurus** [comment]
Seems the current bot wave is increasing quickly, and mostly on instances with captchas disabled. So it seems that the captcha is definitely acting as a deterrent in the current wave.

**Comment by th3raid0r** [comment]
I'm really not liking the Lemmy Devs pushing back on the community so hard here. I assure you, the quickest way to get a fork of the project will be to anger everyone who runs an instance because your opinion on security has a measurable impact on our time.

This is my comment in support of this feature, but it's also a rallying cry if y'all choose not to return the feature leaving us admins only with options like Cloudflare and Imperva to protect the fediverse from spam. 

If this feature is not returned, I commit to forking this project, reverting the change myself, and getting it to other concerned instance admins.

**Comment by maltfield** [comment]
@th3raid0r the devs have already supported the idea of adding hashcash support, which is a better alternative to CAPTCHAs (both mathematically and heuristically).

Instead of forking, why not just submit a PR? They [said they'll accept it](https://github.com/LemmyNet/lemmy/issues/3204#issuecomment-1598534358).

**Comment by SteveDinn** [comment]
According to one admin, most of the wave of recent new users has been spam accounts:
https://geddit.social/post/25346

**Comment by cloventt** [comment]
Re: a comment in #2922 :

> Unfortunately captchas don't stop those signup bots either.

Not so sure about this... our instance got hit with a huge pile-on of bot-accounts yesterday, and enabling the CAPTCHA instantly stopped the influx.

I +1 implementing something privacy-protecting like HashCash or mCAPTCHA as options. But in the meantime I think removing the existing solution was probably premature.

**Comment by TOoSmOotH** [comment]
Just to pile on here we had a bunch of bots registering today and enabling captcha put a stop to them as well. I honestly think that this should stay in until a better solution is in place. It's not perfect but it is better than nothing even if its not the ideal solution. This will buy some time until something else is out there.

**Comment by Nutomic** [comment]
Based on this feedback I agree that captchas should be restored. They are far from perfect, but its still better than allowing account creation with a simple POST request. There are other options but captcha is already supported in lemmy-ui, and will be faster to reimplement. 

If someone could write the code it would be very helpful, as we barely have time for that anymore. You can checkout the tag `0.17.4` and grep for captcha related code there. Note that captcha uuids and answers were stored in-memory in the websocket server which is removed now, so its necessary to add a new database table for captchas.

**Comment by ForbodingAngel** [comment]
> I think its safe to say bots have pretty much beaten captchas, and they're not very useful for signups anymore. We might as well remove them. Registration applications and email verification are already in place anyway.

No offense, but this take is a bit braindead imo. Captcha aren't perfect, that is correct, but they do serve as a barrier.

Consider the swiss cheese approach to signup security where you have captcha as one layer, email verification as another, and signups as a third.

Individually, each one has holes, but if you put them together, each layer catches things that another misses. Is it perfect? No, but it's pretty damn good.

Don't let perfect be the enemy of good.

**Comment by maltfield** [comment]
@ForbodingAngel I think the argument you want to make is Defense in Depth

 * https://en.wikipedia.org/wiki/Defense_in_depth_(computing)

**Comment by dessalines** [comment]
One note, is that captchas (and all signup blocking methods) being optional, it still won't prevent people from creating bot-only instances. 

Once people discover the lemmy-bots that have been made that can bypass the previous captcha method, it also won't help (unless a new captcha method like the suggested ones above are implemented).

**Comment by cloventt** [comment]
@dessalines I agree, but in that situation the responsibility falls on instance admins to blacklist bad-acting instances from federation.

For admins who want to maintain a good reputation in the 'verse, there needs to be multiple layers of tools available, with admins able to select which combination of them they think is appropriate for their instance.

**Comment by lightrush** [comment]
Standing up an instance is and pretty trivial, automatable and fast. If I were a spammer, I'd have a preseeded db with thousands of users or a data seed script that adds them to my instance. If I can create one instance an hour, blacklisting will quickly become unsustainable. I can probably add them faster than that. This is an interesting attack vector to the system and it makes me think that allow-only federation will inevitably become the norm for instances that also have some user curation.

**Comment by maltfield** [comment]
@lightrush what you're describing can happen with email, but we don't have allow-only email. Rather, I think shared blocklists will be more common than allow-only federation. This is how email works.

 * https://en.wikipedia.org/wiki/Domain_Name_System_blocklist

**Comment by lightrush** [comment]
Sure. Shared blocklists could do it. Individual admins on every instance doing their own blocking however sounds impractical. If a shared blocklist system or protocol isn't established before the spammers fire up, I think admins are likely to resort to allow-only. Of course any of these scenarios will evolve.

**Comment by Zetaphor** [comment]
This should probably be closed and further conversation moved to a discussion. This was resolved with #3249

**Comment by awdsns** [comment]
Unfortunately the merge of #3249 was reverted, new PR #3289 not merged yet as of writing.

**Comment by Nutomic** [comment]
This is already included in 0.18.1-rc.1
