### ISSUE TITLE
Question: it is super slow

### ISSUE THREAD

**Issue by guoyunhe** [LemmyNet/lemmy#3206]
### Question

I have tried several lemmy instances and all of them are very slow when open a post page (5~10s). And here is no loading indicators like progress bar or spinner.

**Comment by sunaurus** [comment]
Sounds similar to https://github.com/LemmyNet/lemmy-ui/issues/1410 - are you also on Safari?

**Comment by guoyunhe** [comment]
@sunaurus no, I am using Chrome 114 on macOS. Switching between list and post page is very slow.

**Comment by Nutomic** [comment]
This is not a question, you need to fill in the proper issue template.
