### ISSUE TITLE
[Bug]: Sometimes, communities which contain the name of a social media platform cannot be created

### ISSUE THREAD

**Issue by Hedwig7s** [LemmyNet/lemmy#3211]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Sometimes, when attempting to either create a community with a name containing the name of certain social media platforms, such as "Facebook", when clicking "Create Community" the icon will just change to a spinning circle and then hang indefinitely. I have found this to be true across all lemmy instances. 
I have had times where it has not happened such as trying to make a community called "tfacebook" failed but trying to make a community called "testfacebook" worked

### Steps to Reproduce

1. Go on any lemmy instance
2. Go to create community
3. Give the community a name containing a social media platform (e.g. "tfacebook") (not all social media platforms are blocked)
4. Click "Create"

### Technical Details

No console errors

### Version

BE: 0.17.4

### Lemmy Instance URL

lemmy.ml

**Comment by Nutomic** [comment]
These will just be random, unrelated bugs probably because servers are overloaded. There is no checking for strings like facebook anywhere in the Lemmy code.
