### ISSUE TITLE
Add "last_update" or similar option to API requests. 

### ISSUE THREAD

**Issue by marsara9** [LemmyNet/lemmy#3212]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

When querying the API in order to index the posts and comments of an instance, there's no way to filter by the last time an object has changed.

So currently, unless I'm using federation to get updates, the only solution I see at the moment is to re-query for ever post and comment and then look for updates / new items. And while federation would work, it would end up sending over a lot of extra useless data that isn't needed. 

### Describe the solution you'd like.

Add a new query parameter for communities, posts and comments that would filter results based on a supplied date/time. 

Example:
GET /api/v3/post/list?since=2023-06-19T08:32:46Z&limit=50&sort=New

Which would fetch the last 50 of the newest posts that have been created or otherwise updated since 8:32am UTC on June 19th. 

### Describe alternatives you've considered.

I've looked into federation but this has its own issues. Mainly that I would receive notifications or updated about a lot of data I don't care about. For example I don't need to know when a post is upvoted.  This also creates a lot of traffic back and forth that in my opinion isn't necessary.

**Comment by Nutomic** [comment]
Same as https://github.com/LemmyNet/lemmy/issues/4195 which explains it better.
