### ISSUE TITLE
[Bug]: Thumbnails not displaying on posts

### ISSUE THREAD

**Issue by Antik79** [LemmyNet/lemmy#3220]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

On the lemmy.world instance we have an issue with thumbnails not being displayed next to posts. We suspect it might have something to do with the rate limits for pctrs - we see three rate limits in the nginx.conf but there is no info on how to scale these.

While looking for some solution I came across the following thread but nothing seems to resolve it: https://github.com/LemmyNet/lemmy/issues/1533

### Steps to Reproduce

1. Login to lemmy.world
2. Create any post in a community
3. There won't be a thumbnail

### Technical Details

No errors in browser console. OS is Linux

### Version

BE 0.17.4

### Lemmy Instance URL

lemmy.world

**Comment by dessalines** [comment]
Stale, can re-open if its still an issue.
