### ISSUE TITLE
Function for communities to subscribe to and aggregate fediverse hashtags

### ISSUE THREAD

**Issue by ja2ui0** [LemmyNet/lemmy#3228]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Bootstrapping communities in the fediverse can be a high-effort activity and that in itself is not a problem. The problem is that for any given topic, there already exists a considerable number of people loosely discussing that topic and often hashtagging it. Grouping discussions around a topic that is 1:1 relevant to a community is a missing feature that could take advantage of the underlying fediverse infrastructure to help grow communities of interest organically.

### Describe the solution you'd like.

I would like the option for communities to automatically boost content from across the fediverse that matches a hashtag (or multiple) that are defined by the groups admins / moderators. Ideally, it would not "repost" the content, but it would utilize the boost function to add the original post by the author to the community feed.

The original poster could block engagement from the community by blocking said community without impacting that community's ability to build independent discussion around the topic. Conversely the community could block posts by the user or instance regardless of hashtag usage by blocking the user in the customary way.

### Describe alternatives you've considered.

Two alternatives could be:

1. Rather than automatically boosting, moderators+ could be sent notifications of related hashtags and manually approve or reject them. This would cut down on spam potential at the expense of additional work.
2. Independent community members could crosspost content in the traditional ways, but this breaks the linkage between the community and the original author's post and defeats the network benefit.

**Comment by Nutomic** [comment]
This is not possible because Lemmy communities are represented by group actors (like user accounts), while hashtags are simple attributes on posts. To receive posts with these hashtags, it would be necessary to follow all users who write them (and get a lot of unrelated posts).

**Comment by dessalines** [comment]
In a third party application, sure.
