### ISSUE TITLE
[Bug]: Setting up lemmy from scratch doesn't work using docs

### ISSUE THREAD

**Issue by csi-lk** [LemmyNet/lemmy#3235]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Following the [manual setup steps in the docs](https://join-lemmy.org/docs/en/administration/from_scratch.html) during the step

> Compile and install Lemmy, setup database

The installation fails on command

```
cargo install lemmy_server --target-dir /usr/bin/ --locked --features embed-pictrs
```

### Steps to Reproduce

1. Install Ubuntu from scratch, upgrade, harden
2. Follow manual setup instructions in docs

### Technical Details

```bash
$ sudo cargo install lemmy_server --target-dir /usr/bin/ --locked --features embed-pictrs
[sudo] password for csilk:
    Updating crates.io index
  Installing lemmy_server v0.17.4
warning: package `bumpalo v3.12.1` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
   Compiling lemmy_utils v0.17.4
error: failed to run custom build command for `lemmy_utils v0.17.4`

Caused by:
  process didn't exit successfully: `/usr/bin/release/build/lemmy_utils-ac3fd22c6a80262d/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=translations/email/en.json
  cargo:rerun-if-changed=translations/email/pt.json
  cargo:rerun-if-changed=translations/email/ko.json
  cargo:rerun-if-changed=translations/email/fi.json

  --- stderr
  Error: Fmt(Os { code: 2, kind: NotFound, message: "No such file or directory" })
error: failed to compile `lemmy_server v0.17.4`, intermediate artifacts can be found at `/usr/bin/`
```

### Version

latest

**Comment by RocketDerp** [comment]
You can try building it from git source:

https://github.com/LemmyNet/lemmy-docs/issues/213

**Comment by csi-lk** [comment]
Thanks for posting @RocketDerp, Ill give this a go now and report back

**Comment by csi-lk** [comment]
Tried it using your instructions still have issues (seems to be related to my build output problem), full CLI below

```bash
$ git clone https://github.com/LemmyNet/lemmy.git lemmy
Cloning into 'lemmy'...
remote: Enumerating objects: 65421, done.
remote: Counting objects: 100% (7152/7152), done.
remote: Compressing objects: 100% (790/790), done.
remote: Total 65421 (delta 6599), reused 6465 (delta 6362), pack-reused 58269
Receiving objects: 100% (65421/65421), 15.83 MiB | 4.58 MiB/s, done.
cd lemmyg deltas:   4% (1799/44967)
Resolving deltas:  17% (7645/44967)
Resolving deltas: 100% (44967/44967), done.39122/44967)
$ cd lemmy
$ git checkout 0.17.4
Note: switching to '0.17.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 1386039e Version 0.17.4
$ git submodule init
Submodule 'crates/utils/translations' (https://github.com/LemmyNet/lemmy-translations.git) registered for path 'crates/utils/translations'
$ git submodule update --recursive --remote
Cloning into '/home/csilk/lemmy/crates/utils/translations'...
Submodule path 'crates/utils/translations': checked out 'a241fe1255a6363c7ae1ec5a09520c066745e6ce'
$ echo "pub const VERSION: &str = \"$(git describe --tag)\";" > "crates/utils/src/version.rs"
$ cargo build --release

[truncated a lot of "Compiling output here]

The following warnings were emitted during compilation:

warning: Key `email_verified_body` exists in fi but not in fallback language
warning: Key `email_verified_subject` exists in fi but not in fallback language
warning: Key `email_verified_subject` exists in ko but not in fallback language
warning: Key `email_verified_body` exists in ko but not in fallback language
warning: Key `email_verified_subject` exists in pt but not in fallback language
warning: Key `email_verified_body` exists in pt but not in fallback language

error: failed to run custom build command for `lemmy_utils v0.17.4 (/home/csilk/lemmy/crates/utils)`

Caused by:
  process didn't exit successfully: `/home/csilk/lemmy/target/release/build/lemmy_utils-50151c8a2b7b9da3/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=translations/email/en.json
  cargo:warning=Key `email_verified_body` exists in fi but not in fallback language
  cargo:warning=Key `email_verified_subject` exists in fi but not in fallback language
  cargo:rerun-if-changed=translations/email/fi.json
  cargo:warning=Key `email_verified_subject` exists in ko but not in fallback language
  cargo:warning=Key `email_verified_body` exists in ko but not in fallback language
  cargo:rerun-if-changed=translations/email/ko.json
  cargo:warning=Key `email_verified_subject` exists in pt but not in fallback language
  cargo:warning=Key `email_verified_body` exists in pt but not in fallback language
  cargo:rerun-if-changed=translations/email/pt.json

  --- stderr
  Error: Fmt(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by t0stiman** [comment]
Does [these steps](https://www.reddit.com/r/Lemmy/comments/1443oac/comment/jng0upm/?utm_source=share&utm_medium=web2x&context=3) work for you?

```
mkdir -p /root/lemmy/    
cd /root/lemmy/

git clone https://github.com/LemmyNet/lemmy.git --recursive .     
git branch -a    
git checkout 0.17.3    
echo "pub const VERSION: &str = \"$(git describe --tag)\";" > "crates/utils/src/version.rs"     

cargo build --release --target-dir /root/lemmy/ --locked --features embed-pictrs    
mv /root/lemmy/release/lemmy_server /usr/bin/lemmy_server
```

**Comment by null-dev** [comment]
Compilation from source uses [rosetta-build](https://crates.io/crates/rosetta-build) which requires `rustfmt` to be installed on the machine.

How did you install Rust? Did you use `rustup`? Can you post the output of `rustfmt` and `sudo rustfmt`?

**Comment by B4tuhanY1lmaz** [comment]
I was having the same porblem on Ubuntu Server 22.04 and installing these 3 packages fixed my problem.
```sudo apt install rustfmt protobuf-compiler libprotobuf-dev```

**Comment by SadisticSurgeon** [comment]
Mine failed after these steps: 

`#installs latest release of lemmy
apt install build-essential
apt install pkg-config libssl-dev libpq-dev postgresql protobuf-compiler libprotobuf-dev rustfmt
apt install cargo
mkdir -p /root/lemmy/    
cd /root/lemmy/

git clone https://github.com/LemmyNet/lemmy.git --recursive .     
git branch -a    
git checkout 0.17.3    
echo "pub const VERSION: &str = \"$(git describe --tag)\";" > "crates/utils/src/version.rs"     

cargo build --release --target-dir /root/lemmy/ --locked --features embed-pictrs`

This is the failure : 

`error[E0599]: no method named `email_verified_subject` found for enum `Lang` in the current scope
   --> crates/api_common/src/utils.rs:425:23
    |
425 |   let subject = &lang.email_verified_subject(&user.person.actor_id);
    |                       ^^^^^^^^^^^^^^^^^^^^^^ method not found in `Lang`

error[E0599]: no method named `email_verified_body` found for enum `Lang` in the current scope
   --> crates/api_common/src/utils.rs:426:20
    |
426 |   let body = &lang.email_verified_body();
    |                    ^^^^^^^^^^^^^^^^^^^ method not found in `Lang`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `lemmy_api_common` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
`
If I do rustc --explain E0599 this is the output: 

`This error occurs when a method is used on a type which doesn't implement it:

Erroneous code example:

```
struct Mouth;

let x = Mouth;
x.chocolate(); // error: no method named `chocolate` found for type `Mouth`
               //        in the current scope
```

In this case, you need to implement the `chocolate` method to fix the error:

```
"rustfmt" and "sudo rustfmt hangs completely giving no output... 
struct Mouth;

impl Mouth {
    fn chocolate(&self) { // We implement the `chocolate` method here.
        println!("Hmmm! I love chocolate!");
    }
}

let x = Mouth;
x.chocolate(); // ok!
`

**Comment by RocketDerp** [comment]
> git checkout 0.17.3    

Should be using 0.18.0 here.

What versions of cargo and rustc do you have?

**Comment by SadisticSurgeon** [comment]
cargo and rust are both 1.65.0
I'll try this again using git checkout 0.18.0 and see if it helps anything.

**Comment by RocketDerp** [comment]
You were supposed to run "RustUp" and be on 1.70, and you also seem to not have issued the submodule git commands?

**Comment by SadisticSurgeon** [comment]
> You were supposed to run "RustUp" and be on 1.70, and you also seem to not have issued the submodule git commands?

I had done those in an earlier attempt, and it died. What I have here is just the latest attempt at it, basically from the cargo build step.

**Comment by SadisticSurgeon** [comment]
I'm running it again now with 0.18.0 .. if it dies again I'll revert back to my clean ubuntu 22.04 snapshot and try again from the beginning.

**Comment by SadisticSurgeon** [comment]
compiling finished in about 47 minutes. Worked for me just by switching to 0.18.0

**Comment by Chewie9999** [comment]
I have exactly the same problem, tried installing the extra stuff, which made no difference.
Does it really need to be on Rust v18?
I'm on Ubuntu 22.04.2 LTS and v17 is the latest packaged version it seems.
I've tried both @t0stiman 's steps and that made no difference.

**Comment by RocketDerp** [comment]
These work:

cargo 1.70.0 (ec8a8a0ca 2023-04-25)  
rustc 1.70.0 (90c541806 2023-05-31)

**Comment by Chewie9999** [comment]
> These work:
> 
> cargo 1.70.0 (ec8a8a0ca 2023-04-25) rustc 1.70.0 (90c541806 2023-05-31)

Same versions here :(

**Comment by RocketDerp** [comment]
what's your error output?

**Comment by zachfeldman** [comment]
I personally had this error when doing `cargo run` on the `main` branch involving translations:
```
zach@zach-laptopw:~/dev/lemmy (main)$ cargo run
   Compiling indexmap v1.9.1
   Compiling string_cache v0.8.4
   Compiling url v2.4.0
   Compiling chrono v0.4.26
   Compiling num-bigint v0.4.3
   Compiling serde_urlencoded v0.7.1
   Compiling triomphe v0.1.8
   Compiling zstd-sys v2.0.8+zstd.1.5.5
   Compiling zstd-safe v6.0.5+zstd.1.5.4
   Compiling toml_datetime v0.6.2
   Compiling serde_spanned v0.6.2
   Compiling actix-router v0.5.1
   Compiling uuid v1.3.4
   Compiling text_lines v0.6.0
   Compiling psm v0.1.21
   Compiling bincode v1.3.3
   Compiling lemmy_utils v0.18.1-rc.9 (/home/zach/dev/lemmy/crates/utils)
   Compiling deser-hjson v1.0.2
   Compiling smart-default v0.7.1
   Compiling scoped-futures v0.1.3
error: failed to run custom build command for `lemmy_utils v0.18.1-rc.9 (/home/zach/dev/lemmy/crates/utils)`

Caused by:
  process didn't exit successfully: `/home/zach/dev/lemmy/target/debug/build/lemmy_utils-863dc8680829f157/build-script-build` (exit status: 1)
  --- stderr
  Error: FileRead { file: "translations/email/en.json", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }
```

Basically, it seems I was completely missing them. The following fixed it:

```
cd crates/utils/
git clone git@github.com:LemmyNet/lemmy-translations.git translations
```

I probably just didn't do a deep enough clone or something, but posting in case it helps anyone else!

**Comment by sunaurus** [comment]
Hey, seems this is not about a bug in Lemmy, but issues with local setups.

If you notice anything wrong in the lemmy docs, please make a PR to: https://github.com/lemmynet/lemmy-docs
If you need support with setting up Lemmy, please try a support channel rather than GitHub issues: 
* !lemmy_suppot@lemmy.ml
* https://matrix.to/#/#lemmy-space:matrix.org
