### ISSUE TITLE
Reverse image search for communities/instances/whole lemmy before posting to limit spam/reposts and save space on servers

### ISSUE THREAD

**Issue by M4rtineski** [LemmyNet/lemmy#3240]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

There was always this thing that annoyed me on reddit a lot, reposts, reposts are images/posts that were send multiple times on one subreddit but I want to focus on image part. Reposts not only could be considered a spam but also take up space on instances which is not ideal.

### Describe the solution you'd like.

Add an ability that would allow us to reverse image search the image on choosen sublemmy, instance or whole lemmy platform before posting to help us avoid crating reposts. If having multiple options for image search is asking for too much then having reverse image search just for sublemmies would be plenty enough.  

Maybe we could even add an option for sublemmy moderators to automatically block uploads of images that already exist on the sublemmy with option for poster to ask for an exemption because depending on context image may be wanted to be shared again.

### Describe alternatives you've considered.

No other solutions come to my mind.

**Comment by Eskuero** [comment]
This would probably have to be handled by the [pictrs backend](https://git.asonix.dog/asonix/pict-rs/) not lemmy.

**Comment by M4rtineski** [comment]
> This would probably have to be handled by the [pictrs backend](https://git.asonix.dog/asonix/pict-rs/) not lemmy.

So... Should I make an issue on pictrs github? I think that I saw dev behind pictrs on lemmy's github yesterday or 2 days ago so maybe he will see it anyway.

**Comment by asonix** [comment]
pict-rs knows nothing of lemmy posts, and can only tell whether a given image has been uploaded before or not. Lemmy could implement this by accessing the internal aliases endpoint for uploaded files to see if the file is aliased elsewhere, and then check its own database to find posts referencing those aliases.

This isn't a perfect solution, as pict-rs doesn't deduplicate by perceptual hash, and instead uses a sha. It will catch exact duplicates, though.

**Comment by 8ullyMaguire** [comment]
### Related
- [Booru-Style Image View, Search and Tagging by Users](https://github.com/LemmyNet/lemmy/issues/3626)

**Comment by dessalines** [comment]
Open this one up on the pictrs issue tracker.
