### ISSUE TITLE
Support arm 32 bit / armv7hf

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#325]
@iav We can work against this issue.

**Comment by iav** [comment]
As a workaround:
lemmy can be build on Raspberry Pi. Docker have to be installed.
then lemmy image build as:
```
git clone https://github.com/dessalines/lemmy.git lemmy-src
cd lemmy-src/docker/dev
docker build -f Dockerfile.libc -t dessalines/lemmy:version ../..
```
then setup lemmy on instruction https://github.com/dessalines/lemmy#docker

**Comment by Nutomic** [comment]
Should already work fine with manual installation (compile from sources).
