### ISSUE TITLE
[Bug]: "404: TypeError: Cannot read properties of undefined"

### ISSUE THREAD

**Issue by jernst** [LemmyNet/lemmy#3250]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

When accessing `https://lemmy.world/inbox` while not logged on, I get a badly formatted error `"404: TypeError: Cannot read properties of undefined"`.

### Steps to Reproduce

1. While logged on, go to your inbox
2. Click logout

### Technical Details

I'm just a user, I don't have access to server side stuff.

### Version

BE 0.17.4

### Lemmy Instance URL

lemmy.world

**Comment by kartikynwa** [comment]
If you try this in one of the dev deployments (eg. https://enterprise.lemmy.ml/inbox) you get redirected to the login page.
