### ISSUE TITLE
[Bug]: I can feature (pin) my posts on any community from any instance without being a mod.

### ISSUE THREAD

**Issue by n3oney** [LemmyNet/lemmy#3251]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

I have my own Lemmy instance, and when I make a post from the mod account, to any community - local or federated, I am able to feature/pin it.
The feature gets federated to the original instance, and all users see the post as pinned.

This seems bad - bots could abuse this, as this shows up as the first thing in the feed of the community!

### Steps to Reproduce

1. Host my own Lemmy instance
2. Create a post as a user who's a mod 
4. Click the three dots and the *Pin* Community button ![image](https://github.com/LemmyNet/lemmy/assets/30625554/3d3cdeb7-59a8-4311-bb83-592785294e93)
5. See the community from a different Lemmy instance. (in this example - the original instance) ![image](https://github.com/LemmyNet/lemmy/assets/30625554/ce55a724-2a4c-4d69-8a70-bc8a3d5c99d3)

### Version

0.17.4

### Lemmy Instance URL

lemmy.neoney.dev

**Comment by Eskuero** [comment]
This really works 🫠

**Comment by sunaurus** [comment]
Hey, I think this can be considered a security vulnerability. Please consider removing the issue and reporting it as described in https://github.com/LemmyNet/lemmy/blob/main/SECURITY.md

**Comment by n3oney** [comment]
> Hey, I think this can be considered a security vulnerability. Please consider removing the issue and reporting it as described in https://github.com/LemmyNet/lemmy/blob/main/SECURITY.md

can’t delete, sorry

> Only accounts with admin or owner permissions can delete issues in a repository owned by an organization.

**Comment by Nutomic** [comment]
I tested this with 0.18 and cant reproduce it. So apparently this was already fixed.

**Comment by n3oney** [comment]
True. Can't repro by posting to communities on https://voyager.lemmy.ml
