### ISSUE TITLE
More granular administration tools for federating with other instances

### ISSUE THREAD

**Issue by jordan1776** [LemmyNet/lemmy#3255]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

When I heard about beehaw defederating with sh.itjust.works and lemmy.world , it didn't quite sit right with me.  Because of the state of the mod tools and open user registration on those instances, they are effectively forced to de-federate to protect there community.

But to me, as though the userbase between the instances are fairly similar, de-federation over reasons like this are somewhat overkill. If there was a middle ground between completely separated and fully open.

### Describe the solution you'd like.

I propose a middle ground between blocked and linked instances. This group would be "Linked with restrictions". As the name implies, these instances would be federated, but with restrictions. The options would be:

- Allow inbound user interactions (voting, commenting, post) (from that instance to yours)
- Allow outbound user interactions (to that instance from your users)
- All in 'All' feed

The granularity could go down to the community level (such as allow federation with this instance, but restrict access to these certain communities, or the opposite of block these forms of interaction with this instance, except for a selected list of there communities)

The big thing is de-federation should be a final option, where there should be no question of "maybe we can federate with that instance some other time" as in the meanwhile regular users who done no wrong are punished at no fault of there own.

### Describe alternatives you've considered.

Improve mod tools?

**Comment by dessalines** [comment]
This should mostly be handled by person-based instance blocking which should be in the next release.
