### ISSUE TITLE
[Bug]: DB fix for Communities affected by #3075

### ISSUE THREAD

**Issue by awdsns** [LemmyNet/lemmy#3256]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

As [discussed](https://github.com/LemmyNet/lemmy/issues/3075#issuecomment-1598317356) in #3075, the applied fix only prevents the problem from affecting communities going forward. To fix existing communities affected by this bug, administrators need to manually edit the database.

Since there is probably a significant number of affected communities and not all instance admins have the time or skills to apply this manual fix (if they are even aware of the issue), an automated DB check should be applied to revert all remote communities with the same instance name as the local instance to local communities.

### Steps to Reproduce

see #3075

### Technical Details

Proposed fix from https://github.com/LemmyNet/lemmy/issues/3075#issuecomment-1600028805 :

```sql
UPDATE community c
SET local=TRUE
FROM instance i
WHERE i.id=c.instance_id AND i.domain='domain.tld';
```

### Version

BE 0.17.4

### Lemmy Instance URL

feddit.de and many others

**Comment by kartikynwa** [comment]
Here is the fix in a single SQL query:

```sql
UPDATE community c
SET local=TRUE
FROM local_site ls
  JOIN site s ON ls.site_id=s.id
WHERE c.instance_id=s.instance_id AND NOT c.local;
```

I am not sure how to incorporate as a migration. If someone can help with that I can file a PR.
