### ISSUE TITLE
Increase character limit for markdown fields.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#3262]
Context: https://github.com/LemmyNet/lemmy/issues/2546

50k characters seems a reasonable increase from the current 10k.

**Comment by Nutomic** [comment]
Changing [this line](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/utils/validation.rs#L20) works in my tests to increase the limit to 50k chars. However the same limit also applies to comments, which seems too much. So there should be a separate, lower limit added for comments imo.

**Comment by Neriderc** [comment]
For anyone arriving here wondering why they can only post 10k characters - well I don't have an answer for you, but know that if you post it first, then you can edit it and it allows the 50k in the edit.

**Comment by Neriderc** [comment]
> This doesn't work for me on Lemmy 0.19.2. Editing a comment field (in the web UI) to add more text also triggers the cryptic `invalid_body_field` error. I assume the error comes from the back end.

Not surprising, because of significant backend changes, but good to know.

**Comment by dessalines** [comment]
I checked the logic on the back end, and it looks okay: https://github.com/LemmyNet/lemmy/blob/1be7dbde3379ea9ac4da49c6cc287f563ce08572/crates/utils/src/utils/validation.rs#L160

Lemmy-ui might also need to be updated for this limit tho.
