### ISSUE TITLE
[Bug]: Can't get pictrs to start with lemmy

### ISSUE THREAD

**Issue by arne-fuchs** [LemmyNet/lemmy#3264]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

I've build lemmy from scratch and defined the path of the pictrs in the service file as followed:
```
Environment=PICTRS_PATH=/home/debian/lemmy/pictrs
Environment=PICTRS_ADDR=127.0.0.1:8080
```

I've downloaded the pict-rs ver. 3.1 from the official git and placed it in /home/debian/lemmy and called it pictrs and changed owner to lemmy.

If I try to upload an icon I get following response:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

In the lemmy_server logs I can find following output:
```
Jun 22 11:04:40 ns3030678 lemmy_server[561268]: 2023-06-22T11:04:40.982812Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: Request error: error sending request for url (http://localhost:8080/image): error trying to connect: tcp connect error: Connection refused (os error 111)

Jun 22 11:04:40 ns3030678 lemmy_server[561268]: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/image", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) })

Jun 22 11:04:40 ns3030678 lemmy_server[561268]: 2023-06-22T11:04:40.982842Z  INFO actix_web::middleware::logger: 127.0.0.1 "POST /pictrs/image HTTP/1.1" 400 153 "https://lemmy.paesserver.de/admin" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0" 0.001167
```

in my lemmy.hjson pictrs is defined as followed:
```
pictrs: {
    url: "http://localhost:8080/"
}
```

### Steps to Reproduce

* Follow instructions on https://join-lemmy.org/docs/administration/from_scratch.html#pict-rs
* Get pict-rs 3.1 as binary from https://git.asonix.dog/asonix/pict-rs
* Place it in folder of your liking
* edit the systemd file to point to the binary
* Start service, look that no errors appear
* Login into your lemmy instance and try to upload an icon

### Technical Details

Debian 12

### Version

0.17.4

### Lemmy Instance URL

lemmy.paesserver.de

**Comment by arne-fuchs** [comment]
@kartikynwa Do you know where I get the parameters for pictrs?

**Comment by kartikynwa** [comment]
@arne-fuchs 

1. Check the README here: https://git.asonix.dog/asonix/pict-rs
2. Check Lemmy's docker-compose.yml file for reference on how pictrs is configured for lemmy: https://github.com/LemmyNet/lemmy/blob/main/docker/docker-compose.yml

**Comment by arne-fuchs** [comment]
@kartikynwa Nice thanks! Because I currently get following error:
{"msg":"Unsupported image format","files":null}
