### ISSUE TITLE
Option to not run any database migrations

### ISSUE THREAD

**Issue by tbe** [LemmyNet/lemmy#3269]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Currently, the Lemmy server runs migrations as part of the startup process. This requires the application user to have matching privileges on the database.

From a security point of view, the application should only have the minimum set of privileges, required at runtime.

### Describe the solution you'd like.

Providing a flag, to disable migrations and a tool to either run the migrations with a different set of user/password, or to dump the SQL that would be executed and leave it to the user, would mitigate this issue

### Describe alternatives you've considered.

Currently, migrations could be run by hand, but this is error prone, and can lead to missing migrations.

**Comment by kartikynwa** [comment]
You can use [Diesel's CLI](https://github.com/diesel-rs/diesel/blob/master/diesel_cli/README.md) to run migrations using `diesel migration run`. Just have to configure the `--database-url`.

**Comment by tbe** [comment]
> You can use [Diesel's CLI](https://github.com/diesel-rs/diesel/blob/master/diesel_cli/README.md) to run migrations using `diesel migration run`. Just have to configure the `--database-url`.

Great, didn't see that. Then, the only missing part is a flag to disable migrations during startup.

**Comment by dessalines** [comment]
Lemmy can't run without these migrations being set up as a minimum.
