### ISSUE TITLE
[Bug]: Incoming activity has invalid signature

### ISSUE THREAD

**Issue by Rulasmur** [LemmyNet/lemmy#3273]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

Fresh install of rc6 on a previously unused domain, subscribed to several communities across several other instances which worked.

However while I can see pushes coming in via nginx logs, I only receive the message
```
LemmyError { message: None, inner: Incoming activity has invalid signature, context: SpanTrace [{ target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=0.0.0.0 http.target=/inbox otel.kind=\"server\" request_id=e16f803a-a17f-41d8-b55e-298cb8bd436c", file: "src/root_span_builder.rs", line: 16 }] }
2023-06-22T19:08:08.822722Z  WARN lemmy_server::root_span_builder: Incoming activity has invalid signature
   0: lemmy_server::root_span_builder::HTTP request
```
In the lemmy logs.

I'm not 100% sure if this is truly a bug, how I have been unable to find any related information regarding this, and as such am documenting it for others to find if needed.

### Steps to Reproduce

1. Fresh install via ansible on a AWS ubuntu ec2
2. complete initial setup
3. subscribe to other instances' communities

### Technical Details

```
LemmyError { message: None, inner: Incoming activity has invalid signature, context: SpanTrace [{ target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=0.0.0.0 http.target=/inbox otel.kind=\"server\" request_id=e16f803a-a17f-41d8-b55e-298cb8bd436c", file: "src/root_span_builder.rs", line: 16 }] }
2023-06-22T19:08:08.822722Z  WARN lemmy_server::root_span_builder: Incoming activity has invalid signature
   0: lemmy_server::root_span_builder::HTTP request
```

ubuntu 22

### Version

0.18.0-rc.6

**Comment by adamzwakk** [comment]
I'm getting this on 0.17.4 as well fwiw

**Comment by RocketDerp** [comment]
The logging doesn't give you any clue who the incoming is on the other end of the connection. So you can't even identify if it is a Leemy peer or some other application. Let alone details like Lemmy version.

I did find in the Rust code how to add getting the IP address of the remote server making the attempt: https://github.com/LemmyNet/activitypub-federation-rust

**Comment by Rulasmur** [comment]
The nginx logs do actually show IP etc
```
"POST /inbox HTTP/1.1" 400 39 "-" "Lemmy/0.17.4; +https://beehaw.org"
```
I used nginx to dump the post data as well just to check it for issues, but it doesn't seem to be the issue:

```
137.184.145.108 - - [22/Jun/2023:20:00:40 +0000] "POST /inbox HTTP/1.1" 400 39 "-" "Lemmy/0.17.4; +https://beehaw.org"
{
    "@context": [
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/v1",
      {
        "lemmy": "https://join-lemmy.org/ns#",
        "litepub": "http://litepub.social/ns#",
        "pt": "https://joinpeertube.org/ns#",
        "sc": "http://schema.org/",
        "ChatMessage": "litepub:ChatMessage",
        "commentsEnabled": "pt:commentsEnabled",
        "sensitive": "as:sensitive",
        "matrixUserId": "lemmy:matrixUserId",
        "postingRestrictedToMods": "lemmy:postingRestrictedToMods",
        "removeData": "lemmy:removeData",
        "stickied": "lemmy:stickied",
        "moderators": {
          "@type": "@id",
          "@id": "lemmy:moderators"
        },
        "expires": "as:endTime",
        "distinguished": "lemmy:distinguished",
        "language": "sc:inLanguage",
        "identifier": "sc:identifier"
      }
    ],
    "actor": "https://beehaw.org/c/gaming",
    "to": [
      "https://www.w3.org/ns/activitystreams#Public"
    ],
    "object": {
      "id": "https://programming.dev/activities/like/e2798099-cb81-4a36-82b6-01ad94a21d8e",
      "actor": "https://programming.dev/u/Die4Ever",
      "object": "https://beehaw.org/comment/398510",
      "type": "Like",
      "audience": "https://beehaw.org/c/gaming"
    },
    "cc": [
      "https://beehaw.org/c/gaming/followers"
    ],
    "type": "Announce",
    "id": "https://beehaw.org/activities/announce/9d55459d-9035-46a8-b341-6dc04db844dd"
  }
```

**Comment by Rulasmur** [comment]
Based on the code here and a few lines below:
https://github.com/programming-dot-dev/activitypub-federation-rust/blame/6ac6e2d90efa818d9644f7f09346d3657e65f32d/src/http_signatures.rs#L146

This seems to be a new "secure mode" feature. so either the signature is missing, or getting malformed somewhere

**Comment by Rulasmur** [comment]
@RocketDerp Everything is failing with a 400 bad request 
![image](https://github.com/LemmyNet/lemmy/assets/14957173/5f7fa0ec-7f1a-4b32-b5c4-3ea659b40f43)

**Comment by RocketDerp** [comment]
Well, the live 0.18 instance I have access to is getting content coming in from Beehaw: https://lemmy.ml/c/gaming@beehaw.org?dataType=Post&page=1&sort=New - as there is a (remote originated) posting there from 2 minutes ago.

**Comment by Rulasmur** [comment]
@RocketDerp I'm not sure I'm following the point you've made there. But I suspect the issue to be with fresh installs being misconfigured somewhere, rather than being a true bug in the code.

That is nginx logs

**Comment by Rulasmur** [comment]
> I'm getting this on 0.17.4 as well fwiw
@adamzwakk Was that a fresh install?

**Comment by RocketDerp** [comment]
> I suspect the issue to be with fresh installs being misconfigured somewhere

ok, yha I was lost there. New installs and how federation bootstraps on a new instance to get the signing keys is something I haven't learned yet.

**Comment by Rulasmur** [comment]
It looks to be http signatures for message integrity
https://technospace.medium.com/ensuring-message-integrity-with-http-signatures-86f121ac9823

**Comment by Rulasmur** [comment]
Based on some investigation:
Bad debug:
```
2023-06-22T21:07:47.457918Z DEBUG HTTP request{http.method=POST http.scheme="http" http.host=0.0.0.0 http.target=/inbox otel.kind="server" request_id=f8edb5d8-1e3b-4364-8c03-e0b343121a5d}: activitypub_federation::http_signatures: Verifying with key -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAynYYuiBGF3PMH6ntXz9X
m4379QY3lFhyteEYQvBWjBNoAlNW0RnOQ3CfhJs5VcaUiAlDFCHlBjs6qx70sdL9
QDgFLGuAhmIWl4EvkypmJivcPynPehOscOsLgo74fNglOCs7CdvTOPULHW76J4JI
oEu1C3EmNMI2h+WR3EfkIidbdlOT7hx+9M8wiCcHhq2qSJf5vl05TvGyxbCOhN+b
Ekgsx+qzOhI95/fPbkbIhcaMkK2gQMr8jA4N5OfSYwHjr7/wi3/EkoXSGfmW9LQu
GuD1BCYpvE1oJWtAV75/Pe8YAQQiIbVBUEA0hU58oCJUzF0jZfs303lIbY3JZIm3
DwIDAQAB
-----END PUBLIC KEY-----
, message (request-target): post /inbox
content-type: application/activity+json
date: Thu, 22 Jun 2023 21:07:47 GMT
digest: SHA-256=rkTyphEyV+VI4sJ9o0oLnPjl24NMZ2a6XA8KejS9L1M=
host: 0.0.0.0
```

Based on debug logs from a working instance, the host should have been `host: lemmy.ml`

**Comment by RocketDerp** [comment]
You didn't by chance have to repeat the install, more than the initial time? Some people were reporting they had to purge the PostgreSQL to get federation to work after a repeat install failure. Maybe the signing keys get kept around from the first install attempt or something, I've seen a few people say 'that fixed my install'.

**Comment by Rulasmur** [comment]
```
172.19.0.1 - - [22/Jun/2023:22:04:14 +0000] "POST /inbox HTTP/1.1" 400 39 "-" "Lemmy/0.18.0-rc.6; +https://lemmy.ml"
172.19.0.1 - - [22/Jun/2023:22:04:14 +0000] "POST /inbox HTTP/1.1" 400 39 "-" "Lemmy/0.18.0-rc.6; +https://lemmy.ml"
172.19.0.1 - - [22/Jun/2023:22:04:22 +0000] "POST /inbox HTTP/1.1" 400 39 "-" "Lemmy/0.18.0-rc.6; +https://lemmy.ml"
```
Based on these logs it seems the issue is the outside nginx / second layer nginx

**Comment by RocketDerp** [comment]
Your earlier error message shows it is penetrating all the way into the Rust code, line 16 is doing the logging: `file: "src/root_span_builder.rs", line: 16`

**Comment by Rulasmur** [comment]
`root_span_builder` is a telementry span used for tracing purposes https://opentelemetry.io/docs/concepts/signals/traces/ 
The actual error is thrown in the code I linked earlier

> Based on the code here and a few lines below: https://github.com/programming-dot-dev/activitypub-federation-rust/blame/6ac6e2d90efa818d9644f7f09346d3657e65f32d/src/http_signatures.rs#L146

Being that these are just http signatures, to which I linked an article, I expected to error to not be code related, as servers such as lemmy.ml etc run just fine on this code.

> It looks to be http signatures for message integrity https://technospace.medium.com/ensuring-message-integrity-with-http-signatures-86f121ac9823

Further based on the debug message posted earlier. with the host being `0.0.0.0` made me suspect nginx. Which was mostly confirmed when I saw that the nginx config for the ansible deploy was changed merely 6 hours ago.

I then compared my debug messages with those from a working instance, and confirmed that the host should not be `0.0.0.0`

And am currently investigating a fix which I will PR to lemmy-ansible. Closing this issue due to the issue being in lemmy-ansible.

**Comment by RocketDerp** [comment]
> confirmed that the host should not be 0.0.0.0

On my working server, the host: actually shows to be my own server ;) Because that is in fact what nginx passes along (itself as host).  So I don't think it's the problem.  I think the actual encryption/signature key you are using isn't valid. That isn't code, that's the database content of the -----BEGIN PUBLIC KEY----- data.

For the Rust code to actually get the source IP address forwarded from Nginx, they have to call `request.connection_info().realip_remote_addr()`

**Comment by Rulasmur** [comment]
@stnfrd @adamzwakk Please see related PR for fixes of your installs

**Comment by RocketDerp** [comment]
Sorry if I made a nuisance of myself today over this issue. I feel like a dog chasing my own tail trying to get access to the lemmy application error logs out of the big 3 instances. https://lemmy.ml/post/1453121

**Comment by MetroWind** [comment]
I also have this problem on my new instance. Like in @RocketDerp’s case, the log shows the correct FQDN of my server.
