### ISSUE TITLE
Improve Moderation Tools

### ISSUE THREAD

**Issue by jordan1776** [LemmyNet/lemmy#3275]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Current moderation tools are not adequate enough for a small team of moderators to prevent spam and protect users.

### Describe the solution you'd like.

Ideas from alyaza, admin of beehaw.org:

- Role for approval of applications (to delegate)
- Site mods (to delegate from admins)
- Auto-report posts with certain keywords or domains (for easier time curating without reports)
- Statistics on growth (user, comments, posts, reports)
  - User total
  - MUA
  - User retention
  - Number of comments
  - Number of posts
  - Number of reports open
  - Number of reports resolved
- Sort reports
  - by resolved/open
  - by local/remote
- Different ways to resolved a report
  - Suspend account for a limited amount of time rather than just banning
  - Send warning
- Account mod info
  - Number of 'strikes' (global and local) and reports
  - Moderation notes
  - Change email
  - Change password
  - Change role
- Ability to pin messages in a post
- Admins should be able to purge
- Filter modlog to local
- Better federation tools (applications to communities, limiting)
  - Applications to communities to allow safe spaces to exist (people should not be able to just "walk in" on a safe space - similarly to follow requests in Mastodon in a way)
  - Limiting (Lock our communities down from certain instances but still allow people using our instance to talk to people from those instances)

Source:
https://beehaw.org/comment/397674

### Describe alternatives you've considered.

Block all offending instances as they popup

**Comment by lionirdeadman** [comment]
These should really be separated into different issues..

Warnings : https://github.com/LemmyNet/lemmy/issues/1424
Federation options : #3662 

Will continue and update this comment as I go and find them
