### ISSUE TITLE
Sensitive images from federated posts are stored locally

### ISSUE THREAD

**Issue by lemmus-org** [LemmyNet/lemmy#3276]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

Whenever a post is federated the image is pushed to `pict-rs` and stored locally. This includes sensitive images, even though the admin may have opted to not allow them. It creates a potential legal issue depending on the content and the hosting provider or locality. There are also currently limited tools or support around purging images from `sled`, filesystem, and  `postgres`.

### Describe the solution you'd like.

By default, the logic of storing a federated image locally should respect the admin's configuration regarding sensitive content. While this doesn't solve the entire issue it does help to reduce some of the risk in operating a server.

### Describe alternatives you've considered.

These are some alternatives or further followups that can be addressed, as discussed by other admins:

* Allow disabling all local images except content such as avatars and banners uploaded by local site.
* Continue storing images locally, but clear them out after a configurable period of time.
* Blur sensitive images when stored locally while continuing to link original federated image.
* Only store images locally that are uploaded to the local site.
* Proxy all federated images, but don't store them. This allows CDNs the ability to cache so that load is reduced on origin server while not retaining a direct copy.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3253
