### ISSUE TITLE
[Bug]: Federation fails to send outgoing comments/posts if username exists on previous deleted lemmy instance with the same domain

### ISSUE THREAD

**Issue by fivves** [LemmyNet/lemmy#3278]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

This bug causes the federation service to not send any outgoing content from the instance. When I created an account, deleted the server, got a new server, redirected the URL to the new IP, and then made the exact same account again, Lemmy was unable to sync any comments posted on the instance. 

The fix was to create a new user account on the same instance with a different username. Sucks cause I feel like I "burned" my username I use on everything else! :( 

Fun discovery trying to figure out why my instance wasn't sending any data out. Thank you for creating Lemmy!!!!

### Steps to Reproduce

1. Create a new Lemmy instance on a brand new VPN with a fresh install of Ubuntu with Docker installed
2. Create username "user"
3. Use your new account to federate with other sites. Post content on other instances so that these instances start to federate with yours. 
4. Delete your server. 
5. Create a new VPN with a fresh IP address
6. Change your A Record via your domain service provider to your new IP address
7. Create a new Lemmy instance on this brand new VPN with a fresh install of Ubuntu with Docker installed
8. Create username "user"
9. Try to post content on other instances, ie. lemmy.ml/c/test. After you post your comment, go to /c/test on lemmy.ml and see that your comment was not posted. 

### Technical Details

brand new VPN with a fresh install of Ubuntu with Docker installed, provided by DigitalOcean.

### Version

0.17.4

### Lemmy Instance URL

l.lucitt.com

**Comment by Crashdoom** [comment]
I believe this is intentional design as the public key used for identifying if the message did in fact originate from a particular user on a given domain to prevent impersonation.

Perhaps some kind of command-line tool (similar to Mastodon's [`tootctl self-destruct`](https://docs.joinmastodon.org/admin/tootctl/#self-destruct)) would be useful here for wiping an instance from most remote servers so you can have a clean start.

**Comment by Nutomic** [comment]
Yes this sounds like Lemmy is still checking the signature against your old public key. It should be resolved after a day, as user profiles (and public keys) are updated every 24 hours.

**Comment by airjer** [comment]
I had this problem but it’s fixed by resubscribing to whichever community you’re trying to comment in or up/downvote in.
