### ISSUE TITLE
[Bug]: Error when attempting to follow a Lemmy community

### ISSUE THREAD

**Issue by djcass44** [LemmyNet/lemmy#3287]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When attempting to follow a Lemmy community using the following activity:

```json
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "actor": "https://preader-dev.v2.dcas.dev/users/6b91337d-cdcc-4e78-9c90-ef6c539a31e1",
    "id": "https://preader-dev.v2.dcas.dev/activities/93a248bd-19b6-407b-83f6-e2fc36f811b5",
    "object": "https://lemmy.world/c/android",
    "to": "https://lemmy.world/c/android",
    "type": "Follow"
}
```

I receive the following error: 
```
data did not match any variant of untagged enum AnnouncableActivities
```

The full HTTP response dump is:
```
HTTP/2.0 400 Bad Request\r\nContent-Length: 69\r\nContent-Type: text/plain\r\nDate: Fri, 23 Jun 2023 09:59:13 GMT\r\nServer: nginx/1.18.0 (Ubuntu)\r\n\r\ndata did not match any variant of untagged enum AnnouncableActivities"
```

The full HTTP request dump is:
```
POST /c/android/inbox HTTP/1.1\r\nHost: lemmy.world\r\nUser-Agent: (go-fed/activity v1.0.0) (go-fed/activity v1.0.0)\r\nContent-Length: 318\r\nAccept-Charset: utf-8\r\nContent-Type: application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"\r\nDate: Fri, 23 Jun 2023 09:59:11 GMT\r\nDigest: SHA-256=6Ekw9vpt7coVtbnLXsCcGqENbcTmQYb6wxKv7uOsr9I=\r\nSignature: keyId=\"https://preader-dev.v2.dcas.dev/users/6b91337d-cdcc-4e78-9c90-ef6c539a31e1#main-key\",algorithm=\"hs2019\",headers=\"(request-target) date digest\",signature=\"[REDACTED]\"\r\nAccept-Encoding: gzip\r\n\r\n{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"actor\":\"https://preader-dev.v2.dcas.dev/users/6b91337d-cdcc-4e78-9c90-ef6c539a31e1\",\"id\":\"https://preader-dev.v2.dcas.dev/activities/93a248bd-19b6-407b-83f6-e2fc36f811b5\",\"object\":\"https://lemmy.world/c/android\",\"to\":\"https://lemmy.world/c/android\",\"type\":\"Follow\"}
```

I am able to successfully follow Kbin communities using the same activity. I have tested with other Lemmy instances such as `https://lemmy.ml` and `https://lemmy.blahaj.zone` and all return the same error.

I'm assuming that I've done something wrong but given I don't know Rust very well and the limited ActivityPub documentation, your assistance would be much appreciated.

### Steps to Reproduce

1. Create a `Follow` to a Lemmy community using an external tool (in my case I'm using `https://github.com/go-fed/activity`)
2. Notice that the request fails with an HTTP `400` error
3. Send the same `Follow` to a Kbin community and notice that it succeeds and federated data is received.

### Technical Details

N/A

### Version

N/A

**Comment by Nutomic** [comment]
`to` should be an array, or you can leave it out entirely.

**Comment by djcass44** [comment]
I tried that and Lemmy would successfully  receive the Follow but I would
never receive back an Accept or any federated data. Seems like it is just
swallowing the Follow request

**Comment by Nutomic** [comment]
Could be that the instance you are testing with is overloaded.

**Comment by djcass44** [comment]
Okay so I figured it out. 

* If I remove the `to` field, then `go-fed` just silently drops the request without delivering it.
* If I set the `to` field then `go-fed` will compact it to the short form and Lemmy will not be able to deserialise it.
* If I set the `to` field twice, then `go-fed` cannot compact it and Lemmy is able to deserialise it.

Example of a working request:

```json
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "actor": "https://preader-dev.v2.dcas.dev/users/6b91337d-cdcc-4e78-9c90-ef6c539a31e1",
    "id": "https://preader-dev.v2.dcas.dev/activities/93a248bd-19b6-407b-83f6-e2fc36f811b5",
    "object": "https://lemmy.world/c/android",
    "to": ["https://lemmy.world/c/android", "https://lemmy.world/c/android"],
    "type": "Follow"
}
```

This is obviously janky as hell but does work!

So the issues I see are:
* `go-fed` does not send requests without a `to` field (not Lemmy's problem)
* Lemmy can't deserialise compacted string lists

I'm not a JSON-LD expert so I'm not 100% sure if I'm correct here.

**Comment by Nutomic** [comment]
I tested the activity mentioned in OP, and it gets parsed without any problems. So this seems purely like a problem with go-fed deciding to drop activities in some cases.
