### ISSUE TITLE
[Bug]: Allow users to see their own deleted posts

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#3290]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

A recent commit I did, no longer lets anyone but mods or admins see deleted / removed content. This needs to be altered to allow the creators to see their own deleted / removed content.

### Steps to Reproduce

1. Create a post as a regular user, delete it.
2. No longer see it

### Technical Details

see above

### Version

main

### Lemmy Instance URL

NA

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3286
