### ISSUE TITLE
Put `&page=1` at the end please

### ISSUE THREAD

**Issue by gylotip** [LemmyNet/lemmy#3298]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [x] Is this only a feature request? Do not put multiple feature requests in one issue.
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The URL looks currently like this:
```
https://lemmy.ml/?dataType=Post&listingType=Local&page=1&sort=Active
```
But `&sort=Active` is at the end, while `&page=1` is right before. This is bad design, because `&page=1` is the one that changes every time when scrolling and pressing. This is my issue, because the order looks ugly and doesn't make sense.

### Describe the solution you'd like.

My request is whether you can put `&page=1` at the end of the URL please:
```
https://lemmy.ml/?dataType=Post&listingType=Local&sort=Active&page=1
```
See? It looks so much better. The order makes more sense, because `&page=1` is the one that changes, so it deserves to be the last in the URL.

### Describe alternatives you've considered.

There aren't any alternatives, because this is the only sensible thing where the order makes sense.

**Comment by RocketDerp** [comment]
> Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

**Comment by gylotip** [comment]
@RocketDerp Oops, sorry. I will close this issue and repost it to what you linked.

**Comment by gylotip** [comment]
@RocketDerp Oops, sorry. I will close this issue and repost it to what you linked.
