### ISSUE TITLE
Question: Is releases.md going to be updated?

### ISSUE THREAD

**Issue by cereal7802** [LemmyNet/lemmy#3307]
### Question

I noted that in the lemmy ansible repo it says to check the lemmy changelog for details on changes for each release, but that particular file (RELEASES.md) seems to have last been updated for version 0.17.2. Will this file be getting updated?

**Comment by ross-spencer** [comment]
I notice the changelog is complete on the release page for 0.18 but my ansible upgrade has left the site in a bit of a mess so I am wondering if there's something missing between RELEASES.md and then  the release changelog:

* https://github.com/LemmyNet/lemmy/releases/tag/0.18.0

**Comment by RocketDerp** [comment]
What's the situation with 0.18.3 - is it current now?

**Comment by lionirdeadman** [comment]
It's now current.

**Comment by RocketDerp** [comment]
Thank you
