### ISSUE TITLE
[Bug?]: Database job in CI takes 30mins

### ISSUE THREAD

**Issue by Sebbito** [LemmyNet/lemmy#3308]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Looking around the pipelines for lemmy it seems that pipelines take really long on average. This isn't unusual with bigger projects like lemmy but i did notice something strange:

It's the database that stretches a pipeline to almost 30 minutes.

Look at [this pipeline](https://woodpecker.join-lemmy.org/repos/129/pipeline/331) for an example. All jobs pass in at most 9:22s but the db somehow blocks it from completing. I'm not sure if it is doing anything in the background and I'm just bad at interpreting the logs but it doesn't seem like it should block for **that** long.

There was even [this pipeline](https://woodpecker.join-lemmy.org/repos/129/pipeline/320) that actually timed out.

### Steps to Reproduce

1. Start pipeline
2. Wait till it runs through
3. Inspect db logs (which take the longest)

### Technical Details

/

### Version

any

**Comment by cetra3** [comment]
It's not a bug. The database stays active while all the other steps run

**Comment by Sebbito** [comment]
Oh i see my bad. Since they don't run in parallel the total execution time is whatever the db service displays.

I do have a suggestion to make tho; make more jobs parallel

https://woodpecker-ci.org/docs/usage/pipeline-syntax#group---parallel-execution

Perhaps some of the cargo steps could be in parallel. The steps: prettier_check, cargo_fmt, -check and -clippy could be in one group since they're all related to formatting and perhaps cargo build since that doesn't seem state dependant. I know this isn't a huge gain but maybe saves a couple of minutes.

The other really big time sinks seems to be 

- check_defaults_hjson_updated
- cargo_test
- run_federation_tests

Maybe they can be parallized aswell but then again I'm unsure if they depend on the previous step.

**Comment by Nutomic** [comment]
You can try to setup parallel execution. Anyway as mentioned the db just runs in the background.
