### ISSUE TITLE
[Bug]: websocket connection failed after 0.18.0 upgrade

### ISSUE THREAD

**Issue by zhongkechen** [LemmyNet/lemmy#3321]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Lemmy was set up using docker composer. It worked perfectly using 0.17.4.

Updated lemmy and lemmy-ui image tags from 0.17.4 to 0.18.0 and pull and restarted docker containers. The browser is throwing exception in console:

```
client.js:2 WebSocket connection to 'wss://xxxx.com/api/v3/ws' failed: 
e.tryConnect @ client.js:2
eruda:8 Websocket closed.
Rt.forEach.n.<computed> @ eruda:8
eruda:8 Retrying websocket connection...
```

### Steps to Reproduce

1. set up Lemmy 0.17.4 using docker-compose and everything works
2. update the lemmy/lemmy-ui image tag from 0.17.4 to 0.18.0 and restart
3. wss connection is no longer established

### Technical Details

- Linux/docker
- WebSocket connection to 'wss://xxxx.com/api/v3/ws' failed

### Version

0.18.0

**Comment by hagarashi8** [comment]
AFAIK, websocket API was removed entirely.

**Comment by zhongkechen** [comment]
If it's been removed, why is the UI code still making ws connections?

**Comment by hagarashi8** [comment]
> If it's been removed, why is the UI code still making ws connections?

That's valid issue, but it's Lemmy-ui issue

**Comment by sunaurus** [comment]
I assume you have a old version of the UI cached. How have you configured caching for client.js on your instance?

**Comment by zhongkechen** [comment]
Log out and re-login fixed the issue for me. I'm not sure if this is a code bug or an issue with my  env setup.
