### ISSUE TITLE
Pre-Filled report reasons

### ISSUE THREAD

**Issue by techno156** [LemmyNet/lemmy#3324]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There aren't very many reasons why a user might want to report a post to moderators, and the moment, all report reasons have to be entered by hand every time.

The problem with this system is that there can be multiple variants of the same report reason.

As an example, if a comment or post is spam, it may be reported as "spam", "bot", "scam", "advertisement", "spammer", so on, which would clog up any report queues, particularly if there is a report grouping system in place.

From a user standpoint, in the event of a spam wave, it is also easier to report multiple posts for spam or other rule-breaking issues if there is a pre-filled option that can be easily selected, rather than having to manually type out the report reason for every post, particularly if there are multiple posts/comments that need to be reported, such as during a spam wave.

### Describe the solution you'd like.

Ideally, there would be a list of pre-filled reasons, optionally set/modified by instance operators, and community moderators, which users can use to report a post in lieu of writing their own reasons.

There can be an additional, (configurable?) optional setting to allow for custom report reasons, such as if the post needs to reported for a reason that is not on the pre-filled list.

### Describe alternatives you've considered.

Another alternative might be to have a fixed set of reasons that are set by Lemmy developers, similar to how Twitter handles its reports. While this would simplify the necessary amount of code (as there would be no need to implement a method of storing and modifying the report reasons), it would not adequately address posts or comments that break community rules, but not instance rules.

Another alternative is to remove report reasons entirely, limiting them to moderators, should they need to escalate posts to instance operators, with users only being able to submit a generic report flagging posts for moderators to look at, similar to the older reporting scheme used by Reddit's Alien Blue app, or some forums. While this would simplify the reporting stream, it will also cause problems by increasing moderator workload, issue that would only be amplified if the community is large.

### Additional context

This is related to https://github.com/LemmyNet/lemmy-ui/issues/1505, which is the front end request for the same feature. Request has been posted here and on lemmy-ui, as it requires both front and back end changes to implement.

**Comment by dessalines** [comment]
I don't see us implementing this, especially in a way that would work for every language. I can re-open if someone wants to take it on tho.

**Comment by Nutomic** [comment]
These prefilled reasons could be hardcoded in lemmy-ui, much simpler to implement.
