### ISSUE TITLE
[Bug]: new posts appear above top posts

### ISSUE THREAD

**Issue by 3m4r5** [LemmyNet/lemmy#3332]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

when you sort by "[Top All Time](https://lemmy.world/home/data_type/Post/listing_type/Local/sort/TopAll/page/1)" new posts appear on top

### Steps to Reproduce

1. open this url: https://lemmy.world/home/data_type/Post/listing_type/Local/sort/TopAll/page/1
2. wait for less than a minute

### Technical Details

there are no errors

### Version

BE 0.17.4

### Lemmy Instance URL

lemmy.world

**Comment by RocketDerp** [comment]
> Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

it is widely reported, "the removal of websockets", and servers upgraded to 0.18.0 seem to no longer have the problem. I hope this helps.
