### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by KarkanAlzwayed** [LemmyNet/lemmy#3333]
### Question

I'm trying to sign into Lemmy through Jerboa. Every time I do so, I get a notification that tells me that 17.4 server is too low and something about either joing 18 or signing in with another instance. I signed up to lemmy.world and when I try other instances I get "incorrect log in". Not sure how to bypass this. Signing in through "connect for Lemmy" works fine, but I want to use jerboa, as I like it better. 
Any idea how to get through this?
Thanks

**Comment by RocketDerp** [comment]
There is a /c/Jerboa community on Lemmy: https://lemmy.ml/post/1455993

**Comment by KarkanAlzwayed** [comment]
Thank you. Sorry, this is all new to me and I'm still figuring things out. That helped. Much appreciated
