### ISSUE TITLE
[Bug]: Editing comments increases the comment count on federated instances

### ISSUE THREAD

**Issue by gxtu** [LemmyNet/lemmy#3334]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When you edit a comment on a remote federated instance (i.e. not your home instance), it appears to count each edit as a new comment. Looking at the post through your home instance shows the correct number of comments, but when opening it on the remote instance it shows an incorrect higher comment count depending on how often the comment was edited.

### Steps to Reproduce

1. Create/open a post on a remote federated instance
2. Make a comment on that post
3. Edit the comment (several times)
4. On your home instance the comment count stays the same, but increases on the remote instance with every edit

### Technical Details

[I don't have any logs or other details since I don't run either Lemmy instance]

### Version

Home instance: 0.18.0, Remote instance: 0.17.4

### Lemmy Instance URL

discuss.tchncs.de

**Comment by RocketDerp** [comment]
See also Issue #3023

**Comment by Nutomic** [comment]
I cant reproduce this anymore, seems to be fixed.

https://ds9.lemmy.ml/post/9640
https://enterprise.lemmy.ml/post/417789
