### ISSUE TITLE
Communities portability:Allow communities to migrate to different instances and merge with other communities 

### ISSUE THREAD

**Issue by riparise** [LemmyNet/lemmy#3336]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The fast organic growth of Lemmy lead to some redundancies (similar communities in different instances) and many communities found out there is a more suitable servers for their context.

In order to allow the ecosystem to re-organize, it is important that communities are allowed to migrate to different servers and allow them to merge. 

Furthermore, not every community is able to host its own server. In practice, large lemmy servers will concentrate many communities with different world views.

The community should be able to be independently and freely migrate in case of disagreement with the instances owners, to avoid a concentration of power (yep, that is reddit-trauma)

### Describe the solution you'd like.

1. Communities should be able to migrate to other servers

2. Communities should be able to merge keeping they post history.

3. Communities mods should not be forcefully removed by instance admins. If an admin forcefully do so, the federation should penalize expelling the server.

4. Instance admins should be able to expel a community without penality from the federation. The community would need a grace period to either find a new server to host it or close for good.

5. Mods should be able to backup independently it's community completely, and verify it's identity (GPG) for the rest of the federation in case of conflict.

### Describe alternatives you've considered.

The current architecture of Lemmy is actually very good and I do not think my proposal is the only or the best way to move forward. Maybe not even a *good* way.

I imagine that there are thousands of issues with this proposal (for example username duplication while merging) but I believe this is an interesting discussion to start at some point.

**Comment by sunaurus** [comment]
Hey! There are already several open issues for this, for example https://github.com/LemmyNet/lemmy/issues/3057. It would be more productive to add to existing issues rather than opening new ones!

**Comment by riparise** [comment]
Closing due to redundancy with #3057

**Comment by lionirdeadman** [comment]
Closed since it seems to be the intent :)
