### ISSUE TITLE
An option to set the default amount of posts per-page (by the user and by communities)

### ISSUE THREAD

**Issue by 001Guy001** [LemmyNet/lemmy#3340]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When entering a community there are currently too few posts displayed which means that very recent posts can drown out less recent ones when a community is active enough. Having to manually go back pages might deter users from checking older posts.

### Describe the solution you'd like.

An option to show more posts per-page by default (specifically in communities)

This can be done by the user to apply to every community they view, and by each community (the user setting would override the community setting)

### Describe alternatives you've considered.

NA

**Comment by M4rtineski** [comment]
Quite funny how this issue was the last one on first page

![image](https://github.com/LemmyNet/lemmy/assets/137183342/da15cb85-d814-47b3-b851-a1236f5240ba)

**Comment by Nutomic** [comment]
The backend doesnt have any specific number of posts per page, each frontend can define that on its own.
