### ISSUE TITLE
[Bug]: config.hjson breaks when using quoteless string starting with a number

### ISSUE THREAD

**Issue by db0** [LemmyNet/lemmy#3341]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I wasted a lot of hours today trying to upgrade my lemmy to 0.18.0 because I kept getting this error

`lemmy_1     | thread 'main' panicked at 'Failed to load settings file, see documentation (https://join-lemmy.org/docs/en/administration/configuration.html): LemmyError { message: None, inner: ExpectedF64 at 6:26 at "\n    database: ", context: SpanTrace [] }', crates/utils/src/settings/mod.rs:20:20
`

As my config.hjson has not been changed since 0.17.3 I was stumped and I was following a red-herring trying to figure out why the docker-compose did not set it up correctly etc. 

Turns out, mod.rs was not parsing config.hjson correctly. You see my config.hjson had quoteless strings, like so

```

  database: {
    host: xxx.xxx.xxx.xxx
    database: database_name
    user: username
    password: "password"
    pool_size: 50
  }
  ```
  
  This is allowed in the [hjson specification](https://hjson.github.io/)
  
 >Quoteless Strings

> You can specify strings without quotes.

> In this case only one value per line and no commas are allowed.

However 0.18.0 decided that this is not OK, and started failing.

I am not certain if it's all quoteless string, or just the DB IP btw. it could be just the IP being given as quoteless as it mentions `ExpectedF64`

Once I quoted all of them, it went through.

### Steps to Reproduce

1. Add a quoteless string as your database IP address
2. run docker-compose

### Technical Details

Debian 11

This is the only log

`lemmy_1     | thread 'main' panicked at 'Failed to load settings file, see documentation (https://join-lemmy.org/docs/en/administration/configuration.html): LemmyError { message: None, inner: ExpectedF64 at 6:26 at "\n    database: ", context: SpanTrace [] }', crates/utils/src/settings/mod.rs:20:20
`

### Version

BE 0.18.0

### Lemmy Instance URL

https://lemmy.dbzer0.com

**Comment by sunaurus** [comment]
I can confirm that if an unquoted IP is passed to `host`, the configuration parsing will fail. Seems that the issue only occurs if the value of `host` starts with a number - if it starts with a letter, then unquoted values work fine.

**Comment by db0** [comment]
Cheers, I clarified the title as well

**Comment by dessalines** [comment]
Closing as this is an upstream issue. If someone fixes it in deser-hjson, we will likely pull in the newer version.
