### ISSUE TITLE
add option to not recompress images already compressed

### ISSUE THREAD

**Issue by lordkitsuna** [LemmyNet/lemmy#3346]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

After testing media upload using webp and jpg images on my own instance i found that lemmy is taking webp images that are already highly compressed and efficient and recompressing them. this is causing generational loss and making images look terrible. I poked around my various configs to see if i could disable this behavior but i cant find anything. 

you can see a very clear example of the generational losses here https://slow.pics/c/UEYha5TJ this is after only 2 uploads (upload original, download the transcode, upload that) 

### Describe the solution you'd like.

add a server admin option either in the ui or using config variables that will allow us to disable transcoding of already lossy media. it makes sense to want to compress lossless media but transcoding already lossy media just makes them look terrible as its done more and more and in many cases doesn't even lead to significant savings. 

it seems like odd behavior to transcode already lossy webp when as far as i can tell from testing lemmy does not touch jpg or png whatsoever other than stripping out metadata, i can get perfect checksum matches on uploaded png but i get entirely different sizes with clear signs of generational loss in the resulting image when uploading webp.

### Describe alternatives you've considered.

i suppose i could just use png exclusively but that seems rather wasteful.

**Comment by Nutomic** [comment]
Image compression is entirely handled by pict-rs.
