### ISSUE TITLE
Federate Pinned posts from Kbin Magazines

### ISSUE THREAD

**Issue by XiaoKe89** [LemmyNet/lemmy#3351]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Similar to a previous feature request :https://github.com/LemmyNet/lemmy/issues/2640

Pinned posts from Kbin Magazines are not being federated over when federating begins on Lemmy. It looks like it was previously fixed for Lemmy to Lemmy communities but it looks like it's still happening on communities that originate from Kbin instances.

Example this community from Kbin.social has 2 pinned posts: https://kbin.social/m/catsubs
But when viewed on lemmy.world: https://lemmy.world/c/catsubs@kbin.social it only shows posts after federation began meaning the important information in the pinned post is not able to be viewed inside lemmy instances.
Unsure if this is something that needs to change on lemmy's side or Kbin's side. Thought I'd check here first since it relates to a previous request on lemmy

### Describe the solution you'd like.

When federation begins it should check for pinned posts and federate those over as well so that important information can be viewed on lemmy instances

### Describe alternatives you've considered.

The only current solution to this is to open it directly on Kbin which can be very cumbersome especially since most times you wont know there is a pinned post to actually go look for.

Another alternative is to ask the Magazine owner to repost the pinned post but they may not be willing to do so and would have to do it everytime a new instance begins federating with them which would not be ideal

**Comment by Nutomic** [comment]
Lemmy uses the `featured` collection to federate pinned posts, same as Mastodon. Looking at the kbin Activitypub response, it doesnt include that collection. So its a problem on their side.

**Comment by XiaoKe89** [comment]
> Lemmy uses the `featured` collection to federate pinned posts, same as Mastodon. Looking at the kbin Activitypub response, it doesnt include that collection. So its a problem on their side.

Ah gotcha! Good to know, I'll go ahead and open a feature request on Kbin then. Thank you!
