### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by k5jat** [LemmyNet/lemmy#3358]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I keep getting the following error message and I think it could give just a little more information.

```
lemmy_1     | 2023-06-26T12:59:57.947783Z  WARN lemmy_server::root_span_builder: Domain is not in allowlist
lemmy_1     |    0: lemmy_apub::activities::verify_person_in_community
lemmy_1     |              at crates/apub/src/activities/mod.rs:50
lemmy_1     |    1: lemmy_apub::activities::voting::vote::verify
lemmy_1     |              at crates/apub/src/activities/voting/vote.rs:57
lemmy_1     |    2: lemmy_apub::activities::community::announce::receive
lemmy_1     |              at crates/apub/src/activities/community/announce.rs:141
lemmy_1     |    3: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=POST http.scheme="http" http.host=lemmy.website http.target=/inbox otel.kind="server" request_id=b53bc7b8-8299-47d1-8be8-6bc645ca6353
lemmy_1     |              at src/root_span_builder.rs:16
lemmy_1     | LemmyError { message: None, inner: Domain is not in allowlist, context: SpanTrace [{ target: "lemmy_apub::activities", name: "verify_person_in_community", file: "crates/apub/src/activities/mod.rs", line: 50 }, { target: "lemmy_apub::activities::voting::vote", name: "verify", file: "crates/apub/src/activities/voting/vote.rs", line: 57 }, { target: "lemmy_apub::activities::community::announce", name: "receive", file: "crates/apub/src/activities/community/announce.rs", line: 141 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=lemmy.website http.target=/inbox otel.kind=\"server\" request_id=b53bc7b8-8299-47d1-8be8-6bc645ca6353", file: "src/root_span_builder.rs", line: 16 }] }
```
On which side is this allowlist on? What domain? Is it mine? Is it theirs?

### Describe the solution you'd like.

Adding a qualifier like "Your" or just adding the domains to the error message. Something like:

WARN lemmy_server::root_span_builder: Your Domain is not in remote allowlist for example.com

Or something like:

WARN lemmy_server::root_span_builder: Domain example.com is not in local allowlist.

### Describe alternatives you've considered.

There's not really an alternative. This error gives a lot of information, except where the error is coming from.

### Additional context

I've been getting these a LOT and I'd like to find out where it's coming from so I can contact the instance admin, if it's not on my side, and ask to have my instance added to the allowlist. I feel like this error may be coming from lemmy.ml since my instance isn't getting comments from that instance, but I can't tell if that's it or not.

**Comment by Nutomic** [comment]
This message must be because of the federation allowlist configured on your own instance. You can grep the code for this string to find/change the error message.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3944
