### ISSUE TITLE
Don't tag user in comments when tagged in original post

### ISSUE THREAD

**Issue by WesleyAC** [LemmyNet/lemmy#3367]
It seems like when a user is tagged in a top-level post, they are also tagged in all comments on that post, which is confusing (if the tagged user is using Mastodon/etc, at least, not sure how it's handled natively on Lemmy) and a potential vector for abuse. It would be better to have them mentioned in the top-level post, but not in any comments unless someone specifically mentions them in the text of the comment.

See someone being confused about this here: https://mas.to/@TechConnectify/110613804504504577

**Comment by WesleyAC** [comment]
Looking at the activitypub objects involved here, it's actually less clear to me what's going on (since I don't even see a `Mention` tag on the original post, let alone the comments). But it's clear that there's some kind of problem here.

**Comment by Nutomic** [comment]
Lemmy always tags the creator of the parent comment/post. Removing this would cause federation problems. Also you didnt fill in the issue template.

**Comment by WesleyAC** [comment]
@Nutomic this isn't about the creator of the post, it's about someone who is mentioned in the initial post. I didn't fill out the template since it was unclear to me whether this was a bug or intended (but ill-thought out) behaviour.
