### ISSUE TITLE
A system for sharing usernotes and ban notes across communities to deal with spammers, bots, trolls, bigots, etc.

### ISSUE THREAD

**Issue by 001Guy001** [LemmyNet/lemmy#3368]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

If a spammer/problematic user/annoying bot/etc. appears in a specific community, that community should be able to alert all other communities about that account (somewhat similar to the idea of u/BotDefense and u/BotTerminator from Reddit, but more encompassing and using a different system)

### Describe the solution you'd like.

When removing a user's post/comment or banning a user a mod could choose to share the usernote/ban note to other communities.

Each community could choose to auto-filter/auto-report a user's content if X amount of other communities have shared notes about them.

This can be done for the overall amount of notes the user has, or separately for each category of notes where each community could choose the amount of notes-per-category that would cause an action. For example, 3 spam notes, or 1 racism note.

A community could also choose if it only wants to count several notes in the same category from a single community as one note so that there could be a second and third opinion from different communities before any action is taken (meaning, if the user has 3 pieces of content noted as spam in one community then they will only count as 1 by the other communities that choose that option)

Additional notes:

- Each note will have a link to the offending content so other communities could check it out (the content should be visible from clicking the note even if it's not visible otherwise since it's removed, maybe the content can appear in a small tooltip popup instead of having the note link be active)
- Communities could choose to have different actions for different categories (for example, report spam, and filter transphobia)
- Communities could choose to ignore specific categories. For example, a community that revolves around self-promotion could ignore that category of notes.
- Communities could whitelist users if they see that they're not problematic in their community.
- After X amount of (shared) notes the system could automatically escalate the user for an admin review for a possible warning/suspension/ban/etc.
- A ban note and a usernote about the same piece of content would be counted as 1 note.

Possible categories:

- Racism, xenophobia, etc.
- Homophobia, transphobia, etc.
- Trolling
- Spam: link farming
- Spam: self-promotion
- Reply bot
- Repost bot
- Suspect AI bot

### Describe alternatives you've considered.

NA

**Comment by Nutomic** [comment]
Thats what the mod log is for.
