### ISSUE TITLE
[Bug]: Remove users content from defederated instances

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy#3371]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When a user creates a post and their instance defederates from another instance, the post is not deleted in the defederated instance and he can no longer delete that post from the defederated instance. The request is to automatically delete all content when defederating from an instance.

### Steps to Reproduce
1. Create a post on an instance.
2. Defederate the instance from another instance.
3. Check if the post is still present in the defederated instance.

### Version
0.18

**Comment by Nutomic** [comment]
Yes thats how federation works. Anyway no sense in discussing this with a deleted user account.
