### ISSUE TITLE
Add the possibility to create new communities in other instances

### ISSUE THREAD

**Issue by ogarcia** [LemmyNet/lemmy#3373]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently there are instances that are dedicated to specific topics, for example [eslemmy](https://eslemmy.es/) is an instance very focused on Spanish topics so it would be logical to think that if I want to create a community about a city in Spain, I would do it in that instance, but I can't because my account is registered in another instance.

### Describe the solution you'd like.

It would be very interesting to have the possibility to create communities in other instances. To avoid problems, what could be done is that these new communities created by third parties would have to be approved by a moderator of the instance.

### Describe alternatives you've considered.

There is currently no alternative to this beyond creating a new account on the new instance or asking someone who has an account on that instance to create the community for you.

**Comment by Nutomic** [comment]
You can ask a user there to create the community and add you as mod. Allowing arbitrary community creation over federation would create too many moderation problems I think.

**Comment by ogarcia** [comment]
I think there should be an official way to make such requests.

It's not so much that it automatically allows you to create a community on a third-party instance, but that you can make a request to that instance using your credentials.

I know it's a bit complicated, but I think there should be some official solution to this beyond asking someone from that third party instance to create the community for you.

**Comment by dessalines** [comment]
There shouldn't be a way to do this other than asking them. You can only create communities on your own instance.
