### ISSUE TITLE
Add a "confidence" comment sort option

### ISSUE THREAD

**Issue by academician** [LemmyNet/lemmy#3381]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

While I don't think Lemmy should necessarily try to have total feature parity with Reddit, one feature that I think is worth implementing is a "confidence" sort option for comments - what Reddit calls "Best" in the sort dropdown. This sorts comments based on the proportion of upvotes to downvotes, and maps it onto a binomial proportion confidence interval.

### Describe the solution you'd like.

[Here](https://web.archive.org/web/20100305052116/http://blog.reddit.com/2009/10/reddits-new-comment-sorting-system.html) is Reddit's original announcement post for the feature, written by Randall Munroe from XKCD, and [here](https://medium.com/hacking-and-gonzo/how-reddit-ranking-algorithms-work-ef111e33d0d9#7314) is an article about how the ranking algorithm works under the hood. Essentially, it uses a [Wilson score interval](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Wilson_score_interval) based on the ratio of upvotes to downvotes.

Expressed as a Rust function, Reddit's version looks like this:

```rust
fn confidence(ups: f64, downs: f64) -> f64 {
    let n = ups + downs;
    if n == 0.0 {
        return 0.0;
    }

    let z = 1.281551565545;
    let p = ups / n;

    let left = p + 1.0 / (2.0 * n) * z * z;
    let right = z * (p * (1.0 - p) / n + z * z / (4.0 * n * n)).sqrt();
    let under = 1.0 + 1.0 / n * z * z;

    return (left - right) / under;
}
```

### Describe alternatives you've considered.

The algorithm doesn't have to be replicated exactly, but I do find that it is a typically a better way of viewing comments on a post instead of "hot" (which takes time into account) or "top" (which does not take ratio of downvotes into account). In particular the magic number expressed as `z` above relates to an 85% confidence interval, which works well but could be played with.

There are also other intervals that could be considered (Wikipedia [lists several](https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval)), but the Wilson score interval seems common for this task. I also found [this article](https://possiblywrong.wordpress.com/2014/05/31/reddits-comment-ranking-algorithm-revisited/) which suggests several other alternatives, including introducing randomness as a way of representing uncertainty.

### Additional context

The name for the sort option is somewhat bikesheddable, so in my opinion we should just pick something. "Best" is what Reddit uses, and "confidence" or "consensus" would also be reasonable. I'd just go with "best" to ease transition.

**Comment by dullbananas** [comment]
The name should make the purpose clear. "Consensus" is better at this than "confidence" or "best".

**Comment by academician** [comment]
> The name should make the purpose clear. "Consensus" is better at this than "confidence" or "best".

I agree that "Consensus" is the most pithiest, at least for summing up the intent of the particular sort algorithm proposed. However, I'm not certain that lay users will really understand what it means, which I think is why Reddit went with "Best". "Best" also steers users toward that particular sort instead of others like "Top" and "Hot", which may or may not be desirable from a human behavior point of view.

For what it's worth, Reddit's code called it [confidence](https://github.com/reddit-archive/reddit/blob/master/r2/r2/lib/db/_sorts.pyx#L70) as of 2015, which is the most *technically* correct single word for it. (looking at that code, it's also interesting to note that they also pre-calculate about 40k worth of confidence scores as an optimization)

**Comment by dessalines** [comment]
I can re-open if someone wants to take this on, but I suggest reading the top linked article from my comparison of ranking algos, on why reddit's comment ranking is by far the worst in practice. https://join-lemmy.org/docs/contributors/07-ranking-algo.html

In short, commenting "first" has an extremely high chance of being the top comment, as is shown by a big-data analysis; the worst possible result you could have for a fair comparison.

**Comment by academician** [comment]
@dessalines The [article linked](https://minimaxir.com/2016/11/first-comment/) appears to be an analysis of top comments based on "score". Ie., "top" sort - not "best" sort, which accounts for upvote/downvote ratio. 

In my experience on Reddit, "Best" accounted for recency much better, without measuring it directly at all - particularly where it matters, on posts with many comments and a lot of voting activity. "Good" comments at the bottom get pushed up to the top if their ratio is better than the top comments' ratios. According to [Randall Munroe's post](https://web.archive.org/web/20100305052116/http://blog.reddit.com/2009/10/reddits-new-comment-sorting-system.html) about it when it was announced, accounting for recency was the whole point "Best" was added:

> reddit is heavily biased toward comments posted early. [...] The higher something is listed, the more likely it is to be read (and voted on), and the more votes the comment gets. It's a feedback loop that cements the comment's position, and a comment posted an hour later has little chance of overtaking it -- even if people reading it are upvoting it at a much higher rate.
>
> [...]
>
> There's a solution [to the problem of recency bias in top sort], and it's the new 'Best' ranking. When a few people have voted on a comment, you get a rough idea of its quality. The more people who vote on it, the better an idea you get of where it 'should' ultimately end up. With this algorithm, you quantify exactly how much you can tell about a comment from a limited number of votes.
>
> If everyone got a chance to see a comment and vote on it, it would get some proportion of upvotes to downvotes. This algorithm treats the vote count as a statistical sampling of a hypothetical full vote by everyone, much as in an opinion poll. It uses this to calculate the 95% confidence score for the comment. That is, it gives the comment a provisional ranking that it is 95% sure it will get to. The more votes, the closer the 95% confidence score gets to the actual score.

He also addresses some of the same criticisms I have of Lemmy's "Hot" ordering (see below):

> The idea [of "hot" ordering"] was that it would make comments lose position after a certain time, but this led to even good comments dropping down to the bottom, and if you returned to the post in a day or two the ordering was completely nonsensical.

## On Lemmy's Hot Sot

The reason I proposed adding this is that I personally find the comment sort options on Lemmy to be insufficient for what I like. On same-day posts, I see recent comments bubbled to the top what seems like *too* often - eg, on [this post](https://lemmy.world/post/7260414?scrollToComments=true):

![image](https://github.com/LemmyNet/lemmy/assets/6391/8316b460-a30b-4da0-b040-053d7aea677f)

It's odd to me that two comments with only 10 upvotes appear above a 24u/0d comment, and a 26u/0d comment is even further down the page. I suppose it's a matter of taste, but IMO that favors recency too much.

On older posts ([example](https://lemmy.world/post/6018317?scrollToComments=true)), "Hot" might as well just be "Top" - for example, I see [this](https://lemmy.world/comment/4000890) somewhat ratio'ed comment (107u/25d) ranked higher than [this](https://lemmy.world/comment/3932252) comment with only one downvote (69u/1d). Using the confidence sort from my OP, the second comment would be ranked significantly higher than the first one, with ranks of "0.7631853" and "0.9534418", respectively. On old posts especially, that's a huge benefit.

Now, maybe Lemmy's existing "Hot" algorithm could merely be tweaked to account for vote ratio better. There may be a middle ground. But honestly, "Best" sort for comments worked *really* well for me on Reddit. I rarely felt like I was seeing comments at the top that didn't deserve to be there over more recent comments further down. And if I did, I upvoted the recent comment, and the algorithm would shift the sort - and if enough other people agreed, then the sorting would get fixed.

**Comment by dessalines** [comment]
You're willing to take this one on? Because our tiny dev team doesn't have time to.
