### ISSUE TITLE
[Bug]: Trying to subscribe to a non-local instance always returns not subscribed

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#3384]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

This was originally opened as a [UI issue](https://github.com/LemmyNet/lemmy-ui/issues/1581). After some digging, the issue appears to be on the backend.

I tested this out by using the js client to make a request with my account.
```typescript
import { LemmyHttp } from "lemmy-js-client";

const client = new LemmyHttp("https://lemmygrad.ml");

const doStuff = async () => {
  const { jwt } = await client.login({
    password: "REDCATED",
    username_or_email: "REDACTED",
  });

  const res = await client.followCommunity({
    auth: jwt ?? "",
    community_id: 258,
    follow: true,
  });

  console.log(res);
};

doStuff();
```

This request tries to follow ask lemmy on lemmy.ml from a lemmygrad account. This is the response I get back:
```javascript
{
  community_view: {
    community: {
      id: 258,
      name: 'asklemmy',
      title: 'asklemmy',
      description: 'A loosely moderated place to ask open ended questions\n' +
        '\n' +
        'If your post is\n' +
        '\n' +
        '1. Open ended \n' +
        '2. Not offensive (At this point, I do not have the bandwidth to moderate partisan political discussions)\n' +
        '3. **Not regarding lemmy support** ([!lemmy_support@lemmy.ml](https://lemmy.ml/c/lemmy_support) )\n' +
        '4. not ad nauseam inducing (please make sure its a question that would be new to most members)\n' +
        '5. [An actual topic of discussion](https://lemmy.ml/post/1239589)\n' +
        '\n' +
        'it’s welcome here!',
      removed: false,
      published: '2019-04-25T04:58:33.886275',
      updated: '2023-06-14T00:05:37.871496',
      deleted: false,
      nsfw: false,
      actor_id: 'https://lemmy.ml/c/asklemmy',
      local: false,
      icon: 'https://lemmy.ml/pictrs/image/UsuGsKF2fl.png',
      banner: 'https://lemmy.ml/pictrs/image/XKAjSZCX2P.png',
      hidden: false,
      posting_restricted_to_mods: false,
      instance_id: 339
    },
    subscribed: 'NotSubscribed',
    blocked: false,
    counts: {
      id: 204,
      community_id: 258,
      subscribers: 180,
      posts: 1773,
      comments: 33852,
      published: '2019-04-25T04:58:33.886275',
      users_active_day: 911,
      users_active_week: 3618,
      users_active_month: 7815,
      users_active_half_year: 7986,
      hot_rank: 0
    }
  },
  discussion_languages: []
}
```

Notice that subscribed is `NotSubscribed`.

Compare this to when I try to subscribe to a local community:
```javascript
{
  community_view: {
    community: {
      id: 3957,
      name: 'leftistunix',
      title: 'Linux for Leftists',
      description: 'A Community for all leftists wanting to join and being part of a community that talks about Linux, Unix and the Open-Source Community',
      removed: false,
      published: '2021-04-14T06:10:46.277451',
      updated: '2023-06-24T10:32:37.868872',
      deleted: false,
      nsfw: false,
      actor_id: 'https://lemmygrad.ml/c/leftistunix',
      local: true,
      icon: 'https://lemmygrad.ml/pictrs/image/f0056071-6839-4146-9742-374509ee5fd9.png',
      banner: 'https://lemmygrad.ml/pictrs/image/34095db5-670e-45ba-957c-745ec014abe5.jpeg',
      hidden: false,
      posting_restricted_to_mods: false,
      instance_id: 42
    },
    subscribed: 'Subscribed',
    blocked: false,
    counts: {
      id: 374,
      community_id: 3957,
      subscribers: 532,
      posts: 65,
      comments: 735,
      published: '2021-04-14T06:10:46.277451',
      users_active_day: 2,
      users_active_week: 12,
      users_active_month: 61,
      users_active_half_year: 79,
      hot_rank: 0
    }
  },
  discussion_languages: []
}
```

Subscribed is subscribed, as expected.

### Steps to Reproduce

1. Go to community hosted on an instance other than your own.
2. Try to subscribe to it.
3. There is no subscribe button, just the text "Subscribe".

### Technical Details

I could not reproduce this locally and I do not have access to the logs of affected instances.

### Version

0.18

### Lemmy Instance URL

programming.dev

**Comment by RocketDerp** [comment]
Have you tried this code against a 0.17.4 server? I think it may have been the same.

From everything I have witnessed in testing 30+ servers with this behavior, doing it thousands of times. It requires the remote server to respond. If the remote server is offline at the time of your request you are 'pending' in the database and not yet subscribed. It requires the remote server to respond properly.

Even with 0.17.4 I saw this behavior and it would often work while taking 10 to 15 seconds.  And other times the communications between servers would fail and it would stay stuck in pending on the local database.
