### ISSUE TITLE
Add "blocked" state to GetPersonDetails

### ISSUE THREAD

**Issue by JakeShirley** [LemmyNet/lemmy#3387]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There doesn't seem to be a way to know if you are blocking a user other than when their content appears.  

### Describe the solution you'd like.

It would be nice to know if the other person is blocked when trying to get their details with `GetPersonDetails`.

### Describe alternatives you've considered.

Caching this client side but that sounds quite janky.

**Comment by dessalines** [comment]
I don't think this is a good idea to add, because it essentially overrides the block, and lets you see their content.
