### ISSUE TITLE
[Bug]: person_view.counts.post_score and .comment_score don't match the total post/comment scores

### ISSUE THREAD

**Issue by Dakkaron** [LemmyNet/lemmy#3393]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When doing an a REST call to /api/v3/user?username=someuser, I get something like this:

 ```
 'person_view': {
    'counts': {
      'id': ...,
      'person_id': ...,
      'post_count': 14,
      'post_score': 448,
      'comment_count': 321,
      'comment_score': 71
    }
```

I checked these value against the total score of all my posts and comments, and while the count is correct, the score is not.

The post score is off by ~20%, but the real comment score is more than 20x of what this endpoint reports.

### Steps to Reproduce

1. Do a REST call to /api/v3/user?username=[someuser]
2. Compare the total scores with the sum of the scores of all posts/comments of that user

### Technical Details

I got the scores of all posts/comments using the same endpoint and the pagination to fetch all comments.

Here's a Python (3.6+) snippet to demonstrate the issue:

```
import requests
import math

INSTANCE_URL = "https://feddit.de"
TARGET_USER = "ENTER_USER_NAME_HERE"

LIMIT_PER_PAGE = 50

l = Lemmy(INSTANCE_URL)

res = requests.get(f"{INSTANCE_URL}/api/v3/user?username={TARGET_USER}&limit={LIMIT_PER_PAGE}").json()

totalPostScore = 0
totalCommentScore = 0
page = 1
while len(res["posts"])+len(res["comments"]) > 0:
	totalPostScore += sum([ x["counts"]["score"] for x in res["posts"] ])
	totalCommentScore += sum([ x["counts"]["score"] for x in res["comments"] ])
	
	page += 1
	res = requests.get(f"{INSTANCE_URL}/api/v3/user?username={TARGET_USER}&limit={LIMIT_PER_PAGE}&page={page}").json()

print("Post score from API:      ", res["person_view"]["counts"]["post_score"])
print("Calculated post score:    ", totalPostScore)
print("Comment score from API:   ", res["person_view"]["counts"]["comment_score"])
print("Calculated comment score: ", totalCommentScore)
```

### Version

0.17.4

### Lemmy Instance URL

https://feddit.de

**Comment by dropdevrahul** [comment]
Can i pick this up?

**Comment by Mubelotix** [comment]
See https://github.com/aeharding/voyager/issues/312

**Comment by dessalines** [comment]
Oh yeah we forgot to remove those karma scores from the API.

Also though I can think of a number of reasons why they would be off, because the triggers there are imperfect; people deleting comments, removing their accounts, etc.

**Comment by Nutomic** [comment]
These fields are used for person sort, so the calculation should be fixed and also fields marked as `#[serde(skip)]`.

**Comment by aeharding** [comment]
Hello! Certain apps such as Voyager use these fields for user profiles. I understand the values aren't correct at the moment, but they work well enough. I also understand some people don't like showing "karma" for users, but some people do (and it's a helpful tool for modding).

Could these fields remain for apps that choose to show them?

<img width="797" alt="image" src="https://github.com/LemmyNet/lemmy/assets/2166114/1fb3ee24-a994-4917-9076-0de55c087df9">

**Comment by aeharding** [comment]
@dessalines I see, thanks for the reply! I'll remove from Voyager then. Perhaps in the future, user scores could be exposed in `CommentReportView` (reporter + reportee) to help moderate?

**Comment by dessalines** [comment]
No probs. I could see that potentially having value for mods (IE to find troll accounts with negative total scores), but also it looks like `CommentView` includes `CommentAggregates`, so the downvote counts for that comment are shown. Its probably not too necessary, as on should probably go into their history anyway, rather than just looking at a person's karma score.
