### ISSUE TITLE
Default database.pool_size is very low

### ISSUE THREAD

**Issue by phiresky** [LemmyNet/lemmy#3394]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The config parameter `database.pool_size` is passed as `max_size` to deadpool. On production setups, that parameter should be at least 50-100, otherwise all database queries are bottlenecked on the 5 available connections even if both the database and the rust process have available resources.

### Describe the solution you'd like.

I'd propose to just default the parameter to 100, since this parameter is just a maximum, and connections should be allocated on-demand by deadpool. It just needs to be less than the `max_connections` postgresql.conf parameter.

see also: https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.PoolConfig.html

I just verified that even with a limit of 100 it does not allocate 100 connections at startup by looking at `select count(*) from pg_stat_activity`. I did not verify if it releases connections back after a spike.

### Describe alternatives you've considered.

It could also be set in the ansible or docker-compose configs I guess.

**Comment by RocketDerp** [comment]
There is also a 5 second default timeout hard-coded that I suggest be increased and moved into an environment parameter.

`const POOL_TIMEOUT: Option<Duration> = Some(Duration::from_secs(5));`

https://github.com/LemmyNet/lemmy/blob/0f91759e4d1f7092ae23302ccb6426250a07dab2/crates/db_schema/src/utils.rs#L47C1-L47C69

> see also: https://docs.rs/deadpool-postgres/latest/deadpool_postgres/struct.PoolConfig.html

For sake of clarity, I do see lemmy server Rust code uses "deadpool", but I was unable to find it using "deadpool-postgres", which is a different library?
