### ISSUE TITLE
`/api/v3/comment/like` takes 5+ sec to respond on production instances

### ISSUE THREAD

**Issue by alectrocute** [LemmyNet/lemmy#3395]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

- `/api/v3/comment/like` takes 5+ sec to respond on production instances

<img width="1393" alt="Screenshot 2023-06-28 at 10 44 48 AM" src="https://github.com/LemmyNet/lemmy/assets/35377827/185baae3-83e5-42f2-90d1-2c3875fd7d32">

### Steps to Reproduce

1. Go to https://lemmy.ml
2. Upvote comment
3. Observe long time to respond

### Technical Details

Latest Chrome

### Version

BE 0.18

### Lemmy Instance URL

https://lemmy.ml

**Comment by phiresky** [comment]
this is potentially fixed by #3175 ? try on lemm.ee
