### ISSUE TITLE
Allow Profile posts / microblogging on Lemmy

### ISSUE THREAD

**Issue by DraconicNEO** [LemmyNet/lemmy#3402]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Not necessarily a problem, more of an improvement. On other forum-like platforms users have the ability to make posts to their profile without posting to a community. I think it would be very nice if Lemmy had that ability as well, especially considering that other Federated services also have this ability.

### Describe the solution you'd like.

I think it would be a good idea to add the ability for users to post on their profile on Lemmy. It would be handy if the user is posting about something related to themselves or something related to them that isn't related to any specific community that they just wanted to say publicly.

### Describe alternatives you've considered.

N/A

### Additional context

I'm not sure if this is exclusively a backend issue, it may require frontend changes as well to be implemented. I did file it here though because I felt like it might require backend changes to implement.

**Comment by Nutomic** [comment]
You can make a community /c/DraconicNEO for this purpose. Or use Kbin which has this feature. No reason to reimplement it in Lemmy.

**Comment by DraconicNEO** [comment]
>No reason to reimplement it in Lemmy.

I would disagree with that, this feature in Lemmy would allow users to view and comment posts on a user's profile on kbin which is not possible in the current system.
A lot of the people I've talked to who like or want this feature are people who used to be on Reddit and miss the ability to have profile posts. 


>You can make a community /c/DraconicNEO for this purpose.

That's your official solution? That doesn't sound like a great solution in my opinion to ask everyone who wants to do this (do you think that I was making this request based on what I want alone and that literally nobody else wants this? Not upset I'm just curious). It's probably a bad idea to encourage people to create communities as it has a large potential to cause conflict on the count of users creating subs with another person's username and pretending to be them or represent them. Think about that for a moment and Ask yourself if you really want to encourage that as the official solution.


>Or use Kbin which has this feature.

Well I asked this feature because there are users already on Lemmy who are interested in this. I guess technically jumping ship to kbin is an option, though last time I checked there's more Lemmy instances than there are kbin ones and their servers are already overloaded, so migrating to kbin as an official solution doesn't seem that great if they're struggling to keep up with registrations.

**Comment by M4rtineski** [comment]
Agree, this would be a very useful feature. If noone wants to work on this now we can make it a feature that could be implemented in further future after the platform has finished implementing it's core features.
