### ISSUE TITLE
User Interface Translation

### ISSUE THREAD

**Issue by Chamotrans** [LemmyNet/lemmy#3405]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

N/A

### Describe the solution you'd like.

Let's create an option in Setting to allow user choose their UI language, and put our Localization into Crowdin so we can translate.

### Describe alternatives you've considered.

N/A

**Comment by Nutomic** [comment]
There is already a language selection and translations are done via https://weblate.join-lemmy.org/
