### ISSUE TITLE
[Bug]: Quotation marks and bold in markdown breaks feed

### ISSUE THREAD

**Issue by skariko** [LemmyNet/lemmy#3411]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Hello,
if a post contains this markdown sequence: `**"some text "**` the XML feed will give an nginx 502 Bad Gateway error.

I recreated the problem in my test community.

The post is this: https://feddit.it/post/527823

And the broken feed here: https://feddit.it/feeds/c/test.xml?sort=New

At the time the post is created also appears this error: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

### Steps to Reproduce

1. Create a post and inside put this markdown: `**"some text "**`
2. Try to get the feed of that community.

### Technical Details

Can't find an error but thanks to the support chat on Matrix I was able to find this in the debug:

`lemmy_1     | 2023-06-29T14:22:51.326644Z DEBUG HTTP request{http.method=GET http.scheme="http" http.host=feddit.it http.target=/feeds/c/libri.xml otel.kind="server" request_id=0c280053-e4d3-4103-baa2-923a0d28b5b9}:get_feed:get_feed_community: tokio_postgres::query: executing statement s113 with parameters: [ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([255, 255, 255, 255])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([255, 255, 255, 255])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([255, 255, 255, 255])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([255, 255, 255, 255])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([255, 255, 255, 255])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([255, 255, 255, 255])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([255, 255, 255, 255])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([255, 255, 255, 255])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 16, array_oid: 1000 })), Some([0])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 16, array_oid: 1000 })), Some([0])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 16, array_oid: 1000 })), Some([0])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 16, array_oid: 1000 })), Some([0])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 23, array_oid: 1007 })), Some([0, 0, 0, 195])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 16, array_oid: 1000 })), Some([0])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 16, array_oid: 1000 })), Some([0])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 20, array_oid: 1016 })), Some([0, 0, 0, 0, 0, 0, 0, 20])), ToSqlHelper(PgTypeMetadata(Ok(InnerPgTypeMetadata { oid: 20, array_oid: 1016 })), Some([0, 0, 0, 0, 0, 0, 0, 0]))]`

### Version

0.18.0

### Lemmy Instance URL

feddit.it

**Comment by phiresky** [comment]
opened an upstream issue. this is causing large compounding issue where it cases nginx to mark the upstream as down depending on configurtaion but maybe we should switch to some more robust/popular markdown library? https://github.com/rlidwka/markdown-it.rs/issues/26

**Comment by phiresky** [comment]
We can't 1:1 replace markdown-it with pulldown-cmark because it does not have the ` fenced_divs` extension of which a subset is implemented for spoiler blocks here: https://github.com/LemmyNet/lemmy/blob/1e99e8b9dc48b23fca3b1801c66f30cf17766825/crates/utils/src/utils/markdown/spoiler_rule.rs#L1

They are also not planning on implementing it: https://github.com/raphlinus/pulldown-cmark/issues/589

**Comment by ninanator** [comment]
@phiresky @skariko - Thank you for reporting this. Since Lemmy was using the default settings for Comrak (which means smart quotes weren't enabled before my PR) I'll open up a PR to disable smart quotes for now.
