### ISSUE TITLE
Make a propper how to use Lemmy

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [LemmyNet/lemmy#3412]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Lemmy was recommended to me via DM by a subreddit and I must say, that as a programmer, I can't imagine normal people using this at all.

You need to dig around to learn how to use this nonesense.

### Describe the solution you'd like.

A clear and easy to follow description how to use Lemmy.
I like to open a website or project and instantly write down what a first visitor might encounter. So here I am.

The idea of Lemmy itself is amazing but failing to allow people to use it.

You don't focus on letting people JOIN and use it, it's more like the typical "It's opensource and amazing, WOW it's decentralized" and all this nonsense.

It says Join a server, this is what I want to do, so I click it.
There is a small list of communities, and no search or tags, to filter them, so I'm just forced to scroll and maybe find something I want to join, because the DM that made me aware of Lemmy didn't include the community itself... nice...

Let's be basic and get lemmy.one, I click Join and I'm in.

Now I clicked to sign up and it looks like I need to request a registration, meaning if I need to request a registration the whole idea of decentralisation is basically dead at this point. Why can a subreddit decide if im allowed to sign up on a decentralized network..Makes legit 0 sense. So now if my request is denied I'm not allowed to use lemmy? This is already a red flag compared to reddit.

### Describe alternatives you've considered.

Too many questions...

**Comment by Nutomic** [comment]
This is just complaining. If you want to help improve the user experience, you can make contributions to the docs and joinlemmy repos.
