### ISSUE TITLE
Invalid format for "sub" claim in JWT

### ISSUE THREAD

**Issue by shadone** [LemmyNet/lemmy#3417]
[RFC7519](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2) says the "sub" claim should be a string, not an integer

> The "sub" value is a case-sensitive string containing a StringOrURI value

https://github.com/LemmyNet/lemmy/blob/3159eedd9928f7ae0e01eea22ab721a795687888/crates/utils/src/claims.rs#L10-L11

Currently (some?) standard compliant JWT parsers cannot parse/validate the JWT

**Comment by Nutomic** [comment]
Fixed in https://github.com/LemmyNet/lemmy/pull/3818
