### ISSUE TITLE
[Bug]: Nodeinfo misreports user count

### ISSUE THREAD

**Issue by ThatOneCalculator** [LemmyNet/lemmy#3419]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Lemmy's Nodeinfo (used by Fediverse trackers and whatnot) reports `usage.users.total` as (what I assume to be) the number of discovered users, not the number of local users. This makes many sites like FediDB believe that every single Lemmy instance has tens or hundreds of thousands of users.

For example, let's look at https://cubing.social/nodeinfo/2.0.json :

```json
{
  "version": "2.0",
  "software": {
    "name": "lemmy",
    "version": "0.17.3"
  },
  "protocols": [
    "activitypub"
  ],
  "usage": {
    "users": {
      "total": 74234,
      "activeHalfyear": 5,
      "activeMonth": 5
    },
    "localPosts": 2,
    "localComments": 5
  },
  "openRegistrations": true
}
```

That `total` section under `usage` > `users` is supposed to be for how many users signed up for that Lemmy instance. Instead, we see reports like this on FediDB:

![image](https://github.com/LemmyNet/lemmy/assets/44733677/59b2359f-a634-4f99-afd6-e797ce687539)

### Steps to Reproduce

1. Access nodeinfo (2.0)
2. Observe

### Technical Details

N/A

### Version

0.17.3, although observed on dead 0.18x servers as well.

### Lemmy Instance URL

Seemingly all. Used https://cubing.social/ as example.

**Comment by sunaurus** [comment]
Hey 👋

The data is correct. There are currently a lot of spam-bot infested instances. Look at active user counts instead of total user counts to get a more realistic idea of how many people are on Lemmy.

You can check this post for more info: https://lemm.ee/post/177673

**Comment by ThatOneCalculator** [comment]
Ah, gotcha. I'll close this as invalid then.

**Comment by RocketDerp** [comment]
> reports usage.users.total as (what I assume to be) the number of discovered users, not the number of local users. 

My server is doing as described, reporting the size of the persons table for federated instances, not the number of local users with passwords.  So I think this bug is legit? What am I missing?

**Comment by sunaurus** [comment]
@RocketDerp I don't believe this is typical, I have not seen it on any other server. Can you link your nodeinfo/2.0.json, as well as share the output of the following queries:

`SELECT COUNT(*) FROM site_aggregates WHERE site_id = 1;`
`SELECT COUNT(*) FROM local_user;`

**Comment by RocketDerp** [comment]
In the week that has passed, I've updated my server, and now it is correctly reporting the local number (9).  {"version":"2.0","software":{"name":"lemmy","version":"0.18.1-rc.9-10-g45b1a0d4f"},"protocols":["activitypub"],"usage":{"users":{"total":9,"activeHalfyear":3,"activeMonth":3},"localPosts":15,"localComments":36},"openRegistrations":false}
