### ISSUE TITLE
Allow communities to apply CSS to their communities.

### ISSUE THREAD

**Issue by Rupurudu** [LemmyNet/lemmy#3429]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I always loved the subreddit css feature on the old reddit. The custom themes gives the subreddits personality and makes different communitites stand out of each other. 

For the community customization, Lemmy only has community logo and sidebar. I would love if lemmy allows such customization for their communities.

I believe making the communities stand out instead of the federations or lemmy itself makes the entire experience more fun.

### Describe the solution you'd like.

Have a edit stylesheet field on the community settings, much like the sidebar field. Also have a image upload field to use in the css.

Filter and audit the css code, so it does not override essential parts of the web UI. Both the local instance (at the time of editing) and remote instances (at the browser) should do the auto filtering.

Apply the css to the community pages.

### Describe alternatives you've considered.

I think having additional community customizations such as banners, and colors also works, but not to the extent of CSS. 

### Additional context

Not all client implementations use CSS theming engine, so these customizations might not show up on all of the clients, but I believe this is an acceptable compromize.

**Comment by rivvvers** [comment]
yes I would love to see this implemented

**Comment by dessalines** [comment]
The amount of potentially dangerous manipulation possible via CSS. If there is any community theming, it would be added as specific settings and fields, not as injected CSS. 

Its also been a concious decision to leave theming to individual users, and not to community mods.
