### ISSUE TITLE
Alert Window: Not logged in

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#343]
No idea what causes this, it seems to happen randomly after having the site open for a few hours or days without interacting.

![Screenshot_20191118_183437](https://user-images.githubusercontent.com/1044450/69075736-df07f900-0a29-11ea-87ff-04d6933bb0aa.png)

After clicking okay, Lemmy still shows you as logged in. But voting or commenting will throw errors, and a reload will reveal that you are actually logged out.

**Comment by dessalines** [comment]
Hrm.... a manual logout should only happen when we change the JWT token on the server and reload it... I don't have any expiration set on the JWT token currently. 

I'll have to think about this one.

**Comment by dessalines** [comment]
Is this still an issue?

**Comment by Nutomic** [comment]
I still saw it during the last week or so, still no clue why. Weird that no one else seems to have this problem.

**Comment by dessalines** [comment]
This should be gone now, with the websocket-autoreconnecting, and the toasts.

**Comment by Nutomic** [comment]
FYI I'm still getting the same issue, just without the alert. So now it looks like I'm logged in, but I cant do any actions like voting, so I have to reload the page which shows that I'm not logged in anymore.

**Comment by dessalines** [comment]
Hrm.... The only thing I can think of is that a browser update, or something is causing your cookies to clear out.

**Comment by Nutomic** [comment]
Not sure, I might have restarted the browser in between and that cleared the cookies? Let me try.

**Comment by Nutomic** [comment]
Just got this problem again. Dev tools show that the jwt cookie is not sent at all with new requests. But the website is still showing me as logged in (until I try to post or vote).

**Comment by dessalines** [comment]
Still an issue? No idea what caused it.

**Comment by Nutomic** [comment]
I'm still getting this every few weeks or so, but it might be related to a browser plugin or something considering no one else complains about it.
