### ISSUE TITLE
[Bug]: Matrix user ID validation considers server names with explicit ports invalid

### ISSUE THREAD

**Issue by Whodiduexpect** [LemmyNet/lemmy#3431]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

If you set your account's Matrix user to a server that uses a port inside its server name (like `@user:server.tld:443`) both the validation on Lemmy UI and the Lemmy backend incorrectly state that the MXID is invalid.

#### Through Lemmy UI
1. Click on logged-in user in the top-right
2. Click on settings
3. Enter an MXID into the "Matrix User" field which uses an explicit port in the server name
4. Click save button at the bottom
5. Browser prompts user to "Please match the requested format" despite it being a valid MXID.

#### Through API
Sending a PUT request to `/api/v3/user/save_user_settings` with the `matrix_user_id` key set to a server with an explicit port makes the server return an HTTP 400 response with `{"error":"invalid_matrix_id"}`.

### Technical Details

Browser: Firefox

### Version

BE 0.18.1-rc.4

### Lemmy Instance URL

vlemmy.net

**Comment by mhijazi1** [comment]
Was able to identify the [API issue](https://github.com/LemmyNet/lemmy/blob/cb28af508d030683561bdc9dde2299cf818f2c6b/crates/utils/src/utils/validation.rs#L12)

UI bug seems to be coming from [here](https://github.com/LemmyNet/lemmy-ui/blob/61255bf01a8d2acdbb77229838002bf8067ada70/src/shared/components/person/settings.tsx#L551)

I also opened an issue lemmynet/lemmy-ui#1726

**Comment by emi-rose** [comment]
### Am I doing something wrong? Is it related to this issue? Is it a different issue?
**I am trying to add either one of my Matrix usernames and all of them don't appear after saving settings and don't appear on my profile when viewing from alt.**

Either One Of These Matrix Usernames:
@emi_rose:matrix.org
@emi:envs.net

|**My Settings:**|
|----------------|
|![Screenshot 2023-07-03 125741 - Copy](https://github.com/LemmyNet/lemmy/assets/137147842/96db2819-1850-4bf1-85ea-d171c614c843)|


|**Result From Alt Perspective:**|
|----------------|
|![Screenshot 2023-07-03 125510 - Copy](https://github.com/LemmyNet/lemmy/assets/137147842/1a299c0e-e51a-42b8-8434-035e189788d2)|

|**Expected Result As Seen On Another Individual's Profile:**|
|----------------|
|![Screenshot 2023-07-03 130305 - Copy](https://github.com/LemmyNet/lemmy/assets/137147842/dd3d92a4-393a-4730-8c38-b5e8b496136e)|
