### ISSUE TITLE
[Bug]: Cannot login to newly created self hosted instance with cloudflare tunnel 

### ISSUE THREAD

**Issue by fivves** [LemmyNet/lemmy#3439]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Got my lemmy instance up and running, but cannot log in to the admin account. When I try to log in I receive the following error: 

SyntaxError: Unexpected token 'O', "Origin is "... is not valid JSON

What is this and how do I fix it? thank you 

### Steps to Reproduce

1. Open new lemmy instance
2. Attempt to login 
3. Receive error 

### Technical Details

Running a self hosted lemmy instance with a cloudflare tunnel. there's no ssl security on the server side but cloudflare automatically adds https support. Not sure if this is causing it or how to fix it. 

### Version

0.18.0

### Lemmy Instance URL

https://lemmy.lucitt.social/

**Comment by RocketDerp** [comment]
The project is really busy dealing with data distribution problems and version upgrades/release candidate. They generally have asked that you don't use this issue for instance install problems. Your specific issue seems unique to CloudFare and not really a lemmy bug.

**Comment by finnim** [comment]
Hello, in case it helps, I deployed a v.0.18 instance behind cloudflare yesterday and thinks worked correctly.
I used ansible to deploy it.

**Comment by lionirdeadman** [comment]
Looking at the instance, seems you figured it out - closing.
