### ISSUE TITLE
Can we raise character limit for titles by 25%?

### ISSUE THREAD

**Issue by M4rtineski** [LemmyNet/lemmy#3444]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I have a sublemmy for news on ai and technology. When posting I include the full title, date of the source and sometimes edit the title to tell that something is misinformation. Sometimes I encounter an issue where there's not enough space for what I want to include in the title and it makes it harder to operate.

### Describe the solution you'd like.

I want to character limit for titles to be raised by 25% or 30% to avoid hitting the character limit too often.

### Describe alternatives you've considered.

At the beginning I wanted to make an issue for raising the character limit by 50% but I fugured that it would be a bit too much so I decided to lower the new limit that I'm requesting for.

### Additional context

no context

**Comment by Nutomic** [comment]
Titles are already long enough, otherwise there will be rendering issues for UIs.
