### ISSUE TITLE
[Bug]: Can't login

### ISSUE THREAD

**Issue by stemy2** [LemmyNet/lemmy#3445]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When i'm trying to login, i get the message `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

### Steps to Reproduce

1. Try to login

### Technical Details

error HTTP 400: bad request

### Version

0.18

### Lemmy Instance URL

https://www.lemmynsfw.com

**Comment by rcmaehl** [comment]
Might be related to #3422 

@xaegreal

**Comment by stemy2** [comment]
Seems fixed by the last upgrade.
