### ISSUE TITLE
RSS feeds: add community name to each RSS item tags/<category>

### ISSUE THREAD

**Issue by nodiscc** [LemmyNet/lemmy#3446]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When displaying Lemmy RSS feeds in a feed reader (e.g. https://lemmy.world/feeds/c/selfhosted.xml?sort=Active or https://lemmy.world/feeds/front/RANDOMKEY.xml?sort=Active), the only indicator the community an item was posted to, is the text `submitted by USERNAME to COMMUNITY` inside the article `<content>`).

This makes it impossible to navigate/filter feeds using RSS's "tags" feature ([`<category>`](https://www.rssboard.org/rss-specification#ltcategorygtSubelementOfLtitemgt) element).

The `<category>` element is used in most feed readers as a "tag" which, when clicked, takes you to other articles with the same tag across all feeds. For example, in https://old.reddit.com/r/skyrim/.rss, each RSS `<item>` contains a subelement in the form `<category term="skyrim" label="r/skyrim"/>`, which is rendered in my feed reader (Tiny Tiny RSS) as:

![image](https://github.com/LemmyNet/lemmy/assets/3950390/b6a06c8d-9c95-47eb-b4e3-94efbd8786ed)

Clicking this tag brings up the list of all articles with the same tag **across all feeds in the feed reader**.

More importantly it allows the creation of filters with this tag as a selector (e.g. if the tag is `selfhosted`, then assign a special, highly-visible label in my feed reader - or if the tag is `news` and the content contains `badqualitywebsite.com`, then mark as read or delete the article).

### Describe the solution you'd like.

I'd like RSS feeds generated by Lemmy to contain this element, which would allow tag-based functionality to work in my feed reader.

### Describe alternatives you've considered.

There are manual, imperfect workarounds:
- Full text searching (works but requires manual text input, false positives)
- Filtering on titles content (false positives, resource-intensive)

### Additional context

I'm not sure of how this XML element should be used exactly, as the [RSS 2.0 specification](https://www.rssboard.org/rss-specification#ltcategorygtSubelementOfLtitemgt) says it should be in the form `<category>skyrim</category>`, but the Reddit RSS feed I gave as an example uses `<category term="skyrim" label="r/skyrim"/>`. Maybe I'm not looking at the correct specification?

This feed http://radiofrance-podcast.net/podcast09/rss_13940.xml seems to follow the specification, using for example `<category>Society &amp; Culture</category>`, and I can confirm that my feed reader interprets it the same way:

![image](https://github.com/LemmyNet/lemmy/assets/3950390/b4bc5204-cd60-4958-9490-4c0a1873ef00)

**Comment by knrodriguez** [comment]
Adding categories/subcatefories to a community would also be so helpful for grouping/filtering/searching in lemmy and other lemmy community browsers.

**Comment by nodiscc** [comment]
@knrodriguez please don't hijack issues. The feature you mentioned has already been requested here https://github.com/LemmyNet/lemmy/issues/317

**Comment by knrodriguez** [comment]
@nodiscc My apologies, I thought they could be related in scope but I see now they are different. I will remove my comment.
