### ISSUE TITLE
Up the limit for community names to 21

### ISSUE THREAD

**Issue by sab666** [LemmyNet/lemmy#3449]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

On reddit the character limit for subreddits is 21 characters. In order to best facilitate communities that want to cross over, it would be helpful if they can keep the same name for discoverability. Some examples:
* `ukrainewarvideoreport`
* `PersonalFinanceCanada`
* `BestofRedditorUpdates` (yeah okay, that last one doesn't make sense, but it has been requested on https://lemmit.online/)

### Describe the solution you'd like.

Bump the validation regex to 21 characters. The database field is already varchar(255), so no migration is needed.

### Describe alternatives you've considered.

N/A

**Comment by KAMiKAZOW** [comment]
It shouldn't be thousands of characters bit 21 is a little bit low. Maybe 50?

**Comment by csm10495** [comment]
i think 50 makes more sense than 21

**Comment by sab666** [comment]
DOH. This can actually be adjusted in the admin with the `Max actor name length` setting.
