### ISSUE TITLE
Limit the amount of communities a user can create

### ISSUE THREAD

**Issue by Savjee** [LemmyNet/lemmy#3452]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

On lemmy.world, there's a user creating a ton of communities with random names.

<img width="1328" alt="image" src="https://github.com/LemmyNet/lemmy/assets/817109/0d260171-0a02-459a-8b37-00e34acf5bfe">

At the time of opening this issue, the account created 4162 communities

```js
document.querySelectorAll(".list-unstyled.mb-0 li").length
```

### Describe the solution you'd like.

I see two possible solutions:

1. **Put a sensible limit on how many communities a single user can create/moderate.**
I.e: 100 communities per user max.
However, this might also require a way for admins to override the limit in case someone legitimately wants to go over that limit.

2. **Add a rate limit.** 
Only allow users to create a new community when their previously created community is at least X hours old.

Solution 2 will also prevent people from claiming many community names at once.

### Describe alternatives you've considered.

Banning the particular user is also an option, but does not prevent the issue in the future.

### Additional context

The user in question: https://lemmy.world/u/LMAO (might have been banned already)

**Comment by KAMiKAZOW** [comment]
Was about to suggest the same. For a rate limit I have the suggestion for a "Fibonacci" rate limit. So one minute between creating the first and the second community and so on in Fibonacci sequence: `1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144,...`

After a few days the rate limit could reset to zero.

**Comment by nicojlehne** [comment]
I'd concatenate both proposed solutions and reduce the maximum amount of communities to at most 5 created and or modded per user unless an admin approves more on an individual basis depending on how the user handle(d|s) previous communities.

We don't need a single user creating 100 communities and modding none or claiming every sub name and doing nothing with it.

**Comment by pixiekat** [comment]
I don't agree with a hard coded limit, though I do think a series of rulesets should be configurable for the instance admins to determine this globally as well as override for specific users.

The only hard-coded rule I'd be in favour of is flood control to prevent repeated creations at once.

**Comment by tylerjgarland** [comment]
A community approval queue could also be used. They then could apply their own filtering such even in an automated fashion.

**Comment by salif** [comment]
Some reddit alternatives had a limit on the number of communities one could moderate. For example, one user could not moderate more than 10 communities on ruqqus.com

**Comment by lcwxz1989** [comment]
I think this is important for admin to control the website healthy. So this issue will add some feature or not?

**Comment by dessalines** [comment]
We already have a rate limit `register` that can be used to limit the rate of community creation. So Option 2 from above.
