### ISSUE TITLE
[Bug]: Sorting posts by Top X hides them from view in some communities

### ISSUE THREAD

**Issue by lightrush** [LemmyNet/lemmy#3454]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I noticed today that in some communities like [!framework@lemmy.ml](https://lemmy.ml/c/framework), or [!telecomcanada](https://lemmy.ca/c/telecomcanada), sorting posts by Top X where X could be hour, six hours, etc. hides all posts in the community. The view shows "No Posts." This seems to happen across instances. E.g. [!telecomcanada](https://lemmy.ca/c/telecomcanada) displays this behaviour when accessed via lemmy.ca where it's hosted as well as via lemmy.world, using a different account.

![image](https://github.com/LemmyNet/lemmy/assets/2876507/26ee91d8-7bf5-4601-9835-8cbdff274525)

![Screenshot from 2023-07-02 12-48-47](https://github.com/LemmyNet/lemmy/assets/2876507/e8b88b73-fe26-42fb-9163-a71fd3996b3c)

It looks to be a backend issue since it's reproducible in Jerboa.

### Steps to Reproduce

1. Open [!telecomcanada](https://lemmy.ca/c/telecomcanada) 
2. Sort by Top Day

Expected: Posts show up
Actually: "No Posts." is displayed

### Technical Details

N/A

### Version

0.18.0, 0.18.1rc

### Lemmy Instance URL

lemmy.ca, lemmy.world

**Comment by lightrush** [comment]
This could be me misinterpreting how Top X should work. To me it looks like a sorting function. This is how I'm reading the [doc](https://join-lemmy.org/docs/users/03-votes-and-ranking.html) too. Is it intended to work as a filter instead?

**Comment by L3v3L** [comment]
won't show anything in top hour if nothing has been posted in the last hour

**Comment by WayneSheppard** [comment]
Working as intended.  I see two posts, 10d and 11d old.  "Top Day" should sort all the posts from the last day.

**Comment by lightrush** [comment]
So Top X are both sorting and filtering. Got it. I feel there may be a a nicer way to portray this in the UI but I don't have any good proposal at the moment so I'm good.
