### ISSUE TITLE
Instance Description

### ISSUE THREAD

**Issue by weddi-eddy** [LemmyNet/lemmy#3459]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

As a new lemmy user, it is difficult to quickly know which instance I want to be a part of. Some instance owners may not intend for their instance for mass use.

It is difficult for both user and instance owner to know these things.

### Describe the solution you'd like.

I think if instances had a description entry saying what the instance is intended for, then it could help users decide on which instance to join and help instance owners specify what the instance is for and any other message.

### Describe alternatives you've considered.

This currently doesn't exist.

### Additional context

Maybe a description. Maybe a field or tag. Just something that shows what instances could be intended to do or support.

**Comment by MV-GH** [comment]
Like this ?
![image](https://github.com/LemmyNet/lemmy/assets/67873169/dbc3d8a7-53f0-421b-a3e2-257aa2cec75e)

![image](https://github.com/LemmyNet/lemmy/assets/67873169/799d8b04-ab66-430b-b487-d05e07524597)

**Comment by MV-GH** [comment]
I think these are the taglines

**Comment by lionirdeadman** [comment]
Taglines show on top of the post feed, what's shown on join-lemmy is the description (https://join-lemmy.org/api/interfaces/SiteMetadata.html)

From the conversation, this seems solved.
