### ISSUE TITLE
[Bug]: Moderators are not correctly federated between 0.18.0 and 0.18.1-rc4 instances

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy#3460]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Moderators are not correctly displayed between 0.18.0 instances and those running on 0.18.1-rc4

Example:
https://slrpnk.net/c/solarpunk -> has three mods and is running 0.18.0
https://sopuli.xyz/c/solarpunk@slrpnk.net -> shows all three mods and is running 0.18.0

https://lemmy.world/c/solarpunk@slrpnk.net -> shows only one mod and is running 0.18.1-rc4
https://discuss.as200950.com/c/solarpunk@slrpnk.net -> shows no mod at all and is running 0.18.1-rc4

This also applies to the userpages as seen here:
https://discuss.as200950.com/u/SteveKLord@slrpnk.net -> does not list this user as a mod of !solarpunk@slrpnk.net

### Steps to Reproduce

1. Have a community with mods on 0.18.0
2. Look at community via an instance on 0.18.1-rc4
3. See difference

### Technical Details

n/a

### Version

BE 0.18.0 and BE 0.18.1-rc4

**Comment by RocketDerp** [comment]
> https://lemmy.world/c/solarpunk@slrpnk.net -> shows only one mod and is running 0.18.1-rc4
> https://discuss.as200950.com/c/solarpunk@slrpnk.net -> shows no mod at all and is running 0.18.1-rc4

This is a big clue. They are both running the same version and show different moderators. 

I think it has nothing to do with version, and everything to do with replication of data failures. Lemmy federation is imperfect. See if the user profiles exist on every server for every one of those mods. Sync between servers is a real mess all over the Lemmy network.

**Comment by poVoq** [comment]
This would maybe explain it for Lemmy world, but the other example is a small server that should have no load issues.

**Comment by RocketDerp** [comment]
Lemmy replication is not robust. All it takes is for lemmy_server app to be restarted and outbound changes don't get delivered.  I found a 0.18.0 server that also shows none of the 3 moderators  for that community: https://sh.itjust.works/c/solarpunk@slrpnk.net - the network is unstable.

**Comment by RocketDerp** [comment]
The profile for a missing commuity id is there on the server: https://sh.itjust.works/u/poVoq@slrpnk.net - so it must have something to do with community_moderator database table, but I'm not sure, I'm still learning how these faults happen.

**Comment by ancientmarinerdev** [comment]
The same issue may have occurred here:

https://lemm.ee/comment/950820

You can see mods here:

https://lemmy.ml/c/degoogle

but none here:

https://lemm.ee/c/degoogle@lemmy.ml

**Comment by RocketDerp** [comment]
yha, the mod list is empty on https://lemmy.world/c/degoogle@lemmy.ml too
