### ISSUE TITLE
[removed and posted to lemmy-ui instead]

### ISSUE THREAD

**Issue by 001Guy001** [LemmyNet/lemmy#3463]
[removed by user]

**Comment by L3v3L** [comment]
I think this is issue should be in [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

**Comment by 001Guy001** [comment]
> I think this issue should be in [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)

Good point, will post it there instead 👍
