### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3465]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently when you scroll, you will end up at a bottom with "Next" and "Previous" page navigation buttons. You must click these buttons to see more content.

### Describe the solution you'd like.

Most sites have infinite scroll where new content is automatically loaded off screen so that you are able to indefintiely scroll without interruption. This is what I am proposing for Lemmy.

### Describe alternatives you've considered.

N/A

**Comment by rokejulianlockhart** [comment]
@K4LCIFER, conseqently close the issue.

**Comment by K4LCIFER** [comment]
> this is a lemmy-ui issue, and there is already one open there: [LemmyNet/lemmy-ui#878](https://github.com/LemmyNet/lemmy-ui/issues/878)

Noted! Thanks for letting me know. Sorry for posting in the wrong repo!
