### ISSUE TITLE
[Bug]: Image rejected, wrong dimensions error

### ISSUE THREAD

**Issue by maxjwebber** [LemmyNet/lemmy#3473]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Unclear if this is a backend issue. It could be.

I tried posting an image on the mobile site in Firefox Nightly 116.0a1 for Android and received this error which appeared in a red popup at the bottom of the screen. I was posting to my home instance Beehaw.org.

{"data":{"msg":"Invalid media dimensions","files":null},"state":"success"}

When posting in desktop mode the image still failed to post but no error was displayed.

I also attempted to post a cropped version of the image and a compressed version.

### Steps to Reproduce

1. Log in successfully
2. Click Create Post
3. Click Image -> Browse
4. Compress image, repeat steps 2-3
5. Crop original image, repeat steps 2-3

### Technical Details

I am a user on Beehaw.org accessing the site through Firefox Nightly for Android 116.0a1.

Original image dimensions are 3488x4656, type is jpg, file size is 5.7 mb

Compressed image dimensions are 3488x4656, type is jpg, file size is 3.7 mb

Cropped image dimensions are 3488x4319, type is jpg, file size is 2.6 mb

### Version

UI: 0.18.1-rc.7 BE: 0.18.1-rc.4

### Lemmy Instance URL

Beehaw.org

**Comment by Security-Chief-Odo** [comment]
This is a beehaw specific error, and not related to Lemmy. 

Images are capped at 4000x4000 resolution for beehaw.org. However, the error should be more specific.

**Comment by lionirdeadman** [comment]
Please rename the issue to "Upload restrictions should be forwarded to UI"
