### ISSUE TITLE
Flexible Scoring System User Setting

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3477]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

This feature would allow users to select their preferred scoring method from a range of options, ensuring that the platform accommodates diverse preferences and aligns more closely with individual needs.

Here are some key elements that could be included in this flexible scoring system:

1. Affinity to Admin: Enable users to opt for a scoring system that increases the weight of votes based on their affinity to the admin. By doing so, the platform would prioritize the preferences of the admin, creating a more tailored and focused community for that particular instance.

2. Score Posts based on Community Size: Provide an option for scoring posts based on the size of the community at the time of voting. This approach would consider the collective opinion of a larger community, resulting in a more democratic and representative scoring system.

3. Balancing Scores based on Instance Size: Implement a scoring mechanism that prevents the dominance of big instances, promoting a more diverse representation of instances in the feed. This approach would ensure that posts from smaller instances have a fair chance of being seen and appreciated by users across the platform.

4. Personalized Filter based on User Affinity: Introduce a personalized filter, similar to Reddit's "Best" feature, which takes into account the user's affinity with posts based on their voting history. By analyzing the user's preferences through upvotes and downvotes, Lemmy can provide a customized feed that aligns with their interests, enhancing the user experience.

5. User-Weighted Communities: Allow users to assign a weight to each community they are subscribed to, determining the proportion of posts from each community that appears in their feed. Users could assign weights ranging from 0-100 points or represented as 0 to 5 stars. For users who do not assign a weight, the system can automatically assign a weight based on their interactions with posts in each community. This feature would ensure that communities closely aligned with a user's interests have a greater presence in their feed.

6. User Engagement: Take into account user engagement metrics, such as comments, shares, and interactions, when calculating the score of a post. This approach would provide a more comprehensive measure of a post's relevance and impact within the community, beyond simply the number of votes.

7. Quality Assessment: Introduce a mechanism to evaluate the quality of posts, either through manual moderation or automated algorithms. By promoting high-quality content, the scoring system can prioritize posts that contribute meaningfully to the community, fostering valuable discussions and interactions.

Finding the perfect balance for scoring on Lemmy is a complex task, and no single approach may suit every instance or community. However, by providing users with the ability to choose their preferred scoring system, Lemmy can become a more inclusive and adaptable platform that reflects the values and needs of its diverse user base.

Related:

- [Voting Affinity and Engagement Analysis. #3241](https://github.com/LemmyNet/lemmy/issues/3241)
- [The rank of a post in the aggregated feed should be inversely proportional to the size of the community. #1026](https://github.com/LemmyNet/lemmy/issues/1026)
- [Score posts based on community size at the time of voting. #2794](https://github.com/LemmyNet/lemmy/issues/2794)
- [Keep a score of the upvotes and downvotes given to user. #2370](https://github.com/LemmyNet/lemmy/issues/2370)
- [Bluesky custom algorithms](https://blueskyweb.xyz/blog/3-30-2023-algorithmic-choice). You can build your own or use someone else’s, delete, pin, reorder them. It’s like different feeds.

**Comment by M4rtineski** [comment]
Hey, I know you from lemmy lol

**Comment by 8ullyMaguire** [comment]
I'm closing this in favor of [Algorithm Marketplace](https://github.com/LemmyNet/lemmy/issues/3936)
