### ISSUE TITLE
Add privacy policy to site settings

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#3488]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, there is no way to set a privacy policy for lemmy instances (unless Legal in the admin settings is supposed to fill this role - unsure). This would make instances more transparent to their users.

### Describe the solution you'd like.

Make privacy policy settable in admin settings.

### Describe alternatives you've considered.

1. Hardcode privacy policy
2. Use legal(?)

**Comment by RocketDerp** [comment]
see also https://github.com/LemmyNet/lemmy-ui/issues/1419 - the "Sign Up" in lemmy-ui could really benefit from having a "terms of service" markdown message. And if your site registration is "closed', the "Sign Up" page says nothing to warn that to a user (it asks for username/etc). As for the growing number of alternate front-ends, I think your mention of "legal" field having it in the backend makes some sense.

**Comment by dessalines** [comment]
Yep `legal` is supposed to fill that role, and its entirely customizeable.
