### ISSUE TITLE
Add support for HTTP(S) proxies

### ISSUE THREAD

**Issue by cthu1hoo** [LemmyNet/lemmy#3489]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Outbound HTTP requests backend makes would fail if Lemmy instance has no direct outbound internet connection.

### Describe the solution you'd like.

Please consider adding HTTP(S) proxy support for outgoing requests, HTTP_PROXY environment variable is an industry standard, of sorts. Config option would also work, of course.

Thanks in advance.

### Describe alternatives you've considered.

I've thought about things like routing Lemmy backend container traffic via wireguard client container but I'd rather not. :)

**Comment by Dhawos** [comment]
I think this is actually already supported from what I can read in the documentation from the library that is used to make those request : https://docs.rs/reqwest/latest/reqwest/index.html#proxies

I've tried to set the variables locally to an invalid address and the requests failed, when they succeeded if I did not set these variables

**Comment by cthu1hoo** [comment]
I've tried setting HTTP_PROXY for the lemmy (backend) container and it broke the whole thing for me, i.e. white page with "Server error" and that's it.

Proxy logs show that inter-container traffic within lemmy compose setup also goes through the proxy, which obviously is not aware of `http://pictrs/...` and any other non-fqdn names which only resolve inside the container. So those need to be excluded somehow.
