### ISSUE TITLE
Preventing Banning Abuse - A new approach to moderation for Lemmy / fediverse.

### ISSUE THREAD

**Issue by Rich-McGrath** [LemmyNet/lemmy#3492]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

A Fediverse / Lemmy ban is easy to abuse. I could host a Lemmy instance and ban whomever I want for whatever reason, and their account could be banned from the Fediverse / other Lemmys. 

### Describe the solution you'd like.

Allow individual Lemmys to choose who they sync their ban list from. I.E., two different video games, Lemmy's, decided to synch each other's ban list. Giving each Lemmy a choice to ban people and align their moderation strategy with other Lemmys that share the same approach to banning while providing autonomy to run their own Lemmy as they see fit.

### Describe alternatives you've considered.

Alternatives consider:

1.  The current fediverse implementation. 
2.  Each site maintains a ban list and it is not shared

**Comment by RocketDerp** [comment]
As it stands in 0.18.0, an Instance admin can site-ban a user that isn't homed on their own instance?

**Comment by Rich-McGrath** [comment]
> As it stands in 0.18.0, an Instance admin can site-ban a user that isn't homed on their own instance? I've opened discussions on questions about how Lemmy federation actually works: https://lemmy.ml/comment/1062436

Thank you that is good to know. Still concerned about Fed bans as there are still concerns over the current implementation.

**Comment by RocketDerp** [comment]
I'm asking, what is the tested behavior?

**Comment by sunaurus** [comment]
Hey!

> I could host a Lemmy instance and ban whomever I want for whatever reason, and their account could be banned from the Fediverse / other Lemmys.

This is not the case. If you ban a user from another instance, they would only be banned from interacting with your instance, not the rest of the network.

If you ban a local user, this user will no longer be able to log in. 

> Allow individual Lemmys to choose who they sync their ban list from. I.E., two different video games, Lemmy's, decided to synch each other's ban list.

Interesting idea, but can be problematic, because it opens up bans to the exact abuse you described originally (all banlist-subscribed instances are suddenly vulnerable to ban abuse from instances they are subscribed to)
