### ISSUE TITLE
[Bug]: Searching for remote communities returns zero results

### ISSUE THREAD

**Issue by ilmagico** [LemmyNet/lemmy#3498]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When searching for remote communities, whether in the web UI on in any (android) app I tried (liftoff, jerboa, thunder), searching for a remote community by the exact name seems to return no results, no matter whether the community is already known by the instance.

This is very important for new users, which are then forced to create accounts on every instance they want to join communities in, contributing to server overloads ("hug of death").

Example:
https://lemmy.ml/search?q=ukraine%40sopuli.xyz&type=Communities&listingType=All&page=1&sort=TopAll

This returns zero results. Notice that changing the search from "ukraine@sopuli.xyz" to a more generic "ukraine" *does* return "ukraine@sopuli.xyz" as a search result, so the community is already known by the instance.
 

### Steps to Reproduce

1. Load https://lemmy.world/api/v3/search?q=ukraine%40sopuli.xyz&type_=Communities&sort=TopAll&listing_type=All&page=1&limit=40 or equivalent for a different instance and different remote community (or any fully-qualified community name community@server.tld, including a local one)
2. There is no step 2 ;)

Expected: returns the named community
Actual: no results

Notice that this URL loads fine instead: https://lemmy.ml/api/v3/community?name=ukraine@sopuli.xyz

### Technical Details

I don't run any instance myself

### Version

0.18.*

### Lemmy Instance URL

lemmy.ml, lemmy.world, many more

**Comment by Dhawos** [comment]
From what I've seen, the search endpoint only looks in the name or title column for communities.
Communities don't have the `@instance_id` in the name column, so when the filter is made it won't find any result.

It actually works the same for users : https://lemmy.ml/search?q=dhawos%40jlai.lu&type=Users&listingType=All&page=1&sort=TopAll does not return result but https://lemmy.ml/search?q=dhawos&type=Users&listingType=All&page=1&sort=TopAll does

I'm not sure how it could be fixed, maybe there needs to be special logic for when there is a '@' in the search query. Like maybe adding an instance_id field in the Query types, and using that to filter in the views ?

**Comment by ilmagico** [comment]
Just to be clear, I don't think this is an expected result. Based on Lemmy's docs, you should be able to enter any community, even ones that aren't yet known by the instance you're on, and by either entering the URL or the full name (`!community@server.tld`) you should be able to find and subscribe to that previously unknown community.

See [Following communities](https://join-lemmy.org/docs/users/01-getting-started.html#following-communities):
> When you found a community that you want to follow, enter its URL (e.g. https://feddit.de/c/main) or the identifier (e.g. !main@feddit.de) into the search field of your own Lemmy instance. Lemmy will then fetch the community from its original instance, and allow you to interact with it. The same method also works to fetch users, posts or comments from other instances.

By the way, I didn't see it in the docs, but I'd expect this to work the same for users, i.e. being able to enter `user@server.tld` and find that user.

As for the specific on how to implement this: yes, there probably needs to be some specific logic for when the community contains a "@" or matches a specific regex.

**Comment by Dhawos** [comment]
I've put together a small PR that should handle the case of searching for a remote community when it's already in the local DB.

**Comment by Nutomic** [comment]
The problem is that only the form `!community@instance.com` is supported (note leading !). Similarly user search requires leading @. So the following works and will also fetch the community from sopuli if it isnt known locally.

https://lemmy.ml/search?q=!ukraine%40sopuli.xyz&type=Communities&listingType=All&page=1&sort=TopAll

**Comment by ilmagico** [comment]
@Nutomic Thanks for the response, if I click on that link, I get "No results". Do I need to be logged in for it to work?

I tried in a different instance where I am logged in and yes, sure enough that returns results... I thought I tried that before :thinking: 
Still, there are still a couple of issues:
* Even when logged in, the web UI still briefly shows "No results", just to quickly update showing the requested community. How quickly depends on the instance and how overloaded it is
* The API still returns no results, even when adding `!` to the search, and even when logged in, even when the community is already known to the instance: https://lemmy.ml/api/v3/search?q=!ukraine%40sopuli.xyz&type_=Communities&sort=TopAll&listing_type=All&page=1&limit=40
* Maybe we could make this more user-friendly if it also found the community without the leading `!`

**Comment by Nutomic** [comment]
>  Even when logged in, the web UI still briefly shows "No results", just to quickly update showing the requested community. How quickly depends on the instance and how overloaded it is

lemmy-ui issue

> The API still returns no results, even when adding ! to the search, and even when logged in, even when the community is already known to the instance: https://lemmy.ml/api/v3/search?q=!ukraine%40sopuli.xyz&type_=Communities&sort=TopAll&listing_type=All&page=1&limit=40

use resolve_object

>  Maybe we could make this more user-friendly if it also found the community without the leading !

it needs a way to differentiate between users and communities.
