### ISSUE TITLE
[Bug]: endless "duplicate key" errors for federated activities

### ISSUE THREAD

**Issue by LemiSt24** [LemmyNet/lemmy#3510]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When starting up Lemmy, as soon as federated activities start coming in, I get countless errors of the same type:

`2023-07-06T11:39:31.941832Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: duplicate key value violates unique constraint "idx_activity_ap_id"
lemmy_1     | 
lemmy_1     | Stack backtrace:
lemmy_1     |    0: lemmy_apub::insert_activity::{{closure}}::{{closure}}
lemmy_1     |    1: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
lemmy_1     |    2: lemmy_apub::activities::community::announce::<impl activitypub_federation::traits::ActivityHandler for lemmy_apub::protocol::activities::community::announce::AnnounceActivity>::receive::{{closure}}
lemmy_1     |    3: <activitypub_federation::protocol::context::WithContext<T> as activitypub_federation::traits::ActivityHandler>::receive::{{closure}}
lemmy_1     |    4: <alloc::boxed::Box<T> as activitypub_federation::traits::ActivityHandler>::receive::{{closure}}
lemmy_1     |    5: actix_web::handler::handler_service::{{closure}}::{{closure}}
lemmy_1     |    6: <actix_web::resource::Resource<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}
lemmy_1     |    7: <actix_web::scope::Scope<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}
lemmy_1     |    8: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
lemmy_1     |    9: <actix_web::middleware::compress::CompressResponse<S,B> as core::future::future::Future>::poll
lemmy_1     |   10: <actix_cors::middleware::CorsMiddleware<S> as actix_service::Service<actix_web::service::ServiceRequest>>::call::{{closure}}
lemmy_1     |   11: <tracing_actix_web::middleware::TracingResponse<F,RootSpanType> as core::future::future::Future>::poll
lemmy_1     |   12: <actix_service::map_err::MapErrFuture<A,Req,F,E> as core::future::future::Future>::poll
lemmy_1     |   13: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
lemmy_1     |   14: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
lemmy_1     |   15: <actix_service::and_then::AndThenServiceResponse<A,B,Req> as core::future::future::Future>::poll
lemmy_1     |   16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
lemmy_1     |   17: tokio::runtime::task::core::Core<T,S>::poll
lemmy_1     |   18: tokio::runtime::task::harness::Harness<T,S>::poll
lemmy_1     |   19: tokio::task::local::LocalSet::tick
lemmy_1     |   20: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
lemmy_1     |   21: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   22: tokio::runtime::scheduler::current_thread::Context::enter
lemmy_1     |   23: tokio::macros::scoped_tls::ScopedKey<T>::set
lemmy_1     |   24: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
lemmy_1     |   25: tokio::runtime::runtime::Runtime::block_on
lemmy_1     |   26: std::sys_common::backtrace::__rust_begin_short_backtrace
lemmy_1     |   27: core::ops::function::FnOnce::call_once{{vtable.shim}}
lemmy_1     |   28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
lemmy_1     |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
lemmy_1     |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
lemmy_1     |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
lemmy_1     |       std::sys::unix::thread::Thread::new::thread_start
lemmy_1     |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
lemmy_1     |    0: lemmy_apub::insert_activity
lemmy_1     |            with ap_id=Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lemmy.world")), port: None, path: "/activities/announce/6f7bf258-252f-4f48-9b09-2f23027e5f2c", query: None, fragment: None } local=false sensitive=false
lemmy_1     |              at crates/apub/src/lib.rs:179
lemmy_1     |    1: lemmy_apub::activities::community::announce::receive
lemmy_1     |              at crates/apub/src/activities/community/announce.rs:141
lemmy_1     |    2: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=POST http.scheme="http" http.host=lemmy.lemist.de http.target=/inbox otel.kind="server" request_id=58dc363a-abf3-477e-bf93-86c122d3abfe http.status_code=400 otel.status_code="OK"
lemmy_1     |              at src/root_span_builder.rs:16
lemmy_1     | LemmyError { message: None, inner: duplicate key value violates unique constraint "idx_activity_ap_id"
lemmy_1     | 
lemmy_1     | Stack backtrace:
lemmy_1     |    0: lemmy_apub::insert_activity::{{closure}}::{{closure}}
lemmy_1     |    1: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
lemmy_1     |    2: lemmy_apub::activities::community::announce::<impl activitypub_federation::traits::ActivityHandler for lemmy_apub::protocol::activities::community::announce::AnnounceActivity>::receive::{{closure}}
lemmy_1     |    3: <activitypub_federation::protocol::context::WithContext<T> as activitypub_federation::traits::ActivityHandler>::receive::{{closure}}
lemmy_1     |    4: <alloc::boxed::Box<T> as activitypub_federation::traits::ActivityHandler>::receive::{{closure}}
lemmy_1     |    5: actix_web::handler::handler_service::{{closure}}::{{closure}}
lemmy_1     |    6: <actix_web::resource::Resource<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}
lemmy_1     |    7: <actix_web::scope::Scope<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}
lemmy_1     |    8: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
lemmy_1     |    9: <actix_web::middleware::compress::CompressResponse<S,B> as core::future::future::Future>::poll
lemmy_1     |   10: <actix_cors::middleware::CorsMiddleware<S> as actix_service::Service<actix_web::service::ServiceRequest>>::call::{{closure}}
lemmy_1     |   11: <tracing_actix_web::middleware::TracingResponse<F,RootSpanType> as core::future::future::Future>::poll
lemmy_1     |   12: <actix_service::map_err::MapErrFuture<A,Req,F,E> as core::future::future::Future>::poll
lemmy_1     |   13: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
lemmy_1     |   14: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
lemmy_1     |   15: <actix_service::and_then::AndThenServiceResponse<A,B,Req> as core::future::future::Future>::poll
lemmy_1     |   16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
lemmy_1     |   17: tokio::runtime::task::core::Core<T,S>::poll
lemmy_1     |   18: tokio::runtime::task::harness::Harness<T,S>::poll
lemmy_1     |   19: tokio::task::local::LocalSet::tick
lemmy_1     |   20: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
lemmy_1     |   21: <core::pin::Pin<P> as core::future::future::Future>::poll
lemmy_1     |   22: tokio::runtime::scheduler::current_thread::Context::enter
lemmy_1     |   23: tokio::macros::scoped_tls::ScopedKey<T>::set
lemmy_1     |   24: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
lemmy_1     |   25: tokio::runtime::runtime::Runtime::block_on
lemmy_1     |   26: std::sys_common::backtrace::__rust_begin_short_backtrace
lemmy_1     |   27: core::ops::function::FnOnce::call_once{{vtable.shim}}
lemmy_1     |   28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
lemmy_1     |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
lemmy_1     |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
lemmy_1     |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
lemmy_1     |       std::sys::unix::thread::Thread::new::thread_start
lemmy_1     |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17, context: SpanTrace [{ target: "lemmy_apub", name: "insert_activity", fields: "\u{1b}[3map_id\u{1b}[0m\u{1b}[2m=\u{1b}[0mUrl { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"lemmy.world\")), port: None, path: \"/activities/announce/6f7bf258-252f-4f48-9b09-2f23027e5f2c\", query: None, fragment: None } \u{1b}[3mlocal\u{1b}[0m\u{1b}[2m=\u{1b}[0mfalse \u{1b}[3msensitive\u{1b}[0m\u{1b}[2m=\u{1b}[0mfalse", file: "crates/apub/src/lib.rs", line: 179 }, { target: "lemmy_apub::activities::community::announce", name: "receive", file: "crates/apub/src/activities/community/announce.rs", line: 141 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "\u{1b}[3mhttp.method\u{1b}[0m\u{1b}[2m=\u{1b}[0mPOST \u{1b}[3mhttp.scheme\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"http\" \u{1b}[3mhttp.host\u{1b}[0m\u{1b}[2m=\u{1b}[0mlemmy.lemist.de \u{1b}[3mhttp.target\u{1b}[0m\u{1b}[2m=\u{1b}[0m/inbox \u{1b}[3motel.kind\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"server\" \u{1b}[3mrequest_id\u{1b}[0m\u{1b}[2m=\u{1b}[0m58dc363a-abf3-477e-bf93-86c122d3abfe \u{1b}[3mhttp.status_code\u{1b}[0m\u{1b}[2m=\u{1b}[0m400 \u{1b}[3motel.status_code\u{1b}[0m\u{1b}[2m=\u{1b}[0m\"OK\"", file: "src/root_span_builder.rs", line: 16 }] }`

These errors happen for activities from all instances, not just lemmy.world. I have compiled the most recent master version of lemmy (compiled today at 12:30 UTC), with this pull request merged as well: https://github.com/LemmyNet/lemmy/pull/3483

### Steps to Reproduce

1. Start the backend server
2. Wait for federated activities to start pouring in

### Technical Details

Can't attach lemmy.log as it would exceed GitHub's limit, I hope my excerpt above gives enough info.

OS: Ubuntu Server 20.04

Browser console errors are (hopefully) not relevant.

### Version

0.18.1-rc.9-23-gfe1ab96a3

### Lemmy Instance URL

lemmy.lemist.de

**Comment by phiresky** [comment]
there's a few things that should probably happen here:

* duplicates on `idx_activity_ap_id` should probably be logged as a warning at most
* if idx_activity_ap_id triggers, the HTTP response should still be 200 OK - 4XX. otherwise the sending instance will keep resending the request since it thinks the receiver is down ( https://github.com/LemmyNet/activitypub-federation-rust/blob/af92e0d53204a2ccd13bc0db3c58de24bff646bf/src/activity_queue.rs#L194 ). looks like it should be responding with 400 so that should be ok.
* need to figure out *why* this happens? it can't be reduced to zero because the node can always go down after inserting and before being able to send the OK response. but with the amounts it seems either the sender is wrongly thinking the receiver hasn't received it, or the receiver is sending wrong responses

**Comment by LemiSt24** [comment]
As long as I am reading this "WARN Error encountered" correctly, I think they are just warnings, my mistake.

Nevertheless, there are thousands of these warnings in my log.

**Comment by skariko** [comment]
On Lemmy 0.18.0 I can confirm that even in my docker logs there are plenty of warnings of that type:

`lemmy_1     | LemmyError { message: None, inner: duplicate key value violates unique constraint "idx_activity_ap_id", context: SpanTrace [{ target: "lemmy_apub", name: "insert_activity", fields: "ap_id=Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"feddit.it\")), port: None, path: \"/activities/like/5fad3a34-8b73-4a4b-8031-f9fe5e579525\", query: None, fragment: None } local=false sensitive=true", file: "crates/apub/src/lib.rs", line: 159 }, { target: "lemmy_apub::activities::voting::vote", name: "receive", file: "crates/apub/src/activities/voting/vote.rs", line: 71 }, { target: "lemmy_apub::activities::community::announce", name: "receive", file: "crates/apub/src/activities/community/announce.rs", line: 141 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=feddit.it http.target=/inbox otel.kind=\"server\" request_id=4bd92683-6be1-4897-960b-bade5cefd5a8", file: "src/root_span_builder.rs", line: 16 }] }`

**Comment by RocketDerp** [comment]
On Lemmy 0.18.2 now. I added logging to the insert_activity code to try and figure out what is going on here. This is what I saw:

```
2023-07-12T16:50:25.172155Z DEBUG federation: apub.lib.rs.insert_activity DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lemmy.ml")), port: None, path: "/activities/announce/d299621e-6de4-4227-931f-38c5058c2ad2", query: None, fragment: None }) Object {"actor": String("https://lemmy.ml/c/amd"), "to": Array [String("https://www.w3.org/ns/activitystreams#Public")], "object": Object {"id": String("https://lemmy.world/activities/like/28f19065-09fa-49bc-b30d-ea26512d5618"), "actor": String("https://lemmy.world/u/MistyBubz"), "object": String("https://lemmy.world/post/1310963"), "type": String("Like"), "audience": String("https://lemmy.ml/c/amd")}, "cc": Array [String("https://lemmy.ml/c/amd/followers")], "type": String("Announce"), "id": String("https://lemmy.ml/activities/announce/d299621e-6de4-4227-931f-38c5058c2ad2")}

2023-07-12T16:51:17.446228Z DEBUG federation: apub.lib.rs.insert_activity DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lemmy.ml")), port: None, path: "/activities/announce/d299621e-6de4-4227-931f-38c5058c2ad2", query: None, fragment: None }) Object {"actor": String("https://lemmy.ml/c/amd"), "to": Array [String("https://www.w3.org/ns/activitystreams#Public")], "object": Object {"id": String("https://lemmy.world/activities/like/28f19065-09fa-49bc-b30d-ea26512d5618"), "actor": String("https://lemmy.world/u/MistyBubz"), "object": String("https://lemmy.world/post/1310963"), "type": String("Like"), "audience": String("https://lemmy.ml/c/amd")}, "cc": Array [String("https://lemmy.ml/c/amd/followers")], "type": String("Announce"), "id": String("https://lemmy.ml/activities/announce/d299621e-6de4-4227-931f-38c5058c2ad2")}
```

The second one is throwing the error. What is interesting to me is the timing, about 1 minute later, the second INSERT attempt with the same data. Can we determine what this end-user is doing with votes/likes on post https://lemmy.world/post/1310963 that is triggering the outbound federation activity from lemmy.world to lemmy.ml then to my instance?

**Comment by RocketDerp** [comment]
Now this one isn't a simple "Like" object, but a new posting:

```
2023-07-12T17:05:40.193915Z DEBUG federation: apub.lib.rs.insert_activity DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lemmy.world")), port: None, path: "/activities/announce/3afbbb1f-4188-49ab-a9cc-af91bf2b0b13", query: None, fragment: None }) Object {"actor": String("https://lemmy.world/c/photography"), "to": Array [String("https://www.w3.org/ns/activitystreams#Public")], "object": Object {"id": String("https://lemmy.world/activities/create/c24338e4-b4e7-43f5-ac31-cb9f02bdd603"), "actor": String("https://lemmy.world/u/PrinzMegahertz"), "to": Array [String("https://www.w3.org/ns/activitystreams#Public")],
"object": Object {"type": String("Page"), "id": String("https://lemmy.world/post/1392872"), "attributedTo": String("https://lemmy.world/u/PrinzMegahertz"), "to": Array [String("https://lemmy.world/c/photography"), String("https://www.w3.org/ns/activitystreams#Public")],
"name": String("Thom Hogan: How much effort dors it take?"), "cc": Array [], "content": String("<p>Today’s topic is simple: you’re out on a photography session; how much effort does it take to get a great image?</p>\n"), "mediaType": String("text/html"), "source": Object {"content": String("Today’s topic is simple: you’re out on a photography session; how much effort does it take to get a great image?"), "mediaType": String("text/markdown")}, "attachment": Array [Object {"href": String("https://bythom.com/newsviews/how-much-effort-does-it.html"), "type": String("Link")}], "commentsEnabled": Bool(true), "sensitive": Bool(false), "published": String("2023-07-12T17:05:22.632407+00:00"), "language": Object {"identifier": String("en"), "name": String("English")}, "audience": String("https://lemmy.world/c/photography")}, "cc": Array [String("https://lemmy.world/c/photography")], "type": String("Create"), "audience": String("https://lemmy.world/c/photography")}, "cc": Array [String("https://lemmy.world/c/photography/followers")], "type": String("Announce"), "id": String("https://lemmy.world/activities/announce/3afbbb1f-4188-49ab-a9cc-af91bf2b0b13")}

2023-07-12T17:06:32.753160Z DEBUG federation: apub.lib.rs.insert_activity DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lemmy.world")), port: None, path: "/activities/announce/3afbbb1f-4188-49ab-a9cc-af91bf2b0b13", query: None, fragment: None }) Object {"actor": String("https://lemmy.world/c/photography"), "to": Array [String("https://www.w3.org/ns/activitystreams#Public")], "object": Object {"id": String("https://lemmy.world/activities/create/c24338e4-b4e7-43f5-ac31-cb9f02bdd603"), "actor": String("https://lemmy.world/u/PrinzMegahertz"), "to": Array [String("https://www.w3.org/ns/activitystreams#Public")],
"object": Object {"type": String("Page"), "id": String("https://lemmy.world/post/1392872"), "attributedTo": String("https://lemmy.world/u/PrinzMegahertz"), "to": Array [String("https://lemmy.world/c/photography"), String("https://www.w3.org/ns/activitystreams#Public")],
"name": String("Thom Hogan: How much effort dors it take?"), "cc": Array [], "content": String("<p>Today’s topic is simple: you’re out on a photography session; how much effort does it take to get a great image?</p>\n"), "mediaType": String("text/html"), "source": Object {"content": String("Today’s topic is simple: you’re out on a photography session; how much effort does it take to get a great image?"), "mediaType": String("text/markdown")}, "attachment": Array [Object {"href": String("https://bythom.com/newsviews/how-much-effort-does-it.html"), "type": String("Link")}], "commentsEnabled": Bool(true), "sensitive": Bool(false), "published": String("2023-07-12T17:05:22.632407+00:00"), "language": Object {"identifier": String("en"), "name": String("English")}, "audience": String("https://lemmy.world/c/photography")}, "cc": Array [String("https://lemmy.world/c/photography")], "type": String("Create"), "audience": String("https://lemmy.world/c/photography")}, "cc": Array [String("https://lemmy.world/c/photography/followers")], "type": String("Announce"), "id": String("https://lemmy.world/activities/announce/3afbbb1f-4188-49ab-a9cc-af91bf2b0b13")}
```

And like the previous one, the timing is around 50 seconds from the previous. In this example, it is only two servers involved, the community is homed on the same server as the post was created, lemmy.world instance. I checked for edits, there are no edits to the post (there is a typo in the subject, "does"). So lemmy.world and lemmy.ml are both sending me these duplicates about 50 seconds apart.

**Comment by Nutomic** [comment]
This is from checks to avoid receiving the same activity twice. https://github.com/LemmyNet/lemmy/pull/3583 should get rid of the error messages.

**Comment by RocketDerp** [comment]
What's the behavior with 0.18.3 now that it has been released?

**Comment by Nutomic** [comment]
Looks like this is fixed.
