### ISSUE TITLE
Remember Language (or default language)

### ISSUE THREAD

**Issue by jessearmstrong** [LemmyNet/lemmy#3513]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

It's annoying to have to select your language from a long list every time you create a post or make a comment.

### Describe the solution you'd like.

We set language in our profiles and every time we post. It would be great if the UI would auto select our profile langue or whatever language we last selected to post/comment. 

### Describe alternatives you've considered.

I don't know that there would really be alternatives. It's just scroll through a giant list each post or have your most common selection pre chosen.

**Comment by Nutomic** [comment]
If you only have one language active in user settings, that will be selected automatically. Same if the community only allows one language. Otherwise I believe https://github.com/LemmyNet/lemmy/issues/2870 is a better solution so Ill close this.
