### ISSUE TITLE
[Bug]: Missing posts, Communities not showing all posts

### ISSUE THREAD

**Issue by mermit** [LemmyNet/lemmy#3515]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Posts are missing on some communities, for example:
- [https://lemm.ee/c/citiesskylines@lemmy.ml](https://lemm.ee/c/citiesskylines@lemmy.ml) shows only 2 posts, (UI: 0.18.1-rc.11, BE: 0.18.1-rc.10)
- [https://lemmy.ml/c/citiesskylines](https://lemmy.ml/c/citiesskylines) also shows only 2 posts, (UI: 0.18.1-rc.11, BE: 0.18.1-rc.10)
- but [https://lemmy.ca/c/citiesskylines@lemmy.ml](https://lemmy.ca/c/citiesskylines@lemmy.ml) shows "all" posts, (UI: ?, BE: 0.18.0)
- and [https://lemmy.world/c/citiesskylines@lemmy.ml](https://lemmy.world/c/citiesskylines@lemmy.ml) too. (UI: 0.18.1-rc.10,
BE: 0.18.1-rc.9-14-ge71951309)

Other users also seem to be having the same issues: https://lemm.ee/post/737999

### Steps to Reproduce

1. Go To [https://lemmy.ml/c/citiesskylines](https://lemmy.ml/c/citiesskylines), only showing 2 posts
2. Go To [https://lemmy.world/c/citiesskylines@lemmy.ml](https://lemmy.world/c/citiesskylines@lemmy.ml), showing all expected posts

### Technical Details

Affected instances are running UI: 0.18.1-rc.11, BE: 0.18.1-rc.10.

Could possibly be a UI error too, however the same thing happens on the Memmy IOS App 

### Version

BE 0.18.1-rc.10

### Lemmy Instance URL

lemm.ee, lemmy.ca

**Comment by RocketDerp** [comment]
> * https://lemm.ee/c/citiesskylines@lemmy.ml shows only 2 posts, (UI: 0.18.1-rc.11, BE: 0.18.1-rc.10)

For the "Active", it shows only 3 (one was added 30 minutes ago), but "new" shows all of them: https://lemm.ee/c/citiesskylines@lemmy.ml?dataType=Post&page=1&sort=New

**Comment by dessalines** [comment]
This is due to a filter I added to massively improve performance of the active and hot sorts. I'll have to revert it unfortunately I think.

**Comment by wereii** [comment]
UI: 0.18.1-rc.11  
BE: 0.18.1-rc.10


Can confirm the same problem. This community has been first visited on the versions specified.
https://biglemmowski.win/c/bar@discuss.tchncs.de


Additionally seeing unsynced posts again.
I first loaded this post about an hour and something ago, as of writing it has not synced yet.
- https://biglemmowski.win/post/23090 (1 vote, 0 comments)
- https://lemmy.world/post/936166 (original post, 8 votes, 1 comment)

Trying a different other instance yields the same thing:
- https://biglemmowski.win/post/23182 (first loaded as of writing this comment, sitting at 0 v. 0 c.)
- https://lemm.ee/post/737999  (original post, instance has same UI/BE versions, 9v. 7c.)

**Comment by finnim** [comment]
I can confirm that this also causes pinned posts to disappear.

If I remember correctly, the way reddit calculated "hot' was to give a weight to the score and a weight to the newness of a post. The older it got the lower its hotness due to age becoming an exponentially negative multiplier. With such a formula it should be possible to calculate a hot score without having to filter.

**Comment by Shatur** [comment]
@Nutomic I recently posted [this](https://lemmy.ml/post/1884869) post to game development. But the post is missing if you click on the community. Is this this same bug, or should I open a separate issue?

**Comment by mermit** [comment]
@Shatur I can see it from the community itself (not logged in on lemmy.ml tho). Is it possible that you have “show read posts” turned off?

**Comment by Shatur** [comment]
Oh, I just tried it again and I can see it now too.
That's odd, I didn't change anything and the post was missing yesterday and before writing my message here. Also, the post didn't show up on my profile before.
