### ISSUE TITLE
Enable Users to Customize Vote Federation

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3519]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Due to vote federation across instances, all instances tend to be more of the same, which dilutes the thematic uniqueness of each instance.

### Describe the solution you'd like.

Introduce a user setting or instance admin option that allows opting out or limiting vote federation. This would enable each instance to maintain its thematic focus and uniqueness, providing a more tailored experience for users and instances.

* Users could choose to only count votes from their own instance.
* Users could choose to only count votes from closely aligned instances
* A weighting system could value votes from some instances more than others

### Describe alternatives you've considered.

An alternative could be to provide instance administrators with these options too, but this would affect all users on the instance and may not cater to individual user preferences. The proposed user setting would allow for more personalization and flexibility.

**Comment by Nutomic** [comment]
In a way this is already the case because votes from blocked instances (or instances not on the federation allowlist) are rejected. I dont think it makes sense to add any restrictions specifically for voting.

**Comment by 8ullyMaguire** [comment]
While it's true that votes from blocked instances or instances not on the federation allowlist are rejected, this doesn't address the core issue I raised. The problem is that vote federation across instances can dilute the thematic uniqueness of each instance, making them feel more homogeneous. By introducing a user setting or instance admin option to opt-out or limit vote federation, we can enable instances to maintain their thematic focus and uniqueness. This would provide a more tailored experience for users and instances, as they could choose to only count votes from their own instance or from closely aligned instances. A weighting system could also be implemented to value votes from some instances more than others. The current system of blocking instances or using a federation allowlist is a more binary approach that doesn't offer the same level of personalization and flexibility. The proposed solution would give users and instance administrators more control over how votes are counted and federated, ultimately leading to a more diverse and unique experience across instances.
