### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by systract** [LemmyNet/lemmy#3522]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

**Deleted post still viewable on other federated instances.**

### Steps to Reproduce

- created a post in instance 1.

- View it in instance 2, verified the post saved in instance 2 db.

- Delete the post from instance 1.

- Can't see the post from instance 1 UI.

- Went to instance  2, the post is still there.

- Click the link, the content is also there, but with a header: "Error 403 (Forbidden)!!"

- In DB table, there is field "removed", but the value is still "false".

### Technical Details

DB Table name: post

### Version

UI: 0.18.1-rc.10 BE: 0.18.1-rc.9

**Comment by Nutomic** [comment]
At least provide a title...

https://github.com/LemmyNet/lemmy/issues/3535
