### ISSUE TITLE
Make like scores in comment_like and post_like tables an enum

### ISSUE THREAD

**Issue by pijuszczyk** [LemmyNet/lemmy#3524]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

While working on PR #3523, an observation came to my mind that the current way of storing like scores as Int2 is perhaps suboptimal - we rely on interpreting hard-coded -1 as dislike, 0 as undo and 1 as like.

### Describe the solution you'd like.

If we stored that as a simple C-like enum:

- no explanation comments would be needed for interpreting the value
- the score value passed anywhere would be verbose so that would mean potentially less bugs and less misuses (both in backend and API calls)
- we could introduce new values and change the interpretations of the existing ones more easily
- such a solution would be even more space-efficient (1B vs 2B).

I'd recommend either something similar to VoteType or extending and reusing VoteType. We could also introduce a score-aware undo, i.e.

```
#[derive(EnumString, Display, Debug, Serialize, Deserialize, Clone, Copy, Default, PartialEq, Eq)]
pub enum VoteType {
  Like,
  Dislike,
  UndoLike,
  UndoDislike,
}
```

### Describe alternatives you've considered.

We can still use an int - it's probably sufficient for this job and continuing to use it won't generate a need for migrations.

**Comment by Nutomic** [comment]
Yes that sounds good.

**Comment by dessalines** [comment]
I doubt this would be a good idea, as it would break, or make summing votes unecessarily complicated.

**Comment by pijuszczyk** [comment]
It's true that in [some cases](https://github.com/LemmyNet/lemmy/blob/main/migrations/2020-08-03-000110_add_preferred_usernames_banners_and_icons/up.sql#L172) it would make the vote summing logic more complicated but in the [others](https://github.com/LemmyNet/lemmy/blob/main/migrations/2020-08-03-000110_add_preferred_usernames_banners_and_icons/up.sql#L430-L431) the code already looks very similar to what would be the final effect, minus the transparency of enum values. In the end it's up to you guys to decide but in my opinion the benefits (transparency of values, possibility to extend the value range without forced meanings, size in db) outweigh the drawbacks.

**Comment by Nutomic** [comment]
Seems like were not doing this.
