### ISSUE TITLE
Automatic image resizing

### ISSUE THREAD

**Issue by michaeldileo** [LemmyNet/lemmy#3534]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I notice when I'm browsing the feed that there are a lot of unnecessarily large images being downloaded, probably from mobile or cameras uploading on full resolution. 

### Describe the solution you'd like.

It seems like it'd be user friendly to either automatically shrink the images to more web friendly sizes with an opt-in for full size on upload (backend or frontend), or have the backend return a scaled down image for thumbnails while scrolling the feed.

### Describe alternatives you've considered.

Above

**Comment by dessalines** [comment]
We already shrink the sizes for thumbnails in lemmy-ui using pictrs's transformation abilities.

**Comment by dullbananas** [comment]
An intermediate size like 1000px might be needed
