### ISSUE TITLE
[Bug]: moderator removal of posts not working across federation instances. Only the community home instance has the post removed

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3535]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

At the time of this bug report, the post is 8 hours old. Which puts it at the page break between 1st and 2nd page on Lemmy.ml listing. Not sure if that is related.

It is also possible that the post was moderated for being off-topic (a lemmy technical question that people confuse as "asklemmy" purpose).  If so, should moderation not have been shared back to the other 2 servers - it still appears in their listing of posts for that community.

### Steps to Reproduce

1. first server: post originated on apn_id: https://lemm.ee/post/791973
2. second server: lemmy.ml is the home for the community, [asklemmy@lemmy.ml](https://lemmy.ml/c/asklemmy?dataType=Post&page=1&sort=New)
3. third server shows the post: https://lemmy.ca/post/1226503

The curiosity here is why lemmy.ml does not show the post when it is the middle-man, home, for the asklemmy community. How did it get relayed between the first and third server and end up missing on lemmy.ml?

### Technical Details

N/A

### Version

N/A

### Lemmy Instance URL

lemmy.ml

**Comment by RocketDerp** [comment]
I found another case of this, 7 hours ago from time of this comment:
https://lemmy.world/post/1183289 origin to 3rd server: https://lemmy.ca/post/1245505 and I found it listed on a 4th server: https://lemm.ee/post/826998

In both these cases, it is likely a moderator of asklemmy community removed the posting as being off-topic. So why lemmy.ca and lemm.ee (and other servers, presume) still showing it in their lists sort-by "New" posts?

It looks like mod removal of a post isn't federating to subscribed servers?

**Comment by RocketDerp** [comment]
Spot checking this problem, it seems to be still ongoing, this is the same post on 3 servers:

https://lemmy.lif.ovh/post/10872  
https://lemmy.ca/post/1352524  
https://lemmy.world/post/1341715  

Lemmy.ml, the home to the community, no longer lists the post in "New" sort, having been moderated. This time I found the post https://lemmy.ml/post/1936050 in the mod log, so I'm confident that moderation itself is the source of the problem.

**Comment by Nutomic** [comment]
This seems to be a problem with the "remove content" checkbox on ban user action. Would be very helpful to have an api test case which can reproduce the problem.
