### ISSUE TITLE
[Bug]: GetComments returns 0 comments when not including community ID with non-local community

### ISSUE THREAD

**Issue by TheBrokenRail** [LemmyNet/lemmy#3541]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

If you make a `GetComments` request for a post on a non-local community without including `community_id`, it won't return any comments (just an empty array). This API call works fine for local communities and only requires the post ID for `GetPost` in both local and non-local communities.

This can be fairly easily worked-around by calling `GetPost` to get the community ID before calling `GetComments` with both IDs, but I'd prefer not to make a redundant API call.

### Steps to Reproduce

Here is the broken API call compared with working variants:

| | Local community | Non-local community |
| --- | --- | --- |
| `GetPost` with only post ID | [Works](https://lemmy.ml/api/v3/post?id=1808829) | [Works](https://lemmy.ml/api/v3/post?id=1772935) |
| `GetComments` with only post ID | [Works](https://lemmy.ml/api/v3/comment/list?post_id=1808829) | [Doesn't Work (The Issue In Question)](https://lemmy.ml/api/v3/comment/list?post_id=1772935) |
| `GetComments` with post ID and community | [Works](https://lemmy.ml/api/v3/comment/list?post_id=1808829&community_id=2) | [Works](https://lemmy.ml/api/v3/comment/list?post_id=1772935&community_id=89927) |

### Technical Details

I don't run my own Lemmy instance, so I don't have any logs.

### Version

0.18.1

### Lemmy Instance URL

Tested on both lemmy.ml and lemmy.world

**Comment by RocketDerp** [comment]
I'm assuming you are talking about the API. There is a community on Lemmy for app developers, and this topic has come up several times: https://lemmy.ml/post/1630085?scrollToComments=true

Most likely the Type_=All is missing, and it is a non-local community?

**Comment by TheBrokenRail** [comment]
Yes, that was it! Thank you!
