### ISSUE TITLE
Why cant i log in, i got banned but there is nothing in the modlog, and i didnt do anything just browsing

### ISSUE THREAD

**Issue by MJB9000** [LemmyNet/lemmy#3542]
### Question

Cant login, first 404site.ban, then found my account was banned through another account which is weird because this is my first hour on the site and i haven’t interacted to done anything yet, modlog doesn’t show anything, cleared cache, reset password, tried to login with email, nothing worked.

One thing changed was after the successful password reset i used to get site ban 404 error, now I get “logged in” but when I log in it doesn’t do anything and I’m stuck.

Username is MJB9000

**Comment by L3v3L** [comment]
You need to talk to the people who run the instance you were on. This here, is just the code for project they are running.
