### ISSUE TITLE
[Bug]: Posts featured by a remote mod are not featured on host instance

### ISSUE THREAD

**Issue by jspayne** [LemmyNet/lemmy#3544]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When a mod who is logged in to an instance different from where a community is hosted, feature actions are not federated to the host instance.

### Steps to Reproduce

1. user@instance1 is made mod of !community@instance2
2. user@instance1 makes a post in !community@instance2
3. user@instance1 make the post Featured in Community

Expected:
Post is visible as featued in !community@instance2 by user2@instance2

Actual:
Post is visible in !community@instance2 by user2@instance2, but it is not featured.

### Technical Details

This bug is illustrated by this post (as viewed from two different instances):

https://fanaticus.social/post/150490

https://lemmy.world/post/1197725

### Version

BE 0.18.1

### Lemmy Instance URL

lemmy.world, fanaticus.social

**Comment by RocketDerp** [comment]
This may be related to Issue #3535 that I've been tracking for the past 18 hours.  It seems moderator-specific changes to posts, such as removing a post as off-topic, are not working on subscribed peer instances (servers).

**Comment by RocketDerp** [comment]
This specific bug is confirmed and new testing code to reproduce it is now in https://github.com/LemmyNet/lemmy/pull/3745

**Comment by dullbananas** [comment]
I am currently working on changes to triggers which should fix this. For now, a workaround is to wait for the post to appear on the other instance before featuring it.
