### ISSUE TITLE
Cache existing post order when loading next page.

### ISSUE THREAD

**Issue by xthexder** [LemmyNet/lemmy#3547]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently when reading through posts on an active community, by the time I get to the bottom and hit "Next Page" more posts and comments are made, pushing many of the Page 1 posts onto Page 2, making me see half the same posts again.

This is rather annoying, since it means means it's possible to miss posts entirely if they happen to move between pages at the wrong time.

### Describe the solution you'd like.

Reddit seems to cache a single post order until you do a full page refresh or your session gets too old. It's unclear to me if this is a client-side session thing or if the server actually keeps track of the historical post order for the user.

### Describe alternatives you've considered.

A client could potentially make multiple page requests at a time and resort / deduplicate posts itself, however backend integration in the API would definitely be preferred for performance.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3872
