### ISSUE TITLE
Web Push API support

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#3552]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Users would like notifications for replies, mentions and DMs:

- without having the website foregrounded, and
- without installing a 3rd party native app.

### Describe the solution you'd like.

Implement [Web Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API)

### Describe alternatives you've considered.

No alternatives to the Push API exist.

### Additional context

- iOS [recently added](https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/) support for Web Push API. Android has had support for a while. https://caniuse.com/?search=web%20push
- [Mastodon supports web push](https://docs.joinmastodon.org/methods/push/) natively, might be a good place to start!

**Comment by Nutomic** [comment]
Closing in favor of https://github.com/LemmyNet/lemmy/issues/2631
