### ISSUE TITLE
Question: Is it possible to directly post to another lemmy instance with my domain name?

### ISSUE THREAD

**Issue by iopq** [LemmyNet/lemmy#3557]
### Question

Even if I'm not running a full instance, can I just directly post to another instance using my domain name and a username?

**Comment by sunaurus** [comment]
Hey 👋 

 It's not fully clear to me what you're asking, but in any case I think this issue tracker is not the right place for such a question. I recommend trying in https://lemmy.ml/c/lemmy_support.
