### ISSUE TITLE
Incorporating User Engagement Metrics in Lemmy's Sorting Algorithms

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3563]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Yes, the current "Top" sorting algorithms on Lemmy prioritize votes, which sometimes results in posts with thousands of votes and only a few comments appearing at the top. This can be frustrating as it may not accurately reflect user engagement. Additionally, sorting by "Most Comments" disregards votes completely, which is not ideal either. A balanced sorting algorithm that combines various metrics is needed to better represent user engagement and prevent manipulation through bot accounts.

### Describe the solution you'd like.

I propose that Lemmy incorporates a balanced sorting algorithm that considers multiple user engagement metrics, such as the number of comments, votes, time spent on a post, etc. For example, a "Balanced" sorting algorithm that considers 50% upvotes, 30% comments, and 20% time spent reading. By combining these factors, the sorting algorithm would better represent the interests of the community and be less susceptible to manipulation.

### Describe alternatives you've considered.

An alternative solution could be to implement a moderation system that detects and prevents vote manipulation, similar to Feature Upvote's approach. However, this may not address the issue of accurately representing user engagement in the sorting algorithm.

### Additional context

User engagement is a crucial aspect of any online platform, as it indicates the success and relevance of the content. Implementing a balanced sorting algorithm that combines various user engagement metrics would not only improve the overall user experience on Lemmy but also make the platform more resistant to manipulation. This approach would address the issue of posts with only a few comments appearing on the feed and provide a more accurate representation of user engagement on the platform.

**Comment by SudNeela** [comment]
I think this is a very important issue to tackle, but I'm unsure if this is the right place to do it (maybe this should be a discussion elsewhere)?

> I propose that Lemmy incorporates user engagement metrics into its sorting algorithms. This could include factors such as the number of comments, time spent on a post, and click-through rates. By considering user engagement, the sorting algorithm would better represent the interests of the community and be less susceptible to manipulation.

All three of these metrics are easy to manipulate too. Add more comments, spoof the amount of time one spends on a post, and have each account on your instance 'click' on your post. As an interim solution, I think this is a good idea. However, I don't think this is a good long-term solution.

On the other hand, an interesting idea to tackle would be to detect botnets and outright ban them / defederate with instances that are supporting any sort of botnets. There are ways to detect botnets and it might be worth thinking about integrating a botnet detection system within lemmy (although I'm unsure where this kind of a thing would fit in). If this isn't a good idea, maybe instances dedicated to detecting bad instances can be created, and these instances create some kind of a revocation list that other instances can follow.

**Comment by N1cknamed** [comment]
Engagement algorithms might be detrimental to the quality of posts that appear on the front page. Upvotes are a clear mark of approval by other users, comments and views are not. Implementing this would likely lead to controversial posts and "clickbait" having an easier time getting to the front page. Abuse and manipulation are of course always an issue, but I believe there are better ways of mitigating them.

Not saying the current implementation is perfect, but I'd advocate for caution when replacing it. _Positive_ engagement should be the goal, not just any engagement. Lest we create an environment a la Twitter.

**Comment by lionirdeadman** [comment]
> time spent on a post, and click-through rates

These would not stop bots as they could send the same signals unless this is not federated in which case the value of these metrics decreases a lot IMO

Not only that but it comes at a great privacy cost.

> number of comments

As for the number of comments, well, that's already *active* sorting.

**Comment by 8ullyMaguire** [comment]
> (PS: Could you change the title to something like "Change sorting algorithms to protect against bots"? The current one is not descriptive for someone looking at issues)

Sorry, I had focused too much on the bots when what I want is a more balanced sorting algorithm, I've rewritten the post to better express myself.
