### ISSUE TITLE
Moderators editing incorrect metadata: eg nsfw

### ISSUE THREAD

**Issue by PennyJim** [LemmyNet/lemmy#3566]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There's is likely to be users either maliciously or negligently marking their posts with some incorrect metadata. Resulting in some users coming across nsfw posts when they do not want to.

While moderators and admins can just delete the post, that should not be the only option, given it still provides something to the community.

### Describe the solution you'd like.

I'd like to see moderators gain the ability to "fix" incorrect metadata rather than resorting to nuking the post. While abusable, we could always log the change in the post data. Viewable like:

- nsfw (from moderators)
- nsfw (from [mod icon]@user)

I've said "metadata" because I could see this being used for language tags (or tags in general once they're a thing), but I'm just a user and those seem to be invisibly working(? Considering that I've seen it recommended that you keep unknown as a language, I could see others considering differently).

### Describe alternatives you've considered.

Maybe moderators could hide a post (with clear indication so shadow banning isn't a thing?) and let the user fix it themselves when prompted?

I don't think that is that great of an idea though, as it relies on the party at fault to fix their error(?) and there would also have to be some additional structure to bring the mod's attention back to it.

**Comment by ZephyrXero** [comment]
**+1** I need this feature for a community I mod right now. Specifically the ability to mark a post as NSFW. Right now I have 2 poor options, either message the user asking them to do it themselves and hope they comply promptly, or just remove the post and then deal with trying to get them to tag it correctly and restore once they have. This seems like a pretty fundamental moderation ability to me

**Comment by dessalines** [comment]
Closing this as this was already discussed in #4065 . 

Removing un-marked NSFW posts is the best current solution, that still keeps user's integrity that they can be sure their content cannot be edited or changed by a moderator or admin.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/5869 adds a new endpoint which allows mods to change the nsfw tag.

**Comment by dessalines** [comment]
Fixed by above.
