### ISSUE TITLE
[Bug]: Local instance is processing remote updates even if not subcribed anymore

### ISSUE THREAD

**Issue by michelsup** [LemmyNet/lemmy#3568]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

If you simply prune your database, so not unsubscribing to every previously subscribed communities, your local instance is still processing every update pushed by the remotes instances, populating your database and your media folder with unwanted stuff.

### Steps to Reproduce

1. Stash your database 
2. Restart your federated instance
3. Every POST /inbox is processed with code 200, tables are updated, images stored, etc
4. Remove federation and every POST /inbox is going to error 400

### Technical Details

I understand you SHOULD unsubscribe for the remote instances to be aware you don't want updates anymore. But if for whatever reason this information is lost or not processed correctly, the local instance is bombarded with remote junk.
Moreover, with this system, a rogue instance can push everything to everyone. 
The best would be the local instance to refuse any unwanted updates, and tell the remote to stop pushing these unsolicited uodates. It would be safer, more robust and less detrimental for both server's resources.

### Version

0.18.1

### Lemmy Instance URL

michelsup.org

**Comment by WayneSheppard** [comment]
Rephrasing the issue:

The local server should have an authoritative list of communities it will accept federated actions for.   Any incoming action from a community not subscribed to shall be dropped.  Ideally the local server can respond with an unsubscribe message back to the remote server to halt further messages.

**Comment by Jasdemi** [comment]
Confirming that removed communities without any subscribers still receive posts and comments. The remove options only seems to hide the community from non-mods/admin.

Is there a way to tell remote instances to stop pushing updates no longer needed until that is fixed?

**Comment by MagsMagnoli** [comment]
I like the idea. It would be useful for an instance admin to be able to tell a remote instance to wipe all subscribers and stop sending updates to it. I thought that the allow/block lists in federation settings would do that but from reading logs they only locally reject the updates
