### ISSUE TITLE
[Bug]: community restricted to mods/admins for postings can cause problems for remote federation instances when the admin user is not a mod

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3571]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Lemmy server logs show frequent error:

```
 WARN lemmy_server::root_span_builder: not_a_mod_or_admin: not_a_mod_or_admin
   0: lemmy_api_common::utils::is_mod_or_admin
              at crates/api_common/src/utils.rs:51
    1: lemmy_apub::objects::post::from_json
              at crates/apub/src/objects/post.rs:161
    2: lemmy_apub::fetcher::post_or_comment::from_json
              at crates/apub/src/fetcher/post_or_comment.rs:80
    3: lemmy_apub::objects::comment::verify
              at crates/apub/src/objects/comment.rs:124
    4: lemmy_apub::fetcher::post_or_comment::verify
              at crates/apub/src/fetcher/post_or_comment.rs:68
    5: lemmy_apub::activities::voting::vote::verify
              at crates/apub/src/activities/voting/vote.rs:57
    6: lemmy_apub::activities::community::announce::receive
              at crates/apub/src/activities/community/announce.rs:157
    7: lemmy_server::root_span_builder::HTTP request
            with http.method=POST http.scheme="http" http.host=bulletintree.com http.target=/inbox otel.kind="server" request_id=e4ec5973-49b3-4454-8690-aa539ba20fa1
              at src/root_span_builder.rs:16

 LemmyError { message: Some("not_a_mod_or_admin"), inner: not_a_mod_or_admin, context: SpanTrace [{ target: "lemmy_api_common::utils", name: "is_mod_or_admin", file: "crates/api_common/src/utils.rs", line: 51 }, { target: "lemmy_apub::objects::post", name: "from_json", file: "crates/apub/src/objects/post.rs", line: 161 }, { target: "lemmy_apub::fetcher::post_or_comment", name: "from_json", file: "crates/apub/src/fetcher/post_or_comment.rs", line: 80 }, { target: "lemmy_apub::objects::comment", name: "verify", file: "crates/apub/src/objects/comment.rs", line: 124 }, { target: "lemmy_apub::fetcher::post_or_comment", name: "verify", file: "crates/apub/src/fetcher/post_or_comment.rs", line: 68 }, { target: "lemmy_apub::activities::voting::vote", name: "verify", file: "crates/apub/src/activities/voting/vote.rs", line: 57 }, { target: "lemmy_apub::activities::community::announce", name: "receive", file: "crates/apub/src/activities/community/announce.rs", line: 157 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=bulletintree.com http.target=/inbox otel.kind=\"server\" request_id=e4ec5973-49b3-4454-8690-aa539ba20fa1", file: "src/root_span_builder.rs", line: 16 }] }

```

Hacking in additional logging in the Rust code reveals that this post is the problem:

https://lemmy.world/post/1274909

The interesting thing about this post is that the user https://lemmy.world/u/lwadmin who posted **it is an admin** of the remote Instance, but **not a moderator for the restricted community**.  So my instance does not recognize them as an admin of my own server nor as a moderator of the community, rejecting the post.

Screen shot showing the user is "A"dmin, but no "M" for moderator.
![image](https://github.com/LemmyNet/lemmy/assets/113625597/b6b8fef6-e1eb-4dd5-828e-3aa42d691fa8)

### Steps to Reproduce

1. On Instance-A create a user who is admin
2. Have the user create a post in a community for which they are not a moderator, but the community is set to only allow moderators and admins to post.
3. Instance-B receives the post but does not recognize an admin of another instance as an admin. Nor was the user set as a moderator of the specific community, with that community set to require admin or moderator.

### Technical Details

See above

### Version

BE 0.18.1

### Lemmy Instance URL

lemmy.world

**Comment by RocketDerp** [comment]
In addition to checking my own instance, the Lemm.ml server does not show the posting either and I expect is logging the same errors:  https://lemmy.ml/c/lemmyworld@lemmy.world

**Comment by Nutomic** [comment]
Easiest fix for this might be changing the setting to "only mods can post". Then admins cant post in the community either, unless they make themselves mod first.
