### ISSUE TITLE
Local Only Communities

### ISSUE THREAD

**Issue by sekhat** [LemmyNet/lemmy#3573]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I have a single community on my instance, which the purpose of it is just local discussion and announcements.

I was quite annoyed this morning when I woke up to find a chunk of remote instance bots subscribed to it (looks like they were related to populating other instances "all" feeds).

Now, the problem here, is that that now causes me extra bandwidth usage to service other instances bots, that I don't need to use. (Though I can easily maintain for now, the level of bots, I can imagine if this gets more and more wide spread for instances to do, I would not be able to do so).

### Describe the solution you'd like.

I'd like an option to mark a community as local only, that prevents just that one community from

* Federating
* Allowing Remote Subscribers

### Describe alternatives you've considered.

The only option I've been able to find to manage this, (due to me not seeing any particular admin settings around this in the UI, or moderation settings to allow me to ban community subscribers easily), was open up the database, create a list of the subscribes, manually visit my local url for each of the remote users and ban them, then remove them from the community_followers table.

This is a royal pain. So it's not really an alternative.

**Comment by sekhat** [comment]
Last I checked, you don't *join* an instance with a remote account. You might subscribe to communities on a remote instance, but not the instance as a whole.

Now that's irrelevant either way, if I don't want remote users accessing a community, that's my decision as the instance/community owner.

**Comment by lionirdeadman** [comment]
This would also be quite helpful for communities that aim to help users of a particular instance

**Comment by Nutomic** [comment]
duplicate

**Comment by lionirdeadman** [comment]
I can't find the duplicate, can you link to it?

**Comment by Nutomic** [comment]
Here: https://github.com/LemmyNet/lemmy/issues/1576
