### ISSUE TITLE
Show Previews of/Re-Host images linked from twitter

### ISSUE THREAD

**Issue by liammcnabb** [LemmyNet/lemmy#3575]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When linking images from twitter, the URL is shown rather than the wanted image. This is a frustrating break of action when viewing image-related communities, and I feel needs to be rectified if people are looking to avoid opening other social media. We cannot justify just ignoring twitter in some instances as many artists use it as there sole uploading service.

### Describe the solution you'd like.

If the twitter link has an image embedded present the image rather than a url thumbnail

### Describe alternatives you've considered.

 If a twitter link is provided and the subject provides images, an option to re-host the image where the archive options are presented. This would allow the image preview to be shown without having to open up twitter. Optionally, you can also add a source link to the message area

### Additional context

This might become easier once multiple images per post are handled as suggested in other enhancment requests. But I think for the basics of the enhancement, you can just limit it to one image, and a post containing multiple images be considered a URL

**Comment by Dogeek** [comment]
In my opinion, this is better suited as a lemmy-ui issue. The lemmy backend is responsible for storing the links, the frontend is the one that should display them properly.
