### ISSUE TITLE
Add user setting to set default lemmy view

### ISSUE THREAD

**Issue by Dogeek** [LemmyNet/lemmy#3578]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When going to the base url of an instance (say https://lemmy.world ), the default view for posts is "Local Active" which might not be what the user is most interested in. I for one would appreciate "Subscribed Top Day" as the default view.

### Describe the solution you'd like.

Adding a couple of settings in the local_user table :

- default_user_post_sort: active / top day / top / top hour etc
- default_user_post_category : subscribed / local / all

Alternative lemmy frontend / apps could also make use of the feature (it would be handy in jerboa for instance)

### Describe alternatives you've considered.

This could also be stored as a purely local setting (think localStorage in the browser), but for sync purposes accross devices, adding those in the backend makes sense to me.

**Comment by noornee** [comment]
This already exists in settings page. 

![Screenshot_20230711-001116](https://github.com/LemmyNet/lemmy/assets/71889751/834927fe-db87-4868-be20-c4d9cf59ba8d)
