### ISSUE TITLE
Give instance users ability to see & revoke device sessions

### ISSUE THREAD

**Issue by bappitybup** [LemmyNet/lemmy#3579]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

in the event that I log into a public computer and forget to logout, I can't do anything about it unless I go back to the physical location and log myself out.

### Describe the solution you'd like.

it would be nice if users were able to see all of the devices that were using their account and the ability to choose to individually revoke their access (invalidate their sessions??)

### Describe alternatives you've considered.

i could just change my password or physically go back to that location and logout but it would be nice to be able to do that remotely.

**Comment by Nutomic** [comment]
You can invalidate all logins by changing your password.
