### ISSUE TITLE
Don't save read posts when "show_read_posts" is disabled

### ISSUE THREAD

**Issue by ajayyy** [LemmyNet/lemmy#3586]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

At the moment, your browsing history is still stored in the database when `show_read_posts` is disabled.

### Describe the solution you'd like.

Saving to the PostsRead database should not happen when `show_read_posts` is disabled.

The database either needs to be cleared when `show_read_posts` is disabled, or a new endpoint needs to be created to clear past history.

### Describe alternatives you've considered.

Originally, I worked on a PR to add a new option to not save the read information (https://github.com/LemmyNet/lemmy/pull/3503), but it was suggested to instead reused the `show_read_posts` setting.

**Comment by Nutomic** [comment]
wontfix: https://github.com/LemmyNet/lemmy/pull/3503
