### ISSUE TITLE
[Bug]: Lemmy 0.18.2 instances are not federating deletion of a post by user who created post

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3588]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I suspect some bug in newer changes since 0.18.0 - as I think we would have noticed this earlier. All servers involved in example are running 0.18.2

### Steps to Reproduce

1. Use a login on Lemmy.ml and go to the remote-homed community https://lemmy.ml/c/zztestlemmy000@lemm.ee and create a New Post.
2. Delete your new post after 30 seconds. Confirm it is deleted locally on Lemmy.ml - it should return an error page indicating couldnt_find_post
3. Go to the home instance of the community, see if the post still appears: https://lemm.ee/c/zztestlemmy000?dataType=Post&page=1&sort=New
__

### Technical Details

Using lemmy-ui front end, did not test with other API clients. The user is neither a moderator of the community or admin of either site.

Noteworthy that editing the title of a post did replicate correctly. It is deleting that seems to be the trouble. Testing of deleting a comment also worked fine.

### Version

BE: 0.18.2

### Lemmy Instance URL

lemm.ee lemmy.ml

**Comment by RocketDerp** [comment]
The whole delete behavior isn't right on remote instances.  If you are on lemmy.ml and the community is homed on lemm.ee - if you create your own post and delete that post on lemmy.ml - you can no longer restore it. lemmy.ml will now allow you to read your own deleted post.

**Comment by WayneSheppard** [comment]
Confirmed for Posts.

Tested Comments, these deletes did federate for me

**Comment by RocketDerp** [comment]
Thank you for confirming the problem. I'm working on the code right now, hopefully we can get a fix in before the weekend.

**Comment by RocketDerp** [comment]
It looks like the bug might have been introduced on June 23, which explains why it wasn't happening before and seems only in recent updates.  This commit looks suspicious: https://github.com/LemmyNet/lemmy/commit/dce79b83bfe4eddbe94a4b3846bc20624ef8e4c4

**Comment by RocketDerp** [comment]
Your comment is still not deleted here: https://bulletintree.com/comment/724726

The "community home" server doesn't seem to be sending out delete comments to the federated downstream subscribers. Which is similar to what I've seen with moderator-removed posts #3535. It goes to two servers, but no more.

**Comment by WayneSheppard** [comment]
I made a new comment, on a post hosted at lemmy.ml
https://lemm.ee/comment/1099147

I verified that it federated out to the community server and four other subscribed servers.  I then edited the comment, and again verified the edit was federated out to four subscribed servers.  I then deleted the comment.  The comment was deleted on my server, and the community server.  But none of the subscribed servers deleted the post.

My comment on my home server (now deleted): https://lemm.ee/comment/1099147
My comment on the community server (now deleted): https://lemmy.ml/comment/1570775
My comment on the four subscribed servers is still there:
https://lemmy.world/comment/1259376
https://sh.itjust.works/comment/1045913
https://lemmy.zip/comment/843702
https://lemmy.run/comment/278178

**Comment by RocketDerp** [comment]
We could create a more descriptive new issue,but we already have two going, so I don't mind mixing them together. The key thing here is that EDIT of POST or EDIT of COMMENT seems to work fine across all servers. Where DELETE of Post, (Mod) REMOVE of Post, DELETE of Comment, and possibly??? (Mod) REMOVE of Comment are not consistent between severs.

Since the logging for this comment delete downstream subscriber needs be done on the "community home", let's use community: https://bulletintree.com/c/lemmy_testing0000 - which I run. I'll crank back on all the custom logging I added to the lemmy_server Rust code and figure out what paths are happening.

**Comment by RocketDerp** [comment]
Someone else confirmed the problem in production by making a post on Lemmy about the topic: https://lemmy.ml/post/2066009

**Comment by RocketDerp** [comment]
Anyone confirm if 0.18.3 fixed this?
