### ISSUE TITLE
Once tls_enabled: is set to false. After setting to true it still returns false behaviors. 

### ISSUE THREAD

**Issue by airjer** [LemmyNet/lemmy#3589]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Accidentally launched my instance with tls_enabled set to false. Discovered this, set it to true, and redeployed. It still returns http:// formatted urls within posts. Among having none of the comments from my instance sync anywhere and /c/ links fail. 

### Steps to Reproduce

1. Launch an instance with tls_enabled: false
2. Set to true and redeploy. 
3. Notice all of the same issues. 

### Technical Details

Ubuntu 20.04.6
The server returned this error: couldnt_find_community when using /c/ links

### Version

BE 0.18.2

### Lemmy Instance URL

lemmyf.uk

**Comment by Nutomic** [comment]
Post urls get stored in the database. If you set tls_enabled wrongly, you have to change urls in the db or wipe the db and set it up again.
