### ISSUE TITLE
Expandable Menu with Star Ratings for Content Evaluation

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3590]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

**Is your proposal related to a problem?**

Currently, Lemmy uses an upvote/downvote system for ranking content, which often leads to users treating it as a like/dislike mechanism rather than evaluating the relevance of the content. This can result in content being ranked based on popularity rather than quality or relevance.

**Describe the solution you'd like.**

I propose an expandable menu for each post or comment that includes star ratings for various criteria, such as:

- Irrelevant-Relevant
- Dislike-Like
- Low Quality-High Quality
- Unhelpful-Helpful
- Ordinary-Creative
- Serious-Humorous
- Rude-Polite
- Violent-Harmless

The results of these ratings would not be displayed until after the votes are cast, and users could fill in any number of them. This would allow content to be ranked based on a more comprehensive evaluation, rather than just its popularity.

Identification of malicious or biased users: By flagging users who consistently vote far from the consensus, the feature may help identify users who are intentionally manipulating the ranking system or exhibiting biased behavior.

It would make for a more interesting [Stats Page for Voting Affinity and Engagement Analysis](https://github.com/LemmyNet/lemmy-ui/issues/1389).

This idea is inspired by the [Likes/Dislikes](https://github.com/LemmyNet/lemmy-ui/issues/1873) issue on GitHub and [OpenAssistant](https://open-assistant.io).

**Additional context**

Implementing this feature could significantly improve the content ranking system on Lemmy, making it more comprehensive and accurate. However, it could also complicate the ranking system, and I don't know whether the payoff would be worth the added complexity.

**Comment by lionirdeadman** [comment]
I don't think it is possible to make comprehensive sorting algorithms with and it would likely overwhelm tons of people - I can't imagine how this would even look under a comment. I'm sorry, closing
