### ISSUE TITLE
Block incoming posts/comments for removed federated communities

### ISSUE THREAD

**Issue by redserk** [LemmyNet/lemmy#3594]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When a federated community is removed from an instance, the federated community seems to still receive posts and comments. I'd like to see a feature to prevent new posts and comments from federating to my instance.

I'm worried if I remove a community due to content concerns or legal reasons, the instance will still be storing (and technically hosting) the content I wanted to remove.

### Describe the solution you'd like.

When a federated community is removed, either:
1. Allow an admin to forcibly unsubscribe users so the federated instance will no longer push updates
2. Have an option on the community to ignore federated activity

### Describe alternatives you've considered.

N/A

I've tried to take a very quick glance at the code and did not see any existing mechanisms. The only potential mechanism that seems to exist would be to defederate from the instance hosting the community but that is not ideal if most of the other instance has communities that are fine.

**Comment by pallebone** [comment]
Also having this issue regards CSAM on a community and being unable to prevent new posts federating. Consider this a serious problem and serious bug.

**Comment by Nutomic** [comment]
I tested this just now. If you remove a remote community on your local instance, the posts definitely dont federate. If you still have this problem please open a new issue with exact steps to reproduce.
