### ISSUE TITLE
Question: What is the purpose/meaning/workflow of the `release/v0.18` branch?

### ISSUE THREAD

**Issue by necropola** [LemmyNet/lemmy#3602]
### Question

- It appears to be existing since version `0.18.1` which has been tagged in `main`
- Version `0.18.2` has been tagged in branch `release/v0.18`
- `RELEASES.md` in `main` has been updated to version `0.18.1`
- `RELEASES.md` in `release/v0.18` is still at version `0.17.2`
- `releases/v0.18` is 7 commits ahead of `main` most of which have matching commits in `main` (just with different hashes). Are these independant commits or does it look like this, if they have been merged from `main` to `release/v0.18` or vice versa, too?
- Is `releases/v0.18` just a temporary branch which essentially died when version `0.18.2` got released or is it meant to stay and tag all version `0.18.x` releases? 

I'm confused.

**Comment by alexandrupero** [comment]
I'm also confused by this, the difference is bigger now:

This branch is 32 commits ahead of, 46 commits behind main.

did main and the v0.18 branch diverge and meant to stay that way, or why is it not merged back? Hard to tell which branch to keep track of

**Comment by necropola** [comment]
It looks like the same changes are indepently being applied to both branches instead of being merged from one branch to the other.

**Comment by RocketDerp** [comment]
I raised this issue in the Matrix Chat weeks ago when I commented here, but nobody seemed to care

**Comment by alexandrupero** [comment]
> https://github.com/LemmyNet/lemmy/blob/main/Cargo.toml still has everything tagged as 0.18.1 - even though we are well past 0.18.2 - and I am building from source code to test the latest updates - and my server is identifying itself as a variation of 0.18.1

The cargo package versions seem to be lagging way behind indeed (are the commits updating them not applied?). But the reason your server is identifying itself as 0.18.1 is probably that the latest tag in the main branch is 0.18.1-rc.10 and the version is set by the latest tag in the branch (+ commit hash) [in the dockerfile](https://github.com/LemmyNet/lemmy/blob/102124b6d29edd7d799ee12a6f6df05dbbbf4f6c/docker/Dockerfile#L18C57-L18C57) - and while the latest commits seem to have been applied, the tags are missing

**Comment by RocketDerp** [comment]
Seems like 0.18.3 is being made with the non-main branch?

![image](https://github.com/LemmyNet/lemmy/assets/113625597/9ae2a928-66c4-4546-a782-ab55a0598299)

**Comment by necropola** [comment]
That was to be expected, since it was done similarly with the 0.17.x (and earlier) releases. What I still don't get is, why `main` and the current release branch `release/v0.18` appear to be diverging although they are actually not.

@dessalines Can you shed some light on what the branch strategy is for this project or rather point us to some documentation? Thanks.

**Comment by dessalines** [comment]
https://www.bitsnbites.eu/a-stable-mainline-branching-model-for-git/

**Comment by RocketDerp** [comment]
Thank you for answering. If anyone is able to describe in human language what they see as significant differences between main and 0.18.3 release, please share. Have a good weekend. It's been a fascinating journey to see issue #2910 be addressed.

**Comment by necropola** [comment]
Then it seems that I do not understand **stable mainline**, i. e. I would expect to only see tiny release specific fixes in the release branch and a few cherry-picked fixes which also go into main., since the goal of the release branch is to **freeze** the code before releasing it.

But what I'm seeing is a release branch and main branch running concurrently for quite some time wiith both getting pretty much all changes applied (independently from each other).

**Comment by dessalines** [comment]
> I would expect to only see tiny release specific fixes in the release branch and a few cherry-picked fixes which also go into main., since the goal of the release branch is to freeze the code before releasing it.

That is exactly what's in the release branch, cherry picked fixes from main, with no breaking changes.

**Comment by RocketDerp** [comment]
ok, so does woodpecker run testing on this other branch too? Is it a best practice for developers to test against main and the /v0.18 release branches, because upgrade behavior...

**Comment by dessalines** [comment]
CI will run for any pushes to other branches, or PRs to any branch.
