### ISSUE TITLE
Over ActivityPub, don't show post comments as boosted

### ISSUE THREAD

**Issue by rafal06** [LemmyNet/lemmy#3603]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, post replies also appear as boosted, as well as posts, on Mastodon, which effectively floods the home timeline.

![image](https://github.com/LemmyNet/lemmy/assets/70489677/a8a53e22-cf35-4089-b8bb-f94be10a1e53)

### Describe the solution you'd like.

Show only posts as boosted, with comments shown as normal replies, visible after clicking the post.

### Describe alternatives you've considered.

I don't see any other solution

**Comment by h-2** [comment]
I was coming here to report the same thing!

I was pleasantly surprised that I can subscribe to a lemmy instance from Mastodon (even though I can't even subscribe to the local time timeline of another Mastodon instance). Cool stuff! BUT, I would also like to only see the initial posts of the threads and not every response as an individual post! Ideally, I would still see the replies when I click on a post, but I don't know if that's possible if no-one on my instance is following the replying user.
In any case, having all replies boosted is a bit too much and unfortunately ruins this feature a bit.

**Comment by h-2** [comment]
Also, it would be nice if the post delivered over ActivityPub included the image of a post. I also don't see why there needs to be a link to the post, since that is available through "Open Original Page", or not?

**Comment by lionirdeadman** [comment]
@h-2 Please make a separate issue for that

**Comment by h-2** [comment]
> @h-2 Please make a separate issue for that

Here is the new issue: https://github.com/LemmyNet/lemmy/issues/3683

**Comment by Nutomic** [comment]
You need to report this to the Mastodon devs.
