### ISSUE TITLE
Forum-Style Ranking System

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3604]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Problem
The current ranking system in Lemmy lacks a feature that functions exactly like a traditional forum. Although there are options for sorting posts by "Active" and "New Comments" the ranking system does not consider activity related to the initial post or editing of posts or comments. This limitation hinders the prioritization of recent activity and engagement on the platform.

### Proposed Solution
I propose adding a new ranking option in Lemmy that functions like a traditional forum. This ranking would take into account any activity related posts/comments, including editing, and prioritize them to the top. By considering all types of activity, this ranking system would provide a forum experience.

### Alternatives
An alternative approach could be to exclude editing from the ranking system, focusing only on new comments and the initial post. This would still prioritize recent activity and engagement, but without considering edits. Additionally, the possibility of implementing a "ghost bump" feature could be considered [^1]. This would allow users to bump posts without leaving a useless message behind saying "*deleted by creator*".

### Additionally
It would be beneficial to add a view to the frontend that shows both posts and comments at the same time. In combination with this feature, this would allow users to see all recent activity for small communities at a quick glance.

[^1]: [Instance configuration for bumping posts](https://github.com/LemmyNet/lemmy-ui/issues/843)

- [Lemmy Docs: Votes and ranking](https://join-lemmy.org/docs/users/03-votes-and-ranking.html#votes-and-ranking)

**Comment by domiriel** [comment]
Indeed, now that Lemmy is growing in number of posts, users, and communities, the current ranking/sorting methods are becoming woefully insufficient. Large communities tend to appear at the top of (and dominate) the feed, while smaller ones seldom appear, if at all. There are many active communities with just a few posts every week that “disappear” in this deluge.

This is generating a feedback loop whereby already large communities get more exposure and keep growing, while smaller ones remain small and may ultimately wither away. 

This is clearly a big problem that doesn’t bode well for the health of the platform and, I think, should be promptly addressed.

I wish to highlight this does not require user profiling or “an algorithm” in the pejorative sense of the word. A new sort order would most likely suffice, as proposed.

**Comment by Die4Ever** [comment]
yes I just noticed this on my own instance (running 0.18.3)

sorting by New: https://lemmy.mods4ever.com/?dataType=Post&listingType=Local&page=1&sort=New

![image](https://github.com/LemmyNet/lemmy/assets/30947252/e6d92e4f-c708-4ecd-9753-485843768659)

sorting by New Comments: https://lemmy.mods4ever.com/?dataType=Post&listingType=Local&page=1&sort=NewComments

![image](https://github.com/LemmyNet/lemmy/assets/30947252/2e9f1737-7bc0-429c-9a0f-d01b1bd811c4)

I definitely expected my brand new post to be on the top of "New Comments" like an old forum would do

**Comment by Die4Ever** [comment]
actually I just noticed a new bug, might file a separate issue for this unless I realize I'm just missing something

if I go directly to that community on that instance, I don't see the new post at all, is this a new bug in 0.18.3? or is it due to it having the same URL link as one of the other posts? (my releases page on Github)

https://lemmy.mods4ever.com/c/deus_ex_randomizer?dataType=Post&page=1&sort=New
