### ISSUE TITLE
Opt-in Verification authorities

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/lemmy#3609]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Lack of verification of profiles

### Describe the solution you'd like.

Pitch
A central body ran by the Lemmy non-profit that verifies users. Due to the de-centralised nature of Lemmy the recognition of this authority would be opt-in per user / per server and if opt'd-out a user would not see verification badges given by the non-profit. As well as that, all verifications should be shown on the website in a downloadable a dynamic CSV file showing what body / person is being verified under what account (usernames change, maybe a different ID). Also, there should be a feature that would allow other people to make their own verification bodies in which people can opt-in to with their own badges, you could hypothetically opt-in to different multiple authorities at once.

Motivation
Safety of users, prevention of misinformation, makes famous people more comfortable to join the platform

### Describe alternatives you've considered.

1)A single authority
2) community upvoting accounts

**Comment by lionirdeadman** [comment]
I don't think any org exists or has the money to take on this endeavour. It's also something generally (purposely) avoided by federated networks
