### ISSUE TITLE
Block instances user setting

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#3614]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

A way for a user to block an instance.

### Describe the solution you'd like.

Setting to block instances. There are settings to block users and communities.

### Describe alternatives you've considered.

None

### Additional context

Useful for users who want to block instances from showing up in the homepage feed or search, etc.

**Comment by Dekker3D** [comment]
One example: feddit.de is full of German stuff, and often shows up in the "all" feed. I like browsing that feed, but don't speak German, so I'd like being able to just ignore all of feddit.de. There's also exploding-heads, of course...
