### ISSUE TITLE
[Bug]: user_view.counts is incorrect

### ISSUE THREAD

**Issue by nick-delirium** [LemmyNet/lemmy#3615]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

For the past few days I noticed that localUser counts value returned from getSite and user endpoints fluctuates a lot, mostly returning wrong values. About few days ago it was only for few values inside counts, but now only post and comments count is right:
(comment_score should be 100+, post score should be 20+)

<img width="600" alt="image" src="https://github.com/LemmyNet/lemmy/assets/23126999/9a92e844-573a-4aca-8844-4b4376ad4146">

### Steps to Reproduce

1. call `https://lemmy.world/api/v3/user?username=delirium&sort=New&page=1&limit=20`
2. open user view -> counts -> observe numerical values
3. some of them are wrong :)

### Technical Details

BE: 0.18.2-1-g68276b2f9

lemmy.world instance

browser and os does not matter, issue is consistent.

### Version

BE: 0.18.2-1-g68276b2f9

### Lemmy Instance URL

lemmy.world

**Comment by Nutomic** [comment]
comment_score and post_score have been removed from the api so this can be considered resolved.
