### ISSUE TITLE
[Feature request] show if comment creator is a mod in comment community 

### ISSUE THREAD

**Issue by nick-delirium** [LemmyNet/lemmy#3616]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Right now its pretty frustrating to mark all community mods if you're opening a single post, for example (deep link from mobile app).

### Describe the solution you'd like.

ideally, return list of mods in community view or mark comment/post creator as a moderator in community (same as admin flag)

### Describe alternatives you've considered.

no alternatives considered as of now

**Comment by lionirdeadman** [comment]
I don't understand what you're trying to say - can you clarify? It sounds like you're talking about an app issue?
