### ISSUE TITLE
Subscribe to Instances

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [LemmyNet/lemmy#3621]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

A big part of the beauty of lemmy is discovering new communities. Sometimes, there are communities that appear on your feed that, while not subscribed to, are things you find interesting and would like to see in the future. 

However, the internet is an inherently toxic place. Showing a full fediverse feed shows subs and content to me that are not only things I would never find interesting, but are in fact things that generally reduce my overall viewing enjoyment. 

The beauty of the fediverse is that there are entire instances dedicated to specific topics that have a completely different feel than other instances. For example, there is a instance specific to star trek discussion. I can safely say that everything on that instance has the chance to be interesting and virtually nothing there would upset me.

### Describe the solution you'd like.

I would like the ability to subscribe to that specific instance. That is, any communities created on that instance will automatically be added to my feed with further effort on my part. If there are new communities created, They would also appear in my feed. If I should be able to do this with an arbitrary number of instances. 

For example, I subscribe to the star trek and android specific instances. All communities on that instance automatically appear on my feed. If a new community on that instance is created, it too appears on my feed.  

### Describe alternatives you've considered.

Alternatives that are currently in discussion

1) Community Grouping. We have a separate issue for creating grouped communities. This theoretically can be used by instance owners to create one huge community with the sum of all posts on there. I think this is rather cumbersome.

2) Instance blocklist. I believe this also is in the works. This would straight up prevent an instance from appearing in your feed (including all). The issue there is that there may be a rare occasion that you'd want to see the posts on all. 

3) Instance allowlist. Same issue in that it affects your "all" feed.

**Comment by dessalines** [comment]
Subscribing to every current and potential future community on an instance could explode the DB and federation activities unecessarily.

Adding a instance-specific filter is a much better way to handle this.
