### ISSUE TITLE
Rework "Hot" sorting to show posts from more varied communities

### ISSUE THREAD

**Issue by popcar2** [LemmyNet/lemmy#3622]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I've noticed that almost all of the posts on hot sorting are coming from the same two communities. This is really frustrating as it makes finding discussions and interesting communities very difficult to find in-between the hundreds of meme posts. See the screenshot below.

This gives the impression that Lemmy is a meme-first community, and makes finding more interesting content and text posts more difficult.

### Describe the solution you'd like.

Change the algorithm for Hot sorting to prefer showing a greater variety of communities to the user. I'm fairly sure Reddit has something similar so users don't keep seeing the same one popular community again and again. Maybe limiting the number of posts a particular community can have at a given page could be a good solution.

### Describe alternatives you've considered.

I've tried using other sorts but none of them were satisfactory. I wanted to find new popular posts. Top X often also showed tons of memes (this isn't a problem because it works fine as a sort by rating). Active sort often shows posts that are over a day old and not necessarily new.

The only way to find new popular posts is to either sift through pages on Hot or browse by New, which gets a little tiresome. Realistically the best solution is blocking meme communities, but I do occasionally like scrolling through them.

### Additional context

Pictured: "Hot" sort showing the same two communities again and again on the front page. This is the norm.
![image](https://github.com/LemmyNet/lemmy/assets/16920817/d7f053dd-f198-4aa4-ae8f-f61716139dea)

**Comment by domiriel** [comment]
I feel this problem everyday… similar (or at least related) issue here:

[https://github.com/LemmyNet/lemmy/issues/3604](https://github.com/LemmyNet/lemmy/issues/3604)

**Comment by maegul** [comment]
I think this PR is trying to address this, but more as an adjusted version of Top: https://github.com/LemmyNet/lemmy/pull/3378
