### ISSUE TITLE
Allow moderators to merge duplicate threads instead of banishing them into the null.

### ISSUE THREAD

**Issue by redog** [LemmyNet/lemmy#3624]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

No, just an annoyance 

### Describe the solution you'd like.

Instead of a disconnected nature of a deleted "forum" thread of conversations merge them with the peer(aka first post)

### Describe alternatives you've considered.

Post live in limbo for eternity

**Comment by M4rtineski** [comment]
I like the idea a lot. It will help in situations where there's a duplicate post and both of them get a lot of traction,

**Comment by lionirdeadman** [comment]
Can you rename this issue to "Allow moderators to merge duplicate threads"?

**Comment by dessalines** [comment]
Posts are unique to communities, that each have their own set of comments, moderators, rules, etc. This is a concious decision to ensure that communities can moderate and curate posts as they see fit. 

However, at the top of every post, if it has a common link, you should be able to see the cross-posts to other communities.
