### ISSUE TITLE
Booru-Style Image View, Search and Tagging by Users

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3626]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Lemmy currently lacks a feature that allows users to easily find, browse, and organize images using tags, similar to booru-style imageboards. One of the main reasons why I would like a booru-style image view in Lemmy is that I have often wanted to revisit some images but couldn't find them.

### Describe the solution you'd like.

Introduce a booru-style image view in Lemmy, where users can find images by tags and edit tags to improve the organization of content. This feature would allow users to search for images based on tags. Users should also be able to edit and add tags to images, contributing to the organization and categorization of content on the platform. The proposed solution includes the following components:

1. **Create an image view**: Introduce a new view that displays only images from all subscribed, local, and global communities. This view would present the images in a visually appealing and easy-to-browse manner, like when you are on an expanded image being able to move to the next one by pressing the arrow key. Maybe instead of only images, it could be all non-text posts or all visual content.

1. **Implement a global tag system**: Each instance of Lemmy could have a global list of allowed tags that are not limited to the flairs allowed by the moderators of each community.

1. **Allow users to edit and add tags**: Users should be able to edit and add tags to images, contributing to the organization and categorization of content on the platform. This would enable a more collaborative approach to content curation, similar to booru-style imageboards.

1. **Include exclude tags from the search**: Being able to search for multiple tags, or excluding tags by prefixing them with a minus sign, or even using a wildcard search, which allows users to enter a partial tag and match it against the available tags in the database.

1. **Reduce duplicate content**: To minimize duplicate content, there could be a hashing algorithm to check for duplicate images by comparing their hash values, and all the same images from different communities would just link to the same image. Boorus often have fewer duplicates than sites like Reddit and Lemmy since, due to the lack of a proper tagging system, people just repost the same images in multiple relevant communities.

1. **Create albums**: creating albums with different images. There could be private or public albums, all with public visibility but with the difference of who can modify the album, either the creator or everyone. Items in an album could be sorted to express an order in a story. This would be an expansion of the current saved functionality but allowing for multiple named lists of posts, each for its own topic.

### Describe alternatives you've considered.

An alternative could be expanding the proposed [flair system](https://github.com/LemmyNet/lemmy/issues/317) in Lemmy, but it seems very limited to each community and would need an expansion. The tags you see on sites like [Safebooru](https://safebooru.org/index.php?page=post&s=list) include thousands of different tags, including characters, creators, fandoms, etc. The flair system would be just a more moderated subset of the tagging system required for this feature.

### Additional context
A booru-style imageboard, often referred to as a "booru," is a type of internet forum that focuses on the posting of images, often alongside text and discussion. The name "booru" is derived from Danbooru, which was the first site of this type. Booru-style imageboards are characterized by their non-hierarchical semantic structure, where users can post content, add tags, annotations, translations, artist commentary, and comments.

Unlike traditional imageboards, such as 4chan, where images are posted in threads and may be deleted after a short period, booru-style imageboards are essentially tag-based image archives. This means that images remain in place indefinitely unless deleted by moderators. Booru-style imageboards are often centered around anime and related content, but they can also cover a wide range of topics.

Some examples of booru-style imageboards include [Safebooru](https://safebooru.org/index.php?page=post&s=list), Danbooru, Gelbooru, and Moebooru. These platforms allow users to browse, search, and share images related to various anime, manga, and video game franchises. Booru-style imageboards have gained popularity due to their unique curation process and the ability for users to contribute to the organization and categorization of content.

**Comment by lionirdeadman** [comment]
Tags are already covered by #317 so all this issue adds is a different UI afaict. So I'd recommend moving it to lemmy-ui.

**Comment by 8ullyMaguire** [comment]
The frontend would primarily consist of a grid view with images, which is not the main focus of this proposal.

**Comment by lionirdeadman** [comment]
Maybe I'm misunderstanding but the way I read this issue - each post contains a picture and the post has flairs and people can search/filter through them, is that not correct?

**Comment by 8ullyMaguire** [comment]
The flair system seems very limited to each community and would need an expansion, the tags you see on sites like [Safebooru](https://safebooru.org/index.php?page=post&s=list&tags=programming+) include thousands of different tags including characters. I think the flair system would be just a more moderated subset of the tagging system required for this feature.

1. **Create an image view**: Introduce a new view that displays only images from all subscribed, local, and global communities. This view would present the images in a visually appealing and easy-to-browse manner, like when your are on a expanded image being able to move to the next one by pressing the arrow key. Maybe instead of only images it could be all non-text posts, or all visual.

2. **Implement a global tag system**: Each instance of Lemmy could have a global list of allowed tags that are not limited to the tags allowed by the moderators of each community.

3. **Allow users to edit and add tags**: Users should be able to edit and add tags to images, contributing to the organization and categorization of content on the platform. This would enable a more collaborative approach to content curation, similar to booru-style imageboards.

4. **Include exclude tags from the search**: Being able to search for multiple tags, or excluding tags by prefixing them with a minus sign, or even using a wildcard search, which allows users to enter a partial tag and match it against the available tags in the database.

**Comment by M4rtineski** [comment]
Related:

#3240 

("Reverse image search for communities/instances/whole lemmy before posting to limit spam/reposts and save space on servers")

**Comment by lionirdeadman** [comment]
I think this outside the scope of Lemmy. This issue is asking for an entirely different type of software which is not based on communities or posts.

paging @dessalines @Nutomic

**Comment by Nutomic** [comment]
Yes this looks like it would require almost a complete rewrite of the software.

**Comment by 8ullyMaguire** [comment]
Related to [Advanced Search and Tag Filtering](https://github.com/LemmyNet/lemmy/issues/3788)
