### ISSUE TITLE
[Bug]: Users have no way to remove abusive messages from inbox without admin intervention

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#3629]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

If you receive an abusive DM there is no way to remove it from your inbox without admin help.

### Steps to Reproduce

Ideally a person would be able to delete all private messages in their inbox, regardless of whether they created them or not.

But if this is not possible, blocking the abuse account should hide all DMs from them.

Reproduction:

1. Person B send messages to person A
2. Person A block person B
3. See person B messages still show up in inbox of person A
4. Observe person A also has no way to delete person B's messages. Their stuck it person A's inbox forever unless an admin intervenes.

### Technical Details

N/A

### Version

0.18.2

**Comment by IonicRain** [comment]
I've added another feature request related to your bug report:

https://github.com/LemmyNet/lemmy/issues/3640

IMO, users should be able to block unsolicited PM or DM being received at all. This obviously also limits the problem of users not being able to delete a PM or DM.

**Comment by martinrath77** [comment]
I agree - This is urgent - I just discovered scat NFSW imagery in my inbox and have no way of removing it. Also at least on the instance, i'm on, it's seems not possible to report the message.

**Comment by dessalines** [comment]
You can report private messages to admins, and you can also block the user. Is this issue asking to delete / hide all private messages from them after the block?

**Comment by aeharding** [comment]
> Is this issue asking to delete / hide all private messages from them after the block?

Yes.

Ideally the user would also have the ability to delete/hide messages from other users *without* blocking as well (like most messaging apps). If you would like, I can make a separate request for that.

**Comment by dessalines** [comment]
Ya that would be a separate request. I'll only address hiding messages from blocked users with this one.

**Comment by aeharding** [comment]
> Ya that would be a separate request. I'll only address hiding messages from blocked users with this one.

Follow-up, did a search and looks like the feature to delete received private messages is already submitted in https://github.com/LemmyNet/lemmy/issues/3640 :)
