### ISSUE TITLE
New notification category for new posts in communities you moderate

### ISSUE THREAD

**Issue by jgeorgeson** [LemmyNet/lemmy#3631]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

As a moderator I need to know when there are new posts in the communities I moderate so I can fulfill my role. 

https://lemmy.world/post/1320681

### Describe the solution you'd like.

A new option in settings to receive a notification for every new post only in the communities I moderate. Current notifications for new posts 

### Describe alternatives you've considered.

Creating a second account subscribed only to the communities I moderate and enable new post notification on that account.

https://lemmy.world/comment/1323243

**Comment by M4rtineski** [comment]
Yess please! I'm acitvely moderating 20+ sublemmies and it's hard to keep track of the new posts. Especially when I post myself a lot on them so they easly get burried between my posts.

**Comment by Nutomic** [comment]
I think this is resolved by the new moderator view: https://github.com/LemmyNet/lemmy/pull/3176
