### ISSUE TITLE
Sort type which favors recent posts with active discussions

### ISSUE THREAD

**Issue by kolgza** [LemmyNet/lemmy#3635]
### Requirements

- [x] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When I open Lemmy as an average user, I want to see posts that:

- have active discussions
- are from within the last day
- are highly upvoted

However, the `Hot` sort type shows me extremely recent posts with few votes or comments, and `Active` mostly shows me posts that are between one and two days old.

### Describe the solution you'd like.

Create additional sort types:
- `Active Six Hours`
- `Active Twelve Hours`
- `Active Day`
- `Active Two Days`

With `Active Six Hours`, the latest comment time no longer updates after six hours past the post published time. With `Active Twelve Hours`, the latest comment time no longer updates past twelve hours after the post published time, and so on an so forth.

[`Active Two Days` would be the current default behavior of the `Active` sorting algorithm.](https://join-lemmy.org/docs/contributors/07-ranking-algo.html#lemmy)

### Describe alternatives you've considered.

- Set the default sorting algorithm to `Hot`
- Adjust the `Gravity` value until the average age of posts on the front page of lemmy.ml is twelve hours.

### Additional context

Posts on the topic:
- [YSK: Feel like you only see the same 2-day old content? At least on lemmy.world, you can change your homepage’s default sorting type & scope to “Hot” and “All”](https://lemmy.world/post/994692)
- [FYI sort by “Top Day” if you’re tired of seeing the same top posts from 2-3 days ago](https://lemmy.world/post/192630)

**Comment by dessalines** [comment]
I don't know if its a good idea to create a ton of additional ranks with different bump time limits. 

The `Top Day`, `Top 6 hours`, etc seem to fit all your criteria above, and they're likely to be active discussions.

I'll re-open if someone wants to work on this tho.
