### ISSUE TITLE
arm64 Docker builds

### ISSUE THREAD

**Issue by IngwiePhoenix** [LemmyNet/lemmy#3641]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I have just heared about the XSS volunerability and wanted to update my instance ASAP, but was left realizing that since 0.17.3, there has not been any new arm64 builds submitted to Docker Hub at all.

So just in case, I checked [the docs](https://join-lemmy.org/docs/administration/install_docker.html) to see if I might just be using the wrong containers, but no - all the ones I use.

### Describe the solution you'd like.

I would like to see arm64 builds return. Even if they are only found on `:latest`, that'd still be enough for me - I use Watchtower to autp-update my containers anyway.

### Describe alternatives you've considered.

Provide arm-tagged images like older versions (i.e. `0.17.3-arm64-linux`).

**Comment by lionirdeadman** [comment]
Actually, this is a duplicate of https://github.com/LemmyNet/lemmy/issues/3102
