### ISSUE TITLE
[Bug]: HTML content within the code block

### ISSUE THREAD

**Issue by melroy89** [LemmyNet/lemmy#3648]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Unwanted `<span>..</span>` HTML code is appearing in the `<pre>..</pre>` code blocks, which should not happen. Causing federation issues with other fediverse software, trying to parse the HTML.

Kbin example:

![image](https://github.com/LemmyNet/lemmy/assets/628926/9e2c83b4-5103-4c90-a1d5-928ab9beafdc)

Activity JSON response:

![image](https://github.com/LemmyNet/lemmy/assets/628926/671e7967-5e18-491c-a3dd-1aa162fc1c9c)

### Steps to Reproduce

1. Use the JSON header to retrieve the post in JSON format (used in AP). Example: `curl -i -X GET -H 'Accept: application/activity+json' https://lemmy.sdf.org/post/758086`

2. HTML content of the code block: `<pre style=\"background-color:#ffffff;\">\n<span style=\"color:#323232;\">  So, night shift workers of the world, what has your experience been like and how do you manage being present in your family life?\n</span></pre>`. 

3. There is a `span` tag inside the `pre` tag, which is now getting treated as HTML within a code block.. This is wrong and causes parsing issues. Please, remove the `span` from the federated output in case of code blocks.

### Technical Details

I suspect something is not going right with the conversion between markdown to HTML?

For some reason I do _not_ see this `span` tag on the Lemmy instance (when looking at the source-code of the loaded web page). So it only happens with the JSON output.

### Version

BE: 0.18.2

### Lemmy Instance URL

lemmy.sdf.org as example

**Comment by melroy89** [comment]
Here another example of this bug: https://kbin.melroy.org/m/linux@lemmy.ml/t/12631/Systemd-254-now-with-soft-reboot

**Comment by noughtmare** [comment]
Another example: https://kbin.social/m/haskell/t/511582/Defeating-Return-Type-Polymorphism#entry-comment-2765579

**Comment by Nutomic** [comment]
This seems to be intentional, its a [markdown plugin for syntax highlighting](https://github.com/markdown-it-rust/markdown-it/blob/master/src/plugins/extra/syntect.rs). Should we disable this?

**Comment by noughtmare** [comment]
Since posting my last comment, I've found out that having tags inside code blocks is the right way to do syntax highlighting. You can also do that here on github:

```
<pre><code><span>some code</span></code></pre>
```

Is rendered as:

<pre><code><span>some code</span></code></pre>

Unfortunately it seems github does strip the attributes of the spans, so I can't actually style it.

So I think the problem is over at Kbin's side which escapes the tags like so:

```
&lt;span style=&quot;color:#323232;&quot;&gt;
```

Kbin should not do that.

**Comment by melroy89** [comment]
> Should we disable this? For that we only need to remove the markdown-it feature `syntect`.

You can still have syntax highlighting on your frontend side. But I would remove the syntax highlighting code part from the html when federating yes. 

> Although allowing arbitrary HTML tags does not sound great for security.

Exactly why we escape this kind of content. Indeed. We don't want to inject html code from another remote server.

**Comment by noughtmare** [comment]
> Exactly why we escape this kind of content. Indeed. We don't want to inject html code from another remote server.

Escaping is not the right answer. The easiest alternative that doesn't dump escaped HTML tags on your users is just to strip all the tags. But ideally you should only strip tags that really are harmful, not things like spans with coloring attributes.

And presumably you already have infrastructure that does this, otherwise I'd also see the `<pre>` and `<code>` tags themselves, wouldn't I?

**Comment by melroy89** [comment]
We are now using markdown instead of the HTML.
