### ISSUE TITLE
[Bug]: Remote instance RSS returns "record not found"

### ISSUE THREAD

**Issue by ShinyDog2636** [LemmyNet/lemmy#3650]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When on the page of a user on a remote instance, the linked RSS feed returns "Record not found"

### Steps to Reproduce

1. Go to the page of a remote user, on a local instance (https://lemmy.world/u/dessalines@lemmy.ml)
2. Click the RSS button
3. The linked page returns "Record not found" (https://lemmy.world/feeds/u/dessalines@lemmy.ml.xml)

### Technical Details

For example, https://lemmy.world/u/dessalines@lemmy.ml links to https://lemmy.world/feeds/u/dessalines@lemmy.ml.xml and returns "Record not found"

The page of a local user correctly returns an RSS feed (https://lemmy.ml/u/dessalines links to https://lemmy.ml/feeds/u/dessalines.xml which returns an RSS record)

The RSS feed for a remote _community_ on a local instance returns the same "Record not found". (https://lemmy.world/feeds/c/fediverse@lemmy.ml.xml)

See lemmy-ui issue (https://github.com/LemmyNet/lemmy-ui/issues/1954) for a related user interface bug.

### Version

BE 0.18.2

### Lemmy Instance URL

lemmy.ml, lemmy.world, lemmy.ca, etc

**Comment by dessalines** [comment]
The UI issue is correct, there isn't any reason to serve RSS feeds of remote content. So the UI just needs to build that rss from the actor_id.
