### ISSUE TITLE
Include support for handling image limits in the API

### ISSUE THREAD

**Issue by mykdavies** [LemmyNet/lemmy#3655]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Some admins want to manage the amount of storage needed for image uploads and so have instituted limits on image sizes. Examples include lemmy.ee at 100kB (https://lemm.ee/post/25065) and beehaw.org at 4000x4000 (https://github.com/LemmyNet/lemmy/issues/3473#issuecomment-1620520547).

There does not seem to be a way to set, enforce or expose these rules via the API, so these appear to be implemented in NGINX, giving a 413 Payload Too Large error in the case of lemm.ee.

As a result, when a client app is attempting to upload an offending image, all it can currently tell the user is that the image is somehow too large and that they must find out for themself what the rules are.

### Describe the solution you'd like.

The ideal would be that the instance handles the required resizing for the user.

If this is not seen as an attractive approach, it would then be extremely helpful for client apps if this information could be exposed via the API, so that they could query this information before attempting an upload and automatically handle the resizing to the instance's requirements on the user's behalf. 

My initial inclination is that the bounding-box limit would generally be easier for developers to work with.

### Describe alternatives you've considered.

The lemm.ee link above suggests that users should use other image hosts if their files are too large, but this is not an attractive option for app developers or end users, as if either requires the developers to make a choice of third-party host on behalf of their users (which some will doubtless have reasons for disliking) or it requires the users to make choices or take actions which they may not understand. Most users in most cases would rather just see their images resized, perhaps with a note in the app to inform them that this had happened in case they wanted to deal with this differently.

**Comment by ruffsl** [comment]
> I'd imagine that ongoing storage costs and bandwidth costs due to federation of the content would generally far outweigh any one-off uploading/re-encoding costs (but I have no knowledge here so I may be totally wrong).

Up until recently, before the DB optimizations and removal of web sockets, many admins had to upgrade their VPS hosting plans for more CPU cores and GBs of RAM just to handle modest levels of user traffic. These VPS plans are often rather course, in that bumping up a particular deficient resource, one has to upgrade wholesale to an entire larger tier, E.g. if I only needed to upgrade from one to two cores to account for added CPU load, then I'd often need to pay for 2xRAM, 2xDisk, and 2xBandwidth that may as well go underutilized and overcharged. With such optimizations now landing in Lemmy, admins can finally scale down their VPS costs for more sustainable growth.

- https://programming.dev/comment/157610
- https://programming.dev/comment/317806

![image](https://github.com/LemmyNet/lemmy/assets/2293573/44c10914-5943-431f-bde1-cbecbc827d44)

So, I think it would be a shame to lose all those hard earned overhead performance improvements - in the Lemmy back end - to something as client capable and distributable as media upload-compression. In my opinion, I think allocating limited VPS resources to serve more users instead, with a faster back-end experience, would be better than server side transcoding. Having servers federate the overhead in using the network with clients, just as instances federate the overhead in serving users across the network, could help with maintaining more sustainable operation costs as we continue to scale.

---

> This would be a great opportunity to move towards making that a standard for Lemmy (assuming that it's generally considered a Free enough standard).

It looks like pict-rs can be configured via options to enforce that uploaded media is transcoded to the provided format:
```
      --media-max-width <MEDIA_MAX_WIDTH>
          The maximum width, in pixels, for uploaded media
      --media-max-height <MEDIA_MAX_HEIGHT>
          The maximum height, in pixels, for uploaded media
      --media-max-area <MEDIA_MAX_AREA>
          The maximum area, in pixels, for uploaded media
      --media-max-file-size <MEDIA_MAX_FILE_SIZE>
          The maximum size, in megabytes, for uploaded media
      --media-max-frame-count <MEDIA_MAX_FRAME_COUNT>
          The maximum number of frames allowed for uploaded GIF and MP4s
      --media-enable-silent-video <MEDIA_ENABLE_SILENT_VIDEO>
          Whether to enable GIF and silent video uploads [possible values: true, false]
      --media-enable-full-video <MEDIA_ENABLE_FULL_VIDEO>
          Whether to enable full video uploads [possible values: true, false]
      --media-video-codec <MEDIA_VIDEO_CODEC>
          Enforce a specific video codec for uploaded videos [possible values: h264, h265, av1, vp8, vp9]
      --media-audio-codec <MEDIA_AUDIO_CODEC>
          Enforce a specific audio codec for uploaded videos [possible values: aac, opus, vorbis]
      --media-filters <MEDIA_FILTERS>
          Which media filters should be enabled on the `process` endpoint
      --media-format <MEDIA_FORMAT>
          Enforce uploaded media is transcoded to the provided format [possible values: avif, jpeg, jxl, png, webp]
```
- https://git.asonix.dog/asonix/pict-rs.git

Perhaps Lemmy could surface this, and other such upload restrictions configured in pict-rs, in a back end agnostic manner?
