### ISSUE TITLE
"Pay it forward" Gifting

### ISSUE THREAD

**Issue by domportera** [LemmyNet/lemmy#3658]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Just a lack of the ability to show silent appreciation

### Describe the solution you'd like.

Lemmy is not a commercial project, nor should it be. Gifts as designed by other social media are a toxic money dump that prey on users' good will. Gifts to other users should not be "purchased" from some central authority (though a case could be made that server maintainers could be the distributors of gifts, and at that point it's up to them?).

I think theres a much more wholesome way to actually have a "gift economy" - if a post or comment of mine receives a "gift" from someone, that gift goes into my inventory. The only use for that gift in my inventory is to gift it to another post.

### Describe alternatives you've considered.

more or less mused upon below

### Additional context

 I think this can create a positive feedback loop where users can show their appreciation to each other and feel motivated to do so

But there are a couple of issues:	
-  Where do gifts come from? Does every user just have one of each by default? Do servers distribute them based on their own rules? Are they earned via engagement?
    - If servers determine this, this could help differentiate communities from one another, but also increase "choice paralysis" when choosing a server.
        - This could also allow servers to opt out of gifting entirely if they choose to keep things simpler
-  What of people who don't give back? They become gift leeches and all the gifts from the community disappear into black holes.
    - Auto-regen periods defined by the server? I.e. after one week, if a user has no "thank you" gift, they will be granted one in their inventory
- What would the gifts be, and who decides?
    - Do servers decide? Does lemmy only support certain gifts? If servers decide, how do we limit or support gifting between users of X server on posts of Y servers?

**Comment by lionirdeadman** [comment]
This reminds me a bit of [exemplary tags](https://docs.tildes.net/instructions/commenting-on-tildes) from Tildes though in that case, the gift is linked to the comment.

**Comment by pboling** [comment]
- Gifts could be generated by activity milestones, e.g. 1000th comment
- Gifts could be like "badges" in other systems (e.g. github)
- Gifts could be "named" at time of giving, so they are unique and contextual
- Gifts could be private by default, and individually shown if the recipient so chooses
- Gifts could be copy-on-write, so each recipient gets a gift to give away when they receive one

**Comment by Nutomic** [comment]
What gxtu said.
