### ISSUE TITLE
[Bug]: Pagination with "Show Read Posts" disabled leads to skipped pages of content

### ISSUE THREAD

**Issue by tj111** [LemmyNet/lemmy#3659]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

If you browse with show read posts enabled, and read every post on page 1 of content, when you navigate to page 2, it will show you page 2 of "unread" content, and you need to go back to page one.

### Steps to Reproduce

1.  Disable "Show Read Posts"
2. Browse a community 
  - I suggest a community with consistent content but a relatively static sort - e.g. !spaceporn@lemmy.fmhy.ml w/TopMonth
3. "Read" each post on the 1st page (e.g. upvote all of them)
   - Pay attention to top couple of posts on page
   - Notice vote counts at bottom of page
5. Browse to Page 2
   - Notice large drop in post vote count between end of page 1 and page 2
   - Pay attention to top couple of posts on page
6. Browse back to page 1
   - Notice vote counts at top of page and bottom of page aligns between the end of the original page 1 and the viewed page "2"
   - Notice Page 1 content is different from original page 1 content

### Technical Details

I believe this is a pagination issue when constructing the offsets used for pagination, there may need to be a mechanism to deduct or track the state of read posts.

### Version

BE: 18.

### Lemmy Instance URL

lemmy.fmhy.ml

**Comment by M4rtineski** [comment]
I'm not sure if I understand your post properly but this may be related to this issue: #3547 ("Cache existing post order when loading next page.").

**Comment by Nutomic** [comment]
Should be fixed by https://github.com/LemmyNet/lemmy/pull/3872
