### ISSUE TITLE
[Bug]: BE timesout when creating a new comment or post, or upvoting an item

### ISSUE THREAD

**Issue by Security-Chief-Odo** [LemmyNet/lemmy#3660]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Users attempting to make a new comment or post, or upvote existing items, will get a loading spinner and no indication of the event occurring.  However upon refreshing the page the action was completed successfully. This is causing a lot of duplicates across the instance and frustration for users. 

### Steps to Reproduce

1. Visit https://beehaw.org while logged in
2. Go to a post and make a comment, click `reply` watch it spin with no indication it was successful
3. Refresh the page and see the comment went through successfully

[Example](https://postimg.cc/629XVDdG)

In this image at the start, I upvote a post waiting a few seconds for the UI to update, then refresh the page (F5). We see it go from spinning icon to blue upvote. After that, I unvote it doing the same thing and refresh the page. Lastly, I go to the command line and issue a command to the API to upvote that post, and refresh the page showing that the API did interact successfully. _(see tech details for steps)_

### Technical Details

Lemmy Software:

```
lemmy#
0.18.1
e9e76549a (origin/main, origin/HEAD) Split activity table into sent and received parts (fixes #3103) (#3583)

lemmy-ui#
0.18.2-rc.1
9c489680 (origin/main, origin/HEAD) Fix base.output (see #1911) (#1943)
```

* Enter your docker lemmy container `docker exec -it lemmy-lemmy-1 sh`
* `apk add curl`
* Confirm API is accessible `curl -m10 -s -o /dev/null -w "%{http_code}\n" 'http://localhost:8536/api/v3/site'` _(Can't use `curl -I` because that sends a HEAD request that lemmy responds with a `HTTP/1.1 404 Not Found` for it)_
  * Returns a 200, means the HTTP server is up and responding to `/api` endpoints
* run `curl -m10 -v 'http://localhost:8536/api/v3/post/like' -X POST -H 'content-type: application/json' --data-raw '{"post_id":<post ID>, "score":1,"auth":"<your auth>"}'`
* Get the following:

```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8536...
* Connected to localhost (127.0.0.1) port 8536 (#0)
> POST /api/v3/post/like HTTP/1.1
> Host: localhost:8536
> User-Agent: curl/8.1.2
> Accept: */*
> content-type: application/json
> Content-Length: 183
> 
* Operation timed out after 10000 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
```

That is the POST on Lemmy docker command line, fails to get any response after 10 seconds. Refreshing the page you made the upvote on, in your browser, will **show the above command did work**.

### Version

0.18.1 (GIT HEAD)

### Lemmy Instance URL

https://beehaw.org

**Comment by Nutomic** [comment]
Sounds like the instance is overloaded. Thats something for the admins to sort out, not a software bug.

**Comment by gaywallet** [comment]
Hey @Nutomic odo is an admin on beehaw.org and quite skilled in ops. We would appreciate it if you re-open this issue 😊

**Comment by Nutomic** [comment]
Okay didnt know that. Whats the server load when this is happening? Does a restart help?

Btw we have a private matrix chat for admins and devs to improve performance. I can invite you there if you send me your Matrix ID.

**Comment by Security-Chief-Odo** [comment]
@Nutomic thank you. Right now I'm trying to prove the bug again on a rebuild of beehaw backup. We moved the prod site to 0.18.2 release and not the git head status that the above was occurring on.  My current issue with trying to get `e9e76549a` built and ran is an error stating

```
lemmy_db_schema::utils: Running Database migrations (This may take a long time)...
thread 'main' panicked at 'Couldn't run DB Migrations: Failed to run 2023-07-08-101154_fix_soft_delete_aggregates with: syntax error at or near "trigger"', crates/db_schema/src/utils.rs:316:25
```
Deleting that folder entirely, lets the cargo build/run complete, but then it's not the same code that's the git commit and I want to avoid doing that.

**Comment by Nutomic** [comment]
Could be that your postgres version is too old? Havent heard about that error before.

**Comment by Security-Chief-Odo** [comment]
Hmm you're probably right, I'll upgrade it and try again. Thanks

**Comment by RocketDerp** [comment]
Follow-up on this. Issue #2910 and other PostgreSQL TRIGGER logic was hammering typically 1500 rows with writes on site_aggregates for every single local comment and post to do +1 on INSERT. I am still testing the newly release 0.18.3, but I believe the PostgreSQL TRIGGER and/or site_aggregates table content have been addressed where it isn't writing 1500 rows.. I suggest closing this issue and re-open with post 0.18.3 specific behaviors. Thank you and have a good weekend, love to all.

**Comment by Security-Chief-Odo** [comment]
Closing as I cannot reproduce this error on the provided git commit, or commits afterward.
