### ISSUE TITLE
Move env vars like `LEMMY_CORS_ORIGIN` into config

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#3665]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Lemmy now has a lot of env vars like `LEMMY_CORS_ORIGIN` scattered over its codebase. These need to be moved / consolidated into the `config.hjson`, in addition to working with their env vars.

### Steps to Reproduce

See above

### Technical Details

N/A

### Version

main

### Lemmy Instance URL

main

**Comment by Nutomic** [comment]
Or at least move all env vars into a single file so they are easy to find.

**Comment by googleben** [comment]
[The config crate](https://docs.rs/config/latest/config/) plus [lazy_static](https://docs.rs/lazy_static/latest/lazy_static/)/[once_cell](https://doc.rust-lang.org/std/cell/struct.OnceCell.html) or similar is pretty much plug-and-play. A custom solution for the config struct specifically should be pretty easy too if the config crate is undesirable. This+consolidation into e.g. `lemmy_utils::config` sounds like a good option to me.

**Comment by Nutomic** [comment]
That would likely require switching to a different config format which is supported by that crate ([listed here](https://docs.rs/config/latest/config/enum.FileFormat.html)). Personally Im not against that, hjson is very niche while toml for example is much better supported and more mature in general. It would require a breaking change though.

**Comment by googleben** [comment]
Could also impl [Format](https://docs.rs/config/latest/config/trait.Format.html) for hjson, either as a stopgap until a future breaking change or to just keep using hjson. In any case, there's plenty of options for how to proceed.
