### ISSUE TITLE
Remove the admin language setting

### ISSUE THREAD

**Issue by SorteKanin** [LemmyNet/lemmy#3669]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The admin language setting is confusing and unnecessarily limits what users of an instance can see.

### Describe the solution you'd like.

It should be removed and users should just choose what languages they want themselves.

### Describe alternatives you've considered.

Getting rid of the entire language system may also be an option, but some have concerns that their feed would be flooded by stuff they can't read.

**Comment by Nutomic** [comment]
Sounds identical to https://github.com/LemmyNet/lemmy-ui/issues/1971
