### ISSUE TITLE
Posts sent over ActivityPub should contain the content (picture and text) and not a link

### ISSUE THREAD

**Issue by h-2** [LemmyNet/lemmy#3683]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

This is what a lemmy post on Mastodon looks like:

![image](https://github.com/LemmyNet/lemmy/assets/2996863/fc7e934e-ee6f-48cd-84ca-c798b0f40aef)

And this is what the post on Lemmy looks like:

![image](https://github.com/LemmyNet/lemmy/assets/2996863/e2efb27c-7474-4073-95cf-835d046540a9)

### Describe the solution you'd like.

I'd like the post on Mastodon to look like the post on Lemmy, i.e. it should contain the picture and the additional text.

It should not contain a link to the Lemmy post, because this is available already by going to "…" → "Open Original Page".

### Describe alternatives you've considered.

None

### Additional context

While it may seem like this proposal would reduce traffic to Lemmy instances (because of removing the explicit link), I think it is in the spirit of the Fediverse to share the actual content of a post and not a link to it.

I also think that improving inter-operability with Mastodon will strengthen Lemmy, because it means Lemmy content will be exposed to the large(r) Mastodon user base.

**Comment by h-2** [comment]
Btw, posts that flow from Kbin into Mastodon have full content (picture and text).

**Comment by Nutomic** [comment]
If it looks wrong on Mastodon, report it to the Mastodon devs. Lemmy does federate all the data.
