### ISSUE TITLE
[Bug]: Getting comment-reply notifications after blocking a community.

### ISSUE THREAD

**Issue by chloroken** [LemmyNet/lemmy#3684]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Per title.

### Steps to Reproduce

1. Make a comment in a community
2. Block that community
3. Wait until someone replies (or use an alt)
4. You will get notifications

### Technical Details

n/a

### Version

0.18.2

### Lemmy Instance URL

lemmy.world

**Comment by RocketDerp** [comment]
FYI: I'm trying to devise testing code for this issue in the official lemmy_server API tests
