### ISSUE TITLE
Make resolve_object not require auth

### ISSUE THREAD

**Issue by marsara9** [LemmyNet/lemmy#3685]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I'm working on a service that ultimately provides links to various posts, etc... The problem I'm running into is that in order to get the internal ID for a given post, in order to reconstruct the URL, I have to index nearly all of the posts on the target instance.

Ultimately I'm looking for a way to link to a given post on any instance. i.e. https://github.com/LemmyNet/lemmy/issues/3259 but I'm looking for alternative solutions to my problem. 

### Describe the solution you'd like.

As the above linked issue seems rather complex would it be possible to make resolve_object not require auth. 

### Describe alternatives you've considered.

1. I'm currently using /api/v3/post/list to grab every post on a server. This is incredibly slow and time intensive. 
2. I could explore a way to automatically create a user to get a way to login, but this seems rather problematic and ultimately a security concern.

**Comment by marsara9** [comment]
Alternative -- can an explicit endpoint be created to get the internal ID of a post from a posts ap_id?

As the current approach I'm taking requires that I make 1,000-10,000+ requests using `/api/v3/post/list?type_=All&sort=Old&limit=50&page=....`.  This currently takes hours or days to go through all of the posts on a given server. I then store those IDs in a database so that I don't have to do the lookup again.  I then periodically check the server again for new posts using the last page that I queried. 

In my testing I've found that passing All or Old significantly increases the amount of time required to get a response.  Using Local appears to be much more performant but this doesn't allow me to get the IDs of posts external to the current instance.  If I had a way to lookup a post, or recreate a post's URL from the ap_id, then I wouldn't need to spend days indexing the internal IDs of every post on every instance.

**Comment by RocketDerp** [comment]
> Alternative -- can an explicit endpoint be created to get the internal ID of a post from a posts ap_id?

To state the obvious: if your ap_id is for the server (no matter where you first discovered that ap_id), then the number is the internal. In other words, if it starts with https://lemmy.ml/ for a comment/post/etc, the number on the ind corresponds to the internal id that lemmy.ml knows it by.

your proposed endpoint would, in defense of denial-of-service, have to basically be a query of "do you know this ap_id", and return the localized id or say it is unknown. 

Uncertain speculation based on some experience testing: currently the code would go out and fetch the post or comment, and (I assume) invoke storage usage (and performance-concern http connect to a peer server). In particular, I'm not even certain about the storage of what I would consider "orphan" comments that you provide the ap_id for that have no associated community or post on the local server.  If anyone knows, please chime in: if you toss Lemmy a comment ap_id to resolve_object that it has no community, user, or post for, does it fetch and locally store all 4 elements (comment, user, post, community)?

**Comment by marsara9** [comment]
More context as to my current project: https://www.github.com/marsara9/lemmy-search

So ultimately I'm trying to build a service that can index the entire fediverse. I currently provide a drop-down that allows users to select their home instance. This then makes it so that any links that the user clicks on opens up in their home instance.

So what I'm aiming for is only having to index an instance's local posts and then use that data from say, Lemmy.world, to create a link to that same post on lemmy.ml.

At the moment in order to do this I have to find a way to lookup the internal ID on ~500 instances and then cross reference those based on the ap_id.

**Comment by RocketDerp** [comment]
> At the moment in order to do this I have to find a way to lookup the internal ID on ~500 instances and then cross reference those based on the ap_id.

I've played with similar code in lemmy_helper. My advice to you is that in the long-term, it's having the most recent content that reddit-like sites are often focused on.  So you are probably best to just use the bulk API that you have, the fetching of new comments and posts - and just go around polling the servers for their local of same every x minutes.

Right now, that is even problematic, as the API doesn't have a stable paging reference to get beyond 50, the page movies underneath your page change. in lemmy_helper, I try to fetch the pages of posting and comments as fast as possible before acting on the data.... there are open issues on paging stability https://github.com/LemmyNet/lemmy/issues/3547

**Comment by RocketDerp** [comment]
You also have another option for your app. Install lemmy_server yourself, establish as an instance, and subscribe to every server and community that you want. Then those servers will push to you your content in real-time. This would be the non-bulk approach.  You could query the underlying PostgreSQL data your own self form your own application.

**Comment by marsara9** [comment]
I'd still need a way to convert local.domain to lemmy.ml for a given post. One of the key features I want to provide is a built in Lemmy redirector. So that users from lemmy.ml, lemmy.world, beehaw, etc... can open the links in their home instance instead of having to install a separate script (which I believe doesn't work outside of Lemmy now due to the SameSite change?)

**Comment by marsara9** [comment]
> > At the moment in order to do this I have to find a way to lookup the internal ID on ~500 instances and then cross reference those based on the ap_id.
> 
> I've played with similar code in lemmy_helper. My advice to you is that in the long-term, it's having the most recent content that reddit-like sites are often focused on.  So you are probably best to just use the bulk API that you have, the fetching of new comments and posts - and just go around polling the servers **for their local** of same every x minutes.
> 
> Right now, that is even problematic, as the API doesn't have a stable paging reference to get beyond 50, the page moves underneath your page change. in lemmy_helper, I try to fetch the pages of posting and comments as fast as possible before acting on the data.... there are open issues on paging stability https://github.com/LemmyNet/lemmy/issues/3547

But thanks. Ya I currently poll every 6 hours or after the last crawler has finished, whichever is longer. Currently it's still taking around a week or more to get through all 500+ instances. But I'll keep an eye on this and the related issue I linked to see if there's any updates.

Eventually I'm hoping to add comment data to my index but I'm looking at the crawler taking months to complete with the current APIs.

**Comment by RocketDerp** [comment]
We need to recruit you so that rewrite other-lemmy link option is added to lemmy's native Rust app ;) I'd start out with an efficiently-concerned approach that does it only for known-content (users/comments/posts that it has locally).

**Comment by marsara9** [comment]
The major blocker there is: https://github.com/LemmyNet/lemmy/issues/1101

Once that issue is resolved it becomes trivial to redirect to any post on any instance.

In order to redirect even to known posts/comments there has to be some way to take a remoteID convert it to an ap_id and then convert that back to the internalID. If the remote and internal IDs are the same, this becomes a piece of cake.

I can eventually take a look into that but it's going to be a major database migration. Not to mention the problem of how to ensure that all old posts/comments end up with the same ID.  Alternatively, if one Lemmy instance could call resolve_object on a remote instance I could take a similar approach to what I described in my original post, but now we're back to the auth issue...

**Comment by RocketDerp** [comment]
> an ap_id and then convert that back to the internalID

lemmy_server federation is doing this constantly for incoming content. It queries the apn_id and returns the local id, it can do millions of those a second. For example, every single time a peer server comment comes in on a post, lemmy_server has to search for the post by apn_id to know which PostgreSQL record to update on comment count, etc.

It's the nature of lemmy_server that PostgreSQL has to have these in-RAM to be performant, as an end-user on any-other peer instance can go add new comments or votes to any-old post, even one from 4 years ago. Same with any user deleting/editing an old comment, etc.

**Comment by marsara9** [comment]
Can it do the other half though? Can lemmy.ml convert a remote ID to an ap_id?  i.e. given a post https://lemmy.world/post/1234 can it determine that it has an ap_id of https://lemmy.ml/post/2345 ?

Btw just making sure we're on the same page, you're looking for a way to have universal links on lemmy-ui for posts and comments?  Users and Communities already work or are you talking about something different?

**Comment by RocketDerp** [comment]
>  Can lemmy.ml convert a remote ID to an ap_id? i.e. given a post https://lemmy.world/post/1234 can it determine that it has an ap_id of https://lemmy.ml/post/2345 

I suspect you made up 1234 without looking at that actual link, because it is a beehaw ap_id posting on lemmy.world, so it is alien to both lemmy.ml and lemmy.world - is there any reason you need to convert to two alien servers? 1 server will be local, and 1300+ federated servers will have to convert to local. Converting between alien I can't imagine is a case that we are discussing?

Starting with a fresh example: https://lemmy.ml/post/2246419 is a localized post copy on lemmy.ml of a lemmy.world ap_id original post, notably: https://lemmy.world/post/1819374

> Can lemmy.ml convert a remote ID to an ap_id?

for **known content**, that it has already received for local subscribers, lemmy.ml can efficiently do this. It is already doing it for every single incoming comment from a remote federated instance. It has to look  up the ap_id of the posting (https://lemmy.world/post/1819374) and convert that to post.id 2246419 (localize it), and INSERT into PostgreSQL the new comment.

Again, it is unknown content, a link to comment or post that it does not have an ap_id for - that is the bigger performance problem. If it has a local copy, which I assume is your entire intention of the service you are providing, it can rapidly convert these links of post/comments to local links.

**Comment by marsara9** [comment]
Sounds good but ya for my service I'd have the ap_id of every post in the fediverse but need a way to find the local id, if any, for a given instance. 

In the meantime let me look over what you posted here in more detail and see what if anything I can do for my service and Lemmy itself.

**Comment by marsara9** [comment]
@RocketDerp this still doesn't resolve my main concern but I wanted to share... 

I'm now exposing an endpoint on my service that can take any (post, community or author) `actor_id` and a `home_instance` and it issues a `303 See Other` redirect to the URL that represents that actor on the requested `home_instance`.  This way, when someone clicks on a search result, I can take the user to their home instance instead of the instance that created the post.  I still don't have an efficient way to get the information required to do this lookup, but again wanted to share in-case this can be used for Lemmy itself.

https://github.com/marsara9/lemmy-search/blob/develop/server/src/api/search/mod.rs#L356

https://github.com/marsara9/lemmy-search/blob/develop/server/src/api/search/models/redirect.rs

Assuming testing on this goes well, I hope to make this endpoint live in the near future.

**Comment by RocketDerp** [comment]
Personally, which I have very little power in the product, adding some new client-facing API calls to dump out raw information from PostgreSQL that tells you ap_id = id for posts and comments shouldn't be a big deal. If the column counts are kept low (id, ap_id) - I could see allowing a LIMIT of 2500 or even higher (Reddit allows 500 comments to be fetched maximum on old reddit, for a sense of scale).

**Comment by marsara9** [comment]
Internally in lemmy, for this to work I just need something that can do a `ap_id -> internal-id` lookup.  But I'm guessing lemmy-ui uses the same public APIs as everyone else?

Externally for my project, that API would have to be public which /could/ expose a concern as you described above.  If @dessalines or someone who does have the ability to look this over can give a green light or some requirements / limitations, this shouldn't be hard to do.

**Comment by RocketDerp** [comment]
>  for this to work I just need something that can do a ap_id -> internal-id

Are you intending to store nothing on your site and always do a real-time access to the Lemmy instance? One link-click, one lookup? I assumed you would be caching your lookups in local storage of your system. 

I'm mostly talking about even going a step further, bulk pre-loading of the data you want before the user even clicks the link.

> that API would have to be public which /could/ expose a concern as you described above.

I see no reason these are secret, every /post/xxx /comment/xxx is exposing the internal id numbers. The major concern that I said in my first reply is unknown values. If you go to lemmy.world and ask for a lemmy.ca apn_id and it is unknown ot lemmy.ca, then currently resolve_object does a real-time live connect to lemmy.world to bring-in the data.  If you are fine with only getting responses to alrady-known data (in the PostgreSQL tables), I see no issue with recommending some API that doesn't require authentication.

**Comment by marsara9** [comment]
Sorry I keep getting distracted between the two conversations / asks.  But just staying on topic of my original ask...

> Are you intending to store nothing on your site and always do a real-time access to the Lemmy instance? One link-click, one lookup? I assumed you would be caching your lookups in local storage of your system.

> I'm mostly talking about even going a step further, bulk pre-loading of the data you want before the user even clicks the link.

I'm doing that today.  I'm trying to find an alternative as the current process I have is extremely time-intensive.  My goal with my project is to index essentially the entire Fediverse and then allow users to open links to posts that they find in their home instance, whatever that may be.  So lets just make some assumptions:
1) Assume that there's approximately half a million posts today
2) Assume that there's approximately 5k instances across the fediverse.

Currently today, I have a "crawler" that repeatedly calls `/api/v3/post/list?type_=All&sort=Old&limit=50&page=...` on a given instance capturing the ap_id and the internal Id of that post (along with the title, body, etc... so it can be searched).  Then in order to be able to support opening that post on their home_instance I currently have to do this for EVERY other instance out there.  As it stands this takes about ~8 seconds per query due to the current performance of these larger instances at the moment. (I haven't narrowed down the exact cause yet).

So that ends up coming to `0.5mil / 50 per query * 8 sec` or approximately 24 hours, per instance.  At 5,000 instances, assuming that they all the same size (they're not, but bare with me), I'm looking at approximately 13 YEARS, just to index every post across every instance.

If instead there was an API that could take a given `ap_id` and tell me what that instances internal-id was for that post, I'm back down to just 24 hours to index everything, which is relatively reasonable.

>> that API would have to be public which /could/ expose a concern as you described above.

> I see no reason these are secret, every /post/xxx /comment/xxx is exposing the internal id numbers. The major concern that I said in my first reply is unknown values. If you go to lemmy.world and ask for a lemmy.ca ap_id for a comment and it is an unknown to lemmy.ca, then currently resolve_object does a real-time live connect to lemmy.world to bring-in the data. If you are fine with only getting responses restricted to already-known data (in the PostgreSQL tables), I see no issue with recommending some API that doesn't require authentication. Right now you can fetch a comment or post without authentication and discard most of the data you fetch to just get ap_id = id values... again, for locally known content.

Ya for my project I would only be querying `lemmy.world`, asking it, "what is YOUR internal-id for this ap_id`?  If someone set their home-instance to `lemmy.ml` I would then query `lemmy.ml` instead.  

And sorry I think there was a mix-up before.  Was also trying to look into fixing the link issue on lemmy itself, which technically is off-topic here.

**Comment by RocketDerp** [comment]
And we are clear that I keep emphasizing unknown data behavior? By "unknown", It's entirely possible that a target server has no content to link to, no subscribers to a specific remote community. I don't think in the long-term every small-time instance will want the burden of storage and network I/O to hold copies of every major Lemmy community.

**Comment by marsara9** [comment]
Correct.  I would expect that if I query `some.obscure.server` for a post that I'll more than likely just get back a null.
