### ISSUE TITLE
Change Lemmy backend service to run as non-privileged user inside container

### ISSUE THREAD

**Issue by asimons04** [LemmyNet/lemmy#3687]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Lemmy runs as root inside the Docker container.  As far as I can tell, it doesn't require any escalated privileges necessitating `root`.  

While Docker does isolate the processes, it's always best practice to not run as root unless absolutely required to do so.

### Describe the solution you'd like.

Update the Dockerfile used to build the lemmy container to use a non-privileged user by adding the following between lines 38 and 40 in the existing [Dockerfile](https://github.com/LemmyNet/lemmy/blob/main/docker/Dockerfile):

```
RUN adduser -h /app -s sh -S -u 1000 lemmy
RUN chown -R lemmy /app
USER lemmy
```

This assumes a user id of 1000, which is typical, but can be anything.

The revised Dockerfile would be as such:

```
FROM clux/muslrust:1.70.0 as builder
WORKDIR /app
ARG CARGO_BUILD_TARGET=x86_64-unknown-linux-musl

# comma-seperated list of features to enable
ARG CARGO_BUILD_FEATURES=default

# This can be set to release using --build-arg
ARG RUST_RELEASE_MODE="debug"

COPY . .

# Build the project
    
# Debug mode build
RUN --mount=type=cache,target=/app/target \
    if [ "$RUST_RELEASE_MODE" = "debug" ] ; then \
      echo "pub const VERSION: &str = \"$(git describe --tag)\";" > "crates/utils/src/version.rs" \
      && cargo build --target ${CARGO_BUILD_TARGET} --features ${CARGO_BUILD_FEATURES} \
      && cp ./target/$CARGO_BUILD_TARGET/$RUST_RELEASE_MODE/lemmy_server /app/lemmy_server; \
    fi

# Release mode build
RUN \
    if [ "$RUST_RELEASE_MODE" = "release" ] ; then \
      echo "pub const VERSION: &str = \"$(git describe --tag)\";" > "crates/utils/src/version.rs" \
      && cargo build --target ${CARGO_BUILD_TARGET} --features ${CARGO_BUILD_FEATURES} --release \
      && cp ./target/$CARGO_BUILD_TARGET/$RUST_RELEASE_MODE/lemmy_server /app/lemmy_server; \
    fi

# The alpine runner
FROM alpine:3 as lemmy

# Install libpq for postgres
RUN apk add --no-cache libpq

# Copy resources
COPY --from=builder /app/lemmy_server /app/lemmy

# Create non-privileged user
RUN adduser -h /app -s sh -S -u 1000 lemmy
RUN chown -R lemmy /app
USER lemmy

CMD ["/app/lemmy"]
```

### Describe alternatives you've considered.

I currently build a custom Lemmy backend image based on the most recent release version:

```
FROM dessalines/lemmy:0.18.2
RUN adduser -h /app -s sh -S -u 1000 lemmy
RUN chown -R lemmy /app
USER lemmy
CMD /app/lemmy
```

**Comment by RocketDerp** [comment]
FYI on topic, lemmy-from-scratch does do this: https://github.com/LemmyNet/lemmy-docs/blob/b6a58b81bb66f7e5144be93b660bb82e917d7b58/src/administration/from_scratch.md?plain=1#L39

**Comment by Nutomic** [comment]
Can you make a pull request with that dockerfile?

**Comment by asimons04** [comment]
Done 
https://github.com/LemmyNet/lemmy/pull/3709
