### ISSUE TITLE
Please add blocked domain to "Domain is blocked" message

### ISSUE THREAD

**Issue by urda** [LemmyNet/lemmy#3698]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently Lemmy just logs a blog message: https://github.com/LemmyNet/lemmy/blob/102124b6d29edd7d799ee12a6f6df05dbbbf4f6c/crates/apub/src/lib.rs#L75

We should have the message include the blocked domain as well, so we don't have to match up HTTP request logs against Lemmy logs by hand. 

### Describe the solution you'd like.

Instead of just 

```rust
return Err("Domain is blocked");
```

Maybe something like

```rust
return Err("Domain is blocked (DOMAIN.NAME.TLD)");
```

### Describe alternatives you've considered.

If I can figure out `rust` in my free time I would have cut a PR already.

**Comment by urda** [comment]
I don't know my `rust` but maybe something like

```rust
format!("Domain is blocked ({})", &i.domain);
```

**Comment by urda** [comment]
I'm going to attempt to make some `rust` changes and have opened a PR to address my request in #3699

**Comment by urda** [comment]
Gave it a spin in PR but I do not have enough `rust` education to have been effective.

**Comment by Freakazoid182** [comment]
I've attempted to get you sorted. Not an experienced rust developer myself, so taking the opportunity to learn by contributing here. I will create a PR later today

**Comment by urda** [comment]
Wow! Thanks for helping and stepping up here.

**Comment by Freakazoid182** [comment]
> Wow! Thanks for helping and stepping up here.

All good 👍 The PR is merged! I think this can be closed now

**Comment by urda** [comment]
Closed by #3701

**Comment by urda** [comment]
There might be one minor issue on this, I think the logger / log type is being reported incorrectly as `Unknown`. Should this not say something like `DomainBlocked` from the rust logger so users can use it for searches?

```
2024-03-01T08:03:45.448035Z  WARN lemmy_server::root_span_builder: Unknown: Domain "EXAMPLE.com" is blocked
```

**Comment by Nutomic** [comment]
The error is passing through a library handler so I dont see any other way to handle it.

https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/lib.rs#L51

**Comment by Nutomic** [comment]
See https://github.com/LemmyNet/lemmy/issues/4369
