### ISSUE TITLE
Community Grouping with depth

### ISSUE THREAD

**Issue by web110010** [LemmyNet/lemmy#3700]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There are multiple communities with the same name, around same no of people. When going around to join one it can be incredibly confusing. Hunting out related communities can also be quite a chore.

I also don't want to join multiple communities with same name due to repeated posts as people cross post them, and this just sours the experience. While I was on reddit I would sometimes wish I could see posts from a sub-community of the sub reddit without needing to subscribe to it.

### Describe the solution you'd like.

My solution is similar to #3071, but I think it is different enough to merit a discussion as a feature request. (if not, just point me where to go).

What I propose is, have community admins/moderators, list out different levels of relations with different communities they think are related to theirs.
Example:

> depth level 0: No input, basically the community itself (This would be result in the current `Subscribed` tab)
> depth level 1: The same community in different instances.Example: c/linux@programming.dev and c/linux@lemmy.ml (I would like this to be the default Subscribed view)
> depth level 2: Related communities, which are directly a sub-group of the main community, Example would c/linux@lemmy.ml -> c/linuxmasterrace@feddit.de

> I think level 2 is enough for most communities, but some could use a depth level 3(distant but overlapping communities).
> An example of depth level 3 would be: `level 1:` c/gaming@beehaw.org and `level 3:` c/cosplay@lemmy.blahaj.zone, another could be  `level 1:` c/linuxmasterrace@feddit.de and `level 3:` c/linux@lemmy.ml 

This could probably be just a txt file or multple one per depth, which all the same communities are using for listing out the communities depending on relation.

Now depending on the depth level the user chooses for subscribed, display the posts from related communities, without the user being subscribed to all the communities being displayed. Also ensure that if your instance is blocking a community/instance the related community does not show.

### Describe alternatives you've considered.

I've read #3621 , #3071 , #3193 , #818

I also thought about the depth level control going to infinity, that is if depth level 2 is related communities, then depth level 3 would be whatever the level 0 community add there + depth level 2 of the communities of the depth level 2 communities and so on till infinity. I thought this would very-very easily and incredibly fast go out of hand, crushing multiple servers.

### Additional context

My example is just for understanding purposes and the community admin could just add whatever community the want at whatever depth level they feel like.

**Comment by dessalines** [comment]
Having a tree / hierarchy of communities is way outside scope for us. The best thing to do in the meantime is link related communities in the sidebar, like reddit does.

I'll re-open if someone wants to take it on tho.
