### ISSUE TITLE
[Bug]: Moderator shields do not federate to other instances

### ISSUE THREAD

**Issue by Gyrfalcon5** [LemmyNet/lemmy#3705]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When a moderator uses the "Speak as Moderator" feature to display their comment as a moderation action, this is visible to other users on the community home instance. However, when viewed from other instances, the distinguishing badge does not appear, making it unclear to federated users if the message constitutes formal moderation or not.

### Steps to Reproduce

1. Using a moderator account, make a comment in a community and highlight it using the "Speak as Moderator" feature
2. Navigate to the same comment via an instance which is federated with the original community. As far as I am aware, being logged in to the federated instance is not required.

### Technical Details

N/a

### Version

0.18.2 on both local and federated instance in question

### Lemmy Instance URL

beehaw.org

**Comment by RocketDerp** [comment]
I confirm this bug and have added testing code to reproduce it. https://github.com/LemmyNet/lemmy/pull/3745

**Comment by lionirdeadman** [comment]
This doesn't resolve it for admins and I don't think this resolves it for mods either as this bug happened with a mod that was correctly put in the other instance's moderator list.

**Comment by Nutomic** [comment]
Just tested it and its working fine in the latest version.

https://enterprise.lemmy.ml/post/417390
