### ISSUE TITLE
[Bug]: 2FA bypass using password reset

### ISSUE THREAD

**Issue by into-the-v0id** [LemmyNet/lemmy#3714]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Bug discovered by [@yesbutnobutyesbutno@sh.itjust.works](https://sh.itjust.works/u/yesbutnobutyesbutno) via https://lemmy.ml/post/2404075

If a user with 2FA enabled resets their password, they are automatically authenticated without 2FA challenge upon submitting the password reset form.

### Steps to Reproduce

1. register user
2. enable 2fa
3. logout
4. reset password

### Technical Details

no technical details

### Version

BE 0.18.1-47-g13a866aeb

**Comment by RocketDerp** [comment]
See also: https://github.com/LemmyNet/lemmy/issues/3309
