### ISSUE TITLE
Add option to follow remote instances

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#373]
We already have (unmerged) implementations for responding to webfinger and activitypub requests. The next step imo should be implementing a way for Lemmy to generate outgoing webfinger and activitypub requests. So what we need is basically an input that allows one instance to follow another.

My suggestion is to handle this at the instance level, meaning only admins can enable federation with new instances. This should let us avoid a lot of problems with spam, especially as we dont have proper mod tools yet.

Following a remote instance would include these steps:
1. fetch a list of all remote communities (https://github.com/dessalines/lemmy/blob/master/docs/api.md#list-communities)
2. fetch and store the activitypub profiles and posts of these remote communities
3. display this information on the local instance

Webfinger is probably not needed to communicate with other Lemmy instances, because we already know the correct URLs. We can tell by the nodeinfo endpoint if an instance is running Lemmy.

**Comment by Nutomic** [comment]
To fetch a list of remote communities, I need to be able to make calls to the websocket endpoint of remote Lemmy instances. Any suggestion what would be the best way to do that, eg with a particular websocket library? Or would it be an option to expose the API over HTTP as well?

**Comment by Nutomic** [comment]
We also have to think about how to store remote objects in the database. According to [this post](https://blog.soykaf.com/post/activity-pub-in-pleroma/), Pleroma stores the json directly in postgres using the jsonb type. That sounds useful, but I couldnt figure out from their source code how it works exactly. Maybe someone needs to spin up a Pleroma instance to check the database scheme.

**Comment by dessalines** [comment]
> Or would it be an option to expose the API over HTTP as well?

Ya, I was thinking that we'd need to make a good amount of http endpoints for server-to-server comms, whereas the websocket would be mostly for server-to-client.

As far as the DB stuff, for the most part if possible, I'd like to do these by server-to-server fetches, that way we don't have to deal with *caches* or the same data stored in different places, and potentially being different. It might be unavoidable for some things tho, like federated communities and federated users having some kind of identifier that doesn't change, kind of like how mastodon has `/account/id`.
