### ISSUE TITLE
Blur NSFW: Make it a per-account setting

### ISSUE THREAD

**Issue by MetalZealot** [LemmyNet/lemmy#3744]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Many iOS/ Android Lemmy apps implement an option to blue NSFW content, but most do not make it a per-account setting. This makes it so you have change the blur setting within the app manually every time you want to switch to an alt account meant for viewing NSFW content.

### Describe the solution you'd like.

Add a checkbox for "Blur NSFW Content" underneath the "Show NSFW Content" line within the Account Settings page.

### Describe alternatives you've considered.

as far as I've seen, there are no userscripts that implement a Blur NSFW toggle (never mind an account-specific one) for desktop, and most apps do not offer a simple enough on/off toggle for this feature.

**Comment by dessalines** [comment]
Fixed by #3377
