### ISSUE TITLE
[Bug]: Lemmy 0.18.3 release munges "&" to "&amp;" in post titles and in code blocks of comments, example of YouTube link

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3754]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

This posting on lemmy.ml, upgraded to final release of 0.18.3, that has this issue: https://lemmy.ml/post/2544798

### Steps to Reproduce

1. Create a YouTube posting url link: https://www.youtube.com/watch?v=cfm4L0TGDrw
2. View the results on lemmy-ui output

(Now Lemmy matches this same bug on old Reddit on some link titles)
### Technical Details

N/A as far as I know, I will be adding test code to lemmy server project code contribution to demonstrate/exercise the Rust code paths of this problem.

### Version

BE: 0.18.3

### Lemmy Instance URL

lemmy.ml

**Comment by RocketDerp** [comment]
I found an example of a mundged comment in the wild on Lemmy.ml:

**Comment by RocketDerp** [comment]
Well, this seems another bug, possibly on front-end?

The comment I just posted a screen-shot from, is https://lemmy.ml/comment/2071725

But when you open that link, you see only my reply (RoundSparrow), and not the actual comment 2071725... Here is a link to the user who created the comment: https://lemmy.ml/u/ohai@subsubd.com on Lemmy.ml - but when you click the link in their profile to that specific comment, it isn't being shown?

![image](https://github.com/LemmyNet/lemmy/assets/113625597/630bfe15-518b-46f6-b3c4-650524399607)

**Comment by ohathar** [comment]
> Well, this seems another bug, possibly on front-end?
> 
> The comment I just posted a screen-shot from, is https://lemmy.ml/comment/2071725
> 
> But when you open that link, you see only my reply (RoundSparrow), and not the actual comment 2071725... Here is a link to the user who created the comment: https://lemmy.ml/u/ohai@subsubd.com on Lemmy.ml - but when you click the link in their profile to that specific comment, it isn't being shown?
> 

Hey, that's me! If there's anything I can do to help test, I'm more than happy

**Comment by RocketDerp** [comment]
Does that comment link open for you? Did you delete the comment, was it banned or anything? It's weird that a direct link to https://lemmy.ml/comment/2071725 doesn't show your comment.

**Comment by ohathar** [comment]
It's just as you described, it shows only your comment reply. Interestingly, the permalink from my own instance, https://subsubd.com/comment/108169 does the same.... No, I didn't delete it or anything. Not sure if it was banned or not (that seems like it would be pretty weird if were banned).

**Comment by RocketDerp** [comment]
Some testing code regarding munging of titles, also #3774 about munging code blocks: https://github.com/RocketDerp/lemmy_server_fixes0/blob/9e02a20db30986c07ceabdb0cf308e12d49da7e3/api_tests/src/post.spec.ts#L536

**Comment by RocketDerp** [comment]
odd, the comment link now shows your comment https://lemmy.ml/comment/2071725 - there's been a couple new replies added since we had the problem, I wonder if that is a factor.

**Comment by RocketDerp** [comment]
lemmy-ui seems to be returning the wrong comment, different than the id you ask for, example over at: https://github.com/LemmyNet/lemmy-ui/issues/1999

**Comment by RocketDerp** [comment]
It looks like a community description also had & converted

![image](https://github.com/LemmyNet/lemmy/assets/113625597/8e32feac-b37b-4cc7-9e66-430771f32c10)

**Comment by ShittyKopper** [comment]
this breaks URLs with query parameters: https://lemmy.blahaj.zone/post/2064898

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/4024
