### ISSUE TITLE
Indicate to user that maximum 3 password resets per day are allowed

### ISSUE THREAD

**Issue by pallebone** [LemmyNet/lemmy#3757]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

update:
This is the actual bug and why people think email is broken: 

No notification is sent to the user they have used up the 3 password resets and will not get another one. So appears to user email is broken. Also there is no way to resent a new user verification email if it is lost.

Documents say to test email is working via pass reset but fail to mention you only get 3 attempts per day, no error shown when you exceed 3. 

————

Email was working with this configuration in lemmy.hjson

  email: {
    smtp_server: "in-v3.mailjet.com:587"
    smtp_login: "redacted"
    smtp_password: "redacted"
    smtp_from_address: "lemmy@myserv.one"
    tls_type: "starttls"

Since upgrading the email stopped working unfortunately.
Was able to get some help on matrix and test settings are correct using swaks via the CLI inside the docker image image: dessalines/lemmy:0.18.3

The email can send using the expected settings, however when not using swaks and wanting lemmy to send a mail nothing happens. No errors appear in any logs I can find so it is possible lemmy is not logging anything.

Other users commonly use postfix as a separate docker image so are not affected.

Unclear how I can progress as it appears broken inside lemmy docker somehow.

Any assistance appreciated.

Kindr egards
Peter

### Steps to Reproduce

Testing by trying to do a password reset on the lemmy site via Firefox.

### Technical Details

OS is Debian 12
Docker logs contain no information regarding email whatsoever.

### Version

0.8.3

### Lemmy Instance URL

lemmy.myserv.one

**Comment by pallebone** [comment]
I wish to alter the bug I am reporting here. After further investigation, lemmy is able to generate SOME emails. 
So if I do a password reset on my email account it cannot generate an email, but another email account it actually can work so it seems like lemmy can generate emails at least sometimes.

**Comment by pallebone** [comment]
I believe lemmy cant reset or send emails for the email associated with the ADMIN user which (no surprise) was the email I decided to test with.

**Comment by pallebone** [comment]
Setup with admin account is it was created, I modified its email when i first setup the server to my email address and enabled MFA. Normally I dont log in with the admin account.
Testing was done against the admin accounts email address.
admin account is "lemmy"

**Comment by pallebone** [comment]
"The  Legend" on matrix helped me find why this was happening.

All users on lemmy get 3 password resets a day only and no more, so if anyone exceeds that then it appears like email is broken. There are no errors in the logs. You have to clear the rows from the DB to get it working again.

P

**Comment by pallebone** [comment]
It feels like there should be an error message sent to the user if this happens because currently nothing is logged and no message appears in the UI to indicate the problem and 3 attempts is very little if something is not working or there is testing. The documentation tells you to test email is working by doing a password reset so its confusing for an admin also.

**Comment by pallebone** [comment]
No just for that user for 24 hours

**Comment by NachoPicchu** [comment]
Using the shipped mailserver config from the ansible installation, e.g.
`email: {
smtp_server: "postfix:25"
smtp_from_address: "noreply@{{ domain }}"
tls_type: "none"
}`
Users are not receiving confirmation emails for their accounts.
The mail server seems to generally work as I've gotten an e-mail to review a registration application once.
Subsequent registrations have not resulted in a mail to my admin account though.

**Comment by pallebone** [comment]
Actual bug is: 

No notification is sent to the user they have used up the 3 password resets and will not get another one. So appears to user email is broken. Also there is no way to resent a new user verification email if it is lost. 

For working email configs only these I know to work. Please do not post anything else and ask for support.  Only these work (unless you run your own email server then do whatever you want). 


email: {
    smtp_server: "providerdomain:465"
    smtp_login: "key"
    smtp_password: "pass"
    smtp_from_address: "Lemmy Do Not Reply <lemmy@myserv.one>"
    tls_type: "tls"

alternatively you might use;
email: {
    smtp_server: "providerdomain:587"
    smtp_login: "key"
    smtp_password: "pass"
    smtp_from_address: "Lemmy Do Not Reply <lemmy@myserv.one>"
    tls_type: "starttls"

Again do not post other configs. Only configs like this are valid. If your provider does not support 587 or 465 you are alone and nobody can help you. 

Do not comment further on this post. Tnx.

**Comment by ubergeek77** [comment]
I believe this is relevant here - can anyone confirm deny the following statement:

- If a user on Instance B sends a DM to a user on instance A, the user on instance A will not receive an email

This isn't an SMTP misconfiguration or anything, it's just that Lemmy is not sending an SMTP message for this specific use case, at least in my experience.

Can anyone confirm this?

To clarify my experience on 0.18.3:

- Signup/Approval emails: work fine
- Password reset emails: work fine (and I did this quite a few times)
- Comment reply emails: work fine
- DM emails from users on same instance: work fine
- DM emails from users on external instance: no email

If people confirm this, we could turn this into a generic discussion of "unexpected behavior, email not sent when it should have been." That would also get us back on topic to Lemmy-specific issues and not SMTP misconfiguration issues.

**Comment by pallebone** [comment]
> I believe this is relevant here - can anyone confirm or deny the following statement:
> 
> * If a user on Instance B sends a DM to a user on instance A, the user on instance A will not receive an email
> 
> This isn't an SMTP misconfiguration or anything, it's just that Lemmy is not sending an SMTP message for this specific use case, at least in my experience.
> 
> Can anyone confirm this?
> 
> To clarify my experience on 0.18.3:
> 
> * Signup/Approval emails: work fine
> * Password reset emails: work fine (and I did this quite a few times)
> * Comment reply emails: work fine
> * DM emails from users on same instance: work fine
> * DM emails from users on external instance: no email
> 
> If people confirm this, then it would be an additional case where emails should be sent out, but aren't.
> 
> So, we could turn this into a generic discussion of "unexpected behavior, email not sent when it should have been." That would also get us back on topic to Lemmy-specific issues and not SMTP misconfiguration issues.
> 
> For what it's worth, this did not start in 0.18.3, it's been an issue since I first set up Lemmy, well before 0.18.3.

I believe this is already a known issue.

**Comment by pallebone** [comment]
@ubergeek77 I just checked on matrix chat and nobody has logged a bug for this.

**Comment by ubergeek77** [comment]
Yeah I don't think there are many email issues here. I wonder if they're secretly the same bug? I can't claim to have read through the code, but the issues seem similar.

**Comment by pallebone** [comment]
I think you should log a new bug just so its not missed @ubergeek77
