### ISSUE TITLE
[Bug]: The project leaders of Lemmy multi-server network, who run https://lemmy.ml as an official SUPPORTED instance, have social anxiety over PostgreSQL issues

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3764]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Since May 25, 2023 - Lemmy.ml developer instance has crashed every 10 minutes of every day. I measured it personally. SHOW LOGS to prove otherwise.

### Steps to Reproduce

1. Visit lemmy.ml like I did, user RoundSparrow
2. watch constant REPEAT crashes
3. Watch June 4, 2023 issue #2910 be ignore and denied (psycology)

### Technical Details

Carl Jung psychology about mythology and hazing rituals

### Version

BE 0.17.4

### Lemmy Instance URL

lemmy.ml

**Comment by lionirdeadman** [comment]
Hey, please don't make issues like this. If you'd like to vent and talk, feel free to message me on Matrix or Discord.

**Comment by RocketDerp** [comment]
>  Hey, please don't make issues like this. If you'd like to vent and talk, feel free to message me on Matrix or Discord.

In other words, you do not care about my extreme duress, and want to death-wish me? Plee provide at least 5 pages of detailed eibaoration of why this is th wron place and how brain-damaged I must be to post here? PLEASE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by RocketDerp** [comment]
@lionirdeadman 

Do you love every human being on Earth, Pale Blue Dot, or only something less than 100%? I( do not grasp your reply.

@lionirdeadman  ... This is NOT a RHETORICAL QUESTION: DO you love 100% of human beings? Love ALL persons?

**Comment by lionirdeadman** [comment]
I don't love everyone, I think many people are bad. That said, I obviously don't want to cause you pain and I hope you the best, that's why I asked if you wanted to talk in private.

**Comment by RocketDerp** [comment]
> I don't love everyone

you HATE human beings?

**Comment by lionirdeadman** [comment]
There are human beings I hate, yes. I love many people but there will be some people I hate - I hate nazis and bigoted people for example. Please don't try to twist my words.

I don't understand what you're trying to say and I would like to. I would like to help you and talk to you. Please message me in private.

**Comment by RocketDerp** [comment]
@lemmus-org 

1. Have you read #2910?
2. Is the date of #2910 June 4?
3. What evidence do you have that Project leaders of Lemmy project ***escalated*** Issue #2910 as urgent critical priority of ***server crashing***?

**Comment by RocketDerp** [comment]
>  hate - I hate nazis and bigoted people

So you have FAITH in the FUTURE that HATE improves the Pale Blue Dot of FUTURE?

**Comment by lionirdeadman** [comment]
I don't know what you're trying to say and I would like to talk to you in private rather than here. Can we please do that?

**Comment by RocketDerp** [comment]
>  Hey, please don't make issues like this. If you'd like to vent and talk, feel free to message me on Matrix or Discord.

You win, gate-keeper, You defended #2910 response time of 50+ days. I quit.

**Comment by lionirdeadman** [comment]
I don't know rust, I'm not defending anyone. I'd like to help you; I just don't think GitHub issues is the place for that.

If you believe quitting is best for you, please do so. I sincerely wish you the best.

**Comment by RocketDerp** [comment]
@lionirdeadman 

# Amazing

How you could ignore #2910 for so long

#Really smart of you 

Ignoring #2910 since June 4

**Comment by RocketDerp** [comment]
# Sorry I went so angry

This is why, Sunday night

![image](https://github.com/LemmyNet/lemmy/assets/113625597/5caf5663-5996-42b5-8d2c-41c40b0f336f)

**Comment by dessalines** [comment]
No problem :)
