### ISSUE TITLE
[Bug]: The project leaders of Lemmy multi-server network, who run https://lemmy.ml as an official SUPPORTED instance, use PostgreSQL issues as a means to support China CCP or other agenda? Or some similar agenda? Ignoring issue #2910 since June4?

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3765]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

The back-end of the back-end

### Steps to Reproduce

1. Watch GitHub since early June
2. Watch Issue #2910 get ignored by project leaders
3.

### Technical Details

N/A, social agenda

### Version

BE 0.17.4

### Lemmy Instance URL

lemmy.ml

**Comment by lionirdeadman** [comment]
Please stop, you don't need to do this. I'm still up for a chat if you want.

**Comment by RocketDerp** [comment]
> I'm still up for a chat if you want.

You told me that HATE of human beings is a value you hold, factual?

**Comment by lionirdeadman** [comment]
Not everyone. I don't hate you. Please, we can talk.

**Comment by RocketDerp** [comment]
Are you after something sexual private? a kink? I'm deeply offended and hurt.

**Comment by RocketDerp** [comment]
Why does factual dates of Issue #2910 havee to be kept secret/private?

**Comment by lionirdeadman** [comment]
No, I would not do something sexual and it is not a kink. I don't want to hurt you. GitHub issues are simply not the place for this. 

You've been very accusatory and it's increasingly becoming difficult to try to build a bridge if you're burning them in public. I would like to have this talk in private because I think the way you're acting in public will only cause you harm.

**Comment by RocketDerp** [comment]
> You've been very accusatory and it's increasingly becoming difficult to try to build a bridge if you're burning them in public. I would like to have this talk in private because I think the way you're acting in public will only cause you harm.

SILENCE my raising the facts of #2910  covering for the developers?

I am Stephen Alfred Gutknecht without hidden identity, who are you?

**Comment by lionirdeadman** [comment]
I don't feel comfortable sharing my identity. All I can say is I am not covering for the developers - I'm just trying to optimize GitHub issues to allow people to find issues easier.

**Comment by RocketDerp** [comment]
> I don't feel comfortable sharing my identity. 

TRUTH and FACT of issue #2910 either.

**Comment by lionirdeadman** [comment]
I don't know why you're trying to insult me or why you seem hate me now. I'm just trying to help. I wish there was a way for me to get that feeling across to you.

**Comment by RocketDerp** [comment]
You told me you HATE human persons, were you ever educated how HATE poisons your thinking?

You should stop hate, it is the worst brain damage

"There's another reason why you should love your enemies, and that is because hate distorts the personality of the hater. We usually think of what hate does for the individual hated or the individuals hated or the groups hated. But it is even more tragic, it is even more ruinous and injurious to the individual who hates. You just begin hating somebody, and you will begin to do irrational things. You can't see straight when you hate. You can't walk straight when you hate. You can't stand upright. Your vision is distorted. There is nothing more tragic than to see an individual whose heart is filled with hate. He comes to the point that he becomes a pathological case. For the person who hates, you can stand up and see a person and that person can be beautiful, and you will call them ugly. For the person who hates, the beautiful becomes ugly and the ugly becomes beautiful. For the person who hates, the good becomes bad and the bad becomes good. For the person who hates, the true becomes false and the false becomes true. That's what hate does. You can't see right. The symbol of objectivity is lost. Hate destroys the very structure of the personality of the hater. [...] when you start hating anybody, it destroys the very center of your creative response to life and the universe; so love everybody. Hate at any point is a cancer that gnaws away at the very vital center of your life and your existence. It is like eroding acid that eats away the best and the objective center of your life. So Jesus says love, because hate destroys the hater as well as the hated."

**Comment by lionirdeadman** [comment]
Well, I love many people and I focus my energy on those I love. Of course, there are people I hate. I'm sure that's true of you as well. After all, if you don't hate me, why would you insult me?

Despite these insults, I am still reaching out to you to help. I'd still like to talk with you in private and help you.

**Comment by RocketDerp** [comment]
> there are people I hate. I'm sure that's true of you as well.

I said I am Stephen Alfred Gutknecht, and you are public-ally posting that I HATE persons? That I do not believe LOVE and COMPASSION are cures to hate?

I am considering a legal case about what you just said about me.

**Comment by RocketDerp** [comment]
> there are people I hate.

Lemmy project is run by  staff who HATE

“There’s another reason why you should love your enemies, and that is because hate distorts the personality of the hater. We usually think of what hate does for the individual hated or the individuals hated or the groups hated. But it is even more tragic, it is even more ruinous and injurious to the individual who hates. You just begin hating somebody, and you will begin to do irrational things. You can’t see straight when you hate. You can’t walk straight when you hate. You can’t stand upright. Your vision is distorted. There is nothing more tragic than to see an individual whose heart is filled with hate. He comes to the point that he becomes a pathological case. For the person who hates, you can stand up and see a person and that person can be beautiful, and you will call them ugly. For the person who hates, the beautiful becomes ugly and the ugly becomes beautiful. For the person who hates, the good becomes bad and the bad becomes good. For the person who hates, the true becomes false and the false becomes true. That’s what hate does. You can’t see right. The symbol of objectivity is lost. Hate destroys the very structure of the personality of the hater. […] when you start hating anybody, it destroys the very center of your creative response to life and the universe; so love everybody. Hate at any point is a cancer that gnaws away at the very vital center of your life and your existence. It is like eroding acid that eats away the best and the objective center of your life. So Jesus says love, because hate destroys the hater as well as the hated.”

**Comment by lionirdeadman** [comment]
> I AM BEGGING YOU, why PRIVATE? What is the advantage of private? PLEASE ANSWER, NOT RHETORICAL!

I think a chat in private is better to try to convey emotion and to talk things through. I don't feel comfortable talking about my personal life in public and I believe that's true of most people. I'd like to understand you better without making this available to everyone. I don't think it'd be a good idea to do that in public.

**Comment by RocketDerp** [comment]
> I think a chat in private is better 

Why? Are you a pervert? sex naked?

**Comment by lionirdeadman** [comment]
I think I just explained why, can you tell me what you don't understand?

**Comment by RocketDerp** [comment]
>  I don't feel comfortable talking about my personal life in public

Nobody asked YOU   @lionirdeadman  - who avoids REAL EARTH IDENTITY, to join Stephen Aflred Gutknecht in private. You are manipulative and trying ot lure me into private with no public record. I have brain damage and you think you can fuck me over.

**Comment by lionirdeadman** [comment]
I'm sorry - I don't think I can help you if you think I'm trying to abuse you. I really wish I could help you and I wish you the best. I'm still available for a chat if you change your mind.

**Comment by RocketDerp** [comment]
> f you think I'm trying to abuse you

OI do not THINK it, I know it, factual. You denuclearized me at every reply.

**Comment by RocketDerp** [comment]
> . I'm still available for a chat if you change your mind.

You refuse to answer why PRIVATE SECRET chat is best, Why do you keep wanting to lure me away from public eye?

**Comment by RocketDerp** [comment]
Do you notice you haven't once mentioned issue #2910 on June 4?

**Comment by RocketDerp** [comment]
![image](https://github.com/LemmyNet/lemmy/assets/113625597/a23a9a5f-ba5c-4a89-b7a2-0746fd858387)

**Comment by lionirdeadman** [comment]
I already answered why I think a private chat would be best. I don't understand why you think I'm abusing you. I don't understand why you're trying to insult me and I don't understand why you've been this harsh with me.

**Comment by RocketDerp** [comment]
> I already answered why I think a private chat would be best.

Do you LOVE 100% of all humans, or do you hate people? I do not TRUST you are BEING FACTUAL and HONEST.

**Comment by RocketDerp** [comment]
# Sorry I went so angry

This is why, Sunday night

![image](https://github.com/LemmyNet/lemmy/assets/113625597/5caf5663-5996-42b5-8d2c-41c40b0f336f)
