### ISSUE TITLE
Implement Passkeys/WebAuthn

### ISSUE THREAD

**Issue by basskitten** [LemmyNet/lemmy#3768]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Please implement passkeys aka webauthn for Lemmy. It will make the sign in experience better and strengthen security.

https://webauthn.guide

**Comment by Nutomic** [comment]
What is this and why would it be beneficial for Lemmy?

**Comment by basskitten** [comment]
Passkeys are the new standard to authenticate on the web.

Passkeys are a safer and easier replacement for passwords. With passkeys, users can sign in to apps and websites with a biometric sensor (such as a fingerprint or facial recognition), PIN, or pattern, freeing them from having to remember and manage passwords.

(copied from passkeys.com)
ironically I’m pasting this on GitHub, where I just signed in using .. guess what .. a passkey

**Comment by Nutomic** [comment]
Sounds like this is a commercial product from some company, no thanks.

**Comment by CoelacanthusHex** [comment]
> Sounds like this is a commercial product from some company, no thanks.

Webauthn is a W3C recommended standard and a part of another W3C standard FIDO2. Passkey is only a type of FIDO2, it was implemented by not only commercial companies but also open-source projects such as BitWarden/Vaultwarden. And there are many other types of FIDO2 devices, some were made by commercial companies like Yubikey by Yubico, and others were made by the community and open source, like Solokey, and OpenSK.

https://www.w3.org/TR/webauthn-1/
https://www.w3.org/TR/webauthn-2/

**Comment by CoelacanthusHex** [comment]
In other words, Passkey is often just a business term used by commercial companies to promote their FIDO2 Passwordless implementation. For example, GitHub and Google call all FIDO2 passwordless devices as Passkey and call all 2fa FIDO2 devices as Security Key, but in tech, these things just use FIDO2/WebAuthn API, they all are FIDO2 devices, just use it in a different way. In tech, those should all be called Security Key, there is no Passkey in tech terms.

**Comment by dessalines** [comment]
If someone wants to work on this, they're free to.

**Comment by dessalines** [comment]
Can re-open if someone wants to work on this.
