### ISSUE TITLE
Question: Why do so many API requests seem to respond with unnecessary responses causing extra bandwidth usage?

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#3769]
### Question

Why do so many API requests seem to respond with unnecessary responses?

I'll give you a few examples:
- If you fetch the comments to a post, it will also include the community and the post it was commented in for **each** comment. I have this information already from fetching the post.
- When requesting your private_messages, it will include the recipient per pm, I am the recipient, I don't need this information. (same goes for mentions and replies)
- `user/mark_all_as_read` the endpoint that marks all unread mentions/replies/messages as read will also return all the replies. Why does it return the replies and why does it only return the replies?

So many responses include the full objects where a simple id for that object suffices. And sometimes like in the cases above, that id imo is not even needed.

**Comment by RocketDerp** [comment]
see also: #https://github.com/LemmyNet/lemmy/issues/3531 ??

**Comment by Nutomic** [comment]
If there is unnecessary data we can definitely get rid of it for the next major version. Pull requests welcome.

**Comment by Nutomic** [comment]
Some are fixed here: https://github.com/LemmyNet/lemmy/pull/4058

**Comment by Nutomic** [comment]
Closing this as the question has been answered. Also see https://github.com/LemmyNet/lemmy/issues/2957
