### ISSUE TITLE
Require a valid email address ending with a .tld when signing up

### ISSUE THREAD

**Issue by sleeping-miyagi** [LemmyNet/lemmy#3773]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

New users can sign up for an account with an invalid email that doesn't end with a TLD. For example, they can sign up with `myusername@yahoo` instead of `myusername@yahoo.com`. Verification emails will fail to send or bounce back so the sign up process will never be completed.

There should be validation checks in place to ensure that only valid email addresses are accepted during the signup process.

### Describe the solution you'd like.

Account registration should only accept valid email addresses ending with a TLD. This should be a requirement upon registering and an invalid email should not be accepted when clicking the "Sign Up" button at the end of the sign up form.

### Describe alternatives you've considered.

Display a message or toast that says "Verification email sent to username@domain" and give users the ability to change the email address and resend the verification when they realize their carelessness.

**Comment by RobinFlikkema** [comment]
Please keep in mind that myname@ai is a valid mail address. As "ai." has a MX-record. See for example: https://datatracker.ietf.org/doc/html/rfc7085#section-2.3

However for the new gTLDs [this is not allowed.](https://www.icann.org/en/announcements/details/new-gtld-dotless-domain-names-prohibited-30-8-2013-en) .


Therefore, it might also be acceptable to just "deny" users having only a TLD as mail-domain.

**Comment by lionirdeadman** [comment]
> Furthermore emails like myname@[IPv6:2001:db8::1] are also valid.

While they are valid, I think we should intentionally invalidate them because this will be a spam vector

**Comment by dessalines** [comment]
We already have an email regex check, that looks like it comes from a tested source. If its incorrect you can post or do a PR for a different one.

**Comment by Nutomic** [comment]
@dessalines We dont have any regex check for email currently.

**Comment by dessalines** [comment]
Its here: https://github.com/LemmyNet/lemmy/blob/568233b06243d58e5ceaa3c9f8487bc0c19d5463/crates/db_schema/src/utils.rs#L367

**Comment by Nutomic** [comment]
Okay correction, we are not doing email regex checks anywhere in the api. That function is only used in unit tests.
