### ISSUE TITLE
Soft Removal

### ISSUE THREAD

**Issue by jarrodsfarrell** [LemmyNet/lemmy#3776]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

So I posted a question and either the community revised its rules afterwards or I just didn't read, that thread got removed. Which is fine to remove clutter, but became a bit frustrating when all the information posted to it got orphaned and I had to do some sleuthing to recover what was lost.

### Describe the solution you'd like.

I'm still fine with removing threads from the community's main page but there might be a case where a thread isn't malicious and the information within is still useful, just in the wrong place or minor rule issue. So removing it outright and causing orphans is not beneficial.

Maybe an alternative option where a thread can be soft-removed from the community's page, but still exists in such a way that it can be found by it's URL or in the modlog. Maybe allow a reason that presents a banner á la Reddit.

### Describe alternatives you've considered.

Checking the [documentation](https://join-lemmy.org/docs/users/04-moderation.html), there's no soft deletion option. Only remove.

**Comment by jarrodsfarrell** [comment]
Additional consideration is probably how to handle replying to threads/comments from instances out of sync or from different fediverses like Mastodon that most likely do not have a equivalent way to handle cases like this.

**Comment by RocketDerp** [comment]
> how to handle replying to threads/comments from instances out of sync or from different fediverses like Mastodon that most likely do not have a equivalent way to handle cases like this.

I've been trying to devise some testing code for these situation, as I expect Lemmy's behavior can change (as too Mastodon) over time and easy to not catch it. Does Mastodon have locked posting concept, etc.

**Comment by dessalines** [comment]
Having two different kinds of remove is out of scope for us rn, but I'll re-open if someone wants to take it on.

**Comment by Nutomic** [comment]
It could make sense to let users view their own removed posts, but hide them from other users.
