### ISSUE TITLE
Ability for user to resent email verification 

### ISSUE THREAD

**Issue by pallebone** [LemmyNet/lemmy#3777]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

If a user loses the email verification email on signup, it is impossible to login or get another one. 

### Describe the solution you'd like.

Ability to resent email verification emails. 

### Describe alternatives you've considered.

-

### Additional context

Users sometimes lose their email verification and the accounts get stuck in limbo due to this. No way to resolve the problem.

**Comment by therealmaxmoon** [comment]
I had an issue with my email server and verification mails haven't been sent.

It would be nice if this feature would be there for admins, too, to resend a verification to all people who aren't verified yet or just have a button, which purges all unverified users, because [trying to do it by hand](https://lemdit.com/post/16430), doesn't work correctly.

**Comment by K0-RR** [comment]
Why is this still not fixed? This is urgent as people are being locked out of their accounts.
I didn't even receive a confirmation email from feddit.rocks and now I can't log in…

**Comment by dessalines** [comment]
@K0-RR I can help you get started with this issue. You'll need to create a table which stores emails that haven't been sent successfully, and attempt to retry them periodically until they go through.

**Comment by dessalines** [comment]
This exists in lemmy-ui now. Click the forgot password button, then type in your email.

**Comment by JL710** [comment]
> This exists in lemmy-ui now. Click the forgot password button, then type in your email.

Doing that does send a email to set a new password but it does not verfy your email. At least not for me on https://lemm.ee.

**Comment by dessalines** [comment]
That fix hasn't been deployed anywhere yet. But also if your first email was verified, it doesn't need to re-verify your new one.
