### ISSUE TITLE
Add Reddit-like awards to Lemmy. It could help fund instance infrastructure.

### ISSUE THREAD

**Issue by Oneechan69** [LemmyNet/lemmy#3779]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

As far as I know, most Lemmy instances are funded by donations, and activity is only to increase in time, making maintaining them increasingly expensive.

### Describe the solution you'd like.

Awards like the Gold Award are very popular on Reddit, with many top posts getting lots of awards. I think many users on Lemmy would be willing to give posts good awards, and the ability to financially support Lemmy instances that way would be especially appealing.

### Describe alternatives you've considered.

None.

**Comment by WayneSheppard** [comment]
Needs to be fleshed out more, especially with federation.  A simple case, you make a post on your home SERVER-A and the community home is on SERVER-B and I want to give you an award, and I live on SERVER-C.  Which server profits from the donation?

Does the award get federated to every subscribing server?

**Comment by slrgt** [comment]
this is not a good idea in my opinion. it will cause if users are awarded users should get the reward for their contribution not the admins. to support instances we should have a health bar type ui showing how much money is used for infrastructure costs etc and how much is being donated monthly through opencollective\patreon\github sponsors. Like how reddit used to have the Gold bar ui 
![image](https://github.com/LemmyNet/lemmy/assets/114287507/44818d0e-eeeb-40ab-ab21-47d0821c1f68)

**Comment by josharky** [comment]
Given large parts of the fediverse are anti-capitalist and the idea of subscription tiers is ick, I l'd hope you'd get push back. 

My admins Ada and Kaity have already replied to a Lemmy post that links here to GitHub. There'll be [no subscription tiers on blahaj zone's Lemmy and Hajkey/Iceshrimp servers](https://lemmy.world/post/2498720) and I fully support that.

**Comment by jakariyab** [comment]
Community based awards feature is okay. For example an award can be given by community authors and it will be visible on that community only. But we shouldn't be promoting subscription types of awards and rather have some type of bars (or other ways) to encourage people to donate! (In my opinion ofc)

**Comment by Nutomic** [comment]
This would probably require an integration with proprietary payment operators like Paypal which is not an option. Not to mention that there would be no way to ensure that awards from other instances were actually paid for, or simply faked by an admin.
