### ISSUE TITLE
Moderator from other instances not receiving reports

### ISSUE THREAD

**Issue by obosob** [LemmyNet/lemmy#3781]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I am a moderator on a community on an instance different to my own and I don't receive reports made by users. I only found out about the report due to being told via a different channel by the user that made the report. 

It may also be useful to note that the user that made the report was on an instance different to both my own and the community in question.

I haven't yet made further attempts to reproduce the issue but plan to make some alt accounts around to do some testing and will update this issue accordingly with what I find.

### Steps to Reproduce

1. Be a mod of a community on a different instance 
2. Have a user make a report on a post
3. Note an empty "Reports" page

### Technical Details

I don't have access to the relevant technical details. 

### Version

BE 0.18.2, BE 0.18.3

### Lemmy Instance URL

lemmy.world, feddit.uk, rblind.com

**Comment by RocketDerp** [comment]
I've been working on testing of data replication for remote instances, I'll add this.

**Comment by Nothing4You** [comment]
adding issue search keywords: federation, federated

**Comment by dessalines** [comment]
I believe this is fixed, but can re-open if this is still an issue.

**Comment by Nothing4You** [comment]
it's still an issue, both on 0.19.3 and 0.19.4-beta.6

**Comment by Nothing4You** [comment]
Possibly related to #4701 if this was supposed to be fixed after 0.19.3.
