### ISSUE TITLE
[Bug]: SSL Errors for email and no outbound federation after upgrading

### ISSUE THREAD

**Issue by finnim** [LemmyNet/lemmy#3783]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

After upgrading from 0.18.2 to 0.18.3 there's two things that have been happening:

- Can't send emails via external SMTP server
- No outbound activity is received by other instances (can receive remote content fine)

Regarding sending email I get this error:

`lemmy_1     | 2023-07-31T16:57:18.557188Z  WARN lemmy_server::root_span_builder: email_send_failed: Connection error: Connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
lemmy_1     |
lemmy_1     | Caused by:
lemmy_1     |     0: Connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
lemmy_1     |     1: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
lemmy_1     |     2: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
lemmy_1     |    0: lemmy_api::local_user::reset_password::perform
lemmy_1     |              at crates/api/src/local_user/reset_password.rs:16
lemmy_1     |    1: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=POST http.scheme="https" http.host=lemmy http.target=/api/v3/user/password_reset otel.kind="server" request_id=xxx
`

This started happening exactly the moment I upgraded to the point that the last post instances received from us seemed to be the "we are upgrading to lemmy v0.18.3."

lemmy.hjson email settings is set to "tls" and I don't want to change it as it was working before and I wouldn't like to send emails in an insecure manner.

### Steps to Reproduce

1. Upgrade to v.0.18.3
2. Try to reset password
3. View lemmy server logs.

### Technical Details

Running Ubuntu 20.04, with IPv4 behind NAT and IPv6. Domain is behind cloudflare. Everything was working before, so I wonder if anything has changed in the latest version.

### Version

BE 0.18.3

### Lemmy Instance URL

yiffit.net

**Comment by finnim** [comment]
Here's what I found:

1. Outbound messages are received by instances who did not know us before the upgrade, which makes me suspect that other instances are rejecting our messages.
2. Email works again after using starttls option. Which is weird because I have set it to communicate via port 587. I noticed there's a commit which changes email ports or something, which might be related to this issue.

**Comment by benwoody** [comment]
Also seeing this issue after upgrading to `0.18.3` and changing `tls_type` to `starttls` did not seem to fix the issue.
