### ISSUE TITLE
[Bug]: Strip markdown from titles 

### ISSUE THREAD

**Issue by pwd-github** [LemmyNet/lemmy#3789]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

As Lemmy is federated, occasionally it gets posts from mastodon. However there posts inevitable come with markdown. Markdown should be stripped from the title variable before it's submitted into the database

### Steps to Reproduce

1. Go to mastodon
2. Write a toot and include hashtags and also a community
3. Submit it
4. Look at it on Lemmy 

### Technical Details

N/A because it's a data issue

### Version

0.18.3 and below

### Lemmy Instance URL

lemmy.world but it affects all instances

**Comment by Nutomic** [comment]
Closing in favor of https://github.com/LemmyNet/lemmy/issues/3828.
