### ISSUE TITLE
Strip special characters from display names

### ISSUE THREAD

**Issue by Fmstrat** [LemmyNet/lemmy#3790]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The backend should not allow special characters that cannot be entered via a standard international keyboard into user names. I've run into about 5 of these types of usernames thus far, and it's only going to get worse and less legible:
![Screenshot_20230801-073144](https://github.com/LemmyNet/lemmy/assets/971474/58bab001-a2c3-4ccd-8164-0187c9caad98)

### Describe the solution you'd like.

Block non-standard characters at the API level (so that it blocks in apps, web UI, etc).

### Describe alternatives you've considered.

Filtering at the app/UI level, but this seems excessive.

**Comment by lionirdeadman** [comment]
Blocking these at the API level could result in blank names which is not much better.

**Comment by ruffsl** [comment]
> Blocking these at the API level could result in blank names which is not much better.

If a provided display name is detected to be "un-typable" then the backend could prevent the user from applying the profile change. And for users with existing invalid display names, they could be cleared in a DB migration. Not sure how to handle remote federated traffic. Could that just be sanitize before writing to the local DB?

Or have I misunderstood, and that this issue also applies to user handles as well as display names, the former being a much bigger issue.

I do think what can be entered via a standard international keyboard is still a bit vague, as a lot of language input software exists to augment character input out of necessity, and thus gate keeping what Unicode is allowed or not could impact international communities and obscure language instances.

**Comment by lionirdeadman** [comment]
User handles only allow latin characters AFAIK.

Also, yeah, gatekeeping unicode could be harmful to people who use non-latin languages.

**Comment by Fmstrat** [comment]
> How about we just add a "display name regex" where admins can insert a regex. All display names must match the regex or are denied when trying to edit.

The tough part about this solution is it's non-standardized. App developers are going to have to take these characters into account, so it can lead to a lot of downstream issues like we're seeing in formatting today.

Nothing is stopping me from making my display name:

𒅃 𒀱𒈓⃠⃢⃣⃤ℹ▊█▉😃⃢ဪ﷽̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺ͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩဪ𒌧𒀱𒀱𒀱𒌧꧅ ̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺ͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩ 𓀐𓂸꧄👍 ̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺ͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩ 𓀐𓂸꧅ ̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺̺ͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩͩ 𓀐𓂸4aa𒐫

Right now. Which you can see even on GitHub causes issues.

**Comment by SorteKanin** [comment]
>The tough part about this solution is it's non-standardized.

I don't think it's reasonable to set a standard for what characters are allowed in display names across all instances - or rather, it is reasonable and that standard already exists and it's called Unicode.

If we make a unified standard across instances, that will inevitably lead to some instance in the future being unable to use some character that might be part of their actual language or something.

As a compromise, I guess the lemmy default configuration could include a suggested regex that admins would be free to adjust.

**Comment by dessalines** [comment]
You can add any special characters to the `FORBIDDEN_CHARS` variable. But we aren't going to blanket remove all unicode from display names.
