### ISSUE TITLE
Admin option to set instance default sort by New Comments

### ISSUE THREAD

**Issue by slrgt** [LemmyNet/lemmy#3796]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently admins can only set default options to be local or All.

### Describe the solution you'd like.

The option for admins to set default view to New Comments would allow us to make communities that are more similar to forums than social media

### Describe alternatives you've considered.

.

**Comment by MV-GH** [comment]
How will this work with the feature that will allow users to save their default comment sort types. Will this override that feature? or will it be complementary in the sense that this will set the initial value of this feature and will be overwritten when a user sets a new default?

**Comment by slrgt** [comment]
The users choice would overwrite the server’s defaults. Just like when users change sorting from All to Local

**Comment by Die4Ever** [comment]
Should this be per instance, or per community?

**Comment by slrgt** [comment]
Option for both

**Comment by dessalines** [comment]
Adding this at the instance level wouldn't be too difficult.
