### ISSUE TITLE
Allow the user to see the content of posts that were removed by a moderator

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3804]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

In the modlog, you currently can see the content of comments, and the titles of posts that were removed by a moderator, but it appears that the content of the posts is not viewable. It appears that comments, and post titles are being treated as the same object; however, I would say that then content of posts, and comments are equivelant instead.

### Describe the solution you'd like.

The content of moderator removed posts should still be made available (of course, unless the admin explicitly whipes them from the server)

### Describe alternatives you've considered.

none

### Additional context

This may also be a UI issue in that the UI of the modlog needs to be able to show the contents of the posts, and not just the title.

**Comment by RocketDerp** [comment]
I think a user should always have total records of what they created to disagree with the authorities (admins, mods, remote incandescent) who remove them. In other words, if you are logged-in and the creator of content, you should see that your own content history is nor purged... even if attribute flags show such as "MOD_deleted", "ADMIN-deleted" appear.

**Comment by dessalines** [comment]
This is a UI consideration, the back-end already serves the full post in the `ModRemovePost` object.
