### ISSUE TITLE
[Bug]: Exclude bots from sorting algorithms

### ISSUE THREAD

**Issue by lionirdeadman** [LemmyNet/lemmy#3806]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Right now, if a bot posts a comment, this comment is treated as a normal comment in the sorting algorithms. 

This results in posts that attract or use bots like those for summaries and youtube link converters to bump up the ranking of posts.

I believe this is unwanted as it would not be a sign of activity.

### Steps to Reproduce

1. Trigger a bot to post a comment
2. See the post rise in the sorting algorithm

### Technical Details

N/A

### Version

0.18.2

### Lemmy Instance URL

beehaw.org

**Comment by dessalines** [comment]
Clicking hide bots in your user settings is the correct way to handle this.

**Comment by dullbananas** [comment]
The problem is that comments from bots count towards comment counts, which affects the post's position when using a sort type like Active

**Comment by dessalines** [comment]
I don't think there's any way around that, other than to prevent bots from making comments.

**Comment by dullbananas** [comment]
The solution would be a seperate "comments_excluding_bots" counter in post_aggregates
