### ISSUE TITLE
Notify the user when their post or comment is deleted

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3816]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When a user's post, or comment is deleted, it just vanishes, and they will have no idea that is gone unless they try to visit the post through their profile -- at which point the user will be greeted with either an error page saying that the post does not exist, or a blank page -- or they scroll through the modlog.

### Describe the solution you'd like.

At the moment that a moderator deletes a user's post, that user should be notified that the post is deleted. The message should be sent to the user's inbox along with the removal reason.

### Describe alternatives you've considered.

none

### Additional context

none

**Comment by aeharding** [comment]
Alternative:

## Post removal reasons

- A mod removing a post with a post removal reason simply adds a comment to the post. Then the user will get the comment reply notification like normal.
- This would also allow mods to omit the post removal reason for trolls
- This would also allow mods to easily specify *why* a post was removed which would prevent mod harassment from a user not understanding why their post was removed
- Related: #4186

**Comment by Nutomic** [comment]
Closing in favor of https://github.com/LemmyNet/lemmy/issues/4572
