### ISSUE TITLE
Change all `Option<bool>` to `bool` in DB list queries 

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#3819]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

In places like the `CommentQuery` and `PostQuery`, they take in a lot of `Option`s, but in the case of `bool`, it doesn't make much sense. 

This was likely done to match the API calls, because they also use `Option<bool>`, which is necessary in their case in order to not change DB columns.

### Describe the solution you'd like.

Change all the in-code `Option<bool>` to simple `bool` for the comment, post, and other list queries.

### Describe alternatives you've considered.

NA

### Additional context

#3787

**Comment by Nutomic** [comment]
Also https://github.com/LemmyNet/lemmy/issues/2904

**Comment by Freakazoid182** [comment]
Sounds like a good idea.

Some things that might be considered:

For API call objects, I do think there's a clear difference to be made between the different CRUD operations. 
Create and Read operations, it could make sense to make some generic deserialization logic to default to `false` if the `Option<bool>` parameter is not provided. This could prevent a lot of `.unwrap_or(false)` in many places.
For Update operations, providing no value for the `Option<bool>` indicates to not update the value. You already mentioned this in #2904. This will likely not be a candidate for any changes.
I'm not sure about Delete operations, but I think they might fall in the same bucket as Create and Read.

I think the actual "issue" here is that there's no clear convention at which point `Option<bool>` should be unwrapped. It seems a bit inconsistent across the code base. What I would suggest is to have the convention to unwrap at the first possible moment this can be done. Of course taking the CRUD operation context into account.

**Comment by Freakazoid182** [comment]
What about adding `#[serde(default = false)]` on the `Option<bool>` fields for API query structs? For Create, Read, and Delete operations. I think this will allow for a lot of `.unwrap_or(false)` calls.

**Comment by Freakazoid182** [comment]
Hope you don't mind me making a pull request. Was looking at what needed to be done and noticed I could get some changes in quickly.

**Comment by dessalines** [comment]
I went over these, and they're fine as is.
