### ISSUE TITLE
[Bug]: Comment without parent

### ISSUE THREAD

**Issue by leinardi** [LemmyNet/lemmy#3821]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

The comment `2158163` has `"path": "0.2158161.2158163"`, but there is no comment with ID `2158161` if you query the post comments: https://lemmy.ml/api/v3/comment/list?post_id=2671212&max_depth=8&sort=New&type_=All

What should a client do in this case? just discard the comment?

### Steps to Reproduce

1. Query https://lemmy.ml/api/v3/comment/list?post_id=2671212&max_depth=8&sort=New&type_=All
2. Search for `2158163` parent

### Technical Details

```json
{
"comment": {
"id": 2158163,
"creator_id": 1504491,
"post_id": 2671212,
"content": "Here is an alternative Piped link(s): https://piped.video/watch?v=H7HYVUjgQFY\n\nPiped is a privacy-respecting open-source alternative frontend to YouTube.\n\nI'm open-source, check me out at [GitHub](https://github.com/TeamPiped/lemmy-piped-link-bot).",
"removed": false,
"published": "2023-08-01T23:35:34.094796",
"deleted": false,
"ap_id": "https://feddit.rocks/comment/493132",
"local": false,
"path": "0.2158161.2158163",
"distinguished": false,
"language_id": 37
},
"creator": {
"id": 1504491,
"name": "PipedLinkBot",
"avatar": "https://feddit.rocks/pictrs/image/91e9f62c-4d89-4199-83e6-d0e371e7fe56.png",
"banned": false,
"published": "2023-07-08T22:56:43.809625",
"actor_id": "https://feddit.rocks/u/PipedLinkBot",
"bio": "I'm an open-source bot that comments Piped links when you post/comment a YouTube link.\n\nYou can find my source code at https://github.com/TeamPiped/lemmy-piped-link-bot\nI'm run by [@kavin@feddit.rocks](https://feddit.rocks/u/kavin) ",
"local": false,
"deleted": false,
"admin": false,
"bot_account": true,
"instance_id": 139028
},
"post": {
"id": 2671212,
"name": "Upcoming AMA with Lemmy's creators: Monday, 7 Aug, 1500 CEST",
"body": "This is an opportunity for any users, server admins, or interested third parties to ask anything they'd like to [@nutomic@lemmy.ml](https://lemmy.ml/u/nutomic) and I about Lemmy. This includes its development and future, as well as wider issues relevant to the social media landscape today.",
"creator_id": 34,
"community_id": 2,
"removed": false,
"locked": false,
"published": "2023-08-01T22:11:37.672054",
"updated": "2023-08-01T22:29:37.855797",
"deleted": false,
"nsfw": false,
"ap_id": "https://lemmy.ml/post/2671212",
"local": true,
"language_id": 37,
"featured_community": false,
"featured_local": true
},
"community": {
"id": 2,
"name": "announcements",
"title": "Announcements",
"description": "Official announcements from the Lemmy project. Subscribe to this community or add it to your RSS reader in order to be notified about new releases and important updates.\n\nYou can also find major news on [join-lemmy.org](https://join-lemmy.org/news)",
"removed": false,
"published": "2019-06-02T16:43:50.799554",
"updated": "2023-06-20T09:04:28.814065",
"deleted": false,
"nsfw": false,
"actor_id": "https://lemmy.ml/c/announcements",
"local": true,
"icon": "https://lemmy.ml/pictrs/image/waqyZwLAy4.webp",
"hidden": false,
"posting_restricted_to_mods": true,
"instance_id": 394
},
"counts": {
"id": 1904663,
"comment_id": 2158163,
"score": 17,
"upvotes": 17,
"downvotes": 0,
"published": "2023-08-01T23:35:34.094796",
"child_count": 0,
"hot_rank": 6
},
"creator_banned_from_community": false,
"subscribed": "NotSubscribed",
"saved": false,
"creator_blocked": false
}
```

### Version

BE: 0.18.3

### Lemmy Instance URL

lemmy.ml

**Comment by RocketDerp** [comment]
This is similar to https://github.com/LemmyNet/lemmy/issues/3741 in that we don't have the steps outline how to reproduce this. Any idea? Just a mod-removal or admin-delete? 

I have a replicated copy of that community, so maybe I can query the comment table for that ap_id and see if it was deleted/removed to try and reverse-engineer what happened - but if the missing parent comment came from another instance, that won't work.

**Comment by leinardi** [comment]
> This is similar to https://github.com/LemmyNet/lemmy/issues/3741 in that we don't have the steps outlined how to reproduce this. Any idea? Just a mod-removal or admin-delete?

Unfortunately I have no idea how to reproduce it, I'm just working on a client for lemmy and noticed this issue while fetching the comments of some random post...
