### ISSUE TITLE
[Bug]: Replies to threads are set to "public" when followed from Mastodon / Pleroma / etc.

### ISSUE THREAD

**Issue by csolisr** [LemmyNet/lemmy#3822]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Following a Lemmy community from an ActivityPub microblogging server such as Mastodon, Pleroma, or Misskey, sets the server to repost all messages sent to the community (whether original threads or their replies) as separate posts. However, both the threads and the replies to these have their ActivityPub privacy set to "public", instead of "unlisted". This means that on the home page, if you follow a Lemmy community, it will not only display the thread but also each individual reply in reverse chronological order. This generally pollutes the home page with more messages than required. While the main posts should remain with privacy set to "public", replies should be set to "unlisted" instead.

### Steps to Reproduce

1. Log into your Mastodon account. 
2. Copy the URL of a Lemmy community in the Mastodon search bar, and then go to the "People" or "Users" tab.
3. Click on the user that will appear, and click on "Follow".
4. Wait a few minutes, then return to your home page.

### Technical Details

N/A for the moment

### Version

BE 0.18.2

### Lemmy Instance URL

communities.azkware.net et al.

**Comment by Nutomic** [comment]
This is expected behaviour because Lemmy doesnt support "unlisted".
