### ISSUE TITLE
option to enable .torrent file uploads in posts\comments

### ISSUE THREAD

**Issue by slrgt** [LemmyNet/lemmy#3824]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Sometimes people want to share custom linux ISOs and magnet links don't always work for everyone

### Describe the solution you'd like.

it would be great if instances could enable the option to allow .torrent uploads to post and comments

### Describe alternatives you've considered.

.

**Comment by dessalines** [comment]
We had a bug that didn't allow the `magnet:` URL scheme in post urls, but I just fixed that with #4092 . Should be in the next release.

There's nothing preventing magnet links in comments.
