### ISSUE TITLE
Only list acceptable languages when composing a comment or a post

### ISSUE THREAD

**Issue by bleistift-zwei** [LemmyNet/lemmy#3826]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When composing a post or a comment to a post, we get to select the language we’re writing in. This list seems to be populated from the “languages” setting in one’s profile.

However, the community (or instance; I’m not sure) might have a different list of “acceptable” languages. The API seems to refuse posts that are written in an inacceptable language. At least that’s how I interpret this request/response pair:

```
POST https://feddit.de/api/v3/comment
{
  "content":"> The arts, sciences, research **and education** are free.\n\nArticle 5, paragraph 3, sentence 1 of the German constitution. Every article I read about Florida makes me appreciate that more.",
  "post_id":2205236,
  "language_id":37, // English
  "form_id":"markdown-form-XupRXfLQ9YTiYnQUH9dM",
  "auth":"REDACTED"
}
```

```
400 Bad Request
{ error: "language_not_allowed" }
```

### Describe the solution you'd like.

The error can be completely avoided by only showing languages that are actually available in the community.

### Describe alternatives you've considered.

It might be sensible to show only the intersection of languages allowed by the community and the languages selected by the user. However, while one might not be interested in post in, say, Portugese, one may still want to comment in Portugese. This would not be possible with this proposition.

Another downside is that the intersection might actually be empty, leaving the user without any possibility to compose a comment.

### Additional context

This issue is similar to #3451, but not quite. #3451 has a fix when the comment language is set to “undefined”, but not when it is explicitly set to an unsupported language (if I understand the PR correctly).

I am not sure if this issue might also affect posts (instead of comments).

**Comment by Nutomic** [comment]
This belongs in lemmy-ui and there are already various similar issues.
