### ISSUE TITLE
[DOES NOT COMPILE] Main branch does not compile due to missing view

### ISSUE THREAD

**Issue by NinekoTheCat** [LemmyNet/lemmy#3831]
I've noticed that all the pull requests fail CI and after downloading the project to my own computer it also fails to compile.

I don't know how you expect people to develop something they can't test.

**Comment by RocketDerp** [comment]
confirmed.  I saw a fix for it on a not yet merged pull request: https://github.com/LemmyNet/lemmy/pull/3823/files

![image](https://github.com/LemmyNet/lemmy/assets/113625597/0c08af38-a15a-4c63-92a0-631adc22a12e)

**Comment by NinekoTheCat** [comment]
> confirmed. I saw a fix for it on a not yet merged pull request: https://github.com/LemmyNet/lemmy/pull/3823/files
> 
> ![image](https://user-images.githubusercontent.com/113625597/258649776-0c08af38-a15a-4c63-92a0-631adc22a12e.png)

Well apparently they don't work in the weekends, next time please compile pull req before merging.
