### ISSUE TITLE
Ability to Limit Visibility of a Post to the Current Instance/Community

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3833]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?
Yes, the proposal is related to the problem of wanting to create a poll but only wanting to know the opinions of the people in a specific community or instance. Currently, in Lemmy, there is no option to limit the visibility of a post to a specific community or instance.

### Describe the solution you'd like.
I would like to propose the addition of a feature in Lemmy that allows users to limit the visibility of a post to the current instance or community. This would be useful when creating polls or seeking opinions on a specific topic within a restricted group. By selecting this option, the post would only be visible to members of the current instance or community, ensuring that the responses and discussions are limited to the intended audience.

### Describe alternatives you've considered.
As an alternative to limiting the visibility of a post to the current instance or community, another option could be to implement a toggle feature that allows users to see only votes and comments from users within the local instance. This would provide a way to filter the responses and discussions to only those coming from the local community, without restricting the visibility of the post itself.

### Additional context
This feature would enhance the functionality of Lemmy by providing users with more control over the visibility of their posts. It would allow for more targeted discussions and polls within specific communities or instances, ensuring that the opinions and feedback received are relevant and meaningful.

**Comment by Nutomic** [comment]
duplicate
