### ISSUE TITLE
don't remember the email I signed up with, do remember the username, forgot password

### ISSUE THREAD

**Issue by unusualevent** [LemmyNet/lemmy#3836]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The reset password flow requires an email. I don't remember which one I used.

### Describe the solution you'd like.

Lookup either by email or username, send email.

### Describe alternatives you've considered.

Asking the admin, but there's no admin contact or instance details listed in lemmy.ml. There's no "about this instance" code or anything about how to get support besides the sidebar :/ 

### Additional context

I had originally gone "huh, my password manager doesn't have my lemmy username, I never saved it but I figure the password reset will work fine", then hit sign out, and turns out I need to remember the email I used? that's a pretty standard thing for forgetful people to have forgotten :)

**Comment by Jaoheah** [comment]
Have you tried looking through all of your email accounts, and using the search bar for emails containing the words `Lemmy`? It should be from the email account `noreply@lemmy.ml`. With most modern email providers you can just copy and paste `from: "noreply@lemmy.ml"` into the search bar and it should only show emails from that email account.

**Comment by unusualevent** [comment]
yes (one of the first things I tried), it was created back in february and is no longer in the trash, yet I still control the email addresses I would have used (the whole domain for one, and +nickname addressing for gmail).

**Comment by Jaoheah** [comment]
> yes (one of the first things I tried), it was created back in february and is no longer in the trash, yet I still control the email addresses I would have used (the whole domain for one, and +nickname addressing for gmail).

Ah, have you already tried entering every single email you have into the password reset?

**Comment by unusualevent** [comment]
> Ah, have you already tried entering every single email you have into the password reset?

...out of any possible {foobar}@domain.com email or every possible user+{foobar}@gmail.com email it could have been??

that's an impossible task... I've guessed what I could.

**Comment by Jaoheah** [comment]
> > Ah, have you already tried entering every single email you have into the password reset?
> 
> ...out of any possible {foobar}@domain.com email or every possible user+{foobar}@gmail.com email it could have been??
> 
> that's an impossible task... I've guessed what I could.

I meant the emails you own. Other than that, I am unsure of what you could do.

**Comment by Jaoheah** [comment]
> > Ah, have you already tried entering every single email you have into the password reset?
> 
> ...out of any possible {foobar}@domain.com email or every possible user+{foobar}@gmail.com email it could have been??
> 
> that's an impossible task... I've guessed what I could.

Contact @happydooby:matrix.org on Matrix. They are an admin of lemmy.ml They might be able to help.

**Comment by Jaoheah** [comment]
> I own all of a domain, and could have used any alias in gmail, but I take your point.
> 
> I guess the only other option is if the admin checks the SQL database for the email and manually tells me or sends the reset info via email.
> 
> not really a way to contact the admin, though.

```@happydooby:matrix.org``` is the Matrix account of one of the lemmy.ml admins according to their profile page

**Comment by Nutomic** [comment]
Password reset with username alone can easily be abused, not a good idea to allow that. I suggest you simply create a new account.
