### ISSUE TITLE
Better federation for Peertube content

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3837]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently it seems that Peertube federation is rather lacking -- comments, and likes do not appear to be federated, and the videos only show up as links instead of watchable videos from Lemmy.

### Describe the solution you'd like.

I propose that better federation support for Peertube content to be added so that likes, and comments are properly federated, and that you can watch peertube content from within Lemmy. An example of the current state of federation can be seen [here](https://lemmy.world/c/techlore@neat.tube).

### Describe alternatives you've considered.

none

### Additional context

The videos themselves being viewable from within lemmy may be a duplicate of #2318

**Comment by Nutomic** [comment]
Lemmy federates according to [FEP-1b12](https://codeberg.org/fediverse/fep/src/branch/main/fep/1b12/fep-1b12.md), so Peertube would be responsible to forwarding votes and comments to followers. Maybe its not implemented on their side.

**Comment by K4LCIFER** [comment]
> Lemmy federates according to [FEP-1b12](https://codeberg.org/fediverse/fep/src/branch/main/fep/1b12/fep-1b12.md), so Peertube would be responsible to forwarding votes and comments to followers. Maybe its not implemented on their side.

It's not only comments, and likes, though -- that user's videos only show up as links. [This PeerTube user](https://lemm.ee/u/thelinuxexperiment@tilvids.com) seem's to have playable videos, but they also suffer from no federated likes, or comments.

**Comment by paulo-roger** [comment]
Hola @Nutomic,

Regarding showing the Peertube videos embeded on lemmy topic, is it possible?

**Comment by Nutomic** [comment]
Embeds are currently broken in lemmy-ui. The backend correctly populates `post.embed_video_url` ([example](https://lemm.ee/post/18500178)), but for some reason lemmy-ui doesnt show that.

**Comment by paulo-roger** [comment]
> Embeds are currently broken in lemmy-ui. The backend correctly populates `post.embed_video_url` ([example](https://lemm.ee/post/18500178)), but for some reason lemmy-ui doesnt show that.

It worked perfect on my end! Amazing! Thanks for your work!

**Comment by Chocobozzz** [comment]
> Lemmy federates according to [FEP-1b12](https://codeberg.org/fediverse/fep/src/branch/main/fep/1b12/fep-1b12.md), so Peertube would be responsible to forwarding votes and comments to followers. Maybe its not implemented on their side.

PeerTube channels are `Group` because we plan in the future to have multiple accounts that can manage a channel. But they are not a forum, so we don't accept likes/notes. However I'm not against forwarding these activities if it can help Lemmy use cases.

Don't hesitate to create an issue on https://github.com/Chocobozzz/PeerTube so we can discuss about this :)

**Comment by paulo-roger** [comment]
@Chocobozzz I will create the issue, thanks! We talked in mastodon briefly, I was at grandma for christmas and away from my computer.

**Comment by Nutomic** [comment]
> PeerTube channels are Group because we plan in the future to have multiple accounts that can manage a channel. But they are not a forum, so we don't accept likes/notes. However I'm not against forwarding these activities if it can help Lemmy use cases.

@Chocobozzz One problem is that Lemmy doesnt know that other users arent allowed to create posts (videos) in the Peertube channel. Lemmy has a custom federation attribute `postingRestrictedToMods` which has the same effect, you can see it on [this group](https://lemmy.ml/c/announcements). If Peertube can set the same or similar attribute for its groups, then we can disable posting from Lemmy.

For comments and votes, its like FEP-1b12 describes, the group should `Announce` them to its followers. So it would be great if Peertube groups could do the same (or does Peertube have any existing mechanism for that?)

**Comment by K4LCIFER** [comment]
> This seems to be resolved from our side.

Hmm, it may be completely broken now, as Lemmy.ml doesn't seem to be pulling anything new into [this PeerTube channel](https://lemmy.ml/c/thelinuxexperiment_channel@tilvids.com?dataType=Post&sort=New) (newest is about 9 months old), the same thing is [on SJW](https://tesh.itjust.works/c/thelinuxexperiment_channel@tilvids.com) (newest is around 8 months ago). Yet, [on Peertube](https://tilvids.com/c/thelinuxexperiment_channel/videos?s=1) the newest is from 2 days ago.

**Comment by K4LCIFER** [comment]
Hm, it still appears to be broken. I've done some tests with a few different Peertube channels on Lemmy, and they still haven't been able to sync with Lemmy. I've tried re-subscribing to them, I've tried re-syncing them with the channel link, but Lemmy still doesn't seem to be pulling in any new Peertube content.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/5509 fixes this, it will be released as part of Lemmy 1.0
