### ISSUE TITLE
Users @ as webdomain while server accessed through subdomain

### ISSUE THREAD

**Issue by slrgt** [LemmyNet/lemmy#3840]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The ability for servers to be hosted on a subdomain while the users @ to be the web domain would be really useful. So for example your lemmy server would be on lemmy.example.com and your usernames would be user@example.com

### Describe the solution you'd like.

Its possible on mastodon like this: https://docs.joinmastodon.org/admin/config/#web_domain

### Describe alternatives you've considered.

.

**Comment by Die4Ever** [comment]
What happens if the server hosts Lemmy and Mastodon, and maybe other Fediverse servers too, on the same domain with different subdomains? I also think this just makes things more confusing instead of less confusing

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/issues/3400
