### ISSUE TITLE
Allow moderators to feature a comment and pin it to the top of a post's comments

### ISSUE THREAD

**Issue by kaiser1245** [LemmyNet/lemmy#3843]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

On some potentially contentious posts, users need a visible reminder of rules or codes of conduct. Or, if some action has been taken on a comment thread, moderators may want to inform users of that action. Additionally, some communities have different discussion rules or guidelines that users from outside that community, or users from other instances, may need to be reminded of.

### Describe the solution you'd like.

Allowing moderators to feature a top level comment, pinning it to the top of a post's comment section.

### Describe alternatives you've considered.

Moderators can create comments like this currently (and distinguish them) but they may sink to the bottom of a comment section if others are more highly upvoted.

**Comment by RustoMCSpit** [comment]
OP should be ablr to pin comments too

**Comment by lionirdeadman** [comment]
> Frontends can auto-top distinguished comments, no?

Yes but that would be breaking behaviour. This is not expected behaviour.

**Comment by AppleSheeple** [comment]
> Yes but that would be breaking behaviour.

I meant to say, it can be a client option.

But even if it's not an option, I don't understand how it would "*break*" anything.
It's just sorting and representation.

> This is not expected behaviour.

Arguable.

-----

But on a second thought. This may not be workable client-side as of today if a thread has a huge number of comments, unless all top-level ones are fetched. It can still be implemented as a client-side option with the added support of filtering on distinguished in `/comment/list` API calls, which could be a worthwhile addition on its own, independent of this feature request.

**Comment by lionirdeadman** [comment]
> I meant to say, it can be a client option.

If it's a client option then people can ignore pinned comments which is harmful if used for moderation purposes.

> Arguable

This currently doesn't happen so I doubt people are expecting this behaviour.

---

That's true that comments will not necessarily be grabbed at the moment because of the restricted API. It's also worth mentioning that this feature can't be supported for people to pin if we link it to the distinguish feature.

**Comment by Nutomic** [comment]
The best way to solve this is by returning distinguished comments first in list comment api responses. In fact thats how it should have been implemented from the beginning. The way to do this is to change [comment_view.rs](https://github.com/LemmyNet/lemmy/blob/main/crates/db_views/src/comment_view.rs) to sort distinguished comments first. You can more or less copy the code from the way `featured_community` is used in [post_view.rs](https://github.com/LemmyNet/lemmy/blob/main/crates/db_views/src/post_view.rs).
