### ISSUE TITLE
search bar for comments

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/lemmy#3844]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

.

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

**Comment by lionirdeadman** [comment]
Please explain your enhancement request

**Comment by RustoMCSpit** [comment]
the functionality for a search bar in comment section,

**Comment by RustoMCSpit** [comment]
@Nutomic why was this closed?

**Comment by Nutomic** [comment]
Because you didnt provide any information.
