### ISSUE TITLE
[Bug]: PostgreSQL performance. Editing a Lemmy comment results in expensive SQL transaction to update child_count on comment_aggregates

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3845]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I am working on the scaling issues of Lemmy's PostgreSQL usage on very active comment threads of a posting.

I discovered by accident when analyzing the raw SQL query in https://github.com/LemmyNet/lemmy/blob/91c024fd987b61ac8892b9e7d1896ee4574751da/crates/db_schema/src/impls/comment.rs#L62 that this code actually runs each time a Lemmy comment is edited on incoming federation.

I am struggling with Rust logic how to detect if the SQL transaction was an INSERT or UPDATE to skip the follow-up path update. I asked for Rust help in this Lemmy posting: https://lemmy.ml/post/2982925

The path of a comment does not change any of the placement in the comment reply chains, so there is no need to run the logic when it is an SQL UPDATE to an already-known comment row in PostgreSQL.

### Steps to Reproduce

1. Capture PostgreSQL SQL activity on instance server that is subscribed to community on another instance
2. A remote federated comment is edited multiple times
3. Observe that edits that do not change the path result in a mass update to child_count on comment_aggregates table related to path

### Technical Details

May only happen on federated incoming, did not validate with locally created comments.

NOTE: this is related to server overloading problems with Lemmy in the wild systems once a large number of comments are in the system.

### Version

BE: 0.18.3

### Lemmy Instance URL

all

**Comment by Nutomic** [comment]
Those are just two simple update queries which dont seem to cause any problems in production. At least they dont show up anywhere among the list of longest queries.
