### ISSUE TITLE
implement polling mechanic

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/lemmy#3847]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

.

### Describe the solution you'd like.

also have different sorts of voting, first past the post, instant run-off, etc.

### Describe alternatives you've considered.

.

**Comment by lionirdeadman** [comment]
Closing as duplicate
