### ISSUE TITLE
Re federate to instance when their domain name changes

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#3856]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The FHMY instance lost their domain (fmhy.ml) recently and therefore had to get a new domain name. They did not lose their data. However, this broke the federation between other instances.

- You can still access lemmy.fmhy.ml communities and posts on other instances such as lemmy.world even though lemmy.fmhy.ml is completely offline
- Even if FMHY used the data they had from lemmy.fmhy.ml in their new domain name lemmy.fmhy.net, it will just duplicate/fork the communities and posts from on other instances.

### Describe the solution you'd like.

I think a good solution to solving this is to have each instance generate a public/private key pair, and when two instances federate, they will share public keys. If a instances goes offline and reappears again under a new domain name, it will know it is the same domain name due to the public key pair and re federate by changing the domain name on every community and post made with that instance.

### Describe alternatives you've considered.

Instances can manually re federate by changing the domain name of federated communities and posts

### Additional context

Similar Github issues
https://github.com/LemmyNet/lemmy/issues/3690

**Comment by dessalines** [comment]
You'll have to follow the process here, then re-federate. 

https://join-lemmy.org/docs/administration/backup_and_restore.html?highlight=changing#changing-your-domain-name

There's no way for us to connect to a new instance we don't know about.
