### ISSUE TITLE
Organizing Saved Posts and Comments

### ISSUE THREAD

**Issue by wason-sonico** [LemmyNet/lemmy#3859]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Lemmy has the ability to save posts and comments but there is now way to organize them so they are easier to find and navigate.

### Describe the solution you'd like.

Please add the following:

1. Add either Tags or Categories and let users create their own Tags or Categories.
2. Saved Posts and Comments will be added by the user to a Tag o Category.
3. Implement a filter in the Saved section, to filter by Tag or Category.

Thanks!

### Describe alternatives you've considered.

An alternative would be to use "folders" but that might be difficult to navigate.

### Additional context

I'll create another issue on lemmy-ui and link it here. I understand this issue is for the Lemmy "backend" server software.

**Comment by wason-sonico** [comment]
Lemmy UI issue: https://github.com/LemmyNet/lemmy-ui/issues/2052

**Comment by dessalines** [comment]
I don't see us having the time to do this. I can re-open this if someone wants to take it on tho.
