### ISSUE TITLE
[Bug]: Federation Errors

### ISSUE THREAD

**Issue by DarkArc** [LemmyNet/lemmy#3862]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Lots of instances of "data did not match any variant of untagged enum PageOrNote"

### Steps to Reproduce

Create a fresh instance of lemmy installed via docker (and federate with several servers?). 

Really, this is just happening all over the place, and I'm not seeing many federated votes.

### Technical Details

```
2023-08-10T04:36:23.137184Z  WARN lemmy_server::root_span_builder: data did not match any variant of untagged enum PageOrNote
   0: lemmy_apub::activities::voting::vote::verify
             at crates/apub/src/activities/voting/vote.rs:57
   1: lemmy_apub::activities::community::announce::receive
             at crates/apub/src/activities/community/announce.rs:144
   2: lemmy_server::root_span_builder::HTTP request
           with http.method=POST http.scheme="http" http.host=social.packetloss.gg http.target=/inbox otel.kind="server" request_id=<UUID>
             at src/root_span_builder.rs:16
LemmyError { message: None, inner: data did not match any variant of untagged enum PageOrNote, context: SpanTrace [{ target: "lemmy_apub::activities::voting::vote", name: "verify", file: "crates/apub/src/activities/voting/vote.rs", line: 57 }, { target: "lemmy_apub::activities::community::announce", name: "receive", file: "crates/apub/src/activities/community/announce.rs", line: 144 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=social.packetloss.gg http.target=/inbox otel.kind=\"server\" request_id=806571e2-6faf-4c34-9747-43b7e8333770", file: "src/root_span_builder.rs", line: 16 }] }
```

and:

```
2023-08-10T04:40:21.362015Z  WARN lemmy_server::root_span_builder: data did not match any variant of untagged enum PageOrNote
   0: lemmy_apub::objects::comment::verify
             at crates/apub/src/objects/comment.rs:127
   1: lemmy_apub::fetcher::post_or_comment::verify
             at crates/apub/src/fetcher/post_or_comment.rs:68
   2: lemmy_apub::activities::voting::vote::verify
             at crates/apub/src/activities/voting/vote.rs:57
   3: lemmy_apub::activities::community::announce::receive
             at crates/apub/src/activities/community/announce.rs:144
   4: lemmy_server::root_span_builder::HTTP request
           with http.method=POST http.scheme="http" http.host=social.packetloss.gg http.target=/inbox otel.kind="server" request_id=<UUID>
             at src/root_span_builder.rs:16
LemmyError { message: None, inner: data did not match any variant of untagged enum PageOrNote, context: SpanTrace [{ target: "lemmy_apub::objects::comment", name: "verify", file: "crates/apub/src/objects/comment.rs", line: 127 }, { target: "lemmy_apub::fetcher::post_or_comment", name: "verify", file: "crates/apub/src/fetcher/post_or_comment.rs", line: 68 }, { target: "lemmy_apub::activities::voting::vote", name: "verify", file: "crates/apub/src/activities/voting/vote.rs", line: 57 }, { target: "lemmy_apub::activities::community::announce", name: "receive", file: "crates/apub/src/activities/community/announce.rs", line: 144 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=social.packetloss.gg http.target=/inbox otel.kind=\"server\" request_id=4fea8b91-b6a5-4988-8c43-fbca8ec9380c", file: "src/root_span_builder.rs", line: 16 }] }
```

### Version

dessalines/lemmy:0.18.4

### Lemmy Instance URL

social.packetloss.gg

**Comment by isFakeAccount** [comment]
I have the same error. The comments are also not syncing.

**Comment by nullish-cat** [comment]
Also getting this error at lemmy.fmhy.net. Federation is dodgy, some posts are federating while others are not. Comments don't seem to federate at all. 

Main example: https://lemmy.fmhy.net/c/singularityai has 275 posts while https://lemmy.dbzer0.com/c/singularityai@lemmy.fmhy.net has 51 and https://lemmy.world/c/singularityai@lemmy.fmhy.net has...uh...nothing.

**Comment by Nutomic** [comment]
Are you federating with any other platforms besides Lemmy, such as Mastodon? In that case its expected that some activities wont federate as some of it is incompatible. For more details I need the url of such rejected activities, should be in the logs shortly before the error messages.

**Comment by Tmpod** [comment]
I'm getting a lot of these (specially the `expected value at line 2 column 5` ones) coming from lemmy.world.

**Comment by BentiGorlich** [comment]
FYI your errors have to do with mastodon, just a hint that mastodon is using an array as the `object` in activities of type `flag` (in reports)

> data did not match any variant of untagged enum AnnouncableActivities.

Is the exact error when I adjusted the json I sent to Lemmy to use the Mastodon format

**Comment by Nutomic** [comment]
Lemmy 0.19 has better errors for this, it now includes the id of the failing activity for debugging. Maybe we should also change these log messages to info or debug level.
