### ISSUE TITLE
[Bug]: Your own comment/reply on a post counts as unread comment towards that post

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#3863]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

 Your own comment/reply on a post counts as unread comment towards that post

### Steps to Reproduce

1. open a post
2. make a comment
3. do a action that shows the unread comments
4. It increased by one

https://github.com/LemmyNet/lemmy/assets/67873169/c7c6056a-06c7-4cb3-9eb3-a48946ac0679

### Technical Details

N/A

### Version

0.18.4

### Lemmy Instance URL

lemmy.ml

**Comment by dessalines** [comment]
Shouldn't be too difficult to fix.
