### ISSUE TITLE
Marking controversial communities or instances as sensitive to limit default visibility as an alternative to defederation

### ISSUE THREAD

**Issue by N1N74** [LemmyNet/lemmy#3868]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

To avoid toxic escalation of comments, an instance admin may be incentivized to defederate from other instances where such clashes between their own members and others are likely. This can make it harder for people preferring minimum obstacles to access the fediverse to decide on a homeserver. An alternative to defederation can help in this regard. This will also result in faster adoption of Lemmy.

### Describe the solution you'd like.

Ability to mark communities or other instances as sensitive or controversial by instance admins. An instance marked as sensitive should mean all its communities and users are considered sensitive.

Suggested working:
- [ ] By default, it should hide posts in the feed unless the user selects to show/follows sensitive communities. Blurring of posts instead can also be in an option. 
- [ ] Default option automatically collapses comments from sensitive instances.
- [ ] Custom messages set by admins can be displayed before user comments or posts, involving sensitive users/community. Helps in providing context and advice. Custom message when opening such posts/communities can also be very helpful to provide context to new users.
- [ ] Avoid incrementing inbox counter for such interactions.

### Describe alternatives you've considered.

The proposed solution is an alternative to defederation.

Similar discussions: 
Linked with restrictions: #3255
Safe spaces and locking: #3275
(+A custom warning before commenting or opening posts can help if lemmy decides to implement ideas similar to these in future.)

### Additional context

These measures will discourage the users from engaging in toxicity and also give opportunity to the instance admins to have an open approach while keeping their users informed about the issues and concerns admins have to deal with.

Related issues: #1424, #2397, #3160, #3546, #3833

**Comment by RocketDerp** [comment]
I'm working on a Multi-Community feature, like Multi-Reddit, and I'm running into wanting to add attributes to the community objects along these same lines.

The biggest programming concern I have is how federation works with "Community" objects. I've not seen any recent changes to Lemmy to add new attributes. If anyone can chime in with how to go about adding a new attribute that gets federated outbound, please help. Does a community object get shared outside of Lemmy to Lemmy? Ideas on how to deal with older versions of Lemmy that wouldn't know about the added attribute? As we may have a Lemmy 0.18.4 server talking to a 0.19 server and edits/etc by mods could create conflicts. Thank you.

**Comment by RocketDerp** [comment]
ok, so I overlooked that fresh development is underway to add a new attribute to community! https://github.com/LemmyNet/lemmy/pull/3889

**Comment by Die4Ever** [comment]
This sounds good. I think ideally defederation should only be used for legal issues or technical issues (errors, malicious attacks). Everything else should be handled in a different way, like this, where the instance admins have default ban-lists for instances/communities/users, and the users can choose to stick to the default ban lists or manually tune them.

**Comment by Nutomic** [comment]
You can already do this on a per community basis using /api/v3/community/hide. Only problem is that no one has implemented it in lemmy-ui yet, but you can easily call it from a script.
