### ISSUE TITLE
Proper Translation Tool

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#387]
This approach of using pull requests for translations is not going to scale once the project gets bigger. Besides, translation tools have some extra features that make this task easier, compared to editing some raw text file.

One project I found for this is [Weblate](https://weblate.org/). While I don't have any experience with it, it looks like a good fit. For now we can use the official instance, but later we can always switch to a self-hosted one, and the project is open source.

**Comment by Nutomic** [comment]
Okay I setup a weblate instance at https://weblate.yerbamate.dev. First problem is that the format of our translation files is not supported as far as I see, can we change that to a supported format? Something like [json format](https://docs.weblate.org/en/weblate-3.11/formats.html#json-files) or [i18next](https://docs.weblate.org/en/weblate-3.11/formats.html#json-i18next-files). Alternatively we could add support for our format to Weblate, but I'm sure that would be a lot more work.

I'm also not sure how to handle signups on Weblate, apparently it doesnt have any support for captchas or other options to prevent automated signups. And I need to fix some things like sending emails.

**Comment by dessalines** [comment]
The typescript files are using the official i18next json format: https://www.i18next.com/misc/json-format. 

You might have to go from js <-> typescript but that's a one-liner, i think `JSON.stringify(...`

**Comment by dessalines** [comment]
This is done.
