### ISSUE TITLE
[Bug]: Federation to/from kbin has issues

### ISSUE THREAD

**Issue by M-Reimer** [LemmyNet/lemmy#3876]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I don't know where federation fails here, but as user, I see it while using lemmy, so I report here and hope someone can give more insight into the issue.

Yesterday (12-08-2023) I posted an announcement to a kbin magazine from lemmy.ml. I posted it first and then added some more information by editing it: https://lemmy.ml/post/3230375

This seems to have arrived at kbin.social but my edit did not make it to this day: https://kbin.social/m/leagueoflinux/t/334112/wine-lol-PKGBUILDs-updated-to-version-p8-12

But after checking with my lemmy.world account, I noticed that my post never arrived there even one day after creating the post:
https://lemmy.world/c/leagueoflinux@kbin.social?dataType=Post&page=1&sort=New

I also checked with other instances and the transfer from kbin back to lemmy failed.

### Steps to Reproduce

1. Post from lemmy to a kbin.social magazine
2. The post never makes it to other lemmy instances

I did not test what happens if a post is directly created on kbin.social as I don't have an account there.

### Technical Details

None. I don't run the instance.

### Version

BE: 0.18.4

### Lemmy Instance URL

lemmy.ml

**Comment by Nutomic** [comment]
This sounds like KBin fails to forward the post to magazine followers. Have you asked on their side about this?

**Comment by M-Reimer** [comment]
No, sorry but I don't even have an account for kbin.

**Comment by Nutomic** [comment]
You need to open an issue in their repo, I dont think there is any problem on our side.
