### ISSUE TITLE
Lemmy 0.18.4 PostgreSQL, INSERT of every new Lemmy comment immediately executes 3 separate UPDATE statements to post_aggregates for the same single row

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3877]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Lemmy's PostgreSQL backend is having overloads and needs performance optimization. The comment table is at the heart of the site and one of the largest database tables.

Current TRIGGER function in 0.18.4 executes 3 independent UPDATE interactions (1 of which changes no rows) to the same post_aggregate row when a comment is INSERT:

```
CREATE FUNCTION public.post_aggregates_comment_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Check for post existence - it may not exist anymore
    IF TG_OP = 'INSERT' OR EXISTS (
        SELECT
            1
        FROM
            post p
        WHERE
            p.id = OLD.post_id) THEN
        IF (was_restored_or_created (TG_OP, OLD, NEW)) THEN
            UPDATE
                post_aggregates pa
            SET
                comments = comments + 1
            WHERE
                pa.post_id = NEW.post_id;
        ELSIF (was_removed_or_deleted (TG_OP, OLD, NEW)) THEN
            UPDATE
                post_aggregates pa
            SET
                comments = comments - 1
            WHERE
                pa.post_id = OLD.post_id;
        END IF;
    END IF;
    IF TG_OP = 'INSERT' THEN
        UPDATE
            post_aggregates pa
        SET
            newest_comment_time = NEW.published
        WHERE
            pa.post_id = NEW.post_id;
        -- A 2 day necro-bump limit
        UPDATE
            post_aggregates pa
        SET
            newest_comment_time_necro = NEW.published
        FROM
            post p
        WHERE
            pa.post_id = p.id
            AND pa.post_id = NEW.post_id
            -- Fix issue with being able to necro-bump your own post
            AND NEW.creator_id != p.creator_id
            AND pa.published > ('now'::timestamp - '2 days'::interval);
    END IF;
    RETURN NULL;
END
$$;

```

### Describe the solution you'd like.

Consolidate this into one single UPDATE statement, cutting PostgreSQL WAL activity and dead tuples

### Describe alternatives you've considered.

A more difficult logic to do aggregates in a more holistic approach.

### Additional context

PostgreSQL keeps all the row versions in the table data structure. It means an UPDATE query keeps the existing row version (a.k.a. dead tuple) and creates a new version with updated data. This cruft slows down SELECT performance due to multiple updates.

The 'SELECT
            1
        FROM
            post p
        WHERE
            p.id = OLD.post_id)' logic can likely be made a WHERE clause of the UPDATE.
            
In testing, each of these UPDATES for every comment INSERT, 13,159 comment INSERT operations in this particular data sample, pg_stat_statements output:

![image](https://github.com/LemmyNet/lemmy/assets/113625597/17869bc4-5c27-4803-b3ff-5c64b3fc3104)

For the 13,159 new comment INSERT, the first column is times statement is executed, 2nd column is count of rows actually updated, third column is average mean ms of execution time by PostgreSQL, final column is the SQL statement.  As you can see, on new INSERT of a comment, one of the statements always updates zero rows and still takes 0.7 ms to execute. This was on a high-performance testing system where 13,159 was all the rows en the entire Lemmy instance - real-world servers would be even slower on each of these UPDATE executions.

**Comment by RocketDerp** [comment]
First attempt at rewrite, tested only in INSERT situation, needs to be tested with UPDATE of existing comment:

```
/*
PostgreSQL read of row carries far less overhead than an UPDATE to a row.
*/
CREATE OR REPLACE FUNCTION public.post_aggregates_comment_count() RETURNS trigger
    LANGUAGE plpgsql
    AS
$$
    DECLARE
        prev_post_aggregate RECORD; -- previous post aggregate record
        executed_update boolean DEFAULT FALSE;

BEGIN

    IF TG_OP = 'INSERT' THEN
        -- assumption made that every new comment has an already existing post_aggregates row to reference
        -- LIMIT 1 used to satisfy PostgreSQL function, but there should never be duplicates for same post_id
        SELECT * INTO prev_post_aggregate FROM post_aggregates WHERE post_id = NEW.post_id LIMIT 1;    

        -- A 2 day necro-bump limit
        IF prev_post_aggregate.published > ('now'::timestamp - '2 days'::interval) THEN
            -- Fix issue with being able to necro-bump your own post
			IF NEW.creator_id != prev_post_aggregate.creator_id THEN
				UPDATE
					post_aggregates pa
				SET
					newest_comment_time = NEW.published,
					comments = comments + 1,
					newest_comment_time_necro = NEW.published
				WHERE
					pa.post_id = NEW.post_id;
					
				executed_update := TRUE;
			END IF;
        END IF;
        
        IF NOT executed_update THEN
            UPDATE
				post_aggregates pa
			SET
				newest_comment_time = NEW.published,
				comments = comments + 1
			WHERE
				pa.post_id = NEW.post_id;
		END IF;

    -- ELSE not an INSERT
	ELSIF EXISTS (
	    -- If not INSERT, Check for post existence - it may not exist anymore
		SELECT
			1
		FROM
			post p
		WHERE
			p.id = OLD.post_id
		)
		THEN
			IF (was_restored_or_created (TG_OP, OLD, NEW)) THEN
				UPDATE
					post_aggregates pa
				SET
					comments = comments + 1
				WHERE
					pa.post_id = NEW.post_id;
			ELSIF (was_removed_or_deleted (TG_OP, OLD, NEW)) THEN
				UPDATE
					post_aggregates pa
				SET
					comments = comments - 1
				WHERE
					pa.post_id = OLD.post_id;
			END IF;
    END IF;

    RETURN NULL;
END
$$;

```

Using this revised FUNCTION, insert of 13,1826 comment rows on a high-performance testing Lemmy system shows pg_stat_statement activity:

![image](https://github.com/LemmyNet/lemmy/assets/113625597/62027ee7-9906-490d-9f6d-5a01191d7ba4)

**Comment by phiresky** [comment]
Your terminology is a bit wrong, all those UPDATEs happen in the same transaction. So it's one transaction but with three UPDATE statements.

You should be able to merge that necro bumb thing into the same update statement with something lik

```sql
update ... set newest_comment_time_necro = CASE WHEN (NEW.creator_id != p.creator_id AND pa.published > ('now'::timestamp - '2 days'::interval)
THEN NEW.published
ELSE newest_comment_time_necro
END
...
```

**Comment by RocketDerp** [comment]
> Your terminology is a bit wrong

I edited it based on your feedback.
