### ISSUE TITLE
Setting to only federate with specific activitypub platforms

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#3878]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Cannot setup a Lemmy instance that only federates with lemmy instances and kbin instances. And will not other activitypub instances such as mastodon, plemora, peertube

### Describe the solution you'd like.

Setting to only federate with specific activitypub platforms. Instances can choose what type of activitypub instances to federate with when this setting is enabled.

It will always allow federating with lemmy instances. Instance admins can choose to federate with kbin instances, peertube instances, mastodon instances, etc.

### Describe alternatives you've considered.

None

**Comment by Nutomic** [comment]
Missing any explanation why this would be useful. Seems to go against the entire concept of federation.

**Comment by dessalines** [comment]
We already have allowlist federation, that has nothing to do with this ticket, which is

> And will not other activitypub instances such as mastodon, plemora, peertube

I agree that has no worthwhile use case.
