### ISSUE TITLE
Add a `Mark all reports as resolved` endpoint

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#3882]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, an instance can receive a large amount of reports, with no easy way to resolve them all.

### Describe the solution you'd like.

In a way similar to `Mark all Comments as Read`, we need to add a `Mark all Reports as Resolved` action.

### Describe alternatives you've considered.

NA

### Additional context

NA

**Comment by Die4Ever** [comment]
Potential issue of a new report just came in and isn't showing in your list yet, if you mark all as resolved then the new one would be resolved without you ever seeing it

Might be better to have the frontend give a list of which ones to mark

**Comment by Nutomic** [comment]
Yes this seems like a bad idea, reports are made specifically so that someone looks at them. We shouldnt encourage them to be ignored.
