### ISSUE TITLE
[Bug]: commenting via 3rd party app no longer works due to multiple languages being set 

### ISSUE THREAD

**Issue by aperson** [LemmyNet/lemmy#3884]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Can no longer comment on my instance when I have multiple languages set in preferences with a third party app (voyager).  I originally filed a bug report with them but they said to file a bug with lemmy.

Here is a link to my bug on voyager:

https://github.com/aeharding/voyager/issues/672

### Steps to Reproduce

1.  Have multiple languages set in your instance's preferences.
2.  Try commenting through voyager.
3.  Commenting fails.

### Technical Details

I am an end user and don't have logs.  I am using the voyager app.

### Version

BE 0.18.2

### Lemmy Instance URL

beehaw.org

**Comment by aeharding** [comment]
To be clear, Voyager does not send a `language_id` for posts nor comments. I assume the new comment is failing unless the user selects a language.

**Comment by aeharding** [comment]
@aperson, seeing that your instance is running 0.18.2, I think there is a good chance that the bug you're encountering is https://github.com/LemmyNet/lemmy/issues/3451. I suggest asking your instance administrator to upgrade to the latest version of Lemmy.
