### ISSUE TITLE
Make GetPostsResponse also include if community is blocked

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#3885]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Need to be able to toggle the blocked status of a community of post in Jerboa. We use the actual API datatypes for this.

### Describe the solution you'd like.

GetPostsResponse returns a list of PostView which already returns info such as `creator_blocked` include also `community_blocked` 

### Describe alternatives you've considered.

Make PostView return `CommunityView` instead of `Community` but then it doesn't need `subscribed`. Possibly unwanted because of the aggregates which are possibly expensive?

**Comment by dessalines** [comment]
This one is moot, because any post from blocked communities is automatically filtered out in the query code. So we do this in the back-end, rather than forcing UIs to handle it.

With comments, since they're trees, its a more difficult problem.
