### ISSUE TITLE
Private account

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#3887]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Settings to allow others to view a users profile and see what the users posted, commented or is subscribed to.

### Describe the solution you'd like.

A setting to hide posts and comments from others

A setting to hide communities the user is following

### Describe alternatives you've considered.

None

### Additional context

This will need to be done on the activity pub level most likely so mastodon users cannot get around this feature

This is also useful to reduce harassment of users on the platform form being targeted.

**Comment by dullbananas** [comment]
It might be a good idea to automatically make accounts private if they never posted or commented in a public community
