### ISSUE TITLE
[Bug]: PostgreSQL performance related to local_user_language database table, each new Lemmy user adds 184 rows as default

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3891]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

PostgreSQL performance is a big concern right now in August 2023. One of the identified areas is how the 184 default human languages are referenced by Lemmy.

Currently, if a new user account is created, lemmy does an INSERT of 184 rows into this database table. For 37 test users, 6808 rows. And every time a user refreshes the post list, those 184 rows have to be fetched out of the 6808 total and matched up to the 20 posts lemmy-ui presents.

Ideally, the logic for default users would be either zero or one row that indicates "ALL 184 languages" (everything in language table). Is there ever really a situation where someone would want zero languages with the current design, wouldn't that block all post listing results given how the table is used currently? It seems logical to invert the relationship and not INSERT 184 languages into this table for each new user account instead rework the SELECT logic to not have to match what most users leave as default.

### Steps to Reproduce

1. generate api_test script with 37 users
2. study the database table local_user_language
3. study how the post listing SELECT logic for post table does a JOIN to local_user_language table

### Technical Details

N/A

As an aside: community_language table does the same basic thing of 184 new rows for each community that is created. So there is some performance gain to invert the default behavior in similar fashion.

Also a question to raise... if one new language gets added to the site, 185 total, is the expectation that every default user has to be put through a migration to add one more row?

There might also be a denial of service concern / stability - if a rogue instance would manage to create a site or community with a huge number of fake languages - given how the SELECT logic could behave.

### Version

BE: 0.18.4 main

**Comment by Nutomic** [comment]
The size of local_user_language table is not really a concern, there are various larger tables on lemmy.ml. The performance problems are also resolved and I didnt see any evidence that the mentioned table was a problem. 

```
lemmy=# select
lemmy-#   table_name,
lemmy-#   pg_size_pretty(pg_relation_size(quote_ident(table_name))),
lemmy-#   pg_relation_size(quote_ident(table_name))
lemmy-# from information_schema.tables
lemmy-# where table_schema = 'public'
lemmy-# order by 3 desc;
table_name         | pg_size_pretty | pg_relation_size
----------------------------+----------------+------------------
sent_activity              | 20 GB          |      21580054528
received_activity          | 10 GB          |      11123122176
comment_like               | 2027 MB        |       2125840384
comment                    | 1543 MB        |       1618378752
post_like                  | 1319 MB        |       1382752256
comment_aggregates         | 495 MB         |        518823936
post_read                  | 471 MB         |        494084096
post                       | 458 MB         |        479928320
local_user_language        | 381 MB         |        399843328
person                     | 370 MB         |        388169728
person_post_aggregates     | 243 MB         |        254812160
post_aggregates            | 140 MB         |        147308544
community_follower         | 90 MB          |         94814208
```
