### ISSUE TITLE
RSS feeds should be accessible by appending .rss to path

### ISSUE THREAD

**Issue by CommunistSpectator** [LemmyNet/lemmy#3893]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I'm always frustrated when i append a url with .rss and it doesn't produce what i expect. i'm sure .json users feel the same.

### Describe the solution you'd like.

i'd like every lemmy url to produce a .rss feed. all comments should be in reverse-chronological order, and while 25 was the standard for reddit, more (or less) would be acceptable.

### Describe alternatives you've considered.

i use jerboa. i use the webapp. neither actually give me rss.

### Additional context

some of the reddit .rss and .json pages INCLUDE BUT ARE NOT LIMITED TO

search queries

community posts

community comments

post comments

user profiles

i'm sure there must be some other url that produces valid .rss or .json queries that is escaping me, but, basically, i think a link aggregator is feature-complete when any interation is reproducible in .rss. 

you may contact me at communistSpectator@gmail.com if you have any inquiries about this feature request.

**Comment by Nutomic** [comment]
RSS urls are shown in lemmy-ui, for example https://lemmy.ml/feeds/c/linux.xml?sort=Active

**Comment by dessalines** [comment]
Not all of our items have rss, and different front ends serve things at different routes, so trying to add `.rss` to random lemmy urls isn't a good idea. However these are already defined, and are capable of being shown in the UI.
