### ISSUE TITLE
[Bug]: post not displaying

### ISSUE THREAD

**Issue by olap** [LemmyNet/lemmy#3894]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

This post https://sh.itjust.works/post/3185509 was made from Lemmy.world amd pinned from there but fails to show in the new feed for sjw https://sh.itjust.works/c/rugby?dataType=Post&page=1&sort=New . It does however show in top all week. On https://lemmy.world/c/rugby@sh.itjust.works it does however show it

### Steps to Reproduce

1. Create post on lemmy.world to sjw community
2. Pin post for community from lemmy.worls
3. Visit sjw

Expected:
To see post on SJW

Actual
Post is missing from various sorts

### Technical Details

Seems like other instances are affected too https://lemmy.world/comment/2630997 is from a lemmy.nz user

### Version

BE 18.4

**Comment by olap** [comment]
I have figured out what the new, top, and active sorting algorithm is doing. As I'm using the same URL each time it is removing the post from these various sorts, topTime sorting isn't removing them. I've update the URL with a different query parameter and now it is showing. Hopefully this helps others out when looking at this issue, and this is likely by design but I didn't find it documented anywhere

Will leave it up to triage to figure out next steps

**Comment by dessalines** [comment]
I can't really figure out what's going on so far in the past, but it seems that post correctly federated. Without more details I can't fix it.
