### ISSUE TITLE
Flexible rule engine for downvoting

### ISSUE THREAD

**Issue by lullis** [LemmyNet/lemmy#3895]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I've noticed that some of my communities are started to get some users who are downvoting the majority of posts made without any particular reason. At the same time, I do not want to disable downvoting on my instance or I don't think it's the kind of behavior that the person warrants blocking/banning (perhaps the person is confused and thinks that downvoting things will help train an algorithm?)

### Describe the solution you'd like.

The idea would be to have some flexible rule system to determine if we can accept a down-vote from that user, or maybe to change the score that the vote actually produces. I know that the concept of "karma" does not exist in Lemmy, but there are a lot of other indicators that could be used as a signal to determine if that user's vote should be counted:

 - How old is the account? 
 - How long is that person subscribed to the community? (Would help mitigate people creating alts just to downvote something they don't like)
 - Has the person given at least an amount of N *up-votes* before (to avoid trolls, brigading and/or stalkers)

### Describe alternatives you've considered.

 - Disabling downvotes. It would solve the problem, but it feels like overkill and it removes a tool that can be used better in the hands of sensible people
 - Writing to the people who are too trigger-happy, and ask them to stop it. Doable, but it feels creepy and I don't want to have scripts in place to detect this behavior.

### Additional context

If we could get [Pleroma-style MRF](https://docs.pleroma.social/backend/configuration/mrf/) for these rules, it would be amazing.

**Comment by DraconicNEO** [comment]
I'm not really into the idea of adding automated systems to prevent people from voting and hiding that fact from them, that seems really shady like Reddit's shadowbanning or vote fuzzing and is unfair to new users who will be left wondering why vote isn't going up or whatever issue this causes for them.

>Writing to the people who are too trigger-happy, and ask them to stop it. Doable, but it feels creepy and I don't want to have scripts in place to detect this behavior.

I would disagree, I think if we want people to stop engaging in vote manipulation the best practice is to let them know that you know and tell them to knock it off, you may also try banning them from the community they're doing this in, permanently or temporarily for vote manipulation, as opposed to banning them from the whole instance.

**Comment by lullis** [comment]
No point of my proposal says that the rules need to be hidden from users.

**Comment by Nutomic** [comment]
Seems like people dislike this idea, and it would be a lot of complexity for such a minor issue. You just have to live with a certain number of downvotes.

**Comment by DraconicNEO** [comment]
> Seems like people dislike this idea, and it would be a lot of complexity for such a minor issue. You just have to live with a certain number of downvotes.

Honestly it's better that way, Vote fuzzing or choosing not to take criticism from certain users is a very anti-user thing to do.

Honestly if downvotes are such an issue on an instance a person is running they should just disable them altogether and let the most upvoted stuff float to the top as it naturally always does.
