### ISSUE TITLE
Account Expiry

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#3896]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

A way to have a private instance have accounts that will expire once a certain date and time is reached.

### Describe the solution you'd like.

An API call that can set or modify the date and time when a lemmy account will expire. Once an account expires, it will be disabled (not deleted, not banned). In order to reactive the account again, the expiry date and time must set to blank or updated to a date and time in the future.

And to have the expiry date and time to be displayed in the users account settings.

### Describe alternatives you've considered.

None

### Additional context

Will require Disable and enable user accounts feature

https://github.com/LemmyNet/lemmy/issues/3598

**Comment by Nutomic** [comment]
You dont mention what problem this would solve, or why ban/delete account arent sufficient.

**Comment by dullbananas** [comment]
This could be a plugin (#3562)
