### ISSUE TITLE
Question: Does federated content sync after reinstalling Lemmy?

### ISSUE THREAD

**Issue by therealmaxmoon** [LemmyNet/lemmy#3898]
### Question

I've reinstalled Lemmy many times, tested and broke it. 

Every time I broke it, I had to reinstall it.

The problem is now, while testing comments from Mastodon on Lemmy, the old content got federated, but the new one (which can be found under the same link), can't be accesses over Mastodon anymore, but it is possible to comment on old stuff (where do the comments land?). 

There are different versions, now, but it is the same link ([older Mastodon post](https://mas.to/@maxmoon@lemmy.utopify.org/109156901788446801), [old Mastodon post](https://veganism.social/@maxmoon@lemmy.utopify.org/110913698101006689), [new Lemmy post](https://lemmy.utopify.org/post/2)), but the content is different.

I figured this out after some days, so I don't think it will update automatically.

How to solve this problem?

-> I've posted this issue [in the support community](https://lemmy.ml/post/3708866), too, because this looks like a big issue.

**UPDATE:** I tried to repost the posts with a lower id, which got used in an earlier installation and I am sure the number is high enough to not hit ghost data from earlier installations. But somehow it shows wrong content on some mastodon instances. It is completely screwed up.

**Comment by therealmaxmoon** [comment]
Will it be possible to use Lemmy normally, if a new subdomain will be used, because I don't see any way how to use Lemmy again, if it was already installed?

**Comment by RocketDerp** [comment]
There is an issue open about needing to create procedures and recommendations for lost instance re-install: https://github.com/LemmyNet/lemmy/issues/3782

**Comment by Nutomic** [comment]
This sounds like a question for Mastodon devs. I would try waiting a day or two, its possible that Mastodon caches data from the old installation and cant federate until that cache is updated.
