### ISSUE TITLE
Aging older data, making date-aware cut-off on routine API requests for post listings, scaling lemmy PostgreSQL usage

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy#3899]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There has been talk of slow queries, but I think it's worth making the topic of 'too much data' in PostgreSQL a dedicated conversation. There are two major concerns that I see:

1. API calls to list posts for Active, Hot and even New to lists posts do not have any concept of a date-based cut-off. ("new" is kind of interesting  if you step back, is about getting the latest posts regardless of popularity voting) 
2. There is little to none in the way of documentation or code for archiving out older data. Some instance operators are on a limited budget for storage (and RAM) and as Lemmy grows in popularity, they may wish to only retain a month or two of data given the "fresh meat" nature of many people who read Lemmy - and rely on people using independent search sites that have cropped up for older content.

There may even be desire for community-specific settings. A community of meme messages may have very high activity but a lot of it rarely gets read after a few weeks. In contrast, a small community about a specific comic creator may want to hold years of past conversations and may only have accumulated 80 posts in 3 years.

Right now the SQL SELECT logic for post listing often relies on open-ended queries with LIMIT and OFFSET. This may have worked well when an instance had only 10,000 total posts and comments and wanted to show end-users something on the home page... but when a server becomes very popular and data grows to 1 million posts and comments, there have been serious performance problems of SQL SELECT statements taking 10 seconds or longer due to the amount of data and the JOIN operations performed in Lemmy currently.

### Describe the solution you'd like.

1. I think API calls for listing posts [should be enhanced with a when_before and when_after timestamp](https://github.com/LemmyNet/lemmy/pull/3900) and default to when_after to 10 day period on Hot, Active (for "All", maybe 21 days for a single community).  Somewhat adjacent, I think that if you request "Top Score" that a default cutoff should be score of 20 or higher so that the amount of data being searched and indexed is more in line with the purpose of these sorts. Same with controversial, it should try to exclude non-controversial in the PostgreSQL logic.

2. Community-specific logic to manage large amounts of data so that communities with 100,000 posts or larger do not present technical performance problems for small server operators on a budget of RAM for PostgreSQL. In the "Slow SQL" issue, some code and concepts were shared that used PostgreSQL windowing capability by community_id to identify the most recent 1000 comments per-community as a routine search targeting window. There is also an example of doing a LATERAL JOIN with the LIMIT 20 moved to per-community, a similar approach.

3. Documentation, code, and maybe even an API to archive data. It may be as simple as setting a flag on data so it is excluded from search... auto-locking posts from new comments or edits... or more complex like using PostgreSQL table partitions to better scale performance with a growing amount of accumulated rows.-  post_aggregates could hold less rows than post table, for example, and document the behavior of this.  Some thoughts on maintaining site_aggregates or community_aggregates totals when data as been purged or archived.

### Describe alternatives you've considered.

N/A at the moment

### Additional context

In April 2023, a Lemmy server running for 4 years like lemmy.ml might have had 100,000 posts and an equal number of comments in the PostgreSQL database. The number of instances in the database was around 50 peer servers, now that is over 1700. The number of communities that a server can populate into the database can be well over 15,000 now. An eye towards scaling up to the next level is upon us.  4 days prior to creating this GitHub issue, I did open discussion on the topic on Lemmy forum !lemmypostgresql  https://lemmy.ml/post/3531480

I also think this is towards evolution of smarter client apps that maintain their own knowledge of the timestamp of when they last requested new content from Lemmy, and can pass a parameter specifically indicating they want new posts after that exact time. Further, lifting of the limit=50 from the API to more like limit=500 for bulk replication and downloading would be a good direction forward... and perhaps a condense alternate format for the response (such as just essential details about posts, such as their number of comments, votes, edit timestamps instead of full body)

**Comment by RocketDerp** [comment]
I already experimented with adding date_after to the /post/list API call and didn't find it difficult overall. I opted to use a Integer "Unix epoch" timestamp that existing Rust libraries in Lemmy can parse - and JavaScript can also generate easily... as most any programming language these days. We could go the full step and implement date_before too, giving a way to specify a window and even one more step further to add a flag to indicate if filtering on the SQL select should be based on post 1) published date, 2) edited date, 3) newest comment date, 4) some combination of these previous dates.  This would give a means for a smarter API client to request newer content more strategically...  It's also been brought up that a 'received' date could be considered because federation incoming can sometimes be delayed and 'published' date may not reflect a post that was delivered 2 hours after.  At heart, Lemmy is a very date-oriented experience, the "freshness" of content being a big reason people flock to Lemmy.

**Comment by RocketDerp** [comment]
As a performance improvement, PostgreSQL optimization, I've suggested that featured be taken out of the SELECT statements for post listings.... it's typically very few posts in a big ocean of posts and I think a trick can be applied with the existing TRIGGER FUNCTION to set 10 years into the future the post_aggregates.posted date and remove INDEX overhead. Obviously the "Old" sort order (and perhaps some others) might have issues... and a post-production stage in the Rust code could subtract it... mentioned here: https://github.com/LemmyNet/lemmy/pull/3872#discussion_r1301957585

Thinking about it, there is almost no overhead to SELECT published - INTERVAL (10 years) AS featured_published_normal... I mean once PostgreSQL gets the LIMIT 1 to LIMIT 500 posts we are seeking, it then can run a FUNCTION to look at featured and automatically subtract 10.0 years from it?

**Comment by Nutomic** [comment]
Too long and generic, open more specific issues.
