### ISSUE TITLE
 Allow a user to follow posts so that they receive notifications for all comments made to it as if the user was the OP

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3905]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, if you are interested in the discussion under a post, then you would need to keep checking back on it. 

### Describe the solution you'd like.

If the user can directly follow the post, then they would be able to receive notifications for all comments made to it as if they were the OP.

### Describe alternatives you've considered.

none.

### Additional context

Related to https://github.com/LemmyNet/lemmy/issues/3904.

**Comment by lionirdeadman** [comment]
Duplicate of https://github.com/LemmyNet/lemmy/issues/3069

**Comment by K4LCIFER** [comment]
Ah, so it is! My bad!
