### ISSUE TITLE
Support for Alternate Account Display Names

### ISSUE THREAD

**Issue by RandomDSdevel** [LemmyNet/lemmy#3909]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Currently, users who'd like to separate activity in some communities from main activity in other communities have to create multiple user accounts, as on Reddit.  ~~An example of when somebody might want to attribute post and other activity to a separate, alternate name is that they:~~  

 - ~~might participate in discussion of some less-mainstream fandoms on communities for them and~~ 
 - ~~would like to keep their posts in these communities unassociated with their main account name.~~  

Another reason that a user might want to use an alternate name on a community is that they're better known by that name in other online spaces affiliated (either officially or informally) with that community.  

### Describe the solution you'd like.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Within reason, Lemmy should allow users to create alternate names (pseudonyms) for their accounts aside from their main names.  The functionality required to allow this should get implemented in a way that's easy to moderate.  Also, users shouldn't abuse this new capability to create alternate names for their accounts.  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Examples of other online services and platforms that allow users to have multiple display names include but may not be limited to:  

 - [Archive of Our Own](https://archiveofourown.org/) (AO3,) a fan fiction hosting site.  

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;That site abbreviates 'pseudonyms' (plural intentional) to call them ['pseuds'](https://archiveofourown.org/faq/pseuds?language_id=en) for short.  
 - Discord.  

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Lemmy's support for alternate display names shouldn't be as open as Discord's, however; on Discord, a user can set a different display name for _every server they've joined!_)  

### Describe alternatives you've considered.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Users can create multiple Lemmy accounts on one or more servers, as they can now.  At least some users might consider this situation less than ideal, however.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This feature request doesn't _solely_ involve Lemmy's back end, as it will also have to get surfaced in platform UI if given (any) further consideration.  I still checked the 'Is this a backend issue?' checkbox, though, as it kind of still applies.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Users should not only be able to post, but also to subscribe to communities under their alternate display names.

**Comment by lionirdeadman** [comment]
If this feature should not hinder moderation, it is impossible to insure any level of privacy as this information will need to be shared across other instances. As anyone can spin up their instance, anyone can also get this information.

I think the goals are incompatible as a result.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I originally meant that this feature should be easy to moderate/shouldn't hinder moderation in the sense that it could perhaps be the case that:  

 - Private alternate display names hide that they're connected to another account even to moderators, but 
 - Moderation on an alternate display name still affects the wider account with which it's associated, at least for:  
   - Activity on that server or 
   - Other ecosystem-wide activity that the alternate display name in question is associated with.  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It turns out, however, that I actually forgot a crucial point when originally making this feature request:  the platforms with the similar functionality that inspired me to open this issue and which I referenced in my OP actually _don't_ make alternate display names private.  

 - On AO3:  
   - All of a user's 'pseuds' are visible on their main account profile page.  
   - A user's actual account name is always displayed next to the pseud they're using for something in parentheses, like so:  

     > Pseud (User name)
 - On Discord, you can always discover a user's real account name by looking in the modal information pop-up (sort of like a hovercard) that appears when their per-server user name or avatar is clicked.  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Private alternate display names would then be a novel feature compared to other platforms for Lemmy, at least as far as I'm aware.  I'm going to redact that part of my feature request to avoid scope creep, starting off by striking through the relevant text that no longer applies.  Some further proper refactoring would then be warranted to give this feature request a proper motivation again, but I'd have to think about what that'd be, exactly, and how it'd get phrased.  Consider this issue and its thread on hold until then, I guess?

**Comment by Nutomic** [comment]
You can do this simply by creating another account. As already mentioned this would cause too many problems for moderation, not to mention being very complicated to implement for little benefit.
