### ISSUE TITLE
Allow many-to-many mapping of accounts to e-mail addresses

### ISSUE THREAD

**Issue by brainchild0** [LemmyNet/lemmy#3910]
# Problem

If someone wishes to create several accounts on the same server, such as for purposes of privacy, then the same individual must use a different e-mail address for each account.

Meanwhile, only one e-mail address may be given for each account, limiting recovery options in case of lockout.

# Solution

Remove restriction against multiple accounts using the same e-mail address, or relax it such that  at least a few accounts may use the same  address.

Similarly, allow each account to be assigned at least one auxiliary e-mail address, in addition to the primary, so that a user may recover an account after lockout, even if the e-mail account for the primary address is not accessible.

 
# Alternatives

Users must give alternative e-mail addresses in order to hold multiple accounts on the same server.

Users often hold accounts long term, and at times may want to recover an old account past the point that some associated e-mail address is accessible by the user. Currently, however, accounts may be assigned only one e-mail address. No recovery is possible once the user has lost access to the particular e-mailaccount.

# Discussion

Restrictions against multiple accounts for the same e-mail address may follow from a variety of rationales.  

It may be assumed that a second account has no value to the same individual, or it may be assumed it reduces spam and other abuse to require for each account an address not used by any other.

However, use of multiple accounts for the same individual has legitimate use cases, most particularly ones related to privacy.  A user may engage professional content through one account, perhaps revealing a true identity, but also participate in more personal discussions through an anonymous account, rather than one publicly connected to the other account or to the real identity.

Similarly, the restriction may not reduce overall abuse, since anyone controlling a domain may create and use an arbitrary count of e-mail addresses. 

Further, abuse may be contained by other means that directly address the human-machine distinction, and that enforce appropriate behavior, such as  challenge-response (e.g. *CAPTCHA*) tests, and voluntary reporting of disruptive behavior.

**Comment by rclabough** [comment]
I disagree with this as it'll open a huge door for bot accounts.  The email requirement is there so there is another barrier for bot accounts. 

in fact there are other issues that tackle restricting it even further, removing the + symbol loophole.

**Comment by brainchild0** [comment]
> I disagree with this as it'll open a huge door for bot accounts.

It feels as though you just read the title, and sidestepped the entire line of argument.

Again…
1. It is easy for an attacker to control an arbitrarily high count of working e-mail addresses.
2. Robotic attacks may be guarded by other, more relevant protections, such as tests that a remote user is a real human.
3. The use case is completely legitimate for associating multiple accounts with the same e-mail address, and is supported by comparable commercial platforms.
4. Forcing users to give alternative e-mail addresses for secondary accounts will tend to to make recovery more difficult in the event of password lockout.

**Comment by cynber** [comment]
> How would a password reset work in that case? 

We could add an additional field for the specific username the user wants to reset. The email field could also be replaced entirely, but that might lead to harassment and spam since it would be too easy to send a reset email.

**Comment by brainchild0** [comment]
> The email field could also be replaced entirely, but that might lead to harassment and spam since it would be too easy to send a reset email.

Yet, most sites work exactly the same way.

The frequency of reset requests is throttled.

In some cases, recovery of username is a separate operation in which the user provides an e-mail address, compared to the password recovery in which providing the username is also necessary.

**Comment by Nutomic** [comment]
This would add a lot of complexity for almost no benefit. You can register multiple accounts with the same email using `me+account1@example.com`. And if password reset fails, you can contact the admin.

**Comment by brainchild0** [comment]
Is the behavior documented within the user interface?

Naturally, some administrators will not agree to a password reset for an unverified user. Otherwise, they  would be opening an attack vulnerability.
