### ISSUE TITLE
Ability to share/export, and import user blocklists

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3911]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, if you want to give your blocklist to someone else, or if you want to transfer your blocks to a new user, you need to manually copy and add them one-by-one.

### Describe the solution you'd like.

Some method of exporting/copying a user's blocklist, and a method to then import that blocklist.

### Describe alternatives you've considered.

none

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3976
