### ISSUE TITLE
Import/Export Saved Posts & Comments

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#3918]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

No way to backup and import saved posts and comments

### Describe the solution you'd like.

A setting and API call to be able to import and export saved posts.

### Describe alternatives you've considered.

None

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3976
