### ISSUE TITLE
Add ability for moderators to escalate reports to admins. 

### ISSUE THREAD

**Issue by ludrol** [LemmyNet/lemmy#3919]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When user is making a report about CSAM, moderator can censor media to not show up for users but it isn't purged from database. Mod need to manually contact admins to take action. With how decentralised everything is it isn't always possible. 

Inspired by this post: https://jamie.moe/post/113631

### Describe the solution you'd like.

In the reports there should be an ability to escalate to local or remote admins.  

### Describe alternatives you've considered.

Admins receiving all reports - this approach isn't feasible and would overburden already burnout admins. 
Adding a second report to admin button - users would be paralyzed from multiple choices.   

### Additional context

This cuts down on #2414 and reworks that proposal to make it simpler for faster implementation. That proposal is over complicated with conditions and logic flow.

With how huge lemmy has become there needs to be made a solution that is fast and not perfect. Hosting CSAM is huge liability for server admins.

**Comment by dessalines** [comment]
Admins currently do receive all reports, including ones for communities they don't moderate. So reported content is already elevated to as many eyes as possible.
