### ISSUE TITLE
Allow a way to preprocess images before accepting them for pict-rs

### ISSUE THREAD

**Issue by db0** [LemmyNet/lemmy#3920]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

We've been having some [CSAM trolling on the threadiverse](https://lemmy.dbzer0.com/post/2875447) and also some very nasty instances which freely allow loli uploads which cause others to federate their thumbnails. As such, the instance admins both have to stay extremely vigilant for reports, and also often have to review extremely traumatizing images. 

### Describe the solution you'd like.

In my work with [AI Horde](https://aihorde.net) I have developed multiple tools to fight against CSAM which can be quite useful to supplement the fight against such behaviour, which are extremely risky for instance owners.

For example I just finished developing [lemmy-safety](https://github.com/db0/lemmy-safety) which can allow any instance admin using object storage to perform a cleanup of pict-rs of potential CSAM. Likewise, the AI Horde provides a more generic REST API endpoint that anyone can use to detect NSFW images.

However there is no way to make lemmy preprocess images before sending them to pict-rs, which a malicious user can use to simply open a new comment, upload an CSAM image, and then cancel the comment and keep the url.

I want to suggest an open ended checkpoint between uploading an image and sending it to pict-rs. This could sit either between nginx and lemmy, or between lemmy and pict-rs, whatever is more convenient. 

The way I would like it to work is that I can either place a predefined script name somewhere on the OS, or provide a script path to lemmy to use. Every time an image is requested to be uploaded, the image would be fed to this script which can then run any number of detection schemes to ensure the image is not a problem. The script would then return a true/false and a detection string (e.g. 'CSAM','NSFW','gore' etc) which would be sent to the admins and the user for follow-ups.

This solution would not cover the federated images, but it would be a good way to ensure one's own instance at least, is clean(er)

If this solution is developed I have already multiple solutions that lemmy admins could plug into this detection.

### Describe alternatives you've considered.

No alternative option exists.

**Comment by sunaurus** [comment]
I think adding this functionality into pict-rs would be more flexible - this would also cover checking incoming federated images.

For example, pict-rs could have configuration like:

```
[media]
external_check_endpoint = 'https://lemmy-safety/check'
```

And if such an endpoint is configured, it would `POST` every new image to this endpoint and only continue processing the image if the endpoint responds with a success.

(Assuming @asonix is interested in such a thing for pict-rs)

**Comment by asonix** [comment]
I think supporting this in pict-rs makes sense. While I would rather not tie pict-rs to any proprietary APIs, if a self-hostable solution is available I would consider integrating that

**Comment by rclabough** [comment]
I know we're generally open source but as an instance owner I'm willing to make an exception here to add in support for other cloud providers and their tools.  Since we're not relying on them to stay up I think it should be up to the instance admin if they'd want to opt into them.

I'm not a fan of them, but allowing an instance owner to turn on something like Google's CloudVision API (https://cloud.google.com/vision/docs/detecting-safe-search), would be a huge plus and a good security step.  (I realize not every owner would want this, but for those who do like myself this would make me much more sure in keeping my instance up and running.

Thought being it could simply be a checkmark and a textbox for the API key in admin settings, or in docker just environment keys

**Comment by DraconicNEO** [comment]
Maybe there could also be an option for admins to require users to solve captcha before uploading to pictrs that could prevent this kind of spam if it came from bots or at the very least slow it down since one would have to constantly solve captchas to upload many files to the service.

**Comment by t-var-s** [comment]
> (Assuming @asonix is interested in such a thing for pict-rs)

Registration is disabled to add new issues on https://git.asonix.dog/asonix/pict-rs/issues

**Comment by asonix** [comment]
Opened an issue: https://git.asonix.dog/asonix/pict-rs/issues/30

**Comment by dessalines** [comment]
@asonix You might need to open up registrations for your instance, so we can comment there.

Ideally it would be a `reject_csam` boolean in the pictrs config, that would check the AI horde endpoint. @db0 might be able to help add this to pictrs directly.

**Comment by db0** [comment]
Note: You can't check for CSAM via the AI Horde due to legal reasons having to do with image transfer. What you **can** check via the AI Horde is for NSFW in general.

To check for CSAM, we're need pictrs to be able to call a custom endpoint provided by the user (behind which would be something like a **self-hosted** [lemmy-safety](https://github.com/db0/lemmy-safety) for example)

**Comment by CorvetteCole** [comment]
To build on that, I think the boolean y/n is an option (like a return JSON for the request) but it could even be as simple as the request must return an HTTP 200 code.

**Comment by dessalines** [comment]
> I can help figure out the endpoints which pict-rs would need to call and design a basic http microservice anyone would host themselves along with pict-rs and lemmy.

@db0 @CorvetteCole That sounds best. Then all @asonix would need to do is add an `image_check_url` config option, post the image to it return an error code if the check fails. 

Then we'd run your service in docker-compose, and wire it up to pictrs.

**Comment by db0** [comment]
Just to note that while doing this in picts would be useful for handling federated cached images, allowing such functionality on the lemmy backend itself has other benefits. For example this would open the possibility that when an image is a positive hit, to mark it (and the corresponding post and user) for moderator review, instead of deleting it immediately.

**Comment by dessalines** [comment]
Adding an image-upload moderation queue is not something we have time for rn.

**Comment by rclabough** [comment]
Any and all moderation/CSAM tools should be the top priority right now, it's the only topic of discussion in the admin chat right now.  Most of us are teetering on the edge of shutting down our Lemmy instances (and many already have) because of the recent attacks, pending any tooling that can be given to us.  It should be the only thing there is time for rn.

**Comment by db0** [comment]
pict-rs 0.4.3 added functionality to be able to call an API to validate an image

https://git.asonix.dog/asonix/pict-rs/releases#user-content-external-validation

I just finished writing a lightweight API server which can be used to receive these payloads from pictrs and then be connected by a GPU worker running clip to validate images for CSAM or Porn

https://github.com/db0/pictrs-safety

All I need is some help to convert this into a docker container which can then be (optionally) integrated into the lemmy docker-compose along with pict-rs. Unfortunately my docker knowledge is very low so I could use some help doing this.

I would like someone to help me do the following: 

* Adjust the Dockerfile so that it deploys the container properly (What I made with ChatGPT is giving me an error)
* Provide a sample docker-compose entry which would deploy a postgres (or use lemmy's postgres?) and then connect pictrs-safety to use it.

Please feel free to contact me on matrix to collaborate more directly.

**Comment by poVoq** [comment]
> or use lemmy's postgres

It seems likely that is scanning API endpoint will not run on the same server as Lemmy (given the GPU requirement), so I guess a fully separate Docker setup will make more sense.

But the official docker compose file should probably add the new Pict-rs feature as an optional ENV setting.

**Comment by db0** [comment]
actually with my setup, the docker image can run along with lemmy. The worker will then be able to come from externally (even the admin's PC)

**Comment by db0** [comment]
I've opened a PR for the ansible deployment https://github.com/LemmyNet/lemmy-ansible/pull/175

However do keep in mind that in order for this to work with even the lowest GPUs, lemmy has to be able to adjust the timeout it allows for uploading images, as the image scanning can take upwards of 12 seconds with a low-powered GPU
