### ISSUE TITLE
Allow Moderators to require Captcha for creating posts

### ISSUE THREAD

**Issue by DraconicNEO** [LemmyNet/lemmy#3921]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Users are able to create multiple times very quickly which can overwhelm moderators and cause problematic content to slip by or just be too much to handle. This recently happened in a community where the attackers used Bots to create multiple posts to the community with malicious content.

### Describe the solution you'd like.

Allow for mods to enable a captcha form for creating posts on the community in order to stop malicious bots posting to the community or at the very least slow them down greatly giving mods and admins more time to deal with malicious actors quickly before the situation gets out of hand.

### Describe alternatives you've considered.

N/A

**Comment by dessalines** [comment]
Its been an explicit choice to have the bot protection at the instance/site, not community level. If we do any solution here, it'd have to be there.
