### ISSUE TITLE
[Bug]: Post from unsubscribed community still exists, but cannot be found other than by direct url

### ISSUE THREAD

**Issue by KraXen72** [LemmyNet/lemmy#3929]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

i created this post: https://discuss.tchncs.de/post/2557154
however, i could not find anywhere else other than by direct link:
- i tried checking inbox, nothing there
- i tried checking posts on my profile, nothing there
- i tried checking the Music@lemmy.world community by new, nothing there (i passed the date of posting, went back several weeks)
- i tried checking the api responses in network tab in devtools of my posts page on the profile: nothing there
- i tried checking site-wide search by title, then by specifiying community, then by specifying community & author
- i tried subscribing to the community again, and it still didn't show up under my posts on my profile.
  
 i eventually only found it because i found my lemmy profile through mastodon.social, and it was my only post so far.

### Steps to Reproduce

unsure how this even happened to be hones. but probably:
1. create post in community in remote instance
2. unsubscribe from given community

### Technical Details

i am not an instance owner. 
Only browser console error was:
```
service-worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://lemmy.fmhy.ml/pictrs/image/03e0c09c-daad-4455-9c04-6a4f22507f33.png?format=webp&thumbnail=96"}]
    at m.q (https://discuss.tchncs.de/service-worker.js:1:60476)
    at async m.g (https://discuss.tchncs.de/service-worker.js:1:7644)
```
which is from an instance which is down.

### Version

BE: 0.18.4

### Lemmy Instance URL

https://discuss.tchncs.de

**Comment by mruczek** [comment]
Is "Show read posts" enabled in your profile settings?

**Comment by KraXen72** [comment]
![image](https://github.com/LemmyNet/lemmy/assets/21956756/857a847d-192a-4b4e-969a-550373a1e84b)
yes

**Comment by Nutomic** [comment]
I cant reproduce this. Also being subscribed or not has no influence at all on the posts that you see. Maybe it was removed by a mod.
