### ISSUE TITLE
`id` column is redundant in some tables

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#3933]
For example, the primary key in `comment_aggregates` can be changed from `(id)` to `(comment_id)`. And the one in `comment_saved` can be changed to `(comment_id, person_id)`.

This will reduce disk usage and might help the database know that only one row needs to be found when querying the table using the fields that are in the new primary key.

**Comment by Nutomic** [comment]
Feel free to make a PR.
