### ISSUE TITLE
Ephemeral Content: Automatic Removal of Old Content

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3934]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Yes, the current implementation of Lemmy does not provide an option for users, communities, or instances to automatically remove content older than a specified number of days. This can be an issue for users who want their content to be ephemeral and who don't want to manually remove old content they no longer wish to keep on the platform.

### Describe the solution you'd like.

I propose adding a feature that allows users, communities, and instances to set an expiration period for their content. This expiration period would be configurable and would automatically remove content (posts and comments) older than the specified number of days. The feature should include:

1. A user setting to enable/disable automatic content removal and to set the expiration period (in days) for their content.
2. A community setting to enable/disable automatic content removal and to set the expiration period (in days) for content within the community.
3. An instance setting to enable/disable automatic content removal and to set the expiration period (in days) for content within the instance.

When the expiration period is reached, the content should be permanently removed from the platform. This feature would provide users with more control over their content's lifespan and help instances create a more ephemeral environment if desired, similar to platforms like 4chan.

### Describe alternatives you've considered.

An alternative solution could be to implement a content archiving system, where old content is not deleted but becomes read-only and hidden from search results. However, this approach does not fully address the need for ephemeral content and may still require manual intervention from users to remove unwanted content.

Another alternative is to rely on third-party tools or scripts to automate content removal. However, this approach may not be user-friendly and could lead to inconsistent experiences across the platform.

### Additional context

Ephemeral content is becoming increasingly popular on social media platforms, as it allows users to share their thoughts and experiences without the long-term consequences of a permanent digital footprint. Implementing this feature in Lemmy would cater to users who prefer this type of content and help differentiate the platform from competitors like Reddit.

### Related
- [Allow Setting Post Deletion After Number of Days](https://github.com/LemmyNet/lemmy/issues/3945)

**Comment by TheBrokenRail** [comment]
> Ephemeral content is becoming increasingly popular on social media platforms, as it allows users to share their thoughts and experiences without the long-term consequences of a permanent digital footprint. Implementing this feature in Lemmy would cater to users who prefer this type of content and help differentiate the platform from competitors like Reddit.

This just seems like it'd create a false sense of security. If something is published on the internet, there's a good chance something will automatically archive it. Doubly so with Lemmy due to its federated nature, all you'd need is one malicious instance that ignores deletion requests.

**Comment by cperrin88** [comment]
> Doubly so with Lemmy due to its federated nature, all you'd need is one malicious instance that ignores deletion requests.

You don't even need any malicious actors. Delete requests get lost all the time due to server or network problems.

**Comment by Nutomic** [comment]
This will completely break discussions for anyone who wants to read it some months or years later. Imagine finding a thread about a technical problem that you have, but the comment with the solution was automatically deleted because of this functionality. Not a good idea.
