### ISSUE TITLE
Add Federation Date to /instance page

### ISSUE THREAD

**Issue by BramWarrick** [LemmyNet/lemmy#3935]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Determine when or if federation changed for an instance - I'd like dates for federation on the /instances page. Ideally, a federation log that tracks each federation or defederation would be even more optimal.

So many questions that arise on instances would be instantly answerable, were this implemented.

### Describe the solution you'd like.

When assessing why certain communities are now part of "all," it would be helpful to know if (or when) federation was added. This may be in the table, but I'm not sure. If it's in the table, this is a UI request.

Superseding the above would be to have a federation log - showing all additions, removals, blocks, etc. This would need to be visible to all users so we can make decisions more easily and know why our feed changes.

### Describe alternatives you've considered.

Reviewing instance-level announcements does not reveal when federation occurred, nor can I find out when an instance is defederated (consistently).

### Additional context

Federation and defederation are central to a users lemmy experience and choosing an instance that works for you is important. As time progresses and the lemmyverse evolves, decisions are made by admins that impact the users and...  we'd like to be able to keep track of what's added or removed - and when.

**Comment by Security-Chief-Odo** [comment]
This would be a UI change in addition to a few lines in the server code here to add an _order by_ to return it as. I don't know if showing the date is great but maybe again sorting the list by newest/ most recent at the top.

**Comment by Nutomic** [comment]
The API already returns the data, it only needs to be shown by lemmy-ui.
