### ISSUE TITLE
Algorithm Marketplace

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3936]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently in Lemmy, users are limited to the default sorting algorithms provided, like Top, Hot, New, etc. While these cover the basics, more advanced users may want additional ways to customize and sort content.

### Describe the solution you'd like.

I propose creating a marketplace of sorting algorithms that users can browse and select from. This would allow the Lemmy community to create and share custom sorting algorithms.

The default algorithms would include:

- Top - prioritizes posts with the most upvotes
- Hot - prioritizes new posts that are quickly getting upvotes
- New - newest posts first
- Old - oldest posts first
- Most comments - prioritizes posts with the most comments
- New comments - prioritizes posts with recent comments
- [Forum](https://github.com/LemmyNet/lemmy/issues/3604) - prioritizes posts with any recent activity like new comments, edits, etc. Mimics traditional forum sorting.
- [User engagement](https://github.com/LemmyNet/lemmy/issues/3563) - balances multiple factors like votes, comments, time spent, etc.

All default algorithms could be filtered by timeframes like past day, week, month, year. 

The marketplace would allow anyone to create a new algorithm and make it available for others to install. For example, someone could make an algorithm that only shows posts from followed users.

### Describe alternatives you've considered.

An alternative would be to just allow power users to edit config files to create custom algorithms. However, a marketplace makes it easier for average users to discover and install different algorithms.

### Additional context

Allowing custom sorting algorithms gives users more control over their feed and discoverability of content. It enables power users to experiment and share better ways of ranking content. And it future-proofs Lemmy by allowing new algorithms to be added over time as needs change.

### Related

* [Server-side plugins / extensions](https://github.com/LemmyNet/lemmy/issues/3562)
* [Flexible Scoring System User Setting](https://github.com/LemmyNet/lemmy/issues/3477)

**Comment by Nutomic** [comment]
This is not possible because sorting is done in the database, so adding a new sort option requires a database migration with new indexes, columns and updated queries. Not something that can be done with a simple plugin.
