### ISSUE TITLE
Allow Setting Post Deletion After Number of Days

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3945]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, there is no option to schedule deletion of posts after a certain number of days. This means posts remain on Lemmy indefinitely unless manually deleted.

### Describe the solution you'd like.

Add an option when creating a post to set it to be deleted automatically after a chosen number of days. This would allow users to easily make ephemeral posts without needing to remember to delete them later.

Specifically:

- When creating a post, have a setting like "Delete this post automatically in __ days"
- Store the deletion date with the post metadata
- Have a scheduled job that runs daily to delete expired posts

The number of days until deletion should be configurable, for example between 1 and 365 days.

### Describe alternatives you've considered.

- Relying on manual user deletion. But this requires the user to remember to delete old posts.
- A separate "archive post" option. But this does not fully delete content.
- Instance/Community opt-out configuration.

### Additional context

This feature would enable time-limited and ephemeral posting. It caters to users who want the option for automatic removal of old or irrelevant content without keeping a permanent record. Similar functionality exists on other platforms like Snapchat.

Implementing scheduled deletion makes Lemmy more configurable for different use cases.

### Related
- [Ephemeral Content: Automatic Removal of Old Content](https://github.com/LemmyNet/lemmy/issues/3934)

This is a setting for a post by post basis instead of for all posts like the related feature.

**Comment by cperrin88** [comment]
The problem with your proposal is the federation. Another server can just ignore the timer. Or it could be another software that doesn't have the feature implemented. That means it is deleted from your instance but maybe not from other instances. And even if your home instance triggers the deletion, it is possible that other instances don't get the message or simply ignore it.

Federated content is not very well suited for ephemeral content. It is more the other way around: what you post may never really go away. Therefore implementing such a feature might give users a sense of control that they don't have.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/issues/3934
