### ISSUE TITLE
Custom Feeds

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#3950]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

No

### Describe the solution you'd like.

Implement custom feeds in Lemmy that enable users to:

- Follow specific users, communities, and instances
- Include/exclude tags or keywords, keywords could be based on regex
- Choose to see posts, comments, or both
- Set a custom feed as the default feed

As a example this is how Antennas work in Firefish.
- Name
- Antenna source:
  - All posts
  - Posts from specific users (with text area)
  - Posts from all users on a server
- Include replies toggle
- Keywords to listen to (with text area, separate with spaces for an AND condition or with line breaks for an OR condition.)
- Keywords to exclude (with text area, separate with spaces for an AND condition or with line breaks for an OR condition.)
- Case sensitive toggle
- Only posts with files toggle
- Notify about new posts toggle

### Describe alternatives you've considered.

None

### Additional context

Custom feeds have proven to be successful in other platforms, such as Reddit's multireddit feature. Implementing these features in Lemmy would enhance the user experience by allowing users to find and organize content based on their interests and preferences.

### Related ideas
- [User-Defined Tag/Keyword Filters for Personalized Content Hiding](https://github.com/LemmyNet/lemmy-ui/issues/2164)
- [Grouping communities or multi-communities](https://github.com/LemmyNet/lemmy/issues/818)
- [better interoperability with Mastodon by using hashtags](https://github.com/LemmyNet/lemmy/issues/3906)
- [Algorithm Marketplace](https://github.com/LemmyNet/lemmy/issues/3936)
- [Advanced Search and Tag Filtering](https://github.com/LemmyNet/lemmy/issues/3788)
- [Cross-Instance Feed Viewing](https://github.com/LemmyNet/lemmy-ui/issues/1928)
- [See both posts and comments](https://github.com/LemmyNet/lemmy-ui/issues/946)

**Comment by Nutomic** [comment]
> Follow specific users, communities, and instances

You can already follow communities. You can also follow users from other platforms like Mastodon. Following instances doesnt make much sense as they can have completely unrelated communities.

> Include/exclude tags or keywords, keywords could be based on regex

Partially covered by slur filter for admins, but this might deserve a separate issue if there isnt one already.

> Choose to see posts, comments, or both

Already possible to switch between post/comment views in lemmy-ui

> Set a custom feed as the default feed

Sounds like a frontend matter.

Gonna close this issue because its too vague and covers unrelated things. Some of it is already supported, others dont make sense and for multireddits there are already various issues.
