### ISSUE TITLE
Prevent communities and server from flooding the "new" feed

### ISSUE THREAD

**Issue by machado2** [LemmyNet/lemmy#3954]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There are legimitate reasons someone may want to move a lot of content to a lemmy server. On my own example, by doing so I flooded the "new" feed on lemmy.world and annoyed some people.

### Describe the solution you'd like.

Some limit on how many posts of a community is shown on the "new" feed. This limit should also try to prevent against malicious users doing it on purpose, so it shouldn't be easy to bypass. I guess it's possible for an attacker to create a lot of communities, so there could be some limit per server. 

Maybe the "new" feed could list a number of threads proportinal to the number of users that subscribe to each community. Maybe compute some kind of "weight" for each community so you can easily change what factors on how you distribute that.

### Describe alternatives you've considered.

I didn't find a working alternative. Maybe if I could set the date of the post on the API so it doesn't show as new?

**Comment by Nutomic** [comment]
Relevant: https://github.com/LemmyNet/lemmy/pull/3907

**Comment by dessalines** [comment]
New just means new, regardless of communities. The scaled sort as mentioned above should solve this issue.
