### ISSUE TITLE
[Bug]: Consistent High postgres CPU usage from federation worker calling `community_follower`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#3958]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

#3605 Introduced a consistent, high-CPU postgres usage bug coming from the the federation worker queue.

The query is: `SELECT DISTINCT "community"."id", coalesce("person"."shared_inbox_url", "person"."inbox_url") FROM (("community_follower" INNER JOIN "community" ON ("community_follower"."community_id" = "community"."id")) INNER JOIN "person" ON ("community_follower"."person_id" = "person"."id")) WHERE (((("person"."instance_id" = $1) AND "community"."local") AND  NOT ("person"."local")) AND ("community_follower"."published" > $2))`

The source function used by the new federation worker is this one: https://github.com/LemmyNet/lemmy/blob/main/crates/db_views_actor/src/community_follower_view.rs#L18

Its called about 12x every second.

cc @phiresky 

### Steps to Reproduce

See above

### Technical Details

See above

### Version

main

**Comment by phiresky** [comment]
Is this with debug or release mode? The community_followers_recheck_delay
is once per instance per second on debug one once per minute on release

**Comment by phiresky** [comment]
It should also be very cheap since the published should be one minute in
the past so it should return 0 rows almost always

**Comment by dessalines** [comment]
Its with debug, I'm testing increasing that now.

I increased it to `10 seconds`, and there's still a ton of duped queries: 

![Screenshot_2023-09-10-11-02-58-748_com termux](https://github.com/LemmyNet/lemmy/assets/930215/c545aa11-6a0d-40bc-bf72-e32b4f69a60a)

They do complete fast, but they spike the CPU quite a bit.

**Comment by phiresky** [comment]
It's executed separately for every federated instance that's why there's many

**Comment by phiresky** [comment]
if they are indexed correctly they should take <1ms .. maybe an index is missing?

**Comment by dessalines** [comment]
I am running it with lemmy.ml's prod DB, but here are the indexes: 

![Screenshot_2023-09-10-11-08-46-576_com termux](https://github.com/LemmyNet/lemmy/assets/930215/5321fb75-7473-4101-b659-1e9d35ec2c59)

Could it be an issue with using `NaiveDateTime` ? I thought we should only be using `DateTime<UTC>`, but that is converting it to a naivedatetime:

`.filter(community_follower::published.gt(published_since.naive_utc()))`

**Comment by phiresky** [comment]
So frequent queries here is kinda expected with the current code. If there's 1000 instaences there's 1000 queues and each of them loads new followers every 60s, so that's ~15 per second. When I tested this it didn't seem to be much of an issue because each query was very cheap.

Now I'm running the query on a db and I am seeing 17ms exeution time so something is definitely wrong there, I'll check.

The execution count could also be reduced, both by increasing the recheck delay and by adding more complicated logic or another table.

**Comment by phiresky** [comment]
This is the query it replaces from 0.18.x `SELECT DISTINCT coalesce("person"."shared_inbox_url", "person"."inbox_url") FROM ("community_follower" INNER JOIN "person" ON ("community_follower"."person_id" = "person"."id")) WHERE (("community_follower"."community_id" = $1) AND  NOT ("person"."local"))`.

This query is(was) executed very frequently on an active instance and was in the top 3 most expensive queries if I remember correctly.

**Comment by dessalines** [comment]
Okay I've found one issue:

![Screenshot_2023-09-12-15-41-33-360_com termux](https://github.com/LemmyNet/lemmy/assets/930215/1e1430cb-0a70-48a8-aa7a-a1c24f33ccac)

Appears I need to add an index for `create index on person (local desc, instance_id);` which appears to fix it:

![Screenshot_2023-09-12-15-45-03-788_com termux](https://github.com/LemmyNet/lemmy/assets/930215/64e22493-3ea1-4efa-aa21-dcb9a9d18f86)

I'll have a PR for that in a sec.

**Comment by dessalines** [comment]
I'm not sure what the defaults should be, I'll let you comment on the PR for those.
