### ISSUE TITLE
Add Image Height & Width for image posts 

### ISSUE THREAD

**Issue by asolanki-in** [LemmyNet/lemmy#3961]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

API response for Post with image media doesn't contain height and width info for image.

- Height and Width are useful when needed to display image in Mobile client for some UI.

### Describe the solution you'd like.

height : 
width: 

keys needed to add in post data. 

### Describe alternatives you've considered.

Nothing

**Comment by xximj** [comment]
Already available on Pictrs which is the image service used by Lemmy:

https://crates.io/crates/pict-rs

Just forward your parameters to Lemmy's pictrs endpoint.

**Comment by asolanki-in** [comment]
So in list apis like post list, does thumbnail or full image contain image width and height or for each image I need to send one more api from pictrs just to get height & width????

My use case is for mobile device UI where dynamic hight is shown for image so I need real hight along with posts list in each object.

**Comment by asolanki-in** [comment]
I am referencing #3328
Same thing needed
