### ISSUE TITLE
Follow / auto-post / boost Mastodon (or other) account

### ISSUE THREAD

**Issue by davetapley** [LemmyNet/lemmy#3966]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I'm working on a bot which I'll probably send to http://botsin.space/,
and there are some Lemmy channels which might like to post the posts too.

### Describe the solution you'd like.

A channel can 'subscribe' to a Mastodon account (or other fedi actor) and will automatically post posts from that actor in to itself.

### Describe alternatives you've considered.

Someone can manually do it, or my bot could use the Lemmy API.

Former is onerous; latter would require me (bot developer) to have API access for channel.

### Additional context

Similar to:
- https://github.com/LemmyNet/lemmy/issues/3228

**Comment by Nutomic** [comment]
I dont think its worth implementing this. As you say it can be done perfectly well by bots.

**Comment by salif** [comment]
I think it would be nice if there is a separate instance in which we cannot create new communities, but when we register, a community is automatically created, in which only the moderator can post. Similar to reddit where `u/username` is `r/u_username`.
