### ISSUE TITLE
Cache dependencies in Travis build

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#397]
Looks like this is already configured, but is not working correctly.

https://travis-ci.org/dessalines/lemmy/builds/631833393#L224

**Comment by Nutomic** [comment]
Another problem in Travis is that a failure in `cargo clippy` does not cancel the rest of the build.

https://travis-ci.org/dessalines/lemmy/builds/632078480

**Comment by dessalines** [comment]
https://docs.travis-ci.com/user/job-lifecycle/

We should be okay, we're not doing any deploys or anything from it anyway.

**Comment by Nutomic** [comment]
Sure, it just seems like a waste of time and resources.

**Comment by dessalines** [comment]
I'm gonna try the recommends from this:

https://gist.github.com/jkcclemens/000456ca646bd502cac0dbddcb8fa307

**Comment by dessalines** [comment]
That did nothing. I'm gonna try the exact same thing the docker build does next.

**Comment by Nutomic** [comment]
The problem is that you put `cargo clean` into `before_cache`. I will let you commit that :p

**Comment by dessalines** [comment]
Isn't possible now with the docker travis builds.
