### ISSUE TITLE
[Bug]: Users not notified when mentioned in post

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#3974]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

If someone mentions a user with @ in a post, the mentioned user is not notified. Mentions only work with comments.

### Steps to Reproduce

1. Create a new post with a user mention
2. The mentioned user does not get a notification

### Technical Details

N/a

### Version

0.18.4

**Comment by Nutomic** [comment]
This is simply not implemented yet https://github.com/LemmyNet/lemmy/issues/715
