### ISSUE TITLE
Find UI testing framework.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#398]
Current UI testing instructions:

- Create a new user.
- Log out, log back in.
- Create a community.
- Create a post on community.
- Remove and restore it.
- Create a comment on community.
- Goto search page, search your comment text.

**Comment by richardj** [comment]
Cypress could be a suitable candidate for that. https://www.cypress.io

**Comment by zacanger** [comment]
+1 for Cypress, I found it much easier to work with and more reliable than Selenium.
