### ISSUE TITLE
a way to change and save comment sorting for all posts

### ISSUE THREAD

**Issue by battierp** [LemmyNet/lemmy#3984]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

comments are always sorted by hot with no way to change it.

### Describe the solution you'd like.

a setting to pick which way comments should be sorted between 'hot, old, new, top' that doesn't change.

### Describe alternatives you've considered.

.

**Comment by dessalines** [comment]
This is already done, since your local user setting already has a saved field, called `default_sort_type: SortType` . 

The `list_post` and `list_comment` routes take in an optional `SortType`, and `CommentSortType`. lemmy-ui's front end already uses this, and other UIs could too.
