### ISSUE TITLE
[Bug]: an Ampersand sign '&' is incorrectly handled in post title

### ISSUE THREAD

**Issue by r-hmn** [LemmyNet/lemmy#3987]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Both via lemmy API and lemmy ui, 
if i use the `&` sign in the title, it is replaced with `&amp;` and it appears in the UI 
if i use the text `&amp;` text in the title, it stays visible in the UI

### Steps to Reproduce

1. go to the wesite and navigate to a post of yours
2. edit the post
3. change the title to contain the `&` sign.
4. when applying the change.
5. in the title it now contains the text `&amp;`

### Technical Details

This on lemmy.ml (says BE: 0.18.4 in the bottom, at 24th sept'23)
and also on my own home server (BE: 0.18.4).

I noticed it because a script posts using the lemmy post API, and a title appeared with &amp; text in it.

### Version

0.18.4

### Lemmy Instance URL

lemmy.ml

**Comment by K4LCIFER** [comment]
Related: #3774, #3754

**Comment by M4rtineski** [comment]
Same with community displayed names (or at least that was the case some time ago when I last tried that).

**Comment by oblyn** [comment]
Same in post body

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/4024
