### ISSUE TITLE
Allow admins to hide deleted posts in their feeds

### ISSUE THREAD

**Issue by axeleroy** [LemmyNet/lemmy#3989]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

As I understand it, posts deleted by users, moderators and instance admins are "soft-deleted" so that there is a trace of them in the modlog. They also appear on instance admins personal feed with a "deleted" flag.

I get the appeal for some instance admins, but as I don't have any communities on my instance, these deleted posts are bloating my user feed and I would like to filter them out.

### Describe the solution you'd like.

I thought of a user preference that would allow admin users to opt-out from seeing deleted posts in their feeds. The filtering would ideally happen in the back-end to save bandwidth and allow the feature to work with third-party clients without any work on their side.

### Describe alternatives you've considered.

I have considered opening an issue on my current mobile client and creating CSS rules to hide deleted posts on lemmy-ui but I don't feel that these are the most efficient solutions.

**Comment by Nutomic** [comment]
Fixed in https://github.com/LemmyNet/lemmy/pull/3286

**Comment by axeleroy** [comment]
Hello,

I saw that pull request but thought it was already released and assumed it was fixing another issue, my bad. Is it in any stable release yet?

**Comment by Nutomic** [comment]
It will be in 0.19
