### ISSUE TITLE
Reference communities users and posts by URL or UUID

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#399]
This is needed for federation, because a simple integer id doesnt make any sense when the object actually lives on another instance. We can probably do this by using the URL instead, eg `!main@dev.lemmy.ml` or `@user@dev.lemmy.ml`.

For posts, we might want to use UUIDs, like Peertube does:
```
https://peertube.social/videos/watch/5a6133b8-3e0c-40dc-b859-69d0540c3fe5
```

**Comment by dessalines** [comment]
The `User_` object has a column named `fedi_id`, that right now is the instance name, that should work. Let me know if you need me to add that elsewhere, like to `UserView`.

**Comment by Nutomic** [comment]
Okay that should be good, but we also need to change the frontend to not require the numeric IDs. Honestly I'm not sure yet how this is going to work exactly, its something we need to investigate.

**Comment by Nutomic** [comment]
It might not be exactly the same as this issue, but Peertube has a table "actors", where it stores information about both local and remote users. That is basically all the information that ActivityPub has about an actor.

![Screenshot_20200103_173817](https://user-images.githubusercontent.com/1044450/71735883-82c92f00-2e47-11ea-8dd2-348a4cad3414.png)

**Comment by dessalines** [comment]
A lot of these can be extrapolated from just the `username` and `fedi_id` in the user table. I can build them into the `UserView` as we need.

**Comment by Nutomic** [comment]
For Lemmy yes, but if we want to federate with other platforms, we also need to store stuff like the inboxUrl, outboxUrl etc. Besides, we can probably also extrapolate the `fedi_id` from username and instance name.

**Comment by dessalines** [comment]
I can do a DB migration to add these fields to the user table. Also that `fedi_id` column in the user table was just a placeholder, we can change its name or remove it.

But ya, groups (communities) and person (users) might need a lot more columns added to the community and user tables, let me know what columns I should add to either of them.

**Comment by Nutomic** [comment]
I can probably take care of the database myself, the issue is more about investigating what exactly is needed.

**Comment by Nutomic** [comment]
Guess this wont be needed after all.
