### ISSUE TITLE
Allow the posting of content directly to a user account

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#3990]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently, if a user wishes to post content related to themself (think of a platform like twitter, or mastodon), they need to create their own community, and post content to that. There is no way for a user to post directly to their account.

### Describe the solution you'd like.

Add the functionality to allow a user to post content directly to their user -- the user, itself, would act as a community with one member with posting priveleges.

### Describe alternatives you've considered.

none.

### Additional context

This ties in with #3903.

This issue could be incompatbile with Activity Pub, and I may be overthinking it in that it may be best to just make a community.

**Comment by Nutomic** [comment]
We have no intention to add such functionality. As you said there are already plenty of ways to do this.

**Comment by K4LCIFER** [comment]
> As you said there are already plenty of platforms that support it (or create a community).

Would it not aid in fediverse compatibility? If you try and look at users from Mastodon through Lemmy, for example, you don't see any content e.g. @BrodieOnLinux@linuxrocks.online. This user should have many posts, but none show up. I was under the presumption that this was due to Lemmy not being compatible with a user posting to their profile which is what I was assuming that Mastodon was doing. Please correct me if I am wrong; this idea is not founded upon any documentation, or anything technical.

**Comment by Nutomic** [comment]
That is correct, and there is no reason to reimplement functionality in Lemmy that is already much better handled in dozens of existing platforms.
