### ISSUE TITLE
[Bug]: IPV6 only instance tries to federate with non-ipv6 capable instances and don't show an error

### ISSUE THREAD

**Issue by machado2** [LemmyNet/lemmy#3992]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

My instance only has IPV6 connectivity, it is listing other instances that are not able to talk back to it, and federation breaks.

In the case of lemmy.world, it can accept connections trough the Cloudflare proxy, but it can't connect back to mine, as their underlying server is probably not IPV6 capable.

It would be interesting if Lemmy detected this situation, and made it visible what instances it won't be able to federate with. It's also hard to find what other instances would be federated with it

### Steps to Reproduce

1. Create a new lemmy instance in an ipv6-only server
2. Subscribe to some communities on lemmy.world
3. Subscriptions get stuck at pending

### Technical Details

This is my log

[lemmy.log](https://github.com/LemmyNet/lemmy/files/12742693/lemmy.log)

I'm running it into a dual stack microk8s, on Ubuntu 22.04

### Version

BE: 0.18.4

### Lemmy Instance URL

https://lemmy.fbmac.net/

(I moved the instance behind a Cloudflare proxy as a workaround now)

**Comment by machado2** [comment]
I put lemmy.fbmac.net behind a Cloudflare proxy for now, but I believe it should be handled with at least an error message or something

**Comment by Nutomic** [comment]
It sounds like federation fails in your case is because lemmy.world cant connect to an IPv6 address. I cant think of any way your Lemmy instance could know about that, if anything lemmy.world could show a warning that messages to your instance arent getting delivered.

**Comment by Nutomic** [comment]
Errors are already shown in the logs.
