### ISSUE TITLE
[Bug]: The single quote character, ', is being double sanitized on edit

### ISSUE THREAD

**Issue by rhit-frantzag** [LemmyNet/lemmy#4003]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

This bug is related to #3754, #3774, and #3987. Currently, when a post, comment, or sidebar is edited, all ' characters will be replaced with &;#x27;. Upon additional edits, &amp; will be repeatedly prepended to the string, as shown in this image:
![image](https://github.com/LemmyNet/lemmy/assets/95260668/4ccb3739-56f4-4eb7-a9e9-7339d4622c6d).

### Steps to Reproduce

1. Post a comment, post, or add sidebar text containing ' on an affected instance.
2. Edit the text that contains the ', change nothing, and submit.
3. The bug will occur and will occur again upon each submitted edit.

### Technical Details

[lemmy_log.txt](https://github.com/LemmyNet/lemmy/files/12769981/lemmy_log.txt)
My Lemmy instance is running on an Ubuntu VPS. The browser prints no console errors.

### Version

0.19.0rc1

### Lemmy Instance URL

lemmy.thesanewriter.com

**Comment by MV-GH** [comment]
The amount of problems the sanitation brought in, makes me wonder if its even worth it. It's only a problem on web clients. And they should just properly sanitize it. The app clients don't need this at all.

**Comment by TheSaneWriter** [comment]
I think that the database should store it as raw text and then it should be up to the client to format it correctly.
