### ISSUE TITLE
Sorting Saved Posts

### ISSUE THREAD

**Issue by CoachDom** [LemmyNet/lemmy#4014]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Sometimes when saving a post you can't see it in the "saved" tab because the post was made months before.

### Describe the solution you'd like.

Be able to sort saved posts by "When added" or "Created"

### Describe alternatives you've considered.

Mayhaps just having hard coded that saved posts are sorted by when they were "saved" rather when they were created.

**Comment by Nutomic** [comment]
Use the search: https://github.com/LemmyNet/lemmy/issues/3229
