### ISSUE TITLE
[Bug]: Postgres slowly eats up memory until OOM and then container restarts

### ISSUE THREAD

**Issue by HorseJump** [LemmyNet/lemmy#4017]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

On 0.18.5 my postgres docker container slowly eats up all my memory, starting with swap, until OOM, at which point the container restarts and begins that process over again. 

### Steps to Reproduce

1. Start postgres 15-alpine docker container and wait for OOM and container to restart.

### Technical Details

Running on Ubuntu with Lemmy v0.18.5. Currently collecting logs. 4GB of RAM, 2GB swap.

![image](https://github.com/LemmyNet/lemmy/assets/23646285/efdad11e-c17f-416f-bf3f-8f8660596349)

### Version

0.18.5

### Lemmy Instance URL

midwest.social

**Comment by phiresky** [comment]
can you attach your non-default postgresql settings?  especially shared_buffers, work_mem, etc

**Comment by Illecors** [comment]
```
max_connections = 1000
shared_buffers = 256MB
effective_cache_size = 768MB
maintenance_work_mem = 64MB
checkpoint_completion_target = 0.9
wal_buffers = 7864kB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 655kB
min_wal_size = 1GB
max_wal_size = 4GB
```
This is on a single core 2GB ram + 2GB swap VM running postgres only.

**Comment by HorseJump** [comment]
```
effective_cache_size = 1536MB
maintenance_work_mem = 128MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 2621kB
min_wal_size = 1GB
max_wal_size = 4GB
temp_buffers = 128MB
max_stack_depth = 4MB
superuser_reserved_connections = 8
track_io_timing = on
max_connections = 100
```

**Comment by phiresky** [comment]
i don't see anything obvious in those settings but pg shouldn't eat unlimited memory regardless of what lemmy does

**Comment by airjer** [comment]
I'm having the same issue, although I'm having to shut down and restart.

**Comment by fgilcc** [comment]
Seeing this issue on 0.19.0-beta.6
Not sure if related or this is the expected behavior but database connections(100) are always maxed out, making it so I can't connect to the database from another computer in the same network.

**Comment by phiresky** [comment]
It's expected behaviour for lemmy to use all connections it is set in the config to. If the configs shipped with docker/ansible configure the max_connections of postgresql to be the same as the pool size in lemmy then that would be something to fix

**Comment by Illecors** [comment]
Where is lemmy setting the connection pool size? It wasn't anywhere in docker compose or lemmy.hjson.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/blob/main/config/defaults.hjson#L37

**Comment by Illecors** [comment]
Thank you! Changed pool_size to 50, will see if the issue persists.

**Comment by dessalines** [comment]
Can re-open if its still a problem. On large instances, we've found lemmy does have memory issues, but not postgres.
