### ISSUE TITLE
[Bug]: Legacy pagination doesn't work with Subscribed feed when user is authenticated

### ISSUE THREAD

**Issue by maxpoulin64** [LemmyNet/lemmy#4019]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

On 0.19.0.beta5 and 0.19.0.rc1, legacy pagination of the Subscribed feed when the user is authenticated fails with "CouldntGetPosts: legacy pagination cannot be combined with v2 pagination" despite v2 pagination not being used.

This is also reproducible on voyager.lemmy.ml.

### Steps to Reproduce

1. Create an account on voyager.lemmy.ml and log in
2. Subscribe to enough communities for the Subscribed feed to be more than one page long
3. Go back to the home page, and select the Subscribed feed. Sorting does not matter.
4. Navigate to page 2 of that feed.

Hitting the API directly results in the same issue, so it is not a UI issue. But it only occurs when the user is authenticated, when browsing anonymously everything works just fine.

### Technical Details

When hitting page 2 (or any > 1) of the subscribed feed with a valid Authorization token, Lemmy produces the following log:

```
2023-10-04T23:12:11.321353Z  WARN lemmy_server::root_span_builder: CouldntGetPosts: legacy pagination cannot be combined with v2 pagination
   0: lemmy_apub::api::list_posts::list_posts
           with data=Query(GetPosts { type_: Some(Subscribed), sort: Some(New), page: Some(3), limit: Some(20), community_id: None, community_name: None, saved_only: None, liked_only: None, disliked_only: None, page_cursor: None }) local_user_view=Some(LocalUserView { local_user: LocalUser { REDACTED } })
             at crates/apub/src/api/list_posts.rs:20
   1: lemmy_server::root_span_builder::HTTP request
           with http.method=GET http.scheme="http" http.host=lemmy.max-p.me http.target=/api/v3/post/list otel.kind="server" request_id=1ee7a779-8bf3-47e1-b2ea-637be1bd179e
             at src/root_span_builder.rs:16
```

Above log was produced with the following request:

```
~> curl "https://lemmy.max-p.me/api/v3/post/list?page=3&limit=20&sort=New&type_=Subscribed" -H "Authorization: Bearer $AUTH" 
{"error":"couldnt_get_posts"}
```

### Version

BE: 0.19.0-rc.1, BE: 0.19.0-beta.5, BE: 0.19.0-beta.6

### Lemmy Instance URL

https://voyager.lemmy.ml/

**Comment by Nutomic** [comment]
@phiresky The error message comes from [here](https://github.com/LemmyNet/lemmy/blob/main/crates/db_views/src/post_view.rs#L634). The error condition definitely looks wrong, only because `offset != 0` doesnt mean its invalid. Maybe you meant to check `offset != 0 && self.page_after.is_some()`? (ie cursor pagination enabled and offset provided)

**Comment by maxpoulin64** [comment]
I've tested that fix and it seems to work perfectly for me. I've opened #4030 with that change, so it can just be merged when @phiresky confirms this is the correct fix.
