### ISSUE TITLE
Add an additional federation setting: "Only federate with user-verified / non-open instances"

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4029]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I've been looking into the issue of vote-manipulation, and we're seeing a **ton** of votes from instances with no user verification. 

These are bot accounts who spam create users, then script actions to vote a certain way on posts and comments. When you examine their profiles, you can see a ton of votes, with zero posts or comments.

Reddit thrives on this type of bot-manipulation to push certain agendas, so we have to see what we can do to prevent it on lemmy.

### Describe the solution you'd like.

Add another federation setting: `Only federate with user-verified instances`. And on an apub receive, if that setting is `true`, then block the request if its from an instance without user verification.

This also *may* need to periodically check the RegistrationType, but maybe that might be periodically refetched.

### Describe alternatives you've considered.

NA

### Additional context

NA

**Comment by Nutomic** [comment]
You are talking about disabling federation with instances that have open registration? That would be extremely easy to circumvent, the admin can enable applications and then run a bot on the admin account which automatically accepts all registrations. Or close registrations after a couple thousand accounts are created. Or rewrite API responses to pretend that registration applications are required. Basically it wouldnt help anything.

**Comment by dessalines** [comment]
I suppose that's true. The only real way to stop this `allowlist` federation, where you only federate with trusted instances.

I'm trying to think of ways to have open federation, but still prevent bot manipulation, and maybe there's just no real way to do that.

**Comment by Nutomic** [comment]
Maybe https://github.com/LemmyNet/lemmy/issues/1487
