### ISSUE TITLE
allow for code block text

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/lemmy#4031]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

dyk how in chatgpt, theres this special box code gets put in that respects indentation and colors the text based on what it is (e.g. boolean). 

### Describe the solution you'd like.

a clickable code block button beside the bold and italic options (and maybe even the ability to run said code locally on a device?)

### Describe alternatives you've considered.

.

### Additional context

https://workspace.google.com/marketplace/app/code_blocks/100740430168

like this

**Comment by Nutomic** [comment]
Duplicate

https://github.com/LemmyNet/lemmy-ui/issues/1972
