### ISSUE TITLE
Option for Limited Federation

### ISSUE THREAD

**Issue by DraconicNEO** [LemmyNet/lemmy#4037]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Certain instances may have a lot of problematic communities or have people creating problematic communities, vote manipulation, or other issues that may not warrant complete de-federation but are still problematic to users on the instance.

### Describe the solution you'd like.

I think it would be good if we got a partial defederation system just like Mastodon instances have.
This could allow Admins to restrict ceratin aspects of Federation such as choosing to block all communites from the instance, as well as voting from said instance while still allowing its users to post and comment to your own instance just with certain restrictions.

### Describe alternatives you've considered.

There aren't really any good alternatives, communites can be removed but that doesn't prevent newly created ones from federating, and there's nothing much that can be done about vote manipulation except banning those users specifically.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/issues/3662
