### ISSUE TITLE
Add a "Controversial" sort option

### ISSUE THREAD

**Issue by c0mmando** [LemmyNet/lemmy#4043]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Once posts get -1 downvote it get removed from certain feeds and makes it difficult to find downvoted posts. Anyone with a few bots can make content disappear for 90% of Lemmy users...

### Describe the solution you'd like.

My suggestion is to add a sort by downvotes or "controversial" sorting option to increase transparency. 

### Describe alternatives you've considered.

i haven't found any alternatives

**Comment by MV-GH** [comment]
Contoversial has already been added in 0.19 #3205
