### ISSUE TITLE
[Bug]: Excessive storage usage for thumbnails

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#4053]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

While looking at the code for generating link metadata I noticed a major problem with the way thumbnails are generated: In [this line](https://github.com/LemmyNet/lemmy/blob/main/crates/api_common/src/request.rs#L356) images are fetched using pictrs endpoint `GET /image/download` which stores the full size image in pictrs. This same fullsize image is then returned as "thumbnail", there is no resizing done at all. To confirm this I looked at some API responses from lemmy.ml, and in fact `post.url` and `post.thumbnail_url` always point to an identical image with the exact same dimensions (sometimes over 1000px). Thumbnails are also generated whenever a remote post is received, so even an instance with no local user activity will quickly grow in storage size.

To resolve this I think pictrs should add an option like `GET /image/download?resize={pixels}`. If an image is larger than this, it should be downscaled before storing, and the full sized image discarded. It would also be good if we could test image functionality as part of api tests to ensure that thumbnails are always below a certain size.

cc @asonix @dessalines @phiresky

**Comment by Nutomic** [comment]
The problem is that pictrs stores the original images without any size limit, so they may be thousands of pixels and multiple MB. That means over the long term a lot of storage is used which will make instance hosting more expensive. So there needs to be some size limit, even if its 500 or 1000 pixels. Besides the `thumbnail_url` field is completely useless now if its identical to the `url`.

**Comment by Nutomic** [comment]
Thats only for gifs and wont apply to other file formats. There may be similar settings for jpeg etc, but thats not a good solution because the main image can be large, only thumbnails should be small.

**Comment by dessalines** [comment]
This can be done via nginx, or better, using the new pictrs `"ProxyAllImages"` setting. 

> So this is indeed a Lemmy issue, because PictRS cannot know if the upload is a thumbnail or user upload. So Lemmy needs a way to signal a lower max filesize to PictRS when storing a thumbnail.

Lemmy doesn't store images, only pictrs does. So the pictrs size limits apply to both uploads and thumbnails.

**Comment by Nutomic** [comment]
This issue is still valid. While there is a general size limit in pictrs, it cannot distinguish between thumbnails which should be limited to 100px or so, and post images which should be 1000px or larger. The problem does not happen when using image proxy mode, but not all instances do. 

So to resolve this we still require a parameter `GET /image/download?url={url}&resize={int}` in pictrs, which downscales images before storing them.

**Comment by SorteKanin** [comment]
Just to give my perspective on this issue: I'm currently experiencing quite rapidly increasing storage demands. I now have 300 GB of object storage and I can assure you that roughly 0% of that is from local users.

All remote images seem to be downloaded to my instance (not just thumbnail sizes, full size images). See for instance this post: https://feddit.dk/post/7991887

It is not a local post or a local user or anything, yet the image link is the local domain so the image has been downloaded in full size to my instance.

If this is not intended behavior, that's surprising cause this has been going on ever since I started my instance. But it does seem very undesirable.

I basically want to not download any remote images (maybe not even thumbnails) and only allow local users to upload images.

Hope that helped give some context :)

**Comment by asonix** [comment]
It seems I forgot to add it to the docs but pict-rs' download endpoint does support the same arguments as uploads

That said, remote images make more sense to be used with the proxy endpoint, which should automatically delete locally cached images if they haven't been accessed in a while
