### ISSUE TITLE
[Bug]: `UserSettingsBackup` needs `ts_rs` exports, and should be in api_common crate

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4054]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Copy of a comment from lemmy-js-client:

@Nutomic Since the UserSettingsBackup struct is not in the api_common crate like the other API responses / requests, and it doesn't use ts-rs, its not properly creating the type, so front ends can't use it.

I tried for a bit to fix it, but unfortunately the structs use ObjectId<ApubCommunity... which isn't accessible from api_common (and those should be vectors of DbUrl s anyway).

### Steps to Reproduce

NA

### Technical Details

NA

### Version

main

### Lemmy Instance URL

main

**Comment by Nutomic** [comment]
This was intentional, clients are not supposed to parse that struct but directly download it as a file.

**Comment by dessalines** [comment]
I spose I could treat it as a string / `any` then in js.

**Comment by Nutomic** [comment]
We can also change the return type of `export_settings` in Rust from Json to String if that helps.

**Comment by dessalines** [comment]
We'll know once we start to add this into lemmy-ui if it needs changes.
