### ISSUE TITLE
Question: How can I search for posts from a specific user? A Lemmy equvialent of "author:oneechan69 phrase" on Reddit?

### ISSUE THREAD

**Issue by Oneechan69** [LemmyNet/lemmy#4056]
### Question

On Reddit I can search `author:oneechan69 phrase` to search for all instances of phrase in post and comments by u/oneechan69. I want to do that on Lemmy as well.

**Comment by MV-GH** [comment]
Possible through the API /search , there is a creator_id option

https://mv-gh.github.io/lemmy_openapi_spec/swagger_ui.html#/Miscellaneous/get_search
