### ISSUE TITLE
Boost mastodon posts

### ISSUE THREAD

**Issue by snaggen** [LemmyNet/lemmy#4060]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I haven't seen that it is possible to Boost mastodon posts, and wonder if that would be interesting.

### Describe the solution you'd like.

As I see it in my head, you would boost a mastodon post to get it as a post in the lemmy community, and it would bring in all the comments from the original post also (since the post actually would be the original post, just boosted). 

### Describe alternatives you've considered.

Maybe autodetect links to mastodon posts, and treat them as boosts?

**Comment by Nutomic** [comment]
Thats not possible, a boost doesnt indicate which Lemmy community it targets. Maybe checkout https://github.com/LemmyNet/lemmy/issues/3906

**Comment by snaggen** [comment]
My idea was to let the Lemmy community boost a Mastodon post somehow, to bring it in ...

**Comment by erlend-sh** [comment]
I don’t know how to put this into a feature request, but the baseline of interop I want between Lemmy and Mastodon is for whatever is needed for /c/microblogmemes to [not have to re-share mastodon posts by screenshot](https://writing.exchange/@erlend/111047919886325959).

![IMG_2094](https://github.com/LemmyNet/lemmy/assets/583842/3ecd24fc-68ed-4c08-b469-6b59295f5a4e)
