### ISSUE TITLE
Prevent a user from posting in communities when they are banned from the Instance

### ISSUE THREAD

**Issue by DraconicNEO** [LemmyNet/lemmy#4068]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When a user is banned from an Instance they are still able to post, comment, and vote in the copy of the community their posts and comments just don't get federated, this can cause issues for the Admins on the user's home instance as it essentially becomes unmoderated meaning said user can say and post whatever they want without any mod intervention if the community's mods are located in the instance the user is banned from (which is how it is most of the time). 
with the only line of defense being their home server's instance admin, if it even gets reported to them at all.

### Describe the solution you'd like.

Apply something like the bans from communities to the user being banned from the instance for communities hosted by the banning instance to prevent them from posting or commenting in those communities until their instance ban has expired. This would prevent them from posting spam or malicious content to said communities while also giving a clear indicator that they have been banned. Could be a message saying "You have been banned from this instance and its communities". 

This would only apply to communities hosted by the instance that banned them, for communities not hosted by the banning instance it would work exactly the same as it does now, the instance that banned them just wouldn't be able to see their content.

### Describe alternatives you've considered.

N/A

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/issues/3399
