### ISSUE TITLE
[Bug]: 0.19 bearer authorization is not reliable, most likely due to CACHE

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#4078]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I am writing a Backwards Compatible Lemmy API. I was testing the auth. Half the time I would throw an error that I am not authenticated. After some investigating through cURL. It led me the cause is that Lemmy seems to return cached version of the unauthenticated response.

![image](https://github.com/LemmyNet/lemmy/assets/67873169/e05bc1ae-4034-48cd-a5b4-e2f2a62efb87)

x-cache-status: HIT

### Steps to Reproduce

*You can have this token, its just one of my testaccounts*
*You will probably have to try a few times such is the nature of caches*

1.  curl --location 'https://voyager.lemmy.ml/api/v3/user/validate_auth' --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MCIsImlzcyI6InZveWFnZXIubGVtbXkubWwiLCJpYXQiOjE2OTc3MzY2MjR9.c1nvitcaoMj5FSSDfEasAVPj86WMCXOwsR3n8u7s7NM'
2. curl --location 'https://voyager.lemmy.ml/api/v3/user/validate_auth' 
3. curl --location 'https://voyager.lemmy.ml/api/v3/user/validate_auth' --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MCIsImlzcyI6InZveWFnZXIubGVtbXkubWwiLCJpYXQiOjE2OTc3MzY2MjR9.c1nvitcaoMj5FSSDfEasAVPj86WMCXOwsR3n8u7s7NM'

Third should also be not_logged_in error

### Technical Details

During my investigation I noticed that the third response above return `x-cache-status: HIT`

### Version

0.19.0

### Lemmy Instance URL

voyager.lemmy.ml

**Comment by MV-GH** [comment]
#4074 possibly related

**Comment by Nutomic** [comment]
It was a problem with nginx caching, had to add the new auth header/cookie to no cache directive:
```
# Response cache for unauthenticated users
proxy_cache lemmy_cache_voyager.lemmy.ml;
proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
proxy_cache_valid 1m;
proxy_no_cache $cookie_jwt $cookie_auth $http_authorization;
add_header x-cache-status $upstream_cache_status;
```

**Comment by gribodyr** [comment]
Hi @Nutomic,

For some reason this does not solve the issue for me. I am on the main branch both on lemmy and on lemmy-ui. Any other info I could provide to help troubleshoot?

**Comment by Nutomic** [comment]
@gribodyr You are having this issue on your own server, not voyager.lemmy.ml? Did you enable response caching via nginx or another way? It could also be a separate issue, you need to post more details.

**Comment by MV-GH** [comment]
voyager seems to be working great rn

**Comment by gribodyr** [comment]
@Nutomic 

Preamble: after I wrote this message, I realized that it might be a wrong thread for it. Please feel free to point me in the right direction.

So here's some more information about my setup. 

1. I am deploying Lemmy to an LXC container running on Proxmox using the approach known as "Install From Scratch" (yes, I know it is unsupported but for reasons beyond this message I need to stick to it).
2. I have successfully deployed the lemmy `main` branch on the default port, and I can confirm it is working fine because I can connect to it using Jerboa. 
3. I have also deployed the lemmy-ui `main` branch, and it _sorta_ works (explanation below).
4. Both backend and front-end are sitting behind nginx. Here's my config: 
```
user@lemmy:~$ cat /etc/nginx/sites-enabled/lemmy.conf 
limit_req_zone $binary_remote_addr zone=REDACTED_ratelimit:10m rate=1r/s;
proxy_cache_path /var/cache/nginx keys_zone=lemmy_cache_REDACTED:1m;

server {
    listen 80;
    server_name REDACTED;
    # Hide nginx version
    server_tokens off;

    # Upload limit, relevant for pictrs
    client_max_body_size 20M;

    # Enable compression for JS/CSS/HTML bundle, for improved client load times.
    # It might be nice to compress JSON, but leaving that out to protect against potential
    # compression+encryption information leak attacks like BREACH.
    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
    gzip_vary on;

    # Various content security headers
    add_header Referrer-Policy "same-origin";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";
    add_header X-XSS-Protection "1; mode=block";

    location / {
      proxy_http_version 1.1;

      set $proxpass "http://127.0.0.1:1234";  
      if ($http_accept ~ "^application/.*$") {
          set $proxpass "http://localhost:8536";
      }
                        
      if ($uri ~ "^(.*)/(api|pictrs|feeds|nodeinfo|.well-known)(.*)") {
          set $proxpass "http://127.0.0.1:8536";
      }
 
      if ($request_method = POST) {
          set $proxpass "http://127.0.0.1:8536";
      }

      # Response cache for unauthenticated users
      proxy_cache lemmy_cache_REDACTED;
      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
      proxy_cache_valid 1m;
      proxy_no_cache $cookie_jwt $cookie_auth $http_authorization;
      proxy_cache_bypass $cookie_jwt $cookie_auth $http_authorization;
      add_header x-cache-status $upstream_cache_status;

      proxy_pass $proxpass;
    }
}
```

With this setup I can open the home page, I can setup the default website, etc. However, if I logout and then try to log back in, the UI shows the "auth_cookie_insecure" popup. The only solution is to clear the cookies to be able to log back in.

However, when I downgrade `lemmy` and `lemmy-ui` to `0.18.5`, I have a different problem. When the UI makes calls to the API, the server log shows this: 
```
Oct 22 03:19:20 lemmy lemmy_server[10568]: 2023-10-22T03:19:20.464475Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: Query deserialize error: missing field `auth`
```
And there's a missing field `auth` error message in the JS console. Obviously, login and doesn't work either.

**Comment by aeharding** [comment]
> With this setup I can open the home page, I can setup the default website, etc. However, if I logout and then try to log back in, the UI shows the "auth_cookie_insecure" popup. The only solution is to clear the cookies to be able to log back in.

This issue is reported in #4074
