### ISSUE TITLE
Send proper cache-control headers

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#408]
So that common files like js or css dont have to be loaded every single time. Later we can also setup nginx to cache requests, so that things like rss dont go to the backend every time.

**Comment by Nutomic** [comment]
https://yerbamate.dev/dessalines/lemmy/pulls/12

**Comment by dessalines** [comment]
Also add proxy_cache to nginx:

https://yerbamate.dev/nutomic/peertube-compose/src/branch/master/templates/nginx.conf#L18
https://yerbamate.dev/nutomic/peertube-compose/src/branch/master/templates/nginx.conf#L86

**Comment by Nutomic** [comment]
Another attempt to implement this:

https://yerbamate.dev/LemmyNet/lemmy/pulls/41

**Comment by ptman** [comment]
etags as well

**Comment by Nutomic** [comment]
Okay that should be good now, the only question is what value we should send for cache-control. Right now I have `cache-control: public, max-age=*1 year*". But I dont know how this will work with Lemmy updates (like do new html/css/js file versions get a different hash)? The header is applied to all files whose mime type matches the regex `^((text|image)/.+|application/javascript)$`.

@ptman etag is already added by actix, although I'm not sure how exactly this relates to cache-control.

**Comment by dessalines** [comment]
I bet the etags and last-modified are smart enough to make sure page refreshes on new versions will work fine.

**Comment by dessalines** [comment]
Fixed by 21e913192a8355fe64220ef168cef901f1af4258
