### ISSUE TITLE
Issue: Missing translation file causes build failure

### ISSUE THREAD

**Issue by SDing-14** [LemmyNet/lemmy#4117]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When building the Lemmy project, I encountered an error related to a missing translation file: translations/email/en.json. The build process couldn't locate this file, leading to a failure.

I noticed the following code segment under LEMMY/crates/utils/build.rs is the cause of this issue:

fn main() -> Result<(), Box<dyn std::error::Error>> {
  rosetta_build::config()
    .source("en", "translations/email/en.json")
    .source("fi", "translations/email/fi.json")
    .source("ko", "translations/email/ko.json")
    .source("pt", "translations/email/pt.json")
    .fallback("en")
    .generate()?;

  Ok(())
}

### Steps to Reproduce

This problem happened when I was building the project. The error was specifically related to directories:   
Error: FileRead { file: "translations/email/en.json", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }

I had to modify the code to this to make the app to be built:

fn main() -> Result<(), Box<dyn std::error::Error>> {
  rosetta_build::config()
    .source("en", "/lemmy/lemmy-ui/lemmy-translations/email/en.json")
    .source("fi", "/lemmy/lemmy-ui/lemmy-translations/email/fi.json")
    .source("ko", "/lemmy/lemmy-ui/lemmy-translations/email/ko.json")
    .source("pt", "/lemmy/lemmy-ui/lemmy-translations/email/pt.json")
    .fallback("en")
    .generate()?;

  Ok(())
}

### Technical Details

Log output: I've encountered an issue related to a missing file: translations/email/en.json which caused the build process to fail. The relevant part of the code should be:
rosetta_build::config()
  .source("en", "translations/email/en.json")
  .source("fi", "translations/email/fi.json")
  .source("ko", "translations/email/ko.json")
  .source("pt", "translations/email/pt.json")
  .fallback("en")
  .generate()?;

Operating System: macOS Big Sur

Browser console errors: No browser console errors were mentioned.

### Version

BE: 0.18.5

**Comment by MV-GH** [comment]
Did you clone it recursively? (also the submodules) ? `git clone https://github.com/LemmyNet/lemmy.git --recursive`

**Comment by SDing-14** [comment]
> Did you clone it recursively? (also the submodules) ? `git clone https://github.com/LemmyNet/lemmy.git --recursive`

Yeah just figured out that I might cloned it in the wrong way.
