### ISSUE TITLE
Ability to choose default comment sort in user settings

### ISSUE THREAD

**Issue by iByteABit256** [LemmyNet/lemmy#4128]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I would like to be able to select a default comment sort just like with post sorting

### Describe the solution you'd like.

A new field in user settings for comment sort type, just like with the default post sort.

### Describe alternatives you've considered.

Related to #3796, but I think the user should be able to have this option too

**Comment by Die4Ever** [comment]
On Reddit, you can set the sorting order for comments on a per post basis. So sometimes the comments inside a megathread would be set to sorted by new by default. So I guess the post should be able to override the user's default?

**Comment by iByteABit256** [comment]
> On Reddit, you can set the sorting order for comments on a per post basis. So sometimes the comments inside a megathread would be set to sorted by new by default. So I guess the post should be able to override the user's default?

This sounds good and would solve my use case, maybe it should be opened as a separate issue alongside this though

**Comment by dessalines** [comment]
This should also have a site-wide setting, in addition to the user one.

**Comment by dessalines** [comment]
For this, we should either utilize the user's default_post_sort (with the post -> comment sort mapping), or add a default_comment_sort field. I'd probably prefer the first one, because that's already in place.
