### ISSUE TITLE
Question: Could Ansible script be adjusted to run only on the server?

### ISSUE THREAD

**Issue by danielkrajnik** [LemmyNet/lemmy#4132]
### Question

I'm installing a lemmy server and following recommendation in the documentation I went down the ansible route only to discover that it assumes that ansible will be installed on my local machine, given ssh root access to the server and configure everything itself... is that correct? That's a huge security no-no! Or is it assumed that you will set up two servers, one to manage lemmy server and the lemmy server itself?

Could it be simpler? Just an ansible playbook that runs on the lemmy server and configures itself? I will try docker instead, but I don't see why ansible couldn't be adjusted.

**Comment by Nothing4You** [comment]
Can you be more specific about which aspect of it would be a security no-no?
This topic would likely be better suited in https://github.com/LemmyNet/lemmy-ansible.

It should be possible to install ansible on the lemmy server and then just configure it to run against localhost, although I haven't tested that.

**Comment by danielkrajnik** [comment]
I am not familiar with ansible and I'd rather not install it just to deploy lemmy if there are [other options](https://github.com/ubergeek77/Lemmy-Easy-Deploy). You are right, I should have posted it in that repo.

I just wen through both methods (ansible and docker) and none of them seem to be viable in the long-term... How does ansible update the server? Do you need to install a cron job on your local machine to remotely update it every day or so? That seems very fragile.

**Comment by Nothing4You** [comment]
Ansible is typically running when you invoke it manually.
To update to a new Lemmy version, you'd update to a newer playbook from the lemmy-ansible repository and run the playbook again, or you'd increase the version numbers in the playbook in the appropriate places.

About your security/threat model, it always depends on what you are working with.
If you run a server for thousands of users you might have different requirements than when running a server for yourself and maybe a few friends.
If you have access to the lemmy server directly or via other server that you can access directly, there isn't really any security benefit of having a second server in place imo.
Ansible allows you to fully manage the configuration of a remote server over SSH, so you can basically have your entire desired configuration in Ansible and it will bring the server from its current state to the desired state when running the playbook.

I believe the majority of small instance operators will just install Ansible locally on their machine and deploy changes that way, but you're free to choose whatever you think makes most sense for you.

Which types of updates are you referring to?
Lemmy itself or OS updates for other services, such as the OpenSSH server, Docker, etc.?

Lemmy updates are not that frequent and automatic updates to newer versions are currently not recommended afaik.
OS updates not currently included in the playbooks, these are your own responsibility.
For Debian based systems, you'll likely want to look into unattended-upgrades.

**Comment by danielkrajnik** [comment]
> automatic updates to newer versions are currently not recommended afaik.

I see, thank you for clarifying. I may be just new to this, but I've deployed docker-mailserver, matrix, tor nodes etc. and all of them offered automated updates. Have I made wrong assumptions?

I've just finished deploying [Lemmy-Easy-Deploy](https://github.com/ubergeek77/Lemmy-Easy-Deploy) and it seems to take care of automated updates (with a help of a [simple cronjob](https://github.com/ubergeek77/Lemmy-Easy-Deploy/issues/79))? I'm not trying to crtiticise any approach, just trying to genuinely understand why automated updates wouldn't be included - perhaps I'm wrong and all of my servers will break in a few months time?

**Comment by Nothing4You** [comment]
I may have been wrong on automatic updates, but the lemmy deployment does not currently support them.

Personally, I usually avoid automatic updates for the applications themselves, as I usually want to review the release notes and potentially breaking changes before updating, so I can ensure everything still works well afterwards.

As a current example for Lemmy, 0.19 introduces breaking changes to how authentication works, which will cause issues with existing frontends and client, if they're not updated in time.

**Comment by danielkrajnik** [comment]
Thanks, that explain it. I will close the issue then, ok?

**Comment by Daniel15** [comment]
> only to discover that it assumes that ansible will be installed on my local machine, given ssh root access to the server and configure everything itself... is that correct? That's a huge security no-no! 

This is just how Ansible works in general. It's not specific to Lemmy. It's designed for centralized management - You have one system that runs Ansible, and it uses SSH to connect to all the other systems you want to manage. Running it against localhost should work fine, too. The remote systems only need to have SSH and Python3 installed. Ansible is very useful when you have a lot of servers and want them all to be configured the same way. 

Security-wise, it's fine if you follow some best practices.

- Disable SSH password authentication on your server (only allow keys).
- Generate an Ed25519 key with a long randomly generated password. 
   - Don't store the password on disk anywhere - load it into the SSH agent using `ssh-add` when you want to use Ansible
- Use a long randomly-generated password for the user (for sudo)
- Store this password in a encrypted vault using `ansible-vault`.

Of course, you can also run Lemmy in Docker. That's what I'm doing for my instance and it works well.

**Comment by danielkrajnik** [comment]
> Of course, you can also run Lemmy in Docker. That's what I'm doing for my instance and it works well.

That's what [I did as well](https://deljurgdn.dedyn.io/) (yay, it's working). I think any hobbyist/homelabber would do the same if it was more apparent in the documentation though. Do you think that it would be worthwhile to include a link to [Lemmy-Easy-Deploy](https://github.com/ubergeek77/Lemmy-Easy-Deploy)? It would strengthen the network if more people run their instances, no (and it seems like the author tooke already the burden of maintanance upon them).

I'm setting up mastodon now and experiencing similar lack of simple setup in the official documentation (although to much higher degree), which makes me a little sceptical about the intentions behind the fediverse/activitypub (hopefully I'm wrong).

**Comment by Nutomic** [comment]
@danielkrajnik By all means add links to different installation methods to the [documentation](https://github.com/LemmyNet/lemmy-docs/blob/main/src/administration/administration.md).
