### ISSUE TITLE
Images of old posts should be archived to save space

### ISSUE THREAD

**Issue by tom-heidenreich** [LemmyNet/lemmy#4141]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

The pictrs folder can get pretty big and there is nothing you can do about it

### Describe the solution you'd like.

Many posts that are already older are only seen very rarely. You could archive them to save storage space. Then these posts would take longer to load, but since hardly anyone sees them anyway, it's not a problem.

### Describe alternatives you've considered.

You could also delete the old pictures, but then the corresponding posts are broken

**Comment by Nutomic** [comment]
Posts themselves take very little storage space, images and media have a far bigger impact. Besides where exactly do you propose to archive them?

**Comment by tom-heidenreich** [comment]
> Posts themselves take very little storage space, images and media have a far bigger impact. Besides where exactly do you propose to archive them?

Yes, I meant images (I updated the title).
And by archiving I mean compressing the images

**Comment by Nutomic** [comment]
Thats an issue for [pictrs](https://git.asonix.dog/asonix/pict-rs/). In fact 0.5 already adds similar functionality: https://github.com/LemmyNet/lemmy/issues/4053#issuecomment-1766732851
