### ISSUE TITLE
A new endpoint for local community stats (or counts?)

### ISSUE THREAD

**Issue by ismailkarsli** [LemmyNet/lemmy#4144]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

With 0.19 version, community stats/counts are federated too. I'm not sure how things changed behind the scenes but all the stats are the same across instances. Although this change makes sense, I was implementing a tool to boost local communities and I needed local subscriber count for that. Or maybe instances or clients need these values in the future. So can we have these values with API?

### Describe the solution you'd like.

- A new endpoint to fetch a communities local stats
- Adding local stats to CommunityView object

### Describe alternatives you've considered.

I tried almost every endpoint but I couldn't fetch this info.

**Comment by Nutomic** [comment]
The only thing that changes in 0.19 is that the follower count is federated from the instance where the community is hosted. Other stats are still calculated locally on each instance, just like before. So this issue is essentially about adding a field `CommunityAggregates.local_subscribers`.
