### ISSUE TITLE
Consistent tagnames

### ISSUE THREAD

**Issue by kroese** [LemmyNet/lemmy#4154]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

I publish automatic builds of Lemmy via Github Actions. Therefore I automaticly fetch the tagnames via the Github API, but this is very difficult for this project.

The reason for this it goes from "Beta" to "RC" to "Alpha" again? This is weird by itself, because normally Alpha releases come before the Beta ones.

But it also is problematic because the Github APIs sort the tagnames based on semver sorting, not by date, and the letter "A" is before "B" and "R". So when trying to fetch the latest tag, it lists RC4 as newer than Alpha4.

### Describe the solution you'd like.

It would be very nice to just keep a consistent format of the tagnames. Just call them all RC's or all Beta's, whatever is prefered, as long as they can be sorted by semver and alphabetic order without problems.

### Describe alternatives you've considered.

There is no alternative. The Github API does not allow sorting on the date of tags.

### Additional context

For an example, see: https://api.github.com/repos/lemmynet/lemmy/git/matching-refs/tags/0.1

That output lists "Alpha.4" somewhere in the middle, while "RC.4" is on the bottom. This makes it very hard to deduce that "Alpha.4" is the latest tag, it would be much easier if the bottom entry was always the latest.

**Comment by Nutomic** [comment]
cc @dessalines

**Comment by dessalines** [comment]
Is it possible for people to just not use tags that I'm using for development and bug fixing? I've repeatedly asked people not to use those tags.

Do not use anything other than the production / release tags. You should not definitely not be publishing tags we push, that can and will break instances. 

Use [this file](https://github.com/LemmyNet/lemmy-ansible/blob/main/VERSION) if you want the current version.
