### ISSUE TITLE
[Bug]: Can't subscribe to local communities (0.19.0-rc.4)

### ISSUE THREAD

**Issue by ismailkarsli** [LemmyNet/lemmy#4160]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Can't follow to local communities while remote ones working.

### Steps to Reproduce

1. Create account
2. Try to subscribe a local community

### Technical Details

There is no output in the logs.

### Version

0.19.0-rc.4

### Lemmy Instance URL

voyager.lemmy.ml (and lemy.lol)

**Comment by Die4Ever** [comment]
is this related to https://github.com/LemmyNet/lemmy-ui/issues/2215

**Comment by ismailkarsli** [comment]
> is this related to [LemmyNet/lemmy-ui#2215](https://github.com/LemmyNet/lemmy-ui/issues/2215)

Yep, its duplicate. Closing mine.
