### ISSUE TITLE
Provide username of mod that removed post/comment inside post/comment for mods/admins

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#4164]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

It can be helpful to coordinate within a mod team if a removed post/comment provided the mod that removed it.

Right now, client can only display that a post/comment has been removed, but not who removed it.

### Describe the solution you'd like.

Posts/comments has `removed_by?: Person` with mod account that last removed the post/comment.

### Describe alternatives you've considered.

There is no good solution. You could cross reference with the mod log but that's separate request(s).

**Comment by dessalines** [comment]
We only show the mod names in the mod log to other mods, and admins: https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/site/mod_log.rs#L52

This is to prevent harassment.

**Comment by aeharding** [comment]
@dessalines I actually intended for this enhancement to be mod/admins only, sorry!

I'm fine closing this for now. https://github.com/LemmyNet/lemmy/issues/4162 should cover this with an extra request.

**Comment by dessalines** [comment]
Gotcha, no probs. You and I are thinking of the same problems today lol.
