### ISSUE TITLE
[Bug]: Remove content option while banning is not working on 0.19.0-rc.4

### ISSUE THREAD

**Issue by ismailkarsli** [LemmyNet/lemmy#4169]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I can't try it on voyager.lemmy.ml but "Remove content" check is not working on RC version.

### Steps to Reproduce

1. Ban user (remove content checked, reason is filled, days is empty)

### Technical Details

I'm getting this response `{"error":"unknown","message":"Record not found"}` from /api/v3/user/ban endpoint. It doesn't remove content but ban is working.

### Version

0.19.0-rc.4

### Lemmy Instance URL

lemy.lol

**Comment by Nutomic** [comment]
I tried this just now and it worked fine on voyager. After banning a user, his post and community were both marked as deleted without problems.

**Comment by ismailkarsli** [comment]
> I tried this just now and it worked fine on voyager. After banning a local user, his post and community were both marked as deleted without problems.

I just tested it again. It works fine with the local user, but when I ban a external user from 0.18 on 0.19 instance, this error happens.

I am not sure if it happens between 0.19 and 0.19. Couldn't test it so you can close if you want.

**Comment by Nutomic** [comment]
Youre right its not working properly in case of remote user. Im investigating.
