### ISSUE TITLE
[Bug]: 0.19.0-rc.5 unable to subscribe to Kbin magazines

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy#4176]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

trying to subscribe to a kbin magazine gets stuck on pending

### Steps to Reproduce

1. go to https://voyager.lemmy.ml/c/RedditMigration@kbin.social
2. click Subscribe
3. notice it's stuck on Pending

### Technical Details

subscribing to this worked on programming.dev which is using 0.18.5

### Version

0.19.0-rc.5

### Lemmy Instance URL

https://voyager.lemmy.ml/c/RedditMigration@kbin.social

**Comment by Nutomic** [comment]
I tested this and the follow when through after a while. Seems like kbin is just a bit slow to send the accept (same with some bigger lemmy instances).

![Screenshot_20231120_144552](https://github.com/LemmyNet/lemmy/assets/1044450/2d810b39-6f9d-4a87-b672-b17b31e3c82f)

**Comment by Die4Ever** [comment]
seems like it took more than a day but yea it's working now
