### ISSUE TITLE
[Bug]: Unable to reset password as a registered user

### ISSUE THREAD

**Issue by JohnnyEn** [LemmyNet/lemmy#4177]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Unable to reset user password on 0.18.5 with pwd reset form.

### Steps to Reproduce

1. Go to page /login_reset
2. Paste user email for password reset
3. Submit form
4. Check log on lemmy docker container
5. Check DB table password_reset_request as a proof

### Technical Details

```LemmyError { message: None, inner: column "token_encrypted" of relation "password_reset_request" does not exist, context: SpanTrace [{ target: "lemmy_api::local_user::reset_password", name: "perform", file: "crates/api/src/local_user/reset_password.rs", line: 16 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=lemmy http.target=/api/v3/user/password_reset otel.kind=\"server\" request_id=7a16b135-0b81-4c9e-817a-735cd4ce0f5f", file: "src/root_span_builder.rs", line: 16 }] }
2023-11-19T20:04:31.403234Z  WARN lemmy_server::root_span_builder: column "token_encrypted" of relation "password_reset_request" does not exist
   0: lemmy_api::local_user::reset_password::perform
             at crates/api/src/local_user/reset_password.rs:16
   1: lemmy_server::root_span_builder::HTTP request
           with http.method=POST http.scheme="http" http.host=lemmy http.target=/api/v3/user/password_reset otel.kind="server" request_id=a9237c57-cbe8-426b-9c68-d88f4d9c0f61
             at src/root_span_builder.rs:16
LemmyError { message: None, inner: column "token_encrypted" of relation "password_reset_request" does not exist, context: SpanTrace [{ target: "lemmy_api::local_user::reset_password", name: "perform", file: "crates/api/src/local_user/reset_password.rs", line: 16 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"http\" http.host=lemmy http.target=/api/v3/user/password_reset otel.kind=\"server\" request_id=a9237c57-cbe8-426b-9c68-d88f4d9c0f61", file: "src/root_span_builder.rs", line: 16 }] }```

Browser errors: column "token_encrypted" of relation "password_reset_request" does not exist (400)

Self hosted lemmy instance on latest stable docker images

### Version

0.18.5

### Lemmy Instance URL

_No response_

**Comment by Nutomic** [comment]
That sounds like something wrong with your db schema. Are you having other errors about missing db columns or similar? Maybe you ran an 0.19 version in between which would have renamed that column. Easiest solution is to drop the db and recreate it, otherwise create the column manually.

**Comment by JohnnyEn** [comment]
@Nutomic I have fixed it with altering token with token_encrypted column and set it as nullable. Is there any safe option to rebuild database on next update without data loss?
