### ISSUE TITLE
[Bug]: local is not local

### ISSUE THREAD

**Issue by snan** [LemmyNet/lemmy#4180]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I went to https://lemmy.sdf.org/ and selected Posts and Local, I expected to see

• posts to communities on their instance from users of any random instance

but what I am seeing instead is:

• posts to all kinds of communities from users of any random instance

### Steps to Reproduce

1. Go to https://lemmy.sdf.org/
2. Select Posts
3. Select Local

### Technical Details

🤷🏻‍♀️

### Version

BE: 0.19.0-rc.5

### Lemmy Instance URL

https://lemmy.sdf.org/

**Comment by dullbananas** [comment]
my fault 😭

https://github.com/LemmyNet/lemmy/commit/5b5ac0f37d9d9d232032aee9e469ec79e099df1e#diff-2379d37fd6a1a90023506953ccdd3f4ccfd8c110f2e7ffdabd99569c235e6385R267
