### ISSUE TITLE
[Bug]: post title validation regular expression is incorrect

### ISSUE THREAD

**Issue by varshard** [LemmyNet/lemmy#4197]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/utils/validation.rs#L8

The regular expression for validating a post title is incorrect. It's `.*\S{3,200}.*`, which means it permit any post title with a 3-200 characters of non whitespace. However, the actual intend of the pattern is to prevent a post title that's shorter than 3 a or longer than 200 characters.

### Steps to Reproduce

1. Make a HTTP request to POST /post with name that's longer than 200 letters.
2. It an error with "invalid_post_title" instead of "couldnt_create_post".

### Technical Details

Post title validation shouldn't be `.*\S{3,200}.*`, but `\s*.{3,200}\s*` instead.

### Version

0.17.4

**Comment by dessalines** [comment]
@varshard In the future, put `Fixes #ISSUE_NUM` and it'll automatically close it.
