### ISSUE TITLE
[Bug]: Lemmy users matching the name of communities in the same instance, are not visible in mastodon

### ISSUE THREAD

**Issue by db0** [LemmyNet/lemmy#4201]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When an instance has a user and a community with the same name, mastodon is incapable of finding the user.

Example. I have https://lemmy.dbzer0.com/u/aihorde and https://lemmy.dbzer0.com/c/aihorde. When I search for the @aihorde@lemmy.dbzer0.com from a mastodon instance, only the group is found. If I search for a specific post ID from the `aihorde` user, it cannot be found. 

### Steps to Reproduce

1. Create a community
2. Create a user with the same name
3. Post as that user
4. Attempt to find that user in mastodon
5. Attempt to find that post in mastodon

### Technical Details

I don't think there's any technical details relevant here, but do let me know if you need anything specific

### Version

0.18.5

### Lemmy Instance URL

https://lemmy.dbzer0.com

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/issues/1922
