### ISSUE TITLE
Not sending password in plain text for login

### ISSUE THREAD

**Issue by uis246** [LemmyNet/lemmy#4209]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

After jabber.ru happened, I think sending password as plain text, even over TLS is not safe.

### Describe the solution you'd like.

Options I know:
1. Salted hash
- Password is stored on server
- Server sends salt
- Client replies with hash of salt+password
2. (Salted hash)^2
- Only salted hash is stored on server
- Server sends another salt to client
- Client replies with salted hash of salted hash of password
3. Public key authentication
- Either by singing or by decrypting
- Real world example: onelon.i2p(probably now closed)
- May involve no password
4. Some other cryptographic unicorn magic

### Describe alternatives you've considered.

Doing nothing and keeping sending password all the time?

### Additional context

Options 3 and 4 should allow bypassing state censorship by logging in on not-blocked-yet servers with same identity.

**Comment by dessalines** [comment]
TLS is end to end encrypted, and counts as (3). Its only unsafe if you're using a potential MITM like cloudflare.

**Comment by PoneyClairDeLune** [comment]
> TLS is end to end encrypted, and counts as (3). Its only unsafe if you're using a potential MITM like cloudflare.

So if the setup sits behind other TLS termination proxies, the password can be only left unsafe?

**Comment by uis246** [comment]
> TLS is end to end encrypted, and counts as (3).

No, and not by default unless you are using client certificates.

> Its only unsafe if you're using a potential MITM like cloudflare.

3-letter agencies are happy to do MITM instead of cloudflare. Example: jabber.ru. And that happened in EU of all places. Now imagine what will happen in Russia. US. China.

> If your TLS cert is compromised, then all data you send can be intercepted by that third party.

*private key. Or attacker can just get certificate.

When talking about state actors, TLS alone is not good enough. Leaving plain text password in RAM is bad. Even in CPU cache. Even in registers.

**Comment by Die4Ever** [comment]
But if they can do a MITM attack then they can just steal your cookie instead. Even with your approach, they could still modify your JavaScript to have it attach the plain text password into the payload.

**Comment by dessalines** [comment]
Closing this as it's not specific to lemmy, and from what I can tell, the jabber attack was because of a compromised TLS cert, which allowed the MITM. We're not going to use lemmy to reinvent logging in, so I suggest asking this on security forums.
