### ISSUE TITLE
[Bug]: AP flag activity with array as object is not working

### ISSUE THREAD

**Issue by BentiGorlich** [LemmyNet/lemmy#4217]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

There is a bug in the backend that expects the `object` property of an activity with the `flag` type to be of type `string`. An array should also be accepted.

This is maybe related to: #3862

### Steps to Reproduce

1. post a flag activity to the inbox like this:
```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams"
  ],
  "id": "https://mbin-test1/reports/45f8a01d-a73e-4575-bffa-c9f24c61f458",
  "type": "Flag",
  "actor": "https://mbin-test1/u/BentiGorlich",
  "object": [
    "https://lemmy-test/post/4",
    "https://lemmy-test/u/BentiGorlich"
  ],
  "audience": "https://lemmy-test/c/test_mag",
  "summary": "dikjhgasdpas dsaü",
  "content": "dikjhgasdpas dsaü",
  "to": [
    "https://lemmy-test/c/test_mag"
  ]
}
```
2. get this error: 
> data did not match any variant of untagged enum AnnouncableActivities

### Technical Details

> lemmy-proxy-1     | 192.168.178.144 - - [30/Nov/2023:22:34:18 +0000] "GET /post/4 HTTP/1.1" 200 615 "-" "MbinBot/0.1 (+~~~REDACTED~~~/bot)"
lemmy-lemmy-1     | 2023-11-30T22:34:35.506100Z  WARN lemmy_server::root_span_builder: data did not match any variant of untagged enum AnnouncableActivities
lemmy-lemmy-1     |    0: lemmy_apub::activities::community::announce::receive
lemmy-proxy-1     | 192.168.178.144 - - [30/Nov/2023:22:34:35 +0000] "POST /inbox HTTP/1.1" 400 86 "-" "MbinBot/0.1 (+~~~REDACTED~~~/bot)"
lemmy-lemmy-1     |              at crates/apub/src/activities/community/announce.rs:46
lemmy-lemmy-1     |    1: lemmy_server::root_span_builder::HTTP request
lemmy-lemmy-1     |            with http.method=POST http.scheme="https" http.host=~~~REDACTED~~~ http.target=/inbox otel.kind="server" request_id=2f0d40c8-303c-4040-b7ce-8082c322ce69
lemmy-lemmy-1     |              at src/root_span_builder.rs:16
lemmy-lemmy-1     | LemmyError { message: None, inner: data did not match any variant of untagged enum AnnouncableActivities, context: SpanTrace [{ target: "lemmy_apub::activities::community::announce", name: "receive", file: "crates/apub/src/activities/community/announce.rs", line: 46 }, { target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=POST http.scheme=\"https\" http.host=~~~REDACTED~~~ http.target=/inbox otel.kind=\"server\" request_id=2f0d40c8-303c-4040-b7ce-8082c322ce69", file: "src/root_span_builder.rs", line: 16 }] }

### Version

BE 0.18.5

### Lemmy Instance URL

I used a test instance

**Comment by Nutomic** [comment]
Even if arrays were supported, your example wouldnt work because Lemmy doesnt support flagging user accounts. So this seems invalid.

**Comment by BentiGorlich** [comment]
Could you not just ignore a user in an array? If you don't Mastodon and Lemmy are just incompatible with handling records, because mastodon requires you to include a user in the array. Hopefully they remove that requirement in the future, but afaik it is not yet on the roadmap...

**Comment by Nutomic** [comment]
Thats good to know, I had no idea Mastodon flags look like that. Will work on a  fix.
