### ISSUE TITLE
Profile Privacy Settings

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#4223]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Yes, the proposal is related to a problem concerning privacy and control over personal content on Lemmy. Currently, all user activity on Lemmy is publicly visible, which can be likened to sharing one's browser history with everyone. This lack of privacy settings forces users to either manually remove their content periodically or purge their account and create a new one, both of which are time-consuming tasks. Furthermore, the proposed solution of [ephemeral content](https://github.com/LemmyNet/lemmy/issues/3934) is automatic but prevents users from accessing their own past content. 

### Describe the solution you'd like.

The ideal solution would be the introduction of profile privacy settings that allow users to control who can view their feed. This could include options to make the feed public, visible only to friends or followers, or completely private. This would give users the flexibility to choose their level of privacy and control over their content, without having to resort to manual deletion or account purging. 

### Describe alternatives you've considered.

The alternatives currently available or proposed include manual deletion of content, account purging, and the implementation of ephemeral content. However, these solutions are either labor-intensive or result in the loss of access to past content.

### Additional context

Privacy is a significant concern for many social media users, and the lack of privacy settings on Lemmy could deter potential users from actively participating in the platform. Implementing profile privacy settings would not only enhance user experience but also potentially attract a wider user base who value control over their personal content.

**Comment by Nutomic** [comment]
This doesnt make sense because Lemmy is a public forum, and all content is by definition public. To keep certain posts private, the solution are private communities (https://github.com/LemmyNet/lemmy/issues/187).

**Comment by aardbol** [comment]
It actually makes total sense, because even if your individual posts are public, it doesn't have to mean your whole profile should allow anyone on the internet to stalk or profile you completely. You're also not taking into account that some of this info contains some very sensitive personal information, including your sexual orientation, religious choice, political views and more. By refusing to give users control over their profile privacy, this would make Lemmy by definition not comply with GDPR regulation. I hope you'll reconsider and reopen this issue

**Comment by dessalines** [comment]
> The ideal solution would be the introduction of profile privacy settings that allow users to control who can view their feed.

This would have to work in conjunction with the `private_instance` setting, because otherwise your posts are public. Then we'd need to add a way to manually allowlist specific users.

Feel free to open up a separate issue that works along those lines.
