### ISSUE TITLE
Post across multiple instances and combine comments across instances

### ISSUE THREAD

**Issue by postcardmaniait** [LemmyNet/lemmy#4225]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

It's frustrating seeing the same post multiple times in my feed because the author has posted it on several instances. I think it's fine if an author wants more exposure (so long as other users retain the ability to block all posts from another user), but seeing the post 5, 10 or 100 times in my feed is a overkill.

### Describe the solution you'd like.

There should be a way to list the instances you want the post to appear on, but only have it show once on any given user's feed. All comments from any instances the author selected will be visible in the post.

Perhaps the post will have a unique ID based on the user's lemmy name and home instance to help ensure the singular-ness of the post across all feeds.

### Describe alternatives you've considered.

Not sure about alternatives, but seeing multiple identical posts from different instances, all with different comments can be a bit annoying.

**Comment by MV-GH** [comment]
You mean across multiple communities? The idea of federation is that it will share your post across all federated instances and that you will be able to see all the comments from those instances under your post on your instance.

**Comment by aeharding** [comment]
> All comments from any instances the author selected will be visible in the post.

This would be a bad user experience for certain communities. Imagine the same news article is posted in /c/cars and /c/fuckcars. It is not desired nor expected to have all comments combined.

That being said, I think the problem your brought up is worth thinking further about.

However, I feel like this discussion is best suited for [an RFC](https://github.com/LemmyNet/rfcs).

**Comment by paulo-roger** [comment]
I was thinking about this kinda of feature yesterday! During a crosspost. This is what a **real** crosspost should be. Not just a copy/paste of the same post in another community.

**Comment by Die4Ever** [comment]
maybe this should be something related to whatever feature handles multi-communities/grouped communities, so they can all share the same comments for the same post

**Comment by dessalines** [comment]
Combining comments is out, because these are different posts that live on different communities, each with their own members and mod policies.

Lemmy-ui already has a "post-deduplicator" that simplifies viewing cross-posts on the same page, should probably be replicated in a lot of UIs. But that seems to me the best way to handle it.

**Comment by Oneechan69** [comment]
@dessalines Can u tell me about the deduplicator? If I make a post on different communities with the same title, will they all show up in those community feeds? (if the communities are federated)

**Comment by dessalines** [comment]
Yes, its best to just test this out to see how it works.

The de-duplicator is only for multi-community feeds, like your front page.
