### ISSUE TITLE
Comments of blocked users should be hidden from inbox

### ISSUE THREAD

**Issue by fer0n** [LemmyNet/lemmy#4227]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I’ve been getting some spam comments (with Images I’d rather not see) and even after blocking the people I still see them in my inbox. I’d rather not.

Apologies if this isn’t the most technical in-depth issue, if this isn’t the right place feel free to delete it.

### Steps to Reproduce

1. Write a post somewhere
2. Let someone comment on it 
3. Block the person commenting 
4. Comment (and images) still show up in the inbox 

### Technical Details

Don’t have access to that currently

### Version

0.19

### Lemmy Instance URL

Lemm.ee

**Comment by dessalines** [comment]
This shouldn't be too difficult to add. The comment_reply_view / mention_views just need to filter on creator_blocked.

**Comment by Officer-JimLahey** [comment]
Why has this been closed when it still happens? I have blocked people and I can still see their comments.

**Comment by Nothing4You** [comment]
This should be fixed since Lemmy 0.19.4.
Are you experiencing this on an instance running Lemmy 0.19.4 or newer?
