### ISSUE TITLE
[Bug]: 'This account is not in a ready state yet'

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/lemmy#4236]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I wish I could be more specific but ever since 0.19 my account can't interact at all, apparently it' 'being verified'. Very confused

### Steps to Reproduce

1. Go on app
2. Interact

### Technical Details

Android GrapheneOS

### Version

0.19

### Lemmy Instance URL

lemmy.ml

**Comment by RustoMCSpit** [comment]
Failed to verify JWT token

**Comment by MV-GH** [comment]
Your instance upgraded to 0.19 which revoked the JWTs and unlocked 2fa (due 2fa accidantal lockouts). As consequence jerboa correctlty indicates that it no longer has a valid JWT. And gives a option to login again. (To fetch a new JWT)

**Comment by RustoMCSpit** [comment]
> Your instance upgraded to 0.19 which revoked the JWTs and unlocked 2fa (due 2fa accidantal lockouts). As consequence jerboa correctlty indicates that it no longer has a valid JWT. And gives a option to login again. (To fetch a new JWT)

im confused, do i just out put and relogin?

**Comment by MV-GH** [comment]
Yes but it won't solve the problem as that version of Jerboa does not support yet 0.19

**Comment by RustoMCSpit** [comment]
> Yes but it won't solve the problem as that version of Jerboa does not support yet 0.19

oh so what do i just

**Comment by MV-GH** [comment]
Jerboa supports 0.19 now. You can close this
