### ISSUE TITLE
[Bug]: NSFW content is accessible without authentication via user comments

### ISSUE THREAD

**Issue by Popkornium18** [LemmyNet/lemmy#4237]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

On instances that federate with NFSW instances it is possible to access NSFW content without authentication. They can be viewed by clicking on comments in NSFW communities.

Since the comments often contain NSFW content themselves it would probably best to filter out comments on NFSW communities when viewing users.

### Steps to Reproduce

1. Go to an Instance that federates with NSFW instances, like lemmy.world
2. NSFW Content is not accessible directly. If you try to view NSFW communities, they are blocked, as they should be
3. Find a user that comments on such communities. E.g. search for users with "NSFW" in their name
4. Click on a comment in a NSFW community.
5. You can view the post like any other post, but you wouldn't be able to find it otherwise (by searching for communities or posts directly)

### Technical Details

.

### Version

0.18.5

### Lemmy Instance URL

lemmy.world

**Comment by dessalines** [comment]
I don't know if I'd consider this is a bug. NSFW posts are still publicly-accessible by url (and I suppose by going into user profiles), but they aren't displayed from post listings like home or community.

**Comment by Popkornium18** [comment]
Yes, URLs are accessible, but guessing them is basically impossible. User comments (and users themselves) are easily browsable.

**Comment by dessalines** [comment]
We don't mark users or comments as nsfw, so I don't know how we'd be able to filter for something like this.
