### ISSUE TITLE
Current implementation of post view cursor pagination probably prevents some posts from appearing

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#4239]
The comparison filters for pagination don't seem to be combined correctly.

Currently, posts are sorted by these post_aggregates fields, with the next one being used if the previously sorted field has equal values:
1. featured_local or featured_community (true before false)
2. the field determined by SortType
3. published (unless previous field is also timestamp)

On a page of posts, all posts with a sorted field's value being greater or less than the value for the last post on the previous page are hidden. The correct behavior would be to only filter a sorted field for posts that have the previously sorted field's value equal to the value for the last post on the previous page.

For example, here's page 1 of posts with SortType::Top, with (featured_local, score) shown for each post:

* (true, 10)

* (true, 9)

Page 2 should be:

* (true, 8)

* (false, 100)

But the current implementation would only show posts with `score < 9` on page 2, so the post with (false, 100) would be hidden.

This could be fixed by using filters like `post_aggregates::score.le(9).or(post_aggregates::featured_local.ne(page_after.0.featured_local))`. For the 3rd sorted field, the equality of both 1st and 2nd would be checked. I don't know if that would affect the indexes used in the query plan.

I might fix this in #4042.

**Comment by phiresky** [comment]
Good catch! 

Originally I wanted to use tuple comparisons, such as 

(featured_local, score) <= (true, 100) which would not have this problem. But I had some issue getting diesel to like that tuple comparison so I compared them individually without considering that that's logically different :(

**Comment by phiresky** [comment]
Disregard my above comment about the impact being small, I didn't consider the third column we filter by always (recency)
