### ISSUE TITLE
[Bug]: Block Instance allows you to block your own instance

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#4241]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Block Instance allows you to block your own instance

![image](https://github.com/LemmyNet/lemmy/assets/67873169/7eed1d34-7e62-4bab-9a95-2f00e783a269)

![image](https://github.com/LemmyNet/lemmy/assets/67873169/ec025b8a-bafb-42fd-8ea4-9b87a92707e1)

### Steps to Reproduce

1. call blockInstance with own instance id

### Technical Details

n/a

### Version

0.19.0-rc13

### Lemmy Instance URL

voyager.lemmy.ml

**Comment by dullbananas** [comment]
this is fine
