### ISSUE TITLE
bug: Performance regression on `getSite`

### ISSUE THREAD

**Issue by kroese** [LemmyNet/lemmy#4244]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I monitor my Lemmy instance via different tools, and I noticed that since very recently the response times for the frontpage tripled.

They were always around 100 ms (which is already a bit slow) but since November 22 they tripled to above 300 ms.

This must be caused by RC5 or RC6 of Lemmy, as they were released around that date and I always immediately switch to the latest RC.

Is there anyone else who monitors their instance response times and can confirm they became worse after installing the latest RC?

EDIT: I measured https://voyager.lemmy.ml for a while, since that instance also runs RC7, and it has the same 300+ ms response times. So it does not seem isolated to my instance.

EDIT2: As a test I measured the response times to ```/robots.txt``` and they are only about 50 ms. So this rules out a lot of possible causes, and confirms that this latency is certainly introduced by ```lemmy-ui``` handling the request for the frontpage, and not some other network problem along the way.

My best guess is that there are some queries executed for the frontpage that have become much more inefficient in one of the latest release candidates. Maybe @dullbananas can say something about that?

### Steps to Reproduce

1. Measure time till first byte (TTFB)
2. Notice a big increase
3.
4.

### Lemmy Instance Version

0.19.0 RC7

**Comment by dessalines** [comment]
Thx, yeah there's probably a missing index causing that to be slow.

**Comment by SleeplessOne1917** [comment]
`PersonView::admins` runs [this code](https://github.com/LemmyNet/lemmy/blob/f76499674578ba49e2f07e9e9b0cc4488627f12a/crates/db_views_actor/src/person_view.rs#L75-L83). Nothing here stands out to me as something that would go slow, although more eyes on it would be ideal. [Maybe the implementation of `all_joins` has something to do with this?](https://github.com/LemmyNet/lemmy/blob/f76499674578ba49e2f07e9e9b0cc4488627f12a/crates/db_views_actor/src/person_view.rs#L58-L67)

Alternatively, it could be the index hypothesis.

**Comment by dullbananas** [comment]
Maybe using left join again will fix it

https://github.com/LemmyNet/lemmy/commit/3e1f7f2efa77a518d4fe5e0159eeea9defa215b2#diff-0818f26776eea7641cd240bccb350402b82613ea550453cc1549f109066d336aL54

**Comment by SleeplessOne1917** [comment]
@kroese working on a PR now.

**Comment by SleeplessOne1917** [comment]
@dullbananas @kroese the PR is up if you'd like to test the changes.

**Comment by Nutomic** [comment]
@phiresky Good point. [Here is a gist with slowest queries](https://gist.github.com/Nutomic/64e92cf1b0e81b30c3e6564b414bc8ed) (using `select * from pg_stat_statements where calls > 100 order by mean_exec_time desc limit 10;`). Indeed it shows two sequential scans on local_user table.

**Comment by Nutomic** [comment]
@kroese Thanks for your profiling, it was extremely helpful knowing where exactly the slowdown came from.

**Comment by phiresky** [comment]
@kroese do you have a select * from pg_stat_statements order by total_exec_time desc limit 10 maybe? maybe there's another slow query that's just less common

**Comment by dullbananas** [comment]
The slowdown from RC13 must be either actix_web_prom or something in lemmy-ui. No queries were changed.

https://github.com/LemmyNet/lemmy/compare/0.19.0-rc.12...0.19.0-rc.13

**Comment by SleeplessOne1917** [comment]
> The slowdown from RC13 must be either actix_web_prom or something in lemmy-ui. No queries were changed.

I don't think it's the UI, since the only fix that seemed to work was changing the SQL query to use left join instead of a subquery.
