### ISSUE TITLE
[Bug]: Inconsistent couldnt_get_posts Error on retrieving posts

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#4277]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

In Jerboa we are receiving reports from users unable to retrieve the next pages. 

The request fails with `couldnt_get_posts`

The api call is `https://lemmy.one/api/v3/post/list?type_=All&sort=Hot&page=4&page_cursor=P7b3e3e` 
From testing it seems to only happen when the call is authenicated (passed a bearer token)
But it is not consistent sometimes it does work

### Steps to Reproduce

1. Spam this api call `https://lemmy.one/api/v3/post/list?type_=All&sort=Hot&page=4&page_cursor=P7b3e3e`
2. Pass bearer token
3. until 400

### Technical Details

https://github.com/LemmyNet/lemmy/assets/67873169/7309c44c-ebfb-43c0-bcc3-e97bbf730d7e

### Version

0.19.0

### Lemmy Instance URL

lemmy.one, lemmy.ml

**Comment by Demigodrick** [comment]
I had this issue too, the DB files were being spammed with 

`ERROR:  could not resize shared memory segment "/PostgreSQL.444485008" to 249440 bytes: No space left on device`

My db is in docker, i *think* I've fixed this (so far its been an hour without this message) by increasing the shared memory size of the container to a gig (/dev/shm)

**Comment by MV-GH** [comment]
I made a separate issue for that one #4284

**Comment by citking** [comment]
Had this same issue, was in fact the PgSQL DB needing tuning - after that the issue went away. Check the linked tuning docs in https://github.com/LemmyNet/lemmy/issues/4284
