### ISSUE TITLE
Upgrade to woodpecker v2

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4278]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

A holder issue to remind me to upgrade woodpecker.

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

**Comment by Nutomic** [comment]
Completed.
