### ISSUE TITLE
Increasing and high Server Load Avearge

### ISSUE THREAD

**Issue by nicfab** [LemmyNet/lemmy#4282]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

After upgrading my Lemmy instance to version 0.19.0 I noted a fast increase in load average on the server that remains high (1.30).

### Steps to Reproduce

1. Run `docker compose down`
2. Upgrading to new version 0.19.0 by modifying the `docker-compose.yml` file
3. Run `docker compose up -d`

### Technical Details

The server OS is Ubuntu 22.04.3 LTS.
Some files:
1. Logs - [lemmy_log.txt](https://github.com/LemmyNet/lemmy/files/13692931/lemmy_log.txt)
2. lemmy.hjson (in txt format)- [lemmy.hjson.txt](https://github.com/LemmyNet/lemmy/files/13692945/lemmy.hjson.txt)
3. docker-compose.yml (in txt format) - [docker-compose.yml.txt](https://github.com/LemmyNet/lemmy/files/13692946/docker-compose.yml.txt)

### Version

0.19.0

### Lemmy Instance URL

https://community.nicfab.it

**Comment by arifwn** [comment]
I also noticed increased database load after the upgrade. Is this related to the new persistent federation queue?

**Comment by Demigodrick** [comment]
Just want to +1 this - I've seen on average a doubling of the server load metric since the update was applied.

**Comment by axeleroy** [comment]
I have been able to reduce the database load by setting `database.pool_size` in `lemmy.hjson`. I still have to tweak its value to get a good balance between Lemmy performance and relatively low database load.

**Comment by Nutomic** [comment]
Yes this is most likely because of the new federation queue. Previously, outgoing activities would be handled entirely in memory in the Lemmy process, but now they get written to the db and then read again. #4285 should help by batching these db queries.

**Comment by arifwn** [comment]
Thanks! Adding  `database.pool_size` in `lemmy.hjson` works better than limiting the max connections on postgres.

**Comment by phiresky** [comment]
Please follow these steps to get info about database performance:

1. enable pg_stat_statements and auto_explain by making sure these lines exists in the postgresql config (`customPostgresql.conf`):
    ```
    shared_preload_libraries=pg_stat_statements,auto_explain
    pg_stat_statements.track = all
    auto_explain.log_min_duration=5000ms
    ```
3. open a `psql` repl by running `docker compose exec -it db -u postgres psql -d lemmy` and  reset the stats by calling `create extension pg_stat_statements; select pg_stat_statements_reset()`
4. wait an hour
5. post the outputs of
   `docker compose exec -it db -u postgres -qtAX -d lemmy -c 'select json_agg(a) from (select * from pg_stat_statements order by total_exec_time desc limit 10) a;' > total_exec_time.json`

    and

    `docker compose exec -it db -u postgres -qtAX -d lemmy -c 'select json_agg(a) from (select * from pg_stat_statements order by mean_exec_time desc limit 10) a;' > mean_exec_time.json`

**Comment by phiresky** [comment]
Also, in general a higher server load floor on 0.19 is expected and not really an issue. The floor of server use is higher (esp. for small instances) but it scales better to higher federation loads.

**Comment by axeleroy** [comment]
My issue isn't particularly the increased CPU load but rather the increased IO load which is tanking performance on other services I host, as well as the increased memory usage due to increased PostgreSQL activity (which filled my host's swap until I set a limit to the connection pool size)

**Comment by phiresky** [comment]
It won't.. Do you have synchronous_commit=off set?

**Comment by axeleroy** [comment]
I don't think so, my postgres command is
```
[
  "postgres",
  "-c",
  "session_preload_libraries=auto_explain",
  "-c",
  "auto_explain.log_min_duration=5ms",
  "-c",
  "auto_explain.log_analyze=true",
  "-c",
  "track_activity_query_size=1048576",
]

I'll try that though
```

**Comment by arifwn** [comment]
Postgres memory usage is down again after setting `database.pool_size` to 30 in `lemmy.hjson`. The default value (95?) seems to be too high for my small VPS with 4.5GB RAM.

**Comment by nicfab** [comment]
I am following your comments, and I'll be sure to wait for a solution.
In the meantime, I had to stop my Lemmy docker and put offline my instance.

**Comment by linux-cultist** [comment]
> Postgres memory usage is down again after setting `database.pool_size` to 30 in `lemmy.hjson`. The default value (95?) seems to be too high for my small VPS with 4.5GB RAM.

You can control postgres with the `customPostgresql.conf` file and put settings into it tuned by your hardware:

[pgtune.leopard.in.ua](https://pgtune.leopard.in.ua/)

If you tell postgres to use 3 GB and 1 cpu (for example), it wont use all your resources. It may use memory if its not used by something else, and then release it the second something else needs it. Thats normal.

**Comment by phiresky** [comment]
I'll close this since it seems like the same thing as #4334 and that one has more detail (I don't see any info here that's not present there)
