### ISSUE TITLE
[Bug]: Many API calls return `could not resize shared memory segment` errors

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#4284]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

In Jerboa many random API calls keep failing with this problem `could not resize shared memory segment`

This also happens without being authenticated

### Steps to Reproduce

1. SPAM this call https://lemmy.one/api/v3/user?person_id=21674
2. about 50 % fails with that error

### Technical Details

n/a

https://github.com/LemmyNet/lemmy/assets/67873169/48e14ee4-371c-45db-b5fc-cf3e40ae2638

### Version

0.19.0

### Lemmy Instance URL

lemmy.one

**Comment by Nutomic** [comment]
This seems to be a problem with the database, you can send [this link](https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device) to the instance admin.

Its also a good idea to [tune the postgres config](https://pgtune.leopard.in.ua/).
