### ISSUE TITLE
Question: Rust Crates out of Date, not yet updated or was support dropped?

### ISSUE THREAD

**Issue by Neshura87** [LemmyNet/lemmy#4291]
The Rust Crates containing the API Structs are incompatible with 0.19. Will they be updated eventually or was support for them dropped given they were last updated for the 0.18.2 release?

**Comment by Nutomic** [comment]
I disabled it because we stopped using crates.io for dockerless Lemmy installation. But its true that its also necessary for Rust projects which depend on the Lemmy API, so Im enabling it again in https://github.com/LemmyNet/lemmy/pull/4294

**Comment by CMahaff** [comment]
Another work-around is that you can directly reference a git repo in your Cargo.toml.

For example, something like this:
`lemmy_api_common` = { git = "https://github.com/LemmyNet/lemmy.git", tag = "0.18.3" }`

I haven't tried it with 0.19, but that used to work.
