### ISSUE TITLE
Question: Should lemmy's crates be published to Crates.io? If not, should already published crates be yanked?

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#4308]
### Question

[A search on crates.io shows several crates from this repo](https://crates.io/search?q=lemmy&sort=relevance) (with all of them being out of date). Is there any point to publishing any of these crates other than lemmy_api_common, which could be used for making a lemmy client in rust?

**Comment by Nutomic** [comment]
Yes that would make sense, but the [cargo-workspaces tool](https://github.com/pksunkara/cargo-workspaces#publish) used to publish them doesnt have any options to include or exclude specific crates. Either publish everything together, or do it all manually.

Also see https://github.com/LemmyNet/lemmy/issues/4291
