### ISSUE TITLE
Mastdon homeserver redirect support

### ISSUE THREAD

**Issue by FruityWelsh** [LemmyNet/lemmy#4310]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

This feature of mastadon of taking you to your homeserver to follow someone fails on lemmy instances:
![image](https://github.com/LemmyNet/lemmy/assets/24510330/bd7e7fe6-5b51-4664-bc0a-814023e307dd)

Lemmy page result:
![image](https://github.com/LemmyNet/lemmy/assets/24510330/29a3ecb4-4c16-484d-ae9c-f6a23c1a8d9f)

Nothing different in my console logs when I do it either vs standard lemmy.ml page load.

### Describe the solution you'd like.

Supporting this feature would be great.

### Describe alternatives you've considered.

I'm not sure.

**Comment by Nutomic** [comment]
Its not going to work this way because you cant follow users from Lemmy. Try the other way, follow a Lemmy community without login and get redirected to Mastodon.
