### ISSUE TITLE
Adding custom buttons to the navbar

### ISSUE THREAD

**Issue by Ategon** [LemmyNet/lemmy#4315]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There are certain things that I want prominently shown in the site. For example events such as lemmy canvas, our community request zone since we do a separate system from letting people create communities freely, and things like a status page, stats page, legal page, support page, etc.

### Describe the solution you'd like.

Allow admins to add new buttons to the navbar with whatever links they want

Ideally should
- Support using things like svgs for the button title similar to the current navbar heart
- Support making a button instead a category that when clicked shows many different other buttons in a dropdown (for example if people want to have a button titled Alternate Frontends that when clicked shows all of the frontends they host). The actual dropdown would be something for the frontend but categories can be done here

This is something im requesting in the backend so it can be shared between all frontend and all frontends can choose how they want to display these additional links that makes sense in the context of the frontend

### Describe alternatives you've considered.

Keep current system. People have sort of gone around it currently by having links in their instance description. The issue with this is its very out of the way and people dont look at it so miss essential things

### Additional context

Should basically only require one table in the database to store the titles, links, category, and whether its a category and will not touch federation at all since its all local to the instance (whether its a category could also be implicit by link being blank)

On the API side it can be added into editsite for creation and getsiteresponse for getting them

**Comment by Nutomic** [comment]
The Lemmy backend doesnt have a navbar, and I dont think it makes much sense to store such things in the database. Its much easier to have a config option or some sort of template file in lemmy-ui.

**Comment by Ategon** [comment]
The issue with making it a part of lemmy-ui is changes arent reflected in alternate frontends without configuring it for each individual alternate frontend (and some frontends like the apps that cant be done in since the sites dont host them)

**Comment by Nutomic** [comment]
Having it in Lemmy also doesnt mean that other frontends will automatically implement this. Anyway there is already a lot of code, I dont want to bloat it for such a minor thing which can also be done in other ways (directly in frontends or putting it in the sidebar).
