### ISSUE TITLE
Allow site announcements

### ISSUE THREAD

**Issue by Ategon** [LemmyNet/lemmy#4316]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Currently its difficult to get announcements out to your entire site in a way that doesnt affect the functioning of the site very much

### Describe the solution you'd like.

Allow admins to create announcements for the site that show up near the taglines. After people have seen the announcement that announcement no longer shows up for them to prevent it lingering on their feed forever

### Describe alternatives you've considered.

This can be done in many other ways currently but they all have downsides and have worse UI to support it being an announcement

Stickied post - lingers on peoples feeds until its unstickied
Taglines - some instances use taglines for actual taglines so cant share that with announcements

With both of those as well if you unsticky it or remove it as a tagline people who didnt see it can now never see it there even if its relevant for them

### Additional context

This implementation would have two tables, one for the list of announcements and one for keeping track of the announcements people have read (could also do the other way around and keeping track of unread but figure this future proofs it for there being many dead accounts)

Frontends could do a system with buttons to show previous or next announcements if theres multiple. Could also possibly have a button to show past announcements

**Comment by dullbananas** [comment]
> Stickied post - lingers on peoples feeds until its unstickied

Maybe this should be fixed for sticky posts, not just announcements

**Comment by dessalines** [comment]
The local stickied posts **are** your site announcements, but I agree that it'd be useful to hide them if you really don't want to see them anymore. 

That one is here: #1403
