### ISSUE TITLE
Question: Why does the `0.19.1` tag/commit appear to not belong to any branch of this repository?

### ISSUE THREAD

**Issue by necropola** [LemmyNet/lemmy#4317]
### Question

![image](https://github.com/LemmyNet/lemmy/assets/7461137/1400cad9-fc93-4128-9c0d-8ad89b5934ea)

https://github.com/LemmyNet/lemmy/tree/0.19.1

**Comment by Nutomic** [comment]
Looks like it didnt get pushed to the main branch. @dessalines maybe you can still fix it as there is only one new commit.

**Comment by dessalines** [comment]
Hrm... I tried cherry-picking it, but it didn't seem to fix the issue. This will be resolved when we do the next patch release... my bad.
