### ISSUE TITLE
[Bug]: /api/v3/user/unread_count sometimes returns incorrect_login, despite token still being valid

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#4319]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Lemmy will sometimes return `incorrect_login`, specifically tested on the `/api/v3/user/unread_count` endpoint (but may affect other endpoints) despite the token still being valid.

I've encountered this issue on lemmy v0.19 servers that are experiencing performance issues, recently feddit.de, which leads me to believe that there is an internal application error occurring that's erroring with `incorrect_login`

### Steps to Reproduce

1. On a lemmy server with performance problems, repeatedly make a valid call to `/api/v3/user/unread_count` with token. Observe it usually works, but sometimes errors with `incorrect_login` response.

### Expected Result

Lemmy should never return `incorrect_login` unless the JWT has been revoked, or is otherwise invalid.

When Voyager encounters this error code, it assumes that the JWT is invalid and logs the user out. This is causing issues such as https://github.com/aeharding/voyager/issues/1113.

### Technical Details

I am not the server admin of feddit.de unfortunately, but users report this issue is affecting other v0.19 servers with performance issues as well (see https://github.com/aeharding/voyager/issues/1113)

### Version

0.19.1

### Lemmy Instance URL

feddit.de

**Comment by aeharding** [comment]
I was able to replicate this in a shell script. It took 15 minutes to find errors. I am testing against feddit.de:

My script:

```sh
while true; do sleep 1; curl -H "Authorization: Bearer REDACTED" "https://feddit.de/api/v3/user/unread_count"; echo -e '\n\n\n\n'$(date);done
```

Trimmed beginning/end:
```
Thu Dec 21 15:43:28 PST 2023
{"replies":0,"mentions":0,"private_messages":0}-e



Thu Dec 21 15:43:29 PST 2023
{"replies":0,"mentions":0,"private_messages":0}-e



Thu Dec 21 15:43:31 PST 2023
{"replies":0,"mentions":0,"private_messages":0}-e



Thu Dec 21 15:43:34 PST 2023
{"error":"incorrect_login"}-e



Thu Dec 21 15:43:37 PST 2023
{"error":"incorrect_login"}-e



Thu Dec 21 15:43:39 PST 2023
{"error":"incorrect_login"}-e



Thu Dec 21 15:43:40 PST 2023
{"error":"incorrect_login"}-e



Thu Dec 21 15:43:42 PST 2023
{"error":"incorrect_login"}-e



Thu Dec 21 15:43:43 PST 2023
{"error":"incorrect_login"}-e



Thu Dec 21 15:43:45 PST 2023
{"replies":0,"mentions":0,"private_messages":0}-e



Thu Dec 21 15:43:46 PST 2023
{"replies":0,"mentions":0,"private_messages":0}-e



Thu Dec 21 15:43:48 PST 2023
{"replies":0,"mentions":0,"private_messages":0}-e



Thu Dec 21 15:43:49 PST 2023
{"replies":0,"mentions":0,"private_messages":0}-e
```

**Comment by phiresky** [comment]
Can you say what the server response time is for those? If it's the pool timeout thing then it should be a pretty predictable round number of seconds (don't remember what exactly). If it responds quickly then idk what it could be (rate limit maybe?)

**Comment by aeharding** [comment]
> Can you say what the server response time is for those?

I don't think it's anything above average looking at my logs (snippet above). Seems to be taking 1-2 seconds.

What is interesting is that 6 requests failed in a cluster (see above log). This is following hundreds of successful requests. Does this maybe help narrow it down at all? Perhaps there's an internal service that's restarting or something? (I could try to track down the feddit.de admin, too.)

**Comment by phiresky** [comment]
> 6 requests failed in a cluster 

If the delay was also correlated to the response content then I'd say it's related to the pool allocation. If not then idk.

> Perhaps there's an internal service that's restarting
 
Unlikely. If you get that error then I think it must be coming directly from rust and created within rust. There's only like 3 places that generate that error so it shouldn't be hard to track down, except from a quick glance I didn't see any other obvious failure cases that could lead to it. But they are converted to that error in a way where any other DB failure will be converted to the same error, not just a "token not found" error.

**Comment by johnyb0y** [comment]
I recently noticed revoked logins within just a few minutes with different Lemmy Apps on iOS like for example Voyager or Memmy. 
Coincidentally the Lemmy server is also feddit.de (only server I use). Feddit.de is currently on 0.19.1. 

This might have something to do with this since apps might take this response as "your login is not valid anymore, please login again."

**Comment by dessalines** [comment]
As a side point, I'd recommend using the new validate_auth endpoint on the app startup, rather than periodic calls to check valid auth.

Also this one could be related, as I also ran into some issues with postges shared memory space: https://github.com/LemmyNet/lemmy-ansible/commit/6ecaeaa36b385267151be4f8e1760018a19dc135

**Comment by aeharding** [comment]
> As a side point, I'd recommend using the new validate_auth endpoint on the app startup, rather than periodic calls to check valid auth.

@dessalines Voyager already periodically fetches notification counts anyways, so checking the error code of that request for invalid auth is just a nice side effect.

**Comment by KAMiKAZOW** [comment]
Is this supposed to be fixed in 0.19.2 or is "Error: unknown" a different bug?

![image](https://github.com/LemmyNet/lemmy/assets/3259076/731770f4-4978-415c-b92c-1393e38b72cd)

**Comment by Nutomic** [comment]
@KAMiKAZOW Check the browser console and browser networking tab for more info.

**Comment by Nutomic** [comment]
The fix for this caused more problems than it solved, as many users have invalid cookies for some reason, and they are unable to access Lemmy at all due to the error message. Its reverted in https://github.com/LemmyNet/lemmy/pull/4380, have to test more carefully when attempting to fix this.

**Comment by dessalines** [comment]
The clearing out of the JWT token should work now with `0.19.3`

**Comment by dessalines** [comment]
We reworked how a lot of errors are handled in the upcoming release, can you test this on https://voyager.lemmy.ml ?

**Comment by aeharding** [comment]
Thanks for the reply! I'll check, but so far I've only noticed the problem on certain instances (probably resource constrained).

Worse case, I'll provide an update after release if it seems fixed (or not)
