### ISSUE TITLE
Is 2FA more broken on 0.19.0 than it was on previous versions?

### ISSUE THREAD

**Issue by kirk781** [LemmyNet/lemmy#4326]
### Question

When the server[Discus.tchncs.de] upgraded to 0.19.0 and everyone’s 2FA was reset, I again setup my 2FA. It accepted my code and 2FA was enabled. I tried to login again but it said multiple times that the code generated by the app was invalid. I try to disable this multi factor authentication but even that won’t work since it asks for the TOTP code which it marks as invalid. How is a TOTP code generated by Lemmy’s link and accepted by it’s servers to validate 2FA in the first place be invalid?

To double check, I contacted the mod there and had my 2FA reset. When I again went to re setup 2FA just now, same issue pops up. To make things more complicated, the QR code isn't scannable by any conventional app like _Microsoft Authenticator_ or _Authy_ . I had to rely on a browser extension both on 0.18.x series and on 0.19.0 version.Also, Lemmy uses the SHA 256 version of the hash, right [ not as it should matter to an end user because if the server is accepting a six digit code as valid in the first place means the setup was done right and it should work normally from then ].

**Comment by Tipoff4317** [comment]
2 of the servers I used just upgraded to 0.19.1.  I had to re-setup the 2FA again on both, using 2FAS app.  Both accounts are working.

Learning from the bitter experience with setting up 2FA on Lemmy when it first came out, nowadays when I setup 2FA on any account, I usually login from 2 consoles.  If the 2FA setup fails, I have the other console to remove the 2FA.  This doesn't always work obviously, for the services that logout all consoles, and for the services that don't allow removing 2FAs.

**Comment by Tipoff4317** [comment]
OK.  I just tried it on a UI: 0.19.0, BE: 0.19.1-rc.1 (https://lemm.ee/) and I got the same behavior as @kirk781, i.e.

Step to reproduce:
1) Enable 2FA, finishing by providing the generated code.
2) Logout
3) When supplying the generated TOTP code after hitting enter, got recycled back to the login page, while expecting to have been logged in.

Had to disable the 2FA for that account.

**Comment by Nutomic** [comment]
Maybe this is because previous Lemmy versions used SHA256, but now its SHA1 (which should be the default in most applications).

**Comment by ceandreasen** [comment]
I am also having this issue. Using Yubico Authenticator, which displays clearly that it is using SHA-1 when you add the account, my code is accepted to enable or disable 2fa but not to log in with. Any troubleshooting steps I can take?

**Comment by Tipoff4317** [comment]
@ceandreasen 

It seems this works on the version 0.19.1, but probably not before that.  Maybe if your instance just runs a straight 0.19.1 (not the mixes that lemm.ee run).

**Comment by Nutomic** [comment]
@ceandreasen It uses the same code for both of them. What error message are you getting on the client or in server logs?

**Comment by dessalines** [comment]
We need exact steps to reproduce, including the authenticator app.

**Comment by ceandreasen** [comment]
Sorry, I tested it again on a different instance and got it to work there (it did not the first try), so I think it is just mine. Running some frontend modifications that must be causing it for me, as the backend seems to think it is returning a 200, but my browser aborts the request before it can finish. If I find an upstream issue though I will report it back here. 

Other users might have more details about the issue on their instances though

**Comment by Tipoff4317** [comment]
>     3. When supplying the generated TOTP code after hitting enter, got recycled back to the login page, while expecting to have been logged in.

For me, the keyword is **I hit enter**.  I think how it's supposed to work is, you enter the code and the script takes it automatically to the next page.  If the script is slow (which often was for me), I think maybe I should hit enter (probably activating the cancel button), it takes me back to the email/password page.

So, to help a user like me, maybe putting a message saying "do not hit enter" in would suffice.

**Comment by Tipoff4317** [comment]
@Nutomic Suppose it is; will file accordingly.

**Comment by kirk781** [comment]
> Maybe this is because previous Lemmy versions used SHA256, but now its SHA1 (which should be the default in most applications).

So any new 2FA codes on Lemmy, I should choose _SHA1_ from now on? Because Lemmy is the only pain point; for most forums/sites; one scans a code and just gets done away with. On Lemmy, I am now just waiting for Lemmy.world instance to migrate to 0.19 where I had an older account with some subscribed stuff but lost account access due to 2FA dilemna originally.

**Comment by Tipoff4317** [comment]
@kirk781 

Yeah, SHA1, and also, the URL link to add the entry won't specify the algorithm (previously SHA256) automatically making the entry a SHA1 TOTP.  

My servers that upgraded to 0.19 all dropped existing 2FAs, with the users having to reenable the 2FA with SHA1 this time.
