### ISSUE TITLE
[Bug]: Server being upgraded to 0.19.1 removed the 2FA

### ISSUE THREAD

**Issue by Tipoff4317** [LemmyNet/lemmy#4327]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Servers being upgraded to 0.19.1 remove the existing TOTP 2FA credentials.  I had the same thing happened on 2 servers.

### Steps to Reproduce

1. Go to the server that has been upgraded to 0.19.1 (presumably had less than 0.19.0 before?)
2. Login
3. TOTP 2FA that was there before is no longer required.

I am a user, not an admin.  Presumably, this is not a UI error.

### Technical Details

N/A

### Version

0.19.1

### Lemmy Instance URL

https://lemmy.bleh.au

**Comment by usr3** [comment]
@Tipoff4317 This was done on purpose in #3959 so that users will existing 2FA don't get locked out after server is upgraded to v0.19+

**Comment by Tipoff4317** [comment]
@usr3 Thanks for pointing that out.
