### ISSUE TITLE
cache_external_link_previews cache grows indefinitely

### ISSUE THREAD

**Issue by FireMasterK** [LemmyNet/lemmy#4328]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When `pictrs.cache_external_link_previews` is enabled, external link preview thumbnail images are cached indefinitely.

### Describe the solution you'd like.

Ideally, I think either pictrs could support some kind of lru based algorithm to evict old previews, or the same could be done in Lemmy's database by purging old pictrs images. We could have an asynchronous evictor task. Ideally we should be able to limit the cache by number of images, or total file size.

### Describe alternatives you've considered.

Disabling the caching feature altogether.

### Additional context

Relevant code:
https://github.com/LemmyNet/lemmy/blob/f223eb94d5de292e016175e774e4150bf2e148fa/crates/api_common/src/request.rs#L249

Related: https://github.com/LemmyNet/lemmy/issues/2947#issuecomment-1580263972

**Comment by dessalines** [comment]
I think this is intentional, and we should maybe change the term cache -> save. @Nutomic thoughts?

Some of those other things would have to be built into pictrs itself, not lemmy.

**Comment by dessalines** [comment]
This is addressed by #4035
