### ISSUE TITLE
Make it clearer to external AP apps that communities are communities, not accounts

### ISSUE THREAD

**Issue by Atemu** [LemmyNet/lemmy#4339]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

When searching for a popular thing (i.e. Firefox) on Mastoton, the first results are often Lemmy communities. These usually have a plain name and logo that look official and have lots of "followers". Likely unintentionally so, this creates an air of legitimacy which makes the community extremely easy to confuse with an "official account" of the thing in question.

Which one of these is a Firefox account by Mozilla? (Search term "Firefox" on https://mastodon.social/search.)

![image](https://github.com/LemmyNet/lemmy/assets/18599032/530410d8-4639-4f51-aceb-789664045b05)

It's extremely easy to make the wrong assumption that "Lemmy.ml" is yet another Mastodon instance or, even if you knew better, that this handle is the official Firefox account on Lemmy.

You'd have to be familiar with what Lemmy is and how its communities work via AP to know what is actually going on here.

What makes this somewhat worse is that, at least on Mastodon, the `@` auto completion inside the editor is a very small window where the instance name often gets cut off.

### Describe the solution you'd like.

Perhaps Lemmy should, as a default policy, explicitly declare its communities as such.

One easy way to achieve this would be to append `community` or `(community)` the display name. Something like

![image](https://github.com/LemmyNet/lemmy/assets/18599032/bd5dc166-2756-4ed2-8163-54324ecc56c1)  
or  
![image](https://github.com/LemmyNet/lemmy/assets/18599032/839375a3-8308-42fc-b936-f0019f0d9af7)

### Describe alternatives you've considered.

The respective AP clients should visibly differentiate between a group and a user to avoid confusion; making a change like this less necessary.

Brands, celebrities and organisations should also verify their accounts.

Still, communities will likely always attract a similar or more followers and a lot more traffic than the actual user account. I therefore still think communities should explicitly "declare" themselves as such to the wider network to avoid any confusion.  
They already do so at the protocol level of course but not at the human one and I think that's important to consider too.

**Comment by Leatherface75** [comment]
This is a Mastodon problem and if you check the profile it will say group (Grupp).

![image](https://github.com/LemmyNet/lemmy/assets/2489019/5fbc7a6f-6c7c-424b-8744-d1ba07d5a9e6)

**Comment by Atemu** [comment]
@Leatherface75 see discussion in the "Describe alternatives you've considered." section.

**Comment by Leatherface75** [comment]
> @Leatherface75 see discussion in the "Describe alternatives you've considered." section.

Again this is not a Lemmy problem it's a Mastodon problem.
It needs to add (Group) in searchlist and not only in profile like for example Friendica and others already do.

**Comment by Atemu** [comment]
At this point I'm not sure whether you're intentionally ignoring what I wrote.

**Comment by Leatherface75** [comment]
> At this point I'm not sure whether you're intentionally ignoring what I wrote.

I see what you wrote but you don't seem to understand that Lemmy already does this.
It's Mastodon that doesn't in that listing above.
It shows group when you go to the profile so there it recognises it as a group.
As i showed above other software like Friendica shows (Group) something like you requested.

**Comment by Atemu** [comment]
>  They already do so at the protocol level of course but not at the human one and I think that's important to consider too.

**Comment by Leatherface75** [comment]
> > They already do so at the protocol level of course but not at the human one and I think that's important to consider too.

Again this must be done in Mastodon.

**Comment by Leatherface75** [comment]
This will probably change soon anyway because they're working on groups support in Mastodon.

https://github.com/mastodon/mastodon/pull/19059

**Comment by Nutomic** [comment]
As mentioned this needs to be fixed in Mastodon. Lemmy communities are federated as `type=Group` as opposed to `type=Person` so its easy to distinguish.
