### ISSUE TITLE
[Bug]: ampersand (&) displayed as (&amp;) in post title

### ISSUE THREAD

**Issue by m3t0034** [LemmyNet/lemmy#4357]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

https://lemmy.world/post/10378874
text from external site:
https://science.nasa.gov/eclipses/future-eclipses/eclipse-2024/where-when/

### Steps to Reproduce

1. Make a post with linked site having an ampersand in it's title like: https://science.nasa.gov/eclipses/future-eclipses/eclipse-2024/where-when/
2. observe final post title. &amp; html entity displayed
3.

### Technical Details

Firefox on latest ubuntu. recurring display bug. Same in Chrome.

### Version

https://p.us5.datadoghq.com/sb/e801a480-2ef0-11ee-8d4a-da7ad0900005-4fd5fc281f6aaf614c417e63228c0e31?refresh_mode=sliding&from_ts=1704756232632&to_ts=1704759832632&live=true

### Lemmy Instance URL

lemmy.world

**Comment by Nutomic** [comment]
This is fixed in 0.19
