### ISSUE TITLE
[Bug]: Last 3ish weeks of activity wiped after upgrading to 0.19.2

### ISSUE THREAD

**Issue by BrianAllred** [LemmyNet/lemmy#4362]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Ran the update from 0.19.1 to 0.19.2 on my instance and the last about 3 weeks of activity (posts, comments, new users, new subscriptions) are all gone.

You can see on my instance's version of [!analogue_pocket@lemmy.world ](https://lemmy.frozeninferno.xyz/c/analogue_pocket@lemmy.world), the post I made [today](https://lemmy.world/post/10542473) doesn't show up.

### Steps to Reproduce

1. Upgrade dockerized Lemmy from 0.19.1 to 0.19.2
2. Activity and content from the last 3 weeks are gone

### Technical Details

* Docker 24.0.7 on Proxmox VE 8.1.3
* [lemmy_log.out.zip](https://github.com/LemmyNet/lemmy/files/13895457/lemmy_log.out.zip) (they're 50 MB uncompressed)

### Version

BE 0.19.2

### Lemmy Instance URL

https://lemmy.frozeninferno.xyz

**Comment by BrianAllred** [comment]
I'm getting new activity, but it seems like everything between 3 weeks ago and the upgrade is missing.

**Comment by dessalines** [comment]
There were no db changes in this release, and it shouldn't have touched postgres. I can't think of anything besides a possibly messed up postgres installation, but we'd need to see your docker compose.

**Comment by BrianAllred** [comment]
You're exactly right, I used an old docker compose file that referenced an older version of the database. Entirely my fault, fixed now.

**Comment by dessalines** [comment]
No probs.
