### ISSUE TITLE
[Bug]: lemmy_server::root_span_builder: Unknown: Failed to parse object

### ISSUE THREAD

**Issue by lazynooblet** [LemmyNet/lemmy#4368]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I've just updated https://lazysoci.al/ to 0.19.2 and have been watching logs for last 15 minutes. Immediately after the upgrade logs are filled with a new error

```lemmy-core      | 2024-01-12T13:26:07.257585Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: Unknown: Failed to parse object https://lemmy.world/comment/6612311 with content```

This is then followed by 500+ lines of HTML from the related instance page (looks to be the entire page). And ending with....

```lemmy-core      |   : expected value at line 2 column 5
lemmy-core      |    0: lemmy_apub::activity_lists::community
lemmy-core      |              at crates/apub/src/activity_lists.rs:103
lemmy-core      |    1: lemmy_apub::activities::community::announce::receive
lemmy-core      |              at crates/apub/src/activities/community/announce.rs:154
lemmy-core      |    2: lemmy_server::root_span_builder::HTTP request
lemmy-core      |            with http.method=POST http.scheme="https" http.host=lazysoci.al http.target=/inbox otel.kind="server" request_id=01f817f8-8d21-4996-8e93-c9ae9a66ca6c http.status_code=400 otel.status_code="OK"
lemmy-core      |              at src/root_span_builder.rs:16
```

This is then occuring a few a minute. I'm concerned this is resulting in failed federated content.

### Steps to Reproduce

1. Update to 0.19.2
2. Watch logs

### Technical Details

Attached related log part as its too large for github.
[lazysoci.al_log-snippet.txt](https://github.com/LemmyNet/lemmy/files/13919686/lazysoci.al_log-snippet.txt)

### Version

0.19;.2

### Lemmy Instance URL

lazysoci.al

**Comment by Nutomic** [comment]
Looks like lemmy.world configured something wrong, I notified them.
