### ISSUE TITLE
post unique/idempotent/non-duplicate URL/link

### ISSUE THREAD

**Issue by PatMyron** [LemmyNet/lemmy#4370]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

---

### Problem?

Seamlessly ensure posted URLs / links have not already been submitted to that community

### Describe a solution 

`resubmit` option like https://www.reddit.com/dev/api/#POST_api_submit

### Describe alternatives 

Searching or listing all posts via API

**Comment by MV-GH** [comment]
The search has option to search on url. But a dedicated endpoint for this that returns 200 or 4XX would indeed be even simpler. A community could even enforce that only unique links are posted.

**Comment by PatMyron** [comment]
@dessalines suggested duplicates searches based on title rather than URL:
https://github.com/LemmyNet/lemmy-ui/blob/1787a778f8cf01fb1b00262e44ae8e49f9b3ccc1/src/shared/components/post/post-form.tsx#L655

**Comment by dessalines** [comment]
Doing fuzzy text searching to link cross-posts rather than URLs seems like it'd have a lot of potential issues.

**Comment by PatMyron** [comment]
> Doing fuzzy text searching to link cross-posts rather than URLs seems like it'd have a lot of potential issues.

...ok to re-open this issue then? I agree URL searching rather than just text searching would be better, which is why I linked the `lemmy-ui` code where it's currently just text searching. While technically already possible, I think streamlining URL searching for duplicates would be useful for both UI and API posters

**Comment by dessalines** [comment]
Hrm thought we already did fetchSimilar based on URL, not just title. But that could always be added to the front end, not here.

I still don't know what you're missing tho that [Search](https://join-lemmy.org/api/classes/LemmyHttp.html#search) doesn't already have, since it has a `SearchType.URL` . If its missing something, why not add it there?
