### ISSUE TITLE
Federated TAG system for flexlible programmable auto-cross posting (thorugh linking post in different instance, not duplicating)

### ISSUE THREAD

**Issue by alexwbc** [LemmyNet/lemmy#4375]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

If you search for "pcgaming" in the federated lemmyverse you may find these results:

PC Gaming@lemmy.ca - 6.32K subscribers
PCGaming@lemmy.world - 5.17K subscribers
PC Gaming@lemmy.ml - 1.78K subscribers
PC Gaming@kbin.social - 154 subscribers
PC Gaming@lemmy.fmhy.ml - 26 subscribers

This poses a fragmentation problem as communities growth are split, and often killed, by uneven competition: we can argue that "certainly someday one will win", but chances are in favor that people on the "losing ground" instead keep looking for the same thing here on Lemmy will simply return to the "bigger/old" one (I am talking about the "/R" one).

### Describe the solution you'd like.

Each community build on lemmy, whatever server it may be, come with **one single special tag**... which is... their name.

So, `#pcgaming` is the **root tag** for !PCGaming@lemmy.ca,!PCGaming@lemmy.world,!PC Gaming@lemmy.ml,!PCGaming and PCGaming@lemmy.fmhy.ml
If you don't like your root tag associated with these communities... either you change your name (ie: pc_gaming or something like that) or set your ***.**/c/pcgaming community on the federated blacklist (akin of the good 'ol ROBOTS.TXT with apache servers).

How would it work?
Let's suppose I post an article on **PCGaming@lemmy.world**; you'll see nothing special, but just a regular thread opened on lemmy.world/c/pcgaming.
Now, let's suppose both lemmy.world, lemmy.ml and kbin.social are open to this feature ("Federated Tagging System) but not lemmy.fmhy.ml; while lemmy.ca has choose to not federate with lemmy.world at all!

first result here: lemmy.fmhy.ml and  lemmy.ca servers will be unaffected by this feature. no other checks are needed; but what happen for both lemmy.world, lemmy.ml and kbin.social?

kbin.social/c/pcgaming community have choosen to specifically blacklist/disable TAG federation with **PCGaming@lemmy.world**/c/pcgaming (while they are still fine/enabled with lemmy.ml/c/pcgaming), result: they won't see anything as well.

And finally we come to the feature coming in effect: both lemmy.world, lemmy.ml and their respective /c/pcgaming communities are set on default: it mean both their federated tag system is working.

While the specific post is still hosted on !pcgaming@lemmy.world users on !pcgaming@lemmy.ml will see a "virtual cross post" in their community. While visually transparent to the guest community (!pcgaming@lemmy.ml) the virtual cross behave as just a link: activity such as up/down vote or commenting to that thread must be authorized by lemmy.world server (maybe just an iframe so resources are not wasted in continous mirroring between servers?

### Describe alternatives you've considered.

Maybe some auto post-crossing in which are put on the list of "mod pending approval"?

Or maybe even a "community tag system" in which some communities work as some sort of "folder" that collect an asset of different single federated tag system. Ie. the random community /c/gaming may want to collect root tag like pcgaming, xboxgaming, switchgaming and so go on.

**Comment by Nutomic** [comment]
Sounds mostly like a duplicate of https://github.com/LemmyNet/lemmy/issues/818

**Comment by alexwbc** [comment]
> Sounds mostly like a duplicate of #818
Not really, but following the #818  I've found this one #1113 which is more closer to the concept and the discussion is broader with more solutions.
