### ISSUE TITLE
[Bug]: Posts with unescaped symbols cause RSS to break

### ISSUE THREAD

**Issue by DutchO7** [LemmyNet/lemmy#4382]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When there is a post with unescaped bytes, the RSS feed will fail to validate, and will not be able to be read by a feed reader.

This is the post that has caused trouble with my feed reader:
https://lemmy.ml/post/10615518

Attached is a zip archive containing the feed that broke thunderbird from my home instance, and the feed from the programmerhumor on the lemmy.ml instance which is also broken.
https://github.com/LemmyNet/lemmy/files/13950414/brokenfeeds.zip

### Steps to Reproduce

1. Make or find a post with nonsense binary data in it
2. Download a rss feed that includes the post
3. It wont validate

### Technical Details

There is an error in thunderbird saying that my rss url is not a valid one, thunderbird linked me to [this](https://validator.w3.org/feed/) validator, and it highlighted the bytes being trouble in red, and saying it does not validate.

### Version

BE: 0.19.2, BE: 0.18.4-kt.2

### Lemmy Instance URL

lemmy.blahaj.zone, lemmy.ml

**Comment by Nutomic** [comment]
I guess the easiest solution would be to wrap all strings in CDATA. Contributions welcome, the relevant code is [here](https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/feeds.rs)

**Comment by Elara6331** [comment]
If you look at the RSS output, the data is actually already wrapped with `CDATA` by the rss crate. The problem is that `CDATA` doesn't allow characters outside of the subset allowed by XML, and there's no XML syntax that allows raw bytes inside a document, so there really isn't much that can be done here, other than removing any characters that aren't allowed.
