### ISSUE TITLE
[Bug]: Hot sort showing years old posts

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy#4383]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I see a bunch of years old posts with a score of 1 showing up at the bottom of the front page when sorting !lemmy@lemmy.ml by Hot, maybe integer underflow?

### Steps to Reproduce

1. go to https://programming.dev/c/lemmy@lemmy.ml?dataType=Post&sort=Hot
2. at the bottom of the front page see the years old posts

### Technical Details

https://lemmy.ml/post/62682

![image](https://github.com/LemmyNet/lemmy/assets/30947252/f7cfa050-bd77-464e-b249-ca6c4951b7e0)

### Version

0.18.1

### Lemmy Instance URL

programming.dev

**Comment by Die4Ever** [comment]
the 2nd page has a bunch of posts I would expect to be way ahead of those years old posts

![image](https://github.com/LemmyNet/lemmy/assets/30947252/7a4e15c9-6f11-4ec6-a91b-0aef0d3b5019)

**Comment by Die4Ever** [comment]
looking at the code, it seems like the view is missing a secondary sort?

https://github.com/LemmyNet/lemmy/blob/main/crates/db_views/src/post_view.rs#L470

maybe it was broken by this commit

https://github.com/LemmyNet/lemmy/commit/32afc32bc085862dc09d19370b1ccde7b17c9a2f

**Comment by Nutomic** [comment]
Seems like a problem with the hot rank calculation, after this time the rank should be much lower. cc @dessalines

**Comment by Die4Ever** [comment]
> Seems like a problem with the hot rank calculation, after this time the rank should be much lower. cc @dessalines

Ategon confirmed in the DB that the hot rank score is 0 for all of these, I believe it's always going to be 0 when the post hits 7 days old? so I think it's just missing a secondary sort

**Comment by Nutomic** [comment]
There is a [secondary sort by post id](https://github.com/LemmyNet/lemmy/blob/main/crates/db_views/src/post_view.rs#L497). But if those posts were fetched recently via federation then they would have a higher post id than newer posts. Ive opened https://github.com/LemmyNet/lemmy/pull/4384 which should fix this.

**Comment by dullbananas** [comment]
This should be fixed by #4320
