### ISSUE TITLE
Facebook style customizable questionaire before joining community

### ISSUE THREAD

**Issue by pixiekat** [LemmyNet/lemmy#4385]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

If you run a community and want to be able to screen subscribers before allowing them access, it would be nice to be able to set up a customizable set of 1-3 questions (checkbox, textfield, textarea) that a user would need to fill out which would then be reviewed by the mods and either accepted or denied. This could be used to screen out potential trolls, set up a character description in a roleplay group, let the mods know what your favourite genre is in a book group, allow the user to tell the mods a bit about themselves or how they identify, or just allow the user to accept some conditions for membership.

### Describe the solution you'd like.

Ideally, the admin or mod would be able to set up a number of participation questions that a prospective user must answer before a decision is made by the mods and admins. 

Then you could set the group to require answers for the participation questions before becoming a member and viewing so a new perspective member would click on a subscribe button (or maybe request membership) button and they would be presented with the questions, which they would fill out and click submit.

A message would be displayed indicating they'll receive an answer soon, at which point the mods will be alerted via notifications where they can review the answers and either accept or deny. 

The user would then be notified of the decision.

### Describe alternatives you've considered.

There's not really an alternative for now, short of having a sticky post and allowing users to post there after joining, but that defeats the purpose. 

### Additional context

The proposal is similar to how Facebook group participation questions work: https://www.facebook.com/help/200755420421098. It's handy for a lot of queer groups that I'm in in order to control access and keep out bigots, etc.

**Comment by dessalines** [comment]
This already exists at the server-level, they're called registration applications and most lemmy servers already use them (or they should).

Until local / private communities #187 are added tho, this doesn't make much sense. atm communities are public.

**Comment by pixiekat** [comment]
> This already exists at the server-level, they're called registration applications and most lemmy servers already use them (or they should).

Just to clarify, I believe this is for registering to a *server* not individual communities within that server, IIRC? 

The suggestion would be for individual communities on a Lemmy server (ie, https://lemmy.world/c/fediverse) prior to joining them. 

> Until local / private communities https://github.com/LemmyNet/lemmy/issues/187 are added tho, this doesn't make much sense. atm communities are public.

Understood, though! Will follow this issue as well.

**Comment by dessalines** [comment]
Yep, applications are currently only when you want to join a server, not a community.
