### ISSUE TITLE
Resolving extra reports on at item that has been addressed. 

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4390]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Spam items or highly controversial items usually receive many reports. It's tedious after resolving one of them, to continue to resolve the others.

### Describe the solution you'd like.

I can think of two solutions:

- If the item's been removed, then **also** resolve all reports for that item. This should also work when banning and removing all posts for a user (IE remove_content).
- Resolve all other reports for an item, after you resolve one of them.
  - I don't like this solution as much, because there might be other things about that content that the first reporter, or resolver, didn't notice.

### Describe alternatives you've considered.

NA

### Additional context

NA

**Comment by Nutomic** [comment]
I think its reasonable that reports get marked as resolved automatically if the item in question is already removed or the user is banned. This can be done inside `create_post_report()` and `create_comment_report()` handlers (and also in federation handlers). 

There is also a db trigger for auto-resolving reports (https://github.com/LemmyNet/lemmy/pull/3871) but it only works for reports that were created before the post is removed.

**Comment by dessalines** [comment]
Good point, or simply throw a `item_already_removed` error when a new report is made for a removed item.

For some reason that trigger doesn't seem to be working at all... I've removed and banned users and the reports still show as open. Its probably more transparent if we remove that trigger and do it in code also.

**Comment by Nutomic** [comment]
I can confirm the sql trigger to auto-resolve reports when a post is removed is broken. [This PR](https://github.com/LemmyNet/lemmy/pull/3850) has an alternative implementation in Rust.

**Comment by dessalines** [comment]
That link is the old SQL-trigger-based method. I don't see any new PR for a rust version.

> Essentially, I wish Lemmy's reporting system centered around the item being reported, rather than each individual report.

This could get complicated when you take into account things like original comment text at the time of reporting, resolving an array of reports for an item that then gets a *new* report, etc.

**Comment by aeharding** [comment]
> This could get complicated when you take into account things like original comment text at the time of reporting, resolving an array of reports for an item that then gets a _new_ report, etc.

Perhaps. However it works quite well at Reddit (and scales well moderating large communities and report #s) despite only showing latest text.

**Comment by dessalines** [comment]
K I got it now.
