### ISSUE TITLE
Use a different SQL formatter

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#4405]
The horrific formatting of this file is forced by the formatter that's currently used

https://github.com/dullbananas/lemmy/blob/bliss/replaceable_schema.sql

**Comment by Nutomic** [comment]
Any suggestions? You could also try adjusting the configuration of pg_format.

**Comment by dessalines** [comment]
I remember trying this [prettier plugin for SQL](https://github.com/nene/prettier-plugin-sql-cst), but I don't think it worked as well.

**Comment by dullbananas** [comment]
Doesn't format function bodies:

* [sqlformat](https://sqlparse.readthedocs.io/en/latest/ui/) from the [sqlparse](https://pypi.org/project/sqlparse/) python package
* [prettier-plugin-sql](https://github.com/un-ts/prettier/tree/master/packages/sql)

Not fully implemented yet; throws syntax error:

* [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst)

**Comment by phiresky** [comment]
The link to the query above no longer works so I can't see exactly what you mean. But last time I investigated SQL formatters, the one we use now was the best there was. 

In a different project, what I did was add a filter if the file starts with `-- pgFormatter-ignore` it is skipped and not formatted. That "fixed" the few cases where pgformatter was annoying.

**Comment by Nutomic** [comment]
Feel free to open a PR for this.
