### ISSUE TITLE
[Bug]: Lemmy postgres 15 memory leak (possible solution)

### ISSUE THREAD

**Issue by linux-cultist** [LemmyNet/lemmy#4406]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

There is a memory leak in postgres 15 that is affecting some Lemmy instances. 

It was previously discussed here: https://github.com/LemmyNet/lemmy/issues/4017

On a smaller instance with 4 GB RAM, its very noticable when you have the bug, because postgres only lasts for 3-4 hours before it gets killed by the OOM killer.

After many weeks of trying to figure this one out, I found a discussion on the Postgres forum:

https://www.postgresql.org/message-id/flat/16707-f5df308978a55bf8%40postgresql.org

Adding `jit = 0` to the `customPostgresql.conf` file seems to fix the problem, or at least reduce it very much.

This is supposed to be fixed in Postgres 16 but Lemmy may be a long time on 15.

I know this is not a Lemmy bug per se, but judging from the previous thread, it does affect quite a few instances, and they would be happy to see some kind of a solution.

Maybe it can be added to the docs or somehow highlighted to the community somehow?

### Steps to Reproduce

1. Run a smaller instance
2. Keep an eye on postgres memory
3. Run `dmesg -T | egrep -i 'killed process'` after a day or two to see how postgres or lemmy has been killed by OOM.

### Technical Details

N/A

### Version

0.19.3

### Lemmy Instance URL

N/A

**Comment by Nutomic** [comment]
Thanks for the info, Ive set the config option on lemmy.ml to see if it helps, and mentioned it in the admin chat. If it really works we can make a post in /c/announcements about it.

**Comment by linux-cultist** [comment]
It helps on my instance and slows down the memory leak significantly. But its still there and memory use slowly increases until OOM still. 

Im not sure if its safe to test running Lemmy with postgres 16 to see if its still there in that version, or if it risks causing problems with the database if I do.

**Comment by jivandabeast** [comment]
Have the same issue, was starting to think i messed something up! Will look into your solution tonight

**Comment by Nutomic** [comment]
CI runs without problems using Postgres 16 so it should be fine to upgrade.

https://woodpecker.join-lemmy.org/repos/129/pipeline/5366/21

**Comment by dessalines** [comment]
Remember there's no way to do a clean upgrade path with that, and I'll need to write another backup and restore script with instructions.

**Comment by Nutomic** [comment]
The migration should be identical to [postgres 12 to 15 migration](https://github.com/LemmyNet/lemmy/blob/main/scripts/postgres_12_to_15_upgrade.sh), just changing the version numbers. If its confirmed that postgres 16 fixes the memory leak it might be worth updating.

**Comment by linux-cultist** [comment]
Postgres 16 fixes that particular memory leak, but it was for another application than Lemmy. So hard to be certain it would fix Lemmy as well. Only way to be sure is to test running Lemmy with Postgres 16 I guess. I would do it, but dont want to risk messing up the database, or being unable to go back to version 15... :)

**Comment by dessalines** [comment]
Seems like a good idea to upgrade then, especially since 15 -> 16 isn't *required* like the last one was. 

I'll create a PR with that upgrade script soon, and provide some instructions for the next lemmy-ansible release.

**Comment by linux-cultist** [comment]
Sounds great, probably only gains from upgrading. 👍
