### ISSUE TITLE
fediverse nsfw-image embed fails

### ISSUE THREAD

**Issue by tekakutli** [LemmyNet/lemmy#4408]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

yes, when I post a link to a fediverse note it successfully pulls in the image, EXCEPT when it's marked as nsfw,
then it pulls in the profile pic of the poster

one may argue that's intended  behaviour, but if I post the url to the image directly it pulls it in without issue 
the caveat is that I lose the text part of the post

### Describe the solution you'd like.

pull in the attachment regardless of the nsfw or content warning flag of the queried instance 
let lemmy own nsfw checkbox in charge of hiding it

### Describe alternatives you've considered.

I tried to embed a third party widget on the markdown part of the post but it didn't work

**Comment by Nutomic** [comment]
Which Lemmy version are you running and waht does the pictrs section of your config look like?
