### ISSUE TITLE
[Bug]: upvotes and comments on peertube v6 doesn't seem to work anymore

### ISSUE THREAD

**Issue by srouquette** [LemmyNet/lemmy#4418]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

jlai.lu has been updated recently with the latest Lemmy version (0.19.3), and it restored peertube v6 import.

Now that we can import peertube videos, it seems we can't interact with them anymore.

example:
https://jlai.lu/post/3997332
https://peertube.stream/w/9bc5d635-49de-443e-98fe-c5756c6779e4
comment doesn't appear

It was working with BE 0.18.5 and peertube v5

### Steps to Reproduce

1. search with lemmy a peertube video: https://peertube.stream/w/9bc5d635-49de-443e-98fe-c5756c6779e4
2. click on the lemmy post, upvote and comment
3. check the peertube video if the comment appears
4. comment doesn't appear

### Technical Details

N/A

### Version

BE 0.19.3

### Lemmy Instance URL

https://jlai.lu/post/3997332

**Comment by Nutomic** [comment]
I dont think there were any breaking changes in this area in Lemmy. Could you test if the federation works with Lemmy 0.19 and a Peertube v5 instance? Then we would know which side is causing the problem.

**Comment by Nutomic** [comment]
Are there any errors being logged on the Lemmy/Peertube server when making a comment/vote?

**Comment by srouquette** [comment]
it's fixed, it was a global problem with our instance federation outside of our instance. I'll close this.
