### ISSUE TITLE
[Bug]: api/v3/user returns empty posts array but account has posts if auth query provides correct JWT

### ISSUE THREAD

**Issue by iatenine** [LemmyNet/lemmy#4423]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Basically title, if I remove or alter the auth query param to be incorrect the result comes back fine. Not sure why this occurs as it's not consistent between accounts but it consistently impacts one of my Lemmy.world accounts,

### Steps to Reproduce

1. Log in to an impacted account (not sure who else is besides JackLSauce@lemmy.world)
2. Go to My Profile -> Posts
3. Observe network response

### Technical Details

The following command returns the expected result:
`curl 'https://lemmy.world/api/v3/user?username=JackLSauce&sort=Old&page=1&limit=20'`
and can be used directly from my terminal, while the one called by the site returns the same body except with an empty posts array
![Screenshot from 2024-02-03 20-47-08](https://github.com/LemmyNet/lemmy/assets/4423088/42eee64d-b8a0-42b4-a686-11509daa308d)

### Version

0.18.5

### Lemmy Instance URL

lemmy.world

**Comment by Nutomic** [comment]
Check the user account for "hide read posts" setting, language filters and blocks. Most likely its caused by one of those. Also you are on an old version, if there is a bug you need to check if it can be reproduced with the latest release (eg on ds9.lemmy.ml).

**Comment by dessalines** [comment]
This is almost certainly having to do with language not selecting undetermined.

**Comment by iatenine** [comment]
> Check the user account for "hide read posts" setting, language filters and blocks. Most likely its caused by one of those. Also you are on an old version, if there is a bug you need to check if it can be reproduced with the latest release (eg on ds9.lemmy.ml).

It was the "show read posts" filter, thanks!
I thought that meant "don't show me the same posts on the homepage over and over" which tbf felt like it used to happen more often
