### ISSUE TITLE
[Bug]: When banning and removing data, the removals don't federate.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4430]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Make sure removals federate when banning and removing data.

### Steps to Reproduce

1. Ban a user, with remove-data : true
2. These removals aren't federated.

### Technical Details

Na

### Version

Main

### Lemmy Instance URL

All

**Comment by Nutomic** [comment]
Api tests say that [its working](https://github.com/LemmyNet/lemmy/blob/main/api_tests/src/post.spec.ts#L409). Or is this related to the [following test which is being skipped](https://github.com/LemmyNet/lemmy/blob/main/api_tests/src/post.spec.ts#L479)?

**Comment by dessalines** [comment]
That code looks fine but I think we're missing some test cases.

[This might be the problem](https://github.com/LemmyNet/lemmy/blob/f631f43024632845d384229408da4d19dfceec80/crates/apub/src/activities/block/mod.rs#L147) , but its a little difficult to read since this is handled on apub receiving code.

Its only sending out a Block if that person is local. But we must be missing some cases, such as:

- A federated user makes a bunch of posts on our local communities. When we site ban and remove data, it needs to federate removals of their comments and posts to our local communities.

The only solution I can think of, is to move the logic out of apub receives, and into [remove_user_data](https://github.com/LemmyNet/lemmy/blob/f631f43024632845d384229408da4d19dfceec80/crates/api_common/src/utils.rs#L627). IE when doing either a site or community ban, on any user, loop over all their local content, and federate removals.

**Comment by Nothing4You** [comment]
Is that not #4118?

**Comment by Nothing4You** [comment]
> when doing […] a […] community ban

Community bans do federate content removal for remote users already, it's just site bans that don't federate content removal.

**Comment by Nutomic** [comment]
If someone writes an [api test](https://github.com/LemmyNet/lemmy/tree/main/api_tests) which reveals this bug I can look into it.

**Comment by dessalines** [comment]
Yes thx, this is a dupe of #4118
