### ISSUE TITLE
Instance Block for Non-Local Direct Messages (DMs)

### ISSUE THREAD

**Issue by cassandracomar** [LemmyNet/lemmy#4444]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

minority communities on lemmy frequently get targeted for harassment by malicious users via DMs. while those users can block specific instances, they frequently have to first receive vile or outright triggering material before they block specific users or instances. this leads to instances defederating other instances wholesale in order to continue providing safe spaces for their users. this limits the ability of those instances to maintain wide federation and fractures the lemmy community.

### Describe the solution you'd like.

add an instance setting to, by default, block non-local instances from sending DMs. users should have a setting to opt-out of this or, if the instance does not set it for the whole instance, to opt-in to it. if the setting is toggled, users should not be able to receive DMs from non-local instances.

users need the ability to opt-out or opt-in because some users, like mods and admins, need or want the ability to continue to receive DMs from all federated instances, even when the instance default prohibits it.

an instance-default setting for this is ideal because users don't necessarily know what features are available and may miss communication telling them that the feature is available, leaving them exposed to nastygrams.

related issue: https://github.com/LemmyNet/lemmy/issues/3640

if this feature request is accepted, I'll open a matching front-end issue to track exposing the setting to instances and users.

### Describe alternatives you've considered.

* using a bot with site-admin permissions to automatically delete and flag DMs for admin review. I don't believe such a thing is possible and even if it were, it puts an incredible load on instance administrators of even moderately sized instances.
* allowing users to opt-in to instance blocks -- this feature is already available but 1. I don't believe it actually blocks DM, per the issue I linked above and 2. users generally have to receive unwanted and harmful content before they go looking for a way to disable receiving it.
* a setting to just disable DMs entirely -- while this also works, it goes a step further than we need, as users generally make accounts on instances that provide them the protections they need. the issue is that other instances don't have the same moderation policies as the ones that provide safe spaces and so users don't get banned, even after DM or reply harassment. the proposal is a step below a wholesale block on DMs so direct communication with users on the local instance can continue.
* the same proposal as the one above except that rather than local-only, we provide a user-controlled whitelist so they can maintain DMs with specific instances, other than the local one. while this would be nice, it's more complicated, and local-only DMs would go a huge percentage of the way to an ideal solution.

### Additional context

* https://github.com/LemmyNet/lemmy/issues/3640
* https://github.com/LemmyNet/lemmy/issues/3629
* https://github.com/LemmyNet/lemmy/issues/4205

also, I'm willing and able to implement the feature, if it's accepted.

**Comment by sunaurus** [comment]
I'm wondering if the local/remote distinction is actually necessary here. It makes complete sense to me to allow users to configure if they want to receive DMs or not (or maybe only receive DMs from users they've DMed first?), and it makes sense to allow admins to set the default setting for new users, but applying the setting only for non-local users hints at a deeper problem somewhere.

Maybe the deeper problem is this: until very recent version of Lemmy, admins weren't receiving reports at all for content their users posted on other instances. As far as I know, this should be fixed now in general, so I'm assuming it's also fixed for DM reports, if not, then probably fixing this should be prioritized first. 

But assuming that DM reports are now actually working properly (as in, remote admins on the latest version of Lemmy will receive the report if your user reports a DM), then: in case of harassment, relevant admins can always take action, regardless of whether the offending user is remote or local. So to me it seems like the local/remote distinction is not super relevant. It's a bit of a different story when federating with any instance where admins don't take action for reports of harassment against minorities, but then again, in that case, the problem wouldn't just be limited to DMs anyway, but would also apply to posts and comments, right?

**Comment by sunaurus** [comment]
Btw, this is a bit of a derail, but I'm in general quite worried about the trend of people having massive in-group and out-group mentalities regarding Lemmy instances, where prejudice is regularly applied to users depending on what instance they created their account on, and I feel like adding settings that specifically target remote users will only enforce this trend.

IMO we should be focused on individual users, rather than their home instances, except for extreme cases where it's obvious that a specific instance is being used to create abuse (in which case, defederation is a perfectly valid option). This means focusing on improving Lemmy to remove any cases where moderating remote users is for any reason more difficult than moderating local users, rather than just making remote users kind of second-class citizens.

But I know that there are also lots of people who don't view this instance based in-group situation as a problem at all, so it's a very subjective opinion for sure.

**Comment by cassandracomar** [comment]
different instances have different moderation policies. the one I frequent most heavily is very heavily moderated while others just aren't. there's 0 DM harassment on that instance, at least that I and others have seen, but other instances are much more lax and our users complain of DM harassment from those instances much more frequently. 

DMs are useful. we use it a lot to help each other. turning them off entirely would be a detriment to our communities. being able to be more selective about which spaces we can receive DMs from would go a long way towards our ability to remain federated with other instances. without some way to control who we receive DMs from, I suspect we will slowly return to a state of non-federation, as marginalized users report again and again that a space that was once safe no longer is. 

it's from that place that I'm suggesting this feature, as a useful addition that would give us the capability to thread that needle. 

> Maybe the deeper problem is this: until very recent version of Lemmy, admins weren't receiving reports at all for content their users posted on other instances. As far as I know, this should be fixed now in general, so I'm assuming it's also fixed for DM reports, if not, then probably fixing this should be prioritized first.

that's good to know. it doesn't change the numbers game though, or that it's marginalized people getting targeted. our users don't want to receive the DMs and then report them, they want not to receive them in the first place. but local DMs are different and are largely a positive experience, especially as they allow us to provide each other with various kinds of aid that can't be posted publicly due to the exchange of personal info that doesn't belong in posts/comments.

**Comment by dessalines** [comment]
We can use the existing `instance_block` table for this. 

@Nutomic I could alter the `PrivateMessageQuery` to work with instance blocks, but should this also be handled in the apub receive code?

**Comment by dessalines** [comment]
I spose I'll just do the 2nd one then.

**Comment by cassandracomar** [comment]
thanks all, I'll get the frontend ticket opened.

**Comment by Nutomic** [comment]
@cassandracomar No need, this uses the existing instance block functionality which was added in 0.19
