### ISSUE TITLE
Create an interface for local users to view and remove images.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4445]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Users need to be able to view, and delete their image uploads (one at a time, or all when they delete their account).

### Describe the solution you'd like.

This info is already stored in the `local_image` table.

![Screenshot_20240212_100939_Termux](https://github.com/LemmyNet/lemmy/assets/930215/f79e8c04-7ece-455b-9d1f-2f19520febff)

- Create a tab in your user settings that shows a list of images.
- Have a delete button that forwards that request to the local pictrs

### Describe alternatives you've considered.

NA

### Additional context

LemmyNet/lemmy-ui#2384

**Comment by Nutomic** [comment]
It would be better if we could associate every image with the post or comment where it was used, and delete it if the post itself gets deleted.

**Comment by maltfield** [comment]
@Nutomic that would be a reasonable addition, but users should still be able to delete images that are not attached to a post or comment.

This isn't hypothetical. It's likely to happen a lot -- especially for images that were *accidentally* uploaded and are the most-desired images to be deleted by users. See also:

 * https://github.com/dessalines/jerboa/issues/1363#issue-2127772569

**Comment by maltfield** [comment]
See also corresponding ticket in lemmy-ui:

 * https://github.com/LemmyNet/lemmy-ui/issues/2359

**Comment by dessalines** [comment]
> It would be better if we could associate every image with the post or comment where it was used, and delete it if the post itself gets deleted.

I agree, that would be good also. We'd need to add a `local_image_post: {local_image_id, post_id}` , and the same for comment. But the main issue is that people can upload images **before** that content is even created. And for comments, we'd have to scan their comment body for local images. Possibly more work than is worth it.

> that would be a reasonable addition, but users should still be able to delete "orphaned" images (that are not attached to a post or comment).

Very correct. Any markdown field or image upload box allows you to upload the item *before* its even created.

**Comment by SleeplessOne1917** [comment]
> But the main issue is that people can upload images before that content is even created.

This can be partly mitigated by keeping selected images local and only updating on submit. This is likely simple with pictures that become urls for posts, but much more difficult for images used in markdown.

Also worth considering are pfps, user banners, images in bios, and images in DMs. I'm unsure how commumity icons and banners should be handled.

**Comment by maltfield** [comment]
For additional context of this issue, please see [Nightmare on Lemmy Street (A Fediverse GDPR Horror Story)](https://tech.michaelaltfield.net/2024/03/04/lemmy-fediverse-gdpr/)

[![Nightmare on Lemmy St - A GDPR Horror Story](https://tech.michaelaltfield.net/wp-content/uploads/sites/5/lemmy-fediverse-gdpr_featuredImage2.jpg)](https://tech.michaelaltfield.net/2024/03/04/lemmy-fediverse-gdpr/)
