### ISSUE TITLE
[Bug]: Can't upload image. unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by RocketRide9** [LemmyNet/lemmy#4455]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
https://github.com/LemmyNet/lemmy/issues/3359 might be a duplicate, but I didn't install anything manually and used lemmy.world
I can also reproduce this issue in Voyager ui

### Steps to Reproduce

1. Click create new post
2. Upload image
3. See error

### Technical Details

Using firefox 122
lemmy.world is running lemmy 18.5

### Version

18.5

### Lemmy Instance URL

lemmy.world

**Comment by Nutomic** [comment]
Must be this: https://lemmy.world/post/11967676

**Comment by RocketRide9** [comment]
> Must be this: https://lemmy.world/post/11967676

Yes it is. I contacted lemmy world admins already. I think this issue can be closed.
