### ISSUE TITLE
Is there any way to remove the password character requirement?

### ISSUE THREAD

**Issue by kukumaka** [LemmyNet/lemmy#4467]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

People want to be able to quickly register for my lemmy instance.  They will most likely use similiar passwords to what they have used before.  The majority of people don't use 10 character passwords and it should be their choice.

Can this be done?
Or is there any way to do this manually?

### Describe the solution you'd like.

Remove or lower the character requirement for passwords.

### Describe alternatives you've considered.

6-8 character minimum password seems more reasonable

**Comment by Asudox** [comment]
As much as I can see, the limit is hardcoded:
https://github.com/LemmyNet/lemmy/blob/f56b84615c78a0ca9942e7a82c8d7ce4255ec5cb/crates/api_common/src/utils.rs#L374

So you would need to change and recompile it if you really want that.

**Comment by dessalines** [comment]
You could do this in a fork, but I don't see why we should lower them here. You can try putting 6-8 length passwords in any of those strength meters, and most of them can be broken with a few hours.
