### ISSUE TITLE
[Bug]: Missing URL thumbnail

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#4468]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

The following link has a missing thumbnail:

https://thebetter.news/amazon-deforestation-reduced/

### Steps to Reproduce

1. Create a new post with URL = https://thebetter.news/amazon-deforestation-reduced/
2. Observe missing thumbnail

Expected behavior: Lemmy should extract the jpg from the following document meta tag:

```html
<meta property="og:image" content="https://thebetter.news/wp-content/uploads/2024/01/lula-amazonas.jpg" />
```

resulting in https://thebetter.news/wp-content/uploads/2024/01/lula-amazonas.jpg.

### Technical Details

Observe missing thumbnails:

- https://lemmy.world/post/12218793
- https://lemm.ee/post/24404264

### Version

0.19.3

### Lemmy Instance URL

lemm.ee, lemmy.world

**Comment by dessalines** [comment]
Figured it out. Was a really weird issue where that site uses a non-standard doctype line with a space where it shouldn't be: 

https://github.com/LemmyNet/lemmy/pull/4472/files#diff-0cd13a4a101c05a54d9ab789fa06c9d48ab61c0e1f5c9b9a178440e9ba3a5ef5R101
