### ISSUE TITLE
possible tweak to hot_rank calculation

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy#4471]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Hot sorting seems to lean pretty hard towards new posts/comments, on Reddit it leans more towards highly upvoted posts/comments. I haven't really noticed this being an issue for posts, but for comments it can be a bit annoying to look for the actual conversations happening. I usually just sort comments by Top, but there's currently no way to set that as my default.

### Describe the solution you'd like.

Something as simple as tweaking this line, the constant number added to hours_diff, like using `hours_diff + 4` instead of `hours_diff + 2`

`RETURN log(greatest (2, score + 2)) / power((hours_diff + 4), 1.8);`

### Describe alternatives you've considered.

Changing the default comment sorting to Top? Or comments could use a different function for hot_rank than posts do?

### Additional context

I'd be curious to know how tweaking the offset for hot_rank (and scaled_rank) affects the feel of Lemmy for both posts and comments. I know I've heard lots of people viewing the posts feed with Top 12 Hours or similar because Hot leans too far towards new posts. This could be something tested in small increments, like v0.19.4 uses a +4, and then from there see how feedback goes and v0.19.5 could either use +3 or +8 or something or just go back to +2. This is something you'd really have to test in the wild and get user feedback on. Now that we have Scaled sort, maybe it doesn't need to lean so hard towards just new posts anymore.

I'm referencing this code for the hot_rank function https://github.com/LemmyNet/lemmy/blob/main/migrations/2023-10-23-184941_hot_rank_greatest_fix/up.sql#L6

**Comment by sunaurus** [comment]
>  I usually just sort comments by Top, but there's currently no way to set that as my default.

FYI, this is tracked in #4128, and there is already a PR to implement it: #4469

**Comment by Die4Ever** [comment]
> > I usually just sort comments by Top, but there's currently no way to set that as my default.
> 
> FYI, this is tracked in #4128, and there is already a PR to implement it: #4469

Yeah maybe this isn't necessary if everyone just changes their comment sorting to Top lol idk

**Comment by dessalines** [comment]
> Hot sorting seems to lean pretty hard towards new posts/comments, on Reddit it leans more towards highly upvoted posts/comments. I haven't really noticed this being an issue for posts, but for comments it can be a bit annoying to look for the actual conversations happening. I usually just sort comments by Top, but there's currently no way to set that as my default.

That's intentional, and we don't want to follow the reddit algorithm. See here : https://join-lemmy.org/docs/contributors/07-ranking-algo.html

Agree that my PR to add site and instance default sorts is the better way to go, rather than tweaking the hot sort.
