### ISSUE TITLE
Auto-Deletion Feature for Inactive Accounts

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#4494]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

No.

### Describe the solution you'd like.

I propose the implementation of a user setting that allows accounts to be automatically deleted after a specified period of inactivity. Users should have the option to choose from predefined periods such as 1 month, 3 months, 6 months, 1 year, or set a custom period according to their preference.

### Describe alternatives you've considered.

An alternative could be to send reminder emails to users after a certain period of inactivity, prompting them to either log in to keep their account active or manually delete it if they no longer wish to use Lemmy.

### Additional context

This feature could be particularly appealing to privacy-conscious users and those who value having control over their online presence.

**Comment by dessalines** [comment]
If a server had this, someone would definitely complain that their data is missing. 

If you want to work on this tho, I'll re-open.
