### ISSUE TITLE
Introduce a "Most Active" Sort Algorithm

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#4495]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Yes. Currently, Lemmy offers sorting options such as "active" which organizes posts by the most recent activity and "most comments" which ranks posts based on the total number of comments. However, both these sorting methods have limitations in capturing the pulse of real-time discussions. The "active" sort can be dominated by a few recent comments on different posts, not necessarily reflecting the most engaging discussions. The "most comments" sort, aggregates comments over the lifetime of a post, potentially missing out on current hot topics. This gap makes it challenging for users to immediately dive into the most lively discussions happening at the moment.

### Describe the solution you'd like.

I propose the implementation of a new sort algorithm titled "Most Active", "Real-Time Activity" or something like that. This feature would allow users to discover posts experiencing the highest level of engagement in real-time. Specifically, it would rank posts based on the number of comments received within recent time frame, such as the last hour. This sorting method would enable users to easily find and participate in the most active discussions as they unfold.

### Describe alternatives you've considered.

An alternative could be enhancing the existing "Most Comments" sort feature to include filters for users to select specific time frames. However, this approach might not be as intuitive or straightforward as introducing a dedicated "Most Active" sort option. Another possibility is to implement a "trending" sort, which could combine factors like the rate of new comments and upvotes, but this might dilute the focus on real-time discussion activity specifically.

### Additional context

The introduction of this sort algorithm could significantly improve user engagement on Lemmy by making it easier to find and participate in lively discussions. It addresses the current gap in sorting options by providing a real-time snapshot of community engagement, encouraging more dynamic and timely interactions among users. This feature could also attract new users looking for a platform that offers an immediate sense of community and ongoing dialogue.

**Comment by dessalines** [comment]
This kind of rolling activity would be incredibly complicated to add, and I doubt it would be much better than the active sort.

If you're going to work on this, I'll leave it open, but otherwise I'll likely close it as out of scope for us.

**Comment by 8ullyMaguire** [comment]
I would have preferred to see if people wanted this before you unilaterally decided it isn't worth it, but oh well, I'll just close it.
