### ISSUE TITLE
[Bug]: "Deleted" image isn't actually deleted

### ISSUE THREAD

**Issue by KAMiKAZOW** [LemmyNet/lemmy#4500]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When drafting a post and uploading an image, then changing your mind and clicking "Delete" doesn't actually delete the image.

### Steps to Reproduce

1. Create a post
2. Upload an image
3. Copy the address of that uploaded image
4. Click the red Delete button
5. Paste the image address in a new browser tab

### Technical Details

-

### Version

0.19.3

### Lemmy Instance URL

lemmy.world

**Comment by Nutomic** [comment]
The image is most likely stored in your browser cache. Have you tried force reload (Ctrl + F5), or opening the url in another browser?
