### ISSUE TITLE
[Bug]: couldnt_find_object resolving remote user

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#4511]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I am trying to call the following endpoint:

https://lemmy.world/api/v3/resolve_object?q=https://lemmy.world/u/RM_Transit@mstdn.social

but I get `{"error":"couldnt_find_object"}`.

However if you go directly to the profile, you can see the account. https://lemmy.world/u/RM_Transit@mstdn.social

### Steps to Reproduce

1. Open https://lemmy.world/api/v3/resolve_object?q=https://lemmy.world/u/RM_Transit@mstdn.social
2. Observe error

Expected: Should resolve user

### Technical Details

I am not an admin

### Version

0.19.3

### Lemmy Instance URL

lemmy.world

**Comment by Nutomic** [comment]
You need to fetch from the users home instance, ie `https://lemmy.world/api/v3/resolve_object?q=https://mstdn.social/@RM_Transit`

**Comment by aeharding** [comment]
Alright, thanks!
