### ISSUE TITLE
URL Blocklist

### ISSUE THREAD

**Issue by flamingo-cant-draw** [LemmyNet/lemmy#4514]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

There are occasions where Lemmy communities or instances are spammed by bots/people posting the same link over and over again, like around two weeks ago where some Japanese teen was able to spam Lemmy and the wider Fediverse.

### Describe the solution you'd like.

Admins should be able to set a blocklist of URLs that Lemmy will check post/comments against and deny creation when there's a match. 

### Describe alternatives you've considered.

Admins can deploy an [automod](https://github.com/RikudouSage/LemmyAutomod) of some kind to do this. This is what we currently have on feddit.uk, but I think this is something that should be built into Lemmy itself.

**Comment by flamingo-cant-draw** [comment]
This is something I'd like to work on, but I just wanted to get the design OKed

My idea was to:
- Create a new table in the db that contains all the URLs called `url_blocklist` or something,
- Modify `process_markdown` function in `api_common` to check the body elements of posts and comments,
- Check the URL field of posts when they're created or updated.

The only thing I'm not sure about is what the API endpoints for retrieving and modifying the blocklist should be.

**Comment by Nutomic** [comment]
Yes this sounds good to me. A good place for it in the api would be as part of the existing [local_site endpoints](https://github.com/LemmyNet/lemmy/tree/main/crates/api_crud/src/site). In the database it could be called like `local_site_url_blocklist` accordingly.

Checking the full link is going to be easier for the initial implementation, but it would be more flexible to use a regex, or simply a list of blocked domains. But that can be changed after you figure out the initial db and api changes.
