### ISSUE TITLE
Add ability to remove chosen communities from frontpage feed.

### ISSUE THREAD

**Issue by mazury** [LemmyNet/lemmy#4528]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Currently frontpage shows all new posts from all communities. As an instance admin I would like to control this. The frontpage is visible to everybody, there is no need to sign in. Imagine a case where there is one very active community, which obviously discusses one certain topic. So we observe an unproportional number of posts from that community on frontpage feed. I would like to avoid it. 

I guess I would like the frontpage to be more representative of what could be happening instead of what's actually hapenning in the instance. To show possibilities (variety of communities) that the instance provides rather than what people are actually talking about (one or few communities with plenty of content). I think this is more attractive for potential user. Seeing diverse content. And it attracts diverse users. In turne instance doesn't become homogenous. Now this is of course arguable. Which approach is better or worse. Maybe sometimes one is better over the other? Adding this admin option would at least give us the flexibility.

### Describe the solution you'd like.

I think the list could be in admin panel somewhere. Don't know how lemmyUI does it but in Photon there is tag adding view. Could be similar. Community search bar, same as in create post view -> we choose a community and click add+ button.  

backend implementation suggestions, quick thoughts: 
- new column in community table called frontpage_hidden? 
- new endpoints to add and remove community from this "blocklist"?
- adjusting frontpage posts db query properly  

### Describe alternatives you've considered.

Haven't 

### Additional context

I only thought if similarly to federation we could have whitelist apart from blacklist. But I don't think it's necessary. Don't see why would anybody want to only show posts from few chosen communities. Unless the instance grows so much that it would be easier to create whitelist with like 20  communities that as admins we want to show to the world rather than create blacklist with 100 communities that we think think create "noise". Anyway, I think it could be implemented later. Not sure how that possibility affects design decisions now

**Comment by dullbananas** [comment]
Admins should be able to select community groups (#818) that are shown as options in addition to All and Local, and make one of them the default

**Comment by Nutomic** [comment]
There is `/api/v3/community/hide`, not sure if thats what youre looking for.

https://github.com/LemmyNet/lemmy/pull/2055

**Comment by mazury** [comment]
I've heard that this endpoint also removes community from communities list. I don't want that, I was just thinking of removing the posts visible on the frontpage.

**Comment by dessalines** [comment]
Yes, hide already serves this purpose.

> I've heard that this endpoint also removes community from communities list.

I think that's correct. I don't see why we need to support a super-specific functionality of *hide it from the front page, but not from the community list* . Hide means hide.

**Comment by dullbananas** [comment]
@gapetto would any of these options solve your problem?

* ability to make the community list be the front page
* broad categories of communities that can be selected on the front page

**Comment by gapetto** [comment]
Hmm... I think so, yes. Grouping seems fine. Might be even better cause the instance could have too many communities to hide, so it's better to select let's say 30-40 featured ones for the frontpage. Sure.

So the group would essentially be like category. Or we could even call it tag right? Yeah, that solves the problem I think. So esentially frontpage would become like a multireddit. Though I never used that specific feature on reddit I can see the use case here. And I see that some people might need the multireddit feature as well. Twitter has that also with their lists which is very useful.
