### ISSUE TITLE
[Bug]: Unecessarily duplicated `comment_reply` and `person_mention` rows.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4532]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Most / all of the microblogging apps use a form of reply, that includes your username mention. In lemmy, these are separate concepts, since a direct reply to a comment doesn't actually need the replied user's name, and we keep a separate `person_mention` table specifically for these.

This means that in many lemmy front ends, you'll see both a comment reply, and a comment mention, for the same comment, and both must be individually marked as read.

The best way to fix this, would be to remove *one* of the inserts, either to `comment_reply`, or `person_mention`, when its a direct reply that also includes a mention.

### Steps to Reproduce

1. Reply to a comment with the `@user` mentioned
2. Replied user sees a duplicated response in their inbox.

### Technical Details

Context: https://github.com/dessalines/jerboa/issues/1438

### Version

main

### Lemmy Instance URL

all

**Comment by tracyspacy** [comment]
I had a look, and it seems, the simplest solution following the code's logic is to remove `comment_reply` insert if there is already a `person_mention`.
It could be fixed by adding additional check to send_local_notifs function in [build_response.rs](https://github.com/LemmyNet/lemmy/blob/main/crates/api_common/src/build_response.rs)

```
          if !recipient_ids.contains(&parent_user_view.local_user.id) {}
 ```
 If it is ok, I can submit a pull request.

**Comment by dullbananas** [comment]
@tracyspacy go ahead
