### ISSUE TITLE
Write test script for HTTP API

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#454]
For performance testing, we can use `ab` to write a basic load test for each API call, and see which ones are slow.

For correctness testing, we could write a script that calls each method and verifies the returned data.

**Comment by MitchLillie** [comment]
Is this covered by `apache_bench_report.sh`?

**Comment by Nutomic** [comment]
@MitchLillie Mostly by [https://github.com/dessalines/lemmy/blob/master/server/query_testing/api_benchmark.sh](api_benchmark.sh), but its far from complete (doesnt include any POST/PUT/DEL requests).

**Comment by MitchLillie** [comment]
Gotcha, thanks. I will take a stab at this today

**Comment by MitchLillie** [comment]
Is there anything I'm missing? Simply trying to `curl` as below, and getting 400 responses:

```
curl -i -H "Content-Type: application/json" -d '{
  "op": "Login",
  "data": {
    "username_or_email": "mitch",
    "password": "mitch"
  }
}' http://localhost:8536/api/v1/user/login
```

**Comment by Nutomic** [comment]
I think you need to add `-X POST`.

**Comment by MitchLillie** [comment]
Same result, 400. I think `-X POST` is redundant when you pass `-d`

**Comment by dessalines** [comment]
I just tested this and its working fine on my machine: 

```

**Comment by MitchLillie** [comment]
Awesome, thanks. I knew it was something silly

**Comment by MitchLillie** [comment]
I need to step away from this, sorry. Lots of complication here in holding on to the jwt. I may have more time to investigate next week

**Comment by Nutomic** [comment]
@MitchLillie no need to rush :)

**Comment by dessalines** [comment]
The federation tests have this now.
