### ISSUE TITLE
[Bug]: Deleting A user does not delete content

### ISSUE THREAD

**Issue by BentiGorlich** [LemmyNet/lemmy#4544]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When Lemmy receives a delete activity for a user the content still stays up. I would expect Lemmy to delete all data tied to a user when handling a delete activity. That is not happening, only going to the author of a post throws an error.

### Steps to Reproduce

1. Create a user on a remote instance
2. Create a post in a magazine of the Lemmy instance
3. Send a delete activity to the Lemmy instance that looks like this:
```json
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "id": "https://mtest.tld/f/object/0021af88-d3ef-47af-8db5-0e7b6660c412",
    "type": "Delete",
    "actor": "https://test.tld/u/3_delete1",
    "object": "https://test.tld/u/3_delete1",
    "to": [
        "https://www.w3.org/ns/activitystreams#Public"
    ]
}
```
4. The post is still up. When going to the author of the post (name is still the same) you'll see the error page

### Technical Details

OS: Fedora 39

This error shows up when trying to visit the deleted users profile
```log
lemmy-1     | 2024-03-15T20:46:59.106107Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: Unknown: Record not found
lemmy-1     |    0: lemmy_apub::api::read_person::read_person
lemmy-1     |            with data=Query(GetPersonDetails { person_id: None, username: Some("3_delete1@test.tld"), sort: Some(New), page: Some(1), limit: Some(20), community_id: None, saved_only: None }) local_user_view=Some(LocalUserView { local_user: LocalUser { id: LocalUserId(1), person_id: PersonId(2), password_encrypted: "---REDACTED---", email: None, show_nsfw: true, theme: "browser", default_sort_type: Active, default_listing_type: Local, interface_language: "browser", show_avatars: true, send_notifications_to_email: false, show_scores: true, show_bot_accounts: true, show_read_posts: true, email_verified: false, accepted_application: false, totp_2fa_secret: None, open_links_in_new_tab: false, blur_nsfw: true, auto_expand: false, infinite_scroll_enabled: false, admin: true, post_listing_mode: List, totp_2fa_enabled: false, enable_keyboard_navigation: false, enable_animated_images: true, collapse_bot_comments: false }, person: Person { id: PersonId(2), name: "Test3Admin", display_name: None, avatar: None, banned: false, published: 2024-03-15T19:32:37.838862Z, updated: None, actor_id: DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lemmy.test")), port: None, path: "/u/Test3Admin", query: None, fragment: None }), bio: None, local: true, private_key: Some("---REDACED---"), public_key: "---REDACTED---", last_refreshed_at: 2024-03-15T19:32:37.838862Z, banner: None, deleted: false, inbox_url: DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lemmy.test")), port: None, path: "/u/Test3Admin/inbox", query: None, fragment: None }), shared_inbox_url: Some(DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lemmy.test")), port: None, path: "/inbox", query: None, fragment: None })), matrix_user_id: None, bot_account: false, ban_expires: None, instance_id: InstanceId(1) }, counts: PersonAggregates { person_id: PersonId(2), post_count: 2, post_score: 1, comment_count: 3, comment_score: 4 } })

```

### Version

0.19.3

### Lemmy Instance URL

test instance

**Comment by Nutomic** [comment]
A normal delete activity only deletes the user profile. To delete the content, set the field [removeData: true](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/protocol/activities/deletion/delete.rs#L45).

**Comment by Nutomic** [comment]
Made a PR for that. And yes the checkbox is currently missing, it will be in the next release (https://github.com/LemmyNet/lemmy-ui/pull/2385).

**Comment by BentiGorlich** [comment]
Just to be sure: is the `remove_data` attribute already supposed to do something?
We now send this activity
```json
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "id": "https://test.tld/f/object/c8765c9a-5c78-42a2-a4e0-f34a6c69f2e6",
    "type": "Delete",
    "actor": "https://test.tld/u/1_delete11",
    "object": "https://test.tld/u/1_delete11",
    "to": [
        "https://www.w3.org/ns/activitystreams#Public"
    ],
    "cc": [
        "https://mtest.tld/u/1_delete11/followers"
    ],
    "remove_data": true
}
```
But the behaviour on the lemmy side did not change :thinking:

**Comment by Nutomic** [comment]
Yes it has been implemented for a long time. But it needs to be in camelCase (so `removeData`). Its a bit confusing because Rust converts it to snake_case.

**Comment by BentiGorlich** [comment]
Ah ok, got it :+1:

**Comment by BentiGorlich** [comment]
Worked as expected, so you can close this issue whenever you want :)
