### ISSUE TITLE
Allow users to choose where reports are sent to

### ISSUE THREAD

**Issue by DraconicNEO** [LemmyNet/lemmy#4546]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

On Lemmy there is no way to control which entities you send reports for posts or comments to, you don't get a choice to send or exclude options, such as the community's moderation team, or other instances. This can cause problems because for communities created in bad faith the mods can intercept and resolve reports and even harass the person who did it. Similar story for malicious instances.

### Describe the solution you'd like.

I think a good solution would be to create a form that allows you to select who to send the report to, this is already a feature on the platform Mastodon, when making a report there are options to choose whether or not to send a copy of the report to other instances. 

Here's an example:
![image](https://github.com/LemmyNet/lemmy/assets/44508470/a2d30460-d1b8-4ce3-b855-e0705c1718a1)

The big difference is that in Mastodon they don't have communities or any form of official groups, so the only moderators are instance wide moderators.
In my proposal we also include an option to exclude community moderators in addition to the admins of remote instances.

I made a mockup to show how this would look in Lemmy to give an idea of what I mean:
![image](https://github.com/LemmyNet/lemmy/assets/44508470/5126e9c2-6b59-4f8e-9d09-ec37e51959ce)

### Describe alternatives you've considered.

Could have a separate report function for admins only but that seems very clunky and limiting, and also lead to reports being sent to admins that would be fine for community mods.

**Comment by DraconicNEO** [comment]
> Duplicate of #2414

Doesn't solve issue of report harassment issues, there needs to be

> Duplicate of #2414

I think these are different solutions and that this one is quite different from that one, where that one only gives options to report to moderators (bad idea in the case of bad faith moderators) this gives the option to do what that one does or the inverse of it, which is what would be ideal in the case of bad faith communities and moderators of them.

**Comment by dullbananas** [comment]
Closing again since discussing this option in https://github.com/LemmyNet/lemmy/issues/2414 is enough
