### ISSUE TITLE
search bar to search through saved posts

### ISSUE THREAD

**Issue by RustoMCSpit** [LemmyNet/lemmy#4547]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

not being able to search through my saved posts

### Describe the solution you'd like.

a search bar in the saved tab

### Describe alternatives you've considered.

.

**Comment by Xyphyn** [comment]
I save a lot of posts and half of them have been completely lost. It'd be nice to add a `saved_only` option to the /search route.

**Comment by dessalines** [comment]
> I save a lot of posts and half of them have been completely lost. It'd be nice to add a saved_only option to the /search route.

That would be doable, especially since we already have that for building the post and comment queries.

**Comment by Nutomic** [comment]
These search parameters were added in https://github.com/LemmyNet/lemmy/pull/5034, but were removed again as part of search optimizations (https://github.com/LemmyNet/lemmy/pull/6397).

Related to https://github.com/LemmyNet/lemmy/issues/6434

**Comment by dessalines** [comment]
Saved only is moved to its own combined endpoint called `list_person_saved`, which returns both comments and posts you've saved in one view.

I'm a bit wary to add searching to that tho, as it would require filtering on column(s) in another table which is very slow... although the result sets are small enough that we probably could add it.

In the front end, this wouldn't be on the search page, but on your `saved` tab, we'd add a search field.
