### ISSUE TITLE
`creator_banned_from_community` field for `VoteView`

### ISSUE THREAD

**Issue by Sjmarf** [LemmyNet/lemmy#4561]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

As of #4392, moderators can use the "View Votes" button in addition to admins. It's possible that clients could allow moderators to ban a user from this menu. Currently, it is difficult to display whether one of the users is already banned from the community, which makes this feature difficult to implement for client developers. 

### Describe the solution you'd like.

One solution to this would be to add a `creator_banned_from_community` field to `VoteView`.

### Describe alternatives you've considered.

There aren't really any viable workarounds that I can see.

**Comment by DraconicNEO** [comment]
I think this is very important because not being able to ban users from vote view kind of defeats the purpose of having vote view as a mod in the first place. I mean there are weird funky API workarounds to arbitrarily ban people from communities but most mods aren't going to do that.
