### ISSUE TITLE
[Bug]: Users banned from a community still get posts and comments from that community in their home feed

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#4570]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I'm not entirely sure if this is a bug or working as intended, but users who are blocked from a community can still see posts and comments from that community on their home feed. The API still allows users to block communities they are banned from, so there a a non-zero change this behavior is intentional.

### Steps to Reproduce

1. Create a user to ban from a community
2. Ban them from the community
3. Log into banned user's account
4. Notice that you can still see posts from the community on your feed.

### Technical Details

n/a

### Version

BE 0.19.3

**Comment by Nutomic** [comment]
A community ban also unsubscribes the user from the community, see [here](https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/community/ban.rs#L60) and [here](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/activities/block/block_user.rs#L191). So there should be no community posts in the subscribed feed. Are you testing locally or over federation?

**Comment by SleeplessOne1917** [comment]
Locally

**Comment by Nutomic** [comment]
Tested this just now, user is getting unsubscribed from the community after ban. Are you maybe doing a site ban?

**Comment by SleeplessOne1917** [comment]
I was using a community ban. Even if the user is unsubscribed, they can still see posts in their  local feed (if the comm is on the same instance) and all feed.

**Comment by Nutomic** [comment]
Ah youre not talking about subscribed feed. I dont think there is anything implemented to hide posts from communities that banned you, so this would be a new feature request.

**Comment by SleeplessOne1917** [comment]
Is this a feature you think lemmy should have?

**Comment by dessalines** [comment]
I'm of the opinion, just like with blocks, that other users shouldn't get to have control over what you *see*. Blocks and bans should prevent 1-way interaction, but not 2-way.
