### ISSUE TITLE
[Bug]: Removed comments should not be returned in search results

### ISSUE THREAD

**Issue by Nothing4You** [LemmyNet/lemmy#4576]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Removed content should be omitted from searches, at least for non-admin/mod users.
For admins/mods, this would certainly improve usability of the site if there is no toggle, similar to how posts no longer show up in communities after they've been removed.
I haven't tested this for posts, but at least comments are returned despite being removed, even without being logged in.

### Steps to Reproduce

1. Visit https://lemmy.ml/search?q=sneed&type=Comments&listingType=All&page=1&sort=New
2. See a bunch of comments saying `Removed by mod`

### Technical Details

N/A

### Version

0.19.3

### Lemmy Instance URL

lemmy.ml

**Comment by tracyspacy** [comment]
If we want just to not show removed comments in search results leaving the rest incl CommentView as it is now, this could be achieved by adding a filter in list fn within CommentQuery impl [here](https://github.com/LemmyNet/lemmy/blob/main/crates/db_views/src/comment_view.rs)

**Comment by Nothing4You** [comment]
I just tested on voyager.lemmy.ml with 0.19.4-beta.5 and deleted comments are not showing up in search results anymore.

Deleted posts however are showing up in search results still, as #4634 only implemented this for comments.
