### ISSUE TITLE
What's crates/utils/src/version.rs ?

### ISSUE THREAD

**Issue by paolobarbolini** [LemmyNet/lemmy#4583]
### Question

As part of https://github.com/M4SS-Code/cargo-goggles/issues/11 I've stumbled on `lemmy_utils` -> `src/version.rs` and I was just wandering what that file is for. Could `env!("CARGO_PKG_VERSION")` substitute it?

https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

**Comment by Nutomic** [comment]
Yes youre right, thanks for the suggestion!
