### ISSUE TITLE
Add `.optional()` to database fetches that shouldn't throw an error for zero-result single-row-fetches.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4601]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

When doing a single-row DB fetch, [diesel will throw an error](https://docs.rs/diesel/latest/diesel/query_dsl/trait.RunQueryDsl.html#method.get_result) if there is no row returned. 

This affects `.get_result`, `.first`, and maybe other aliases I'm unaware of.

In the code, we have various wrappers / methods to prevent errors from zero result single-fetches, but we should just be using `.optional()` instead.

As far as I'm aware, [list fetches do not throw an error if there are zero results returned](https://docs.rs/diesel/latest/diesel/prelude/trait.RunQueryDsl.html#method.load).

### Describe the solution you'd like.

Use `.optional()` for single-fetches that shouldn't return an error.

Grep for the expressions above, add `.optional()`, and trace down and remove any error-catching hacks.

### Describe alternatives you've considered.

NA

### Additional context

https://github.com/LemmyNet/lemmy/pull/4580#discussion_r1553955221

**Comment by Nutomic** [comment]
Can you link these wrappers in our code which should be removed?

**Comment by dessalines** [comment]
I made a huge PR to make all these return options, and found and fixed a lot of uncaught cases in the process.
