### ISSUE TITLE
[Bug]: Scaled sort only shows posts created in last hour

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#4608]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Effectively it works as another "new" sort, instead of fulfilling the stated goal of showing popular posts from smaller communities. It seems the algorithm needs some adjustment.

See https://lemmy.ml/?dataType=Post&listingType=All&sort=Scaled

cc @dessalines @dullbananas 

### Version

0.19.3

**Comment by dessalines** [comment]
I think its working as intended, bc when I change the filter to Local, it did find many posts older than an hour. 

You're not going to see many older posts with Scaled + All, because there's so many small communities with new posts that its giving a boost to.

**Comment by Die4Ever** [comment]
I do think Scaled is pretty good for the Subscribed feed, I use that as my default. Although I do think it could favor new posts a little less, and maybe Hot could use the same tweak

Somewhat related issue https://github.com/LemmyNet/lemmy/issues/4471

**Comment by dullbananas** [comment]
There's a small chance that this happens because the batches for updating the ranks use `published` instead of `id`, and a newly inserted post is only guaranteed to be the most recently published post if it's local.

**Comment by dessalines** [comment]
I just checked this again, and if you filter by local, it does show some older posts. Can re-open if necessary.
