### ISSUE TITLE
Post to own profile

### ISSUE THREAD

**Issue by Jak2k** [LemmyNet/lemmy#4620]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

I would like to post to my profile, like I could post to u/<name> on reddit.

### Describe the solution you'd like.

Letting me post to my profile.

### Describe alternatives you've considered.

Linking a mastodon account. That has the con of multiple different accounts and shouldn't be necessary in the fediverse.

**Comment by Nutomic** [comment]
You can create a community `/c/jak2k` for this. I believe KBin also has this functionality. Implementing it in Lemmy would be too much work for very little benefit.

**Comment by Jak2k** [comment]
Maybe add an option to follow the submissions of a user instead? This would really be a game-changer for me.

**Comment by Nutomic** [comment]
You can do that from Mastodon and other platforms.

**Comment by Jak2k** [comment]
Then I need a second platform...

**Comment by dessalines** [comment]
Lemmy doesn't have user following, its only focused on following topic-specific communities.
