### ISSUE TITLE
Introduce a commie: pseudo-URI for webfinger.

### ISSUE THREAD

**Issue by SoniEx2** [LemmyNet/lemmy#4626]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Lemmy currently treats communities as accounts (under the acct: pseudo-URI), this is a deviation from the intent of the standard and a misuse of the acct: pseudo-URI.

### Describe the solution you'd like.

This will require a few deprecation cycles, but allowing communities (but not actual accounts) to be queried under a commie: pseudo-URI - without changing anything else - would be a good start. Then, at some point in the future, switch to trying both formats when looking up a community. Finally, maybe in a decade or so, add an option for admins to disable legacy community support. Then, after another decade, remove the option and only use commie: pseudo-URIs.

### Describe alternatives you've considered.

The main other option is to do nothing. There probably aren't any other options beyond that.

**Comment by Nutomic** [comment]
It was implemented like this originally as `group:news@lemmy.ml`, but that was incompatible with Mastodon. Thats why we had to switch to the current implemenation. So its not possible to change this unless Mastodon and other platforms add support for the new format first (which seems very unlikely).

**Comment by Nutomic** [comment]
In that case Mastodon cant fetch the user, its a bug on their side.

https://github.com/mastodon/mastodon/issues/17008
