### ISSUE TITLE
[Bug]: Posts and comments are not federating consistently on 0.19.3

### ISSUE THREAD

**Issue by andrewgioia** [LemmyNet/lemmy#4630]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

We're experiencing a problem similar to some previous federation issues here (#3101 and #3525 most specifically) where various posts and comments are not consistently federating out to other instances.

I have a slew of examples here but restarting the docker container(s) and even manually syncing posts through search are not working at all. A recent one is below in steps to reproduce.

Using phiresky's instance checker it's also showing some strange sync dates and lagging instances: https://phiresky.github.io/lemmy-federation-state/site?domain=mtgzone.com

Is there anything we can do to try to debug this? Is there a way to force resync?

### Steps to Reproduce

Missing posts:

1. Go to mtgzone.com/d/digital and note the post ["Worst Midweek Magic Ever"](https://mtgzone.com/post/577254) has 2 comments.
2. View this community on sopuli.xyz at https://sopuli.xyz/c/digital@mtgzone.com. The post does not appear at all.
3. The missing posts are even more pronounced on my own personal instance

Missing comments:

1. Go to https://mtgzone.com/post/572967 and note 15 comments
2. This same post on [lemmy.world](https://lemmy.world/post/14092789) has 14 comments.

### Technical Details

Running lemmy v0.19.3 on Ubuntu via docker.

### Version

BE 0.19.3

### Lemmy Instance URL

mtgzone.com

**Comment by Nutomic** [comment]
I suggest you join the [admin chat on matrix](https://matrix.to/#/#lemmy-support-general:discuss.online), where people are looking into these problems.

**Comment by yo-scottie-oh** [comment]
Adding another example of a missing post for testing purposes:

- Go to https://lemmy.world/c/caps and note the post [Thanks for the chats guys, hope to resume them soon](https://lemmy.world/post/14870120), which has one comment.
- View this community on lemm.ee at https://lemm.ee/c/caps@lemmy.world. The post shows up there, too.
- View this community on lemmy.ml at https://lemmy.ml/c/caps@lemmy.world. The post does not show up.
