### ISSUE TITLE
Question: why data type of comment_id/post_id in lemmy is i32 but not u32 or u64?

### ISSUE THREAD

**Issue by leonwang908** [LemmyNet/lemmy#4632]
### Question

what will happen if No. 2,147,483,648 comes?
just wondering.

**Comment by Nutomic** [comment]
It matches the [integer type in postgres](https://www.postgresql.org/docs/current/datatype-numeric.html). It looks like there are no unsigned integers available. If we get near the limit we have to migrate to bigint.

**Comment by dessalines** [comment]
Its also what diesel uses: https://kotiri.com/2018/01/31/postgresql-diesel-rust-types.html
