### ISSUE TITLE
Remove `local_user.auto_expand` images in favor of `local_user.post_listing_mode`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4643]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Auto-expanding images isn't a setting that would work well with every type of post_listing_mode, which are currently : `Card`, `SmallCard`, and `List` .

Also, auto-expand images doesn't exist at the local_site level, only the local_user level, whereas post_listing_mode exists at both levels, so is more versatile. A site can set a default post_listing_mode, and that can also be overridden by a local user setting.

### Describe the solution you'd like.

Get rid of the `local_user.auto_expand` setting.

### Describe alternatives you've considered.

NA

### Additional context

cc @SleeplessOne1917 @MV-GH @matc-pub

**Comment by MV-GH** [comment]
Didn't know that existed, don't think we use it in Jerboa

**Comment by dessalines** [comment]
Ya it was recently added, we'll need to add it at some point.
