### ISSUE TITLE
[Bug]: Auto Increment for person_id fails when a user tries to register with an existing username

### ISSUE THREAD

**Issue by leonwang908** [LemmyNet/lemmy#4657]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Let say current max(person_id) is 10. and there is a user registered name like 'hoge'.
then a new user try to register 'hoge' 10 times. finally he register his username as 'hoge2', his person_id will be 21

### Steps to Reproduce

1. find a username already existing
2. check last registered user's person_id
3. register same username from step 1.
4. successfully register a user with other username
5. check user's person_id from step 4

### Technical Details

The OS is Ubuntu 22.04.2 LTS

### Version

BE 0.19.3

**Comment by dessalines** [comment]
[Not possible with postgres](https://stackoverflow.com/questions/2036571/is-there-a-way-to-avoid-calling-nextval-if-the-insert-fails-in-postgresql), also the number is meaningless and isn't going to affect anything.
