### ISSUE TITLE
[Bug]: Importing user settings doesnt import all blocks

### ISSUE THREAD

**Issue by slrgt** [LemmyNet/lemmy#4669]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I'm migrating instance and I have a large block list of all the meme communities but importing my settings to my new account only imports some of the blocks. I have to continue to manually import the same settings over and over to import more of the blocked communities

### Steps to Reproduce

1. export settings
2. import settings
3. check blocked settings

### Technical Details

firefox

### Version

.19.3

**Comment by dessalines** [comment]
Could you test this on https://voyager.lemmy.ml , which is running our beta?

Looking at the code we currently have a 10k limit, but its possible due to all the fetches this requires, that it doesn't skip failed ones cleanly.

**Comment by slrgt** [comment]
Ok, i requested an account

**Comment by dessalines** [comment]
Approved.

**Comment by slrgt** [comment]
It didnt import the blocks

**Comment by Nutomic** [comment]
Can you share your exported settings file? You can remove things like followed communities or other sections for privacy.

**Comment by slrgt** [comment]
Sure, here: [lemmy_user_settings_20240426T042048.484Z.json](https://github.com/LemmyNet/lemmy/files/15170119/lemmy_user_settings_20240426T042048.484Z.json)
