### ISSUE TITLE
[Bug]: Woodpecker crates.io publish failing on tag.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4678]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Crates.io publish is failing.

Has to do with `lemmy_db_perf` not being an existing repo:

```
Caused by:
the remote server responded with an error (status 403 Forbidden): this token does not have the required permissions to perform this action
error: unable to publish package lemmy_db_perf
```

Full error is here: https://woodpecker.join-lemmy.org/repos/129/pipeline/6724/6

### Steps to Reproduce

1. Create a tag
2. Publish step fails.

### Technical Details

NA

### Version

main

### Lemmy Instance URL

all

**Comment by Nutomic** [comment]
That package shouldnt be necessary, we can mark it as [publish = false](https://github.com/LemmyNet/lemmy/blob/main/crates/api_crud/Cargo.toml#L3)

**Comment by dessalines** [comment]
mmk, I'll do that now.
