### ISSUE TITLE
Do you agree to follow the rules in our Code of Conduct?

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4697]

**Comment by dessalines** [comment]
Weird, I didn't open this.

**Comment by dullbananas** [comment]
I think this is what you did:

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#converting-tasks-into-issues

**Comment by dessalines** [comment]
Ah... kind of a neat feature, didn't know about that.
