### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nleskiw** [LemmyNet/lemmy#4710]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Unable to subscribe to community on federated Lemmy server from self-hosted instance.

              
This also occurs when searching for "!tenforward@lemmy.world" in my self-hosted instance' search bar. 

### Steps to Reproduce

1. Start a self-hosted Lemmy instance, log out of lemmy.world.
2. Navigate to [https://lemmy.world/c/tenforward](https://lemmy.world/c/tenforward)
3. Click "Subscribe"
4. Enter hostname of your instance

What Happens: 
* You are redirected to your instance, UI says "Could not fetch !tenforward@lemmy.world" and error appears in log

Expected Behavior: 
* You are subscribed to the remote Community

### Technical Details

Relevant log lines: 
```2024-05-08T02:32:13.942893Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: CouldntFindObject: Failed to resolve actor via webfinger
 
 Caused by:
     The webfinger object did not contain any link to an activitypub item
    0: lemmy_apub::fetcher::search::search_query_to_object_id
              at crates/apub/src/fetcher/search.rs:19
    1: lemmy_apub::api::resolve_object::resolve_object
            with data=Query(ResolveObject { q: "!tenforward@lemmy.world" }) local_user_view=Some(REDACTED)
              at crates/apub/src/api/resolve_object.rs:19
    2: lemmy_server::root_span_builder::HTTP request
            with http.method=GET http.scheme="https" http.host=REDACTED http.target=/api/v3/resolve_object otel.kind="server" request_id=04b362f0-91fc-401c-bcbe-6a8317e0a768 http.status_code=400 otel.status_code="OK"
              at src/root_span_builder.rs:16```
              
 OS: Ubuntu Jammy 
 uname: `5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
 Browser console errors: None - Firefox 125.0.2 (64-bit) / Windows

### Version

BE: 0.19.3

### Lemmy Instance URL

lemmy.cringecollective.io

**Comment by Nutomic** [comment]
Please use https://matrix.to/#/#lemmy-support-general:discuss.online or https://lemmy.ml/c/lemmy_support for this.
