### ISSUE TITLE
Add accept/decline step to appointing a user as a moderator or admin

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#4715]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Currently, people can be appointed as mods or admins without their consent. This could cause issues if a community or instance gets in some kind of trouble and mods/admins try to shift and dilute blame.

### Describe the solution you'd like.

Add a step to mod an admin appointments that allow users to accept or decline an appointment. 

### Describe alternatives you've considered.

n/a

**Comment by dullbananas** [comment]
Duplucate of #785
