### ISSUE TITLE
[Bug]: data did not match any variant of untagged enum FfMpegStream at line 25 column 8

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#4728]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

You cannot upload videos captured on phones because they fail.

### Steps to Reproduce

1. Try to upload this file: https://github.com/LemmyNet/lemmy/assets/2166114/6123c0d3-f7bc-4933-b3df-93721e9be3df
2. See "data did not match any variant of untagged enum FfMpegStream at line 25 column 8" in response

### Technical Details

None

### Version

0.19.3

### Lemmy Instance URL

lemmy.world

**Comment by aeharding** [comment]
Actually, I am having the same problem trying to upload from Android Pixel with video captured on device. So somehow related. Tested against multiple instances.

**Comment by asonix** [comment]
fixed in pict-rs 0.5.14

**Comment by aeharding** [comment]
Oh thanks! Unfortunately image upload is broken on voyager.lemmy.ml so I couldn’t test upcoming Lemmy software
