### ISSUE TITLE
[Bug]: Unsticking of post not federated

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy#4743]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I saw that the community i moderate is available on blahaj.zone, and it has pulled some old comments, but new ones did not federate. There is also an old stickied post still stickied.

[https://lemmy.blahaj.zone](https://lemmy.blahaj.zone/c/bicycle_touring@lemmy.world)[/c/bicycle_touring@lemmy.world](https://programming.dev/c/bicycle_touring@lemmy.world)

I assume somone from that instance had the c subscribed at some point, but then unsubscribed, so new comments and actions did not federate. If now somebody on that instance would subscribe again - will the obsolete sticky post just stay there forever? Because i am not sending the mod activity again to unsticky it?

### Steps to Reproduce

1. attempt to unsticky a post
2. check other instances

### Technical Details

https://lemmy.world/post/15490712

### Version

0.19.3

### Lemmy Instance URL

lemmy.world, lemmy.blahaj.zone

**Comment by Nutomic** [comment]
This is fixed by https://github.com/LemmyNet/lemmy/pull/4475
