### ISSUE TITLE
Have all DB functions support either a postgres connection, or a postgres pool.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4745]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

When using diesel transactions, you need to use an individual postgres connection, rather than passing in an entire DB pool. This is a problem because some API actions, like comment creation, have many operations, and should be done in a transaction. 

Currently, nearly all our functions in `db_schema` use the pool, rather than individual connections. So for the above example, we'd have to create nearly identical functions just for the `PgConn` versions.

### Describe the solution you'd like.

Create a `PoolOrConnection` enum, and alter all the functions in `db_schema` to use it, instead of the pool.

Add a helper function to the enum, that if given a pool, extracts the connection, but if given a connection, just uses it.

### Describe alternatives you've considered.

NA

### Additional context

#4742

**Comment by dessalines** [comment]
Looks like this is already done, but that should be renamed:

https://github.com/LemmyNet/lemmy/blob/ec77c00ef80248e9eceec800082e34547f9aa084/crates/db_schema/src/utils.rs#L68

**Comment by phiresky** [comment]
this was done in #3420
