### ISSUE TITLE
[Bug]: saved_only queries are very slow

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4756]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

The saved only queries are extremely slow now, and timing out.

### Steps to Reproduce

1. Try to view the posts and comments you've saved.
2. The queries time out.

### Technical Details

Na

### Version

0.19.4-rc.2

### Lemmy Instance URL

lemmy.ml

**Comment by dullbananas** [comment]
Is it caused by #4479?

**Comment by dessalines** [comment]
Yep, I'll have a PR and a suggestion for you to look at in a sec.

**Comment by dessalines** [comment]
Fixed by the above commit.
