### ISSUE TITLE
Question: use Lemmy instead of join-lemmy.org/news

### ISSUE THREAD

**Issue by KaKi87** [LemmyNet/lemmy#4760]
### Question

Hi,

How about using Lemmy instead of join-lemmy.org/news, since [Lemmy can be used as a blog](https://join-lemmy.org/docs/users/06-other-features.html#lemmy-as-a-blog) ?

Thanks

**Comment by dessalines** [comment]
We used to do this, since lemmy.ml is our developer-run instance, but now we'd prefer to use join-lemmy.org for release news and such.

**Comment by KaKi87** [comment]
So, in the end, Lemmy is realistically *not* usable as a blog ? 😅

**Comment by KaKi87** [comment]
But how about a blog-only instance, as described in the linked documentation ?

**Comment by dessalines** [comment]
You can run one if you like? We're keeping our news on join-lemmy.org
