### ISSUE TITLE
Return a list of posts when creating a post

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#4776]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Currently, after creating a post, only the created post is shown. Showing a list of the community's newest posts instead, with the new post at the top, would lead to a higher and more consistent amount of people who see new posts.

### Describe the solution you'd like.

Add a variant of the post creation API that returns this list of posts.

### Describe alternatives you've considered.

An alternative is to add a `page_after_or_equal` option to the post list API. This would make two sequential requests necessary, which significantly affects speed, and the time between the two requests could increase cache misses in the database if a lot of other queries happen in that time.

**Comment by MV-GH** [comment]
Could this not be achieved in the frontend by just redirecting to community feed sorted by new?

**Comment by dessalines** [comment]
I don't know how this flow would work. After creating a post, you should only be viewing that one post anyway. And navigating back to your feed, should have things sorted based on your preferences.

**Comment by dullbananas** [comment]
> After creating a post, you should only be viewing that one post anyway.

That shouldn't be the only option.

**Comment by Nutomic** [comment]
I also fail to see the purpose of this. It seems you mainly want new posts to be shown to more users? But the amount of people who actually submit posts in a given timeframe is very small in comparison to people who browse passively. So I doubt that this would have any noticable effect.

**Comment by dullbananas** [comment]
> But the amount of people who actually submit posts in a given timeframe is very small in comparison to people who browse passively. So I doubt that this would have any noticable effect.

This logic might be false because of the snowball effect. If this change affects whether or not a post gets attention from other posters, then it affects the post's rank, which affects how much attention it gets from people who browse passively.

Also, this change can affect the user experience of people who post. I often manually look at a community's new posts after I make a post, and that shouldn't need to be manual. And it's a step towards people being able to completely replace the main feed with less addictive ways of seeing posts (what's special about this one is it allows the amount of posts viewed to easily adapt to how much time you have but without effortless instant gratification, and it shows new posts which need viewers).

**Comment by Nutomic** [comment]
Closing this as its not very useful nor intuitive.
