### ISSUE TITLE
[Bug]: Site logo disappearing

### ISSUE THREAD

**Issue by kroese** [LemmyNet/lemmy#4777]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I have run into a strange issue where the site logo is frequently disappearing. The image still exists in pict-rs, but the `icon` field in the `site` table gets blank.

It has happened well over 10 times by now, but Im still not exactly sure how to reproduce it. I only know that it happened every time I did a version update in 0.19.4 (rc3 to rc4, etc.). But it also happened a few times, while the version stayed the same. Maybe its related to the restart of the container, I dont know.

My guesses what could be happening:

- Maybe Lemmy overwrites my local instance config, with federated data from a remote instance. And that remote instance has no `icon` set for my site, therefore overriding my own configuration.
- Maybe Lemmy executes some database migrations under some conditions, and this migration clears the `icon` in my database.

### Steps to Reproduce

Not clear, it seems to be related to container restarts/version updates.

### Technical Details

... 

### Version

BE 0.19.4-rc.6

**Comment by dessalines** [comment]
Do you see this line in your docker logs when restarting?

`No Local Site found, creating it.`

**Comment by dessalines** [comment]
This makes sense: it has to do with a long-standing bug in our updates for text like fields in forms. 

We need to differentiate between 3 actions: do nothing, update the field, or delete the optional field from the DB. For things like bio, preferred username, etc we use an empty string to tell the database to do a DB delete, but if I recall correctly, that *might* not work for the optional URL-like fields, which include icons, banners, etc. I'll take a crack at it now tho.

**Comment by dessalines** [comment]
Yeah it was probably that one. I've added a PR that cleans up a lot of this code, and is more explicit about these URL DB clears.
