### ISSUE TITLE
Dont use `unimplemented!()` macro as it causes federation breakages.

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#4782]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

https://github.com/LemmyNet/lemmy/blob/0.19.3/crates/apub/src/activities/block/mod.rs#L79

This code gets called by the federation library [here](https://github.com/LemmyNet/activitypub-federation-rust/blob/main/src/fetch/object_id.rs#L161) when receiving a ban action in a removed community. Need to replace it with something like the following:

```
    match apub {
      InstanceOrGroup::Instance(i) => Site::delete(...).await,
      InstanceOrGroup::Group(g) => Instance::delete(...).await,
    }
```

We should [deny the macro via clippy](https://rust-lang.github.io/rust-clippy/stable/index.html#/unimplemented) to ensure it isnt used anywhere in the code. Same goes for [todo!()](https://rust-lang.github.io/rust-clippy/stable/index.html#/todo) macro.

Edit: Specifically `InstanceOrGroup` should use a macro, such as [enum_delegate](https://crates.io/crates/enum_delegate) which is already used elsewhere. Same for [PostOrComment](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/fetcher/post_or_comment.rs) and the other ones next to it.

**Comment by dessalines** [comment]
@Nutomic this is one of the few things we have left for `0.19.6`

**Comment by dessalines** [comment]
Changing this back to `0.19.6`, because its causing lots of problems. Even just adding logging lines in there as placeholders is better than the unimplemented panics.

**Comment by dessalines** [comment]
Mostly done by the above PR.
