### ISSUE TITLE
When searching for communities, the search query should also search through communitiy sidebards, rather than soley the communtity name

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy#4785]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Currently, when searching for communities, the search query only looks at the names of communities. This can often result in relevant communities not being shown, as some communities don't have the exact topic in the community name.

What I propose is that the search query should also search through community sidebars. Sidebars often contain a summary/introduction for the type of content that the community contains.

**Comment by dessalines** [comment]
The current community search [only filters by its title and name.](https://github.com/LemmyNet/lemmy/blob/main/crates/db_views_actor/src/community_view.rs#L120) 

I wouldn't be opposed to adding the sidebar there, but it might need some discussion. Could be too wide a net and catch too many communities. There is no "relevance" sort here either, so sorting by community popularity or published time might get much worse.

**Comment by dullbananas** [comment]
This would work well if the search is done on a filtered variant of the sidebar content, probably generated with natural language processing. It would at least need to filter out the rule list and links to other communities.
