### ISSUE TITLE
Store demographic info in Person

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#4786]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

* Options for Reddit polls often have a male variant and a famale variant, or an American variant and a non-American variant, etc. When polls are added to Lemmy (#787), this correlation can be automatic if the data is stored in Person, which would make some polls less complicated.
* The age distribution of community subscribers can be very useful or interesting information.

### Describe the solution you'd like.

Add optional fields for year of birth, country, and sex

### Describe alternatives you've considered.

.

**Comment by dessalines** [comment]
I def like this idea, although a tagging #3951 system, where people can add any number of tags might be more flexible. 

At the same time, that might be too "loose", and we couldn't have predefined fields / lists for countries for example.

**Comment by Nutomic** [comment]
Due to federation all this data would be completely public. And Lemmy users are generally quite concerned about privacy, so most would probably not fill in the data. Which means its not really worth the effort.

**Comment by lullis** [comment]
Does this really need to go to Person? Seems like it's useful enough if it is related to LocalUser, no?

**Comment by dessalines** [comment]
One use-case might be to know the demographics of a community's subscribers, so it'd need to go on Person, for federated subscribers.

There's probably an activitypub attachment or field we could utilize for this. As long as all these fields are optional (and not required on signups), it shouldn't be a problem.

**Comment by Nutomic** [comment]
Lemmy is not Facebook, we dont want to store personal info. If people are interested in this they can directly ask for it in polls.
