### ISSUE TITLE
[Bug]: Lemmy post deletions (by user) do not federate to mastodon.

### ISSUE THREAD

**Issue by M4rtineski** [LemmyNet/lemmy#4792]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Story: I made 2 different posts on memes@lemmy.ml to test if the images on newer lemmy version get shown properly on mastodon instead of being just embedded from link. After deleting the posts on lemmy I noticed that the mastodon posts didn't disappear even after 1 hour. Link to the community on mastodon: https://c.im/@memes@lemmy.ml I couldn't share a direct link to the post because it decides to take you straight to lemmy source post instead.

### Steps to Reproduce

1. Make a post in a community that federates with your mastodon instance.
2. Wait for the post to federate.
3. Delete the post.
4. Post stays on mastodon.

### Technical Details

no details

### Version

0.19.4

### Lemmy Instance URL

lemmy.ml and c.im for mastodon

**Comment by Nutomic** [comment]
Cant reproduce this, deletions are federating just fine.
