### ISSUE TITLE
Remove Person from CommunityBlockView/PersonBlockView/InstanceBlockView

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#4793]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Person in Instance/Person/CommunityBlockView is not needed at all.

Person can already be found within the same response at `$.my_user.local_user_view.person`  It is unnecessary duplicated at `$.my_user.instance_blocks[*].person` and `$.my_user.community_blocks[*].person` and `$.my_user.community_blocks[*].person`

### Describe the solution you'd like.

Remove it

### Describe alternatives you've considered.

None

**Comment by dessalines** [comment]
Going into those structs, I wonder if any are really necessary now. Just returning the `Community`, `TargetPerson`, or `Instance` should be enough.

**Comment by MV-GH** [comment]
Yeah they aren't necessary in Jerboa I just map em to those.
