### ISSUE TITLE
[Bug]: Unable to connect to TLS Postgres Pool

### ISSUE THREAD

**Issue by Just-Insane** [LemmyNet/lemmy#4795]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

After updating from 0.19.3 to 0.19.4, the backend fails to connect successfully to a TLS-required postgres pool (using pgbouncer).

pgbouncer shows the client attempting to connect and immediately closing the connection after 0s:

```
2024-06-10 18:03:24.702 UTC [6] LOG C-0x558e29389c30: lemmy/lemmy@10.244.0.71:60720 login attempt: db=lemmy user=lemmy tls=TLSv1.3/TLS_AES_256_GCM_SHA384
2024-06-10 18:03:24.740 UTC [6] LOG C-0x558e29389c30: lemmy/lemmy@10.244.0.71:60720 closing because: client close request (age=0s)
```

The lemmy backend container reports:

```
Lemmy v0.19.4
2024-06-10T18:03:37.268466Z  INFO lemmy_db_schema::schema_setup: Running Database migrations (This may take a long time)...
2024-06-10T18:03:37.302547Z  INFO lemmy_db_schema::schema_setup: Database migrations complete.
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.9/src/crypto/mod.rs:259:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
stack backtrace:
   0:     0x55ebfd669be2 - <unknown>
   1:     0x55ebfc3d161c - <unknown>
   2:     0x55ebfd666cff - <unknown>
   3:     0x55ebfd6699b4 - <unknown>
   4:     0x55ebfd66b0ed - <unknown>
   5:     0x55ebfd66ae4c - <unknown>
   6:     0x55ebfd66b55e - <unknown>
   7:     0x55ebfd66b452 - <unknown>
   8:     0x55ebfd66a086 - <unknown>
   9:     0x55ebfd66b194 - <unknown>
  10:     0x55ebfc249d65 - <unknown>
  11:     0x55ebfc3ced81 - <unknown>
  12:     0x55ebfc249d2b - <unknown>
  13:     0x55ebfd5f2665 - <unknown>
  14:     0x55ebfd5df370 - <unknown>

```

I suspect this is related to this change: https://github.com/LemmyNet/lemmy/pull/4690

### Steps to Reproduce

1. Upgrade from 0.19.3 to 0.19.4 when using a postgres pool and pgbouncer
2. Observe that TLS connection appears to be failing

### Technical Details

Running lemmy on kubernetes using this helm chart: https://gitlab.com/ananace/charts/-/tree/master/charts/lemmy

Using this Postgres Operator: https://github.com/CrunchyData/postgres-operator which forces TLS by default

### Version

0.19.4

### Lemmy Instance URL

lemmy.cloudhub.social

**Comment by makotech222** [comment]
I had to make this change for mine to work:

![image](https://github.com/LemmyNet/lemmy/assets/4389156/ba51f271-0273-428a-b93f-40ee517f5d0c)

minus line 9, unrelated

**Comment by Just-Insane** [comment]
So, I guess there was an update to rusttls that didn't add a default tls provider. That'll probably need an update to the project I guess.

**Comment by dessalines** [comment]
@makotech222 could you do a PR for this one?

**Comment by makotech222** [comment]
sorry, i don't have lemmy working locally anymore so i can't really work on it.

**Comment by makotech222** [comment]
Might still be an issue on latest:

![image](https://github.com/LemmyNet/lemmy/assets/4389156/81f55ee6-69a4-4a88-b097-d24cf552e855)

**Comment by marekschneider** [comment]
> Might still be an issue on latest:
> 
> ![image](https://private-user-images.githubusercontent.com/4389156/341982462-81f55ee6-69a4-4a88-b097-d24cf552e855.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzI5ODMsIm5iZiI6MTcxOTA3MjY4MywicGF0aCI6Ii80Mzg5MTU2LzM0MTk4MjQ2Mi04MWY1NWVlNi02OWE0LTRhODgtYjA5Ny1kMjRjZjU1MmU4NTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjJUMTYxMTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc5MWZmNTg4NThjOTk2ZmY3Yjk0ZGE1MGM3ZmM2ODhhOGExOGE2MTQ3OGE4Njg1ZWI3ZTc4MGVlNTQ4YjVhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7uuxaKW7Cv9hdzBj-EIV4IpcBDFOG_yc66tx-EeQpU0)

 I am experiencing the same issue in the latest version.

**Comment by makotech222** [comment]
I moved the code back to main.rs and it works fine.

**Comment by asonix** [comment]
fwiw pict-rs installs a provider on it's own if one is not already set. If you care about your provider taking precedence it needs to be installed before pict-rs is started

**Comment by makotech222** [comment]
moved the init code back to main.rs. The first PR that was made had this, but i think some formatter thing complained in the PR, and it got moved to where it is now. My screenshot is also showing the correct place for it.

**Comment by dessalines** [comment]
I'll wait on a PR from you for this.

**Comment by makotech222** [comment]
I don't have anything set up to submit PRs anymore to lemmy sorry.

**Comment by dessalines** [comment]
You can't run these commands?

```
git clone https://github.com/LemmyNet/lemmy
git checkout -b fix_tls_pool
```

???
