### ISSUE TITLE
Orthogonal search filters

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy#4800]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Currently, several of our search filters are actually more than one filter at once. The easiest to explain example if the Top <insert time frame here> sorts. These all filter by the highest score over different time frames, but some of our sort types also make sense to be sorted by time frame. Controversial and Most Comments are also things users would likely want to limit to a time frame, e.g. what are the most controversial posts of the day or the most commented on posts of the year? Even Active, Hot, and New Comments could arguably benefit from this.

Sacled is another factor for sorting that I think needs to be distinct from the other sorts. Currently, it only scales hotness. Users could very well like to see total score, activity, controversey, etc. scaled by community as well.

This isn't even going into sorting communities and comments (users already have their own sort types) where several of the sort options don't even make sense. 

### Describe the solution you'd like.

I think there are 3 aspects of sorting posts that need to be separated so they can be used alongside eachother:
- What is being sorted by (score, number of comments, active, etc.)
- Time frame being sorted over
- Whether or not to scale sort by community size

I also think it's worth relooking at comment and community sorts. Communities, for example, are one thing in our app that makes sense to have an option to sort alphabetically.

### Describe alternatives you've considered.

Living with it.

**Comment by Nutomic** [comment]
Essentially the same as https://github.com/LemmyNet/lemmy/issues/4340
