### ISSUE TITLE
[Bug]: Comments disassociated with post

### ISSUE THREAD

**Issue by Fmstrat** [LemmyNet/lemmy#4807]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Growing number of posts that show a large comment count but no, or few, actual comments. Federation appears normal across any instances providing comments.

An example is: https://lemmy.nowsci.com/post/8091511

As you can see from that post, there are only 2 comments displayed, and a "2 more replies" that does nothing. When inspecting the DB for this post:

```
SELECT *
FROM post
WHERE id = 8091511
-- Gives 1 record as expected

SELECT *
FROM post_aggregates
WHERE post_id = 8091511
-- Gives 1 record as expected, with 104 in the comments column

SELECT *
FROM comment
WHERE post_id = 8091511
-- Gives 105 records, so just about right

SELECT *
FROM comment_aggregates
WHERE comment_id IN (
    SELECT id
    FROM comment
    WHERE post_id = 8091511
)
-- 105 records again
```

Everything looks in order. All comments are present and accounted for, but whatever SQL is running to grab them in the backend is not actually grabbing them all. I would guess this is a `JOIN` that's either out-of-line or there is missing data outside of the `comments` table that a `JOIN` is expecting to be there.

Happy to provide any query results or debug as necessary. Thanks!

### Steps to Reproduce

I'm not sure of the specific situations that cause this, but it's been as simple as:

1. Post to a community on another instance
2. Get notifications of comments (including comment content)
3. Comments are not on the post

### Technical Details

- I don't have debugging logs on, so they're unfortunately empty.
- Running in docker on Ubuntu Server
- No browser console errors
- Issue occurs when using API via app, or via web

### Version

0.19.3

### Lemmy Instance URL

lemmy.nowsci.com

**Comment by Nothing4You** [comment]
seems like you broke your language settings, without login you can see a bunch of comments that are marked as english language.

go to https://lemmy.nowsci.com/settings and adjust the language multi select, hit save, and you'll see the comments again.

**Comment by Fmstrat** [comment]
Well that was dumb. No idea how that could have happened. Appologies for the report, thanks!
