### ISSUE TITLE
Change how number of votes affects controversy rank

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#4852]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Controversial sort is sometimes too similar to top sort.

Example:

https://lemmy.ca/u/dullbananas?page=1&sort=Controversial&view=Overview

This post should be closer to the top:  https://lemmy.ca/post/23418411

Completely ignoring the vote count would also be bad because it would cause a lot of stuff to go to the top by having an insignificant amount of downvotes.

### Describe the solution you'd like.

Replace `(upvotes + downvotes)` with `least(upvotes + downvotes, 10)`

### Describe alternatives you've considered.

Use logarithmic scale, just like hot sort

**Comment by dessalines** [comment]
[Here's the controversy_rank function](https://github.com/LemmyNet/lemmy/blob/main/crates/db_schema/replaceable_schema/utils.sql#L11).

Which is basically `(upvotes + downvotes) / (upvotes / downvotes)`

Some discussion of that function is here: #2515 , and reddits algo, which is what ours matches, is [here](https://github.com/reddit-archive/reddit/blob/master/r2/r2/lib/db/_sorts.pyx#L60).

The fact that it takes the magnitude of upvotes + downvotes, tells me that it intentionally biases popular posts no matter what.

**Comment by dullbananas** [comment]
Reddit algorithm appears to use exponent instead of multiplication

**Comment by dessalines** [comment]
Ah `**` means exp. Should be an easy fix then, just changing that function.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/4872
