### ISSUE TITLE
Fix incorrect community removals

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#4861]
It might be possible to create a migration that reverts incorrect community removals caused by the issue fixed in #4859.

**Comment by Nutomic** [comment]
Its better to discuss this in the security advisory, not here.

**Comment by dullbananas** [comment]
The linked PR is the one for the function used by removing communities created by a banned user, which fixes a bug found by chance and not actually relevant to the other issue

**Comment by Nutomic** [comment]
As no one has complained about this it doesnt seem important.
