### ISSUE TITLE
Mod actions on secondary instance don't federate probably

### ISSUE THREAD

**Issue by chris-y** [LemmyNet/lemmy#4865]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Modding users and changing community descriptions aren't working on 0.19.5 when the mod user is on a different instance to the community.

### Steps to Reproduce

1. Create a community on instance A
2. Create a new user on instance B
3. Post in the community using user B
4. Give user B mod rights (this should work) 
5. Create a second user "C" on instance A
6. Post on the community using user C
7. Give user C mod rights using user B (this should show up as mod on instance B only)
8. Edit the community description using user B.
9. Check both these things on instance A, user C has no mod rights and the description hasn't changed.

### Technical Details

Public instances so don't have access to this.

### Version

0.19.5

### Lemmy Instance URL

was attempting this on: feddit.uk,lemm.ee

**Comment by chris-y** [comment]
This was working fine on 0.19.3, it appeared to break when instance A was on 0.19.4 and instance B was still on 0.19.3.

**Comment by chris-y** [comment]
> I am having the same issue right now. However, both instances are 0.19.5.

Same. Federation generally seems to be a bit flaky, I'm getting some posts not coming through, and edits not federating.

**Comment by WaterSword** [comment]
experiencing the same issue, editing the sidebar, banner and icon of a community on a different instance than my account.

**Comment by chris-y** [comment]
> Same. Federation generally seems to be a bit flaky, I'm getting some posts not coming through, and edits not federating.

Turns out my general federation problems were an automod bot being a bit over-zealous!  This doesn't explain the mod actions though - especially as others are reporting the same.

**Comment by dessalines** [comment]
We might need to add some API tests for post featuring / unfeaturing to make sure that's federating correctly. 

As for edits tho, I'm positive we have federation tests for those.

@Nutomic any idea what might be causing this one? I think there was some changes to how featuring works in a federated way.

**Comment by Nutomic** [comment]
There was https://github.com/LemmyNet/lemmy/pull/4475 but it wouldnt break sidebar edits. Best to write an api test for remote mod actions and see where things fail.

**Comment by flamingo-cant-draw** [comment]
I believe this issue is caused by #4611.
