### ISSUE TITLE
`list_logins` endpoint response is inconsisent with other endpoints

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#4873]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

`GET /user/list_logins` returns a list of `LoginToken`. Every other endpoint returns a Response object that is a wrapper for a list of entities. For example `ListMediaResponse` or `ListCommunitiesResponse` or `ListPostLikesResponse` or `ListPostLikesResponse` or ...

list_logins is the only endpoint that directly returns a list.

### Describe the solution you'd like.

Add a wrapper Response object like the other endpoints

### Describe alternatives you've considered.

Do not change it.

**Comment by dessalines** [comment]
Makes sense, I can get this one.
