### ISSUE TITLE
'PersonBlockId' / 'CommunityBlockId' is not used

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#4879]
These type alias arent used. Either use them for BlockPerson/ BlockCommunity which use just `PersonId` or `CommunityId`

Or don't export them.

**Comment by MV-GH** [comment]
'CommunityBlockId' should then also be removed?

**Comment by dessalines** [comment]
I don't see that one.

**Comment by MV-GH** [comment]
mb, that was a 0.18.5 remnant. No longer exists
