### ISSUE TITLE
Log activities that are slow to send

### ISSUE THREAD

**Issue by Nothing4You** [LemmyNet/lemmy#4883]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

With #4864 merged, outbound federation may slow down in some situations without visible errors, while this previously would abort earlier and give an indicator that the connection timed out.

### Describe the solution you'd like.

Outbound federation submissions that take longer than a certain threshold, e.g. 10 seconds, will get logged, along with their duration.

### Describe alternatives you've considered.

N/A

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/activitypub-federation-rust/pull/127
