### ISSUE TITLE
[Bug]: Can't submit anything because of a rate limit error

### ISSUE THREAD

**Issue by stemy2** [LemmyNet/lemmy#4884]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Hello,

I tried to create a community, but the validation button doesn't do anything.

### Steps to Reproduce

1. Login to the instance.
2. Create a new community.
3. Click on the submit button.

### Technical Details

Browser console
```
XHRPOST
https://lemmy.ml/api/v3/community
[HTTP/2 400  247ms]

	
error	"rate_limit_error"
```

### Version

BE: 0.19.5

### Lemmy Instance URL

lemmy.ml

**Comment by dessalines** [comment]
Its rated to 2-3 max per hour on lemmy.ml for registers and community creation. You're correctly hitting the rate limit most likely.

**Comment by stemy2** [comment]
Shouldn't you raise the said limit ? No matter the time i wait, i still have the error message, it literally prevents me to use the service.

**Comment by dessalines** [comment]
I'm not able to replicate this. I just tested by making a new account, and creating a new community, and everything worked fine. 

The only thing I can think of is that you're on a VPN (I am too btw), that's hitting lemmy with a lot of requests by the same IP.

**Comment by dullbananas** [comment]
This might indicate a need for per-user rate limits

**Comment by beedell-roke** [comment]
I've just hit this by merely uploading two JPEG banners and avatars for two communities: [^1] [^2]

[^1]: [`lemmy.ml/c/blame`][1]

[1]: https://lemmy.ml/c/blame

[^2]: [`lemmy.ml/c/backrooms`][2]

[2]: https://lemmy.ml/c/backrooms

> ~~~JSON
> {"data":{"error":"rate_limit_error"},"state":"success"}
> ~~~

**Comment by dessalines** [comment]
We have strict upload size and rate limits. You'll need to wait a bit to be able to upload more photos.

**Comment by beedell-roke** [comment]
@dessalines, the problem I've experienced with that that makes designing banners seriously difficult, since the previewer is 1:1 equivalent with the result, and the timeout lasts a while.

**Comment by dessalines** [comment]
You'll just need to look at the banner before uploading. Different apps are going to render it differently anyway, so there's no guarantee it'll look the same everywhere.

**Comment by beedell-roke** [comment]
> there's no guarantee it'll look the same everywhere

@dessalines, I can't design for what I can't design for, indeed. However, I'm not attempting to: submitting a banner that (looks good in an image viewer, but) doesn't fit the *website* GUI at least, would be nonsensical. I could file an FR for an accurate previewer...?

**Comment by dessalines** [comment]
A previewer wouldn't bypass image upload rate limits, but you're free to open an issue on the lemmy-ui repo for one. Ideally in the edit community, after uploading, it would try to render it in a way that looks similar to the non-edit view.
