### ISSUE TITLE
[Bug]: Login fails if local user does not have an entry on local_user_vote_display_mode

### ISSUE THREAD

**Issue by lullis** [LemmyNet/lemmy#4885]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

The query used for login relies on a join between `local_user`, `local_user_vote_display_mode`, `person` and `person_aggregates`. If local user does not have an entry on `local_user_vote_display_mode` the `find_by_email_or_name`  function will not return the user, and the whole login process fails.

### Steps to Reproduce

1. Create an local user
2. Remove its local_user_vote_display_mode entry.
3.Attempts to login will all fail with "incorrect_login"

### Technical Details

Not relevant

### Version

0.19.5

**Comment by Nothing4You** [comment]
Unless this situation can happen during regular operation, how is this a bug?

If you delete random data in the database it's not unexpected that things will not work as intended.

Presumably this is because you insert users into the database outside of Lemmy, in which case you are responsible for creating all necessary db rows to ensure it does the same steps Lemmy code does.

**Comment by lullis** [comment]
How is information about user preferences relevant to the authentication process?

I just spent the better part of a day chasing down authentication issues and nothing but a "incorrect login" message because of this. It's low priority for sure, but if the application code only works on the assumption that the underlying database will always be fully intact, I'd say that it is indeed a bug.

**Comment by MV-GH** [comment]
Just because it isn't strictly needed for the authentication process doesn't mean you will have a functioning user. `local_user_vote_display_mode` is required to exist for the local_user. Without this the `/site` will fail for that user. You won't be any further. 

In the future i recommend that you use the create account API call, to create users, Lemmy will take care of the requirements.

**Comment by Nutomic** [comment]
Like @MV-GH said, we cant ensure that Lemmy keeps working correctly when you do arbitrary edits in the db.

**Comment by lullis** [comment]
> Just because it isn't strictly needed for the authentication process doesn't mean you will have a functioning user.

Agreed, but irrelevant to the point. "Having a functioning user" is a separate concern. If your authentication system can only work if it does on some form of data integrity that is not directly a function of authentication data (username, password, 2fa secret), it's definitely a sign of mixed responsibilities.

>  Without this the `/site` will fail for that user.

And with proper separation of concerns, it would be a lot easier to (a) detect why it's failing and (b) implement proper exception-handling.

In this case, it's just a table with a bunch of default values, mapped 1:1 to the user. How hard would it be to create the entry for the user if the record is not present?

> In the future i recommend that you use the create account API call, to create users, Lemmy will take care of the requirements.

I am interacting with the database because I am building an application that does things that are *precisely* made to bypass the current API. I need to create users directly by authenticating with their reddit credentials, without password, and without depending on application approval. If the Account API allowed me to do these things, I certainly would.

**Comment by dessalines** [comment]
> and without depending on application approval

That's an optional setting that your server can turn off.

> I need to create users directly by authenticating with their reddit credentials

So do that and then create a lemmy user via the API. There's nothing in the API that prevents you from doing this.

If you need features added to the API, that's the way to handle this. Not via manual DB commands.

**Comment by lullis** [comment]
> That's an optional setting that your server can turn off.

This is meant to be run as a separate service that can be installed by other admins on their server. A priori, I can not dictate how they should set up their servers. Admins might want, e.g, to keep their registrations closed except for users that sign up via reddit like what I've done for alien.top.

> f you need features added to the API, that's the way to handle this. 

Yeah, in effect what I am doing is developing an API of my own, because I have no control over Lemmy's API. If Lemmy provided authentication with OIDC already, I would be fine with it.
