### ISSUE TITLE
Question: undelete option for comments and how does deleting work in Lemmy?

### ISSUE THREAD

**Issue by Baerbeisser** [LemmyNet/lemmy#4886]
### Question

In the comment menu there is a "delete" option. I would expect an "undelete" option in the same place for deleted comments but there's none. Instead there's still up/downvote, save, share, report, which makes no sense for deleted comments.

Where can i undelete deleted comments in Voyager?

And btw, other people seem still able to see my deleted comments but i can't.

**Comment by Nothing4You** [comment]
you can find the voyager issue tracker here: https://github.com/aeharding/voyager/issues

deleted comments may have been visible in some clients before lemmy 0.19.4, as of lemmy 0.19.4 this has been addressed.

keep in mind though that deleting anything posted on the internet is effectively "nicely asking" other instances to delete the content, and they may decide not to delete them.

**Comment by dessalines** [comment]
You're asking in the wrong repo, this is for the lemmy back-end, not the voyager app.
