### ISSUE TITLE
[Bug]: pict-rs transformations don't apply to proxied images

### ISSUE THREAD

**Issue by Xyphyn** [LemmyNet/lemmy#4893]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I'm unsure if this is a `pict-rs` issue or a Lemmy issue, but looking at `pict-rs`'s API, I think it's more likely to be Lemmy.

Many clients use pict-rs image transformations to load images more efficiently, such as `thumbnail` and `format`. Recently, as I was testing performance of my app, I noticed images were taking a ridiculous amount of bandwidth. Looking into it, **images via `/image_proxy` were being loaded at their full size, regardless of these arguments.**

This is not good for bandwidth, as this 24px avatar is being loaded in 4K.

![image](https://github.com/LemmyNet/lemmy/assets/80978739/c57a9ab2-9345-4bea-86e8-762552516c40)

These arguments still work fine for non proxied images, and before 0.19.4.

### Steps to Reproduce

1. Fetch an image via `/image_proxy`
2. Add arguments to control image size/format, such as `?thumbnail=256&format=webp`
3. Observe how the received image ignores those arguments.

### Technical Details

The solution to this is likely to pass these parameters to pict-rs. 

### Version

0.19.5

### Lemmy Instance URL

lemm.ee

**Comment by dessalines** [comment]
Could you link the post / profile example?

**Comment by Xyphyn** [comment]
Here's one image:

https://lemm.ee/api/v3/image_proxy?url=https%3A%2F%2Fmander.xyz%2Fpictrs%2Fimage%2Fdbeda0de-d3fb-4fab-8703-3e52e72cb4db.jpeg&format=webp&thumbnail=48

Notice how format is set to webp and thumbnail is 48, but it still loads the full thumbnail. Lemmy-ui doesn't use these afaik (if recommend it should!), so this issue doesn't completely apply there.

Every proxied image has this issue.

**Comment by dessalines** [comment]
@asonix is there a way to do image processing on these proxied image urls?

**Comment by Nutomic** [comment]
It seems like we need to request proxied images via `/image/process` if there are any parameters. Basically the same logic as [here](https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/images.rs#L134-L150).

![Screenshot_20240709_175913](https://github.com/LemmyNet/lemmy/assets/1044450/b842f1e0-4aea-4e82-9324-894c22ae414d)

**Comment by dessalines** [comment]
K, I'll get this.
