### ISSUE TITLE
refactor: use rsa instead of openssl

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#4900]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Use the `rsa` crate instead of openssl, as this will make lemmy much more portable. 

It also could potentially mean we could stop using these custom docker images (iirc bundling openssl was one of the main reasons they're necessary, and also possibly postres libs)

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

### Additional context

https://github.com/LemmyNet/activitypub-federation-rust/pull/116

cc @kwaa

**Comment by kwaa** [comment]
It looks like Lemmy is only using OpenSSL [here](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/apub.rs), and this file is not used.

Maybe delete it to solve this issue?

**Comment by kwaa** [comment]
Lemmy:

- [ ] activitypub-federation (https://github.com/LemmyNet/activitypub-federation-rust/pull/116)
- [ ] lemmy-utils

Other libraries with `openssl` / `native-tls` deps:

- [ ] reqwest
- [ ] lettre

**Comment by dessalines** [comment]
Ya, if its unused go ahead and delete it in a PR.

reqwest *might* already have a non-openssl feature that we just need to use: https://docs.rs/reqwest/latest/reqwest/#optional-features

**Comment by kwaa** [comment]
> lettre would also appreciate a PR I'm sure, and we stay on the latest versions of that also.

lettre also has `rustls-tls` feature: https://github.com/lettre/lettre/blob/0132bee59d4963ba21c532b35281e00aae8ce81e/Cargo.toml#L111

Since I don't plan to clone Lemmy locally, I can't test them.

**Comment by dessalines** [comment]
I'll test that one and add it to your PR

**Comment by kwaa** [comment]
Lemmy's `Cargo.lock` no longer contains `openssl`, so this issue can be closed.

**Comment by dessalines** [comment]
Thx for helping with this!

**Comment by Nutomic** [comment]
Blocked by https://github.com/LemmyNet/lemmy/pull/4904

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/4976
