### ISSUE TITLE
Add CleanURL Rules as a Submodule to be used in sanitizing URLs. 

### ISSUE THREAD

**Issue by The-RedWizard** [LemmyNet/lemmy#4905]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Currently, Lemmy will attempt to clean the URLs based on its own rules, instead I think it would be great if we could adopt the [crowd soured rules](https://github.com/ClearURLs/Rules/) created for the CleanURL extension. Considering Lemmy has such a large user base with a vested interest in scrubbing URLs from their respective platforms, we could contribute back to the CleanURL ruleset in a large way. 

### Describe the solution you'd like.

Per this thread conversation: [https://hexbear.net/comment/5136579](https://hexbear.net/comment/5136579) I've created a pull request that adds the Rules repo under `Modules\Rules` as a submodule to the Lemmy repo. This could either be implemented as a default functionality, or an optional functionality for Lemmy Admins. Ultimately, I think it makes good sense to not reinvent the wheel when it comes to URL sanitization. 

### Describe alternatives you've considered.

Initially, I thought of solving this issue via a bot that either DMs the OP of a post or comments within the post containing the sanitized URL, but since there is already some level of sanitation happening, it feels right to put this directly within the backend. 

### Additional context

This is my first real pull request, so please let me know if I'm not following proper procedure, or if I misunderstood the conversation within that thread.

**Comment by dessalines** [comment]
This would be a great opportunity for someone to build a proper rust crate to do this, that could be used by many projects.

I created a lemmy post about this: https://lemmy.ml/post/18162485

**Comment by jendrikw** [comment]
I wrote something in the last couple days.

https://crates.io/crates/clearurls

Let me know if if fits your need or you need anything else. Issues and PRs welcome.

**Comment by dessalines** [comment]
@jendrikw We'd be able to use the crate, but are dependent on https://github.com/jendrikw/clearurls/issues/3 , since our comments often contain links that also need to be stripped of tracking.
