### ISSUE TITLE
create_community  How can we have the same name? Can we set it to not have the same name Can the minimum number of words in the name be changed from 3 to 2

### ISSUE THREAD

**Issue by qiancsff** [LemmyNet/lemmy#4909]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

create_community 
How can we have the same name? Can we set it to not have the same name
Can the minimum number of words in the name be changed from 3 to 2

### Describe the solution you'd like.

create_community 
How can we have the same name? Can we set it to not have the same name
Can the minimum number of words in the name be changed from 3 to 2

### Describe alternatives you've considered.

create_community 
How can we have the same name? Can we set it to not have the same name
Can the minimum number of words in the name be changed from 3 to 2

**Comment by dessalines** [comment]
I can't tell what this means, but yes, community names must be unique. Use the display name to differentiate them.
