### ISSUE TITLE
[Bug]: Email notifications for new registrations are no longer sent

### ISSUE THREAD

**Issue by Illecors** [LemmyNet/lemmy#4916]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Starting with 0.19 my instance no longer sends out registration notification emails. Email itself is working fine - reports and registration verification is sent out correctly.

Postfix logs only show a single connection attempt as well.

### Steps to Reproduce

1. Sign up at lemmy.cafe

### Technical Details

[lemmy.log](https://github.com/user-attachments/files/16338851/lemmy.log)

### Version

0.19.5

### Lemmy Instance URL

https://lemmy.cafe

**Comment by dessalines** [comment]
Here's the code for that: https://github.com/LemmyNet/lemmy/blob/main/crates/api_crud/src/user/create.rs#L190

Do you have `require_email_verification` turned on? If so, it shouldn't send one out until after they've verified their email.

**Comment by Illecors** [comment]
I do have `require_email_verification` turned on. I think it used to work exactly the way you describe - after the applicant confirmed their email address.

The comment on line 190 and the following `if` implies that it actually would not send out an email. If that's expected - should I raise a feature request?

**Comment by Nutomic** [comment]
In that case the admin notification is sent out [after the user verified his email address](https://github.com/LemmyNet/lemmy/blob/main/crates/api/src/local_user/verify_email.rs#L44). However the check for `RegistrationMode::RequireApplication` seems wrong and is probably causing your problem as you have applications disabled. Would you make a PR to remove that line?
