### ISSUE TITLE
[Bug]: Wrong return message from API when creating comment on local-only community

### ISSUE THREAD

**Issue by abdel-m** [LemmyNet/lemmy#4918]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Related to #4853 
When i try to create a comment on a local-only community, the API creates successfuly the comment but return the message "CouldntFindComment". 
Tried on my local Lemmy instance and also tried on this public instance : https://enterprise.lemmy.ml/

### Steps to Reproduce

1. Create a LOCAL-ONLY community
2. Create a new post (no need image)
3. Try to comment this post

### Technical Details

Trace logs on my server : 
2024-07-24T14:53:37.623261Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: CouldntFindComment: CouldntFindComment
   0: lemmy_api_common::build_response::send_local_notifs
             at crates/api_common/src/build_response.rs:95
   1: lemmy_api_crud::comment::create::create_comment
           with data=Json(CreateComment { content: "test", post_id: PostId(10), parent_id: None, language_id: None }) local_user_view=LocalUserView { local_user: LocalUser { id: LocalUserId(2), person_id: PersonId(3), password_encrypted: Sensitive, email: None, show_nsfw: true, theme: "browser", default_sort_type: Active, default_listing_type: Local, interface_language: "fr", show_avatars: true, send_notifications_to_email: false, show_scores: true, show_bot_accounts: true, show_read_posts: true, email_verified: false, accepted_application: true, totp_2fa_secret: None, open_links_in_new_tab: false, blur_nsfw: true, auto_expand: false, infinite_scroll_enabled: false, admin: false, post_listing_mode: List, totp_2fa_enabled: false, enable_keyboard_navigation: false, enable_animated_images: true, collapse_bot_comments: false }, local_user_vote_display_mode: LocalUserVoteDisplayMode { local_user_id: LocalUserId(2), score: false, upvotes: true, downvotes: true, upvote_percentage: false }, person: Person { id: PersonId(3), name: "######", display_name: None, avatar: None, banned: false, published: 2024-07-18T23:15:17.530203Z, updated: None, actor_id: DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("########")), port: None, path: "/u/######", query: None, fragment: None }), bio: None, local: true, private_key: Some(Sensitive), public_key: "MANUALLY REMOVED", last_refreshed_at: 2024-07-18T23:15:17.530203Z, banner: None, deleted: false, inbox_url: DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("##########")), port: None, path: "/u/######/inbox", query: None, fragment: None }), shared_inbox_url: Some(DbUrl(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("##########")), port: None, path: "/inbox", query: None, fragment: None })), matrix_user_id: None, bot_account: false, ban_expires: None, instance_id: InstanceId(1) }, counts: PersonAggregates { person_id: PersonId(3), post_count: 6, post_score: 9, comment_count: 11, comment_score: 0 } }
             at crates/api_crud/src/comment/create.rs:39
   2: lemmy_server::root_span_builder::HTTP request
           with http.method=POST http.scheme="http" http.host=######## http.target=/api/v3/comment otel.kind="server" request_id=d5d47950-4890-4e14-8b2b-bc22fb692aa8 http.status_code=400 otel.status_code="OK"
             at src/root_span_builder.rs:16

### Version

BE 0.19.5

### Lemmy Instance URL

https://enterprise.lemmy.ml/

**Comment by abdel-m** [comment]
My bad, issue already exist

**Comment by abdel-m** [comment]
I reopen this issue because i tried the fix from the PR #4854 and it does not work

**Comment by dessalines** [comment]
Enterprise.lemmy.ml isn't running the change with the previous fixes. I need to look at the comment_view read to see if this is actually an issue.

**Comment by dessalines** [comment]
Okay I've verified that you're correct, if `my_local_user` isn't passed, it won't send notifications.

**Comment by abdel-m** [comment]
i'm testing on the main branch with merged PR but it's not working... Also when i create a comment on a local community and then delete it, the server raise the same error "CouldntFindComment", the same when I click on "+1" or "-1" button

**Comment by dessalines** [comment]
I'll also test this now.

**Comment by dessalines** [comment]
I can't replicate either case. Which commit are you on?

**Comment by abdel-m** [comment]
I'm on the last commit 5421e9a from my fork at https://github.com/abdel-m/lemmy (I synced the repos before the tests)

**Comment by dessalines** [comment]
```
cd docker
./docker_update.sh
```

and go to http://HOST:1236 , and try it again.
