### ISSUE TITLE
[Bug]: Remote mods can't edit communities

### ISSUE THREAD

**Issue by flamingos-cant** [LemmyNet/lemmy#4930]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

If a mod on a remote instance to the community tries to edit it, the changes only apply on the mod's instance as the community's instance rejects the edit.

### Steps to Reproduce

1. Be a mod on a remote community
2. Edit the community
3. The changes only apply on your local instance

### Technical Details

I ran into this from a [new community](https://feddit.uk/c/herfriend@sappho.social) I have on a new instance for the domain, and when I added a description with my feddit account, the changes weren't reflected on sappho. Here's what I get in the logs:

```
2024-07-31T11:36:38.874292Z  WARN lemmy_server::root_span_builder: Unknown: cant accept local object from remote instance
    0: lemmy_apub::objects::community::verify
              at crates/apub/src/objects/community.rs:131
    1: lemmy_apub::activities::community::update::verify
              at crates/apub/src/activities/community/update.rs:78
    2: lemmy_apub::activities::community::announce::receive
              at crates/apub/src/activities/community/announce.rs:51
    3: lemmy_server::root_span_builder::HTTP request
            with http.method=POST http.scheme="http" http.host=sappho.social http.target=/inbox otel.kind="server" request_id=eba2ad40-589a-4678-bddb-a5a8fcadca83
              at src/root_span_builder.rs:16
```

### Version

0.19.5

**Comment by Nutomic** [comment]
Duplicate https://github.com/LemmyNet/lemmy/issues/4865
