### ISSUE TITLE
INFO: paginationcursor possible to return duplicate posts?

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#4961]
### Question

Jerboa used to check for duplicate postIds on post retrieval, since duplicates are often possible with page param. I believed that wasn't the case with paginationcursor. So this check wasn't implemented for it. But from what I hear from the user of Jerboa, it isn't case as they are experiencing duplicate posts. Is my understanding wrong about pagination cursor? Or is this more a bug on Lemmy side?

**Comment by Pdzly** [comment]
I didnt noticed any duplication on LW ( 0.19.3 )

**Comment by Nothing4You** [comment]
I believe this depends on the sort order?
The cursor is effectively just a post id currently if I'm reading it correctly.
When sorting by `New` the page cursor can easily determine where to continue without duplicates, but with other sort types, like `Active`, the sort order might change from what was used on the original request. If the post id used for the returned cursor is now earlier in the result, posts that used to be before this post will get returned again.

**Comment by MV-GH** [comment]
Ah yes that makes sense. I was thinking they all decay at the same rate but that's not the case
