### ISSUE TITLE
 [Feature] Admin Setting/Slider for Adjusting Character Limit on User Bios

### ISSUE THREAD

**Issue by recursiveAdaption** [LemmyNet/lemmy#4972]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Admins are unable to expand or reduce the character limit for user bios

### Describe the solution you'd like.

A slider and/or input box similar to settings under the Admin Settings page that would allow instance admins to adjust users' bio character limit

### Describe alternatives you've considered.

I've looked through Admins Settings and was asked to open an issue here on the backend

### Additional context

Here's the link to the feature request that was made on [Lemmy's frontend](https://github.com/LemmyNet/lemmy-ui/issues/2657) before this request

**Comment by dullbananas** [comment]
Why is a different limit needed?

**Comment by recursiveAdaption** [comment]
> Why is a different limit needed?

- allowing our users to customize their profile to freely express themselves has a higher likelihood to convince new people to join Lemmy, as such this should have a positive impact on increasing new user acquisition in a sustainable stable manner with an assumed easy-to-implement feature.

I'd like to apologize in advance if this feature is harder to implement in reality due to one reason or another, unfortunately I'm uninformed on Lemmy's development process so assuming that the implementation is easier in principal than practice is/can be naive

As a recent software dev grad, I can understand the absurdity when sometimes a stakeholder or passing user claims that a proposed feature should be easy to implement

Anyways thank you for taking the time and effort to read my feature request!

**Comment by Nutomic** [comment]
The current limit is [300 chars](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/utils/validation.rs#L23). I would prefer to change that hardcoded value instead of adding another setting. As a reference it would be good to know how many chars are allowed by other platforms.

**Comment by dessalines** [comment]
I agree, I'd prefer to keep it hard-coded rather than making it customizeable. What that limit should be, I don't know.

**Comment by DraconicNEO** [comment]
I'm in agreement that it should be hard-coded, or really just not there at all. 

Honestly I'm not entirely sure what i t should be but I do know that as it currently is it is very short, it should be a bit longer than 300 characters. Maybe 1000 characters?

**Comment by Nutomic** [comment]
Youre welcome to make a pull request, just change the number I linked above.

**Comment by dessalines** [comment]
I'll make a PR for this shortly, its easy enough.
