### ISSUE TITLE
Fetching Wordpress blogs as communities

### ISSUE THREAD

**Issue by Nicthurne** [LemmyNet/lemmy#5000]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Acitivitypub-enabled Wordpress sites have two actors: "For instance, if your website is example.com, then the blog-wide profile can be found at @example.com@example.com, and authors like Jane and Bob would have their individual profiles at @jane@example.com and @bobz@example.com, respectively." ([source](https://wordpress.org/plugins/activitypub/#description))

From within a Lemmy search bar, I can fetch the "individual profiles", but not the "blog-wide profiles".
For example, from my account at lemm.ee I was able to fetch @eric@chefblogger.me ([as seen here](https://lemm.ee/u/Eric@www.chefblogger.me)) but not @chefblogger.me@chefblogger.me. 

I see that https://lemmy.ml/c/notiz.blog@notiz.blog exists, so it probably worked at some point, but similarly I currently can not fetch notiz.blog@notiz.blog to show up as a community/group from within lemm.ee.

### Describe the solution you'd like.

"Blog-wide profiles" from Wordpress sites (resp. their Activitypub actors) should be able to be fetched from a Lemmy instance to show up as a community that can be subscribed to. That is especially crucial for federation as on Lemmy, one can't subscribe to the "individual profiles" which are federated as users.

### Describe alternatives you've considered.

I'm really not knowledgeable enough to consider alternatives.

**Comment by harcesz** [comment]
Oddly enough fetching the collective profile (not the posts) seems to be working on 0.19.3 - https://szmer.info/c/kolektyw@adapulawska.org but not on 0.19.05

**Comment by dessalines** [comment]
Lemmy only allows following activitypub groups, not person actors. So unless wordpress identifies blogs as groups, then we can't support this.

**Comment by Nutomic** [comment]
No Wordpress should work, see https://github.com/LemmyNet/lemmy/pull/4692. 

chefblogger.me seems to have federation disabled, because the following command returns html instead of json: `curl -H "Accept: application/activity+json" -v https://www.chefblogger.me/blog/`

For notiz.blog the problem is https://github.com/LemmyNet/activitypub-federation-rust/pull/114, which will be fixed in Lemmy 0.19.6

**Comment by DraconicNEO** [comment]
> No Wordpress should work, see #4692.
> 
> chefblogger.me seems to have federation disabled, because the following command returns html instead of json: `curl -H "Accept: application/activity+json" -v https://www.chefblogger.me/blog/`
> 
> For notiz.blog the problem is [LemmyNet/activitypub-federation-rust#114](https://github.com/LemmyNet/activitypub-federation-rust/pull/114), which will be fixed in Lemmy 0.19.6

I tried to subscribe to a few federated blogs but I would get it stuck at subscribe pending forever. Will this issue also be fixed in 0.19.6 as well?

**Comment by Nutomic** [comment]
Which blogs specifically?

**Comment by DraconicNEO** [comment]
> Which blogs specifically?

soatok.blog

**Comment by Nutomic** [comment]
I tried with 0.19.6 and its working: https://voyager.lemmy.ml/c/soatok.blog@soatok.blog

**Comment by DraconicNEO** [comment]
> I tried with 0.19.6 and its working: https://voyager.lemmy.ml/c/soatok.blog@soatok.blog

Awesome, so I guess this one has the same issue as notiz.blog which is getting fixed in 0.19.6
