### ISSUE TITLE
Federate with Guppe

### ISSUE THREAD

**Issue by plink1** [LemmyNet/lemmy#5019]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I have had good results sending Lemmy posts to Mastodon, and vice-versa. One exception has been the above group shown in the title. In Mastodon, send/receive posts works fine, but the Lemmy version seems cut off from the rest of the Fediverse.  Posts to that group from Lemmy simply show up in the lemmy version of the group, but not in the group itself. (screen shot provided).

In Mastodon, that same group shows posts every few minutes from many sources, but not posts from Lemmy. 

Could someone look into that? Thanks.

### Steps to Reproduce

1.In lemmy.ml, create a post in a test community and then cross-post to a.gup.pe/palestine.  Or simply create a post directly in  a.gup.pe/palestine.
2.Check that post in Lemmy a.gup.pe/palestine (it should show up) and then go to Mastodon and look for it there in the same-named group. (it *should* be there also, but it probably won't be - hence the bug.)
![aguppe_palestine_lemmy](https://github.com/user-attachments/assets/8f00a87f-02e7-489d-a4b5-fae294ac9038)

### Technical Details

n/a

### Version

BE: 0.19.6-beta1

### Lemmy Instance URL

lemmy.ml

**Comment by Nutomic** [comment]
> Posts to that group from Lemmy simply show up in the lemmy version of the group, but not in the group itself. (screen shot provided).

This actually means its a problem on the Guppe side, for some reason it fails to handle the federated post sent by Lemmy. Nothing we can do about it, you need to [ask the guppe developers](https://github.com/immers-space/guppe/issues). But the project hasnt received any updates in the last year so it seems half dead.

**Comment by DraconicNEO** [comment]
I made an issue there, hopefully someone can work on it, but I won't be surprised if they don't since like @Nutomic said, project is likely dead.

**Comment by Nutomic** [comment]
Ive subscribed to the issue in case there is any response. Gonna close this.
