### ISSUE TITLE
Remove the ability for community mods to delete communities.

### ISSUE THREAD

**Issue by TheOneImprove** [LemmyNet/lemmy#5021]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

I am currently semi scared from the fact that any mod could delete a community with more than 1000 users for no reason.

### Describe the solution you'd like.

I recommend instead making this functionality a server admin exclusive. 

### Describe alternatives you've considered.

You can have a button for the mods to send a request to the server admins to delete the community.

**Comment by dessalines** [comment]
These are not database deletes, and communities can be restored at the click of a button. 

There might be a UI related bug in the current released versions of lemmy that don't let mods reload a deleted community page correctly tho. Could you test that out at voyager.lemmy.ml (a test instance) ? Thx.

**Comment by Nothing4You** [comment]
@dessalines there is also the problem that only the top mod can delete/restore, admins can't restore

**Comment by dessalines** [comment]
Could you create an issue for allowing admins to restore / delete communities? It should probably be top mod OR admin.
