### ISSUE TITLE
Allow users to delete images they uploaded to via pictshare.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#505]
So far it appears that the de.lemmy.ml pictshare instance is completely separate from the Lemmy instance. In the future, we really should link the uploaded images to the account, if for nothing else other than allowing the user to manually delete them. This is important for privacy and will help with compliance with the GDPR and CCPA.

**Comment by dessalines** [comment]
This is possible using the returned delete code, that the front end could provide in some way. If someone else would like to tackle this go ahead: https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/API.md#example-2

**Comment by StaticallyTypedRice** [comment]
> This is possible using the returned delete code, that the front end could provide in some way. If someone else would like to tackle this go ahead: https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/API.md#example-2

I think the way to go about this would be to store records of image uploads and delete codes in the Lemmy database, and have a panel in the logged in user's page to delete them. When the account is deleted, they should be an option to delete all uploaded files.

It'd also be a good idea to block off pictshare to anyone not logged in to prevent it from being abused by people, for example if they're looking for a free image host, and we don't have any orphaned images.

**Comment by Nutomic** [comment]
Related: #371, https://yerbamate.dev/dessalines/lemmy/pulls/13

**Comment by Charleshthomasiii** [comment]
Can the geturl.php call return the delete url for existing pictshare images? Otherwise, I'm not sure how to get the delete url.

**Comment by StaticallyTypedRice** [comment]
> Can the geturl.php call return the delete url for existing pictshare images? Otherwise, I'm not sure how to get the delete url.

I think the delete URL is returned when the image is first uploaded.

**Comment by maltfield** [comment]
See also this ticket to add a section to the [Lemmy UI for users to be able to delete individual images](https://github.com/LemmyNet/lemmy-ui/issues/2359) without having to delete their account

 * https://github.com/LemmyNet/lemmy-ui/issues/2359
