### ISSUE TITLE
Replace all `clippy::unwrap_used` with Results and `?` in all tests.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#5051]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

In most of our tests, we use `clippy::unwrap_used` annotation, when these aren't necessary. 

### Describe the solution you'd like.

They can be replaced with `-> LemmyResult<()>` (or another result type), and use `?` in place of `unwrap`

### Describe alternatives you've considered.

NA

### Additional context

#5048

**Comment by Nutomic** [comment]
This is a good issue for new contributors to get started. You basically need to follow these steps:

1. Setup [local dev environment](https://join-lemmy.org/docs/contributors/02-local-development.html)
2. Search for `clippy::unwrap_used` in the code and remove it one at a time
3. Run `./scripts/lint.sh` and fix errors one at a time by replacing `.unwrap()` with `?`, and changing function return type to `LemmyResult<()>`
4. Commit frequently whenever it is compiling without errors
5. Repeat from 2

Its not necessary to remove all occurences in a single pull request, doing only part of them is also helpful. There are some cases where unwrap is used for `Option`, these can probably remain.
