### ISSUE TITLE
[Bug]: Hidden Communities are not Hidden

### ISSUE THREAD

**Issue by Ategon** [LemmyNet/lemmy#5074]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When a community is marked as hidden posts will still appear in the all feed even when people are not subscribed

This was not the case on 0.19.3 and is a recent bug to .4 and .5 (im assuming due to the hide post feature)

### Steps to Reproduce

1. Mark a community as hidden in the database (that you are not subscribed to)
2. Have another account make a post in that community
3. Check the all feed
4. The post will be there

### Technical Details

No errors, running on a debian server

### Version

0.19.5

### Lemmy Instance URL

programming.dev

**Comment by Nutomic** [comment]
Do you mean `community.hidden` in the db? There is a switch on the frontpage for "show hidden posts" (eye icon next to subscribed/local/all selector), do you have that disabled? Can you tell the exact api call with parameters that returns wrong data? And does the problem happen while logged in or logged out?

**Comment by Ategon** [comment]
Yes community.hidden

Shows the posts with both settings for the show hidden posts. Its the call the all feed makes which is `https://programming.dev/api/v3/post/list?limit=20&sort=New&saved_only=false&type_=All&show_hidden=false`

both logged in and out

**Comment by Nutomic** [comment]
I had a look at the code and added a test case, as far as I can tell this is being handled completely correctly. I also tested this on ds9.lemmy.ml by marking `https://ds9.lemmy.ml/c/test_hidden` and `https://a.gup.pe/u/israel` as hidden. Neither of these is showing any posts unless I subscribe first.

You mentioned some problems with database corruption in the chat, maybe the problem is related to that.

**Comment by dessalines** [comment]
Closed then as can't replicate.
