### ISSUE TITLE
[Bug]: upvotes not syncing, thumbnail url not syncing, crosspost not detected

### ISSUE THREAD

**Issue by RayCarro** [LemmyNet/lemmy#5077]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I'm not sure if these issues are related or not, but I haven't noticed these like this before programming.dev updated to 0.19.5 (they were on 0.19.3 before).

<details>

<summary>screenshots</summary>

- post on home instance with all data shown correctly: 
  - ![image](https://github.com/user-attachments/assets/ef6a611e-a3a1-47d1-98fc-936d09927dac)
- post on programming.dev with things missing and cross-post not found: 
  - ![image](https://github.com/user-attachments/assets/7564451e-7292-45ca-aaaa-34582f7b0863)
- cross-post detected on the original post: 
  - ![image](https://github.com/user-attachments/assets/26b80916-d172-44ab-9814-3bf029178a5f)

</details>

### Steps to Reproduce

1. Made a post with a custom thumbnail URL
2. Look at post from different instance
3. cross-post somewhere else (manually putting in the thumbnail URL due to it not being filled automatically)

### Technical Details

original post: https://lemmy.mods4ever.com/post/321

programming.dev view of original post: https://programming.dev/post/20177957

cross-post: https://programming.dev/post/20178106

### Version

0.19.5

### Lemmy Instance URL

https://programming.dev/post/20177957

**Comment by RayCarro** [comment]
interesting that everything seems to be working from lemm.ee https://lemm.ee/post/43962766

**Comment by Nutomic** [comment]
The crosspost to video game music was not federated to lemmy.mods4ever.com so its normal that it cant be shown. Crossposts are only checked in the local db, not explicitly federated. Regarding missing upvotes, are you following the community? If not its not going to federate completely. And can you reproduce the problem with thumbnail federation consistently? You can test with enterprise.lemmy.ml.

**Comment by RayCarro** [comment]
> The crosspost to video game music was not federated to lemmy.mods4ever.com so its normal that it cant be shown.

I included the address bar in the screenshots, the screenshot demonstrating the issue is viewing programming.dev. Both communities are followed.

**Comment by Nutomic** [comment]
programming.dev seems to have some db corruption, it could also be related to that. cc @Ategon
