### ISSUE TITLE
Edits not saving

### ISSUE THREAD

**Issue by agranapz** [LemmyNet/lemmy#5113]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Trying to edit this post https://lemmy.world/post/20682794 but is not saving the changes

### Steps to Reproduce

1. Publish post
2. Edit
3. Save changes

### Technical Details

No

### Version

BE: 0.19.3-6-g86e4cb214

### Lemmy Instance URL

lemmy.world

**Comment by agranapz** [comment]
Also selecting language post not saving

**Comment by dessalines** [comment]
Use voyager.lemmy.ml to test, but also this is likely a browser issue.

**Comment by agranapz** [comment]
> Use voyager.lemmy.ml to test, but also this is likely a browser issue.

Sorry but I don't have much idea about GitHub, can you tell me how to test it?

**Comment by Nutomic** [comment]
Make an account on https://voyager.lemmy.ml/ and try to reproduce this issue.

**Comment by agranapz** [comment]
I've tried it from several browsers and from an app for Lemmy, it doesn't work. I try in that instance...

**Comment by dessalines** [comment]
Can re-open if its still an issue. If edits were actually broken a lot of people would be seeing this.
