### ISSUE TITLE
Config not saving

### ISSUE THREAD

**Issue by agranapz** [LemmyNet/lemmy#5114]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Trying to change languages, unselect Undefined and select Español and Galego but not saving the changes

### Steps to Reproduce

1. Unselect Undefined
2. Select Español and Galego
3. Save

### Technical Details

No

### Version

BE: 0.19.3-6-g86e4cb214

### Lemmy Instance URL

lemmy.world

**Comment by agranapz** [comment]
Also not saving Mostrar notificaciones de nuevos mensajes option

**Comment by dessalines** [comment]
Use voyager.lemmy.ml to test this, as it has our main branch.
