### ISSUE TITLE
[Bug]: Different images in `image` and `attachment`

### ISSUE THREAD

**Issue by silverpill** [LemmyNet/lemmy#5115]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Images in `image` and `attachment` fields of a `Page` have different `url` even though files are identical. Is that intentional?

Example:

```json
{
  "attachment": [
    {
      "name": null,
      "type": "Image",
      "url": "https://lemmy.example/pictrs/image/c5b8cb50-34c0-4476-b041-76bca55c7ff3.jpeg"
    }
  ],
  "image": {
    "type": "Image",
    "url": "https://lemmy.example/pictrs/image/921585dc-3906-47f0-8a88-e2a5a32a9a94.jpeg"
  },
  "type": "Page",
  ...
}
```

So if a server parses both fields, the post image will be duplicated.

On one occasion I saw a post where only `image` was present but not attachment.

### Steps to Reproduce

1. Fetch `Page` object from Lemmy server

### Technical Details

N/A

### Version

0.19.5

**Comment by Nutomic** [comment]
Attachment is the post url, which may be an image or a web link. Image is the thumbnail, there is currently a bug which means thumbnails are not downsized so they are identical to the original image (https://github.com/LemmyNet/lemmy/issues/4053). This will be fixed in the next release.

**Comment by silverpill** [comment]
Ah, it's a thumbnail. I'll ignore it then, thanks for clarification.
