### ISSUE TITLE
[Bug]: Unable to verify email while logged in

### ISSUE THREAD

**Issue by asudox** [LemmyNet/lemmy#5116]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I tried changing my account's email while logged in and tried to verify it in a logged in state, which did nothing. It just redirected me to the home page of the instance I currently am on. Logging out and trying to verify using the same verification link, surprisingly, works.

### Steps to Reproduce

1. Log in with your lemmy account
2. Change email
3. Try to verify email while still logged in to lemmy account

### Technical Details

Browser console errors: None

### Version

BE: 0.19.5

### Lemmy Instance URL

programming.dev

**Comment by dessalines** [comment]
I don't understand what's going on.

- You current email is verified (as you're logged in correctly)
- You changed your email
- It sent you a new verify link
- The new link does nothing, because you've already been verified.

Is that correct? I'm don't think we should unverify a person because they change their email.

**Comment by asudox** [comment]
> I don't understand what's going on.
> 
>     * You current email is verified (as you're logged in correctly)
> 
>     * You changed your email
> 
>     * It sent you a new verify link
> 
>     * The new link does nothing, because you've already been verified.
> 
> 
> Is that correct? I'm don't think we should unverify a person because they change their email.

Isn't that a verification to prove that the email indeed belongs to the account it's assigned to?

And I still don't understand why the verification works when the user is not logged in but not when the user is logged in.

**Comment by Nutomic** [comment]
The `email_verified` field is checked on login (depending on instance configuration). So if we set `email_verified = false` after changing the email, you would not be able to login anymore until the new email is verified. Seems like this would require a separate db field `account_verified`.

**Comment by asudox** [comment]
> The `email_verified` field is checked on login (depending on instance configuration). So if we set `email_verified = false` after changing the email, you would not be able to login anymore until the new email is verified. Seems like this would require a separate db field `account_verified`.

Oh, that's why

**Comment by dessalines** [comment]
We have an `email_verified` column on the `local_user` table, but we don't unverify users when they change their email. 

The entire point of verification is as part of a signup procedure (sites might require it), so you could break your ability to log in if we unverified emails. So this is probably a nofix.

**Comment by asudox** [comment]
> We have an `email_verified` column on the `local_user` table, but we don't unverify users when they change their email.
> 
> The entire point of verification is as part of a signup procedure (sites might require it), so you could break your ability to log in if we unverified emails. An `account_verified` field doesn't serve any purpose for us. So this is probably a nofix.

Got it. Closing this issue then.
