### ISSUE TITLE
[Bug]: some communities seem unable to load

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy#5117]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Some communities with underscores in the ID seem broken.

### Steps to Reproduce

1. Go to search page: https://programming.dev/search?q=data+structures&type=Communities&listingType=Local&page=1&sort=TopAll
2. Click on [Data Structures and Algorithms](https://programming.dev/c/data_structures)
3. The server returned this error: couldnt_find_community

### Technical Details

Discussion here https://programming.dev/post/20515601 with additional examples 

### Version

0.19.5

### Lemmy Instance URL

https://programming.dev/c/data_structures

**Comment by Nutomic** [comment]
Probably also due to broken db indexes on programming.dev, same as #5074 and #5077

**Comment by Nothing4You** [comment]
broken index on the community table was confirmed: https://programming.dev/post/20515601/12803517
