### ISSUE TITLE
Use vertical import style (one item per line) in rustfmt to reduce merge conflicts

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#5119]
In my opinion, resolving merge conflicts is a bigger inconvenience than seeing tall imports.

**Comment by Nutomic** [comment]
Make a pull request to see how it looks, and we can discuss it there.

**Comment by Nutomic** [comment]
Imo this is not really a problem, if there are import conflicts they are quick to resolve with editor tools and cargo fmt.
