### ISSUE TITLE
Allow using newer version of AGPL by specifying "AGPL-3.0-or-later"

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy#5133]
In #5130, it was implied that "AGPL-3.0-only" is the license identifier that matches what we're currently doing. I looked at the AGPL text, and this seems to be correct, as I could only find a part that says the program needs to specify in order to allow using any future versions or using future versions allowed by a specified entity. Lack of ability to use a future version could get messy.

We might need to get contributors' permission before switching to "or-later".

**Comment by Nutomic** [comment]
1. Changing the license of an open source project requires approval of every single person whos code it contains. Thats probably dozens of people, and if anyone disagrees or is unreachable, we need to rewrite their code. Lots of work for no real benefit.
2. We dont know which terms a future AGPL 4.0 may have. In theory it could change the whole license text and remove important protections. I am not willing to license my contributions under such uncertain conditions.

**Comment by DraconicNEO** [comment]
> 1. Changing the license of an open source project requires approval of every single person whos code it contains. Thats probably dozens of people, and if anyone disagrees or is unreachable, we need to rewrite their code. Lots of work for no real benefit.
> 
>     2. We dont know which terms a future AGPL 4.0 may have. In theory it could change the whole license text and remove important protections. I am not willing to license my contributions under such uncertain conditions.

Agreed, we never know what the future holds, so we can't be sure 4.0 will be better or worse. 3.0 is already very good as it is. Better than 2.0. Should keep it as it is unless necessary otherwise.

**Comment by dullbananas** [comment]
The bad update problem can be solved with a comment saying something like this above the license field in Cargo.toml: "dessalines and nutomic can decide which future versions of the GNU Affero General Public License can be used" ("can decide..." is copied from AGPL)

**Comment by DraconicNEO** [comment]
> The bad update problem can be solved with a comment saying something like this above the license field in Cargo.toml: "dessalines and nutomic can decide which future versions of the GNU Affero General Public License can be used" ("can decide..." is copied from AGPL)

What if dessalines and nutomic aren't the maintainers anymore at such a future point? What if it's someone else who might not have the passion for open source that the current maintainers and contributors do now, and thus will choose aspects that can compromise the integrity of the project.

Why not just not change the license. GPL-3.0 is fine right now. Open-source License changes are hard to pull off and that is kind of the point because of the protection it offers in and of itself.

**Comment by dessalines** [comment]
> We dont know which terms a future AGPL 4.0 may have. In theory it could change the whole license text and remove important protections. I am not willing to license my contributions under such uncertain conditions.

Agree with this, the "or-later" could be anything, and might include things that turn out to not be that great. Not even sure when they're going to release the next iteration.
