### ISSUE TITLE
[Bug]: Intermittent CI error for federation tests: failed to fetch deeply nested comment.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#5145]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

We're getting a frequent error on our CI log related to fetching deeply nested comments:

https://woodpecker.join-lemmy.org/repos/129/pipeline/9741/21#L457

It only seems to happen intermittently on 2 / 3 CI machines. I looked into the logs and can't figure out whats causing it, but don't see any issues. 

### Steps to Reproduce

1. Run the CI
2. Sometimes get the error above

### Technical Details

See CI build log above

### Version

main

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/5152
