### ISSUE TITLE
Expand rating system by adding super like, and super dislike, and possibly neutral response making it better version of rating out of five.

### ISSUE THREAD

**Issue by vertigofilip** [LemmyNet/lemmy#5161]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

It is just a feature I would like to see.

### Describe the solution you'd like.

Neutral response is going to work just like normal like, and dislike, and super like, and super dislike would have some sort of cooldown for each user making them special option for exceptional posts, or comments..

### Describe alternatives you've considered.

Option for double like/dislike also with cooldown would make 

### Additional context

This feature requires proper backend support before it could be implemented in UI. It is inspired by 5 star rating system in older versions of YouTube.

**Comment by dessalines** [comment]
Not interested in adding anything besides like / dislike. In the future we might add #2541 , but those won't affect sorting.
