### ISSUE TITLE
[Bug]: RSS XML is double encoding in <title> tag and should not.

### ISSUE THREAD

**Issue by gnatbandanna** [LemmyNet/lemmy#5171]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Please forgive if this is already known - I did not see this exact issue.

RSS feeds, for example [here](https://lemmy.ml/feeds/c/privacy.xml?sort=Active), are providing double-encoded html/xml:

```
<title>Polling the group: what do y&amp;#x27;all know about the Orion browser from Kagi?</title>
```
While it should be providing either of these:

```
<title>Polling the group: what do y'all know about the Orion browser from Kagi?</title>

<title>Polling the group: what do y&#x27;all know about the Orion browser from Kagi?</title>
```

This causes interpretation issues with RSS readers. Please also see this FreshRSS [post](https://github.com/FreshRSS/FreshRSS/issues/6979) for more info.

### Steps to Reproduce

1. Look at any feed.xml that tries to use `'` or `"` etc encoding and find an example.
2.
3.

### Technical Details

n/a

### Version

BE: 0.19.3-6-g86e4cb214

**Comment by Nutomic** [comment]
[Here is the code](https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/feeds.rs#L569. It [removes some invalid xml characters](https://github.com/LemmyNet/lemmy/blob/main/crates/routes/src/feeds.rs#L98) and then [replaces some characters](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/src/utils/markdown/mod.rs#L27). The rss library itself [doesnt do any escaping](https://github.com/rust-syndication/rss/issues/167). I also confirmed that the post title you mention is not escaped in the database. 

The [test_sanitize_html function also works as expected for that title](https://github.com/LemmyNet/lemmy/pull/5174). So I have no idea where this double encoding might come from.
