### ISSUE TITLE
[Bug]: /community/random endpoint always returns 404

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#5183]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When I call `/api/v3/community/random` I am always getting 404 with no response body.

### Steps to Reproduce

Example requests:

```sh
curl https://lemmy.ml/api/v3/community/random?type_=All
curl https://lemmy.ml/api/v3/community/random
curl https://lemmy.zip/api/v3/community/random?type_=Local
```

### Technical Details

N/A

### Version

0.16.6

### Lemmy Instance URL

lemmy.ml, lemmy.zip

**Comment by aeharding** [comment]
Is it possible that this didn't make the cut for the 0.19.6 release? If it will be in a future release feel free to close it!

**Comment by Nothing4You** [comment]
doesn't look like it was backported to 0.19, it's only in the main branch, which is for 0.20.
