### ISSUE TITLE
[Bug]: CORS issues with 3rd party web frontends when setting cors origin to * in config.json

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy#5185]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I noticed that there was a change in the default settings of the config.hjson and added it to our config:

https://github.com/LemmyNet/lemmy/blob/05c3eae016ffb4b96d7d2468482a93e704986d91/config/defaults.hjson#L125

However adding this makes the login in 3rd party web-frontends fail with CORS issues, kinda the opposite of what one would expect.

### Steps to Reproduce

1. Add `cors_origin: "*"` to lemmy config.hjson
2. Restart backend
3. Try to log into 3rd party web-frontends fails

### Technical Details

Running the official containers in a custom Podman setup.

### Version

BE 0.19.6

### Lemmy Instance URL

https://slrpnk.net/

**Comment by Nutomic** [comment]
This was changed in https://github.com/LemmyNet/lemmy/pull/4095. Note that `*` is only the example value, but the default is `None`. As far as I can tell the default behaviour was not changed.

**Comment by poVoq** [comment]
Why is this broken example value given in the official repo though?

**Comment by dessalines** [comment]
It shouldn't be broken, although you could look at the [logic in the function](https://github.com/LemmyNet/lemmy/blob/main/src/lib.rs#L339).

What would a good example be for that column? I can just remove the doku example for that setting also, if the default `unset` works better.

**Comment by Nothing4You** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

wildcard does not work with credentials, which is probably the main issue.

actix docs also warn about this: https://docs.rs/actix-cors/latest/actix_cors/struct.Cors.html#method.send_wildcard

i think this should be a list type in the configuration though, as having multiple frontends requires adding multiple allowed origins.

when it comes to the documentation example, maybe something like `photon.lemmy.tld, voyager.lemmy.tld`?

**Comment by dessalines** [comment]
Seems like the default configuration allows any origin already. I don't know that there's any difference between actix's `allow_any_origin` and `send_wildcard` anyway.

I'll make a PR to have `*` just use the default behavior.

**Comment by Nothing4You** [comment]
> When all origins are allowed and `send_wildcard` is set, `*` will be sent in the `Access-Control-Allow-Origin` response header. If `send_wildcard` is not set, the client’s `Origin` request header will be echoed back in the `Access-Control-Allow-Origin` response header.

The difference is that with `*`, browsers will not allow including credentials, while returning the `Origin` request header value dynamically per request will allow them to be included.

**Comment by dessalines** [comment]
In that case it sounds like `*` is going to cause more problems than just `allow_any_origin()`, so hopefully my PR above will handle that case.

**Comment by Nothing4You** [comment]
agreed
