### ISSUE TITLE
[Bug]: Failed to update community stats: column cl.post_id does not exist

### ISSUE THREAD

**Issue by makotech222** [LemmyNet/lemmy#5186]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Updating to 0.19.6. Looks like this postgres function (public.community_aggregates_activity) references CommentLike.PostId and wasn't updated when that column got dropped.

### Steps to Reproduce

1. Run lemmy

### Technical Details

Running in docker locally in windows.

### Version

0.19.6

**Comment by makotech222** [comment]
Possibly causing https://github.com/LemmyNet/lemmy/issues/5182

**Comment by Nutomic** [comment]
It looks like the triggers `community_aggregates_activity` and `site_aggregates_activity` were not moved to replaceable_schema yet. Could also be related to #5179.
