### ISSUE TITLE
Add some form of "loading" indicator for buttons for delete, remove, etc.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#519]
When you click on the buttons for delete, remove, etc at the bottom a post or comment, there is no feedback while the operation goes out to the API, which could take seconds on a slow connection. This has made me think that the click didn't go through before, prompting re-clicks which I imagine can cause problems. There should be a loading indicator while these operations are in progress.

The same is true for editing comments, which just closes the textbox on submitting and eventually changes the displayed comment. The edit prompt for posts are fine and actually show a loading indicator on the submit button.

**Comment by dessalines** [comment]
Sounds like a good first issue.

**Comment by Nutomic** [comment]
@dessalines you need to label it then ;)

**Comment by Charleshthomasiii** [comment]
Can I take a crack at this?

**Comment by dessalines** [comment]
Sure thing, just look at the other loading indicator examples in the code, should be straightforward.

**Comment by dessalines** [comment]
Also as part of this ticket, try to get comment loading indicators working. This has actually been pretty difficult.

**Comment by dessalines** [comment]
This isn't really necessary any more, with the increased DB speed.
