### ISSUE TITLE
Need a different way to mark post/comments as read for instances with downvotes disabled

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy#5211]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Yes. In instances with downvotes enabled I can just upvote or downvote everything I see, as a way to remind myself that I've already read it. But on instances with downvotes disabled, I can't use the upvote feature to mark content as read since it would imply endorsement. I need an alternative way to track mark content as read.

### Describe the solution you'd like.

I would like to see a "Mark as Read" feature implemented in Lemmy. This could work as follows:

1. For posts, the system could automatically mark a post as read when a user visits the post's page or clicks on the post's title from a list of posts.
2. For comments, the system could display a new toggle icon with each comment. Clicking on the icon would mark the comment as read.

### Describe alternatives you've considered.

I haven't considered any alternatives, as I'm not aware of any existing solutions for this issue.

### Additional context

No additional context provided.

**Comment by Nothing4You** [comment]
that would be a frontend issue, this is already possible via API.

**Comment by dessalines** [comment]
That's correct. We already have a MarkAsRead action in the API.
