### ISSUE TITLE
Add crossposts in the `post/list` endpoint to allow frontends to do deduplication

### ISSUE THREAD

**Issue by db0** [LemmyNet/lemmy#5215]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

Post deduplication is possible but costsly and it could/should be made more feasible for frontends

### Describe the solution you'd like.

I would like the API endpoint /post/list to also provide the crosspost list on each returned post the way they are returned for each single post endpoint. This would allow UIs to utilize this information to perform deduplication or to do other fancier operations like combined comment sections from multiple posts in one deduplicated view. This would enable things [like this](https://lemmy.dbzer0.com/post/30138798)

### Describe alternatives you've considered.

One can poll each post appearing on the frontpage individually for its crosspost lists but that becomes too wasteful

**Comment by Nutomic** [comment]
Would it be enough to return the id of each crosspost, or the full PostView? That could result in a lot of data.

**Comment by db0** [comment]
The deduplication by post_url doesn't work if the posts are not in the same page of results though. It also doesn't quite allow the capability I suggested starting from the list (i.e. one will not be able to see how many total comments are in all the combined discussions about the url before opening it). 

I'm not certain what you mean about a "list of lists" in the sql however. Can you elaborate?

**Comment by dessalines** [comment]
Lists of lists means that joining a list of posts, each of which has its own cross-posts. If you look at our post view queries / objects, they never do this, and make sure each post only links to one item, not many, so we don't have to do massive join de-duplication.

This is something I'm probably not going to add because of the performance and joining issues. You'll just have to use the single GetPost to get information about cross-posts.
