### ISSUE TITLE
Webhook Notifications

### ISSUE THREAD

**Issue by fishcharlie** [LemmyNet/lemmy#5217]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

As the creator of [Echo](https://echo.rrainn.com) there is no good way to get user notifications to my server. The only method for doing this now is for me to send the user token to my server and make the API request myself. Which has a lot of security concerns with it (especially considering that tokens aren't tied to my application specifically and there is no way for a user to revoke my token).

### Describe the solution you'd like.

So being able on the clients device to be able to submit a request to the Lemmy server to forward all notifications to my server as webhook notifications would be super useful and improve the user experience.

### Describe alternatives you've considered.

- Sending users token to my server to query the notifications directly - Lots of security concerns here
- Better OAuth support for apps so I can get a safe token that is unique to my app and user that I can send to my server and query APIs directly on behalf of the user - Decided not to propose this because it seems like the LOE would be much greater than just starting with webhooks

**Comment by dessalines** [comment]
We're eventually going to add proper notifications via unified push / ntfy, which would work on all platforms. There's a few tickets for this: https://github.com/LemmyNet/lemmy/issues?q=is%3Aissue+is%3Aopen+notifications+label%3A%22area%3A+notifications%22

**Comment by fishcharlie** [comment]
@dessalines Awesome. That sounds good. I briefly looked at the `ntfy` documentation (not very in depth) and it looks like they do support some server to server forms of receiving notifications. So possibly I could just have my server subscribe to those? One of the things tho is it still requires a token on behalf of that user. So maybe my real problem is the security around those tokens.

I have a couple of operational requirements that require notifications to go through my server as opposed to direct to the clients device, which is really what I'm trying to figure out.

**Comment by fishcharlie** [comment]
@dessalines So that is different than what this feature request is. iOS applications don't really support push notifications except for using the APN service. Which in order to send notifications through, requires my specific certificate/key. Which my server has, but which can't be uploaded to Lemmy ntfy instances directly (due to security concerns).

It looks like there is a ntfy iOS app that users could download. But that wouldn't be integrated with my Lemmy iOS client, and would be a separate thing users have to download. It also looks like there is a way to [upload a Firebase key](https://docs.ntfy.sh/develop/#ios-app) and have ntfy proxy notifications through that to your iOS app. But that still requires uploading a private key to ntfy directly, which isn't plausible here.

Hopefully that makes sense. It just doesn't seem like this fits my use case and what I'm looking for here. Unless I'm totally missing something.

**Comment by Nutomic** [comment]
I think it makes more sense to implement notification support in plugins, then admins can choose the ones they want. I have some plans to start working on that.
