### ISSUE TITLE
Allow admin to choose any additional languages to be selected for newly registered users in addition to "Undetermined" and "English"

### ISSUE THREAD

**Issue by giorgi3092** [LemmyNet/lemmy#5234]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

I am running an instance for a specific country (Georgia) where people's browsers do not always carry the language information (a lot of people use English as their system/browser language). 

This means that when a new user signs up, their profile settings are set to "Undetermined" and "English" only so everything (which is literally everything) posted in language "ქართული" is not displayed. and it is very inconvenient to explain to the user to go to their settings and press Ctrl and look for "ქართული" and then posts will be displayed. 

### Describe the solution you'd like.

Allow admins from the admin panel to select languages that should be selected for every newly registered user.

I guess it should be very simple to do this. As it was explained to me:
"The default languages for creating a new user are taken from all the languages in your browser's Accept-Language header, then we add UNDETERMINED to it."

So maybe add a list of languages to admin panel that should also be added for a new user regisration.

### Describe alternatives you've considered.

Other way is to modify the code and maintain my own branch. I want to follow the official branch and not break upgrades.

**Comment by dessalines** [comment]
It should add *all* the user's browser languages, but yes I agree it'd be nice to be able to add a set of default languages besides undetermined for new users.

**Comment by Nutomic** [comment]
I made a change in https://github.com/LemmyNet/lemmy/pull/5235 so that new users also have the site languages which are configured under `/admin`. This way it has the same effect without an extra setting.
