### ISSUE TITLE
way to disable slur filter for non-English languages

### ISSUE THREAD

**Issue by DimensionalScoop** [LemmyNet/lemmy#535]
The slur filter removes words that are innocuous in other languages, e.g. the (very common) German word "weniger", meaning "less" or "fewer". This makes sense for English posts, but makes it very confusing to have a discussion in German.

**Comment by Nutomic** [comment]
Related to #440.

**Comment by Nutomic** [comment]
Übrigens hab ich bisher noch keine deutsche Diskussion auf Lemmy gesehen.

**Comment by dessalines** [comment]
Yup this will have to wait for proper multi-language support. In the meantime I can alter that regex to make sure it doesn't catch weniger.

**Comment by Porrumentzio** [comment]
This has been very frustrating as on Basque some of our verbs end with -dindu, and it's removed without reason. I even didn't know that that was a slur word in English, implementing this in the code is a very bad idea (in my opinion) for other languages (even on the same language, words should not be automatically removed IMO)

**Comment by Porrumentzio** [comment]
Hi! I see you removed some words and added others. Could this be optional on each instance (decides by administrators) or at least by language?

There will be part of words present in many other languages and this will create problems for sure

**Comment by dessalines** [comment]
No because that would be a really easy way to circumvent the slur filter. We'll take language conflicts with these on a case-by-case basis.

**Comment by Ashdemai** [comment]
> No because that would be a really easy way to circumvent the slur filter. We'll take language conflicts with these on a case-by-case basis.

This sounds really counter-intuitive when you have other tools to defederate from offending instances.

**Comment by Nutomic** [comment]
This issue is very old. The slur filter is already disabled by default, and instance admins need to enable it manually if they wish.
