### ISSUE TITLE
Traefik support

### ISSUE THREAD

**Issue by timboswell** [LemmyNet/lemmy#539]
As discussed in [this thread](https://dev.lemmy.ml/post/30134/comment/2229), it would be nice to include support for traefik as a reverse proxy. I have a working docker-compose which does the job, creating this issue for tracking the PR. 

The following traefik labels are the relevant ones: 
Lemmy container:
```
    labels:
      - "traefik.frontend.rule=example.org"
      - "traefik.port=8536"
```
Pictshare container:
```
    labels:
      - "traefik.frontend.rule=Host:example.org;PathPrefixStrip:/pictshare"
      - "traefik.port=80"
```

**Comment by timboswell** [comment]
What's the best branch to create a PR on?

**Comment by dessalines** [comment]
Any branch really, I'll rename the docker-file and put it in the right spot, naming it something like docker-compose.traefik.yml or something.

**Comment by timboswell** [comment]
docker-compose.traefik.yml added to dev branch

**Comment by jimmybrancaccio** [comment]
@timboswell Maybe I'm blind, but I can't find your `docker-compose.traefik.yml` file. Mind sharing it cause I'm having some trouble getting it working with Traefik as well. When trying to upload an avatar it keeps hitting my main router for Lemmy and not my router for pictshare. Thanks!

**Comment by dessalines** [comment]
Let me know if this needs re-opened.

**Comment by bmanturner** [comment]
Unsure where to find this example file

**Comment by jimmybrancaccio** [comment]
@bmanturner I could never find it either, but I spent some significant time trying to get this working in Traefik v2.x and could not. There was something specific in the Nginx config that I could not figure out how to "convert". Everything else was working except that. It was the part with the "nested" locations bit if I recall. I ended up giving up and just using the Nginx container and it's config and all worked just fine.

**Comment by Nutomic** [comment]
@jimmybrancaccio I think we had a nested location before for pictrs, but thats not needed anymore cause pictrs is routed through Lemmy now. So maybe your traefik config would work now.

**Comment by dessalines** [comment]
Iframely is the only thing then. The back-end doesn't need the nginx, but the front end still does fetch page titles from it:

`let res = await fetch(`/iframely/oembed?url=${url}`).then(res => res.json());`

**Comment by jimmybrancaccio** [comment]
Hrmm, if I can find some time I will try setting it up again. I know I said something about it in the Matrix channel, but that was a while ago. Perhaps this weekend if I have time I will give it a shot and update results here.

**Comment by ajitam** [comment]
This is the second issue I found on this project that gets `Closed` and actually no clear resolution is done.

Or I'm I missing something? and there is traefik support somewhere

ping @dessalines

**Comment by jimmybrancaccio** [comment]
@ajitam You may want to have a look at https://github.com/LemmyNet/lemmy-ui/issues/876#issuecomment-1590201024.

**Comment by ajitam** [comment]
0K, that is something. But (don't get me wrong) but if I see issue "Traefik support" in closed state I presume that "I can spin up lemmy using traefik" using the code the repo

**Comment by Kangie** [comment]
@ajitam see #3502
