### ISSUE TITLE
Create an alternative Lite frontend for no JS/CSS browsers

### ISSUE THREAD

**Issue by AndreVallestero** [LemmyNet/lemmy#554]
This would also make it ideal for people who use no-script or for people who simply prefer a lighter, faster alternative.

**Comment by dessalines** [comment]
The API is open, anyone is free to make a read-only / non-live-updating version.

**Comment by dessalines** [comment]
I'll close this here, but if anyone wants to make a read-only version, let me know and I'll link it.
