### ISSUE TITLE
Add admin contact form

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#556]
Peertube has this, and its very useful for all kinds of things. I also didn't get anything like spam from it on my Peertube instance so there is no real downside. It can even be used for reports until we have those implemented.

https://peertube.social/about/instance (click contact)

**Comment by StaticallyTypedRice** [comment]
In the same vein, we should look into implementing some sort of modmail system like on Reddit.

**Comment by dessalines** [comment]
The *About* stuff I wanted to be mostly in the sidebar, with the sidebar possibly linking to a post on /c/main for a longer document. 

This works not just for the main sub, but for every community as well, to have a longer info type document.

**Comment by dessalines** [comment]
This kind of server / instance specific info is exactly what the sidebar is for.
