### ISSUE TITLE
Suggestion: Remove full url's pic addresses from DB

### ISSUE THREAD

**Issue by mflsim** [LemmyNet/lemmy#591]
Change all url pic addresses (avatars, image upload) from "http://xxx.xxx.xxx.xxx/pictshare/pic.jpg" to "/pictshare/pic.jpg".

It's easier for migration or ip/domain change in the future.

**Comment by Nutomic** [comment]
From what I heard, domain change is not possible anyway once activitypub is working. So this change might not be worth doing.

**Comment by dessalines** [comment]
Right now I'm not forcing image posts, or any url post for that matter, to be cached in lemmy. Not only would a local image caching mean that every image gets duplicated everywhere, it also seems wrong bc I feel that a link aggregator should be agnostic when it comes to the type of content posted.

The front end actually does some wonky logic too, to determine whether that image is a pictshare on another domain, or on the same one, so it can do proper image thumbnail sizing.

**Comment by Nutomic** [comment]
Though it does make sense to proxy images, both for privacy and to prevent overloading smaller instances. Mastodon does that as well.

**Comment by dessalines** [comment]
There's a few columns at play here: 

- `user_.avatar_thumbnail` - this could probably be changed and set to the local one.
- `post.url` - I can't change this, it needs to be a full url
- `post.image_thumbnail` - This is currently correctly only storing the image hash id from pictshare.

**Comment by dessalines** [comment]
With federation now being implemented, it seems better to go the other way around: use the full urls in the DB, since federated users will have icon locations that are not local, and federated posts have image thumbnails that aren't local either.
