### ISSUE TITLE
In mobile view, replace the top menu with a proper mobile-like overlay drawer popped from the left or right

### ISSUE THREAD

**Issue by pioneer** [LemmyNet/lemmy#601]
The example overlay drawer can be found on the main page of React Material here - https://material-ui.com/. The drawer even looks great in desktop mode as well, though the primary scope of this ticket is the mobile view. In the desktop mode, everything looks and works perfectly.

Reason: IMO it's the most widespread approach to implement mobile menus now, just to look modern, apart from that it's 100% functional of course. The current menu looks slightly from the past, but that's not the only reason. The popped out menu in mobile view occupies space on the top and makes UI navigation slightly more difficult, as in order to return back to posts I have to scroll down a bit.

Not sure if it can be easily implemented, not a Bootstrap professional, but found this discussion with some examples - https://stackoverflow.com/questions/48996084/create-a-responsive-navbar-sidebar-drawer-in-bootstrap-4

**Comment by dessalines** [comment]
If someone wants to find a way to do this, go right ahead. The relevant component is `navbar.tsx`
