### ISSUE TITLE
Invalid value in PostView.url

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#602]
I noticed during my testing for federation that `PostView.url` can sometimes have a value of `Some("")`. That obviously doesnt make sense and causes problems. I presume that this happens because of entering an url when creating a post, and deleting it again.

**Comment by dessalines** [comment]
Hrm ya that's probably it. IThis is most likely a front end thing, I think there's other places in the code I have to do checks for this anyway.

**Comment by Nutomic** [comment]
Ideally you should also clean up the existing data in the db, or we will run into problems with that later.

**Comment by Nutomic** [comment]
We probably need a database migration for this as well.

**Comment by Nutomic** [comment]
This is not fixed, we still have many posts on lemmy.ml with empty URL. Try running the following query:
```
select id, name from post where url='';
```

So we need to do the following:

- [ ] Write a migration to replace all empty URLs in database field post.url with `null`
- [ ] [Remove compatibility code](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/objects/post.rs#L73)

**Comment by dessalines** [comment]
This also needs to go along with #1385, which is a critical bug IMO because invalid post urls can break the UI.
