### ISSUE TITLE
Some external pictures are shown incorrectly

### ISSUE THREAD

**Issue by pioneer** [LemmyNet/lemmy#613]
Here's the URL I'm experiencing this - https://dev.lemmy.ml/post/30964
![Выделение_089](https://user-images.githubusercontent.com/200538/78073056-d694d700-73a8-11ea-83f5-8b56e804c97d.png)
The URL of the picture is probably https://pasteboard.co/IWPyqiz.png, and the issue is maybe because such Pasteboard URLs are not really PNGs but rather HTML having a PNG inside.

**Comment by dessalines** [comment]
Why does pasteboard use a png extension for a webpage?

**Comment by pioneer** [comment]
No idea but it's weird of course. Just tested this snippet and seems it works:
```
<img src="https://pasteboard.co/IWPyqiz.png" onerror="this.src = 'https://image.shutterstock.com/image-vector/default-ui-image-placeholder-wireframes-600w-1037719192.jpg'">
```

**Comment by dessalines** [comment]
This should be fixed by `pict-rs`.
