### ISSUE TITLE
Cyrillic text looks differently with Journal and United themes

### ISSUE THREAD

**Issue by pioneer** [LemmyNet/lemmy#614]
Seems the "News Cycle" and Ubuntu fonts used in the themes mentioned, don't support cyrillic letters properly.
![Выделение_091](https://user-images.githubusercontent.com/200538/78079238-612f0380-73b4-11ea-8ca9-9fbcb823f436.png)

**Comment by dessalines** [comment]
You can change them if you like, or create a theme that works better with cyrillic.

**Comment by pioneer** [comment]
It worked before, I can remember those themes were using just the system font. This has changed recently. Overall, I tend to think that Lemmy-wide themes should use as universal fonts as possible, but that may not be a very easy thing to do sometimes.

**Comment by pioneer** [comment]
Even if I create a theme, it doesn't look like there's an easy way to use it on the main Lemmy instance anyway.

**Comment by dessalines** [comment]
The themes do have their own specific fonts. And yes, if you create a theme, its available on all instances.

https://dev.lemmy.ml/docs/contributing_theming.html

**Comment by Nutomic** [comment]
What dessalines means is creating a theme and getting it into Lemmy by making a pull request ;)

Or you could change an existing theme in the same way.
