### ISSUE TITLE
Allow Users To Hide Their Post History & Visually Completely Disable Upvotes Site-wide

### ISSUE THREAD

**Issue by grravity** [LemmyNet/lemmy#623]
Hoping to see an implementation to allow users to hide their post history from being visible to other people.

Also suggesting the ability to disable seeing upvotes, and even being able to upvote site-wide as a client side option. It's like being able to disable likes on Twitter, and is a thing I personally (and know many others) really dislike, as it gives people something to gauge their post worthness against others. As a super basic example if Joe gets more likes (upvotes) than Crystal, Crystal may felt like she did something wrong, may feel less important, etc. Can be mentally frustrating for some. 
This is not an issue that exists within imageboards, where there are generally no likes, everything is sorted by new (or bump order, which is similar but imo different to likes/upvotes), and I'm not saying disable them for everyone, but just allow users to hide them essentially.
Imo it'd allow for a Reddit-style experience, but with a less socially adept mindset for users who enjoy that more. Focusing more on the content, rather than "karma" or "likes/upvotes".

**Comment by Nutomic** [comment]
This is definitely something I would like to see. So far we only considered hiding votes globally but that might be too much. A user option seems like a good compromise.

**Comment by dessalines** [comment]
Lets split these into two issues.

**Comment by dessalines** [comment]
I'm not opposed to this, but there is at least one negative of user history hiding: trolls could enable that option and not moderators or instance owners easily see their history. Would make it a lot more difficult to root out trolls.

**Comment by Nutomic** [comment]
It wouldn't be that hard to show the full history only to site admins. Mods should only see a history of comments that were made in their community(s).

**Comment by dessalines** [comment]
There are **many cases** where a mod needs to see activity in other communities. 

Some of the reddit mod tools even aggregate a lot of this data, and its def helpful to see stuff like : *80% of this user's comments are in /r/unpopularopinion, with a score of 468*.

**Comment by grravity** [comment]
I think a mod should be able to see a users post activity in that specific community they're moderating.
Maybe allow the moderators to see a percentage and score of what they generally post in, alongside an average score of all their posts. This is fair. But no need imo to force users to show their entire post history to all users.

**Comment by dessalines** [comment]
It would've been **really useful** to see your post history, considering you just used an ableist slur on another ticket.

**Comment by Nutomic** [comment]
If all mods can see the full history of all users, the option becomes almost useless. Any user could just create a community, become a mod that way and then see the full history of all users.

**Comment by dessalines** [comment]
Ya.... I think the best way to handle this is through #187 (private communities), in which case your history on those subs wouldn't be visible if the `only mods can view` option is checked. That or the invite-only instance thing, where no one would be able to create an account at all unless they go through screening.
