### ISSUE TITLE
Break out API files into their own modules.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#625]
The API files are getting too long, best to break them out into their own modules, with the files being the specific endpoints.

**Comment by Charleshthomasiii** [comment]
I'm trying to see the hierarchy. Do you mean that comment, community, mod, post, site, and user become modules and then each struct and its functions are in its own file?

**Comment by dessalines** [comment]
Exactly. But we don't wanna do any reorgs like that until federation is mostly done, because there's lots of changes on the federation branch in each of those files, and the merges aren't gonne be fun.

Pinging @Nutomic on this too.

**Comment by Nutomic** [comment]
Yep definitely don't try to do this now.

**Comment by dessalines** [comment]
This is done.

**Comment by Nutomic** [comment]
Not really? API files might be a bit shorter now, but they are still 700+ lines.
