### ISSUE TITLE
Include stack trace with errors

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#628]
Otherwise we only get the error message, with no indication where exactly it came from. Makes debugging very hard. Particularly here, and maybe also in other places: https://github.com/LemmyNet/lemmy/blob/master/server/src/websocket/server.rs#L458

https://stackoverflow.com/questions/42275777/how-to-trace-the-cause-of-an-error-result/42275876#42275876

**Comment by dessalines** [comment]
Not totally positive, but this might work too. From [here](https://rust-lang-nursery.github.io/failure/error.html)

`println!("{}, {}", error.cause(), error.backtrace())`

**Comment by dessalines** [comment]
Is this still needed. Also we still need to migrate to anyhow : #689

**Comment by Nutomic** [comment]
I think this works fine now.
