### ISSUE TITLE
Seperate config files

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#630]
As I mentioned in #629, I think we should create two seperate config files:

### Admin config

This one should hold things that are essential for Lemmy to function, and cant be applied without a restart. It can only be edited over ssh, and contain the following items:

- database config
- email config
- domain, ip:port binding
- federation settings
- setup items

### Site config

This one should hold settings that can be applied directly from the frontend, and not require any restart. Things like:

- rate limits
- site name, description etc (no reason to put that in the db)
- anything related to moderation

**Comment by dessalines** [comment]
I'm really against this, I hate it when programs break out their settings files, and require an entire folder hierarchy. It makes setup a pain. The current `config.hjson` already has sections, and has its own hierarchy, no need to break this out into separate files. 

We should be able to apply those settings without a restart, all it takes is figuring out how to get this to re-initialize when a new config is saved:

```
lazy_static! {
  static ref SETTINGS: Settings = {
    match Settings::init() {
      Ok(c) => c,
      Err(e) => panic!("{}", e),
    }
  };
}
```
