### ISSUE TITLE
Browser storage

### ISSUE THREAD

**Issue by Nicedude-git** [LemmyNet/lemmy#631]
Hi.

I am new to this github thing so apologies if not posting in right place.

Been testing this software for a few days and it looks promising. 

What i find it needs is some sort of autosaving when posting. For instance, sometimes when submiting a post and for whatever reason the submission fails, when reloading the page all the text already entered is gone, and got to redo the post from scrach, which may be frustrating. 

Also i love the no email needed for registration feature, though i fear this could open an attack vector from spammers or malicious users, so i was thinking maybe a captcha would help to counter this (i am by no means advocating forcing users to register with email). 

Hope you consider this. 

Cheers.

**Comment by dessalines** [comment]
> For instance, sometimes when submiting a post and for whatever reason the submission fails, when reloading the page all the text already entered is gone, and got to redo the post from scrach, which may be frustrating.

It wouldn't navigate unless the post went through, could write some steps to reproduce this?

From at least version `v0.6.45` it should also come up with a prompt if you try to navigate anywhere else, after editing a post. 

Some anti-spam / captcha discussion is here: #124

**Comment by Nicedude-git** [comment]
> > For instance, sometimes when submiting a post and for whatever reason the submission fails, when reloading the page all the text already entered is gone, and got to redo the post from scrach, which may be frustrating.
> 
> It wouldn't navigate unless the post went through, could write some steps to reproduce this?
> 
> From at least version `v0.6.45` it should also come up with a prompt if you try to navigate anywhere else, after editing a post.
> 
> Some anti-spam / captcha discussion is here: #124

Sometimes the post just doesn't go through and the little wheel keeps circling forever. In those case i refresh the page and everything is gone and the post wasn't posted.

Auto draft would be useful as well in cases when writting long posts and something happens, for instance the browser crashes.

I have found such festure very useful in forums, gmail, discourse, etc.

**Comment by dessalines** [comment]
I wish there was some way to reproduce, because I've never seen this. 

As far as the save / load draft, this is doable using browser storage. Would you rename this ticket to that?

**Comment by Nicedude-git** [comment]
Hello.

The prompt when navigating away from the page only occurs when clicking a link. If i reload the page, the promt is gone. And the post is gone too. Is it possible to make the post not to go away when reloading or the browser crashes or something like that? This is a very useful feature when writing long posts to find your post is not gone if something happenned (for instance if the page reloaded after switching tabs).

**Comment by dessalines** [comment]
> The prompt when navigating away from the page only occurs when clicking a link. If i reload the page, there is no prompt.

Apparently this is because react's browser-routing blocker that I used for this, doesn't account for page reloads, only router navigation. Covering page reloads will require some hacky solution that I'll have to see what people did some other time.

I still think its a good idea to do browser storage drafts. Could you add an issue for the page reload not being blocked when there's a form filled?

> PS: still getting the site stuck on some actions, such as submitting post or going to the main page. The circle keeps circling forever.

I can't reproduce this, so the next time it happens, if you're able, please right-click inspect page, and send me your whole console dump. Also give me the version you're seeing this with, at the bottom of the main page.
