### ISSUE TITLE
Back end code cleanup: unwraps, is_some, and is_ok

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#639]
Grep all the instances of unwrap, is_some, is_ok, is_err, and prefer using match or if let.

**Comment by niniack** [comment]
From my understanding of match (new to rust!), it'll need specific cases and how to handle that. Curious to see if I can take a crack at this, any suggestions? Is this a good first issue?

**Comment by dessalines** [comment]
Yep this would be a good issue. Basically any unwraps / the above listed can crash the program. Sometimes they're unavoidable, but we wanna get rid of as many of these as we can.

**Comment by niniack** [comment]
Makes sense about the crashing. How would you suggest going about finding the relevant cases and their handling for match? Any sort of starting point or literature would be awesome!

**Comment by dessalines** [comment]
Using grep. There are lots of correct examples of match and if let in the code currently.
