### ISSUE TITLE
Automatically publish new builds to Docker Hub

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#646]
It would be very useful if all CI builds were automatically pushed to hub.docker.com. In particular, tagged releases should be pushed as `dessalines/lemmy:release-name`, and branches as `dessalines/lemmy:branch-name`. 

This is a bit tricky cause our current CI does not use Docker, so we either need to rewrite that, or add another build.

We also need to make sure that the version shown in the footer of the page is accurate (right now it only shows the last release, not the commit hash or branch).

**Comment by dessalines** [comment]
https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

**Comment by NicolasCARPi** [comment]
Note that you might also want to look at doing that with github actions. You even have something made by Docker ready to go: https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by dessalines** [comment]
Been working on this for a little bit to free up my dev machine from builds.

Docker caching unfortunately was even slower than not caching (for some reason saving and loading took like 10+ minutes.

- No caching, 18 minutes - https://travis-ci.org/github/LemmyNet/lemmy/builds/711326298
- With Caching, 25+ minutes https://travis-ci.org/github/LemmyNet/lemmy/builds/711333477

**Comment by dessalines** [comment]
@asonix 

I'm also blocked in this currently, because it looks like the tests in our `federation-test` folder fail, if you use `cargo build --release` instead of `cargo build`, you get invalid signature errors:

```
lemmy-beta_1      | [2020-07-24T14:26:35Z DEBUG lemmy_server::apub::extensions::signatures] Verifying with key -----BEGIN PUBLIC KEY-
----
lemmy-beta_1      |     MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA08uWzLsAkYT3ZwAmloFL
lemmy-beta_1      |     9XueC87HixJZOwcEl4/9gtL/oDuXQ4muWpmRBYC1a2Bn0WFlTR4b2pek6eYYOp+j
lemmy-beta_1      |     CjsPzYurxrCXL9S1eK5GHFsOG0kg9b8XalOP0ETdOp3dRGok3cMNV5Fshqj4lQXW
lemmy-beta_1      |     UIfBIAigMwp+QDn+iXNOLyTw0AG8dpB7ajDi/FqHHSSoD5Bhoq6+5YHsO/8vUCB2
lemmy-beta_1      |     ahtzFLqWXwXDBhq3/KTcoVP6SbpcsqZK1j9hO215J6Dq7DUGHKBkjMzHl/bBMguC
lemmy-beta_1      |     Q20pivsB/YRpEUpiqehyIlfbmrZqm0q3e0uwLg5M5trqsKDfFsiOSgVqBJJeZXpj
lemmy-beta_1      |     gQIDAQAB
lemmy-beta_1      |     -----END PUBLIC KEY-----
lemmy-beta_1      |     , message (request-target): post /c/main/inbox
lemmy-beta_1      |     (created): 1617114692
lemmy-beta_1      |     (expires): 1617192837
lemmy-beta_1      |     content-type: application/json
lemmy-beta_1      |     digest: SHA-256=neQzGSNKHfrNrBIz8Oi8EDKXgG/8EQYGZ7CE9aCDGXc=
lemmy-alpha_1     | [2020-07-24T14:26:35Z DEBUG lemmy_server::apub::activities] Result for activity send:
lemmy-alpha_1     |     ClientResponse HTTP/1.1 500 Internal Server Error
lemmy-alpha_1     |       headers:
lemmy-alpha_1     |         "cache-control": "public, max-age=3600"
lemmy-alpha_1     |         "date": "Fri, 24 Jul 2020 14:26:35 GMT"
lemmy-alpha_1     |         "content-type": "text/plain; charset=utf-8"
lemmy-alpha_1     |         "content-length": "43"
lemmy-beta_1      | [2020-07-24T14:26:35Z ERROR actix_http::response] Internal Server Error: LemmyError { inner: ErrorMessage { msg:
"Invalid signature on request: /c/main/inbox" }
```

You can verify this by changing to  `cargo build --release` in `federation-tests/run-tests.sh`

**Comment by asonix** [comment]
strange... I can take a look at that but not until later
