### ISSUE TITLE
Implement integration tests for federation

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#658]
Dessalines suggested to do this in Typescript + Jest so we can reuse some of the API code from the frontend. 

Here is an example for a basic test case:

1. Execute ./run-federation-test.sh
2. Compile and run the integration test
3. Login and create a post on instance alpha
4. Search the post id and make sure it returns the correct post
5. Probably wipe the db

**Comment by dessalines** [comment]
Okay I just added this to the federation branch. To test:

```
cd ui
yarn api-test
```

The file to write the tests in is at `ui/src/api_tests/api.spec.ts`

**Comment by Nutomic** [comment]
Fixed in 035532512afe934ef9661e3e9d77cbd59fe4edb1.
