### ISSUE TITLE
Add activity table to diesel.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#659]
- [x] Add activity table to diesel.
- [x] Make sure all inbox posts create a row there.

**Comment by Nutomic** [comment]
This is for the IDs for Activitypub activities? In that case it needs to be populated in apub::activities, the inbox doesnt really need it (yet).

**Comment by dessalines** [comment]
I added a DB table a while back, mainly used for logging, but that every local and federated action should insert to. It's basically just an id, user ID, local, and jsonb column.
