### ISSUE TITLE
Find a good .rustfmt.toml 

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#661]
It'd be a good idea to copy one from another project, I'd be surprised if there wasn't a good somewhat standard one floating around.

The only thing I want to keep is `tab_spaces=2`.

**Comment by Nutomic** [comment]
Here are some good options to format imports (nightly only for now):
```
imports_layout="HorizontalVertical"
merge_imports=true
reorder_imports=true
```

**Comment by Nutomic** [comment]
Gonna close this because our current config seems fine.
