### ISSUE TITLE
Email not sending HTML.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#666]
Emails broken: https://dev.lemmy.ml/post/32098/comment/4019

- It could be an issue with the openssl on that openssl-bundled rust image.
- We did refactor that send email code, maybe its not sending correctly.
- The html does seem fine in the message.

**Comment by Nutomic** [comment]
In the email it definitely seems broken, cause I don't think that string `--5Z04...` is supposed to be there, and especially not in the middle of the headers. That's why the content-type header is ignored.

**Comment by dessalines** [comment]
Found this one.

**Comment by dessalines** [comment]
https://github.com/lettre/lettre/issues/389
