### ISSUE TITLE
CSS classes for vertical comment lines on the left

### ISSUE THREAD

**Issue by pioneer** [LemmyNet/lemmy#667]
The colour lines on the left of a comment that are supposed to distinguish nested comments by their level are currently applied using the `style` attribute, so they are hardcoded and override any theme settings. A theme should be able to change those colours accordingly, so the vertical lines should have CSS classes instead of hardcoded styles.

This is a continuation of the discussion from here https://dev.lemmy.ml/post/30493/comment/3870

**Comment by pioneer** [comment]
After some investigation, it appeared to be less straightforward than it looked initially. A very rough and dirty implementation can be found here https://gist.github.com/pioneer/ba905f6e427bdd898c934d52bc5c39c5, but it raises questions.

Seems many if not all current themes redefine the border style of comments, including the left border, so the original approach with the `style` attribute makes practical sense, otherwise, no colour for the left border would be applied at all. So putting the `comment-depth-N` styles into `main.css` won't work with the themes we have. I only see the option to take care of all existing themes and preprocess them somehow, so this means we won't be able anymore to just simply grab another theme from https://bootstrap.build/, a theme has to be manually checked for not overlapping with our styles before including. Well, some of the existing themes use fonts that don't support some languages (i.e. at least I'm aware of Cyrillic issues, and I believe every **official** Lemmy theme should have as few issues as possible), so maybe it's a good idea anyway to have the themes preprocessing step before including it, but it requires discussion and, if the decision is made, constant effort on every theme change/inclusion.

**Comment by pioneer** [comment]
Another less controversial questions would be:

- since there are 6 iterating colours, could someone please suggest what's the best place to put it as a constant in the Inferno code?
- those 6 colours, not sure if it's good or bad to have exactly 6 of them. I'm personally ok with 6, but ideally, themes should be able to redefine that number. I don't know if it's realistic for a theme to be able to iterate through an arbitrary number of colours using CSS only, but maybe it could be partly achieved with adding another class like `comment-depth-N`, this time with a real depth value, not with `depth % 6`. Since it could be not so easy to implement an ideal solution, and since it doesn't look very important these days, I think it could be postponed for a while but any ideas are welcome.

**Comment by dessalines** [comment]
Sorry I've been really into federation work this past week, so I  haven't had time to chime in on much else.

This could be done to work for all themes by:

- Removing the colors from `utils.tsx`, putting them in `main.css`
- Adding a `comment-depth-N` to `main.css`, with a manual `border-left: 2px , with the color`
- Changing the comment component to work with it

**Comment by pioneer** [comment]
That's exactly how it's done in the gist from the first comment above (except the removal of the colors from `utils.tsx`, but it's rough and dirty anyway). What I'm trying to say is that it won't help, as almost every theme will redefine the border style.

**Comment by dessalines** [comment]
Add `!important` to your custom `border-left` style if its not working, but I doubt it needs that since main.css should be overriding any of the themes loaded.

**Comment by pioneer** [comment]
Already added `!important` as you can see in the gist above. Found why it does not work here https://github.com/LemmyNet/lemmy/blob/master/ui/src/utils.ts#L393, `main.css` is not overriding any of the themes as the theme CSS is added at the end of the `<head>`, so it's vice versa, a theme overrides `main.css` instead. Will try to swap the order and see if it breaks things or not.

**Comment by pioneer** [comment]
Wait, that's wrong anyway. If `main.css` is able to override a theme, how could then a theme be able to define its own colours of the left vertical line (which is the scope of this ticket)? I only see the option, for now, to check every single theme that comes with Lemmy if it does not redefine the vertical line style, change the themes accordingly if necessary, and perform that check for every single theme to be included into Lemmy in future.
