### ISSUE TITLE
Try out middle-aligning post titles.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#668]
The post listings look a bit empty with short text.

**Comment by Charleshthomasiii** [comment]
Is this what you meant by middle aligning the titles? It looks kinda wack.
![middle_aligned_titles](https://user-images.githubusercontent.com/22798606/81517556-5055a400-9309-11ea-854b-44a7336ee804.png)

**Comment by dessalines** [comment]
It was a suggestion by @Nutomic , but it wasn't about centering the text horizontally, but about vertical  middle aligning the post titles to the center of the photo. So it would push down the text.
