### ISSUE TITLE
Configure Travis CI to also test on ARM

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#673]
Since a benefit of Lemmy is that it can be deployed on a low-power computer like a Raspberry Pi, I think it's a good idea to also test the build on ARM processors.

**Comment by StaticallyTypedRice** [comment]
I actually tried to implement this months ago, but couldn't get all the dependencies to install on ARM in a way that would actually build the project.

[This branch contains my failed efforts if anyone wants to look at it.](https://github.com/StaticallyTypedRice/lemmy/commits/testing)

**Comment by dessalines** [comment]
There is a docker build for arm, which is deployed on every minor release (bc it takes hours to build), but I don't know if its really required for travis CI to do unit tests on both ARM too.

It looks like its a one line addition: `https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support`, what was the failure message on your build?

**Comment by StaticallyTypedRice** [comment]
I had all kinds of errors, which are visible through the Travis tests for the commits in the branches I linked. They mostly have to do with apt and postgresql dependencies not being compatible or failing to install. I might take another crack at this after my university finals.

**Comment by Nutomic** [comment]
Related to this, we also need to run the integration tests for federation working on Travis.

**Comment by Nutomic** [comment]
We do this on drone.io now.
