### ISSUE TITLE
Most notification emails are not coming through. 

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#674]
I talked about this in [this comment](https://dev.lemmy.ml/post/32097/comment/4004) but I thought I'd post it as an issue.

I'm having a problem where most of the inbox notifications aren't getting emailed to me, but some are. Once in a while I'd get a notification of a comment or reply, but most are only notified in the site itself despite me enabling email notifications.

**Comment by StaticallyTypedRice** [comment]
Possibly related to #666

**Comment by Nutomic** [comment]
Did you notice any kind of pattern with the notifications that you aren't getting? I assume you already checked the spam? And which email-provider so you use? You could try if it works with another provider.

**Comment by StaticallyTypedRice** [comment]
I haven't been able to find any sort of patterns. I use Protonmail, but I'm not sure why they would block Lemmy.

**Comment by StaticallyTypedRice** [comment]
This problem was likely fixed so I'm closing this issue.
