### ISSUE TITLE
Page load or post submission hangs

### ISSUE THREAD

**Issue by Nicedude-git** [LemmyNet/lemmy#676]
I think I found a way to reproduce this. Chrome, android (lemmy 0.6.54): leave some text in post field. Spend a few minutes in other browser tab, browsing something else, and then go back to the lemmy tab. If you try to submit the text you left in lemmy post field, it won't, and the little wheel will keep circling forever (and then I have to reload from the browser, losing the input text). 

Something very similar happens with any page: if i leave lemmy in a tab, go to another tab to browse something else and then come back, then I try to load some lemmy page by clicking on its link, it won't, and the little wheel keeps circling.

**Comment by Nicedude-git** [comment]
in Brave browser for android the page just autoreloads when coming back to lemmy tab (losing input text). After autoreload, pages load normally.

Firefox for android seems to behave just like Brave.

**Comment by Nicedude-git** [comment]
Any comments? Was this reproducible by others?

**Comment by Nutomic** [comment]
I also noticed this sometimes, no idea what triggers it.

**Comment by Nicedude-git** [comment]
> I also noticed this sometimes, no idea what triggers it.

I think it is what I said. For some reason mobile browser automatically reload tabs when you switch to another tab and then come back after an amount of seconds.

This behavior makes you lose the text input (that's why I requested feature something like post draft or the like. Other community software such as Discourse and Xenforo solved this problem with autodraft or something like that).

Chrome for android for some reason doesnt auto reload lemmy tabs, but it makes the page unusable anyway, beacuse if you click on a thread, or try to post, after comming back from another tab for a few seconds, OR leaving the tab open too long, the page will hang and little circle will keep circling endlessly. 

I hope this is solvable, cause I am really enjoying lemmy, and this little annoyance has the potential to send long, effortful posts to the limbo to never be recovered.

**Comment by dessalines** [comment]
I can't reproduce this, so I'll need some console logs. I don't use chrome on android, but I'm guessing its not correctly re-connecting to websocket like firefox on android / desktop is.
