### ISSUE TITLE
Add federated mentions.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#681]
Currently parsing out `@` mentions doesn't account for federated mentions, and also on the front end it creates full markdown-style links.

- [x] Fix back-end mention parser to support `!community@instance` and `@user@instance`.
- [x] Switch from `/c/...` and `/u/...` to `!` and `@`
- [x] Make sure front end markdown can convert the new types of federated mentions.

Related to #679

**Comment by Nutomic** [comment]
@dessalines this seems to be finished?

**Comment by dessalines** [comment]
Ah yep it is.
