### ISSUE TITLE
Adding a language to Weblate translations

### ISSUE THREAD

**Issue by niniack** [LemmyNet/lemmy#688]
I'm interested in contributing translations for Hindi, but I can't seem to find how to suggest a new language on Weblate. How would I go about doing this?

**Comment by dessalines** [comment]
I just checked, there was a button at the bottom of the language list for "request new language", but I also have to do some code stuff after that request, which I just did.

Here it is, let me know if you have any issues :)

https://weblate.yerbamate.dev/projects/lemmy/lemmy/hi/

**Comment by niniack** [comment]
Amazing, thank you!
