### ISSUE TITLE
Have default theme light

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#690]
I think if the default them was white the website will look more attractive to new users since all the mainstream websites use a light theme by default such as Reddit, facebook, twitter, youtube.

The dev.lemmy.ml default dark theme makes lemmy look like an older website. Not suggesting to ditch the dark theme, just to not use the dark theme by default.

**Comment by dessalines** [comment]
This pretty much sums up my feelings on light themes: 
![image](https://user-images.githubusercontent.com/930215/80897165-0266ed80-8cc4-11ea-9364-4927fe5801ce.png)

In seriousness though, many people are going to suggest different defaults, and its impossible to please everyone. The best I can do is allow customization, and let people save their preferences, and we have I think 8 or different themes right now. If a lot of people want this later on, and its been voted on in some mass way, then I'd consider it, to the detriment of my eyes.
