### ISSUE TITLE
Question: Where do post and comments store that are on other instances

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy#692]
If I made a post in a community on another instance or made a comment in a post on another instance, where is that stored? Is it stored on the other instance or is it stored on the instance I am apart of?

**Comment by dessalines** [comment]
Its primary store is on the hosting instance, but activitypub sends your comment / post to all the other instances that have users subscribed to it, so its duplicated.

**Comment by trymeouteh** [comment]
> Its primary store is on the hosting instance, but activitypub sends your comment / post to all the other instances that have users subscribed to it, so its duplicated.

By hosting instance, you mean it is stored on the instance I am apart of?

And if it copies the comment and post and sends it to the other instance, if I edit my post or comment, will it update itself on the other instance?

**Comment by dessalines** [comment]
I suggest reading this on how activitypub works first: https://www.w3.org/TR/activitypub/

But there are actors: in our case, users, and communities, that live on an instance. When you create a comment, you talk to your local server, and it sends messages to all the federated servers, same with edits. When someone on the other server creates a comment, they're talking to their local server, which then sends a message to your server, so you can see it.
