### ISSUE TITLE
Parse out inreplyto field

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#694]
> At this point, the receiving server may notice that this post is in reply to another post, via the inReplyTo field. If the receiving server doesn’t have that post, it will fetch it to complete the thread. And continue fetching upthread posts until it reaches the top. So this is a second way that posts propagate. In addition to the servers we directly send our message to, any server receiving a reply to it will fetch a copy.

**Comment by Nutomic** [comment]
I think this only applies to comments, not to posts (assuming we are using Lemmy terminology).

**Comment by dessalines** [comment]
Correct. Right now I'm doing the replyto for comments like this:

```rust
    // Add a vector containing some important info to the "in_reply_to" field
    // [post_ap_id, Option(parent_comment_ap_id)]
    let mut in_reply_to_vec = vec![post.ap_id];

    if let Some(parent_id) = self.parent_id {
      let parent_comment = Comment::read(&conn, parent_id)?;
      in_reply_to_vec.push(parent_comment.ap_id);
    }
```

So the first array item is the post the comment is in, and the next one is an optional `comment_ap_id` if its in reply to another comment, as opposed to top-level in a post.

The issue is, when we receive this activity, we might not have either the post, or the comment locally, so we have to fetch them from their `ap_id`.
