### ISSUE TITLE
Quick bug on "context" button

### ISSUE THREAD

**Issue by felipeforte** [LemmyNet/lemmy#702]
Currently running on Parabola GNU/Linux-libre and GNU IceCat web browser.

![image](https://user-images.githubusercontent.com/64996043/81358526-527bf080-90c6-11ea-883b-27b80afd0f21.png)

The context button (the chain icon) is not functioning properly. While I do not have the technical expertise to pinpoint exactly why, I noticed something that might help:

![image](https://user-images.githubusercontent.com/64996043/81358645-a1c22100-90c6-11ea-9d2d-a210adf0f95b.png)

This is the "Inspector" tool of GNU IceCat showing how the "context" button (highlighted) breaks the pattern of all other functioning buttons. Hope this helps!

**Comment by dessalines** [comment]
The other ones are buttons that do in-page actions, that one is a link. I'd have to see a console.log for why it's not working, bc its working from Firefox and android right now.

**Comment by sylviaji** [comment]
I think it works if you click on the chain icon (the anchor element):
<img width="161" alt="a" src="https://user-images.githubusercontent.com/40915557/81361365-310e0b00-90ac-11ea-895a-008b6b5611ca.png">

but won't work if you click on the green area:
<img width="274" alt="button" src="https://user-images.githubusercontent.com/40915557/81361387-3e2afa00-90ac-11ea-8f53-aa6af663235c.png">

**Comment by dessalines** [comment]
Ah okay, I think I can alter this.

**Comment by felipeforte** [comment]
> I think it works if you click on the chain icon (the anchor element):
> <img alt="a" width="161" src="https://user-images.githubusercontent.com/40915557/81361365-310e0b00-90ac-11ea-895a-008b6b5611ca.png">
> 
> but won't work if you click on the green area (the button element excluding the chain icon):
> <img alt="button" width="274" src="https://user-images.githubusercontent.com/40915557/81361387-3e2afa00-90ac-11ea-8f53-aa6af663235c.png">

Both clicks have the same behavior. Or should I say the absence of behavior haha

**Comment by felipeforte** [comment]
> The other ones are buttons that do in-page actions, that one is a link. I'd have to see a console.log for why it's not working, bc its working from Firefox and android right now.

How can I have access to the console.log to share with you?

**Comment by sylviaji** [comment]
> Ah okay, I think I can alter this.

I tried to do the nesting in the reverse way (button inside the link) and it works, not sure if that’s the best practice. But seems like it’s not what this issue is about.

**Comment by sylviaji** [comment]
> Both clicks have the same behavior. Or should I say the absence of behavior haha

Hmm, what happens if you click on the link in your picture?

<img width="387" alt="Screen Shot 2020-05-07 at 10 38 55 PM" src="https://user-images.githubusercontent.com/40915557/81364659-2e171880-90b4-11ea-9a30-b5888271bf78.png">

**Comment by felipeforte** [comment]
> > Both clicks have the same behavior. Or should I say the absence of behavior haha
> 
> Hmm, what happens if you click on the link in your picture?
> 
> <img alt="Screen Shot 2020-05-07 at 10 38 55 PM" width="387" src="https://user-images.githubusercontent.com/40915557/81364659-2e171880-90b4-11ea-9a30-b5888271bf78.png">

I mean, I don't know what you mean by "clicking". It's on the Inspector tool, so if I click on it, it just prompts me to edit the HTML code.

If I, however, copy and paste that link in the format "https://<lemmy instance>/<pasted link>" it works.
