### ISSUE TITLE
"Reply" button can send multiple messages

### ISSUE THREAD

**Issue by felipeforte** [LemmyNet/lemmy#706]
Currently, the "Reply" button has a probably not intended feature of sending multiple instances of the same message:

![image](https://user-images.githubusercontent.com/64996043/81515723-eba84280-9324-11ea-997f-e61d272726b6.png)

If the loading icon is pressed, it will send repeated messages.

Also, sometimes when I comment or send messages, I receive an error that I wasn't able to replicate again, but it read something along the lines of "Operation cancelled" in red, and apparently it still sent some extra cloned messages. Yesterday I probably spammed the hell out of @dessalines 's message inbox because of that hahaha

Using GNU IceCat under Arch Linux

**Comment by dessalines** [comment]
Ah yeah that's probably a bug, it should disable the button while loading. This probably needs to be done with all buttons.

I'm not sure about the operation cancelled thing, probably a DB locking issue that I can't fix until we finish some of the current federation work.
