### ISSUE TITLE
Small adjustments of password fields

### ISSUE THREAD

**Issue by mateMathieu** [LemmyNet/lemmy#708]
There are two places where password fields request an auto-fill were they should not, and it tends to bug the non-geeky user:
1. on the login / sign in page, only the login password field should request an autofill, currently it fills both login and sign in. 
=> Modify the sign in password field to not request an autofill
2. on the setting page, the "current password" field request an autofill as well, this forces the user to delete the content if she/he does not want to change the password, since the "new password" and "retype new password" field are blank.
=> Modify the "current password" field to not request an autofill on the setting page.

Browser: Firefox 76.0, OS: Neon

Keep it up, you guys rock! Best

**Comment by dessalines** [comment]
Does anyone know the right way to do this? AFAIK just using `<input type="password"`, your browser will try to autofill every password field.

**Comment by sylviaji** [comment]
[How to turn off form autocompletion - Web security | MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields)

Adding `autoComplete=“new-password”`  to the password fields worked for me on both Firefox and Chrome.

I tried `autoComplete=“off”` first but it did not work, seems like most browsers ignore it.

**Comment by mateMathieu** [comment]
Hi, this might be useful to you:

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by dessalines** [comment]
Thx @sylviaji and @mateMathieu , that did it.

**Comment by mateMathieu** [comment]
I confirm the bug is solved, @dessalines sterling job!!!

**Comment by dessalines** [comment]
No probs.
