### ISSUE TITLE
Clarify the difference between "remove" and "delete"

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#712]
Instead we should use text like "deleted by user", and "removed by mod/admin for x reason".

**Comment by dessalines** [comment]
This also needs to add an optional `removed_by`, and `removed_reason` to the post and comment views, which should come after or at the same time as the materialized view rework in #606

**Comment by Nutomic** [comment]
@dessalines We can do that as a seperate issue, for now we could just change the text on the frontend to clarify what delete vs remove means.

**Comment by dessalines** [comment]
Closed by #712
