### ISSUE TITLE
Give instance administrators finer control over what federated content to display

### ISSUE THREAD

**Issue by StaticallyTypedRice** [LemmyNet/lemmy#714]
I think the current activitypub model of either display everything from an instance or block it is kind of lacking. Ideally, instance administrators should have finer control over what federated content is displayed through their own instance.

My proposal is to have options for deleting and blocking specific federated posts and comments, also specific federated communities, locally, so that they are ignored by the local instance. The goal of this is to give instance administrators more options on moderating content from the broader fediverse.

**Comment by StaticallyTypedRice** [comment]
This could be a far feature as federation isn't finished yet, but I want to make an issue now so people can share their opinions.

**Comment by Nutomic** [comment]
Blocking communities and users is pretty straightforward, it just needs a lot more work and will come later at some point. But which criteria do you propose to block posts and comments?

**Comment by StaticallyTypedRice** [comment]
Basically it'd be allowing moderators to moderate federated content.

**Comment by Nutomic** [comment]
I believe this issue is already fixed, as admins can delete any remote communities, users, posts or comments, which prevents them from being shown locally.
