### ISSUE TITLE
French translation and upvote/downvote

### ISSUE THREAD

**Issue by NicolasCARPi** [LemmyNet/lemmy#719]
Hello,

Just to let you know, I did a pass at the french translation on weblate. I'm attaching [the diff](https://github.com/LemmyNet/lemmy/files/4632094/french.diff.txt) for reference (because I first started doing in git).

I couldn't find a good translation for "Upvote/Downvote". And in fact, it's a [heated debate](https://www.reddit.com/r/france/comments/wmszf/comment_traduiriezvous_upvote_et_downvote_en/).

Different things we can think of:

1. Keep upvote and downvote (with the verbs being "upvoter" and "downvoter" which plays nice in french (verb of the first group))
2. Vote pour / Vote contre
3. Vote / Dévote
4. Vote positif / Vote négatif

I would go with 1 or 4, but 3 is good too. If there is another french person reading this, please give your opinion :)

**Comment by dioraman** [comment]
An Italian person here. Same problem, more problems [there](https://www.reddit.com/r/italy/comments/3tlocs/til_che_la_traduzione_italiana_di_upvotes_and/). I saw on Weblate the problem is similar in Castilan.

Which translation may fit better the purpose of the project? Consistency with Reddit is not mandatory.

**Comment by dessalines** [comment]
If `Like` and Dislike` are easier in those languages, that works too.

**Comment by NicolasCARPi** [comment]
@dessalines This would make it sound exactly like facebook (J'aime / J'aime pas), which is a negative point to me. What do you think?

**Comment by dessalines** [comment]
Its up to you, to me upvote and downvote are close enough to like / dislike, whichever is the simplest way to denote preference in your language.

**Comment by NicolasCARPi** [comment]
Well someone finished up the french translation so I don't have to make a choice anymore ;)
