### ISSUE TITLE
"Collapse comments" function should be on the far right/left hand side of the page

### ISSUE THREAD

**Issue by 47773838382882828** [LemmyNet/lemmy#724]
Currently it looks like this:
![9BDB5155-746D-47F2-82BA-CB3E75BFA305](https://user-images.githubusercontent.com/59035377/82133782-32210400-9833-11ea-9148-a65415c2cb50.jpeg)

The "plus" should be on the far left/right because it's easier to access and it's quite easy to click on something else by accident.

**Comment by dessalines** [comment]
I don't like how that looks, and its different from all my mobile clients.

**Comment by 47773838382882828** [comment]
Sorry what I mean is, clicking on the red part of the image below should toggle the collapse function as well.

![A6DF9E8F-CBFA-4C20-977E-1EDB836952C0](https://user-images.githubusercontent.com/59035377/82134005-d310be80-9835-11ea-9b03-db81e856f793.jpeg)

**Comment by dessalines** [comment]
If you make the page thinner (browser window, or dev tools), you'll see it smartly right-aligns the indicators to fill the right space there. I don't know how doable this is.
