### ISSUE TITLE
Lemmy not able to be crawled/indexed

### ISSUE THREAD

**Issue by 47773838382882828** [LemmyNet/lemmy#726]
Since it is a web app, googlebot and other bots aren't able to index the site. 

Archiving with the internet archive also dosent work.

Any possible workarounds?

**Comment by dessalines** [comment]
You just opened up this exact same issue: #725 

Are you spamming issues?

Dupe of #226

**Comment by 47773838382882828** [comment]
Sorry must have clicked twice or something

**Comment by dessalines** [comment]
Ah, cool.
