### ISSUE TITLE
Simplify duplicate / cross posts.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#727]
It looks good from the front page, but post-listing needs a simplified version for the cross-posts within that post.

![image](https://user-images.githubusercontent.com/930215/82134740-e8033880-97c8-11ea-8272-f14b3ba5159b.png)

**Comment by 47773838382882828** [comment]
Sometimes there are too many crossposts and it looks like spam. Should there be an expand function to show more?
