### ISSUE TITLE
Deleting an account doesn't seem to work

### ISSUE THREAD

**Issue by optikfluffel** [LemmyNet/lemmy#730]
When trying to delete an account I simply get redirected to the start page, the account still exists and is signed in.

**Comment by dessalines** [comment]
It doesn't delete your account, I don't have this yet. It overwrites all your comments and posts with removed. Which is the account so I can make sure it did that?

**Comment by optikfluffel** [comment]
Oh ok, I didn't know that this isn't implemented yet. The one I want to get rid of is [this account](https://dev.lemmy.ml/u/udo).

(I accidentally created two accounts, then lost access to the first one for a while, ...
the usual drama 🙈)

**Comment by michel-slm** [comment]
Signed up after the AMA and noticed the same issue (I don't actually need the account deleted, but renaming is not an option - signed up as just `michel` since I'm curious if it's already taken or not) 

Can it be renamed to michel-slm to match my other accounts elsewhere, or deleted and I'll start over? https://dev.lemmy.ml/u/michel

**Comment by dessalines** [comment]
I would just make a new account, there's no renaming of accounts. I have no way of merging accts.

**Comment by michel-slm** [comment]
Will do - sorry about making the database noisy! I'll get around and delete the old account once this issue is resolved.

**Comment by nathgit** [comment]
Mastodon doesn't give an option to delete an account either. Is that a common theme in opensource/federated alternatives for some reason?

**Comment by dessalines** [comment]
I don't know, we typically don't delete anything for database reasons. IE you make a community, deleting that db row would wipe out everyone's comments, posts, etc. Or you make a comment, then deleting your user would remove all the comments under yours.

**Comment by ryexandra** [comment]
Would it be reasonable to reassign deleted Posts and Comments to a special "nobody" user ie `ID: 0`? this way a user *could* be properly deleted.

**Comment by MasterOfTheTiger** [comment]
@nathgit Mastodon actually does give an option to delete your account.

**Comment by ryexandra** [comment]
Also of note. This is vital for GDPR and the Right to be Forgotten compliance.

As postgres serial ID's start at `1` I propose that a special `nobody` or `*deleted*` user be created as ID `0` or `-1`. when a user delete's their account all posts, comments, and messages are reassigned to this special user as well as have their content removed.

**Comment by prcmt** [comment]
A delete account button should delete your account. If it doesn't do that at the moment, probably should change the label.
