### ISSUE TITLE
Hide user actions in UI (create post, subscribe) when not logged in

### ISSUE THREAD

**Issue by IronOxidizer** [LemmyNet/lemmy#733]
It clutters the page for users not logged in, it's deceiving since it makes the user think they're logged in when they're not, and it's annoying to fill in the post information to have the post form reset because the user needs to login before they can post.

**Comment by dessalines** [comment]
> and it's annoying to fill in the post information to have the post form reset because the user needs to login before they can post.

I just tested this with a non-logged in user, it **does not reset the form**, it has a toast at the bottom saying you need to log in.

The create post, create community, and subscribe are ones I specifically don't want to hide because they show functionality.
