### ISSUE TITLE
Finnicky UI in the Recent Comments

### ISSUE THREAD

**Issue by TheEvilSkeleton** [LemmyNet/lemmy#734]
I really don't know how to explain this, but here is a video showing what the problem is:

https://youtu.be/ZVIr8_XphB0

**Comment by dessalines** [comment]
Its correctly showing the scrollbar on mouseover. You mean it should permanently hide it?

**Comment by TheEvilSkeleton** [comment]
Yes, that would be much better, or it should permanently show it, so it doesn't move the words every time you put the cursor on it
