### ISSUE TITLE
solar notification is barely visible due to very similar colors

### ISSUE THREAD

**Issue by dioraman** [LemmyNet/lemmy#736]
Users choosing *solar* theme cannot see notifications since they are written as white font on albumen background.
An higher contrast background may let them actually read the notification.

*Meta: I wanted to give a blind try as newcomer's pull request but I find hard to go through the CSS sheets. Next time I will run my personal Lemmy instance for tests.*

Example screenshot as follows:
![example screenshot](https://dev.lemmy.ml/pictshare/zlhnit.jpg)

**Comment by dessalines** [comment]
I'm busy with other things right now, but if anyone wants to take a look at the theme and fix this, that'd be nice.

**Comment by kixiQu** [comment]
Vaporwave light has the same problem. I'll switch to minty for a while and see if it has the same. 
<img width="717" alt="Screen Shot 2020-06-02 at 3 11 16 PM" src="https://user-images.githubusercontent.com/18646700/83575309-1597f380-a4e4-11ea-9d7f-3acad518d45a.png">
