### ISSUE TITLE
docu translation

### ISSUE THREAD

**Issue by dioraman** [LemmyNet/lemmy#738]
Support for translation of documentation. This is not urgent since Lemmy is in an early beta stage. Also, AFAIU a solution with the current system (Weblate) may be hacky.

Adde: there is an open issue to support translations for mdBook. Check it out [here](https://github.com/rust-lang/mdBook/issues/5)!

**Comment by Nutomic** [comment]
[Here is a PR for translations in mdBook which looks quite promising](https://github.com/rust-lang/mdBook/pull/1306). Hopefully it will get merged soon. And I dont think that weblate is the right tool for this, as it seems to be made mainly for translating short strings. For this, I would move the docs into a separate repo, and handle translations through pull requests.

In general I agree that translating the docs is very important. Right now they are only readable for people who speaks English, which excludes most of the world's population from creating an instance.

**Comment by dessalines** [comment]
@Nutomic set this up now, and it'll be closed by #1342
