### ISSUE TITLE
Add support for embedded link previews / Opengraph tags

### ISSUE THREAD

**Issue by marek-lach** [LemmyNet/lemmy#74]
This can probably best be achieved with an _opengraph parser_ of some sort.

It'd replicate the existing functionality of both _Reddit_ and _Prismo_:

<img width="765" alt="Screenshot 2019-04-18 at 11 27 47" src="https://user-images.githubusercontent.com/45913977/56351370-3cef0c80-61cd-11e9-8553-b47fa3a1a792.png">

**Comment by dessalines** [comment]
This is something I'd like to take a poll on before adding.

[Vote here.](https://simplevote.tk/#/poll/mZkE)

Sites like hacker news, and lobste.rs, **don't have image previews**, and it does makem look pretty clean:

![](https://i.imgur.com/3746YVk.png)

![](https://i.imgur.com/25NCqOz.png)

**Comment by ChrisCates** [comment]
This should be a toggleable feature.
That the user and/or admin can decide whether or not this feature is enabled.

**Comment by marek-lach** [comment]
Definitely should be optional, and definitely a low priority issue right now.

**Comment by dessalines** [comment]
I relented and added image thumbnails at least. It only works if your url is an actual image tho.

![](https://i.imgur.com/hhrhY4t.png)

**Comment by marek-lach** [comment]
> I relented and added image thumbnails at least. It only works if your url is an actual image tho.
> 
> ![](https://camo.githubusercontent.com/31d7e7b84027efb7b9c20162246ae8ae40cbb812/68747470733a2f2f692e696d6775722e636f6d2f686872685934742e706e67)

Cool :-)

**Comment by dessalines** [comment]
- [stackoverflow post with opengraph tags](https://stackoverflow.com/questions/48758954/using-rich-preview-meta-tags-as-images-html-css)
- [A tester](https://metatags.io/)
