### ISSUE TITLE
Add a list of contributors inside Lemmy

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#743]
I think it would be nice to add a list of contributors like this one in Syncthing. Afaik it is auto-generated from the git log so it should be rather easy to work, and would be a cool way to reward contributors. A good place to put this might be a site in Lemmy similar to the donations page.

![Screenshot_20200525_011523](https://user-images.githubusercontent.com/1044450/82767311-3b533780-9e16-11ea-856c-c57ffcf8e700.png)

**Comment by dessalines** [comment]
The sidebar seems like the best place for this, I added it to the translations and a link to the github contributor page:

![image](https://user-images.githubusercontent.com/930215/87050689-983f5d00-c1cc-11ea-8ca8-e5f3c32b04d7.png)
