### ISSUE TITLE
Testing for federation

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#746]
- [x] Split integration tests into multiple files, extract helper functions
- [x] Extend integration tests
- [ ] Add tests for malicious behaviour (eg invalid http signature)
- [ ] More unit tests
- [ ] add integration test that verifies ActivityPub sending/receiving (using raw json)
- [ ] look into using [FediDB](https://fedidb.org/)

**Comment by dessalines** [comment]
I'll close this in favor of #1040, all the specific checks are better outlined there.
