### ISSUE TITLE
Ansible installation is broken

### ISSUE THREAD

**Issue by Hoaxha** [LemmyNet/lemmy#747]
Executing `ansible-playbook lemmy.yml --become` on Debian 10 throws:

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/lemmy/ansible/lemmy.yml': line 57, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: start docker-compose
    ^ here
```

**Comment by Nutomic** [comment]
It works fine for me on Manjaro, so I believe that you arent meeting one or more of the requirements for that module:

https://docs.ansible.com/ansible/latest/modules/docker_compose_module.html#docker-compose-module

**Comment by dessalines** [comment]
I'm guessing its an old version of ansible that can't read the `.yml`
