### ISSUE TITLE
Adjust Ansible playbook for different Linux distributions

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#753]
Our current playbook is written for Ubuntu 18.04. Some examples that will break on other distros:

- Ubuntu 20.04 has `python-minimal` renamed to `python2-minimal`
- Distros that dont use `apt` will obviously fail to install any of the dependencies

**Comment by ceecx** [comment]
Wish there was more documentation on installing Lemmy with Ansible, in fact I tried different systems, all of which failed, my back-end knowledge sucks.  :(

**Comment by dessalines** [comment]
This would require a LOT of work, its not something me or nutomic will likely work on.

**Comment by ceecx** [comment]
> This would require a LOT of work, its not something me or nutomic will likely work on.

If I have any information that would help with the installation I will provide it.

**Comment by Nutomic** [comment]
@ceecx If you post your logs, we can probably help you (at least for Ubuntu). The manual installation should work for every distro, as long as you find the right packages.

**Comment by ceecx** [comment]
> @ceecx If you post your logs, we can probably help you (at least for Ubuntu). The manual installation should work for every distro, as long as you find the right packages.

I opened an Issues, thanks. #901

**Comment by dessalines** [comment]
I'll re-open if anyone wants to make these.
