### ISSUE TITLE
Server IP exposed by additional resource loading even behind CDN

### ISSUE THREAD

**Issue by simsalis** [LemmyNet/lemmy#754]
New instance with no posts loads 2 images and 1 cookie exposing actual server IP, even behind Cloudflare. There are no images uploaded on the instance and only one user (fresh install). uMatrix reveals that clearly:

uMatrix | cookie | css | image | media | script | XHR | frame | other        
domain.com | 3 | 8 | 2 | 0 | 2 | 2 | 0 | 1
IP | 1 | 0 | 2 | 0 | 0 | 0 | 0 | 0

cc: @Nutomic @dessalines

**Comment by Nutomic** [comment]
Can you tell which resource specifically is loaded directly from the server IP? Maybe from the network monitor in your browser?

**Comment by simsalis** [comment]
Problem was caused by Cloudflare SSL settings. Moving from Full (Strict) to Full solved it.
