### ISSUE TITLE
Consider replacing bcrypt

### ISSUE THREAD

**Issue by PeterUlb** [LemmyNet/lemmy#762]
It might be worth looking into alternatives for bcrypt which allow the specification of Memory and CPU-hardness parameters. 
E.g. argon2id.

**Comment by dessalines** [comment]
Pull requests welcome, but bcrypt has been working fine. I also think changing that crypto library might break hashed password validation.

**Comment by igalic** [comment]
might be a good, very low-prio, exercise for someone to build [hash rotation](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#upgrading-legacy-hashes), before it's needed.

**Comment by dessalines** [comment]
I don't see what's wrong with bcrypt, and changing that would mess up all the current passwords.
