### ISSUE TITLE
Add additional search functionality

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#765]
- [x] Add community filtering for posts, comments
- [ ] Add URL search type

**Comment by je-vv** [comment]
How about adding ability to search for posts included by oneself (u/<my_username>), and also by some specific other user (u/<another_username>)?

**Comment by dessalines** [comment]
I'm starting to think this should all just be a simple search parsing method like twitter does, with everything in a single box: `test search (from:user_a,user_b) community: main@instance.dev`
