### ISSUE TITLE
User avatars can be too large

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#766]
The avatar of [this user](https://dev.lemmy.ml/u/kixiQu) has a size of 6 MB and the full version is loaded on every page where that user posted. It should be scaled down and maybe the animation removed. This might be a problem specific to .mp4 or animations, I dont know.

Image link for reference in case they change it: https://dev.lemmy.ml/pictshare/re1urp.gif

**Comment by kartikynwa** [comment]
If you wanna resize an image to a reasonable size while uploading pictshare has this in their api:
https://github.com/HaschekSolutions/pictshare/blob/-/rtfm/MODIFIERS.md#resize

**Comment by igalic** [comment]
what about caching headers?
surely avatars don't change too often, and if they do, pictshare surely assigns them a fresh URL

(this is not to disregard making the images smaller to begin with, but in addition to it)

**Comment by Nutomic** [comment]
FYI we are switching from pictshare to [pict-rs](https://git.asonix.dog/asonix/pict-rs/).

**Comment by dessalines** [comment]
I'm guessing it'll still be a problem with gifs, but that'll need testing.

**Comment by dessalines** [comment]
This should be good now, with the pict-rs migration.
