### ISSUE TITLE
Remove trackers from links

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#768]
Lemmy could automatically remove things like [utm parameters](https://en.wikipedia.org/wiki/UTM_parameters) and rewrite AMP links. Maybe we could also add a user option to redirect youtube links to invidious, twitter to nitter etc.

[Previously discussed here](https://dev.lemmy.ml/post/33655/comment/5330)

**Comment by dessalines** [comment]
[ClearUrls](https://gitlab.com/KevinRoebert/ClearUrls) looks like the most popular tracker remover for firefox. If it had a simple js library that was `function removeTrackers(url: String): String`, then this would be very easy.

**Comment by Nutomic** [comment]
It should be done in Rust imo, but I guess js is better than nothing.

**Comment by bytesnake** [comment]
For the utm parameters a simple [regex](https://stackoverflow.com/questions/51187508/removing-utm-parameters-from-url-in-javascript-with-a-regex) (or even a split and join) should suffice, but I don't know how AMP links are handled

**Comment by pefimo** [comment]
[Projekt:ONI](https://home.oniprojekt.ninja/#solutions) provides a browser extension called WhatCampaign that overwrites `utm_*` URL parameters. Maybe that could be used as a starting point too?
