### ISSUE TITLE
Automatic creation of identicons

### ISSUE THREAD

**Issue by kolgza** [LemmyNet/lemmy#770]
# What are identicons?
[From Wikipedia](https://en.wikipedia.org/wiki/Identicon)
> An Identicon is a visual representation of a hash value, […] that serves to identify a user of a computer system as a form of avatar while protecting the users' privacy. The original Identicon was a 9-block graphic, and the representation has been extended to other graphic forms by third parties.

# Why would Lemmy start using identicons?
Lemmy currently already supports users uploading profile pictures. This makes it easier to differentiate between different users. However there are two key issues:

1. Users without profile pictures don't have this benefit [of being easily differentiated]
2. There exists a dichotomy between users with profile pictures, and users without profile pictures.

## Why not just require those users create profile pictures?

Many users may want not want to upload a profile picture if it makes them less anonymous.

## Why not just set a default profile picture?

If a significant number of people don't change their default profile picture, then my two key problems would still persist.

# What might they look like?

[This blog post](https://barro.github.io/2018/02/avatars-identicons-and-hash-visualization/) describes different types of identifications. Something like the Github or Wordpress identicons (as described in the linked blog post) might be effective in giving Lemmy a nice retro aesthetic. However, it might also be worth taking a more modern approach to this concept, such as with [*Iqons*](https://github.com/nimiq/iqons). 

# Other resources

- [Jdenticon: Open source library for generating identicons](https://jdenticon.com)
- [identicon.js, which has more Github-style identicons](https://github.com/stewartlord/identicon.js)
- [Nimiq Iqons, a NodeJS library that has a more modern take on identicons](https://github.com/nimiq/iqons)

**Comment by kolgza** [comment]
See also: [lobste.rs](https://lobste.rs/), another link aggregator which implements identicons.

![image](https://user-images.githubusercontent.com/46303203/83643687-daf39100-a59f-11ea-8287-378e5cd847a6.png)

**Comment by 47773838382882828** [comment]
Nice idea. GitHub does this as well

**Comment by dessalines** [comment]
I'm pretty strongly against this, I also think those identicons in lobster.rs are really ugly.

> Users without profile pictures don't have this benefit [of being easily differentiated]

Old reddit and lots of other platforms didn't have avatars, and a username was enough to differentiate fine.

> There exists a dichotomy between users with profile pictures, and users without profile pictures.

It looks pretty good currently to me.

![image](https://user-images.githubusercontent.com/930215/83950521-5ac86800-a7f9-11ea-9d24-226bc02c2efb.png)

If someone doesn't want an icon, they shouldn't have one, and if they want an identicon, they can upload their own one manually.

**Comment by kolgza** [comment]
I was going to let this go, because if you didn't think that they *look good*, then it's not worth trying to convince you that my tastes are better than your tastes. However, as I've used Lemmy, I've come to think that this isn't an issue worth me letting go.

> Old reddit and lots of other platforms didn't have avatars, and a username was enough to differentiate fine.

I suppose it's not very difficult to just look at the username, but I'd rather be able to differentiate without having to conscientiously do so.

> I also think those identicons in lobster.rs are really ugly.

Yeah, they do look somewhat dated. I like the [Nimiq Iqons](https://github.com/nimiq/iqons). Perhaps, in the future, we could have something similar, but based on the Lemmy mascot.
