### ISSUE TITLE
Hierarchicial tags — a cool feature to borrow from Tildes!

### ISSUE THREAD

**Issue by kolgza** [LemmyNet/lemmy#771]
# What are hierarchical tags?
Tildes uses hierarchical tags to establish post categorization beyond which group (the Tildes equivalent of a subreddit or a community) a post is in. The closest Reddit analogue for them would be post flairs. There a few key differences between them and flairs, however:
- They can exists on posts across multiple groups.
- Multiple tags can be applied to the same post.
- Their hierarchical nature allows for increasing levels of specificity the longer each tag gets.

# Why should they be implemented?
- They would make searching for posts easier.
- They would make finding similar posts easier.
- They would help differentiate Lemmy from Reddit

# What might be some problems with them?
- User apathy: many users just don't use them, or don't use them to their fullest potential.
- Potentially redundant tags could exist.

# Other resources
- [Tildes Gitlab page](https://gitlab.com/tildes/tildes)
- [Tildes Documentation of hierarchical tags](https://docs.tildes.net/instructions/hierarchical-tags)

**Comment by kolgza** [comment]
Relevant:  #317

**Comment by dessalines** [comment]
Could you copy this over to #317 and I'll close this as a dupe?
