### ISSUE TITLE
Convert images and gifs to webp upon upload

### ISSUE THREAD

**Issue by kolgza** [LemmyNet/lemmy#772]
[WebP: A new image format for the Web](https://developers.google.com/speed/webp/)
> WebP is a modern **image format** that provides superior **lossless and lossy** compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster.
>
> WebP lossless images are [26% smaller](https://developers.google.com/speed/webp/docs/webp_lossless_alpha_study#results) in size compared to PNGs. WebP lossy images are [25-34% smaller](https://developers.google.com/speed/webp/docs/webp_study) than comparable JPEG images at equivalent [SSIM](https://en.wikipedia.org/wiki/Structural_similarity) quality index.
>
> Lossless **WebP supports transparency** (also known as alpha channel) at a cost of just [22% additional bytes](https://developers.google.com/speed/webp/docs/webp_lossless_alpha_study#results). For cases when lossy RGB compression is acceptable, **lossy WebP also supports transparency**, typically providing 3× smaller file sizes compared to PNG.

Related #767

**Comment by dessalines** [comment]
Looks like pictshare supports this, its just a matter of changing the url.

@Nutomic you might be interested in this, check it out:
url | size 
--- | ---
Regular | 
https://communism.lemmy.ml/pictshare/w0aasm.jpg | 162 KB
https://communism.lemmy.ml/pictshare/webp/w0aasm.jpg | 87 KB
Thumbnail |
https://communism.lemmy.ml/pictshare/192/w0aasm.jpg | 10.69 KB
https://communism.lemmy.ml/pictshare/webp/192/w0aasm.jpg | 5.91 KB

**Comment by Nutomic** [comment]
Is webp supposed to have a .jpg extension? That seems wrong. Also afaik not every browser supports webp, so this probably needs a conditional in the frontend. Anyway, saving bandwidth is always good :+1:

**Comment by kolgza** [comment]
As far as I know, WebP files should have a `.webp` extension. This might or might not cause problems on Windows, where the file extension determines the mime-type. 😛

On Linux, the issue I ran into was with *Eye of GNOME* not supporting WebP (although I didn't have the same issue with *nomacs*).

**Comment by dessalines** [comment]
Yeah it doesn't look like pictshare changes the extension, but a browser inspect does show it as `webp`. 

[We're close to 80%](https://caniuse.com/#feat=webp) supported on webp, if anyone asks I'm just gonna say upgrade their browser.

**Comment by Nutomic** [comment]
Looks like youre gonna exclude all of macOS/iOS and IE with that. Not a good idea to switch without any fallback imo.

**Comment by mbeck810** [comment]
@dessalines @Nutomic Can you please reconsider this feature?

Practically all browsers support WebP by now ([94.77%](https://caniuse.com/?search=webp)) and IE was forcefully replaced via Windows Update. Many other sites use WebP these days.

WebP is the only format I found working on Lemmy, but it needs to be manually converted and hosted externally, which is too complicated for many users.

When a link to an external GIF file is posted, Lemmy converts the preview to MP4 which doesn't work properly. It's not properly embedded and MP4 doesn't support looping, while WebP can loop and therefore fully replace the old GIF.
