### ISSUE TITLE
Consider FEDERATION.md convention

### ISSUE THREAD

**Issue by aschrijver** [LemmyNet/lemmy#774]
On SocialHub a sort of informal convention was adopted for describing the federation behavior of AP implementations. Currently there are about 5 (AFAIK) impls that already did so. Consider creating one as well.

Refer to: [Documenting federation behavior in a semi-standard way](https://socialhub.activitypub.rocks/t/documenting-federation-behavior-in-a-semi-standard-way/453)

I saw [Activitypub API outline](https://github.com/LemmyNet/lemmy/blob/master/docs/src/contributing_apub_api_outline.md) which is already great, and federation description will be very valuable additional info.

Particularly relevant to Lemmy is e.g. the discussion on [Groups implementation](https://socialhub.activitypub.rocks/t/groups-implementation/591) and then knowing how Lemmy's approach to Groups is. (Note: Based on that discussion you _might_ want to make changes to how it works, for compat reasons).

**Comment by Nutomic** [comment]
This looks good, thanks for bringing it up! We definitely want to write up documentation for everything, but I think so far we havent decided on any format. That one looks good, we can definitely write that up sooner or later (probably after we get federation working).

Is there any summary for the Groups thread? I dont feel like reading through all that. We are currently doing groups like this: 
- users can follow groups, and the group always accepts the follow
- if anyone posts to a group, the group will announce that
- followers get posts and comments via these announces

**Comment by aschrijver** [comment]
The discussion is ongoing, and there are various perspectives on what is the best approach, so it could be a good place to let Lemmy's voice be heard. I transferred the above 3 bullet points to the thread as a FYI.
