### ISSUE TITLE
Password managers aren't filling in the right fields on new user setup or login

### ISSUE THREAD

**Issue by phelix001** [LemmyNet/lemmy#777]
When setting up a new user or logging in, password managers get useless.  

Password managers should save the correct username, save the password, when gererating a password put it in the correct field, and when logging in enter info into the correct fields.

From https://stackoverflow.com/questions/23156578/google-chrome-autofilling-all-password-inputs

In HTML5 with autocomplete attribute there is a new property called "new-password" which we can use to over come this issue. Following works for me.

<input id="userPassword" type="password" autocomplete="new-password">
current-password : Allow the browser or password manager to enter the current password for the site. This provides more information than "on" does, since it lets the browser or password manager know to use the currently-known password for the site in the field, rather than a new one.

new-password : Allow the browser or password manager to automatically enter the new password for the site. This might be automatically generated based on the other attributes of the control, or might simply tell the browser to present a "suggested new password" widget of some kind.

Refer: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password

**Comment by dessalines** [comment]
Did you test this on lemmy? BC we already fixed this #708

**Comment by phelix001** [comment]
You're right. I had a pw manager issue.
