### ISSUE TITLE
Add System monitoring to production servers

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#782]
Some options:

- https://grafana.com/grafana/
- https://github.com/allinurl/goaccess

**Comment by dessalines** [comment]
Going to set up goaccess on the server soon.

**Comment by dessalines** [comment]
@Nutomic beat me to it :)

**Comment by Nutomic** [comment]
We are collecting a lot of useful data now, but still need to configure Grafana to aggregate it nicely. Its very powerful, but not easy to get started with.

**Comment by Nutomic** [comment]
Should be good now.
