### ISSUE TITLE
Docker development - diesel compile fail

### ISSUE THREAD

**Issue by ernestwisniewski** [LemmyNet/lemmy#788]
`git clone `https://github.com/LemmyNet/lemmy`
`cd lemmy/docker/dev`
`./docker_update.sh`

I tried on macos and ubuntu, same effect. Output:

   ...
   Compiling actix-web v2.0.0
   Compiling actix-web-actors v2.0.0
   Compiling actix-files v0.2.1
error: could not compile 'diesel'.

Caused by:
  process didn't exit successfully: 'rustc --crate-name diesel /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="32-column-tables"' --cfg 'feature="64-column-tables"' --cfg 'feature="bitflags"' --cfg 'feature="chrono"' --cfg 'feature="default"' --cfg 'feature="postgres"' --cfg 'feature="pq-sys"' --cfg 'feature="r2d2"' --cfg 'feature="with-deprecated"' -C metadata=6a4596e4b46d2d5b -C extra-filename=-6a4596e4b46d2d5b --out-dir /app/server/target/x86_64-unknown-linux-musl/release/deps --target x86_64-unknown-linux-musl -L dependency=/app/server/target/x86_64-unknown-linux-musl/release/deps -L dependency=/app/server/target/release/deps --extern bitflags=/app/server/target/x86_64-unknown-linux-musl/release/deps/libbitflags-b1b1703c3a6b9c66.rmeta --extern byteorder=/app/server/target/x86_64-unknown-linux-musl/release/deps/libbyteorder-3b185b2680b66e8e.rmeta --extern chrono=/app/server/target/x86_64-unknown-linux-musl/release/deps/libchrono-0e6a05e9c3624412.rmeta --extern diesel_derives=/app/server/target/release/deps/libdiesel_derives-0a35bf96b44d0023.so --extern pq_sys=/app/server/target/x86_64-unknown-linux-musl/release/deps/libpq_sys-a1f5e32c2eb5efaa.rmeta --extern r2d2=/app/server/target/x86_64-unknown-linux-musl/release/deps/libr2d2-1b10333a8349332b.rmeta --cap-lints allow -L native=/usr/local/musl/lib' (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...

**Comment by dessalines** [comment]
iirc this has to do with your system not having libpq or some of the other dependencies required for postgres. I'd just install postgres on your development machine then try again.

**Comment by dessalines** [comment]
Your system also needs openssl I'm pretty sure.

**Comment by ernestwisniewski** [comment]
@dessalines you're right, there was a problem with postgres libraries (and this is diesel specific issue), thanks for the tip. Anyway if someone has a similar problem on Ubuntu, the solution might be: 

sudo apt install libpq-dev libmysqlclient-dev libdbus-1-dev libsqlite3-dev
sudo ln -s /usr/lib/x86_64-linux-gnu/libpq.so /usr/lib/libpq.so

**Comment by Nutomic** [comment]
@ernestwisniewski you should only need libpq-dev, we don't use mysql or sqlite.

**Comment by ernestwisniewski** [comment]
I figured it out after a while. A real problem was the lack of memory on my VPS where I set up a test instance. I decided to change the vps parameters, but first I tried to add some swap space and it works as well: https://github.com/diesel-rs/diesel/issues/2026

**Comment by Nutomic** [comment]
@ernestwisniewski Whats the minimum RAM requirement then in your experience? Would be useful to add that to the documentation.

**Comment by Nutomic** [comment]
Actually the local development docs dont even mention the required packages. I will add that.

**Comment by dessalines** [comment]
Ya I wouldn't recommend using anything but the prod docker image on VPS's, this thing ain't easy to build.
