### ISSUE TITLE
Remove openssl from rust-musl-builder

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#789]
I think our only dep left that requires openssl, is https://github.com/lettre/lettre, which should include rusttls instead of requiring a system-dependent openssl, once v0.10 hits.

**Comment by paolobarbolini** [comment]
Hello, lettre maintainer here.
lettre 0.10.0-alpha.3 is out, with support for rustls. This version received a lot of improvements and bug fixes over the 0.9 version and the past alphas, and is ready to be tested in the wild. Feel free to ping me in case you need help with the upgrade.

**Comment by dessalines** [comment]
Thanks, I'll try it out.

@Nutomic I see we also have these, would you be able to see if rusttls has these?

```
lemmy_apub/src/extensions/signatures.rs
11:use openssl::{

lemmy_utils/src/apub.rs
2:use openssl::{pkey::PKey, rsa::Rsa};
```

**Comment by dessalines** [comment]
@paolobarbolini I started trying to upgrade our email to this new lettre, but there's a lot of breaking changes and not much documentation yet. Here's our email function: https://github.com/LemmyNet/lemmy/blob/main/lemmy_utils/src/email.rs

How do I do an HTML body, or use the `SmtpTransportBuilder` (it has no `::new`).

**Comment by paolobarbolini** [comment]
You can do something like this:

```rust
let mut builder = SmtpTransport::builder_dangerous("domain");
builder = builder.port(server_port);

if config.tls {
    let tls_config = TlsConfig::new("domain");
    builder = builder.tls(Tls::Wrapper(tls_config));
}
if let (Some(username), Some(password)) = config.credentials {
    builder = builder.credentials(Credentials::new(username, password));
}

let mailer = builder.build().expect("builder built ok");

// use the mailer as long as you want
// if you have the r2d2 feature enabled (it's on by default) connections will be recycled
// by storing them into a connection pool

// once you don't need it anymore Drop it
```

To create an html message you do something like

```rust
let email = Message::builder()
    .from(from_address.parse().expect("from address isn't valid"))
    .to(to_address.parse().expect("to address isn't valid"))
    .subject(subject)
    .multipart(
        MultiPart::mixed()
        .multipart(
            MultiPart::alternative()
            .singlepart(
                SinglePart::seven_bit()
                .header(header::ContentType("text/plain; charset=utf8".parse().unwrap()))
                .body("utf-8 plaintext version of the email (ideally there should be always a plaintext fallback)")
            )
            .multipart(
            MultiPart::related()
                .singlepart(
                    SinglePart::eight_bit()
                    .header(header::ContentType("text/html; charset=utf8".parse().unwrap()))
                    .body("utf-8 html email")
                )
            )
        )
    ).expect("email built correctly");

// when you are ready send it
mailer.send(email).expect("message sent");
```

**Comment by Nutomic** [comment]
@dessalines Signing and verifying signatures should work fine with [ring](https://briansmith.org/rustdoc/ring/signature/index.html), but they dont have key generation implemented yet.

https://github.com/briansmith/ring/issues/219
