### ISSUE TITLE
Admin is not added

### ISSUE THREAD

**Issue by yuri25** [LemmyNet/lemmy#791]
I can’t add an administrator ... I installed it using docker. Please help me what could be the reason? Try it yourself please - test site https://ptzportal.ru/setup

**Comment by Nutomic** [comment]
Firefox dev tools say that the websocket connection is not working. How did you install it? And do you have the following lines in your nginx config?

https://github.com/LemmyNet/lemmy/blob/master/ansible/templates/nginx.conf#L60

**Comment by yuri25** [comment]
`server {
	server_name ptzportal.ru www.ptzportal.ru;
	charset UTF-8;
	index index.html;
	disable_symlinks if_not_owner from=$root_path;
	include /etc/nginx/vhosts-includes/*.conf;
	include /etc/nginx/vhosts-resources/ptzportal.ru/*.conf;
	access_log /var/www/httpd-logs/ptzportal.ru.access.log;
	error_log /var/www/httpd-logs/ptzportal.ru.error.log notice;
	ssi on;
	return 301 https://$host:443$request_uri;
	set $root_path /var/www/admin/data/www/ptzportal.ru;
	root $root_path;
	listen 81.16.141.142:80;
	listen [2a01:48a0:4001::fa]:80;
	location / {
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:8536;
	}
}
server {
	server_name ptzportal.ru www.ptzportal.ru;
	ssl_certificate "/etc/letsencrypt/live/ptzportal.ru-0002/fullchain.pem";
	ssl_certificate_key "/etc/letsencrypt/live/ptzportal.ru-0002/privkey.pem";
	ssl_ciphers EECDH:+AES256:-3DES:RSA+AES:!NULL:!RC4;
	ssl_prefer_server_ciphers on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	add_header Strict-Transport-Security "max-age=31536000;";
	ssl_dhparam /etc/ssl/certs/dhparam4096.pem;
	charset UTF-8;
	index index.html;
	disable_symlinks if_not_owner from=$root_path;
	include /etc/nginx/vhosts-includes/*.conf;
	include /etc/nginx/vhosts-resources/ptzportal.ru/*.conf;
	access_log /var/www/httpd-logs/ptzportal.ru.access.log;
	error_log /var/www/httpd-logs/ptzportal.ru.error.log notice;
	ssi on;
	set $root_path /var/www/admin/data/www/ptzportal.ru;
	root $root_path;
	listen [2a01:48a0:4001::fa]:443 ssl;
	listen 81.16.141.142:443 ssl;
	location / {
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:8536;
	}
}


proxy_cache_path /var/cache/lemmy_frontend levels=1:2 keys_zone=lemmy_frontend_cache:10m max_size=100m                 use_temp_path=off;

server {
    listen 80;
    server_name ptzportal.ru;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ptzportal.ru;

   ssl_certificate /etc/letsencrypt/live/ptzportal.ru-0002/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/ptzportal.ru-0002/privkey.pem;

    # Various TLS hardening settings
    # https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_session_timeout  10m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Hide nginx version
    server_tokens off;

    # Enable compression for JS/CSS/HTML bundle, for improved client load times.
    # It might be nice to compress JSON, but leaving that out to protect against potential
    # compression+encryption information leak attacks like BREACH.
    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
    gzip_vary on;

    # Only connect to this site via HTTPS for the two years
    add_header Strict-Transport-Security "max-age=63072000";

    # Various content security headers
    add_header Referrer-Policy "same-origin";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";
    add_header X-XSS-Protection "1; mode=block";

    # Upload limit for pictshare
    client_max_body_size 50M;

    location / {
        proxy_pass http://127.0.0.1:8536;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Proxy Cache
        proxy_cache             lemmy_frontend_cache;
        proxy_cache_use_stale   error timeout http_500 http_502 http_503 http_504;
        proxy_cache_revalidate  on;
        proxy_cache_lock        on;
        proxy_cache_min_uses    5;
    }    

    location /pictshare/ {
      proxy_pass http://127.0.0.1:8537/;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      if ($request_uri ~ \.(?:ico|gif|jpe?g|png|webp|bmp|mp4)$) {
        add_header Cache-Control "public, max-age=31536000, immutable";
      }   
    }

    location /iframely/ {
      proxy_pass http://127.0.0.1:8061/;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Anonymize IP addresses
# https://www.supertechcrew.com/anonymizing-logs-nginx-apache/
map $remote_addr $remote_addr_anon {
  ~(?P<ip>\d+\.\d+\.\d+)\.    $ip.0;
  ~(?P<ip>[^:]+:[^:]+):       $ip::;
  127.0.0.1                   $remote_addr;
  ::1                         $remote_addr;
  default                     0.0.0.0;
}
# log_format main '$remote_addr_anon - $remote_user [$time_local] "$request" '
# '$status $body_bytes_sent "$http_referer" "$http_user_agent"';
access_log /var/log/nginx/access.log main;
`

**Comment by yuri25** [comment]
![carbon](https://user-images.githubusercontent.com/253228/84153852-0cbc9a00-aa6f-11ea-9f4d-72912094509f.png)

**Comment by yuri25** [comment]
Please help me set up my config Nginx correctly, you probably need to remove something from it.

**Comment by dessalines** [comment]
You didn't copy that nginx file correctly, for some reason you changed your proxy_pass addresses from `0.0.0.0` to `127.0.0.1`, which means it won't be available over the internet.

**Comment by yuri25** [comment]
Ok, now I’ll try to change to back to 0.0.0.0

**Comment by yuri25** [comment]
Changed everywhere 127.0.0.1 to 0.0.0.0 - unfortunately the result is the same ...:(

**Comment by Nutomic** [comment]
What is all that in the beginning? You probably need to delete everything up to `proxy_cache_path ...`.

**Comment by yuri25** [comment]
I will delete as you advise ... I added the config Nginx from the lemmy to the existing one ... But it looks like some kind of problem will be with the certificates. I'll try different options ...

**Comment by yuri25** [comment]
For some reason, the problem appeared in these lines:
# listen 443 ssl http2;
   listen [2a01: 48a0: 4001 :: fa]: 443 ssl;
   listen 81.16.141.142-00-0043 ssl;
And deleted everything above proxy_cache_path
