### ISSUE TITLE
Add option to query /post/list by community_name in the API 

### ISSUE THREAD

**Issue by IronOxidizer** [LemmyNet/lemmy#800]
Currently clients must query post lists using a community_id which isn't always possible without first resolving community_name to community_id. This requires a query for /community which is an additional request in the critical chain resulting in increased load on the DB, API, and client connection.

**Comment by dessalines** [comment]
Okay once that PR is merged, you'll be able to do the `/post/list` and provide a `community_name`

**Comment by IronOxidizer** [comment]
Thanks for this! I'll be updating lemmy-lite accordingly. Feel free to close issue when PR is merged.
