### ISSUE TITLE
Some HTML titles don't load after refreshing

### ISSUE THREAD

**Issue by kartikynwa** [LemmyNet/lemmy#801]
If you load one of the following pages and then refresh, the document title doesn't update after the refresh:
- https://dev.lemmy.ml/communities
- https://dev.lemmy.ml/search
- https://dev.lemmy.ml/create_post
- https://dev.lemmy.ml/create_community

**Comment by revmischa** [comment]
Index page won't load for me, same error:
`Cannot read property 'enable_downvotes' of undefined`
Seeing the same thing

**Comment by dessalines** [comment]
I'm getting this a lot, I'll work on it next.
