### ISSUE TITLE
Remove 64-column-tables feature from Diesel

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#805]
Diesel takes up a large part of the compilation time for Lemmy, and is a major bottleneck. We could probably reduce the compilation time by disabling the 64-column-tables feature, and using 32-column-tables instead. There is only one table that is slightly over the limit (post_view), so we should be able to split that.

**Comment by Nutomic** [comment]
I tested this and it actually increased the time for a clean build by 10 seconds.

**Comment by dessalines** [comment]
Re-opening as it'll eventually be possible to remove this feature.

**Comment by Nutomic** [comment]
I opened #920 for this with some more details, so I think we can close this.
