### ISSUE TITLE
Discover sharedInbox

### ISSUE THREAD

**Issue by vpzomtrrfrt** [LemmyNet/lemmy#808]
It looks like Lemmy is currently assuming all instances have a sharedInbox at /inbox, which is not good. Per the AP spec, sharedInbox should be optional and is found in endpoints.sharedInbox on the Actor

**Comment by dessalines** [comment]
That's only if their user doesn't have a sharedInbox, which all lemmy clients should at least.

In general you should always use sharedInbox for all public activities: 

https://flak.tedunangst.com/post/what-happens-when-you-honk

Connecting to non-lemmy clients is way down the road.

**Comment by vpzomtrrfrt** [comment]
yeah, the "optional" part doesn't seem practically necessary, though it's technically required by the spec
