### ISSUE TITLE
Set up an email service.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#811]
The embedded emails are getting mostly blocked and denied, it'd probably be a good idea to just pay for an email service and use its smtp.

**Comment by Nutomic** [comment]
I could just setup an smtp relay on peertube.social, didnt hear about any problems with email there.

**Comment by dessalines** [comment]
Ya that'd be good. Maybe it's just the ml domain then that email services are blocking.

**Comment by alltheseteeth** [comment]
We're running an instance of [mailcow](https://github.com/mailcow/mailcow-dockerized) on a separate server. With a focus on security IE DDoS protection, making sure the source IP is masked we found to be important.

**Comment by dessalines** [comment]
This is done.
