### ISSUE TITLE
Better search UI?

### ISSUE THREAD

**Issue by Icy-Thought** [LemmyNet/lemmy#814]
Rather than having a button redirect to a search page, why not place a search icon next to the notification-bell icon (on the top right corner) that expands into a search bar when clicked? 

For advance search one could enter an empty search to redirect to the search page **or** have flair button for people to select the type of search they want to perform **or** have people search and later filter out based on what their intentions was with their search.

Concepts that could showcase my intentions are:
- https://codepen.io/aaroniker/pen/XyXzYp
- https://codepen.io/ = own search functionality.

**Comment by dessalines** [comment]
Hrm.... I'd be willing to accept a PR, as long as it responsive for mobile like the other ones. Also I've been trying to not do any animations or anything that would add browser slowness.

**Comment by arrudaricardo** [comment]
Can I work on this ?

**Comment by dessalines** [comment]
Sure thing.
