### ISSUE TITLE
Support for adding moderators/admins to communities?

### ISSUE THREAD

**Issue by taminaru** [LemmyNet/lemmy#815]
Hello, unless I am mistaken I have noticed that you cannot add moderators or admins to communities you have created. Is this already a feature or is it planned for the future?

Apologies in advance for any misunderstandings.

**Comment by Nutomic** [comment]
You can do it, the actions are available on the comments of that user.

**Comment by taminaru** [comment]
> You can do it, the actions are available on the comments of that user.

Ah, I see. Thank you, that worked!

**Comment by taminaru** [comment]
Closing this issue now.
