### ISSUE TITLE
Comment Preview Too Similar To Post's Text

### ISSUE THREAD

**Issue by Scupake** [LemmyNet/lemmy#817]
![2020-06-16_12-14](https://user-images.githubusercontent.com/61241021/84767917-2f990200-afcb-11ea-914d-eec51854a592.png)
I suggest putting the preview in a box, because changing the font would take a long time due to the amount of themes that Lemmy has.

**Comment by dessalines** [comment]
I'm very confused, that's not the comment, that's just two lines in the post body. 

There's no "comment preview".

**Comment by dessalines** [comment]
Hrm, that's vaporwave-dark theme right? Why is it rendered wrong on your browser? What's your browser?

![image](https://user-images.githubusercontent.com/930215/84909223-6d596180-b083-11ea-801a-4a4ac7e01c08.png)

**Comment by Nutomic** [comment]
@dessalines It happens when you click the preview button (also with the default dark theme).

**Comment by dessalines** [comment]
Ohhh okay.
