### ISSUE TITLE
Change main branch and some terms.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#820]
- [x] Change master to main
- [x] Change whitelist/blacklist to allowlist, blocklist

**Comment by Nutomic** [comment]
I was thinking we should wait until federation branch is merged before renaming to main. I have already renamed the config option for federation, do we have any other blacklist/whitelist?

https://yerbamate.dev/LemmyNet/lemmy/pulls/56

**Comment by dessalines** [comment]
I'm building that PR right now just to be sure. I found one other place with blacklist, i got it tho.

**Comment by dessalines** [comment]
Connected services to change it:

- [ ] Github
- [ ] Gitea
- [ ] Travis
- [ ] Weblate

**Comment by dessalines** [comment]
@Nutomic I got all these, but couldn't figure out the weblate. It unfortunately might require a whole new import.

**Comment by Nutomic** [comment]
I changed Weblate to main (was under [this url](https://weblate.yerbamate.dev/settings/lemmy/lemmy/#vcs)).
