### ISSUE TITLE
Deleted communities still show up in user's profile

### ISSUE THREAD

**Issue by TheEvilSkeleton** [LemmyNet/lemmy#824]
so i created a community at Lemmy called `test_` to test some of the moderating features, but i decided to delete it. Unfortunately, when i deleted it, it still shows in my profile. I also tried visiting my profile without an account, and it still shows up

![image](https://user-images.githubusercontent.com/50847364/85208918-fda4da00-b301-11ea-86ca-6f0f61e7cdb2.png)

![image](https://user-images.githubusercontent.com/50847364/85208931-0d242300-b302-11ea-9e59-182792ee8dc0.png)

**Comment by dessalines** [comment]
Its fine for deleted communities to still show up, it just means that no new posts can be added. They can be restored by their creator at any time. I'm not sure if they should still show up in your user profile... I think they probably should, both so someone can see if you're making spam communities, and if you ever want to restore them.

**Comment by TheEvilSkeleton** [comment]
> I'm not sure if they should still show up in your user profile... I think they probably should, both so someone can see if you're making spam communities, and if you ever want to restore them.

I personally think that they should be gone. It gets annoying to see `test_` whenever I look at my profile, but might just be me

**Comment by dessalines** [comment]
Closing unless this is something a lot of people want, but to me, I'd like to have my deleted communities listed in my profile so I could restore them when/if I want.
