### ISSUE TITLE
Lack of capitalization in words

### ISSUE THREAD

**Issue by TheEvilSkeleton** [LemmyNet/lemmy#825]
Related to https://github.com/LemmyNet/lemmy/pull/778, there are words that lack capitalized letters. You can watch this video as a visual representation: https://www.invidio.us/watch?v=WSlO9dki7ao&feature=youtu.be

Some examples (in the video) being:

- "save" to "Save"
- "unsave" to "Unsave"
- "cross-post" to "Cross-post"
- "archive link" to "Archive link" or "Archive Link"
- "upload video" to "Upload video" or "Upload Video"

etc.

**Comment by dessalines** [comment]
All of those used to be the text, not icons, and everything in the action bar should be lowercase. This is the standard on reddit and lobste.rs at least, `font-weight-bold` and lowercase.
