### ISSUE TITLE
API for external front ends

### ISSUE THREAD

**Issue by dominikaaaa** [LemmyNet/lemmy#828]
Hi, I'm not sure if this is the place to ask, as https://dev.lemmy.ml/ is just one instance of Lemmy, so I'm not sure if this should be a request for that or Lemmy as a whole, but I was wondering if there's documentation to an external API, as I was interested in creating an Android app for it. 

If there isn't one, having support for that would be nice to have.

**Comment by Nutomic** [comment]
Thats cool! The API docs are here: https://dev.lemmy.ml/docs/contributing_websocket_http_api.html

However, it is unstable and probably far from ideal now, so I suggest you join our [dev chat on Matrix](https://matrix.to/#/!tUnhsBRCsiePXfsIGe:matrix.org).

Are you planning to write this from scratch, or fork an existing app?

**Comment by dominikaaaa** [comment]
Was planning on making it from scratch. I use Joey for reddit heavily so I'd take UI inspiration from them, but that's closed source. I'll definitely get matrix :3

**Comment by Nutomic** [comment]
@dessalines suggests using Slide, but personally I use RedReader. Anyway I think you would save a ton of work by forking an existing app and rewriting the API client, instead of writing the whole app from scratch.

[Also check out this issue](https://github.com/LemmyNet/lemmy/issues/151)

**Comment by dominikaaaa** [comment]
It appears that slide wouldn't have interest in maintaining that officially, and I'd rather not maintain a fork of an app which has a much large audience right off the bat (which I'm fine with, I've maintained a few large projects). 

I'll look into RedReader, and if I don't like it I guess I'll keep this as a summer project to do :p

**Comment by dessalines** [comment]
I based the main web app off of slide and boost, but joey looks really nice too. Anyway, anything is better than a web app for mobile. Let me know if you need any help on the way. BTW here's our dev chat: https://matrix.to/#/!tUnhsBRCsiePXfsIGe:matrix.org?via=matrix.org&via=synapse.vpzom.click&via=asonix.dog
