### ISSUE TITLE
"Mark all private messages as read" button does not trigger live update

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#830]
If you have some unread private messages and click "mark all as read", nothing changes in the UI. You need to reload the page manually to see that the action was successful.

**Comment by dessalines** [comment]
I can't reproduce this for some reason... When I click mark all as read, its clearing them out. The code looks like its correctly setting them as empty lists too.

**Comment by dessalines** [comment]
I'll change it so it does this without waiting for the response tho.
