### ISSUE TITLE
WSL2 pict-rs IO error: Permission denied

### ISSUE THREAD

**Issue by ceecx** [LemmyNet/lemmy#831]
I'm using WSL2 with Docker Desktop and according to the documentation to install it, he gives the error:
![image](https://user-images.githubusercontent.com/18570103/85375009-3e9e2800-b568-11ea-8467-ee2d6688d709.png)

I was running successfully with pictshare before and I'm not sure which part of the permissions are wrong, how do I fix it? Thank you for being open source.

**Comment by asonix** [comment]
What user and group own the pictrs volume folder?

**Comment by ceecx** [comment]
> What user and group own the pictrs volume folder?
I used the Root user for the test environment, everything else is default.

**Comment by asonix** [comment]
The pictrs volume folder needs to be owned by 991:991 to work correctly with the container

**Comment by dessalines** [comment]
The ansible deploy does this automatically btw, but I think in docker unfortunately it does need a 

```
mkdir -p volumes/pictrs
sudo chown -R 991:991 volumes/pictrs
```

I'll add that to the docker install instructions.

**Comment by ceecx** [comment]
@dessalines @asonix 
Sorry I didn't double check it, it works fine now, thanks!

**Comment by kklot** [comment]
> The ansible deploy does this automatically btw, but I think in docker unfortunately it does need a
> 
> ```
> mkdir -p volumes/pictrs
> sudo chown -R 991:991 volumes/pictrs
> ```
> 
> I'll add that to the docker install instructions.

I installed with docker and did this but still have the same errors as the screenshot. I run locally, no changes make to the `docker-compose.yml`, no `nginx` running as well. What else could be done to fix this?

**Comment by dessalines** [comment]
You followed these instructions? https://lemmy.ml/docs/administration_install_docker.html#docker-installation

You'll need to `docker-compose restart`.

What error are you getting?

**Comment by kklot** [comment]
Yes, I followed that guide, the errors are exactly like this: 

> ![image](https://user-images.githubusercontent.com/18570103/85375009-3e9e2800-b568-11ea-8467-ee2d6688d709.png)

which means I can run the lemmy-ui fine, but cannot upload images.

**Comment by Nutomic** [comment]
Try to stop the container (`docker-compose down`), then make sure the folder permissions are correct as mentioned above, and starting it again.

**Comment by kklot** [comment]
Thanks, I tried that and also tried to remove and rebuild all but still getting the same error. This is the folders

```bash
cd ~/lemmy
ls -la volumes
drwxr-xr-x   4 user  staff  128  9 Jan 18:03 .
drwxr-xr-x   7 user  staff  224 12 Jan 01:09 ..
drwxr-xr-x   2 991     991     64  9 Jan 17:29 pictrs
drwx------@ 25 user  staff  800 11 Jan 23:58 postgres
```

**Comment by dessalines** [comment]
Might have to do with your postgres folder then? I have no idea what might be messed up with your docker install but mine has root group:

```
drwxr-xr-x  4   991 lp    4096 Jan  5 12:05 pictrs/
drwx------ 19    70 root  4096 Jan  6 10:42 postgres/
```
