### ISSUE TITLE
Cant close long notifications

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#834]
The close button is below the end of the screen, and scrolling doesnt move the notification. Should be enough to move the button to the top right instead. Maybe also add a "close all" button?

![Screenshot_2020-06-23 Lemmy](https://user-images.githubusercontent.com/1044450/85477360-ae80d280-b5a9-11ea-9454-69e5cb053cc1.png)

**Comment by dessalines** [comment]
Should these maybe only stay up for like 5 seconds anyway? There is still the notification bell.

**Comment by Nutomic** [comment]
Yes that would be good.
