### ISSUE TITLE
It would be nice to have a size limit on images for comments

### ISSUE THREAD

**Issue by SirLotsaLocks** [LemmyNet/lemmy#836]
I was told to post this here so here goes
In my limited experience with sending images in comments they end up huge and making it hard to talk around them or easily move on to the next comment. like [this](https://dev.lemmy.ml/post/34286/comment/6389) or [this](https://dev.lemmy.ml/post/35059/comment/7586)

It would be nice to have an option to shrink them to a reasonable size so they are more like this

**Comment by dessalines** [comment]
I had it at `90vh`, now I've lowered it to `40vh`, looks a lot better now.
