### ISSUE TITLE
Mute terms

### ISSUE THREAD

**Issue by kixiQu** [LemmyNet/lemmy#837]
For comments, I would think what would be ideal is to have that comment (and any replies) folded on page load. For posts, maybe just show nothing at all. Posts seem more important to mute than comments. It could be just on the user's home page, and show the posts if you navigated to that community--or not show anywhere. 

An example of a use would be for someone who gets overwhelmed by coronavirus news to be able to still subscribe to general news communities. 

Another use might be to avoid media spoilers, because even image previews / article titles can carry a lot of information. (Google news suggestions have spoiled things for me before) 

(I am not totally sure what "unstructured critique" means exactly but I only mean to suggest this enter the feature backlog)

**Comment by Nutomic** [comment]
I dont think this functionality makes sense in a forum.
