### ISSUE TITLE
Select a Community improvements

### ISSUE THREAD

**Issue by realpanzer** [LemmyNet/lemmy#839]
Can we get:

- a possibility to post in more than one community at once if we want to (let say we have three boxes with Select a community instead of just one)
- possibility to search-as-you-type within the box as the list is getting longer and longer and it is tiresome to go through the whole list and find the appropriate Community - I just rather select some Community from the top instead).

**Comment by Nutomic** [comment]
With the second point, you mean the community selection on `/create_post`? That one is already "search as you type", but only on desktop.

**Comment by realpanzer** [comment]
Ah, Ok. I am on mobile ...
