### ISSUE TITLE
Switch to a more lightweight HTTP client

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#840]
We are currently using isahc, but it is quite heavy because it bundles curl. We should switch to a more lightweight library instead, because we really dont need all the features that curl brings.

For this reason we used attohttpc before, but that one causes some weird crashes for @dessalines (I cant reproduce it). The error message is `Internal Server Error: Error(Io(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }))`, in `apub::fetcher::fetch_remote_object()`.

**Comment by dessalines** [comment]
Here's the branch that contains the conversion, since that work is pretty much done. https://github.com/LemmyNet/lemmy/tree/attohttpc_federation_merge_from_master

**Comment by dessalines** [comment]
This is done now, its using the actix web client.
