### ISSUE TITLE
Update the example Kubernetes Deployment

### ISSUE THREAD

**Issue by nikhiljha** [LemmyNet/lemmy#842]
The provided Kubernetes config file references an old version of Lemmy. Replacing it with `latest` causes it to no longer function (something to do with the PORT environment variable being set to a string by k8s).

https://github.com/LemmyNet/lemmy/blob/96f133750dd295d62672beec38232f81764cade8/docker/k8s/lemmy.yml#L28

**Comment by dessalines** [comment]
I'm going to close this, and also remove our kubernetes support, it was added by someone who then ghosted, and no one else has kept it up.
