### ISSUE TITLE
admin page won't load

### ISSUE THREAD

**Issue by nikhiljha** [LemmyNet/lemmy#844]
Everything else functions just fine, deployed with Kubernetes (kompose + docker-compose.yml) and copied over the environment variables in lemmy.yml in the k8s folder.

The admin page will not load, and the logs read...

```
[2020-06-26T23:17:45Z ERROR lemmy_server::websocket::server] Error during message handling No such file or directory (os error 2)
```

when I visit the `/admin` page.

**Comment by dessalines** [comment]
the `front_end_dir` isn't being set to the right location. 

I forget who made the kubernetes deployment, but I don't know anything about kubernetes so I can't support it.

**Comment by nikhiljha** [comment]
Can it be set via an environment variable? I can fix it and PR if I knew where to set that.

**Comment by dessalines** [comment]
Try `LEMMY__FRONT_END_DIR`
