### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by physkets** [LemmyNet/lemmy#850]
Can the website be turned into a PWA, so that users can easily "add to home screen" and use the website like an app?

**Comment by dessalines** [comment]
Many mobile browsers will let you do this now, such as Firefox nightly preview.

But no, we aren't going to make a wrapper PWA, that would just take up another browsers worth of RAM and battery drain on your phone. There are plans to build an android app tho, and the API is open.

**Comment by physkets** [comment]
> Many mobile browsers will let you do this now, such as Firefox nightly preview.

That is exactly what I'm talking about. I'm using FF Preview 5.2.0 on Android, and when I open websites that are PWA compatible, FF provides an option to "Install", as opposed to just "Add to Home screen" which is what it shows for https://dev.lemmy.ml/

So my question is about whether it can be made 'installable'.

**Comment by dessalines** [comment]
Looks like this is possible here: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

If anyone wants to take a crack at it, go right ahead.

**Comment by kartikynwa** [comment]
Where should this `.webmanifest` file go in the repo? I can build a first draft which we can build upon from there.

**Comment by dessalines** [comment]
The `ui/assets` folder.

**Comment by dessalines** [comment]
This is done.
