### ISSUE TITLE
[DOCS/HTTP API] Missing explanation of aggregate type

### ISSUE THREAD

**Issue by cage2** [LemmyNet/lemmy#851]
Hi!

I found this project interesting and inspiring, thank you!

I am starting to study the HTTP API but i was not able to find a way to understand the structure of many types like (for example): `CommunityFollowerView`.

I can not find documentation of that type i found this in https://dev.lemmy.ml/docs/about.html (maybe it is my fault, though).

Instead i found this in the code:

https://github.com/LemmyNet/lemmy/blob/4c1cb5999cad496714cec67f101be38cd281d416/server/src/db/community_view.rs#L7

Does this code maps the JSON structure from the API? If yes, is this the preferred way to get documentations about these structures?

Thank you very much!
Bye!
C.

**Comment by Nutomic** [comment]
The [API docs are here](https://dev.lemmy.ml/docs/contributing_websocket_http_api.html), but they might be incomplete or outdated. Anyway the API is unstable so you will probably have to look at the Rust code for the time being.

You are right, API responses are identical to `db::*_view` structs.

**Comment by cage2** [comment]
Hi!

Thank you very much, i know near nothing about rust but those specific part code seems not too difficult to understand to me! 

Thank you also for make clear that the API is not yet stable!

Bye!
C.
