### ISSUE TITLE
Dont show total karma in search results

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#853]
![Screenshot_20200628_134103](https://user-images.githubusercontent.com/1044450/85946503-4b3dca00-b934-11ea-9661-eab8e4f76f12.png)

We removed this from the user profile a while ago to prevent negative effects like karma farming. We should do the same here and not display the overall points.

**Comment by jmarthernandez** [comment]
I can pick this up

**Comment by Nutomic** [comment]
@jmarthernandez sure, go ahead.

**Comment by jmarthernandez** [comment]
Opened a PR here https://github.com/LemmyNet/lemmy/pull/883.  Sorry, I don't think I have access to link it to the issue properly

**Comment by Nutomic** [comment]
For that you just need to add it to the commit message, putting `(fixes #853)` at the end. But its not that important.
