### ISSUE TITLE
Don't count 400/500 status codes against rate limit

### ISSUE THREAD

**Issue by Aeolun** [LemmyNet/lemmy#858]
I am trying to build an application that uses the API, but I apparently messed up the register function, and now I'm stuck for an hour.

**Comment by Nutomic** [comment]
As a workaround, you could test with https://enterprise.lemmy.ml/ instead. Or run a local instance.

**Comment by dessalines** [comment]
This is a legit bug, but when building an application, please don't do API testing using production instances. You can set up a local instance for testing with a few lines: https://dev.lemmy.ml/docs/administration_install_docker.html

**Comment by Aeolun** [comment]
Fair enough. Thanks.

**Comment by dessalines** [comment]
I think this bug is fixed now by the correction of actix `real_remote_ip` in a recent commit.
