### ISSUE TITLE
Create comment/post with CTRL+ENTER in text box

### ISSUE THREAD

**Issue by Atemu** [LemmyNet/lemmy#860]
When I'm done writing, I would like to be able to press C-RET to post my submission instead of having to move my mouse and click the `Post` button.

**Comment by dessalines** [comment]
Tab+Enter

**Comment by NIXOYE** [comment]
CTRL + Enter would be great considering it's what used on most websites and most people will try to use ctrl + enter and wont really think to try tab + enter.
