### ISSUE TITLE
New comment in live update deletes my comment in progress

### ISSUE THREAD

**Issue by DShiller** [LemmyNet/lemmy#861]
I was typing a long comment on lemmy, and the thread live-updated to show a new comment. Instantly my comment, still in the box and not submitted, was erased.

I'm not sure if you need any more info, there's not much more to it, but please tell me if you need anything else to investigate this bug!

**Comment by dessalines** [comment]
Whats the version say at the bottom? I could've swore I've fixed this, and have tried everything to replicate it.

**Comment by DShiller** [comment]
> 
> 
> Whats the version say at the bottom? I could've swore I've fixed this, and have tried everything to replicate it.

Version 0.7.1 on the communism instance! I use Firefox 77.0.1 and Windows 10 64-bits.

**Comment by dessalines** [comment]
Yeah, this should be fixed in v0.7.2 onward, you might need to refresh the page.

**Comment by Nutomic** [comment]
Gonna close this, please comment or open a new issue if you still have the problem.

**Comment by Nutomic** [comment]
I just had this happen again (on dev.lemmy.ml), but it was unrelated to any new comment being posted.

**Comment by dessalines** [comment]
I did verify in a ton of new testing, that votes and resorts don't do it now... just replicating this has been really difficult bc I don't know what causes it.

**Comment by dessalines** [comment]
Okay I found what causes it (an EditComment), working on it now.

**Comment by dessalines** [comment]
Should be fixed in v0.7.7, being deployed now.
