### ISSUE TITLE
Consider implementing Federation Applications

### ISSUE THREAD

**Issue by asonix** [LemmyNet/lemmy#862]
A common moderation problem on Mastodon is that there's always a reaction to bad servers after federation has been ongoing for a while, potentially unnoticed. A way to solve this issue could be to implement a sort of "asking permission to federate" system, where a given server can request to federate with another, and that server's admins or moderators can accept or reject the federation request.

Before federation is accepted or rejected, the only content allowed could be a "Federate Server" message to the shared inbox, and after a "reject federate server" message is sent in reply, no further messages will be accepted. If an "accept federate server" is sent in reply, that could mean that any additional message may be exchanged between servers.

This could be further extended with "Undo Reject Federate Server" and "Undo Accept Federate Server" to bring federation between servers to the initial state.

**Comment by asonix** [comment]
as activitypub, this could likely be implemented as Follow to the Server Actor, although that specific message sequence is already in use by activitypub relay servers. I'm unsure whether managing federation requests with the same vocabulary would be compatible or not. My initial thoughts are "it's probably fine"

**Comment by VVelox** [comment]
This honestly strikes me as a very bad idea as the idea behind as it utterly breaks the idea of making a distributed system via making it problematic for one to setup one's own server. They have to go and then ask for any group/person they want to talk with.

This also just adds additional annoying to handle overhead for administration.

You don't know if who you are going to be federating with will turn out to be bad or not. Till after a problem has occured with spamming or the like, so the default is just to accept. This means you are having to do more work for no gain.

On top of that it means topics that make people uncomfy are less likely to be discussed or fleshed out properly given people are afraid of the admins of other servers deciding they are horrible and dropping federation, regardless of if the community they are part of is okay with them or not. In fact it does not even have to be a discussion on the server that is dropping federation. It can be entirely on two different ones not under that persons control.

**Comment by Nutomic** [comment]
I think its a good idea, something to add later after the initial federation release. This would probably be one of multiple options to handle federation, those who dont like it could go with an allowlist or blocklist of instances.
