### ISSUE TITLE
Fetching ActivityPub objects should be signed requests.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#868]
Currently, the history / user / community fetching are unsigned requests from the server directly. It would be nice for these to be signed like the standard posts.

**Comment by Nutomic** [comment]
This also means that users cant fetch ActivityPub objects from the server for testing purposes (cause the signing key is only stored on the server). You can see that on the link below. On the other hand, signed fetches would prevent crawlers from indexing the data. Maybe this should be optional, or only used for sensitive objects.

https://radical.town/users/felix/outbox.json
