### ISSUE TITLE
static files 404

### ISSUE THREAD

**Issue by IThawk** [LemmyNet/lemmy#873]
http://localhost:8536/static/assets/css/tribute.css

response: 404
how to solve;
I just run by : cargo run

**Comment by dessalines** [comment]
What did you run, which guide did you follow? 

And please use the docker development.

**Comment by IThawk** [comment]
@dessalines  how to deploy by docker?

**Comment by IThawk** [comment]
```llwei@DESKTOP-T4VRMU0:/mnt/d/workspace/language/rust/lemmy/docker/dev$ sh test_deploy.sh
test_deploy.sh: 2: set: Illegal option -
llwei@DESKTOP-T4VRMU0:/mnt/d/workspace/language/rust/lemmy/docker/dev$ ls
Dockerfile  docker-compose.yml  docker_update.sh  test_deploy.sh
llwei@DESKTOP-T4VRMU0:/mnt/d/workspace/language/rust/lemmy/docker/dev$ sudo docker build .
[sudo] password for llwei:
Sending build context to Docker daemon  6.656kB
Step 1/36 : FROM node:10-jessie as node
```

**Comment by dessalines** [comment]
This isn't enough information for me to help with anything.

The install guides are here: https://dev.lemmy.ml/docs/administration.html

**Comment by Nutomic** [comment]
If you need more help, please add info about your setup and logs, then reopen this issue.
