### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#881]
Should have some things about including logs and details about the setup, plus steps to reproduce. Anyone know a good one we can copy?

**Comment by RayBB** [comment]
Might want to add multiple issue templates:
1. for bugs
2. for feature requests
3. for questions/support

Here's an example for bugs:
https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

This repo also uses decent templates: https://github.com/wagtail/wagtail/issues/new/choose

**Comment by dessalines** [comment]
I do really like wagtails: https://github.com/wagtail/wagtail/tree/master/.github/ISSUE_TEMPLATE

I can do a PR for this sometime soon.

**Comment by dessalines** [comment]
This is done now. https://github.com/LemmyNet/lemmy/commit/1bd7218a7e750f430497720e6dd6ae9cd68acff8
