### ISSUE TITLE
Was there another DDOS today?

### ISSUE THREAD

**Issue by nathgit** [LemmyNet/lemmy#886]
I reloaded a lemmy tab I had opened earlier, & it gave the standard error that it couldn't connect to the server but other sites worked fine. Was that another DDOS or something else? I tried it again later on & it loaded normally. It makes it seem like lemmy is a target for some reason. That and the lack of a privacy policy #721 make me hesitant to sign up.

**Comment by Nutomic** [comment]
Yes, but we now moved to a different hoster that has ddos protection, and it already stopped an attack. So downtime shouldn't happen anymore (hopefully).

**Comment by nathgit** [comment]
Is it safe to join then? What kind of risks are there to users in DDOS attack other than just not being able to access the site? A site having 2 ddos attacks in less than a week is concerning.

**Comment by dessalines** [comment]
Its safe, it would only bring down the site.

**Comment by ceecx** [comment]
Regarding security and performance, I'd like to add CDN and 3rd party storage support (for uploaded files) to better bear the load overhead of the local server.

**Comment by dessalines** [comment]
I'd have to ask some security ppl on the pros/cons of a CDN, I know its faster for some static resources, but it comes with a security cost. Also its kinda nice not having to rely on them, because right now lemmy could even run (after its been installed), in a network without internet.

Our main issues right now are the DB, which I'm working on currently.

**Comment by ceecx** [comment]
> because right now lemmy could even run (after its been installed), in a network without internet.
I understand this, but it could be a fallback option to add it to the config file, with the option to enable or disable it. Same with the Twemoji source, the current CDN is not friendly to access in China, wish there were more sources available in the config. Changing the code makes it less convenient, and I actually like Lemmy a lot! I'm trying to get it to do more things.

**Comment by Nutomic** [comment]
I didnt know about the emojis, imo those should be served by Lemmy directly if possible (for privacy reasons).

**Comment by ceecx** [comment]
> I didnt know about the emojis, imo those should be served by Lemmy directly if possible (for privacy reasons).

That's a great option too.

**Comment by Nutomic** [comment]
Opened an issue for it: #895.
