### ISSUE TITLE
Front page UI Suggestions

### ISSUE THREAD

**Issue by marekmutch** [LemmyNet/lemmy#888]
<img width="1919" alt="Screen Shot 2020-07-02 at 12 36 45 PM" src="https://user-images.githubusercontent.com/7782373/86387315-016d2080-bc61-11ea-99d6-e0fc9ba2eacc.png">

<img width="1920" alt="Screen Shot 2020-07-02 at 12 36 57 PM" src="https://user-images.githubusercontent.com/7782373/86387320-0205b700-bc61-11ea-8d3f-0e81372c2bf3.png">

Hello. I'm a UI/UX designer and I thought I'd offer a few suggestions to help improve the UI. I'm new to contributing so I'm not sure if there's a process for UI changes or if someone is in control of it - I'm primarily an Angular front-end dev but have been thinking about contributing here. Right now I just overwrote some styles with a browser extension to adjust the design.

Here's a rundown of the adjustments I made in my screenshots:

Body: 
- `#fff` background on light mode

Top nav:
- More vert padding
- More padding between items
- Login/Sign-up primary button - _to draw a little more attention_
- Site name `1rem` font size

Buttons/input:
- Remove `-sm`
- #00C853 background, no border on light theme
- `0.25rem` border-radius

List:
- increase margin on `hr`s - _increased spacing between groups can increase scannability, allowing users to look through content quicker and retain more from skimming_
- add small margin above `.details`
- reduce size of avatars to `1.25rem`
- `-.25rem` top margin on avatars
- background on svg thumbnails - `rgba(0,0,0,.04)` on light mode, `rgba(255,255,255,.05)` dark mode - _this increases the visual consistency between img posts and icon thumbnails and a defined clickable area for icon thumbnails_
- vert padding and min-height on svg thumbnails to make the icons smaller - _the icons currently draw a lot of attention due to their size and contrast, they should blend in more as secondary information to the title_
- `.25rem` border radius on thumbnails (it was on dark mode only)

Cards: 
- no background
- `.25rem` border radius
- border color `rgba(0,0,0,.1)` on light mode

Seems like dark mode has gotten a little more love than light mode - there's some things that could be adjusted to apply to both, such as border radii. Hope to dive in to help some day

**Comment by dessalines** [comment]
Thx, these are some good suggestions. Its mostly helpful to do these in a PR on the code.

Some of the color stuff would require going into the actual themes... there are ~8 current themes, they would need manual editing. A lot of the other stuff (esp spacing) could be done via bootstrap classes in the `.tsx` components.

I don't have time for this rn tho (federation and DB work), but once you get a chance to dive into the `.tsx` files, you could make a PR.

**Comment by ceecx** [comment]
Amazing contribution! I think it looks very nice, I wish there were more front end options, and I'm trying to modify it, but I think you did it better!

**Comment by marekmutch** [comment]
@dessalines thanks for the info about what to look into. I'll take a look at the code to see if I can put together a PR sometime 👍 

@ceecx glad you like it! feel free to code any of my suggestions - you can tag me if you want some feedback :)

**Comment by ceecx** [comment]
Waiting for your PR results :)
