### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by ceecx** [LemmyNet/lemmy#889]
I'm trying the OpenLiteSpeed proxy Lemmy and seem to be having some problems uploading images.
Through the console I see `POST domain/pictrs/image 404 (Not Found).`

Posting my configuration:
`OpenLiteSpeed 1.7.2`
![image](https://user-images.githubusercontent.com/18570103/86408489-ab908b00-bce9-11ea-94c9-b8a22644e9a6.png)
![image](https://user-images.githubusercontent.com/18570103/86408513-b5b28980-bce9-11ea-96b7-00b203fffccf.png)
![image](https://user-images.githubusercontent.com/18570103/86408519-bcd99780-bce9-11ea-812d-8311fad5abc3.png)

Other than that, I think everything else is fine.

**Comment by ceecx** [comment]
Are there actually plans to support external storage? I've gotten used to putting uploaded files in reliable cloud storage.

**Comment by dessalines** [comment]
Make sure you do the `chown` commands listed in the guide: https://dev.lemmy.ml/docs/administration_install_docker.html

You could always forward the pict-rs routes from the nginx.conf we provided to another instance, or symlink your pict-rs volumes folder to external storage.

**Comment by ceecx** [comment]
I tried to get OpenLiteSpeed permissions, but `POST http://domain/pictrs/image net::ERR_CONNECTION_ RESET`

**Comment by ceecx** [comment]
> Make sure you do the `chown` commands listed in the guide: https://dev.lemmy.ml/docs/administration_install_docker.html
> 
> You could always forward the pict-rs routes from the nginx.conf we provided to another instance, or symlink your pict-rs volumes folder to external storage.

I swear I did it according to the documentation and it's running with the correct `991:991` user.

**Comment by dessalines** [comment]
Post your nginx.conf please

**Comment by ceecx** [comment]
> Post your nginx.conf please

I said I try to deploy Lemmy using OpenLiteSpeed, and if you don't want me to use it, You can tell me: you only offer Nginx help. But don't ask me to post a configuration of Nginx knowing that I don't use Nginx, thank you.

**Comment by ceecx** [comment]
BTW: Even if I don't use any reverse proxies, with ip:port it still returns the above given Error message.

**Comment by dessalines** [comment]
We can only offer nginx help, sorry. Its necessary for both the pictures and the embeds. Follow these instructions to get it working. https://dev.lemmy.ml/docs/administration_install_docker.html

If you can translate this to whatever reverse proxy you're using, then it should work: https://raw.githubusercontent.com/LemmyNet/lemmy/master/ansible/templates/nginx.conf

**Comment by dessalines** [comment]
You can re-open this if you need any more help.
