### ISSUE TITLE
moderators should be able to edit other users posts

### ISSUE THREAD

**Issue by toogley** [LemmyNet/lemmy#890]
for instance, if a post contains a bad link or picture, whatever but the rest of the post is fine - then it should be possible to just remove the bad part.

**Comment by dessalines** [comment]
Hrm I'm not sure about this one. I think the safest thing is to remove that post / comment, and tell the creator to edit it, then you can restore it.

Something just feels icky to me about mods and admins being able to literally overwrite others posts.

**Comment by mpfaff** [comment]
Perhaps a "mod notes" feature? Kind of like how Google Docs (and others) handles comments, so a portion of text has a footnote attached with the mod's edit?

**Comment by dessalines** [comment]
They can always just make a comment tho, which is clearer anyway.
