### ISSUE TITLE
Source code of themes

### ISSUE THREAD

**Issue by commagray** [LemmyNet/lemmy#893]
Hi!

Maybe I'm blind, but I don't see source code at `ui/assets/css/themes`. Only compiled `.min.css` and a few available with `.scss`. May I have rest of the themes, please?

Thanks.

**Comment by dessalines** [comment]
Many of them are default themes from bootswatch: https://bootswatch.com/ , which has both the scss, and can generate the `.min.css` files.

I haven't gotten around to adding a bootstrap theme generation from the scss with fuse-box.

**Comment by dessalines** [comment]
I added the `scss` for darkly and litely in the assets folder.
