### ISSUE TITLE
Dont load emojis from external CDN

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#895]
Emojis are loaded from `twemoji.maxcdn.com`, which is bad for privacy and will break if that domain is not reachable for whatever reason (eg the domain might be blocked in China). We should serve them directly from Lemmy instead.

**Comment by ceecx** [comment]
I think this option is acceptable, and the default could be changed to load from local, plus it would be better if the CDN address could be freely enabled (modified) via the config file.

**Comment by igalic** [comment]
with pict-rs, Lemmy has half a CDN
it that was set to a different (sub) domain, that would count, in the eyes of the browser, as a CDN

**Comment by dessalines** [comment]
Ya good call... if any front end devs can help with this, let me know.
