### ISSUE TITLE
The Chinese translation has been updated.

### ISSUE THREAD

**Issue by ceecx** [LemmyNet/lemmy#896]
I saw that some of the vocabulary is not suitable for daily use in China, it is confusing, in order to make it work better for Chinese users, so I updated the translation.

[https://weblate.yerbamate.dev/projects/lemmy/lemmy/zh_Hans/](https://weblate.yerbamate.dev/projects/lemmy/lemmy/zh_Hans/)

**Comment by Nutomic** [comment]
Thanks, but translations are updated automatically with every release so there is no need to do anything else here.

**Comment by dessalines** [comment]
Thanks for updating too @ceecx !
