### ISSUE TITLE
FATAL:  password authentication failed

### ISSUE THREAD

**Issue by 153** [LemmyNet/lemmy#897]
I am following the install process [for docker users](https://dev.lemmy.ml/docs/administration_install_docker.html). I created a new postgres user named lemmy and set its password. I set its password in the `lemmy.hjson` file. Now I repeatedly get this error: 

`lemmy_1     | [2020-07-03T15:19:04Z ERROR r2d2] FATAL:  password authentication failed for user "lemmy"`

**Comment by Nutomic** [comment]
You set the password in `docker-compose.yml`, and you did that before running `docker-compose up -d` for the first time?

**Comment by 153** [comment]
Oh no, I didn't! I just fixed that. I already ran `docker-compose up -d`, what do I do? 

Thank you for the help!

**Comment by 153** [comment]
Now when I run `docker-compose up -d`, I simply get this error message when I go to the URL: 
`502 Bad Gateway`

I am using the included nginx conf in the [Install with Docker](https://dev.lemmy.ml/docs/administration_install_docker.html) guide with the proper hostname set

**Comment by dessalines** [comment]
Log please.

**Comment by 153** [comment]
```
postgres_1  | 2020-07-03 18:21:58.111 UTC [661] FATAL:  password authentication failed for user "lemmy"
postgres_1  | 2020-07-03 18:21:58.111 UTC [661] DETAIL:  Password does not match for user "lemmy".
postgres_1  |   Connection matched pg_hba.conf line 95: "host all all all md5"
```

**Comment by dessalines** [comment]
You need to start from scratch again, and set those passwords before you start the services.

**Comment by 153** [comment]
I know absolutely nothing about docker or postgres. sorry for bugging you. Should I delete my postgres user and recreate it? Is there a way to uninstall the docker image or can I run the `docker-compose up -d` command to re-install? 

Sorry for being a pain, I appreciate the support

**Comment by dessalines** [comment]
That's okay :)

```
sudo docker-compose down
sudo rm -rf volumes
```

And then follow the guide again.

**Comment by 153** [comment]
Thank you again @dessalines. I'll close this issue now.
