### ISSUE TITLE
CSS no longer rendering correctly in Pale Moon

### ISSUE THREAD

**Issue by gitbugged** [LemmyNet/lemmy#898]
Up until recently, the site worked fine in the [Pale Moon](https://www.palemoon.org) browser.

However, a recent update to the site caused it to look like this: https://i.imgur.com/kRC4hgi.jpg

The entire style sheet is essentially white. If there has been a recent underlying API/framework update perhaps it could be correlated with [UXP](https://github.com/MoonChildProductions/UXP) developers.

Thanks!

**Comment by dessalines** [comment]
Dupe of #570
