### ISSUE TITLE
Markdown footnotes support

### ISSUE THREAD

**Issue by mpfaff** [LemmyNet/lemmy#903]
Support for markdown footnotes using Pandoc's syntax would be really nice for posts talking about scientific publications, or debates where the user needs to provide sources for statistics or studies.

For example:

```markdown
Some text that needs a citation[^1].

[^1]: https://scientificstuff.com/article/the-source-article
```

Should be rendered as:

```markdown
Some text that needs a citation[¹](#footnote_1).

---

1. [^](#cite_1) https://scientificstuff.com/article/the-source-article
```

Some text that needs a citation[¹](#footnote_1).

---

1. [^](#cite_1) https://scientificstuff.com/article/the-source-article

where `[¹](#footnote_1)` should link to the footnote at the bottom and `[^](#cite_1)` should link back to the text that cited the footnote. Please keep in mind that this is just a hack to show the general idea of how it looks, and it should obviously be implemented by the parser.

https://www.flutterbys.com.au/stats/tut/tut17.3.html#h2_29 shows some examples of the output Pandoc generates, though I'm not sure if it's up to date.

**Comment by dessalines** [comment]
That isn't in any markdown spec, just some extra addition that pandoc added. You're able to replicate this though through markdown if you like.

Otherwise, you could open up an issue with our markdown parser, [markdown-it](https://github.com/markdown-it/markdown-it), but this isn't anything that we can support directly.

**Comment by mpfaff** [comment]
@dessalines I wasn't suggesting that the full citation extension be added, just the footnote one. What do you mean about it not making sense for web? Wikipedia already uses bottom-of-page citations for web.

I'll go have a look over at markdown-it and see that they think.
