### ISSUE TITLE
Add admin ability to "purge" posts / comments.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#904]
This removes any trace of a thing, and doesn't add any info about it to the modlog (runs an actual database delete). Should only be used for really heinous things. "Purge" seems like a good term for it.

Obviously its currently possible to do this in the database directly.

#891

**Comment by rfwatson** [comment]
Perhaps some generic entry should still be added to the modlog, at least by default?

It feels like the kind of feature that could easily be abused/allow users to lose trust in the platform

**Comment by dessalines** [comment]
Hrm... yes that's possible. It'd be a very generic line like: `X mod purged a comment / post`

**Comment by AdaephonBen** [comment]
Can I have a crack at this?

**Comment by dessalines** [comment]
Sure thing! The main difficulty is I think this requires another `ModAction` table, similar to the other ones, but without a foreign key to a comment_id or post_id (since the purge will delete that item from the DB). That requires a DB migration, a view, and more tables in diesel in `moderator.rs` (as well as unit tests in there), and `moderator_views.rs`. This is necessary so on the modlog we can at least show the message `Mod X purged an item on this date`.

The other stuff should be pretty straightforward, adding an endpoint.

I've gotten a lot of requests for people to purge their users too, so I think not just posts and comments, but also user and communities should be purgeable as well.

The API could either add separate endpoints, but it might be easier just to have the API be

```rs
pub struct ModPurge {
  community_id: Option<i32>,
  post_id: Option<i32>,
  ...
```

**Comment by dessalines** [comment]
[hmu on matrix if you need any help](https://matrix.to/#/@happydooby:matrix.org).

**Comment by dessalines** [comment]
@AdaephonBen any updates?

**Comment by dessalines** [comment]
A permadelete should also remove the pictures from pictrs. Dependent on #1276

**Comment by dessalines** [comment]
Also any community or user deletion ( or purge if we do that ) should delete all banner / avatar / sidebar images from pictrs.

**Comment by Nutomic** [comment]
> Also any community or user deletion ( or purge if we do that ) should delete all banner / avatar / sidebar images from pictrs.

I think that should be optional, with a checkbox similar to the "Remove Posts and Comments" box when banning a user.

**Comment by dessalines** [comment]
This is done now by the above merge.

**Comment by maltfield** [comment]
Is Lemmy currently tracking when items are deleted from the mod log?

I think it's ok that each instance has the choice to be less transparent, but I think it's just as important that users are able to see which instances are "sweeping their tracks" more than others.

**Comment by maltfield** [comment]
@dessalines is it possible to get a count (or ratio) of all the entries purged from the modlog by querying the API?

Then users can see which instances have mods that "cover their tracks" more often than other instances.

**Comment by Nutomic** [comment]
You can get the full mod log from `/api/v3/site/modlog`
