### ISSUE TITLE
Proposal to redesign the lemmy logo to appel to a larger audience 

### ISSUE THREAD

**Issue by Scaledi** [LemmyNet/lemmy#912]
my logo idea is here
https://dev.lemmy.ml/post/36934
it is the mouse whiskers in a minimalistic style, somthing that many sites are adopting
I am willing to redesign it, as I feel like the lines might be a bit too... thin?

**Comment by Nutomic** [comment]
I'm not a fan of that personally, its way too minimalist. Would be better to keep the mouse mascot.

**Comment by mtoniott** [comment]
I do agree that a more clean / minimalistic logo is needed to appeal to a larger audience, but I'm not a fan of it either.  Maybe at some point lemmy should make a new logo contest to find a more modern one ?

**Comment by mtoniott** [comment]
I tried things by trying to make a cleaner version of the current logo. It is I think a bit better but still not perfect.
![logo3](https://user-images.githubusercontent.com/54251266/87189251-9d95c800-c2f0-11ea-900f-d5174a4976cf.png)
![logo4](https://user-images.githubusercontent.com/54251266/87189268-a2f31280-c2f0-11ea-97f5-959da3a919ff.png)

![withtext1](https://user-images.githubusercontent.com/54251266/87189353-c9b14900-c2f0-11ea-90da-ad9980779118.png)
![withtext4](https://user-images.githubusercontent.com/54251266/87189361-cb7b0c80-c2f0-11ea-841e-7217ad1adba1.png)
(fonts are Ardeco and gravity, one is under SIL OFL 1.1 and the other under CC-BY-4.0).

**Comment by Scaledish** [comment]
I like it, but not the orange, maybe transparency would work better there

**Comment by Datdus** [comment]
I think Lemmy's current logo is stronger and more recognizable than your proposal. I am also of the opinion a logo should be timeless. I don't think jumping on a minimalist design trend is a very good idea. That said, Lemmy's logo is already pretty minimalist. It's honestly fine.

Do be careful to not get sued by Disney. They're pretty aggressive when it comes to protecting their Disney ears.
