### ISSUE TITLE
"Next" Button for Pagination Sometimes Does Not Appear

### ISSUE THREAD

**Issue by lotus42** [LemmyNet/lemmy#928]
![Screen Shot 2020-07-09 at 6 52 37 PM](https://user-images.githubusercontent.com/6904118/87098531-83d38280-c215-11ea-8677-93282fdf1afb.png)

### Issue Summary

Sometimes the **Next** button does not appear under conditions where it should. A refresh usually resolves the issue until it eventually happens again.  

### Steps to Reproduce

* Paginating through pages of Lemmy posts it happens on occasion
* It is inconsistent- frequency varies so it can be difficult to easily reproduce

### Technical details

* Firefox 78.0.1, macOS 10.15.5 on iMac 2013

**Comment by dessalines** [comment]
This should be fixed by #927
