### ISSUE TITLE
Single Signon  with Pleroma

### ISSUE THREAD

**Issue by Vibhigupta** [LemmyNet/lemmy#933]
I want to create account of my instance user with same credentials on lemmy as well, I run Pleroma so I wanted my instance doesn't have to sign up again just login with same credential.

**Comment by dessalines** [comment]
That's not how federation works. 

You sign up with a user on one instance, then you can follow users on other instances with the account you already made. Lemmy won't support user following for a long time tho.

**Comment by Vibhigupta** [comment]
I think, you didn't understand my question or I have used wrong tittle.

I own one pleroma instance and I don't want my user to sign up again on lemmy instance, they can simply use pleroma credentials and login in lemmy. It's not related to federation 

I have seen this with mastodon user can login on xmpp server with same credentials on mastodon account

**Comment by dessalines** [comment]
We're not going to support multiple signups. 

> mastodon user can login on xmpp server with same credentials on mastodon account

oauth is really out of scope for us right now.

**Comment by Cam-B** [comment]
Understood that this is out of scope for now but just wanted to add the comment that I would love to see Oauth and OIDC too :)
