### ISSUE TITLE
user created account 39 minutes ago but is celebrating cakeday

### ISSUE THREAD

**Issue by DShiller** [LemmyNet/lemmy#934]
Just noticed that this user: https://communism.lemmy.ml/u/eswtf created their account 39 minutes ago but their profile says it's their cakeday.

Surely cakeday should happen a full year after registration and not on the date of registration?

![image](https://user-images.githubusercontent.com/38543836/87202981-ef931980-c301-11ea-953d-2ed9fca68aae.png)

**Comment by Filip785** [comment]
Hmm, I made PR for this and intended it to work like this. 

If @dessalines agrees with your proposal I can submit another one to fix it.

**Comment by dessalines** [comment]
Hrm.... yeah its probably a good idea to do a check to make sure its not the same year as published. Its a one-line fix, you got it @Filip785 ?
