### ISSUE TITLE
Frontend component updates result in duplicate websocket requests

### ISSUE THREAD

**Issue by masterstur** [LemmyNet/lemmy#935]
### Issue Summary

Frontend components that use `componentWillReceiveProps` that fetch data will result in duplicate web socket requests where the same fetch data function is called elsewhere in the component

### Steps to Reproduce

1. Load up a Lemmy instance & sign in
2. Open chrome/ff dev tools and monitor the console output or network logs
3. Navigate to the User panel
4. Switch between User views, "comments", "posts", etc
5. Any view switch results in duplicate data fetches

(This should replicate for any page using `componentWillReceiveProps` beyond the initial load that fetches data.  The main page switching to comments tab also replicates)

### Technical details

Attached images of duplicated requests and database query logs showing the duplicate queries.  To my knowledge this would effect the User, Search, Main, Community and, Communities components.  This seems to be caused because `componentWillReceiveProps` will fire off for every initiated re-render of the component and any underlying state/nav change that requires new data triggers a render via calling setState- So any `componentWillReceiveProps` that also makes a websocket requests ends up duplicating the one that just happened.

I started to look into fixing this in my fork, but the React docs state they plan to deprecate the problem function and the provided alternatives seemed to be a bad fit or required more refactoring effort than I'm comfortable with (I have little react experience)

![dupe_ws](https://user-images.githubusercontent.com/5491045/87211975-34ab5180-c2ea-11ea-80e9-8935a2044285.PNG)
![duped_queries](https://user-images.githubusercontent.com/5491045/87211980-38d76f00-c2ea-11ea-8664-b440a983b509.PNG)

**Comment by dessalines** [comment]
Good catch, I didn't notice this one. Let me know if you need any help with it.

**Comment by masterstur** [comment]
It does look like the easy answer is to remove the `fetch` calls from (mostly) everywhere and have only `componentWillReceiveProps` call it.  I could probably have that done pretty quick but at some point React will deprecate and remove that function and another solution will be needed

**Comment by dessalines** [comment]
This doesn't use react BTW, it uses inferno. but yes the fetch could probably be called on the handle methods instead. I have a comment there tho that it messes up with the back button, it'll need some testing.

**Comment by masterstur** [comment]
Yeah I was concerned though that since it's the component/lifecycle api that Inferno would match what React does for compatibility.  I can probably ask them what their plans are for this though.  I'm not a FE guy so it was hard to research up alternatives without being directed to the React docs 😅

**Comment by dessalines** [comment]
This is merged now #959 .
