### ISSUE TITLE
Consider disabling comment textarea autofocus when a post is opened

### ISSUE THREAD

**Issue by kartikynwa** [LemmyNet/lemmy#944]
### Issue Summary

When a post is opened, the comment textarea is focused automatically. On PC, it is no problem but on phone (Android Firefox Nightly), it pops out the keyboard which gets a bit annoying.

I tried doing it myself but `ui/src/components/comment-form.tsx` doesn't have an `autofocus` attribute anywhere so I don't know how to go about it.

**Comment by Nutomic** [comment]
Same here, on Firefox Android. Its pretty annoying.

**Comment by dessalines** [comment]
Ya my bad, I added this recently because I do think when you hit the reply button (for a reply comment) it should focus, but not on the main / first initial comment box. I'll fix this in a sec.
