### ISSUE TITLE
Can't connect to PostgreSQL 12 on MacOS Catlina

### ISSUE THREAD

**Issue by Axighi** [LemmyNet/lemmy#952]
I followed the Local Development instruction to set up the environment. Since I'm using Mac, I installed Postgres via official EDB package. When I ran `cargo run`, the error below shows up: 
```
    Finished dev [unoptimized + debuginfo] target(s) in 1.08s
     Running `target/debug/lemmy_server`
Error: LemmyError { inner: QueryError(DatabaseError(__Unknown, "could not load library 
\"/Library/PostgreSQL/12/lib/postgresql/llvmjit.so\": dlopen(/Library/PostgreSQL/12/lib/postgresql/llvmjit.so, 10): Library not 
loaded: @loader_path/../..//opt/local/lib/libncurses.6.dylib\n  Referenced from: 
/Library/PostgreSQL/12/lib/postgresql/llvmjit.so\n  Reason: no suitable image found.  Did find:\n\tfile system relative paths not
allowed in hardened programs")) }
```
I googled a lot but failed to figure it out. So I wish someone could help.

**Comment by dessalines** [comment]
I can't support the hundreds of possible different dev environments, I suggest just using the docker development until someone can figure out your mac osx issues.

**Comment by Axighi** [comment]
I solved this issue by starting a Docker Postgres instance. So I'll close this issue.
