### ISSUE TITLE
No way to login if you forget password, forgot password button is not clickable

### ISSUE THREAD

**Issue by elonmusksama** [LemmyNet/lemmy#955]
### Issue Summary

When logging in, if you forget password and try to click the **forgot password** button, it does not do anything.

### Steps to Reproduce

1. click login and press forgot password button

**Comment by dessalines** [comment]
Did you put in your email to the form?

**Comment by elonmusksama** [comment]
Yes. ill try with the new account i made and check to see if that works

**Comment by elonmusksama** [comment]
hmm it seems to have worked, maybe something on my end that made it not clickable. sorry for the bother lol

**Comment by elonmusksama** [comment]
no clue why it wasn't working before

**Comment by dessalines** [comment]
Still, I think I'm just gonna hide that password reset button until you have a valid email in the field. Otherwise someone else will ask why the button isn't working.

**Comment by elonmusksama** [comment]
Yeah that would be much more intuitive

**Comment by elonmusksama** [comment]
i didn't know you could make accounts without an email tho, isn't that risky, maybe add an email verification before actually allowing the account to post.

**Comment by dessalines** [comment]
I don't want to force email signups, even tho it does risk losing the account bc they haven't provided an email backup. Maybe some kind of indicator next to the email field would be good.

**Comment by elonmusksama** [comment]
A big red button that no one can miss would work wonders lol

**Comment by elonmusksama** [comment]
to confirm the creation of an account and that if they lose the password, recovery is impossible without an email
