### ISSUE TITLE
Restoring permanently deleted content through a backup

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [LemmyNet/lemmy#962]
I remember reading that there’s always a backup of a Lemmy community stored somewhere. We had an issue several months ago when a community was down, but the data saved themselves every twenty‐four hours or so, so you used those data as the replacement. Since we lost a few posts, you abbreviated the server’s saving schedule.

If you have a backup dating from two or or more days ago, somebody might be able to extract the content from that and reintegrate it into the current version. Does such a backup exist? Could we make it exist?

**Comment by Nutomic** [comment]
We have hourly backups of all the data. But I'm not sure if we could extract data of a specific user and put it back in the production database. However, its possible that the data is still saved in the database, and just the restore functionality is not working.

**Comment by Nutomic** [comment]
It looks like you permanently deleted all your posts and comments. Restoring an individual user from a backup would need a lot of work and testing, definitely not worth the effort. But we can reactivate your account so that you can use it again.

**Comment by Anarcho-Bolshevik** [comment]
I’m afraid that I am uninterested in reusing my account (at least for the time being). I posted some useful content with it and I anticipated the ‘delete account’ option to simply unmake my account rather than erase all of my posts, which was unintentional on my part and I found it excessive. I could offer my assistance if restoration is more a matter of patience than ingenuity, but if it would be a massive project requiring lots of people or a great deal of skill then I wouldn’t worry about it.

**Comment by Nutomic** [comment]
Its really not easy, and there is a chance that doing this would break the server. Besides, the error message makes it very clear that this is permanent.

![Screenshot_20200714_134506](https://user-images.githubusercontent.com/1044450/87422087-880df000-c5c7-11ea-9e20-414ea198e17f.png)

**Comment by Anarcho-Bolshevik** [comment]
All right, don’t worry about it, then.
