### ISSUE TITLE
Unable to login on Firefox for iOS

### ISSUE THREAD

**Issue by sseneca** [LemmyNet/lemmy#969]
### Issue Summary

After pressing "Login", it loads forever but doesn't log in. I've tried turning off tracking protection etc. but it doesn't help. Works with iOS Safari though.

### Steps to Reproduce

1.  I clicked login, and an endless spinner shows up.

### Technical details

iOS 13.5

Firefox version 27.0

**Comment by dessalines** [comment]
Version at the bottom? 

Really tough to do this one with no logs or anything.

**Comment by sseneca** [comment]
Sorry, I should have mentioned that this is on the main lemmy instance https://dev.lemmy.ml, not my own, so I don't have logs to attach. This has been happening for a while, before the current version 0.7.20 (I have never been able to log in with iOS Firefox, and have tried a few times for the past couple weeks).

**Comment by dessalines** [comment]
The browser console logs would be most helpful, but I realize that's probably impossible on mobile. I can't think of a way I can test this because I don't have an iphone. You could try clearing cookies?

Any FF addons enabled? Since it works on other browsers on your phone, its not a network issue.

**Comment by sseneca** [comment]
Clearing cookies doesn't seem to work. And Firefox on iOS can't install addons (as far as I know), Apple wouldn't allow it :/

I just tried on Firefox Focus and DuckDuckGo's own app, and it doesn't work there either. It's probably worth somebody trying it out on Chrome for iOS, too.

**Comment by rfwatson** [comment]
Tested this on Firefox 27, iOS 13.5.1 (iPad) - logging in seemed to work fine fwiw.

**Comment by dessalines** [comment]
@sseneca Did you try it on another browser on your device? I'd thought you did.

**Comment by sseneca** [comment]
yeah, I tried it on Safari, the normal Firefox app, Firefox Focus, and DuckDuckGo. Safari was the only one where it logged me in.

**Comment by dessalines** [comment]
I'd need somebody with an iphone to help out with this, because I don't have one, and without browser logs, I can't see what's going on.

**Comment by yehia2amer** [comment]
I just tried to login and it’s working fine on firefox on ios & safari !
All iOS browsers are forced to use Webkit, so all of them should behave the same.
———
I am using iOS 14 Public beta so I don’t know if it is an apple related issue on older iOS versions.

**Comment by eiknat** [comment]
someone in our discord was able to reproduce on Firefox 27, iOS 13.6. safari works fine. looking into debugging options.

**Comment by dessalines** [comment]
Ah, so that's why its happening on multiple browsers, but not all on ios. They all have to use webkit. I guess this means for ios the browser is less relevant than whatever webkit is installed. I'm not sure if the iOS version will be all that relevant either.

**Comment by eiknat** [comment]
@dessalines potentially worth checking the info for that user on the db? possible somehow it could be a URL issue like the one we just fixed with #990 . if so, the URL would need to be fixed manually since it's already inserted.

not sure why it wouldn't affect anyone else, but could potentially be an odd URL format that works outside of webkit

**Comment by dessalines** [comment]
Maybe, but it'd probably be easier for them to just try and make a new account. Plus #990 was only a problem if they somehow spoofed the front end to disable that form validation.

**Comment by sseneca** [comment]
I've tried this with two different accounts and it happens with both :thinking:

**Comment by PorkrollPosadist** [comment]
I just built and set up an local instance of Lemmy from HEAD (617d63643258b481df60e1472bdb14afec764813), created an ordinary user account, and tried to log in using Firefox, Chrome, and Firefox focus.  I was hoping to reproduce the bug and capture some debug information from the server side, but "unfortunately" everything seemed to work.

Software versions:

Firefox: 27.0 (18428)
Firefox Focus: 8.1.4
Chrome: 84.0.4147.71
iOS: 13.5.1
Device: iPhone X
Model Number: MQCP2LL/A

**Comment by sseneca** [comment]
I just tried logging in to dev.lemmy.ml again with a different account and for the first time that worked, but then when I restarted Firefox Focus I started having the same issues with either account I tried. I have not been able to figure out how to make this reproducible or consistent rn, and this has made me less sure because I didn't change anything between restarting the browser

**Comment by dessalines** [comment]
No idea, as I don't have any console logs. You say you can't make a new account and log into it on dev.lemmy.ml either?

**Comment by sseneca** [comment]
I have two accounts and cannot log in with either.

I just tried making a third account and it logged in fine. Logging out and logging back in also worked fine. Logging in with another browser also worked. But then trying to log in with my normal account still did not work.

**Comment by dessalines** [comment]
And you've tried logging into those accounts on desktop, and it works fine?

**Comment by sseneca** [comment]
yes, all accounts work on desktop

**Comment by eiknat** [comment]
does this still happen with the new frontend? a few people were able to reproduce and it seems this is related to autofilling the field.

**Comment by sseneca** [comment]
Logging in is working again for me, so I’m going to close this. Feel free to re-open if people are still having this problem.

iOS 14.2
FF version 29.1
dev.lemmy.ml v0.8.2

**Comment by dessalines** [comment]
It must've been the websocket timeout in the front-end then, which I tweaked in v0.8.2. Another person commented that their forever loading circles have stopped too . Sorry about that.

**Comment by eiknat** [comment]
> 
> 
> It must've been the websocket timeout in the front-end then, which I tweaked in v0.8.2. Another person commented that their forever loading circles have stopped too . Sorry about that.

our reproduction on this indicated it was related to auto-fill, so the password was filled in in the text box but the state wasn't actually set. it was sending the password to the API as null but the returned error wasn't in an expected format which was causing the infinite loading appearance:
```
[2020-11-03T20:30:22Z ERROR lemmy_server::websocket::handlers] Error during message handling missing field `password` at line 1 column 34
```

though it appears to be fixed with the FE updates, we might want to check for bugs with other auto-fill things like comment text boxes for add-ons like grammarly which is heavily used for accessibility reasons by non-english speakers.

**Comment by dessalines** [comment]
Hrm... I always assumed that if inferno's showing you that component, that its already done all the lifecycle hooks necessary. The only thing I can think of is to add another null / empty check on the login submit.
