### ISSUE TITLE
Adding Markdown Editor when Creating New Post

### ISSUE THREAD

**Issue by yehia2amer** [LemmyNet/lemmy#977]
### Is your proposal related to a problem?

Creating a Post is one of the most important aspects that affect UX in a site like this one. but the current version lacks a Markdown Editor to simplify creating posts. which makes users in need to go to another tool to write the post and then past it in the site.

### Describe the solution you'd like

Adding Makdown Editor & Improve the UI. Maybe using a library like [StackExchange pagedown](https://github.com/StackExchange/pagedown) as a start.

### Describe alternatives you've considered

users Now need to go to another tool to write the post and then past it in the site, or memorize the Markdown commands.

### Additional context

Screenshots from Reddit and StackOverflow new post pages [here](https://imgur.com/a/4u1TDgo)

**Comment by dessalines** [comment]
I agree that we probably need one, but it has to be **very lightweight**, look clean, pure javascript, and work with existing things like our autocomplete fields.

It might even be worth someone building additional buttons directly into the UI, rather than using an external tool.

**Comment by yehia2amer** [comment]
Great to hear that.

I Agree, This is actually what StackExchange did in [pagedown](https://github.com/StackExchange/pagedown). The Problem is the latest commit was on 2017. and the Markdown.Editor.js is dependent on there own Converter.

**Comment by dessalines** [comment]
I'm working on this now, cause its fun to add.
