### ISSUE TITLE
Indicator of new comments since you've last looked at a post

### ISSUE THREAD

**Issue by PopeRigby** [LemmyNet/lemmy#980]
### Is your proposal related to a problem?

I'd like to be able to see how many new comments there are on a post since I've last looked at the comments on that post.

### Describe the solution you'd like

In parentheses, a plus icon with the number of new comments next to the the old comment count. Like this:

`11 (+2)`

Alternatively, in parentheses, the number of new comments plus the word new, next to the total comment count. Like this:

`11 (3 new)`

I'm by no means an expert on UI so feel free to tweak this how you see fit.

**Comment by dessalines** [comment]
I doubt I'll add this, because it would require me to keep track of either every comment that's been viewed by every user, or save aggregates of "comment_count_per_post" at specific times, and post access times for every user. Lemmy doesn't keep track of what you view, when you view it.

**Comment by ernestwisniewski** [comment]
Maybe something on client side. Cookies or localstorage can be used to store post visit timestamp and current number of comments.

**Comment by PopeRigby** [comment]
[Tildes](https://www.tildes.net) is able to do it. Maybe take a look at their code: https://gitlab.com/tildes/tildes

**Comment by dessalines** [comment]
Ya, it'd be easy to do client side, but I'm pretty against adding client-specific features like that, bc then any mobile clients wouldn't have that data, and have to re-create it on their own (which I think for reddit most don't for new comment counts).
