### ISSUE TITLE
[UX issue] "Name" vs. "Title" is confusing

### ISSUE THREAD

**Issue by 12people** [LemmyNet/lemmy#985]
![image](https://user-images.githubusercontent.com/7361228/87773711-d3243f00-c823-11ea-8970-e92ca205c3e9.png)

It's unclear what the fields "Name" and "Title" refer to — at first glance, they mean the same thing.

As a fix, I'd suggest:

1. Changing the terminology to make the difference clearer — e.g. "Name" and "Display name"
2. Adding clarifying information on the "Create community" page. For example, "Name – used as the identifier for the community, cannot be changed" and "Display name — shown as the title on the community's page"

**Comment by dessalines** [comment]
Mmm yeah, display name might be good.

**Comment by kolgza** [comment]
Perhaps change "Name" to "Community Handle"?

**Comment by dessalines** [comment]
This is done.
