### ISSUE TITLE
Add user bios

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy#992]
We have a column in the DB for user bios, just haven't implemented it on the API side, or the front end yet.

**Comment by Axighi** [comment]
How do we plan to display and edit user bios?

**Comment by dessalines** [comment]
Editing them from your user settings, displaying them everywhere in place of your username (except mentions / anywhere where the real URL is required.)

**Comment by Nutomic** [comment]
So this is about displayname then, not a user description or such.

**Comment by dessalines** [comment]
Oh whoops lol, wrong ticket... I think its cause I just added some points to that #1017 .

Ya user bios just displayed on your user details page, and editable from the settings sidebar there.

**Comment by Axighi** [comment]
Done in pr #1043.

**Comment by Nutomic** [comment]
FYI you can just put `(fixes #1043)` at the end of your commit message, so it will reference and close the issue automatically.
