### ISSUE TITLE
Receiving notification discards comment being made

### ISSUE THREAD

**Issue by Permafacture** [LemmyNet/lemmy#995]
### Issue Summary

Receiving a notification (like if someone responded to a comment of yours) opens a popup.  I was typing a comment on a post and it suddenly disappeared while I was typing. I'm pretty sure receiving a notification of a comment response on a different post caused this.

### Steps to Reproduce

1. sign in
2. open a post
3. click the reply button on a comment (this opens up a text box under the comment)
4. start typing a reply
5. (untested) have a friend reply to another comment of yours so that you'd get a notification
6. comment box from step 4 disappears

### Technical details

My experience was on chrome 84.0.4147.89 on an android phone

**Comment by dessalines** [comment]
This will be fixed by #997

**Comment by Scaledi** [comment]
Thought this was just me! thanks for the fix!
